# Generated by Django 4.2.11 on 2025-06-13 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0007_postgresql_is_training_score_fix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practitioner',
            name='family_emergency_contact',
            field=models.CharField(blank=True, help_text="Contact d'urgence si différent du responsable familial", max_length=200, null=True, verbose_name="Contact d'urgence familial"),
        ),
        migrations.AlterField(
            model_name='practitioner',
            name='family_role',
            field=models.CharField(blank=True, choices=[('parent', 'Parent'), ('guardian', 'Tuteur légal'), ('child', 'Enfant'), ('spouse', 'Conjoint(e)'), ('sibling', 'Frère/Sœur'), ('other', 'Autre')], help_text='Rôle de ce pratiquant dans sa famille', max_length=20, null=True, verbose_name='Rôle familial'),
        ),
    ]
