# Generated by Django 5.1.6 on 2025-08-11 19:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('competitions', '0005_exam_alter_notification_created_at_and_more'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('board_type', models.CharField(choices=[('general', 'Général'), ('competition', 'Compétition'), ('training', 'Entraînement'), ('federation', 'Fédération'), ('club', 'Club'), ('event', 'Événement')], default='general', max_length=20, verbose_name='Type de tableau')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('is_template', models.BooleanField(default=False, verbose_name='Est un template')),
                ('is_archived', models.BooleanField(default=False, verbose_name='Archivé')),
                ('color_theme', models.CharField(default='blue', max_length=20, verbose_name='Thème de couleur')),
                ('is_public', models.BooleanField(default=False, verbose_name="Public dans l'organisation")),
                ('allowed_roles', models.JSONField(default=list, help_text="Liste des rôles d'organisation autorisés à accéder au board", verbose_name='Rôles autorisés')),
                ('enable_time_tracking', models.BooleanField(default=True, verbose_name='Suivi du temps activé')),
                ('enable_comments', models.BooleanField(default=True, verbose_name='Commentaires activés')),
                ('enable_attachments', models.BooleanField(default=True, verbose_name='Pièces jointes activées')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_boards', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boards', to='organizations.organization', verbose_name='Organisation')),
                ('related_competition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='boards', to='competitions.competition', verbose_name='Compétition associée')),
            ],
            options={
                'verbose_name': 'Tableau Kanban',
                'verbose_name_plural': 'Tableaux Kanban',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BoardTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('description', models.TextField(verbose_name='Description')),
                ('board_type', models.CharField(choices=[('general', 'Général'), ('competition', 'Compétition'), ('training', 'Entraînement'), ('federation', 'Fédération'), ('club', 'Club'), ('event', 'Événement')], max_length=20, verbose_name='Type de tableau')),
                ('columns_config', models.JSONField(help_text='Configuration JSON des colonnes par défaut', verbose_name='Configuration des colonnes')),
                ('default_tasks', models.JSONField(default=list, help_text='Tâches prédéfinies à créer avec le template', verbose_name='Tâches par défaut')),
                ('is_system_template', models.BooleanField(default=False, verbose_name='Template système')),
                ('is_public', models.BooleanField(default=True, verbose_name='Public')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('usage_count', models.PositiveIntegerField(default=0, verbose_name="Nombre d'utilisations")),
                ('color_scheme', models.CharField(default='default', max_length=20, verbose_name='Schéma de couleurs')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='Icône')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
            ],
            options={
                'verbose_name': 'Template de tableau',
                'verbose_name_plural': 'Templates de tableaux',
                'ordering': ['-is_system_template', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('position', models.PositiveIntegerField(verbose_name='Position')),
                ('color', models.CharField(default='#6B7280', max_length=7, verbose_name='Couleur')),
                ('wip_limit', models.PositiveIntegerField(blank=True, help_text='Nombre maximum de tâches dans cette colonne', null=True, verbose_name='Limite WIP')),
                ('is_done_column', models.BooleanField(default=False, help_text='Les tâches dans cette colonne sont considérées comme terminées', verbose_name='Colonne de fin')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='task_management.board', verbose_name='Tableau')),
            ],
            options={
                'verbose_name': 'Colonne',
                'verbose_name_plural': 'Colonnes',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('priority', models.CharField(choices=[('low', 'Basse'), ('medium', 'Moyenne'), ('high', 'Haute'), ('urgent', 'Urgente')], default='medium', max_length=10, verbose_name='Priorité')),
                ('status', models.CharField(choices=[('todo', 'À faire'), ('in_progress', 'En cours'), ('in_review', 'En révision'), ('done', 'Terminé'), ('blocked', 'Bloqué')], default='todo', max_length=15, verbose_name='Statut')),
                ('due_date', models.DateTimeField(blank=True, null=True, verbose_name="Date d'échéance")),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='Date de début')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Terminé le')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='Position')),
                ('estimated_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Heures estimées')),
                ('time_spent', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Temps passé')),
                ('attachments', models.JSONField(default=list, help_text='URLs des fichiers attachés', verbose_name='Pièces jointes')),
                ('labels', models.JSONField(default=list, help_text='Tags et labels pour la catégorisation', verbose_name='Étiquettes')),
                ('custom_fields', models.JSONField(default=dict, help_text='Données contextuelles supplémentaires', verbose_name='Champs personnalisés')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='task_management.board', verbose_name='Tableau')),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='task_management.column', verbose_name='Colonne')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('parent_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='task_management.task', verbose_name='Tâche parent')),
            ],
            options={
                'verbose_name': 'Tâche',
                'verbose_name_plural': 'Tâches',
                'ordering': ['column__position', 'position', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='Assigné le')),
                ('role', models.CharField(choices=[('assignee', 'Assigné'), ('reviewer', 'Réviseur'), ('watcher', 'Observateur'), ('collaborator', 'Collaborateur')], default='assignee', max_length=15, verbose_name='Rôle')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('notify_on_updates', models.BooleanField(default=True, verbose_name='Notifier des mises à jour')),
                ('notify_on_comments', models.BooleanField(default=True, verbose_name='Notifier des commentaires')),
                ('notify_on_due_date', models.BooleanField(default=True, verbose_name="Notifier de l'échéance")),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments_made', to=settings.AUTH_USER_MODEL, verbose_name='Assigné par')),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Assigné')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='task_management.task', verbose_name='Tâche')),
            ],
            options={
                'verbose_name': 'Assignation de tâche',
                'verbose_name_plural': 'Assignations de tâches',
            },
        ),
        migrations.CreateModel(
            name='TaskComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Contenu')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('is_edited', models.BooleanField(default=False, verbose_name='Modifié')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Auteur')),
                ('parent_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='task_management.taskcomment', verbose_name='Commentaire parent')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='task_management.task', verbose_name='Tâche')),
            ],
            options={
                'verbose_name': 'Commentaire',
                'verbose_name_plural': 'Commentaires',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='board',
            index=models.Index(fields=['organization', 'board_type'], name='task_manage_organiz_7e7d5b_idx'),
        ),
        migrations.AddIndex(
            model_name='board',
            index=models.Index(fields=['created_by'], name='task_manage_created_104c47_idx'),
        ),
        migrations.AddIndex(
            model_name='board',
            index=models.Index(fields=['is_archived', 'is_public'], name='task_manage_is_arch_2c40e8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='board',
            unique_together={('organization', 'name')},
        ),
        migrations.AddIndex(
            model_name='boardtemplate',
            index=models.Index(fields=['board_type', 'is_public'], name='task_manage_board_t_513061_idx'),
        ),
        migrations.AddIndex(
            model_name='boardtemplate',
            index=models.Index(fields=['is_system_template'], name='task_manage_is_syst_254443_idx'),
        ),
        migrations.AddIndex(
            model_name='column',
            index=models.Index(fields=['board', 'position'], name='task_manage_board_i_7440a4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='column',
            unique_together={('board', 'position')},
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['board', 'column'], name='task_manage_board_i_4880a8_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['created_by'], name='task_manage_created_614442_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['status', 'priority'], name='task_manage_status_fb609e_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['due_date'], name='task_manage_due_dat_9496a8_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['parent_task'], name='task_manage_parent__b60f1e_idx'),
        ),
        migrations.AddIndex(
            model_name='taskassignment',
            index=models.Index(fields=['task', 'is_active'], name='task_manage_task_id_261440_idx'),
        ),
        migrations.AddIndex(
            model_name='taskassignment',
            index=models.Index(fields=['assignee', 'is_active'], name='task_manage_assigne_21dffc_idx'),
        ),
        migrations.AddIndex(
            model_name='taskassignment',
            index=models.Index(fields=['assigned_at'], name='task_manage_assigne_854e53_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='taskassignment',
            unique_together={('task', 'assignee', 'role')},
        ),
        migrations.AddIndex(
            model_name='taskcomment',
            index=models.Index(fields=['task', 'created_at'], name='task_manage_task_id_6db1ba_idx'),
        ),
        migrations.AddIndex(
            model_name='taskcomment',
            index=models.Index(fields=['author'], name='task_manage_author__47708f_idx'),
        ),
    ]
