# Generated by Django 4.2.21 on 2025-07-31 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrganisateurNonMembre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_phone', models.CharField(blank=True, max_length=30)),
                ('statut_validation', models.CharField(default='en_attente', max_length=30)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
