@echo off
echo === NETTOYAGE ET RECREATION DES MIGRATIONS ===
echo.

echo 1. Deplacement des fichiers non-migration...
if exist multitenant\migrations\migrate_existing_clubs.py (
    move multitenant\migrations\migrate_existing_clubs.py multitenant\
    echo   - migrate_existing_clubs.py deplace
)

echo.
echo 2. Suppression des migrations problematiques...
if exist multitenant\migrations\__pycache__ (
    rmdir /s /q multitenant\migrations\__pycache__
    echo   - Cache supprime
)

echo.
echo 3. Creation d'une migration vide si necessaire...
if not exist multitenant\migrations\0001_initial.py (
    echo # Generated by Django > multitenant\migrations\0001_initial.py
    echo from django.db import migrations >> multitenant\migrations\0001_initial.py
    echo. >> multitenant\migrations\0001_initial.py
    echo class Migration(migrations.Migration): >> multitenant\migrations\0001_initial.py
    echo     initial = True >> multitenant\migrations\0001_initial.py
    echo     dependencies = [] >> multitenant\migrations\0001_initial.py
    echo     operations = [] >> multitenant\migrations\0001_initial.py
    echo   - Migration initiale creee
)

echo.
echo 4. Application des migrations...
python manage.py migrate multitenant

echo.
echo 5. Creation des migrations manquantes...
python manage.py makemigrations multitenant

echo.
echo 6. Application finale...
python manage.py migrate

echo.
echo === NETTOYAGE TERMINE ===
pause