#!/usr/bin/env python3
"""
Script pour corriger la migration 0008 problématique.
Crée une migration corrective qui vérifie l'existence des tables avant de les modifier.
"""

import os
import django
from django.conf import settings
from django.db import connection

# Configuration Django
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'config.settings')
django.setup()

def check_table_exists(table_name):
    """Vérifie si une table existe dans la base de données"""
    with connection.cursor() as cursor:
        cursor.execute("""
            SELECT EXISTS (
                SELECT 1 FROM information_schema.tables 
                WHERE table_schema = 'public' 
                AND table_name = %s
            )
        """, [table_name])
        return cursor.fetchone()[0]

def fix_migration_0008():
    """Marque la migration 0008 comme appliquée si nécessaire"""
    from django.db import migrations
    from django.db.migrations.recorder import MigrationRecorder
    
    print("🔍 Vérification des tables competitions...")
    
    # Tables que la migration 0008 essaie de supprimer
    tables_to_check = [
        'competitions_matchtimeslot',
        'competitions_categorysche',
        'competitions_competitionschedule',
        'competitions_schedulechange',
        'competitions_tatamischedule',
        'competitions_organizationtemplate'
    ]
    
    existing_tables = []
    missing_tables = []
    
    for table in tables_to_check:
        if check_table_exists(table):
            existing_tables.append(table)
            print(f"✅ Table trouvée: {table}")
        else:
            missing_tables.append(table)
            print(f"❌ Table manquante: {table}")
    
    if not existing_tables:
        print("✅ Aucune table à supprimer trouvée, les migrations peuvent continuer")
        return True
    
    print(f"\n⚠️ {len(existing_tables)} table(s) trouvée(s) qui pourraient causer des problèmes")
    
    # Vérifier l'état de la migration dans le registre
    recorder = MigrationRecorder(connection)
    try:
        applied_migrations = recorder.applied_migrations()
        migration_key = ('competitions', '0008_remove_matchtimeslot_category_schedule_and_more')
        
        if migration_key in applied_migrations:
            print("✅ Migration 0008 déjà marquée comme appliquée")
            print("🔧 Le problème pourrait être une base de données incohérente")
            
            # Proposer de supprimer manuellement les tables restantes
            print("\n💡 Solution recommandée: Supprimer les tables restantes manuellement")
            for table in existing_tables:
                print(f"   DROP TABLE IF EXISTS {table} CASCADE;")
            
        else:
            print("❌ Migration 0008 pas encore appliquée")
            
    except Exception as e:
        print(f"❌ Erreur lors de la vérification des migrations: {e}")
        return False
    
    return True

def create_safe_migration():
    """Crée une migration corrective qui vérifie l'existence des tables"""
    
    migration_content = '''# Generated by fix_migration_0008.py
from django.db import migrations, connection

def check_table_exists(table_name):
    """Vérifie si une table existe"""
    with connection.cursor() as cursor:
        cursor.execute("""
            SELECT EXISTS (
                SELECT 1 FROM information_schema.tables 
                WHERE table_schema = 'public' 
                AND table_name = %s
            )
        """, [table_name])
        return cursor.fetchone()[0]

def safe_remove_fields_and_tables(apps, schema_editor):
    """Supprime les champs et tables seulement s'ils existent"""
    
    tables_to_drop = [
        'competitions_matchtimeslot',
        'competitions_categorysche',
        'competitions_competitionschedule',
        'competitions_schedulechange', 
        'competitions_tatamischedule',
        'competitions_organizationtemplate'
    ]
    
    with connection.cursor() as cursor:
        for table in tables_to_drop:
            if check_table_exists(table):
                print(f"Suppression de la table: {table}")
                cursor.execute(f"DROP TABLE IF EXISTS {table} CASCADE")
            else:
                print(f"Table déjà supprimée: {table}")

def reverse_safe_remove(apps, schema_editor):
    """Opération inverse (ne fait rien car on ne peut pas recréer les tables)"""
    pass

class Migration(migrations.Migration):
    
    dependencies = [
        ('competitions', '0007_alter_clubqrcode_id_alter_organizationqrcode_club_and_more'),
    ]

    operations = [
        migrations.RunPython(safe_remove_fields_and_tables, reverse_safe_remove),
    ]
'''
    
    # Écrire la migration corrective
    migration_dir = "apps/competitions/migrations"
    migration_file = f"{migration_dir}/0008_safe_remove_schedule_models.py"
    
    os.makedirs(migration_dir, exist_ok=True)
    
    with open(migration_file, 'w', encoding='utf-8') as f:
        f.write(migration_content)
    
    print(f"✅ Migration corrective créée: {migration_file}")
    return True

def main():
    """Fonction principale"""
    print("🔧 Correctif pour la migration 0008 - MartialComp")
    print("=" * 50)
    
    try:
        # Vérifier l'état actuel
        if not fix_migration_0008():
            return 1
        
        print("\n📋 Solutions possibles:")
        print("1. Supprimer manuellement les tables restantes avec SQL")
        print("2. Marquer la migration comme appliquée: python manage.py migrate --fake competitions 0008")
        print("3. Revenir à la migration précédente: python manage.py migrate competitions 0007")
        print("4. Créer une migration corrective")
        
        response = input("\nVoulez-vous créer une migration corrective ? (y/N): ")
        if response.lower() == 'y':
            create_safe_migration()
        
        print("\n✅ Diagnostic terminé")
        return 0
        
    except Exception as e:
        print(f"❌ Erreur: {e}")
        return 1

if __name__ == "__main__":
    exit(main())