X XXXXXXXXXX XXXXXXX XXXXXX X XXXXXXXXXXXX XXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

X XXXX XXXX XXXXXXX XX XXXXXXXXX XXXXXX X XX X XXXXXXXXXX XX XXXXXXXXX XXXXXXX

X XXXXXX X XXXXXX XXXX XXXXXXXXXXX

XX XXXXXXXXXX XX XXXXXX XXXXXXX
   XXXXXX XXXXXXXXX XXXXX

XX XXXX XX XXXXX XXXXXXX XXXXXX XXXXX XXXXXXXXX
   XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

XX XXXXXXXXXX XXXXXXX
   XXXXXX XXXXXXXXX XXXXXXXXX

XX XX XXXXXXXXX XXXX XXXXXX XX XXXXXXXX XXX XXXXXXXX XX XXXXX

X XX XXX XX XXXXXX XXXXX
X XXXXXXX XX XXXXXX X XX XXXXXXXX XXXXXX XXX XXXX
X XXXXXXX XX XXXXXX X XX XXXXXX XXXX XX XXXXXXXX XXXXXX 
X XXXXXXX XXXXXXXXXXXXXXX XX XXXX X XXXXXXX
X XXXXX XX XXXXXXX XX XXXXXXXXX

X XXXXXXXX XX XXXXX X XXXXXXXXX
XXXXX XXXXXX XX XXXXXXXXX XXXX XXXXXX XXXX XX XXXXXXXX
X XXXXXXXXX XXXXXX X XXXXX XXXXXX
    XXXXXXXX XXXXXXXX XXXXXXX XX XXXX
    XXXXXXXXXX XXXXX XX XXXX
    XXXXXXXXXXXXX XXXXX XX XX XXXX XXXX

XX  XX XXXX XXXXXXXXXXX XX XXXXXXXXXXX XXXX XXXXX XXXXXXXXXX
XX  XX XXXXXXXXX XX XXXXXXXX XXXX XXXXXXXXX XXXXXXXXXX

X XXXXXXXX XXXXXXXX
XXXXXX XXXXXXX XXXX XXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

X XX XX XX XXXXXX XXXXXXXX XXXX
X XXXXXXXX XXX XXXXXXXX XX XXXXX XXXX XX XXXXXXX XXXXXX
X XX XXXXXX XXXX XXXX XXXXXXXXXX XX XXX XXXXXX XXXXXXXX XXXXX XXXXX
X XXXX XXX XXXXXXXXX XXXXXX XXXXXXXXXXXXX XX XXXXXXXX XXXXXXXXXXXXXXX