# -*- coding: utf-8 -*-
TRANSLATIONS = {
    "Les commandes peuvent être passées directement auprès du club. Contactez-nous pour plus d'informations sur les disponibilités et les tailles.": "Oda zinaweza kuwekwa moja kwa moja kwa klabu. Wasiliana nasi kwa taarifa zaidi kuhusu upatikanaji na vipimo.",
    "Item": "Bidhaa",
    "Les articles présentés sont indicatifs. Contactez le club pour connaître les produits disponibles et les tarifs actuels.": "Bidhaa zinazoonyeshwa ni za kuonyesha tu. Wasiliana na klabu kujua bidhaa zinazopatikana na bei za sasa.",
    "Contactez-nous pour connaître les disponibilités, les tailles ou pour passer commande.": "Wasiliana nasi kujua upatikanaji, vipimo au kuweka oda.",
    "Hello,": "Habari,",
    "I would like to order the following product:": "Ningependa kuagiza bidhaa ifuatayo:",
    "Please contact me for availability and order details.": "Tafadhali wasiliana nami kwa upatikanaji na maelezo ya oda.",
    "Best regards": "Salamu za heshima",
    "Erreur lors du démarrage du scanner. Veuillez vérifier que vous avez autorisé l\\'accès à la caméra.": "Hitilafu wakati wa kuanza skana. Tafadhali hakikisha umeruhusu ufikiaji wa kamera.",
    "Sélectionnez les disciplines pratiquées par votre organisation": "Chagua taaluma zinazofanywa na shirika lako",
    "discipline(s) sélectionnée(s)": "taaluma zilizochaguliwa",
    "Enregistrer les disciplines": "Hifadhi taaluma",
    "Test CSRF Login": "Jaribio la Kuingia CSRF",
    "Test CSRF Login Simple": "Jaribio Rahisi la Kuingia CSRF",
    "Password: ": "Nenosiri: ",
    "Login": "Ingia",
    "Une erreur s'est produite lors de la connexion avec votre compte social. Cela peut arriver pour plusieurs raisons.": "Hitilafu imetokea wakati wa kuunganisha na akaunti yako ya kijamii. Hii inaweza kutokea kwa sababu mbalimbali.",
    "Problème temporaire de connexion avec le service d'authentification.": "Tatizo la muda la muunganisho na huduma ya uthibitishaji.",
    "Si le problème persiste, contactez notre": "Ikiwa tatizo linaendelea, wasiliana na yetu",
    "Connectez-vous en un clic avec votre compte préféré pour accéder à MartialComp.": "Ingia kwa kubofya moja na akaunti yako unayoipenda kufikia MartialComp.",
    "Vos informations sont sécurisées. Nous n'avons jamais accès à vos mots de passe de réseaux sociaux.": "Taarifa zako ni salama. Hatupati kamwe ufikiaji wa nenosiri zako za mitandao ya kijamii.",
    "Plus qu'une étape pour rejoindre MartialComp !": "Hatua moja tu zaidi kujiunga na MartialComp!",
    "\n                        En créant un compte, vous acceptez nos <a href=\"#\">Conditions d'utilisation</a>\n                        et notre <a href=\"#\">Politique de confidentialité</a>.\n                        ": "\n                        Kwa kuunda akaunti, unakubali <a href=\"#\">Masharti ya Matumizi</a>\n                        yetu na <a href=\"#\">Sera yetu ya Faragha</a>.\n                        ",
    "Token CSRF: ": "Tokeni ya CSRF: ",
    "\n            Ceci est un test de traduction avec blocktrans.\n            La plateforme ultime de gestion des compétitions d'arts martiaux.\n        ": "\n            Hii ni jaribio la tafsiri na blocktrans.\n            Jukwaa la mwisho la usimamizi wa mashindano ya sanaa za kijeshi.\n        ",
    "%(days)d jours": "Siku %(days)d",
    "%(months)d mois": "Miezi %(months)d",
    "%(years)d an(s) et %(months)d mois": "Mwaka (miaka) %(years)d na miezi %(months)d",
    "%(years)d an(s)": "Mwaka (miaka) %(years)d",
    "Vous devez être responsable de club pour accéder à\xa0 cette page. Veuillez créer un club ou contacter un administrateur pour être associé à\xa0 un club existant.": "Lazima uwe msimamizi wa klabu kufikia ukurasa huu. Tafadhali unda klabu au wasiliana na msimamizi ili uhusishwe na klabu iliyopo.",
    "Le pratiquant doit avoir au moins 18 ans.": "Mtendaji lazima awe na angalau miaka 18.",
    "Ce pratiquant est déjà assigné comme {} pour cette compétition.": "Mtendaji huyu tayari amegawiwa kama {} kwa mashindano haya.",
    "Juge ad-hoc recruté avec succès.": "Hakimu wa dharura ameajiriwa kwa mafanikio.",
    "Pratiquant non trouvé.": "Mtendaji hakupatikana.",
    "Juge ad-hoc mis à jour.": "Hakimu wa dharura amesasishwa.",
    "Ce juge est déjà actif.": "Hakimu huyu tayari ni hai.",
    "Juge ad-hoc activé.": "Hakimu wa dharura amewashwa.",
    "Juge ad-hoc désactivé.": "Hakimu wa dharura amezimwa.",
    "Briefing marqué comme effectué.": "Mkutano umewekwa alama kuwa umefanyika.",
    "La note doit être entre 1 et 5.": "Alama lazima iwe kati ya 1 na 5.",
    "Évaluation enregistrée.": "Tathmini imerekodiwa.",
    "Note invalide.": "Alama batili.",
    "Seuls les juges en attente ou ayant décliné peuvent être supprimés.": "Waamuzi wanaosubiri au waliokataa peke yao wanaweza kufutwa.",
    "Juge ad-hoc {} supprimé.": "Hakimu wa dharura {} amefutwa.",
    "Catégorie manquante.": "Kategoria inakosekana.",
    "Juge affecté à la catégorie.": "Hakimu amegawiwa kwa kategoria.",
    "Ce juge est déjà affecté à cette catégorie.": "Hakimu huyu tayari amegawiwa kwa kategoria hii.",
    "Juge officiel affecté à la catégorie.": "Hakimu rasmi amegawiwa kwa kategoria.",
    "ID du juge manquant.": "Kitambulisho cha hakimu kinakosekana.",
    "Données manquantes.": "Data inakosekana.",
    "Juge retiré de la catégorie.": "Hakimu ameondolewa kutoka kategoria.",
    "Code PIN: %(pin)s - Partagez ce code avec les arbitres de cette aire.": "Msimbo wa PIN: %(pin)s - Shiriki msimbo huu na waamuzi wa eneo hili.",
    "Profil introuvable.": "Wasifu haupatikani.",
    "Aucune organisation associée à votre compte.": "Hakuna shirika linalohusiana na akaunti yako.",
    "Vous n'avez pas les permissions nécessaires pour modifier les disciplines de cette organisation.": "Huna ruhusa zinazohitajika kurekebisha taaluma za shirika hili.",
    "Les disciplines ont été mises à jour avec succès !": "Taaluma zimesasishwa kwa mafanikio!",
    "Une erreur est survenue lors de la mise à jour des disciplines.": "Hitilafu imetokea wakati wa kusasisha taaluma.",
    "Aucun type de compétition trouvé pour cette discipline.": "Hakuna aina ya mashindano iliyopatikana kwa taaluma hii.",
    "Erreur lors de l'ajout de la catégorie: {}": "Hitilafu wakati wa kuongeza kategoria: {}",
    "ID de la catégorie requis.": "Kitambulisho cha kategoria kinahitajika.",
    "Erreur lors de la suppression de la catégorie: {}": "Hitilafu wakati wa kufuta kategoria: {}",
    "Catégorie '{}' supprimée avec succès.": "Kategoria '{}' imefutwa kwa mafanikio.",
    "Vous n'avez pas les droits pour modifier cette compétition.": "Huna haki za kurekebisha mashindano haya.",
    "Impossible de supprimer cette catégorie car {} inscription(s) y sont liées.": "Haiwezekani kufuta kategoria hii kwa sababu usajili {} unahusiana nayo.",
    "Sans type": "Bila aina",
    "Statut juge technique attribué à {}": "Hali ya hakimu wa ufundi imegawiwa kwa {}",
    "Statut juge technique retiré de {}": "Hali ya hakimu wa ufundi imeondolewa kutoka {}",
    "Statut arbitre combat attribué à {}": "Hali ya mwamuzi wa mapigano imegawiwa kwa {}",
    "Statut arbitre combat retiré de {}": "Hali ya mwamuzi wa mapigano imeondolewa kutoka {}",
    "Rôle non reconnu.": "Jukumu halitambuliwi.",
    "Erreur: {}": "Hitilafu: {}",
    "Veuillez sélectionner au moins 2 catégories à fusionner.": "Tafadhali chagua angalau kategoria 2 za kuunganisha.",
    "Veuillez spécifier un nom pour la nouvelle catégorie ou une catégorie cible.": "Tafadhali bainisha jina la kategoria mpya au kategoria lengwa.",
    "Une ou plusieurs catégories n'ont pas été trouvées.": "Kategoria moja au zaidi hazijapatikana.",
    "Fusion réussie ! {} inscription(s) déplacée(s) vers la catégorie '{}'.": "Muungano umefanikiwa! Usajili {} umehamishwa kwenda kategoria '{}'.",
    "Erreur lors de la fusion des catégories: {}": "Hitilafu wakati wa kuunganisha kategoria: {}",
    "Catégorie '{}' divisée avec succès ! {} pratiquant(s) dans '{}', {} pratiquant(s) dans '{}'.": "Kategoria '{}' imegawanywa kwa mafanikio! Watendaji {} katika '{}', watendaji {} katika '{}'.",
    "Paramètres manquants: category_id et practitioner_id requis": "Vigezo vinakosekana: category_id na practitioner_id vinahitajika",
    "%(name)s a été retiré(e) de la catégorie '%(category)s'.": "%(name)s ameondolewa kutoka kategoria '%(category)s'.",
    "Données JSON invalides": "Data ya JSON batili",
    "Une erreur est survenue.": "Hitilafu imetokea.",
    "Demande de renouvellement envoyée pour la saison %(season)s.": "Ombi la kuhuisha limetumwa kwa msimu %(season)s.",
    "Renouveler l'affiliation - %(federation)s": "Huisha ushirika - %(federation)s",
    "Vous n'avez pas les permissions pour gérer cette compétition.": "Huna ruhusa za kusimamia mashindano haya.",
    "Inscription réussie ! Bienvenue dans le club {}.": "Usajili umefanikiwa! Karibu klabu {}.",
    "Erreur lors de l'inscription : {}": "Hitilafu wakati wa usajili: {}",
    "Inscription au Club": "Usajili wa Klabu",
    "Vous devez être responsable d'organisation pour accéder à cette interface.": "Lazima uwe msimamizi wa shirika kufikia kiolesura hiki.",
    "Configuration d'organisation requise pour organiser des événements.": "Usanidi wa shirika unahitajika kuandaa matukio.",
    "Trop d'inscriptions en attente": "Usajili mwingi sana unaosubiri",
    "Planification tardive": "Kupanga ratiba kuchelewa",
    "Colonne 'Date de naissance' non trouvée. En-têtes détectés: {}": "Safu wima 'Tarehe ya kuzaliwa' haikupatikana. Vichwa vilivyogunduliwa: {}",
    "Colonnes 'Nom' et/ou 'Prénom' non trouvées. En-têtes détectés: {}": "Safu wima 'Jina' na/au 'Jina la kwanza' hazijapatikana. Vichwa vilivyogunduliwa: {}",
    "Nom ou prénom manquant": "Jina au jina la kwanza linakosekana",
    "Format de date invalide ou non reconnu: {}": "Muundo wa tarehe batili au haujatambuliwa: {}",
    "Date de naissance invalide (type: {})": "Tarehe ya kuzaliwa batili (aina: {})",
    "Date de naissance manquante": "Tarehe ya kuzaliwa inakosekana",
    "Pratiquant déjà existant: {} {}": "Mtendaji tayari yupo: {} {}",
    "Erreur lors de la lecture du fichier: {}": "Hitilafu wakati wa kusoma faili: {}",
    "Aucun fichier n'a été sélectionné.": "Hakuna faili iliyochaguliwa.",
    "Format de fichier non supporté. Utilisez CSV ou Excel.": "Muundo wa faili hauafikiwi. Tumia CSV au Excel.",
    "Aucune organisation associée au club.": "Hakuna shirika linalohusiana na klabu.",
    "{} pratiquants importés avec succès. {} erreurs.": "Watendaji {} wameagizwa kwa mafanikio. Hitilafu {}.",
    "Aucun pratiquant n'a pu être importé. {} erreurs.": "Hakuna mtendaji aliyeweza kuagizwa. Hitilafu {}.",
    "Aucun club associé à votre compte.": "Hakuna klabu inayohusiana na akaunti yako.",
    "{} pratiquants importés avec succès.": "Watendaji {} wameagizwa kwa mafanikio.",
    "{} lignes n'ont pas pu être importées.": "Mistari {} haijaweza kuagizwa.",
    "Vous n'êtes associé à aucun club. Contactez un administrateur.": "Huhusishwi na klabu yoyote. Wasiliana na msimamizi.",
    "Vous n'avez pas l'autorisation de voir cette page.": "Huna ruhusa ya kuona ukurasa huu.",
    "Une erreur est survenue lors du chargement de la page.": "Hitilafu imetokea wakati wa kupakia ukurasa.",
    "Erreur lors de l'export des données.": "Hitilafu wakati wa kusafirisha data.",
    "Pratiquant introuvable.": "Mtendaji hakupatikani.",
    "Vous n'avez pas l'autorisation de voir ce pratiquant.": "Huna ruhusa ya kuona mtendaji huyu.",
    "Erreur lors du chargement du profil.": "Hitilafu wakati wa kupakia wasifu.",
    "Vous n'êtes associé à aucune organisation. Contactez un administrateur.": "Huhusishwi na shirika lolote. Wasiliana na msimamizi.",
    "Vous n'avez pas l'autorisation de créer un pratiquant. Contactez un administrateur.": "Huna ruhusa ya kuunda mtendaji. Wasiliana na msimamizi.",
    "Ajouter un Pratiquant": "Ongeza Mtendaji",
    "Vous n'avez pas l'autorisation de modifier ce pratiquant.": "Huna ruhusa ya kurekebisha mtendaji huyu.",
    "Club non trouvé": "Klabu haikupatikana",
    "Vous n'êtes associé à aucune organisation.": "Huhusishwi na shirika lolote.",
    "Ce pratiquant possède déjà un profil Juge/Arbitre.": "Mtendaji huyu tayari ana wasifu wa Hakimu/Mwamuzi.",
    "Le rôle Juge/Arbitre a été attribué avec succès à {}.": "Jukumu la Hakimu/Mwamuzi limegawiwa kwa mafanikio kwa {}.",
    "Erreur lors de l'attribution du rôle: {}": "Hitilafu wakati wa kugawa jukumu: {}",
    "Vous n'êtes associé à aucun club.": "Huhusishwi na klabu yoyote.",
    "Permission refusée": "Ruhusa imekataliwa",
    "Ce pratiquant a déjà un compte utilisateur associé.": "Mtendaji huyu tayari ana akaunti ya mtumiaji inayohusiana.",
    "Compte créé avec succès ! Un email avec les identifiants a été envoyé à {email}": "Akaunti imeundwa kwa mafanikio! Barua pepe na vitambulisho imetumwa kwa {email}",
    "Compte créé avec succès ! Nom d'utilisateur : {username} - Mot de passe : {password}": "Akaunti imeundwa kwa mafanikio! Jina la mtumiaji: {username} - Nenosiri: {password}",
    "Créer un compte pour {name}": "Unda akaunti kwa {name}",
    "Erreur lors de l'accès à cette page.": "Hitilafu wakati wa kufikia ukurasa huu.",
    "Cet utilisateur est déjà associé à {name}.": "Mtumiaji huyu tayari amehusishwa na {name}.",
    "L'utilisateur {username} a été associé avec succès à {name}.": "Mtumiaji {username} amehusishwa kwa mafanikio na {name}.",
    "Utilisateur introuvable.": "Mtumiaji hakupatikani.",
    "Veuillez sélectionner un utilisateur.": "Tafadhali chagua mtumiaji.",
    "Associer un compte à {name}": "Husisha akaunti na {name}",
    "La qualification a été ajoutée avec succès.": "Sifa imeongezwa kwa mafanikio.",
    "Erreur lors de l'ajout de la qualification.": "Hitilafu wakati wa kuongeza sifa.",
    "Fonctionnalité en cours de développement.": "Kipengele kinaendelezwa.",
    "Vous n'avez pas l'autorisation d'accéder à ces données.": "Huna ruhusa ya kufikia data hizi.",
    "Une erreur est survenue lors de la recherche.": "Hitilafu imetokea wakati wa kutafuta.",
    "Poussins (<10 ans)": "Watoto (<miaka 10)",
    "Benjamins (10-11 ans)": "Watoto wadogo (miaka 10-11)",
    "Minimes (12-13 ans)": "Wadogo (miaka 12-13)",
    "Cadets (14-15 ans)": "Vijana wadogo (miaka 14-15)",
    "Juniors (16-17 ans)": "Vijana (miaka 16-17)",
    "Seniors (18-34 ans)": "Wakubwa (miaka 18-34)",
    "Vétérans (35+ ans)": "Wakongwe (miaka 35+)",
    "Suspendus": "Wamesimamishwa",
    "Archivés": "Wamehifadhiwa",
    "Avec licence": "Na leseni",
    "Sans licence": "Bila leseni",
    "Avec compte": "Na akaunti",
    "Vous n'avez pas l'autorisation d'effectuer cette action.": "Huna ruhusa ya kufanya kitendo hiki.",
    "Le montant est requis.": "Kiasi kinahitajika.",
    "Montant invalide.": "Kiasi batili.",
    "Paiement enregistré avec succès.": "Malipo yamerekodiwa kwa mafanikio.",
    "Erreur lors de l'enregistrement du paiement.": "Hitilafu wakati wa kurekodi malipo.",
    "Ce pratiquant n'a pas d'adresse email.": "Mtendaji huyu hana anwani ya barua pepe.",
    "Rappel envoyé avec succès à {email}.": "Ukumbusho umetumwa kwa mafanikio kwa {email}.",
    "Erreur lors de l'envoi du rappel.": "Hitilafu wakati wa kutuma ukumbusho.",
    "Compte utilisateur créé avec succès pour {}. Identifiants: Nom d'utilisateur: {}, Mot de passe temporaire: {}": "Akaunti ya mtumiaji imeundwa kwa mafanikio kwa {}. Vitambulisho: Jina la mtumiaji: {}, Nenosiri la muda: {}",
    "Ajouter qualification": "Ongeza sifa",
    "Inscriptions du pratiquant": "Usajili wa mtendaji",
    "Ce pratiquant est déjà inscrit à cette compétition.": "Mtendaji huyu tayari amesajiliwa kwa mashindano haya.",
    "Inscription créée avec succès!": "Usajili umeundwa kwa mafanikio!",
    "Une erreur est survenue lors de la création de l'inscription.": "Hitilafu imetokea wakati wa kuunda usajili.",
    "Erreur lors du chargement des compétitions.": "Hitilafu wakati wa kupakia mashindano.",
    "Format de date invalide.": "Muundo wa tarehe batili.",
    "Profil mis à jour avec succès.": "Wasifu umesasishwa kwa mafanikio.",
    "Une erreur est survenue lors de la mise à jour: {}": "Hitilafu imetokea wakati wa kusasisha: {}",
    "Vous n'avez pas les permissions pour accéder à ce club.": "Huna ruhusa za kufikia klabu hii.",
    "QR Codes du Club": "QR Code za Klabu",
    "Statistiques QR Codes": "Takwimu za QR Code",
    "Aucun juge ou arbitre n'a été trouvé dans votre club. Vous pouvez ajouter des qualifications à\xa0 vos pratiquants depuis leur profil.": "Hakuna hakimu au mwamuzi aliyepatikana katika klabu yako. Unaweza kuongeza sifa kwa watendaji wako kutoka wasifu wao.",
    "Erreur API catégories: {}": "Hitilafu ya API ya kategoria: {}",
    "{} pratiquant(s) inscrit(s) avec succès.": "Mtendaji (watendaji) {} wamesajiliwa kwa mafanikio.",
    "{} déjà inscrit(s) dans cette catégorie.": "{} tayari wamesajiliwa katika kategoria hii.",
    "Erreur inscription simple: {}": "Hitilafu ya usajili rahisi: {}",
    "Requête invalide.": "Ombi batili.",
    "Vous devez être responsable de club.": "Lazima uwe msimamizi wa klabu.",
    "Inscription non trouvée.": "Usajili haukupatikana.",
    "Pratiquant désinscrit complètement de la compétition.": "Mtendaji ameondolewa kabisa kutoka mashindano.",
    "Pratiquant désinscrit de la catégorie avec succès.": "Mtendaji ameondolewa kutoka kategoria kwa mafanikio.",
    "Erreur désinscription: {}": "Hitilafu ya kuondoa usajili: {}",
    "Erreur API compétitions disponibles: {}": "Hitilafu ya API ya mashindano yanayopatikana: {}",
    "Content-Type doit être application/json": "Content-Type lazima iwe application/json",
    "Erreur inscription pratiquant {}: {}": "Hitilafu ya usajili wa mtendaji {}: {}",
    "Format JSON invalide.": "Muundo wa JSON batili.",
    "Erreur inscription en masse: {}": "Hitilafu ya usajili wa wingi: {}",
    "Le nom de l'équipe est obligatoire.": "Jina la timu ni lazima.",
    "Une équipe avec ce nom existe déjà pour cette compétition.": "Timu yenye jina hili tayari ipo kwa mashindano haya.",
    "Équipe '{}' créée avec succès.": "Timu '{}' imeundwa kwa mafanikio.",
    "Une équipe avec ce nom existe déjà.": "Timu yenye jina hili tayari ipo.",
    "Équipe '{}' modifiée avec succès.": "Timu '{}' imerekebishwa kwa mafanikio.",
    "Équipe '{}' supprimée avec succès.": "Timu '{}' imefutwa kwa mafanikio.",
    "Pratiquant non spécifié.": "Mtendaji hajabainishwa.",
    "Ce pratiquant est déjà dans l'équipe.": "Mtendaji huyu tayari yuko katika timu.",
    "Membre ajouté à l'équipe.": "Mwanachama ameongezwa katika timu.",
    "{} retiré de l'équipe.": "{} ameondolewa kutoka timu.",
    "Membre mis à jour.": "Mwanachama amesasishwa.",
    "Ordre des membres mis à jour.": "Mpangilio wa wanachama umesasishwa.",
    "Équipe source non spécifiée.": "Timu chanzo haijabainishwa.",
    "Votre équipe est déjà complète.": "Timu yako tayari ni kamili.",
    "Vous ne pouvez pas fusionner avec votre propre équipe.": "Huwezi kuunganisha na timu yako mwenyewe.",
    "Cette équipe a déjà une demande de fusion en cours.": "Timu hii tayari ina ombi la muungano linaloendelea.",
    "Demande de fusion envoyée à {} ({}).": "Ombi la muungano limetumwa kwa {} ({}).",
    "Cette demande ne vous est pas destinée.": "Ombi hili si lako.",
    "Fusion acceptée! Nouvelle équipe '{}' créée.": "Muungano umekubaliwa! Timu mpya '{}' imeundwa.",
    "Demande de fusion refusée.": "Ombi la muungano limekataliwa.",
    "Demande de fusion annulée.": "Ombi la muungano limeghairiwa.",
    "Veuillez sélectionner 2 équipes à fusionner.": "Tafadhali chagua timu 2 za kuunganisha.",
    "Impossible de fusionner une équipe avec elle-même.": "Haiwezekani kuunganisha timu na yenyewe.",
    "Vous n'avez pas les droits sur ces équipes.": "Huna haki juu ya timu hizi.",
    "Équipe '{}' fusionnée avec '{}'. {} membre(s) transféré(s).": "Timu '{}' imeunganishwa na '{}'. Wanachama {} wamehamishwa.",
    "Données manquantes: date de naissance, disciplines ou nom requis": "Data inakosekana: tarehe ya kuzaliwa, taaluma au jina vinahitajika",
    "Votre demande d'affiliation à {} a été envoyée.": "Ombi lako la ushirika kwa {} limetumwa.",
    "Vous devez être associé à un club pour voir les programmes d'entraînement.": "Lazima uhusishwe na klabu ili kuona programu za mazoezi.",
    "Vous devez être associé à un club pour créer des programmes.": "Lazima uhusishwe na klabu ili kuunda programu.",
    "Le programme d'entraînement a été créé avec succès.": "Programu ya mazoezi imeundwa kwa mafanikio.",
    "Vous devez être associé à un club.": "Lazima uhusishwe na klabu.",
    "Le programme a été modifié avec succès.": "Programu imerekebishwa kwa mafanikio.",
    "Vous devez être associé à un club pour créer des créneaux.": "Lazima uhusishwe na klabu ili kuunda muda wa mazoezi.",
    "Le créneau d'entraînement a été créé avec succès.": "Muda wa mazoezi umeundwa kwa mafanikio.",
    "Aucune compétition disponible. Vous devez d'abord créer une compétition.": "Hakuna mashindano yanayopatikana. Lazima uunde mashindano kwanza.",
    "Impossible de créer une équipe : aucune compétition disponible.": "Haiwezekani kuunda timu: hakuna mashindano yanayopatikana.",
    "Vous devez sélectionner une compétition.": "Lazima uchague mashindano.",
    "Aucune poule ou compétition trouvée avec cet identifiant.": "Hakuna kundi au mashindano yaliyopatikana na kitambulisho hiki.",
    "Aucun type de compétition 'Combat' trouvé. Les compétitions techniques ne nécessitent pas de poules.": "Hakuna aina ya mashindano ya 'Mapigano' iliyopatikana. Mashindano ya ufundi hayahitaji makundi.",
    "Mode Standard (round-robin)": "Aina ya Kawaida (round-robin)",
    "{} poules créées dans {} catégories avec {} combats générés. {} - Types: {}": "Makundi {} yameundwa katika kategoria {} na mapigano {} yaliyozalishwa. {} - Aina: {}",
    "Les {} poule(s) de la catégorie '{}' et leurs combats ont été supprimés.": "Makundi {} ya kategoria '{}' na mapigano yake yamefutwa.",
    "La poule {} a encore {} combat(s) non terminé(s).": "Kundi {} bado lina mapigano {} ambayo hayajamalizika.",
    "Pas assez de qualifiés pour générer une phase finale.": "Waliostahiki hawatoshi kuzalisha awamu ya mwisho.",
    "Phase finale générée: {} avec {} combats.": "Awamu ya mwisho imezalishwa: {} na mapigano {}.",
    "Cette catégorie n'a qu'une seule poule. Pas de phase finale nécessaire.": "Kategoria hii ina kundi moja tu. Hakuna awamu ya mwisho inayohitajika.",
    "Il reste {} combat(s) non terminé(s) dans les poules éliminatoires de cette catégorie.": "Kuna mapigano {} ambayo hayajamalizika katika makundi ya kufutwa ya kategoria hii.",
    "Phase finale générée pour '{}': 2 demi-finales créées. La finale sera automatiquement peuplée après les demi-finales.": "Awamu ya mwisho imezalishwa kwa '{}': nusu fainali 2 zimeundwa. Fainali itajazwa kiotomatiki baada ya nusu fainali.",
    "Finale directe générée pour '{}': 1 combat créé.": "Fainali ya moja kwa moja imezalishwa kwa '{}': pigano 1 limeundwa.",
    "Combat de finale créé pour '{}': {} vs {}": "Pigano la fainali limeundwa kwa '{}': {} dhidi ya {}",
    "Fusion approuvée. Vous pouvez maintenant l'exécuter.": "Muungano umeidhinishwa. Sasa unaweza kuutekeleza.",
    "Fusion exécutée. Nouvelle équipe: {nom}": "Muungano umetekelezwa. Timu mpya: {nom}",
    "Mode de la catégorie '{category}' basculé vers {mode}.": "Aina ya kategoria '{category}' imebadilishwa kuwa {mode}.",
    "Catégorie non trouvée.": "Kategoria haikupatikana.",
    "Vous devez être connecté pour modifier cette compétition.": "Lazima uwe umeingia ili kurekebisha mashindano haya.",
    "ID du type de compétition requis.": "Kitambulisho cha aina ya mashindano kinahitajika.",
    "Le type de compétition doit appartenir à la même discipline que la compétition.": "Aina ya mashindano lazima iwe ya taaluma ile ile na mashindano.",
    "Type de compétition ajouté avec succès.": "Aina ya mashindano imeongezwa kwa mafanikio.",
    "Ce type de compétition est déjà associé à cette compétition.": "Aina hii ya mashindano tayari imehusishwa na mashindano haya.",
    "Erreur lors de l'ajout du type de compétition: {}": "Hitilafu wakati wa kuongeza aina ya mashindano: {}",
    "Type de compétition supprimé avec succès.": "Aina ya mashindano imefutwa kwa mafanikio.",
    "Erreur lors de la suppression du type de compétition: {}": "Hitilafu wakati wa kufuta aina ya mashindano: {}",
    "Le type de compétition est requis.": "Aina ya mashindano inahitajika.",
    "Le type de compétition sélectionné n'est pas associé à cette compétition.": "Aina ya mashindano iliyochaguliwa haihusishwi na mashindano haya.",
    "Le type de compétition sélectionné n'existe pas.": "Aina ya mashindano iliyochaguliwa haipo.",
    "Impossible de supprimer cette catégorie car {} inscription(s) y sont liées. Veuillez d'abord réassigner ou supprimer ces inscriptions.": "Haiwezekani kufuta kategoria hii kwa sababu usajili {} unahusiana nayo. Tafadhali gawa upya au ufute usajili huu kwanza.",
    "Ce type de compétition n'est pas associé à cette compétition": "Aina hii ya mashindano haihusishwi na mashindano haya",
    "Le pratiquant est déjà inscrit dans une catégorie de ce type": "Mtendaji tayari amesajiliwa katika kategoria ya aina hii",
    "Cette action nécessite une requête POST.": "Kitendo hiki kinahitaji ombi la POST.",
    "Cette action doit être effectuée via le bouton de publication sur la page de gestion.": "Kitendo hiki lazima kifanywe kupitia kitufe cha uchapishaji kwenye ukurasa wa usimamizi.",
    "Veuillez définir le lieu de la compétition avant de publier": "Tafadhali fafanua mahali pa mashindano kabla ya kuchapisha",
    "Veuillez créer au moins une catégorie avant de publier": "Tafadhali unda angalau kategoria moja kabla ya kuchapisha",
    "Veuillez saisir au moins 2 caractères": "Tafadhali ingiza angalau herufi 2",
    "Le type de compétition a été créé avec succès.": "Aina ya mashindano imeundwa kwa mafanikio.",
    "Créer un type de compétition": "Unda aina ya mashindano",
    "Le type de compétition a été modifié avec succès.": "Aina ya mashindano imerekebishwa kwa mafanikio.",
    "Modifier le type de compétition": "Rekebisha aina ya mashindano",
    "Le type de compétition a été supprimé avec succès.": "Aina ya mashindano imefutwa kwa mafanikio.",
    "Rôles": "Majukumu",
    "Votre club n'a pas encore de discipline assignée. Veuillez configurer les disciplines pour voir les compétitions disponibles.": "Klabu yako bado haina taaluma iliyogawiwa. Tafadhali sanidi taaluma kuona mashindano yanayopatikana.",
    "Données de démonstration affichées pour le développement. En production, configurez les organisations pour chaque club.": "Data ya maonyesho inaonyeshwa kwa maendeleo. Katika uzalishaji, sanidi mashirika kwa kila klabu.",
    "Import/Export - {}": "Uagizaji/Usafirishaji - {}",
    "Fonctionnalité d'import en cours de développement": "Kipengele cha uagizaji kinaendelezwa",
    "Certifications - {}": "Vyeti - {}",
    "Examens & Grades - {}": "Mitihani na Madaraja - {}",
    "Calendrier - {}": "Kalenda - {}",
    "Utilisez le formulaire ci-dessous pour créer une nouvelle compétition pour {}.": "Tumia fomu hapa chini kuunda mashindano mapya kwa {}.",
    "Vous n'avez pas les permissions pour accéder à cette fédération.": "Huna ruhusa za kufikia shirikisho hili.",
    "Demande marquée comme en cours d'examen.": "Ombi limewekwa alama kuwa linakaguliwa.",
    "Demande approuvée. Le certificat peut maintenant être émis.": "Ombi limeidhinishwa. Cheti sasa linaweza kutolewa.",
    "Certificat émis avec succès. Numéro: %(number)s": "Cheti kimetolewa kwa mafanikio. Nambari: %(number)s",
    "La génération PDF nécessite l'installation de ReportLab. Contactez l'administrateur.": "Kuzalisha PDF kunahitaji usakinishaji wa ReportLab. Wasiliana na msimamizi.",
    "Erreur lors du chargement de l'organisation {}: {}": "Hitilafu wakati wa kupakia shirika {}: {}",
    "Erreur lors de la récupération des compétitions à gérer: {}": "Hitilafu wakati wa kupata mashindano ya kusimamia: {}",
    "Erreur lors de la récupération des juges: {}": "Hitilafu wakati wa kupata waamuzi: {}",
    "Erreur lors de la récupération des qualifications: {}": "Hitilafu wakati wa kupata sifa: {}",
    "Erreur lors du tri par created_at: {}": "Hitilafu wakati wa kupanga kwa created_at: {}",
    "Erreur lors de la récupération de tous les pratiquants: {}": "Hitilafu wakati wa kupata watendaji wote: {}",
    "Erreur lors de la récupération des affectations: {}": "Hitilafu wakati wa kupata ugawaji: {}",
    "Erreur lors de la récupération des paiements récents: {}": "Hitilafu wakati wa kupata malipo ya hivi karibuni: {}",
    "Erreur lors de la récupération des données d'entraînement: {}": "Hitilafu wakati wa kupata data ya mazoezi: {}",
    "Erreur lors de la récupération des commandes: {}": "Hitilafu wakati wa kupata oda: {}",
    "Erreur lors de la récupération des notifications: {}": "Hitilafu wakati wa kupata arifa: {}",
    "Erreur lors de la récupération des tickets de support: {}": "Hitilafu wakati wa kupata tiketi za msaada: {}",
    "Erreur lors de la récupération des données financières: {}": "Hitilafu wakati wa kupata data za kifedha: {}",
    "Erreur lors de la récupération des événements: {}": "Hitilafu wakati wa kupata matukio: {}",
    "Erreur lors de la récupération des combats: {}": "Hitilafu wakati wa kupata mapigano: {}",
    "Erreur lors de la récupération des documents: {}": "Hitilafu wakati wa kupata hati: {}",
    "Erreur lors de la récupération des données d'adhésion: {}": "Hitilafu wakati wa kupata data za uanachama: {}",
    "Erreur lors de la récupération des données de tâches: {}": "Hitilafu wakati wa kupata data za kazi: {}",
    "Erreur lors du chargement de la compétition {}: {}": "Hitilafu wakati wa kupakia mashindano {}: {}",
}
