# -*- coding: utf-8 -*-
TRANSLATIONS = {
    "Première place - Champion": "Nafasi ya kwanza - Bingwa",
    "Benjamins": "Watoto wadogo",
    "Cadets": "Vijana wadogo",
    "Juniors": "Vijana",
    "Seniors": "Wakubwa",
    "L'équipe fusionnée aurait trop de membres ({total} > {max})": "Timu iliyounganishwa ingekuwa na wanachama wengi sana ({total} > {max})",
    "Impossible de défaire la fusion: des combats ont déjà eu lieu": "Haiwezekani kutengua muungano: mapigano tayari yamefanyika",
    "Fusion annulée (rollback)": "Muungano umeghairiwa (kurejeshwa)",
    "Felicitations! Vous remplissez maintenant toutes les conditions pour passer au grade %(grade)s. Consultez les prochains examens disponibles.": "Hongera! Sasa unatimiza masharti yote ya kupanda daraja %(grade)s. Angalia mitihani inayokuja inayopatikana.",
    "Plus que 7 jours avant eligibilite!": "Siku 7 tu kabla ya kustahiki!",
    "Dans 7 jours, vous serez eligible pour passer au grade %(grade)s. Preparez-vous et consultez les examens a venir.": "Katika siku 7, utastahiki kupanda daraja %(grade)s. Jitayarishe na uangalie mitihani inayokuja.",
    "Dans environ 30 jours, vous serez eligible pour passer au grade %(grade)s. C'est le moment de vous preparer.": "Katika takriban siku 30, utastahiki kupanda daraja %(grade)s. Ni wakati wa kujitayarisha.",
    "Derniere chance: Inscription examen dans 3 jours!": "Nafasi ya mwisho: Usajili wa mtihani katika siku 3!",
    "La date limite d'inscription pour l'examen '%(exam)s' est dans 3 jours. Inscrivez-vous maintenant pour ne pas manquer cette opportunite!": "Tarehe ya mwisho ya usajili kwa mtihani '%(exam)s' ni katika siku 3. Sajili sasa usikose fursa hii!",
    "L'examen '%(exam)s' a lieu le %(date)s. Vous avez encore 14 jours pour vous inscrire.": "Mtihani '%(exam)s' unafanyika %(date)s. Bado una siku 14 za kusajili.",
    "Rappel: Votre examen de grade est demain!": "Ukumbusho: Mtihani wako wa daraja ni kesho!",
    "L'examen '%(exam)s' a lieu demain %(date)s a %(location)s. Preparez-vous et arrivez a l'heure. Bonne chance!": "Mtihani '%(exam)s' unafanyika kesho %(date)s katika %(location)s. Jitayarishe na ufike kwa wakati. Bahati njema!",
    "Rappel: Vous etes eligible pour un passage de grade": "Ukumbusho: Unastahiki kupanda daraja",
    "Vous remplissez les conditions pour passer au grade %(grade)s mais vous n'etes inscrit a aucun examen. Consultez les examens disponibles!": "Unatimiza masharti ya kupanda daraja %(grade)s lakini hujasajiliwa kwa mtihani wowote. Angalia mitihani inayopatikana!",
    "Nous vous recommandons de changer ce mot de passe dès votre première connexion.": "Tunakupendekeza ubadilishe nenosiri hili wakati wa kuingia kwako kwa mara ya kwanza.",
    "Découvrez ce que vous pouvez faire avec MartialComp :": "Gundua unachoweza kufanya na MartialComp:",
    "Cet email a été envoyé automatiquement par MartialComp.": "Barua pepe hii imetumwa kiotomatiki na MartialComp.",
    "Vous avez demandé à associer cette adresse email à votre compte MartialComp.": "Umeomba kuunganisha anwani hii ya barua pepe na akaunti yako ya MartialComp.",
    "Si le bouton ne fonctionne pas, copiez et collez ce lien dans votre navigateur :": "Ikiwa kitufe hakifanyi kazi, nakili na ubandike kiungo hiki kwenye kivinjari chako:",
    "Si vous n'avez pas demandé cette confirmation, vous pouvez ignorer cet email en toute sécurité.": "Ikiwa haukuomba uthibitisho huu, unaweza kupuuza barua pepe hii kwa usalama.",
    "Pour confirmer que cette adresse email vous appartient, cliquez sur le lien ci-dessous :": "Ili kuthibitisha kuwa anwani hii ya barua pepe ni yako, bofya kiungo hapa chini:",
    "Vous avez demandé la réinitialisation de votre mot de passe sur": "Umeomba kuweka upya nenosiri lako kwenye",
    "Réinitialiser mon mot de passe": "Weka upya nenosiri langu",
    "Important :": "Muhimu:",
    "Ce lien est valable pendant": "Kiungo hiki kinatumika kwa",
    "Après ce délai, vous devrez refaire une demande de réinitialisation.": "Baada ya muda huu, utahitaji kufanya ombi jipya la kuweka upya.",
    "Si vous n'avez pas demandé cette réinitialisation, vous pouvez ignorer cet email. Votre mot de passe ne sera pas modifié.": "Ikiwa haukuomba kuweka upya hii, unaweza kupuuza barua pepe hii. Nenosiri lako halitabadilishwa.",
    "Vous avez demandé la réinitialisation de votre mot de passe sur MartialComp.": "Umeomba kuweka upya nenosiri lako kwenye MartialComp.",
    "Pour choisir un nouveau mot de passe, cliquez sur le lien suivant :": "Ili kuchagua nenosiri jipya, bofya kiungo kifuatacho:",
    "Ce lien est valable pendant 24 heures.": "Kiungo hiki kinatumika kwa masaa 24.",
    "Découvrez tout ce que vous pouvez faire avec MartialComp :": "Gundua yote unayoweza kufanya na MartialComp:",
    "Accédez à votre espace :": "Fikia eneo lako:",
    "Bienvenue sur MartialComp - Connexion via %(provider_display)s réussie": "Karibu MartialComp - Kuingia kupitia %(provider_display)s kumefanikiwa",
    "Veuillez confirmer que vous souhaitez utiliser cette adresse email pour votre compte MartialComp.": "Tafadhali thibitisha kuwa ungependa kutumia anwani hii ya barua pepe kwa akaunti yako ya MartialComp.",
    "Le lien de confirmation que vous avez utilisé n'est plus valide. Cela peut arriver si :": "Kiungo cha uthibitisho ulichotumia hakipo tena. Hii inaweza kutokea ikiwa:",
    "Le lien a été copié incorrectement": "Kiungo kimenakiliwa vibaya",
    "Pour votre sécurité, les liens de confirmation expirent après 3 jours.": "Kwa usalama wako, viungo vya uthibitisho vinaisha baada ya siku 3.",
    "Pas de panique, nous allons vous aider": "Usijali, tutakusaidia",
    "Entrez votre adresse email et nous vous enverrons un lien pour réinitialiser votre mot de passe.": "Ingiza anwani yako ya barua pepe na tutakutumia kiungo cha kuweka upya nenosiri lako.",
    "Si un compte existe avec cette adresse email, vous recevrez un lien pour réinitialiser votre mot de passe.": "Ikiwa akaunti ipo na anwani hii ya barua pepe, utapokea kiungo cha kuweka upya nenosiri lako.",
    "Vérifiez également vos dossiers spam ou courrier indésirable": "Angalia pia folda yako ya barua taka",
    "Le lien est valable pendant 24 heures": "Kiungo kinatumika kwa masaa 24",
    "Si vous ne recevez rien, vérifiez que l'adresse email est correcte": "Ikiwa hupokei chochote, hakikisha anwani ya barua pepe ni sahihi",
    "Le lien de réinitialisation a expiré ou a déjà été utilisé. Veuillez faire une nouvelle demande.": "Kiungo cha kuweka upya kimeisha muda au tayari kimetumika. Tafadhali fanya ombi jipya.",
    "Ne partagez jamais votre mot de passe avec quelqu'un": "Usishiriki nenosiri lako na mtu yeyote",
    "Utilisez un gestionnaire de mots de passe pour les stocker en sécurité": "Tumia kidhibiti cha nenosiri kuvihifadhi kwa usalama",
    "Activez l'authentification à deux facteurs si disponible": "Washa uthibitishaji wa hatua mbili ikiwa unapatikana",
    "Nous avons envoyé un email de vérification à votre adresse. Veuillez vérifier votre boîte de réception et cliquer sur le lien de confirmation.": "Tumetuma barua pepe ya uthibitishaji kwa anwani yako. Tafadhali angalia sanduku lako la barua na ubofye kiungo cha uthibitisho.",
    "Ouvrez votre boîte de réception email": "Fungua sanduku lako la barua pepe",
    "Vous ne trouvez pas l'email ? Pensez à vérifier votre dossier spam ou courrier indésirable.": "Hupati barua pepe? Fikiria kuangalia folda yako ya barua taka.",
    "Ex: Cadets -60kg": "Mfano: Vijana -60kg",
    "Âge min": "Umri wa chini",
    "Âge max": "Umri wa juu",
    "Poids min": "Uzito wa chini",
    "Poids max": "Uzito wa juu",
    "Ajoutez votre première catégorie en utilisant le formulaire ci-dessus.": "Ongeza kategoria yako ya kwanza kwa kutumia fomu hapo juu.",
    "Ajout en cours...": "Kuongeza kunaendelea...",
    "Erreur lors de la création de la catégorie": "Hitilafu wakati wa kuunda kategoria",
    "Erreur lors de la suppression de la catégorie": "Hitilafu wakati wa kufuta kategoria",
    "Hub de Gestion": "Kituo cha Usimamizi",
    "PUBLIÉE": "IMECHAPISHWA",
    "BROUILLON": "RASIMU",
    "Gestion Pro Complète": "Usimamizi Kamili wa Kitaalamu",
    "Interface avancée pour organisateurs expérimentés": "Kiolesura cha juu kwa waandaaji wenye uzoefu",
    "Dashboard de Gestion": "Dashibodi ya Usimamizi",
    "Vue d'ensemble avec statistiques en temps réel": "Muhtasari na takwimu za wakati halisi",
    "Vue d'Ensemble": "Muhtasari",
    "Tableau de bord complet de la compétition": "Dashibodi kamili ya mashindano",
    "Gérer les catégories de compétition": "Simamia kategoria za mashindano",
    "Gestion des officiels et qualifications": "Usimamizi wa maafisa na sifa",
    "Suivi Temps Réel": "Ufuatiliaji wa Wakati Halisi",
    "Monitoring live de la compétition": "Ufuatiliaji wa moja kwa moja wa mashindano",
    "Planning & Tatamis": "Kupanga na Tatami",
    "Organisation temporelle et spatiale": "Mpangilio wa wakati na nafasi",
    "Ordre de Passage": "Mpangilio wa Kupita",
    "Séquencement et ordre des épreuves": "Upangaji wa mfuatano na mpangilio wa mashindano",
    "Affecter Juges": "Gawa Waamuzi",
    "Attribution des juges aux tatamis": "Ugawaji wa waamuzi kwa tatami",
    "Publier Planning": "Chapisha Ratiba",
    "Rendre le planning public et accessible": "Fanya ratiba kuwa ya umma na kupatikana",
    "Lien Public": "Kiungo cha Umma",
    "Générer et partager l'URL publique": "Zalisha na shiriki URL ya umma",
    "Vue Spectateur": "Mtazamo wa Mtazamaji",
    "Aperçu de la page publique": "Onyesho la ukurasa wa umma",
    "Fiches Notation": "Karatasi za Alama",
    "Distribution des fiches aux juges": "Usambazaji wa karatasi kwa waamuzi",
    "À définir": "Itafafanuliwa",
    "Rechercher un type...": "Tafuta aina...",
    "Trier par nom": "Panga kwa jina",
    "Trier par nombre de catégories": "Panga kwa idadi ya kategoria",
    "Trier par date de création": "Panga kwa tarehe ya kuunda",
    "Types total": "Jumla ya aina",
    "Catégories total": "Jumla ya kategoria",
    "Moy. catégories/type": "Wastani kategoria/aina",
    "Types vides": "Aina tupu",
    "Chargement des types de compétition...": "Kupakia aina za mashindano...",
    "Erreur lors du chargement des types": "Hitilafu wakati wa kupakia aina",
    "Aucun type de compétition trouvé. Créez votre premier type pour organiser les catégories.": "Hakuna aina ya mashindano iliyopatikana. Unda aina yako ya kwanza ili kupanga kategoria.",
    "Modification en masse": "Marekebisho kwa wingi",
    "Suppression en masse": "Kufuta kwa wingi",
    "Trier par type": "Panga kwa aina",
    "Trier par genre": "Panga kwa jinsia",
    "Trier par âge": "Panga kwa umri",
    "Trier par inscriptions": "Panga kwa usajili",
    "Filtres avancés": "Vichujio vya juu",
    "Avec inscriptions seulement": "Na usajili peke yake",
    "Catégories vides seulement": "Kategoria tupu peke yake",
    "Avec inscriptions": "Na usajili",
    "Vides": "Tupu",
    "Moy./catégorie": "Wastani/kategoria",
    "Chargement des catégories...": "Kupakia kategoria...",
    "Erreur lors du chargement des catégories": "Hitilafu wakati wa kupakia kategoria",
    "Aucune catégorie trouvée. Créez votre première catégorie pour organiser les participants.": "Hakuna kategoria iliyopatikana. Unda kategoria yako ya kwanza ili kupanga washiriki.",
    "Pagination des catégories": "Upaginishaji wa kategoria",
    "Affectation des juges": "Ugawaji wa waamuzi",
    "Recruter un juge ad-hoc": "Ajiri hakimu wa dharura",
    "Juges Ad-Hoc (Temporaires)": "Waamuzi wa Dharura (Wa Muda)",
    "Recrutez des pratiquants adultes (18+) présents à la compétition pour servir comme juges temporaires.": "Ajiri watendaji watu wazima (18+) waliopo kwenye mashindano ili watumike kama waamuzi wa muda.",
    "Chargement des juges ad-hoc...": "Kupakia waamuzi wa dharura...",
    "Aucun juge ad-hoc recruté pour cette compétition.": "Hakuna hakimu wa dharura aliyeajiriwa kwa mashindano haya.",
    "Recruter mon premier juge ad-hoc": "Ajiri hakimu wangu wa kwanza wa dharura",
    "Affectations par zone": "Ugawaji kwa eneo",
    "Glisser un juge ici": "Buruta hakimu hapa",
    "Juges de coin": "Waamuzi wa kona",
    "Glisser jusqu'à 4 juges": "Buruta hadi waamuzi 4",
    "Pratiquants de la discipline": "Watendaji wa taaluma",
    "Configurer l'assignation": "Sanidi ugawaji",
    "Expérimenté": "Mwenye uzoefu",
    "Maintenez Ctrl pour sélectionner plusieurs catégories": "Shikilia Ctrl ili kuchagua kategoria nyingi",
    "Activer immédiatement (crée un compte si nécessaire)": "Washa mara moja (huunda akaunti ikiwa ni lazima)",
    "Recruter": "Ajiri",
    "Programmation des passages": "Kupanga ratiba ya vipindi",
    "Durée par passage (min)": "Muda kwa kipindi (dakika)",
    "Nombre de tatamis/aires": "Idadi ya tatami/maeneo",
    "Pause entre catégories (min)": "Pumziko kati ya kategoria (dakika)",
    "Catégories à programmer": "Kategoria za kupanga",
    "Planning des aires": "Ratiba ya maeneo",
    "Programmées": "Zimepangwa",
    "Dates définies": "Tarehe zimefafanuliwa",
    "Discipline définie": "Taaluma imefafanuliwa",
    "Copier le lien": "Nakili kiungo",
    "Résultats et notation": "Matokeo na alama",
    "Interfaces de notation": "Violesura vya alama",
    "Dashboard Juges": "Dashibodi ya Waamuzi",
    "Interface pour les juges assignés": "Kiolesura kwa waamuzi waliogawiwa",
    "Ouvrir": "Fungua",
    "Gestion Notation": "Usimamizi wa Alama",
    "Configurer les critères de notation": "Sanidi vigezo vya alama",
    "Résultats par catégorie": "Matokeo kwa kategoria",
    "Aucune catégorie n'a encore été créée. Créez des catégories pour accéder aux résultats.": "Hakuna kategoria iliyoundwa bado. Unda kategoria ili kufikia matokeo.",
    "État de la notation": "Hali ya alama",
    "Non notés": "Hazijaandikiwa alama",
    "Exporter tous les résultats": "Hamisha matokeo yote",
    "Imprimer certificats": "Chapisha vyeti",
    "Vue publique": "Mtazamo wa umma",
    "Suivi temps réel": "Ufuatiliaji wa wakati halisi",
    "Aucune performance en cours...": "Hakuna utendaji unaoendelea...",
    "Erreur affectation": "Hitilafu ya ugawaji",
    "Rejoignez-nous !": "Jiunge nasi!",
    "Lien copié dans le presse-papier !": "Kiungo kimenakiliwa kwenye ubao wa kunakili!",
    "Êtes-vous sûr de vouloir dépublier cette compétition ? Elle ne sera plus visible publiquement.": "Je, una uhakika unataka kuondoa uchapishaji wa mashindano haya? Hayataonekana tena hadharani.",
    "Compétition dépubliée avec succès": "Mashindano yameondolewa kwa mafanikio",
    "Erreur lors de la dépublication": "Hitilafu wakati wa kuondoa uchapishaji",
    "Option mise à jour": "Chaguo limesasishwa",
    "Erreur lors de la mise à jour": "Hitilafu wakati wa kusasisha",
    "Envoyer une notification à tous les participants inscrits ?": "Tuma arifa kwa washiriki wote waliosajiliwa?",
    "destinataires": "wapokeaji",
    "Erreur lors de envoi": "Hitilafu wakati wa kutuma",
    "Envoyer une notification à tous les juges assignés ?": "Tuma arifa kwa waamuzi wote waliogawiwa?",
    "Notifications envoyées aux juges": "Arifa zimetumwa kwa waamuzi",
    "non disponible": "haipatikani",
    "QR Code téléchargé": "QR Code imepakiwa",
    "Erreur lors du téléchargement": "Hitilafu wakati wa kupakia",
    "Chargement des résultats en temps réel...": "Kupakia matokeo kwa wakati halisi...",
    "Erreur lors du chargement des résultats": "Hitilafu wakati wa kupakia matokeo",
    "Aucune performance pour cette catégorie...": "Hakuna utendaji kwa kategoria hii...",
    "Préparation export en cours...": "Maandalizi ya usafirishaji yanaendelea...",
    "Fonction export en cours de développement": "Kazi ya usafirishaji inaendelezwa",
    "Préparation des certificats...": "Maandalizi ya vyeti...",
    "Fonction impression en cours de développement": "Kazi ya kuchapisha inaendelezwa",
    "Voulez-vous publier tous les résultats ? Ils seront visibles publiquement.": "Je, unataka kuchapisha matokeo yote? Yataonekana hadharani.",
    "Résultats publiés avec succès !": "Matokeo yamechapishwa kwa mafanikio!",
    "Êtes-vous sûr de vouloir supprimer cette inscription ? Cette action est irréversible.": "Je, una uhakika unataka kufuta usajili huu? Kitendo hiki hakiwezi kurejeshwa.",
    "Inscription supprimée avec succès": "Usajili umefutwa kwa mafanikio",
    "Erreur suppression inscription": "Hitilafu ya kufuta usajili",
    "Briefing": "Mkutano wa maelezo",
    "Compte actif": "Akaunti hai",
    "Marquer briefing effectué": "Weka alama mkutano umefanyika",
    "Décliné": "Imekataliwa",
    "Aucun pratiquant éligible (18+ ans)": "Hakuna mtendaji anayestahiki (miaka 18+)",
    "Compte existant": "Akaunti iliyopo",
    "Veuillez sélectionner un pratiquant": "Tafadhali chagua mtendaji",
    "Recrutement...": "Kuajiri...",
    "Juge ad-hoc recruté avec succès": "Hakimu wa dharura ameajiriwa kwa mafanikio",
    "Erreur lors du recrutement": "Hitilafu wakati wa kuajiri",
    "Activer ce juge ad-hoc ?": "Washa hakimu huyu wa dharura?",
    "Désactiver ce juge ad-hoc ?": "Zima hakimu huyu wa dharura?",
    "Supprimer ce juge ad-hoc ?": "Futa hakimu huyu wa dharura?",
    "Toutes les catégories sont programmées": "Kategoria zote zimepangwa",
    "Aire": "Eneo",
    "Glissez les catégories ici": "Buruta kategoria hapa",
    "Générer automatiquement le planning ? Cela remplacera la programmation actuelle.": "Zalisha ratiba kiotomatiki? Hii itabadilisha ratiba ya sasa.",
    "Planning généré automatiquement": "Ratiba imezalishwa kiotomatiki",
    "Erreur de connexion au serveur": "Hitilafu ya muunganisho na seva",
    "Modifier les Détails": "Rekebisha Maelezo",
    "Fonctionnalité en cours de développement. Bientôt disponible !": "Kipengele kinaendelezwa. Kitapatikana hivi karibuni!",
    "Planifier la Compétition": "Panga Mashindano",
    "Fonctionnalité de planification en cours de développement. Bientôt disponible !": "Kipengele cha kupanga kinaendelezwa. Kitapatikana hivi karibuni!",
    "Inscription - ": "Usajili - ",
    "Le nom de la catégorie est requis.": "Jina la kategoria linahitajika.",
    "Catégorie créée avec succès !": "Kategoria imeundwa kwa mafanikio!",
    "Erreur de réponse du serveur. Vérifiez la console pour plus de détails.": "Hitilafu ya jibu la seva. Angalia konsoli kwa maelezo zaidi.",
    "Une erreur est survenue lors de la création de la catégorie:": "Hitilafu imetokea wakati wa kuunda kategoria:",
    "Gérez vos compétitions et leurs catégories": "Simamia mashindano yako na kategoria zake",
    "Compétitions total": "Jumla ya mashindano",
    "types": "aina",
    "Vous n'avez pas encore créé de compétitions. Commencez par créer votre première compétition.": "Bado hujaunda mashindano. Anza kwa kuunda mashindano yako ya kwanza.",
    "Affectation des pratiquants": "Ugawaji wa watendaji",
    "Non affectés": "Haijagawiwa",
    "Affectés": "Imegawiwa",
    "Aucun type défini": "Hakuna aina iliyofafanuliwa",
    "Glissez un pratiquant ici": "Buruta mtendaji hapa",
    "Aucune catégorie pour ce type": "Hakuna kategoria kwa aina hii",
    "Pratiquant affecté avec succès !": "Mtendaji amegawiwa kwa mafanikio!",
    "Recrutement d'Arbitres Ad-Hoc": "Kuajiri Waamuzi wa Dharura",
    "Recrutez des participants adultes (18+) comme arbitres temporaires pour les combats. Ils auront accès aux interfaces d'arbitrage le temps de l'événement.": "Ajiri washiriki watu wazima (18+) kama waamuzi wa muda kwa mapigano. Watakuwa na ufikiaji wa violesura vya uamuzi wakati wa tukio.",
    "Arbitres ad-hoc actifs pour les combats": "Waamuzi wa dharura hai kwa mapigano",
    "Aucun arbitre ad-hoc actif. Utilisez la section 'Juges Techniques' ci-dessus pour recruter des arbitres en sélectionnant le type 'Arbitre Combat'.": "Hakuna hakimu wa dharura hai. Tumia sehemu ya 'Waamuzi wa Ufundi' hapo juu kuajiri waamuzi kwa kuchagua aina 'Hakimu wa Mapigano'.",
    "Aller à la section Recrutement Ad-Hoc": "Nenda sehemu ya Kuajiri wa Dharura",
    "Programmation par tatami": "Kupanga kwa tatami",
    "Durée par défaut (min)": "Muda wa kawaida (dakika)",
    "Arbitre de coin": "Hakimu wa kona",
    "Arbitre de table": "Hakimu wa meza",
    "Partager sur": "Shiriki kwenye",
    "Cochez les juges que vous souhaitez affecter à cette catégorie, puis cliquez sur 'Affecter les juges sélectionnés'.": "Weka alama kwa waamuzi unaoataka kuwagawa kwa kategoria hii, kisha bofya 'Gawa waamuzi waliochaguliwa'.",
    "Officiel": "Rasmi",
    "Ajoutez d'abord des juges techniques ou des juges ad-hoc.": "Ongeza kwanza waamuzi wa ufundi au waamuzi wa dharura.",
    "cat.": "kat.",
    "pratiquant(s) sélectionné(s)": "mtendaji (watendaji) waliochaguliwa",
    "Erreur de connexion lors de la suppression": "Hitilafu ya muunganisho wakati wa kufuta",
    "Erreur lors de l'affectation": "Hitilafu wakati wa kugawa",
    "Erreur lors de la recherche": "Hitilafu wakati wa kutafuta",
    "sélectionné": "imechaguliwa",
    "Juge ajouté avec succès": "Hakimu ameongezwa kwa mafanikio",
    "Erreur lors de l'ajout du juge": "Hitilafu wakati wa kuongeza hakimu",
    "Un seul arbitre central par tatami": "Hakimu mkuu mmoja peke yake kwa tatami",
    "Maximum 3 arbitres de coin par tatami": "Waamuzi wa kona 3 upeo kwa tatami",
    "Un seul arbitre de table par tatami": "Hakimu mmoja wa meza peke yake kwa tatami",
    "Un seul placator par tatami": "Msuluhishi mmoja peke yake kwa tatami",
    "Cet arbitre est déjà assigné à ce rôle": "Hakimu huyu tayari amegawiwa jukumu hili",
    "Retirer de ce tatami": "Ondoa kutoka tatami hii",
    "Arbitre retiré du tatami": "Hakimu ameondolewa kutoka tatami",
    "assigné comme": "amegawiwa kama",
    "Ce juge est déjà assigné à cette catégorie": "Hakimu huyu tayari amegawiwa kwa kategoria hii",
    "Retirer cette catégorie du planning ?": "Ondoa kategoria hii kutoka ratiba?",
    "Cette action va réassigner toutes les catégories. Continuer ?": "Kitendo hiki kitapanga upya kategoria zote. Endelea?",
    "ajouté": "imeongezwa",
    "Retirer de cette catégorie": "Ondoa kutoka kategoria hii",
    "Retirer ce juge de cette catégorie ?": "Ondoa hakimu huyu kutoka kategoria hii?",
    "Juge retiré de la catégorie": "Hakimu ameondolewa kutoka kategoria",
    "QR Code téléchargé avec succès": "QR Code imepakiwa kwa mafanikio",
    "Vue drag & drop": "Mtazamo wa kuburuta na kudondosha",
    "Affecté à": "Imegawiwa kwa",
    "Retiré de la catégorie": "Imeondolewa kutoka kategoria",
    "Erreur lors de l affectation": "Hitilafu wakati wa kugawa",
    "Erreur lors du retrait": "Hitilafu wakati wa kuondoa",
    "Retirer ce juge": "Ondoa hakimu huyu",
    "Aucune description": "Hakuna maelezo",
    "Aucun type de compétition. Commencez par en créer un !": "Hakuna aina ya mashindano. Anza kwa kuunda moja!",
    "Fusionner:": "Unganisha:",
    "Fusionner": "Unganisha",
    "(Sélectionnez pour fusionner)": "(Chagua kuunganisha)",
    "inscrit(s)": "amesajiliwa (wamesajiliwa)",
    "Peu d'inscrits": "Wachache wamesajiliwa",
    "Pratiquants inscrits": "Watendaji waliosajiliwa",
    "Attribuer/Retirer rôle Juge": "Gawa/Ondoa jukumu la Hakimu",
    "Attribuer/Retirer rôle Arbitre": "Gawa/Ondoa jukumu la Hakimu",
    "Aucun pratiquant inscrit dans cette catégorie.": "Hakuna mtendaji aliyesajiliwa katika kategoria hii.",
    "Aucune catégorie créée.": "Hakuna kategoria iliyoundwa.",
    "Compétition publiée": "Mashindano yamechapishwa",
    "Voir la page publique": "Tazama ukurasa wa umma",
    "Gestion avancée (Pro)": "Usimamizi wa juu (Kitaalamu)",
    "Ex: Combat, Kata, Technique...": "Mfano: Mapigano, Kata, Ufundi...",
    "Description optionnelle...": "Maelezo ya hiari...",
    "Type de scoring": "Aina ya alama",
    "Fusionner les catégories": "Unganisha kategoria",
    "Les pratiquants des catégories sélectionnées seront regroupés dans une seule catégorie. Les catégories vides seront supprimées.": "Watendaji wa kategoria zilizochaguliwa watawekwa katika kategoria moja. Kategoria tupu zitafutwa.",
    "Catégories à fusionner": "Kategoria za kuunganisha",
    "Catégorie cible (optionnel)": "Kategoria lengwa (hiari)",
    "Si vous sélectionnez une catégorie existante, les autres seront fusionnées dedans.": "Ukichagua kategoria iliyopo, nyingine zitaunganishwa ndani yake.",
    "Nom de la nouvelle catégorie": "Jina la kategoria mpya",
    "Ex: Juniors fusionnés": "Mfano: Vijana waliounganishwa",
    "Les pratiquants seront répartis équitablement entre les deux nouvelles catégories, en se basant d'abord sur l'âge puis sur le grade.": "Watendaji watagawanywa kwa usawa kati ya kategoria mbili mpya, kwanza kwa umri kisha kwa daraja.",
    "plus âgés / gradés": "wakubwa zaidi / wenye daraja la juu",
    "Ex: Seniors A": "Mfano: Wakubwa A",
    "Ex: Seniors B": "Mfano: Wakubwa B",
    "Attention: cette action supprimera la catégorie d'origine et créera deux nouvelles catégories.": "Tahadhari: kitendo hiki kitafuta kategoria ya asili na kuunda kategoria mbili mpya.",
    "Le pratiquant pourra toujours participer aux autres catégories (ex: combat).": "Mtendaji bado ataweza kushiriki katika kategoria nyingine (mfano: mapigano).",
    "Veuillez spécifier un nom pour la nouvelle catégorie": "Tafadhali bainisha jina la kategoria mpya",
    "Fusion en cours...": "Muungano unaendelea...",
    "Erreur lors de la fusion": "Hitilafu wakati wa kuunganisha",
    "Type créé avec succès": "Aina imeundwa kwa mafanikio",
    "Supprimer le type": "Futa aina",
    "Type supprimé": "Aina imefutwa",
    "Catégorie créée": "Kategoria imeundwa",
    "Publier la compétition ?": "Chapisha mashindano?",
    "Publication...": "Kuchapisha...",
    "Aucune catégorie définie. Cliquez sur 'Ajouter une catégorie' pour commencer.": "Hakuna kategoria iliyofafanuliwa. Bofya 'Ongeza kategoria' kuanza.",
    "Aucune inscription pour le moment.": "Hakuna usajili kwa sasa.",
    "Aucun juge assigné pour le moment.": "Hakuna hakimu aliyegawiwa kwa sasa.",
    "Erreur de chargement des grades": "Hitilafu ya kupakia madaraja",
    "Êtes-vous sûr de vouloir supprimer cette inscription ?": "Je, una uhakika unataka kufuta usajili huu?",
    "Êtes-vous sûr de vouloir retirer ce juge ?": "Je, una uhakika unataka kumwondoa hakimu huyu?",
    "Inscription des pratiquants": "Usajili wa watendaji",
    "Sélectionnez un type de compétition": "Chagua aina ya mashindano",
    "Aucun type de compétition disponible pour cette compétition.": "Hakuna aina ya mashindano inayopatikana kwa mashindano haya.",
    "Inscrivez vos pratiquants": "Sajili watendaji wako",
    "Filtrer les pratiquants": "Chuja watendaji",
    "Aucun pratiquant disponible": "Hakuna mtendaji anayepatikana",
    "Glissez-déposez les pratiquants ici pour les inscrire": "Buruta na udondoshe watendaji hapa kusajili",
    "Résumé des inscriptions": "Muhtasari wa usajili",
    "Veuillez sélectionner un type de compétition": "Tafadhali chagua aina ya mashindano",
    "Veuillez sélectionner une catégorie": "Tafadhali chagua kategoria",
    "Aucune catégorie disponible pour ce type": "Hakuna kategoria inayopatikana kwa aina hii",
    "Total inscrits": "Jumla ya waliosajiliwa",
    "De votre club": "Kutoka klabu yako",
    "Pratiquants du club": "Watendaji wa klabu",
    "Restants à inscrire": "Waliobaki kusajiliwa",
    "Pools / Catégories": "Makundi / Kategoria",
    "Inscription par glisser-déposer": "Usajili kwa kuburuta na kudondosha",
    "Glissez les pratiquants vers les catégories": "Buruta watendaji kuelekea kategoria",
    "H": "M",
    "F": "K",
    "Aucun type de compétition défini": "Hakuna aina ya mashindano iliyofafanuliwa",
    "Inscriptions en attente:": "Usajili unaosubiri:",
    "Vider": "Futa yote",
    "Valider les inscriptions": "Thibitisha usajili",
    "Aucun pratiquant disponible dans votre club": "Hakuna mtendaji anayepatikana katika klabu yako",
    "Pratiquants déjà inscrits": "Watendaji waliosajiliwa tayari",
    "Types:": "Aina:",
    "Désinscrire de cette catégorie": "Ondoa usajili kutoka kategoria hii",
    "Aucun pratiquant inscrit pour le moment": "Hakuna mtendaji aliyesajiliwa kwa sasa",
    "Gestion des équipes": "Usimamizi wa timu",
    "Créer une nouvelle équipe": "Unda timu mpya",
    "Demandes de fusion": "Maombi ya muungano",
    "Aucune équipe créée pour cette compétition": "Hakuna timu iliyoundwa kwa mashindano haya",
    "Créez une équipe pour regrouper vos pratiquants": "Unda timu ili kupanga watendaji wako",
    "Équipes par catégorie pour les pools": "Timu kwa kategoria kwa makundi",
    "Cette vue montre toutes les équipes regroupées par catégorie de compétition. Utilisez ces informations pour organiser les pools de combat.": "Mtazamo huu unaonyesha timu zote zilizopangwa kwa kategoria ya mashindano. Tumia taarifa hizi kupanga makundi ya mapigano.",
    "Filtrer par type :": "Chuja kwa aina:",
    "Tout masquer": "Ficha yote",
    "Masquer catégories sans équipes": "Ficha kategoria bila timu",
    "catégorie(s) masquée(s)": "kategoria zilizofichwa",
    "Équipe(s)": "Timu",
    "pool(s) suggéré(s)": "kundi (makundi) yaliyopendekezwa",
    "Fusionner 2 équipes": "Unganisha timu 2",
    "Équipe multi-clubs": "Timu ya klabu nyingi",
    "Sélectionner pour fusion": "Chagua kuunganisha",
    "titulaires": "wachezaji",
    "remp.": "wabadala",
    "Aucune équipe dans cette catégorie": "Hakuna timu katika kategoria hii",
    "Aucune catégorie avec des équipes pour le moment": "Hakuna kategoria yenye timu kwa sasa",
    "Créez des équipes dans l'onglet 'Équipes' pour les voir ici regroupées par catégorie.": "Unda timu katika kichupo cha 'Timu' ili kuziona hapa zimepangwa kwa kategoria.",
    "Ex: Équipe Combat A": "Mfano: Timu ya Mapigano A",
    "Seuls les pratiquants inscrits à cette compétition sont affichés, regroupés par catégorie.": "Watendaji waliosajiliwa kwa mashindano haya peke yao wanaonyeshwa, wamepangwa kwa kategoria.",
    "Membres titulaires": "Wanachama wa msingi",
    "Remplaçants": "Wabadala",
    "Pratiquants inscrits à cette compétition.": "Watendaji waliosajiliwa kwa mashindano haya.",
    "Aucun pratiquant n'est encore inscrit à cette compétition. Veuillez d'abord inscrire des pratiquants avant de créer une équipe.": "Hakuna mtendaji aliyesajiliwa kwa mashindano haya bado. Tafadhali sajili watendaji kwanza kabla ya kuunda timu.",
    "-- Sélectionner --": "-- Chagua --",
    "Fusion d'équipes inter-clubs": "Muungano wa timu baina ya klabu",
    "Votre équipe est incomplète. Vous pouvez demander à fusionner avec une équipe d'un autre club qui manque également de membres.": "Timu yako haijakamilika. Unaweza kuomba kuunganisha na timu ya klabu nyingine ambayo pia inakosa wanachama.",
    "Équipes incomplètes disponibles": "Timu ambazo hazijakamilika zinazopatikana",
    "Ex: Notre équipe a 2 membres, nous cherchons à compléter...": "Mfano: Timu yetu ina wanachama 2, tunatafuta kukamilisha...",
    "Reçues": "Zilizopokelewa",
    "Envoyées": "Zilizotumwa",
    "Aucune demande reçue": "Hakuna ombi lililopokelewa",
    "Aucune demande envoyée": "Hakuna ombi lililotumwa",
    "Sélectionnez 2 équipes à fusionner. L'équipe résultante conservera le nom de la première équipe sélectionnée.": "Chagua timu 2 za kuunganisha. Timu inayotokana itahifadhi jina la timu ya kwanza iliyochaguliwa.",
    "Équipe principale": "Timu kuu",
    "Sélectionnez une équipe": "Chagua timu",
    "Équipe à fusionner": "Timu ya kuunganisha",
    "Équipes disponibles dans cette catégorie": "Timu zinazopatikana katika kategoria hii",
    "Fusionner les équipes": "Unganisha timu",
    "Êtes-vous sûr de vouloir désinscrire ce pratiquant de la catégorie": "Je, una uhakika unataka kumwondoa mtendaji huyu kutoka kategoria",
    "Erreur lors de la désinscription": "Hitilafu wakati wa kuondoa usajili",
    "Équipe complète": "Timu kamili",
    "Équipe incomplète": "Timu isiyo kamili",
    "Aucun titulaire": "Hakuna mchezaji wa msingi",
    "Il manque": "Inakosa",
    "titulaire(s) pour compléter cette équipe.": "mchezaji (wachezaji) wa msingi kukamilisha timu hii.",
    "Il faut au moins 2 équipes incomplètes pour fusionner": "Inahitajika angalau timu 2 ambazo hazijakamilika kuunganisha",
    "Cliquer pour sélectionner": "Bofya kuchagua",
    "Équipe qui conservera son nom": "Timu itakayohifadhi jina lake",
    "Membres transférés vers équipe 1": "Wanachama waliohamishwa kwa timu 1",
    "Veuillez sélectionner 2 équipes": "Tafadhali chagua timu 2",
    "Voulez-vous vraiment fusionner ces 2 équipes ? Les membres de": "Je, unataka kweli kuunganisha timu hizi 2? Wanachama wa",
    "seront transférés vers": "watahamishwa kwenda",
    "Équipes fusionnées avec succès": "Timu zimeunganishwa kwa mafanikio",
    "Un compte utilisateur sera créé automatiquement pour ce pratiquant": "Akaunti ya mtumiaji itaundwa kiotomatiki kwa mtendaji huyu",
    "Un mot de passe temporaire aléatoire sera généré": "Nenosiri la muda la nasibu litazalishwa",
    "Un email sera envoyé au pratiquant avec ses identifiants": "Barua pepe itatumwa kwa mtendaji na vitambulisho vyake",
    "Le pratiquant pourra se connecter et changer son mot de passe": "Mtendaji ataweza kuingia na kubadilisha nenosiri lake",
    "Je confirme vouloir créer un compte pour ce pratiquant": "Ninathibitisha nataka kuunda akaunti kwa mtendaji huyu",
    "Le mot de passe sera généré de manière aléatoire (8 caractères)": "Nenosiri litazalishwa kwa nasibu (herufi 8)",
    "Le pratiquant devra changer son mot de passe lors de la première connexion": "Mtendaji atalazimika kubadilisha nenosiri lake wakati wa kuingia kwa mara ya kwanza",
    "Si l'email ne peut pas être envoyé, les identifiants seront affichés à l'écran": "Ikiwa barua pepe haiwezi kutumwa, vitambulisho vitaonyeshwa kwenye skrini",
    "Que se passe-t-il après la création du compte ?": "Nini kinatokea baada ya kuunda akaunti?",
    "Le pratiquant recevra un email avec ses identifiants de connexion": "Mtendaji atapokea barua pepe na vitambulisho vyake vya kuingia",
    "Il pourra se connecter à son espace personnel": "Ataweza kuingia kwenye eneo lake binafsi",
    "Il pourra consulter ses inscriptions aux compétitions": "Ataweza kuangalia usajili wake wa mashindano",
    "Il pourra gérer son profil et ses informations": "Ataweza kusimamia wasifu wake na taarifa zake",
    "Il sera invité à changer son mot de passe temporaire": "Ataalikwa kubadilisha nenosiri lake la muda",
    "Inscription de": "Usajili wa",
    "Combat en Direct": "Mapigano ya Moja kwa Moja",
    "Créer un Combat": "Unda Pigano",
    "combat(s) en cours": "pigano (mapigano) yanaendelea",
    "Accès complet : équipes, poules, ententes, fusions, phase finale et podium": "Ufikiaji kamili: timu, makundi, makubaliano, muungano, awamu ya mwisho na jukwaa la tuzo",
    "Liste des Combats": "Orodha ya Mapigano",
    "Voir tous les combats de cette compétition avec leurs statuts": "Tazama mapigano yote ya mashindano haya na hali zake",
    "Interface Combat": "Kiolesura cha Mapigano",
    "Interface de gestion de combat en temps réel pour arbitres": "Kiolesura cha usimamizi wa mapigano kwa wakati halisi kwa waamuzi",
    "Accéder à la liste des combats pour créer ou gérer un combat": "Fikia orodha ya mapigano kuunda au kusimamia pigano",
    "Voir les combats": "Tazama mapigano",
    "Interface Taekwondo": "Kiolesura cha Taekwondo",
    "Interface spécialisée Taekwondo avec points et pénalités spécifiques (Kyong-go, Gam-jeom)": "Kiolesura maalum cha Taekwondo na pointi na adhabu maalum (Kyong-go, Gam-jeom)",
    "Aucun combat Taekwondo actif pour le moment": "Hakuna pigano la Taekwondo linaloendelea kwa sasa",
    "Monitoring Live": "Ufuatiliaji wa Moja kwa Moja",
    "Suivi public des combats en temps réel pour spectateurs et organisateurs": "Ufuatiliaji wa umma wa mapigano kwa wakati halisi kwa watazamaji na waandaaji",
    "Créez un combat et démarrez-le pour activer le monitoring live": "Unda pigano na ulianze ili kuwasha ufuatiliaji wa moja kwa moja",
    "Interface complète d'arbitrage avec points, pénalités et chronomètre": "Kiolesura kamili cha uamuzi na pointi, adhabu na kipima muda",
    "Interface plein écran pour projecteur/écran public avec synchronisation automatique": "Kiolesura cha skrini kamili kwa projekta/skrini ya umma na ulandanishi kiotomatiki",
    "Nouvelle fenêtre": "Dirisha jipya",
    "Créez un combat et démarrez-le pour activer l'affichage public": "Unda pigano na ulianze ili kuwasha onyesho la umma",
    "Suivi de Poule": "Ufuatiliaji wa Kundi",
    "Suivre l'ordre de passage et le classement en temps réel de toute la poule": "Fuatilia mpangilio wa kupita na cheo kwa wakati halisi wa kundi lote",
    "poules": "makundi",
    "Créez des poules pour activer le suivi en temps réel": "Unda makundi ili kuwasha ufuatiliaji wa wakati halisi",
    "Classement Live": "Cheo cha Moja kwa Moja",
    "Classement en temps réel avec statistiques détaillées et podium dynamique": "Cheo kwa wakati halisi na takwimu za kina na jukwaa la tuzo linalobadilika",
    "Notation & Scoring": "Alama na Ufungaji",
    "Dashboard Scoring": "Dashibodi ya Alama",
    "Vue d'ensemble du scoring avec statistiques et progression par catégorie": "Muhtasari wa alama na takwimu na maendeleo kwa kategoria",
    "performances": "utendaji",
    "Interface Admin Scoring": "Kiolesura cha Msimamizi wa Alama",
    "Gérer les scores des juges et superviser les notations pour toutes les catégories": "Simamia alama za waamuzi na usimamie ufungaji kwa kategoria zote",
    "juges": "waamuzi",
    "Gérer les scores des juges et superviser les notations. Créez d'abord des catégories pour configurer le scoring.": "Simamia alama za waamuzi na usimamie ufungaji. Unda kwanza kategoria ili kusanidi alama.",
    "Scoring Technique": "Alama za Ufundi",
    "Accéder aux interfaces de notation technique pour juges": "Fikia violesura vya alama za ufundi kwa waamuzi",
    "Scoring Standalone": "Alama Huru",
    "Système de notation indépendant avec critères personnalisés": "Mfumo huru wa alama na vigezo maalum",
    "Critères de Notation": "Vigezo vya Alama",
    "Configurer les critères et poids de notation pour chaque catégorie": "Sanidi vigezo na uzito wa alama kwa kila kategoria",
    "Créez d'abord des catégories pour configurer les critères de notation": "Unda kwanza kategoria ili kusanidi vigezo vya alama",
    "Créer des catégories": "Unda kategoria",
    "Historique Scoring": "Historia ya Alama",
    "Consulter l'historique des notations effectuées pour cette compétition": "Angalia historia ya alama zilizofanywa kwa mashindano haya",
    "Cette page vous permet d'importer et d'exporter les données de votre club au format Excel. Vous pouvez ainsi gérer facilement vos pratiquants et optimiser votre organisation.": "Ukurasa huu unakuruhusu kuagiza na kusafirisha data ya klabu yako kwa muundo wa Excel. Unaweza kusimamia kwa urahisi watendaji wako na kuboresha shirika lako.",
    "Téléchargez toutes les données de vos pratiquants au format Excel pour les consulter hors ligne ou les modifier dans un tableur.": "Pakua data zote za watendaji wako kwa muundo wa Excel ili kuzitazama nje ya mtandao au kuzirekebisha kwenye lahajedwali.",
    "Importez de nouveaux pratiquants ou mettez à jour les existants en uploadant un fichier Excel au format approprié.": "Agiza watendaji wapya au sasisha waliopo kwa kupakia faili ya Excel kwa muundo unaofaa.",
    "Complétez le fichier Excel avec les informations de vos pratiquants. Veillez à respecter le format des colonnes.": "Kamilisha faili ya Excel na taarifa za watendaji wako. Hakikisha unafuata muundo wa safu wima.",
    "Formats acceptés: .xlsx, .xls, .csv": "Muundo unaokubaliwa: .xlsx, .xls, .csv",
    "Fichier sélectionné:": "Faili iliyochaguliwa:",
    "Erreur de sécurité. Veuillez recharger la page.": "Hitilafu ya usalama. Tafadhali pakia upya ukurasa.",
    "Téléchargez la liste complète de vos pratiquants au format Excel pour sauvegarde ou modification hors ligne.": "Pakua orodha kamili ya watendaji wako kwa muundo wa Excel kwa hifadhi au marekebisho nje ya mtandao.",
    "NOM": "JINA",
    "Formats de date acceptés": "Muundo wa tarehe unaokubaliwa",
    "JJ/MM/AAAA (ex: 15/03/2010)": "SS/MM/MMMM (mfano: 15/03/2010)",
    "JJ-MM-AAAA (ex: 15-03-2010)": "SS-MM-MMMM (mfano: 15-03-2010)",
    "JJ.MM.AAAA (ex: 15.03.2010)": "SS.MM.MMMM (mfano: 15.03.2010)",
    "Vérifiez que les noms de colonnes correspondent": "Hakikisha majina ya safu wima yanalingana",
    "Les doublons seront automatiquement ignorés": "Nakala rudufu zitapuuzwa kiotomatiki",
    "Total juges": "Jumla ya waamuzi",
    "Pour effectuer le paiement, veuillez contacter directement la fédération ou suivre les instructions indiquées sur la facture.": "Kufanya malipo, tafadhali wasiliana moja kwa moja na shirikisho au fuata maelekezo yaliyoonyeshwa kwenye ankara.",
    "Profil du pratiquant": "Wasifu wa mtendaji",
    "Changer système...": "Badilisha mfumo...",
    "Contact d'urgence:": "Mtu wa kuwasiliana naye kwa dharura:",
    "Voir l'espace membre": "Tazama eneo la mwanachama",
    "Activer le compte de connexion": "Washa akaunti ya kuingia",
    "Attribuer rôle Juge/Arbitre": "Gawa jukumu la Hakimu/Mwamuzi",
    "Compte existant détecté": "Akaunti iliyopo imegunduliwa",
    "Lier ce compte": "Unganisha akaunti hii",
    "Aucun compte de connexion": "Hakuna akaunti ya kuingia",
    "Défiler à gauche": "Sogeza kushoto",
    "Parcours": "Njia",
    "Parc.": "Njia",
    "Palm.": "Tuzo",
    "Fin.": "Fedha",
    "Docs": "Hati",
    "Cmd.": "Amri",
    "Carte ID": "Kadi ya Kitambulisho",
    "Défiler à droite": "Sogeza kulia",
    "Aucun historique de grade.": "Hakuna historia ya daraja.",
    "Informations Médicales": "Taarifa za Matibabu",
}
