# -*- coding: utf-8 -*-
TRANSLATIONS = {
    "Configuration tarifaire": "Usanidi wa bei",
    "Souscription": "Usajili",
    "Période d'adhésion": "Kipindi cha uanachama",
    "Méta-données": "Meta-data",
    "Configuration du déclencheur": "Usanidi wa kichocheo",
    "Configuration de l'action": "Usanidi wa kitendo",
    "Conditions d'application": "Masharti ya utekelezaji",
    "Configuration de base": "Usanidi wa msingi",
    "Contenu affiché": "Maudhui yanayoonyeshwa",
    "Packages disponibles": "Vifurushi vinavyopatikana",
    "Options de collecte": "Chaguzi za ukusanyaji",
    "Configuration d'accès": "Usanidi wa ufikiaji",
    "Voir le formulaire": "Tazama fomu",
    "Formulaire et package": "Fomu na kifurushi",
    "Données personnalisées": "Data maalum",
    "Traitement": "Uchakataji",
    "Alerte": "Tahadhari",
    "%(count)d alerte(s) marquée(s) comme résolue(s).": "Tahadhari %(count)d zimewekwa alama kama zilizotatuliwa.",
    "Marquer comme résolu": "Weka alama kama imetatuliwa",
    "Administration MartialComp - Système d'Adhésion": "Usimamizi wa MartialComp - Mfumo wa Uanachama",
    "Système d'Adhésion": "Mfumo wa Uanachama",
    "Ex: Package Étudiant Mensuel": "Mfano: Kifurushi cha Mwanafunzi cha Kila Mwezi",
    "Description détaillée du package...": "Maelezo ya kina ya kifurushi...",
    "0 = illimité": "0 = bila kikomo",
    "Type de package": "Aina ya kifurushi",
    "Prix de base": "Bei ya msingi",
    "Disciplines incluses": "Taaluma zilizojumuishwa",
    "Sessions max/semaine": "Vipindi vya juu/wiki",
    "Inclut les compétitions": "Inajumuisha mashindano",
    "Inclut les stages": "Inajumuisha semina",
    "Inclut l'équipement": "Inajumuisha vifaa",
    "Laissez vide ou mettez 0 pour des sessions illimitées": "Acha tupu au weka 0 kwa vipindi visivyo na kikomo",
    "Code devise à 3 lettres (EUR, USD, etc.)": "Msimbo wa sarafu wa herufi 3 (EUR, USD, nk.)",
    "Nombre de jours après expiration où le package reste accessible": "Idadi ya siku baada ya kumalizika ambapo kifurushi kinabaki kupatikana",
    "Plus petit = affiché en premier": "Ndogo zaidi = inaonyeshwa kwanza",
    "Ce package sera mis en avant visuellement": "Kifurushi hiki kitaangaziwa kwa macho",
    "Le prix ne peut pas être négatif.": "Bei haiwezi kuwa hasi.",
    "La devise doit être un code à 3 lettres (ex: EUR, USD).": "Sarafu lazima iwe msimbo wa herufi 3 (mfano: EUR, USD).",
    "Prix payé": "Bei iliyolipwa",
    "Semestriel": "Kila nusu mwaka",
    "Loisir": "Burudani",
    "Senior": "Mkubwa",
    "Jeune": "Kijana",
    "Disciplines accessibles avec ce package": "Taaluma zinazopatikana na kifurushi hiki",
    "Package d'adhésion": "Kifurushi cha uanachama",
    "Prochaine date de renouvellement": "Tarehe ya kuhuisha ijayo",
    "Disciplines personnalisées": "Taaluma maalum",
    "Remplace les disciplines du package si définies": "Inabadilisha taaluma za kifurushi ikiwa zimefafanuliwa",
    "Souscription d'adhésion": "Usajili wa uanachama",
    "Souscriptions d'adhésion": "Usajili wa uanachama",
    "Renouvellement dû": "Kuhuisha kunahitajika",
    "Alerte d'expiration": "Tahadhari ya kumalizika",
    "Échec de paiement": "Malipo yameshindikana",
    "Envoyer un SMS": "Tuma SMS",
    "Créer une notification": "Unda arifa",
    "Suspendre l'adhésion": "Sitisha uanachama",
    "Renouveler automatiquement": "Huisha kiotomatiki",
    "Créer une tâche": "Unda kazi",
    "Nom du workflow": "Jina la mtiririko wa kazi",
    "Type de déclencheur": "Aina ya kichocheo",
    "Jours avant le déclencheur": "Siku kabla ya kichocheo",
    "Pour les rappels d'expiration": "Kwa vikumbusho vya kumalizika",
    "Contenu de l'action": "Maudhui ya kitendo",
    "Configuration spécifique à l'action": "Usanidi mahususi wa kitendo",
    "Packages applicables": "Vifurushi vinavyotumika",
    "Workflow d'adhésion": "Mtiririko wa kazi wa uanachama",
    "Workflows d'adhésion": "Mtiririko wa kazi wa uanachama",
    "Changement de package": "Mabadiliko ya kifurushi",
    "Nom du formulaire": "Jina la fomu",
    "Type de formulaire": "Aina ya fomu",
    "Message de bienvenue": "Ujumbe wa karibu",
    "Message de succès": "Ujumbe wa mafanikio",
    "Échelonnement de paiement": "Malipo ya awamu",
    "Soumissions max/jour": "Uwasilishaji wa juu/siku",
    "Formulaire d'adhésion en ligne": "Fomu ya uanachama mtandaoni",
    "Formulaires d'adhésion en ligne": "Fomu za uanachama mtandaoni",
    "Package sélectionné": "Kifurushi kilichochaguliwa",
    "Données du formulaire": "Data ya fomu",
    "Notes de traitement": "Maelezo ya uchakataji",
    "Souscription créée": "Usajili umeundwa",
    "Soumission de formulaire d'adhésion": "Uwasilishaji wa fomu ya uanachama",
    "Soumissions de formulaires d'adhésion": "Uwasilishaji wa fomu za uanachama",
    "Rappel de renouvellement": "Kumbusho la kuhuisha",
    "Suggestion d'upgrade": "Pendekezo la kuboresha",
    "Assiduité faible": "Mahudhurio duni",
    "Type d'alerte": "Aina ya tahadhari",
    "Résolu par": "Imetatuliwa na",
    "Notification envoyée": "Arifa imetumwa",
    "Alerte d'adhésion": "Tahadhari ya uanachama",
    "Alertes d'adhésion": "Tahadhari za uanachama",
    "Adhésion bientôt expirée": "Uanachama unakaribia kumalizika",
    "L'adhésion de {} expire le {}.": "Uanachama wa {} unamalizika tarehe {}.",
    "Échec du renouvellement automatique": "Kuhuisha kiotomatiki kumeshindikana",
    "Le renouvellement automatique a échoué: {}": "Kuhuisha kiotomatiki kumeshindikana: {}",
    "Un bon taux de rétention est généralement supérieur à 70%%": "Kiwango kizuri cha uhifadhi kwa kawaida ni zaidi ya 70%%",
    "Aucune organisation associée trouvée.": "Hakuna shirika linalohusiana lililopatikana.",
    "Accès non autorisé à cette souscription.": "Ufikiaji usioidhinishwa kwa usajili huu.",
    "Détail de la souscription": "Maelezo ya usajili",
    "Votre demande d'adhésion a été soumise avec succès. Vous recevrez une confirmation par email.": "Ombi lako la uanachama limewasilishwa kwa mafanikio. Utapokea uthibitisho kwa barua pepe.",
    "Une erreur est survenue lors de la soumission.": "Hitilafu imetokea wakati wa uwasilishaji.",
    "Analytics Adhésions": "Uchambuzi wa Uanachama",
    "Package '{}' créé avec succès.": "Kifurushi '{}' kimeundwa kwa mafanikio.",
    "Package '{}' modifié avec succès.": "Kifurushi '{}' kimerekebishwa kwa mafanikio.",
    "Modifier le package": "Rekebisha kifurushi",
    "Suppression de package - Fonctionnalité en développement": "Kufuta kifurushi - Kipengele kinaendelezwa",
    "Édition de souscription - Fonctionnalité en développement": "Kurekebisha usajili - Kipengele kinaendelezwa",
    "Renouvellement - Fonctionnalité en développement": "Kuhuisha - Kipengele kinaendelezwa",
    "Annulation - Fonctionnalité en développement": "Kufuta - Kipengele kinaendelezwa",
    "Gestion des formulaires - Fonctionnalité en développement": "Usimamizi wa fomu - Kipengele kinaendelezwa",
    "Création de formulaire - Fonctionnalité en développement": "Kuunda fomu - Kipengele kinaendelezwa",
    "Édition de formulaire - Fonctionnalité en développement": "Kurekebisha fomu - Kipengele kinaendelezwa",
    "Liste des soumissions - Fonctionnalité en développement": "Orodha ya uwasilishaji - Kipengele kinaendelezwa",
    "Détail de soumission - Fonctionnalité en développement": "Maelezo ya uwasilishaji - Kipengele kinaendelezwa",
    "Traitement de soumission - Fonctionnalité en développement": "Uchakataji wa uwasilishaji - Kipengele kinaendelezwa",
    "Gestion des workflows - Fonctionnalité en développement": "Usimamizi wa mtiririko wa kazi - Kipengele kinaendelezwa",
    "Création de workflow - Fonctionnalité en développement": "Kuunda mtiririko wa kazi - Kipengele kinaendelezwa",
    "Édition de workflow - Fonctionnalité en développement": "Kurekebisha mtiririko wa kazi - Kipengele kinaendelezwa",
    "Test de workflow - Fonctionnalité en développement": "Jaribio la mtiririko wa kazi - Kipengele kinaendelezwa",
    "Liste des alertes - Fonctionnalité en développement": "Orodha ya tahadhari - Kipengele kinaendelezwa",
    "Résolution d'alerte - Fonctionnalité en développement": "Kutatua tahadhari - Kipengele kinaendelezwa",
    "Export analytics - Fonctionnalité en développement": "Hamisha uchambuzi - Kipengele kinaendelezwa",
    "Type d'audit: Tenant spécifique\n": "Aina ya ukaguzi: Mpangaji mahususi\n",
    "Le tenant {} présente des problèmes de sécurité critiques.\n\n": "Mpangaji {} ana matatizo muhimu ya usalama.\n\n",
    "\n\nAction requise: Veuillez examiner et corriger ces problèmes immédiatement.": "\n\nKitendo kinachohitajika: Tafadhali kagua na urekebishe matatizo haya mara moja.",
    "Vous utilisez actuellement le plan <strong>%(tenant.get_subscription_plan_display)s</strong> qui limite le nombre de %(resource_type)s que vous pouvez avoir.": "Kwa sasa unatumia mpango wa <strong>%(tenant.get_subscription_plan_display)s</strong> ambao unapunguza idadi ya %(resource_type)s unayoweza kuwa nayo.",
    "Un audit de sécurité vérifie la protection et l'isolation des données entre les tenants dans l'architecture multi-tenant.": "Ukaguzi wa usalama unathibitisha ulinzi na utengaji wa data kati ya wapangaji katika usanifu wa wapangaji wengi.",
    "Dimensions recommandées: 1920x600px. Max 5 Mo.": "Vipimo vinavyopendekezwa: 1920x600px. Upeo wa 5 MB.",
    "Nombre de jours avant la fin de saison pour envoyer les rappels de renouvellement": "Idadi ya siku kabla ya mwisho wa msimu kutuma vikumbusho vya kuhuisha",
    "Taux de TVA en pourcentage (ex: 20.00)": "Kiwango cha kodi ya thamani kwa asilimia (mfano: 20.00)",
    "Aperçu actualisé": "Muhtasari uliosasishwa",
    "Entrainement personnalise et coaching professionnel pour tous les niveaux. Atteignez vos objectifs avec un accompagnement sur mesure.": "Mazoezi ya kibinafsi na ukocha wa kitaalamu kwa viwango vyote. Fikia malengo yako na usaidizi uliobinafsishwa.",
    "Entrainement personnalise selon vos objectifs. Programme adapte a votre niveau et vos disponibilites.": "Mazoezi yaliyobinafsishwa kulingana na malengo yako. Programu iliyobadilishwa kwa kiwango chako na upatikanaji wako.",
    "Excellent coach ! Tres pedagogue et patient. J'ai enormement progresse en quelques mois.": "Kocha bora! Mwalimu sana na mvumilivu. Nimepiga hatua kubwa kwa miezi michache.",
    "Grace a lui, j'ai progresse tres rapidement. Les cours sont bien structures et motivants.": "Shukrani kwake, nimepiga hatua haraka sana. Kozi zimepangwa vizuri na zinachochea.",
    "Cette organisation ne peut pas être supprimée car elle a des affiliations. Veuillez supprimer toutes les affiliations avant de supprimer l'organisation.": "Shirika hili haliwezi kufutwa kwa sababu lina ushirika. Tafadhali ondoa ushirika wote kabla ya kufuta shirika.",
    "\n                    Attention : Ce rôle est actuellement attribué à %(count)s utilisateur(s).\n                    Supprimer ce rôle supprimera également toutes ces attributions.\n                ": "\n                    Tahadhari: Jukumu hili kwa sasa limepewa mtumiaji %(count)s.\n                    Kufuta jukumu hili kutafuta pia ugawaji wote huo.\n                ",
    "Administration MartialComp - Shop": "Usimamizi wa MartialComp - Duka",
    "Admin Shop": "Usimamizi wa Duka",
    "Gestion E-commerce": "Usimamizi wa Biashara mtandaoni",
    "Aucun article": "Hakuna bidhaa",
    "\n                                    Êtes-vous sûr de vouloir supprimer le produit \"%(name)s\" ?\n                                    ": "\n                                    Je, una uhakika unataka kufuta bidhaa \"%(name)s\"?\n                                    ",
    "Catégories standards créées/mises à jour.": "Makundi ya kawaida yameundwa/kusasishwa.",
    "Nombre de tâches": "Idadi ya kazi",
    "WIP": "WIP",
    "Statut et priorité": "Hali na kipaumbele",
    "Données additionnelles": "Data ya ziada",
    "Description du tableau (optionnel)": "Maelezo ya bodi (hiari)",
    "Sarcelle": "Rangi ya bahari",
    "Observateur": "Mtazamaji",
    "Une compétition doit être sélectionnée pour ce type de tableau.": "Mashindano lazima yachaguliwe kwa aina hii ya bodi.",
    "Titre de la tâche": "Kichwa cha kazi",
    "Description détaillée (optionnel)": "Maelezo ya kina (hiari)",
    "Séparez les étiquettes par des virgules": "Tenganisha lebo kwa koma",
    "Colonne invalide": "Safu wima batili",
    "Toutes les organisations": "Mashirika yote",
    "Inclure les tableaux archivés": "Jumuisha bodi zilizohifadhiwa",
    "Assigner à": "Gawa kwa",
    "Tâche": "Kazi",
    "Assigné": "Amegawiwa",
    "Réviseur": "Mkaguzi",
    "Collaborateur": "Mshirikiano",
    "Notifier des mises à jour": "Arifu kuhusu masasisho",
    "Notifier des commentaires": "Arifu kuhusu maoni",
    "Notifier de l'échéance": "Arifu kuhusu tarehe ya mwisho",
    "Assignation de tâche": "Ugawaji wa kazi",
    "Assignations de tâches": "Ugawaji wa kazi",
    "Est un template": "Ni kiolezo",
    "Public dans l'organisation": "Umma katika shirika",
    "Liste des rôles d'organisation autorisés à accéder au board": "Orodha ya majukumu ya shirika yaliyoidhinishwa kufikia bodi",
    "Commentaires activés": "Maoni yamewezeshwa",
    "Pièces jointes activées": "Viambatanisho vimewezeshwa",
    "Tableau Kanban": "Bodi ya Kanban",
    "Nombre maximum de tâches dans cette colonne": "Idadi ya juu ya kazi katika safu wima hii",
    "Colonne de fin": "Safu wima ya mwisho",
    "Les tâches dans cette colonne sont considérées comme terminées": "Kazi katika safu wima hii zinachukuliwa kuwa zimekamilika",
    "Colonne": "Safu wima",
    "Heures estimées": "Masaa yanayokadiriwa",
    "Temps passé": "Muda uliotumika",
    "Tâche parent": "Kazi kuu",
    "URLs des fichiers attachés": "URL za faili zilizoambatanishwa",
    "Tags et labels pour la catégorisation": "Tagi na lebo kwa uainishaji",
    "Champs personnalisés": "Sehemu maalum",
    "Données contextuelles supplémentaires": "Data ya muktadha ya ziada",
    "Configuration des colonnes": "Usanidi wa safu wima",
    "Configuration JSON des colonnes par défaut": "Usanidi wa JSON wa safu wima chaguo-msingi",
    "Tâches par défaut": "Kazi chaguo-msingi",
    "Tâches prédéfinies à créer avec le template": "Kazi zilizowekwa mapema kuundwa na kiolezo",
    "Template système": "Kiolezo cha mfumo",
    "Schéma de couleurs": "Mpangilio wa rangi",
    "Template de tableau": "Kiolezo cha bodi",
    "Templates de tableaux": "Violezo vya bodi",
    "\n                            Vous avez atteint votre limite de %(limit)s tableau(x). \n                            Mettez à niveau votre abonnement pour créer plus de tableaux.\n                            ": "\n                            Umefikia kikomo chako cha bodi %(limit)s. \n                            Boresha usajili wako ili kuunda bodi zaidi.\n                            ",
    "\n                            Ce tableau a atteint sa limite de %(limit)s tâche(s). \n                            Mettez à niveau votre abonnement pour ajouter plus de tâches.\n                            ": "\n                            Bodi hii imefikia kikomo chake cha kazi %(limit)s. \n                            Boresha usajili wako ili kuongeza kazi zaidi.\n                            ",
    "\n                            Vous utilisez %(current)s/%(limit)s tableaux (%(percentage)s%%). \n                            Pensez à mettre à niveau votre abonnement.\n                            ": "\n                            Unatumia bodi %(current)s/%(limit)s (%(percentage)s%%). \n                            Fikiria kuboresha usajili wako.\n                            ",
    "\n                            Ce tableau utilise %(current)s/%(limit)s tâches (%(percentage)s%%). \n                            Pensez à mettre à niveau votre abonnement.\n                            ": "\n                            Bodi hii inatumia kazi %(current)s/%(limit)s (%(percentage)s%%). \n                            Fikiria kuboresha usajili wako.\n                            ",
    "1 heure": "Saa 1",
    "%(hours)s heures": "Masaa %(hours)s",
    "Dans 1 jour": "Kwa siku 1",
    "Dans %(days)s jours": "Kwa siku %(days)s",
    "Il y a 1 jour": "Siku 1 iliyopita",
    "Il y a %(days)s jours": "Siku %(days)s zilizopita",
    "Modifier la tâche": "Rekebisha kazi",
    "Supprimer la tâche": "Futa kazi",
    "Déplacer la tâche": "Hamisha kazi",
    "Tâche déplacée avec succès": "Kazi imehamishwa kwa mafanikio",
    "Tâche créée avec succès": "Kazi imeundwa kwa mafanikio",
    "Tâche supprimée avec succès": "Kazi imefutwa kwa mafanikio",
    "Tâche mise à jour avec succès": "Kazi imesasishwa kwa mafanikio",
    "Erreur de connexion réseau": "Hitilafu ya muunganisho wa mtandao",
    "Limite WIP dépassée": "Kikomo cha WIP kimepitwa",
    "Êtes-vous sûr de vouloir supprimer cette tâche ?": "Je, una uhakika unataka kufuta kazi hii?",
    "Veuillez patienter...": "Tafadhali subiri...",
    "Aucune modification détectée": "Hakuna mabadiliko yaliyogunduliwa",
    "Tableau mis à jour avec succès": "Bodi imesasishwa kwa mafanikio",
    "Toutes les tâches": "Kazi zote",
    "Mes tâches": "Kazi zangu",
    "jours de retard": "siku za kuchelewa",
    "Afficher plus": "Onyesha zaidi",
    "Afficher moins": "Onyesha kidogo",
    "Vous n'avez pas accès à ce tableau.": "Huna ufikiaji wa bodi hii.",
    "Tableau créé avec succès.": "Bodi imeundwa kwa mafanikio.",
    "Nom et organisation requis": "Jina na shirika vinahitajika",
    "Vous n'avez pas la permission de modifier ce tableau.": "Huna ruhusa ya kurekebisha bodi hii.",
    "Tableau mis à jour avec succès.": "Bodi imesasishwa kwa mafanikio.",
    "Permission insuffisante": "Ruhusa haitoshi",
    "archivé": "imehifadhiwa",
    "désarchivé": "imerejeshwa",
    "Tableau {} avec succès.": "Bodi {} kwa mafanikio.",
    "Tableau '{}' supprimé avec succès.": "Bodi '{}' imefutwa kwa mafanikio.",
    "Colonne ajoutée avec succès.": "Safu wima imeongezwa kwa mafanikio.",
    "Impossible de supprimer une colonne contenant des tâches": "Haiwezekani kufuta safu wima yenye kazi",
    "Un tableau doit avoir au moins une colonne": "Bodi lazima iwe na angalau safu wima moja",
    "Colonne '{}' supprimée avec succès.": "Safu wima '{}' imefutwa kwa mafanikio.",
    "Tableau non trouvé": "Bodi haikupatikana",
    "Format non supporté": "Muundo hauhimiliwi",
    "task_id et column_id requis": "task_id na column_id vinahitajika",
    "Tâche ou colonne non trouvée": "Kazi au safu wima haikupatikana",
    "Limite WIP atteinte pour cette colonne ({}/{})": "Kikomo cha WIP kimefikiwa kwa safu wima hii ({}/{})",
    "Limite WIP invalide": "Kikomo cha WIP batili",
    "Tâche non trouvée": "Kazi haikupatikana",
    "Commentaire ajouté avec succès.": "Maoni yameongezwa kwa mafanikio.",
    "Aucun tableau spécifié.": "Hakuna bodi iliyobainishwa.",
    "Vous n'avez pas la permission de créer des tâches dans ce tableau.": "Huna ruhusa ya kuunda kazi katika bodi hii.",
    "Tâche créée avec succès.": "Kazi imeundwa kwa mafanikio.",
    "Vous n'avez pas la permission de modifier cette tâche.": "Huna ruhusa ya kurekebisha kazi hii.",
    "Tâche mise à jour avec succès.": "Kazi imesasishwa kwa mafanikio.",
    "Impossible de supprimer une tâche ayant des sous-tâches": "Haiwezekani kufuta kazi yenye kazi ndogo",
    "Tâche '{}' supprimée avec succès.": "Kazi '{}' imefutwa kwa mafanikio.",
    "Colonne non trouvée": "Safu wima haikupatikana",
    "column_id requis": "column_id inahitajika",
    "Statut invalide": "Hali batili",
    "Priorité invalide": "Kipaumbele batili",
    "Contenu requis": "Maudhui yanahitajika",
    "Aucune discipline disponible": "Hakuna taaluma inayopatikana",
    "Documents et licences": "Nyaraka na leseni",
    "Statut et métadonnées": "Hali na meta-data",
    "Les champs marqués d'un * sont obligatoires.": "Sehemu zilizo na alama ya * ni za lazima.",
    "Êtes-vous sûr de vouloir supprimer cette compétition ?": "Je, una uhakika unataka kufuta mashindano haya?",
    "Cette fonctionnalité": "Kipengele hiki",
    "La modification des détails": "Kurekebisha maelezo",
    "La planification": "Upangaji",
    "Le partage": "Kushiriki",
    "est en cours de développement.": "inaendelezwa.",
    "Détail de la compétition": "Maelezo ya mashindano",
    "Aucun participant inscrit": "Hakuna mshiriki aliyesajiliwa",
    "Aucun juge/arbitre assigné": "Hakuna hakimu/mwamuzi aliyegawiwa",
    "Le nom du pays doit contenir au moins 2 caractères.": "Jina la nchi lazima liwe na angalau herufi 2.",
    "Gestion des rapports": "Usimamizi wa ripoti",
    "Welcome": "Karibu",
    "À définir": "Itabainishwa",
    "Aucun type de compétition trouvé. Créez votre premier type pour organiser les catégories.": "Hakuna aina ya mashindano iliyopatikana. Unda aina yako ya kwanza kupanga makundi.",
    "Aucune catégorie trouvée. Créez votre première catégorie pour organiser les participants.": "Hakuna kundi lililopatikana. Unda kundi lako la kwanza kupanga washiriki.",
    "Recrutez des pratiquants adultes (18+) présents à la compétition pour servir comme juges temporaires.": "Ajiri watendaji watu wazima (18+) waliopo kwenye mashindano kutumika kama mahakimu wa muda.",
    "Glisser jusqu'à 4 juges": "Buruta hadi mahakimu 4",
    "Expérimenté": "Mwenye uzoefu",
    "Activer immédiatement (crée un compte si nécessaire)": "Washa mara moja (inaunda akaunti ikiwa ni lazima)",
    "État": "Hali",
    "Créer": "Unda",
    "Envoyer une notification à tous les participants inscrits ?": "Tuma arifa kwa washiriki wote waliosajiliwa?",
    "Génération de la programmation en cours...": "Uzalishaji wa ratiba unaendelea...",
    "Voulez-vous publier tous les résultats ? Ils seront visibles publiquement.": "Je, unataka kuchapisha matokeo yote? Yataonekana hadharani.",
    "Décliné": "Imekataliwa",
    "Êtes-vous sûr de vouloir vous déconnecter de MartialComp ? Vous devrez vous reconnecter pour accéder à votre compte.": "Je, una uhakika unataka kutoka kwenye MartialComp? Utahitaji kuingia tena kufikia akaunti yako.",
    "Oui, me déconnecter": "Ndiyo, niondoe",
    "Annuler et rester connecté": "Ghairi na ubaki umeingia",
    "Autre compte": "Akaunti nyingine",
    "\n            Dans %(days)s jours, vous serez eligible au passage de grade %(grade)s.\n            ": "\n            Kwa siku %(days)s, utakuwa na sifa za kupita daraja %(grade)s.\n            ",
    "jours avant eligibilite": "siku kabla ya kustahiki",
    "\n            Vous serez eligible au grade %(grade)s dans %(days)s jours.\n            ": "\n            Utakuwa na sifa za daraja %(grade)s kwa siku %(days)s.\n            ",
    "\n            Vous remplissez toutes les conditions pour passer au grade %(grade)s !\n            ": "\n            Unatimiza masharti yote ya kupita daraja %(grade)s!\n            ",
    "\n            L'inscription a l'examen \"%(exam)s\" ferme dans %(days)s jours (%(deadline)s).\n            ": "\n            Usajili wa mtihani \"%(exam)s\" unafungwa kwa siku %(days)s (%(deadline)s).\n            ",
    "\n            La date limite d'inscription a l'examen \"%(exam)s\" approche : %(deadline)s.\n            ": "\n            Tarehe ya mwisho ya usajili wa mtihani \"%(exam)s\" inakaribia: %(deadline)s.\n            ",
    "\n            Votre examen \"%(exam)s\" a lieu demain a %(location)s.\n            ": "\n            Mtihani wako \"%(exam)s\" unafanyika kesho katika %(location)s.\n            ",
    "Bonne chance !": "Bahati njema!",
    "\n            Vous avez reussi votre examen et obtenu le grade %(grade)s !\n            ": "\n            Umefaulu mtihani wako na kupata daraja %(grade)s!\n            ",
    "\n            Vous n'avez pas obtenu le grade %(grade)s cette fois-ci.\n            ": "\n            Hukupata daraja %(grade)s wakati huu.\n            ",
    "Continuez vos efforts ! Vous pouvez vous inscrire au prochain examen.": "Endelea na juhudi zako! Unaweza kusajiliwa kwa mtihani ujao.",
    "\n            Vous etes eligible au grade %(grade)s depuis %(days)s jours.\n            ": "\n            Umekuwa na sifa za daraja %(grade)s kwa siku %(days)s.\n            ",
    "PROGRESSION DE GRADE": "MAENDELEO YA DARAJA",
    "Dans %(days)s jours, vous serez eligible au passage de grade %(grade)s.": "Kwa siku %(days)s, utakuwa na sifa za kupita daraja %(grade)s.",
    "ELIGIBILITE PROCHE": "KUSTAHIKI KUNAKARIBIA",
    "Vous serez eligible au grade %(grade)s dans %(days)s jours.": "Utakuwa na sifa za daraja %(grade)s kwa siku %(days)s.",
    "FELICITATIONS !": "HONGERA!",
    "Vous remplissez toutes les conditions pour passer au grade %(grade)s !": "Unatimiza masharti yote ya kupita daraja %(grade)s!",
    "URGENT : INSCRIPTION EXAMEN": "HARAKA: USAJILI WA MTIHANI",
    "L'inscription a l'examen \"%(exam)s\" ferme dans %(days)s jours (%(deadline)s).": "Usajili wa mtihani \"%(exam)s\" unafungwa kwa siku %(days)s (%(deadline)s).",
    "RAPPEL INSCRIPTION EXAMEN": "KUMBUSHO LA USAJILI WA MTIHANI",
    "RAPPEL : EXAMEN DEMAIN": "KUMBUSHO: MTIHANI KESHO",
    "Votre examen \"%(exam)s\" a lieu demain a %(location)s.": "Mtihani wako \"%(exam)s\" unafanyika kesho katika %(location)s.",
    "Vous avez reussi votre examen et obtenu le grade %(grade)s !": "Umefaulu mtihani wako na kupata daraja %(grade)s!",
    "RESULTAT D'EXAMEN": "MATOKEO YA MTIHANI",
    "RAPPEL MENSUEL": "KUMBUSHO LA KILA MWEZI",
    "Vous etes eligible au grade %(grade)s depuis %(days)s jours.": "Umekuwa na sifa za daraja %(grade)s kwa siku %(days)s.",
    "\n                        Bonjour, %(name)s!\n                    ": "\n                        Habari, %(name)s!\n                    ",
}
