# -*- coding: utf-8 -*-
TRANSLATIONS = {
    "Dernier contrôle": "Udhibiti wa mwisho",
    "Apte": "Anafaa",
    "À renouveler": "Inahitaji kuhuishwa",
    "Informations Sportives": "Taarifa za Michezo",
    "Qualification Juge / Arbitre": "Sifa za Hakimu / Mwamuzi",
    "Meilleur résultat:": "Matokeo bora:",
    "Statistiques Combat": "Takwimu za Mapigano",
    "Nuls": "Sare",
    "Taux de victoire:": "Kiwango cha ushindi:",
    "Dernières participations": "Ushiriki wa hivi karibuni",
    "Aucun résultat enregistré": "Hakuna matokeo yaliyorekodiwa",
    "Évolution des classements": "Mabadiliko ya vyeo",
    "Pas encore de palmarès": "Hakuna rekodi ya tuzo bado",
    "Les résultats des compétitions apparaîtront ici.": "Matokeo ya mashindano yataonekana hapa.",
    "Renouvellement auto": "Kuhuisha kiotomatiki",
    "Montant adhésion": "Kiasi cha uanachama",
    "Aucune adhésion enregistrée": "Hakuna uanachama uliorekodiwa",
    "Total payé": "Jumla iliyolipwa",
    "Total dû": "Jumla inayodaiwa",
    "Données non disponibles": "Data haipatikani",
    "Échéance:": "Tarehe ya mwisho:",
    "Générer facture": "Zalisha ankara",
    "Module finances non disponible": "Moduli ya fedha haipatikani",
    "Les données financières ne sont pas disponibles pour ce pratiquant.": "Data za kifedha hazipatikani kwa mtendaji huyu.",
    "Documents du pratiquant": "Hati za mtendaji",
    "Non téléchargé": "Haijapakiwa",
    "Requis - Non téléchargé": "Inahitajika - Haijapakiwa",
    "Photo d'identité": "Picha ya kitambulisho",
    "Téléchargée": "Imepakiwa",
    "Non téléchargée": "Haijapakiwa",
    "Gérer les documents": "Simamia hati",
    "Total dépensé": "Jumla iliyotumika",
    "Article favori:": "Bidhaa inayopendwa:",
    "achetés": "zilizohununuliwa",
    "commande(s) en attente de livraison": "oda inayosubiri uwasilishaji",
    "Historique des commandes": "Historia ya oda",
    "Aucune commande dans l'historique": "Hakuna oda katika historia",
    "Pas encore de commandes": "Hakuna oda bado",
    "Les commandes de la boutique apparaîtront ici.": "Oda za duka zitaonekana hapa.",
    "Carte d'identité sportive": "Kadi ya kitambulisho cha michezo",
    "Né(e) le:": "Alizaliwa:",
    "Générer QR Code": "Zalisha QR Code",
    "Caractères autorisés : lettres minuscules, chiffres, point et underscore": "Herufi zinazoruhusiwa: herufi ndogo, nambari, nukta na mstari wa chini",
    "Générer un mot de passe personnalisé": "Zalisha nenosiri maalum",
    "Mot de passe personnalisé": "Nenosiri maalum",
    "Aucun email renseigné. Les identifiants ne pourront pas être envoyés automatiquement.": "Hakuna barua pepe iliyotolewa. Vitambulisho havitaweza kutumwa kiotomatiki.",
    "Envoyer les identifiants par email": "Tuma vitambulisho kwa barua pepe",
    "Le pratiquant devra changer son mot de passe à la première connexion.": "Mtendaji atalazimika kubadilisha nenosiri lake wakati wa kuingia kwa mara ya kwanza.",
    "Les identifiants ont été envoyés par email.": "Vitambulisho vimetumwa kwa barua pepe.",
    "Notez ces identifiants ! Le mot de passe ne pourra plus être affiché après fermeture de cette fenêtre.": "Andika vitambulisho hivi! Nenosiri halitaweza kuonyeshwa tena baada ya kufunga dirisha hili.",
    "Un compte utilisateur correspondant a été trouvé dans le système.": "Akaunti ya mtumiaji inayolingana imepatikana katika mfumo.",
    "Compte détecté": "Akaunti imegunduliwa",
    "Confirmer la liaison": "Thibitisha muunganisho",
    "Attribuer le rôle Juge/Arbitre": "Gawa jukumu la Hakimu/Mwamuzi",
    "Peut noter les techniques et formes": "Anaweza kutoa alama za mbinu na fomu",
    "Peut arbitrer les combats": "Anaweza kuamua mapigano",
    "Ex: JF-2024-001": "Mfano: JF-2024-001",
    "Notes optionnelles...": "Maelezo ya hiari...",
    "Ex: Cotisation annuelle 2024-2025": "Mfano: Michango ya kila mwaka 2024-2025",
    "Envoyer un rappel de paiement": "Tuma ukumbusho wa malipo",
    "Un email de rappel sera envoyé à": "Barua pepe ya ukumbusho itatumwa kwa",
    "Ce pratiquant n'a pas d'adresse email. Impossible d'envoyer un rappel.": "Mtendaji huyu hana anwani ya barua pepe. Haiwezekani kutuma ukumbusho.",
    "Paiement dû": "Malipo yanayodaiwa",
    "Adhésion expirant bientôt": "Uanachama unaoisha hivi karibuni",
    "Message personnalisé (optionnel)": "Ujumbe maalum (hiari)",
    "Ajoutez un message personnalisé au rappel...": "Ongeza ujumbe maalum kwenye ukumbusho...",
    "Paiement enregistré avec succès": "Malipo yamerekodiwa kwa mafanikio",
    "Erreur lors de l'enregistrement": "Hitilafu wakati wa kurekodi",
    "Une erreur est survenue": "Hitilafu imetokea",
    "Rappel envoyé avec succès": "Ukumbusho umetumwa kwa mafanikio",
    "Erreur lors de l'envoi": "Hitilafu wakati wa kutuma",
    "Classement moyen": "Cheo cha wastani",
    "Choisir une photo": "Chagua picha",
    "Prendre une photo": "Piga picha",
    "Sélectionnez d'abord une discipline, puis choisissez un grade. Ce grade sera utilisé comme référence principale dans les listes et compétitions.": "Chagua kwanza taaluma, kisha chagua daraja. Daraja hili litatumika kama rejea kuu katika orodha na mashindano.",
    "Cliquez sur Générer pour obtenir un numéro unique selon la discipline, le club et la date de naissance.": "Bofya Zalisha kupata nambari ya kipekee kulingana na taaluma, klabu na tarehe ya kuzaliwa.",
    "Si ce pratiquant est également un juge ou arbitre, vous pouvez définir ses qualifications ici. Ces informations seront utilisées pour les affectations lors des compétitions.": "Ikiwa mtendaji huyu pia ni hakimu au mwamuzi, unaweza kufafanua sifa zake hapa. Taarifa hizi zitatumika kwa ugawaji wakati wa mashindano.",
    "Ce pratiquant est un juge/arbitre": "Mtendaji huyu ni hakimu/mwamuzi",
    "Peut juger les épreuves techniques (formes, katas, quyen...)": "Anaweza kuamua mashindano ya ufundi (fomu, kata, quyen...)",
    "Peut arbitrer les épreuves de combat": "Anaweza kuamua mashindano ya mapigano",
    "Numéro officiel de certification de juge": "Nambari rasmi ya uthibitisho wa hakimu",
    "Décochez si le juge n'est plus disponible pour les affectations": "Ondoa alama ikiwa hakimu hapatikani tena kwa ugawaji",
    "Notes sur la qualification": "Maelezo kuhusu sifa",
    "Informations complémentaires sur les qualifications, formations suivies, etc.": "Taarifa za ziada kuhusu sifa, mafunzo yaliyofuatwa, n.k.",
    "Capturer": "Nasa",
    "Veuillez sélectionner au moins une discipline pour le pratiquant.": "Tafadhali chagua angalau taaluma moja kwa mtendaji.",
    "Un ou plusieurs champs nécessaires sont introuvables dans le formulaire (date de naissance, disciplines, nom de famille).": "Sehemu moja au zaidi zinazohitajika hazipatikani kwenye fomu (tarehe ya kuzaliwa, taaluma, jina la ukoo).",
    "Veuillez renseigner la date de naissance, sélectionner au moins une discipline et indiquer le nom de famille.": "Tafadhali jaza tarehe ya kuzaliwa, chagua angalau taaluma moja na uonyeshe jina la ukoo.",
    "Génération...": "Kuzalisha...",
    "Généré": "Imezalishwa",
    "Erreur lors de la génération du numéro :": "Hitilafu wakati wa kuzalisha nambari:",
    "Réponse inattendue du serveur": "Jibu lisilotarajiwa kutoka seva",
    "Erreur lors de la génération du numéro de licence :": "Hitilafu wakati wa kuzalisha nambari ya leseni:",
    "Le fichier est trop volumineux. Taille maximum: 5 MB. Compression en cours...": "Faili ni kubwa sana. Ukubwa wa juu: MB 5. Upunguzaji unaendelea...",
    "Accès à la caméra refusé. Veuillez autoriser l'accès dans les paramètres de votre navigateur.": "Ufikiaji wa kamera umekataliwa. Tafadhali ruhusu ufikiaji katika mipangilio ya kivinjari chako.",
    "Erreur lors de l'accès à la caméra:": "Hitilafu wakati wa kufikia kamera:",
    "\n                        Ajouter une nouvelle qualification pour %(name)s\n                        ": "\n                        Ongeza sifa mpya kwa %(name)s\n                        ",
    "\n                        Historique des inscriptions de %(name)s\n                        ": "\n                        Historia ya usajili wa %(name)s\n                        ",
    "\n                            %(name)s n'a encore aucune inscription enregistrée.\n                            ": "\n                            %(name)s bado hana usajili wowote uliorekodiwa.\n                            ",
    "Inscription annulée": "Usajili umeghairiwa",
    "\n                    Affichage de %(start)s à %(end)s sur %(total)s pratiquants\n                ": "\n                    Kuonyesha %(start)s hadi %(end)s kati ya watendaji %(total)s\n                ",
    "Qualification active": "Sifa hai",
    "Vous avez déjà envoyé des demandes à toutes les fédérations disponibles": "Tayari umetuma maombi kwa mashirikisho yote yanayopatikana",
    "Renouvellement": "Kuhuisha",
    "En soumettant cette demande, la fédération sera notifiée. Une fois approuvée, vous recevrez une facture pour le paiement de la cotisation.": "Kwa kuwasilisha ombi hili, shirikisho litaarifiwa. Likishaidhinishwa, utapokea ankara ya malipo ya michango.",
    "Ex: Tatami 1, Zone A, Aire Combat Principal": "Mfano: Tatami 1, Eneo A, Eneo Kuu la Mapigano",
    "Sélectionnez les catégories qui seront gérées sur cette aire. Seuls les combats de ces catégories seront visibles.": "Chagua kategoria zitakazosimamiwa katika eneo hili. Mapigano ya kategoria hizi peke yake yataonekana.",
    "En régénérant, l'ancien lien et PIN ne fonctionneront plus.": "Kwa kuzalisha upya, kiungo cha zamani na PIN hazitafanya kazi tena.",
    "Créez des aires de combat pour permettre aux arbitres d'accéder à leurs catégories via un simple code PIN, sans avoir besoin de vos identifiants.": "Unda maeneo ya mapigano ili kuruhusu waamuzi kufikia kategoria zao kupitia msimbo wa PIN rahisi, bila kuhitaji vitambulisho vyako.",
    "Cette action annulera définitivement le combat. Cette opération ne peut pas être annulée.": "Kitendo hiki kitaghairi pigano kabisa. Operesheni hii haiwezi kughairiwa.",
    "Informations sur le combat": "Taarifa kuhusu pigano",
    "Participants :": "Washiriki:",
    "Statut actuel :": "Hali ya sasa:",
    "Score actuel :": "Alama ya sasa:",
    "Date prévue :": "Tarehe iliyopangwa:",
    "Indiquez la raison de l'annulation :": "Onyesha sababu ya kughairi:",
    "Ex: Blessure d\\'": "Mfano: Jeraha la\\'",
    "Ce motif sera enregistré avec l'annulation du combat.": "Sababu hii itarekodiwa na kughairiwa kwa pigano.",
    "Retour au combat": "Rudi kwenye pigano",
    "Prêts & Fusions": "Ukopeshaji na Muungano",
    "Ententes (Prêts)": "Makubaliano (Ukopeshaji)",
    "Remise des Prix": "Sherehe ya Tuzo",
    "Pos.": "Naf.",
    "Pts+": "Pnt+",
    "Pts-": "Pnt-",
    "Le classement sera disponible dès que des combats seront terminés.": "Cheo kitapatikana mara mapigano yatakapomalizika.",
    "Gérer le mode combat (équipe ou individuel) pour chaque catégorie": "Simamia aina ya mapigano (timu au mtu binafsi) kwa kila kategoria",
    "Chaque catégorie peut fonctionner en mode équipe ou Individuel indépendamment.": "Kila kategoria inaweza kufanya kazi katika aina ya timu au Mtu binafsi kwa kujitegemea.",
    "Les pratiquants sont regroupés en équipes. Les scores sont cumulés par équipe.": "Watendaji wamepangwa katika timu. Alama zinajumlishwa kwa timu.",
    "Chaque pratiquant combat individuellement. Les scores sont personnels.": "Kila mtendaji anapigana kibinafsi. Alama ni za kibinafsi.",
    "Êtes-vous sûr de vouloir basculer la catégorie": "Je, una uhakika unataka kubadilisha kategoria",
    "vers le mode": "kwenda aina ya",
    "Nombre de poules": "Idadi ya makundi",
    "Les équipes et les inscriptions des participants ne seront pas affectées. Vous pourrez régénérer les poules après cette opération.": "Timu na usajili wa washiriki hazitaathiriwa. Utaweza kuzalisha upya makundi baada ya operesheni hii.",
    "Équipes par catégorie": "Timu kwa kategoria",
    "remplaçants": "wabadala",
    "Termines": "Zilizomalizika",
    "Planifies": "Zilizopangwa",
    "Aucun participant n'a ete ajoute a cette poule.": "Hakuna mshiriki aliyeongezwa katika kundi hili.",
    "Non planifie": "Haijapangwa",
    "Termine": "Imemalizika",
    "Annule": "Imeghairiwa",
    "Planifie": "Imepangwa",
    "Details": "Maelezo",
    "Aucun combat": "Hakuna pigano",
    "Aucun combat n'a ete cree pour cette poule.": "Hakuna pigano lililoundwa kwa kundi hili.",
    "Creer le premier combat": "Unda pigano la kwanza",
    "Coin Rouge": "Kona Nyekundu",
    "Coin Blanc": "Kona Nyeupe",
    "Une entente permet de prêter temporairement un pratiquant d'un club à un autre pour une compétition spécifique.": "Makubaliano yanaruhusu kukopesha kwa muda mtendaji kutoka klabu moja kwenda nyingine kwa mashindano maalum.",
    "-- À définir plus tard --": "-- Itafafanuliwa baadaye --",
    "L'équipe peut être assignée après validation de l'entente": "Timu inaweza kugawiwa baada ya kuthibitisha makubaliano",
    "Modifiez les informations de l'équipe": "Rekebisha taarifa za timu",
    "Créez une nouvelle équipe pour la compétition": "Unda timu mpya kwa mashindano",
    "Informations de l'équipe": "Taarifa za timu",
    "Aucune compétition disponible. Vous devez d'abord créer une compétition avant de pouvoir créer des équipes.": "Hakuna mashindano yanayopatikana. Lazima uunde mashindano kwanza kabla ya kuweza kuunda timu.",
    "Créez une compétition en premier": "Unda mashindano kwanza",
    "--- Sélectionnez une catégorie ---": "--- Chagua kategoria ---",
    "Une fusion permet de combiner deux équipes avec un effectif insuffisant en une seule équipe complète.": "Muungano unaruhusu kuunganisha timu mbili zenye idadi duni ya wanachama kuwa timu moja kamili.",
    "Équipes avec effectif insuffisant:": "Timu zenye idadi duni ya wanachama:",
    "Nom proposé pour l'équipe fusionnée": "Jina lililopendekezwa kwa timu iliyounganishwa",
    "Ex: Équipe A / Équipe B": "Mfano: Timu A / Timu B",
    "Ex: Effectif insuffisant pour constituer des équipes complètes...": "Mfano: Idadi haitoshi kuunda timu kamili...",
    "Position et role": "Nafasi na jukumu",
    "Position du membre (1, 2, 3...)": "Nafasi ya mwanachama (1, 2, 3...)",
    "Role specifique (attaquant, defenseur, etc.)": "Jukumu maalum (mshambuliaji, mlinzi, n.k.)",
    "Statut du membre": "Hali ya mwanachama",
    "Remplacant": "Mbadala",
    "Ce membre est un remplacant (non titulaire)": "Mwanachama huyu ni mbadala (si wa msingi)",
    "Attention: Il ne peut y avoir qu\\'un seul capitaine par equipe. Le capitaine actuel sera remplace.": "Tahadhari: Kunaweza kuwa na nahodha mmoja peke yake kwa timu. Nahodha wa sasa atabadilishwa.",
    "Équipes": "Timu",
    "Sélectionnez combien de participants de chaque poule seront qualifiés pour la phase finale.": "Chagua washiriki wangapi kutoka kila kundi watakaostahiki kwa awamu ya mwisho.",
    "Le classement de chaque poule est calculé automatiquement (victoires, différence de points)": "Cheo cha kila kundi huhesabiwa kiotomatiki (ushindi, tofauti ya pointi)",
    "Les N premiers de chaque poule sont qualifiés": "Wa kwanza N kutoka kila kundi wanastahiki",
    "Les combats sont générés avec croisement (1er poule A vs 2ème poule B)": "Mapigano yanazalishwa kwa mvuko (wa kwanza kundi A dhidi ya wa pili kundi B)",
    "La phase créée dépend du nombre de qualifiés:": "Awamu iliyoundwa inategemea idadi ya waliostahiki:",
    "Tous les combats des poules éliminatoires doivent être terminés avant de générer la phase finale.": "Mapigano yote ya makundi ya kufutwa lazima yamalizike kabla ya kuzalisha awamu ya mwisho.",
    "Avec": "Na",
    "qualifiés par poule:": "waliostahiki kwa kundi:",
    "Cette fonction analyse chaque catégorie combat et génère automatiquement des poules en fonction du nombre d'équipes ou de participants.": "Kazi hii inachambua kila kategoria ya mapigano na kuzalisha kiotomatiki makundi kulingana na idadi ya timu au washiriki.",
    "Éviter les équipes du même club dans la même poule": "Epuka timu za klabu moja katika kundi moja",
    "Tente de répartir les équipes pour qu'un club n'ait pas plusieurs équipes dans la même poule.": "Inajaribu kugawanya timu ili klabu isiwe na timu nyingi katika kundi moja.",
    "environ 4 par poule": "takriban 4 kwa kundi",
    "ÉGALITÉ ! Lancer une prolongation": "SARE! Anza muda wa ziada",
    "ÉQUIPE ROUGE": "TIMU NYEKUNDU",
    "Terminer Combat": "Maliza Pigano",
    "ÉQUIPE BLANCHE": "TIMU NYEUPE",
    "Équipe Blanc": "Timu Nyeupe",
    "REPRENDRE": "ENDELEA",
    "Réinitialiser le chronomètre ?": "Weka upya kipima muda?",
    "3 sorties ! Pénalité de -0.5 appliquée pour ROUGE": "Kutoka 3! Adhabu ya -0.5 imetolewa kwa NYEKUNDU",
    "3 sorties ! Pénalité de -0.5 appliquée pour BLANC": "Kutoka 3! Adhabu ya -0.5 imetolewa kwa NYEUPE",
    "Combat terminé !": "Pigano limemalizika!",
    "Mettez le combat en pause avant de changer la durée": "Weka pigano katika pumziko kabla ya kubadilisha muda",
    "PROLONGATION": "MUDA WA ZIADA",
    "Entrez le code PIN à 4 chiffres fourni par l'organisateur": "Ingiza msimbo wa PIN wa nambari 4 uliotolewa na mwandaaji",
    "Simulation": "Uigaji",
    "Auto-refresh": "Upya kiotomatiki",
    "Total combats": "Jumla ya mapigano",
    "Mode Simulation Activé": "Aina ya Uigaji Imewashwa",
    "Ce mode simule des actions de combat pour visualiser le comportement en temps réel.": "Aina hii inaiga vitendo vya mapigano kuonyesha tabia kwa wakati halisi.",
    "Aucun combat trouvé": "Hakuna pigano lililopatikana",
    "Liste de toutes les équipes": "Orodha ya timu zote",
    "Vue par catégorie": "Mtazamo kwa kategoria",
    "Équipes totales": "Jumla ya timu",
    "Équipes non assignées": "Timu ambazo hazijagawiwa",
    "Équipes sans catégorie": "Timu bila kategoria",
    "Planification des combats": "Kupanga mapigano",
    "Poule complète:": "Kundi kamili:",
    "Aucune catégorie définie pour cette compétition": "Hakuna kategoria iliyofafanuliwa kwa mashindano haya",
    "Voir les catégories": "Tazama kategoria",
    "Aucune équipe n'a été créée": "Hakuna timu iliyoundwa",
    "Équipes avec effectif insuffisant": "Timu zenye idadi duni ya wanachama",
    "Ces équipes pourraient bénéficier d'une fusion:": "Timu hizi zinaweza kufaidika na muungano:",
    "Cette action va créer une nouvelle équipe fusionnée. Continuer ?": "Kitendo hiki kitaunda timu mpya iliyounganishwa. Endelea?",
    "Des équipes ont un effectif insuffisant et pourraient être fusionnées.": "Timu zina idadi duni ya wanachama na zinaweza kuunganishwa.",
    "Liste des poules": "Orodha ya makundi",
    "Seuls les types de compétition 'Combat' peuvent avoir des poules. Les compétitions techniques ne nécessitent pas de poules.": "Aina za mashindano ya 'Mapigano' peke yake zinaweza kuwa na makundi. Mashindano ya ufundi hayahitaji makundi.",
    "Étape 2: Choisir le mode de génération": "Hatua ya 2: Chagua aina ya kuzalisha",
    "Chaque équipe contre toutes les autres": "Kila timu dhidi ya nyingine zote",
    "Moins de combats, plus rapide": "Mapigano machache, kwa haraka zaidi",
    "Attention: La génération automatique supprimera toutes les poules existantes pour les types sélectionnés.": "Tahadhari: Kuzalisha kiotomatiki kutafuta makundi yote yaliyopo kwa aina zilizochaguliwa.",
    "Générer les demi-finales et la finale pour cette catégorie? Les 2 premiers de chaque poule seront qualifiés.": "Zalisha nusu fainali na fainali kwa kategoria hii? Wa kwanza 2 kutoka kila kundi watastahiki.",
    "Promouvoir les vainqueurs des demi-finales vers la finale?": "Pandisha washindi wa nusu fainali kwenda fainali?",
    "Vous pouvez créer des poules manuellement ou les générer automatiquement par catégorie.": "Unaweza kuunda makundi kwa mkono au kuyazalisha kiotomatiki kwa kategoria.",
    "Chaque équipe affronte toutes les autres (round-robin complet). Plus de combats, classement précis.": "Kila timu inakutana na nyingine zote (round-robin kamili). Mapigano zaidi, cheo sahihi.",
    "Chaque équipe fait 2 combats minimum puis demi-finales et finale. Rapide et efficace.": "Kila timu inafanya mapigano 2 ya chini kisha nusu fainali na fainali. Haraka na bora.",
    "poule(s) et": "kundi (makundi) na",
    "Cérémonie Podium": "Sherehe ya Jukwaa la Tuzo",
    "Attendez que les catégories soient terminées pour lancer la cérémonie.": "Subiri kategoria zimalizike ili kuanza sherehe.",
    "Cérémonie de Remise des Prix": "Sherehe ya Kutoa Tuzo",
    "Pas encore de résultats": "Hakuna matokeo bado",
    "Cette catégorie n'a pas encore de résultats à afficher.": "Kategoria hii bado haina matokeo ya kuonyesha.",
    "Utilisez les flèches pour passer à une autre catégorie.": "Tumia mishale kupita kwenye kategoria nyingine.",
    "Révéler le podium": "Fichua jukwaa la tuzo",
    "Cliquez ou appuyez sur Espace pour révéler progressivement": "Bofya au bonyeza Nafasi kufichua hatua kwa hatua",
    "Naviguez vers une catégorie avec des résultats": "Elekea kwenye kategoria yenye matokeo",
    "Révéler": "Fichua",
    "Podium complet": "Jukwaa la tuzo kamili",
    "N": "S",
    "Diff. pts": "Tofauti pnt",
    "Vue d'ensemble des Podiums": "Muhtasari wa Majukwaa ya Tuzo",
    "Récapitulatif de tous les podiums de la compétition": "Muhtasari wa majukwaa yote ya tuzo ya mashindano",
    "Lancer la Cérémonie": "Anza Sherehe",
    "Aucune catégorie terminée": "Hakuna kategoria iliyomalizika",
    "Les podiums apparaîtront une fois les catégories terminées.": "Majukwaa ya tuzo yataonekana kategoria zitakapomalizika.",
    "Régénérer tous les combats de cette poule ? Les combats existants seront supprimés.": "Zalisha upya mapigano yote ya kundi hili? Mapigano yaliyopo yatafutwa.",
    "Choisissez une compétition pour voir les équipes groupées par catégorie": "Chagua mashindano ili kuona timu zilizopangwa kwa kategoria",
    "Choisissez une compétition pour gérer ses équipes": "Chagua mashindano kusimamia timu zake",
    "Les équipes sont organisées par compétition. Sélectionnez une compétition ci-dessous pour accéder à ses équipes.": "Timu zimepangwa kwa mashindano. Chagua mashindano hapa chini kufikia timu zake.",
    "Voir par catégorie": "Tazama kwa kategoria",
    "Voir les équipes": "Tazama timu",
    "Créez d'abord une compétition pour pouvoir gérer les équipes.": "Unda kwanza mashindano ili uweze kusimamia timu.",
    "Suivi en direct": "Ufuatiliaji wa moja kwa moja",
    "SUIVI EN DIRECT": "UFUATILIAJI WA MOJA KWA MOJA",
    "Actualisation auto. 10s": "Upya kiotomatiki. 10s",
    "combats termines": "mapigano yaliyomalizika",
    "termines": "yaliyomalizika",
    "planifies": "yaliyopangwa",
    "Demarrer": "Anza",
    "Aucun combat dans cette poule": "Hakuna pigano katika kundi hili",
    "Classement actuel": "Cheo cha sasa",
    "Pts": "Pnt",
    "Classement disponible pour les combats individuels": "Cheo kinapatikana kwa mapigano ya mtu binafsi",
    "Le combattant rouge est disqualifié en raison du nombre d\\'avertissements.": "Mpigaji mwekundu amefukuzwa kwa sababu ya idadi ya maonyo.",
    "Le combattant bleu est disqualifié en raison du nombre d\\'avertissements.": "Mpigaji bluu amefukuzwa kwa sababu ya idadi ya maonyo.",
    "\n                        Du %(start)s au %(end)s\n                    ": "\n                        Kutoka %(start)s hadi %(end)s\n                    ",
    "Gérer les types de compétition": "Simamia aina za mashindano",
    "Entrez une adresse...": "Ingiza anwani...",
    "Image de bannière": "Picha ya bango",
    "Format recommandé: 1200x300px, max 5MB. Formats acceptés: JPG, PNG, GIF": "Muundo unaopendekezwa: 1200x300px, upeo MB 5. Muundo unaokubaliwa: JPG, PNG, GIF",
    "Bannière actuelle:": "Bango la sasa:",
    "Avec poids": "Na uzito",
    "Aucun participant inscrit pour le moment": "Hakuna mshiriki aliyesajiliwa kwa sasa",
    "Juges et Arbitres inscrits": "Waamuzi na Wasimamizi waliosajiliwa",
    "Aucun juge ou arbitre inscrit pour le moment": "Hakuna hakimu au mwamuzi aliyesajiliwa kwa sasa",
    "Ex: 60": "Mfano: 60",
    "Ex: 70": "Mfano: 70",
    "Erreur lors de l'ajout du type": "Hitilafu wakati wa kuongeza aina",
    "Erreur lors de la suppression du type": "Hitilafu wakati wa kufuta aina",
    "Erreur lors de l'ajout de la catégorie": "Hitilafu wakati wa kuongeza kategoria",
    "Commencez par créer votre première compétition.": "Anza kwa kuunda mashindano yako ya kwanza.",
    "Aucun type de compétition disponible": "Hakuna aina ya mashindano inayopatikana",
    "Mes Pratiquants": "Watendaji Wangu",
    "Glissez-déposez les pratiquants ici": "Buruta na udondoshe watendaji hapa",
    "Ce pratiquant est déjà inscrit": "Mtendaji huyu tayari amesajiliwa",
    "Veuillez inscrire au moins un pratiquant": "Tafadhali sajili angalau mtendaji mmoja",
    "Erreur lors de l enregistrement": "Hitilafu wakati wa kurekodi",
    "Supprimer le type de compétition": "Futa aina ya mashindano",
    "\n                            Ce type de compétition est utilisé par %(counter)s compétition. \n                            La suppression n'est pas recommandée.\n                        ": "\n                            Aina hii ya mashindano inatumika na mashindano %(counter)s. \n                            Kufuta hakupendekezwi.\n                        ",
    "Compétition par équipe": "Mashindano ya timu",
    "Compétition individuelle": "Mashindano ya mtu binafsi",
    "Taille d'équipe": "Ukubwa wa timu",
    "Maximum": "Upeo",
    "Nouveau type": "Aina mpya",
    "Aucun type de compétition trouvé": "Hakuna aina ya mashindano iliyopatikana",
    "Pagination des types de compétition": "Upaginishaji wa aina za mashindano",
    "Today": "Leo",
    "Deadline": "Tarehe ya mwisho",
    "Les tiers peuvent vérifier ce certificat en utilisant ce code sur notre page de vérification publique.": "Wahusika wengine wanaweza kuthibitisha cheti hiki kwa kutumia msimbo huu kwenye ukurasa wetu wa uthibitishaji wa umma.",
    "Êtes-vous sûr de vouloir suspendre ce certificat ? Le bénéficiaire ne pourra plus l'utiliser jusqu'à sa réactivation.": "Je, una uhakika unataka kusimamisha cheti hiki? Mnufaika hataweza kukitumia tena hadi kitakapowashwa upya.",
    "Ex: Tenue, protections, documents...": "Mfano: Mavazi, kinga, hati...",
    "Le numéro de certificat et le code de vérification seront générés automatiquement lors de l'émission.": "Nambari ya cheti na msimbo wa uthibitishaji vitazalishwa kiotomatiki wakati wa kutolewa.",
    "Bas gauche": "Chini kushoto",
    "Cliquez pour modifier le logo": "Bofya kurekebisha nembo",
    "Cliquez pour ajouter un logo": "Bofya kuongeza nembo",
    "Modifier le logo": "Rekebisha nembo",
    "Supprimer le logo": "Futa nembo",
    "Basculer le thème": "Badilisha mandhari",
    "Toutes les fonctionnalités de gestion sont accessibles depuis les menus déroulants de chaque compétition": "Vipengele vyote vya usimamizi vinapatikana kutoka menyu za kushuka za kila mashindano",
    "Cliquez pour gérer cette compétition": "Bofya kusimamia mashindano haya",
    "Hub de gestion": "Kituo cha usimamizi",
    "Voir page publique": "Tazama ukurasa wa umma",
    "Rechercher par nom, prénom, email ou licence...": "Tafuta kwa jina, jina la kwanza, barua pepe au leseni...",
    "Afficher/masquer les filtres": "Onyesha/ficha vichujio",
    "Filtres actifs:": "Vichujio hai:",
    "Recherche:": "Utafutaji:",
    "Tout effacer": "Futa yote",
    "pratiquants trouvés": "watendaji waliopatikana",
    "Naissance": "Kuzaliwa",
    "Tot.": "Jml.",
    "TOTAL": "JUMLA",
    "Import bancaire": "Uagizaji wa benki",
    "Importer un relevé": "Agiza taarifa ya benki",
    "Réconciliation": "Upatanisho",
    " sem": " wiki",
    "Consultez les statistiques détaillées de vos athlètes par compétition : victoires, points marqués/encaissés, différentiels. Idéal pour faire un retour personnalisé à chaque élève.": "Angalia takwimu za kina za wanamichezo wako kwa mashindano: ushindi, pointi zilizofungwa/zilizopokewa, tofauti. Bora kwa kutoa maoni maalum kwa kila mwanafunzi.",
    "QR code non disponible": "QR code haipatikani",
    "Ces federations vous invitent a rejoindre leur reseau. Acceptez pour beneficier de leurs competitions et services.": "Mashirikisho haya yanakualika kujiunga na mtandao wao. Kubali ili kufaidika na mashindano na huduma zao.",
    "Pratiquants sélectionnés:": "Watendaji waliochaguliwa:",
    "Pratiquants à inscrire:": "Watendaji wa kusajili:",
    "Erreur!": "Hitilafu!",
    "Une erreur est survenue lors de inscription en masse.": "Hitilafu imetokea wakati wa usajili wa wingi.",
    "Une erreur est survenue lors de ouverture du modal inscription en masse": "Hitilafu imetokea wakati wa kufungua dirisha la usajili wa wingi",
    "Aucun pratiquant disponible dans ce club. Ajoutez des membres pour utiliser inscription en masse.": "Hakuna mtendaji anayepatikana katika klabu hii. Ongeza wanachama ili kutumia usajili wa wingi.",
    "Veuillez patienter, traitement du fichier": "Tafadhali subiri, faili inashughulikiwa",
    "Import réussi!": "Uagizaji umefanikiwa!",
    "La page va se recharger.": "Ukurasa utapakia upya.",
    "Erreur lors de import:": "Hitilafu wakati wa kuagiza:",
    "Erreur de connexion:": "Hitilafu ya muunganisho:",
    "Impossible ouvrir le selecteur de fichier.": "Haiwezekani kufungua kichaguzi cha faili.",
    "Impossible ouvrir le selecteur de fichier. Details dans la console.": "Haiwezekani kufungua kichaguzi cha faili. Maelezo katika konsoli.",
    "Succes!": "Imefanikiwa!",
    "pratiquant(s) inscrit(s) a": "mtendaji (watendaji) wamesajiliwa kwa",
    "Erreur lors de inscription": "Hitilafu wakati wa usajili",
    "Le fichier est trop volumineux (max 2 MB)": "Faili ni kubwa sana (upeo MB 2)",
    "Veuillez sélectionner une image": "Tafadhali chagua picha",
    "Logo mis à jour avec succès": "Nembo imesasishwa kwa mafanikio",
    "Erreur lors de upload du logo": "Hitilafu wakati wa kupakia nembo",
    "Logo supprimé avec succès": "Nembo imefutwa kwa mafanikio",
    "Erreur lors de la suppression du logo": "Hitilafu wakati wa kufuta nembo",
    "Prenom": "Jina la kwanza",
    "Eleves": "Wanafunzi",
    "Jiu-Jitsu": "Jiu-Jitsu",
    "Krav Maga": "Krav Maga",
    "Capoeira": "Capoeira",
    "Annees d'experience": "Miaka ya uzoefu",
    "eleves": "wanafunzi",
    "Heure fin": "Saa ya mwisho",
    "Duree": "Muda",
    "Personnalisez votre site public et gerez son contenu": "Binafsisha tovuti yako ya umma na usimamie maudhui yake",
    "Ex: Karate, Taekwondo, Self-defense": "Mfano: Karate, Taekwondo, Kujilinda",
    "Instagram": "Instagram",
    "YouTube": "YouTube",
    "Les modifications seront visibles immediatement sur votre site public.": "Mabadiliko yataonekana mara moja kwenye tovuti yako ya umma.",
    "Excellent taux de retention d'eleves (95%%)": "Kiwango bora cha kubaki kwa wanafunzi (95%%)",
    "Eleve": "Mwanafunzi",
    "eleve": "mwanafunzi",
    "Materiel fourni": "Vifaa vilivyotolewa",
    "Excellent coach ! Tres pedagogue et patient.": "Kocha bora! Mwalimu mzuri na mvumilivu.",
    "Grace a lui, j'ai progresse tres rapidement.": "Shukrani kwake, nimeendelea kwa haraka sana.",
    "Unite": "Kitengo",
    "Dashboard Federation": "Dashibodi ya Shirikisho",
    "Dashboard Entraineur": "Dashibodi ya Kocha",
    "Guide d'utilisation detaille": "Mwongozo wa matumizi wa kina",
    "Retour a l'apercu": "Rudi kwenye muhtasari",
    "Documentation generale": "Nyaraka za jumla",
    "Table des matieres": "Yaliyomo",
    "Aucune section trouvee dans ce guide.": "Hakuna sehemu iliyopatikana katika mwongozo huu.",
    "Types de Dashboard": "Aina za Dashibodi",
    "Langues Supportees": "Lugha Zinazosaidiwa",
    "Roles Utilisateur": "Majukumu ya Mtumiaji",
    "Acces Rapide aux Dashboards": "Ufikiaji wa Haraka wa Dashibodi",
    "Interface pour les pratiquants d'arts martiaux": "Kiolesura kwa watendaji wa sanaa za kijeshi",
    "Voir Documentation": "Tazama Nyaraka",
    "Gestion des clubs et de leurs membres": "Usimamizi wa klabu na wanachama wao",
    "Administration des federations": "Usimamizi wa mashirikisho",
    "Outils d'arbitrage professionnel": "Zana za uamuzi wa kitaalamu",
    "Gestion specialisee des combats": "Usimamizi maalum wa mapigano",
    "Gérer les saisons sportives, tarifs et renouvellements d'affiliation": "Simamia msimu wa michezo, bei na kuhuisha ushirika",
    "Compétitions récentes": "Mashindano ya hivi karibuni",
    "Créez et configurez vos saisons sportives (ex: 2024-2025)": "Unda na usanidi misimu yako ya michezo (mfano: 2024-2025)",
    "Consultez et traitez les demandes de renouvellement des clubs": "Angalia na ushughulikie maombi ya kuhuisha ya klabu",
    "Générez et gérez les factures d'affiliation des clubs": "Zalisha na usimamie ankara za ushirika wa klabu",
    "Définition des tarifs d'affiliation par type (membre, partenaire, technique, administratif)": "Ufafanuzi wa bei za ushirika kwa aina (mwanachama, mshirika, ufundi, utawala)",
    "Suivi des renouvellements d'affiliation des clubs": "Ufuatiliaji wa kuhuisha ushirika wa klabu",
    "Rappels automatiques avant expiration des affiliations": "Vikumbusho vya kiotomatiki kabla ya kuisha kwa ushirika",
    "Vues": "Mtazamo",
    "Certifie depuis": "Imethibitishwa tangu",
    "L'invitation sera envoyee au club. Le club devra accepter l'invitation pour finaliser l'affiliation.": "Mwaliko utatumwa kwa klabu. Klabu italazimika kukubali mwaliko ili kukamilisha ushirika.",
    "Tous les clubs disponibles ont deja ete invites ou sont affilies.": "Klabu zote zinazopatikana tayari zimealikwa au zimeshirikishwa.",
    "Aucune compétition pour le moment.": "Hakuna mashindano kwa sasa.",
    "Aucune discipline disponible.": "Hakuna taaluma inayopatikana.",
    "Un programme d'entraînement définit un ensemble de modules et d'exercices à suivre sur une période donnée.": "Programu ya mazoezi inafafanua seti ya moduli na mazoezi ya kufuata kwa kipindi fulani.",
    "Une fois le programme créé, vous pourrez y ajouter des modules et des exercices détaillés.": "Mara programu itakapounda, utaweza kuongeza moduli na mazoezi ya kina.",
    "Une session d'entraînement représente une occurrence spécifique d'un créneau régulier.": "Kipindi cha mazoezi kinawakilisha tukio maalum la muda wa kawaida.",
    "La liste de présence sera automatiquement générée avec tous les pratiquants du club.": "Orodha ya mahudhurio itazalishwa kiotomatiki na watendaji wote wa klabu.",
    "Heure début": "Saa ya kuanza",
    "Optionnel. Ex: Cours adultes, Initiation enfants...": "Hiari. Mfano: Kozi za watu wazima, Utangulizi kwa watoto...",
    "Un créneau d'entraînement définit un horaire récurrent pour les sessions d'un club.": "Muda wa mazoezi unafafanua ratiba ya kujirudia kwa vipindi vya klabu.",
    "Une fois le créneau créé, vous pourrez planifier des sessions basées sur cet horaire.": "Mara muda utakapounda, utaweza kupanga vipindi kulingana na ratiba hii.",
    "Bouton exemple": "Kitufe cha mfano",
    "Cochez la case pour activer un type d'affiliation. Les types non cochés ne seront pas proposés aux clubs.": "Weka alama kwenye kisanduku ili kuwasha aina ya ushirika. Aina ambazo hazijawekwa alama hazitapendekezwa kwa klabu.",
    "Ce titre sera affiché en haut de la page d'accueil.": "Kichwa hiki kitaonyeshwa juu ya ukurasa wa nyumbani.",
    "Décrivez votre fédération, sa mission, ses valeurs...": "Elezea shirikisho lako, dhamira yake, thamani zake...",
    "Creer": "Unda",
    "Gerer": "Simamia",
    "Gerez les saisons sportives, les tarifs d'affiliation et les demandes de renouvellement des clubs.": "Simamia misimu ya michezo, bei za ushirika na maombi ya kuhuisha ya klabu.",
    "Gérer les clubs affiliés": "Simamia klabu zilizoshirikishwa",
    "Organiser et gérer les compétitions": "Andaa na simamia mashindano",
    "Gérer les licences fédérales": "Simamia leseni za shirikisho",
    "Gérer les certifications": "Simamia vyeti",
    "Statistiques et rapports": "Takwimu na ripoti",
    "Configuration de la fédération": "Usanidi wa shirikisho",
    "Nom, adresse, responsable, date d'affiliation, statut": "Jina, anwani, msimamizi, tarehe ya ushirika, hali",
    "Nom, prénom, club, grade, licence, date de naissance": "Jina, jina la kwanza, klabu, daraja, leseni, tarehe ya kuzaliwa",
    "Nom, date, lieu, type, nombre d'inscrits, statut": "Jina, tarehe, mahali, aina, idadi ya waliosajiliwa, hali",
    "Compétition, catégorie, participant, classement, club": "Mashindano, kategoria, mshiriki, cheo, klabu",
    "Nom, niveau de certification, date d'obtention, statut": "Jina, kiwango cha uthibitisho, tarehe ya kupata, hali",
    "Numéro, bénéficiaire, type, date d'émission, statut": "Nambari, mnufaika, aina, tarehe ya kutolewa, hali",
    "Les fichiers CSV peuvent être ouverts avec Excel, Google Sheets ou tout autre tableur. L'encodage UTF-8 est utilisé pour garantir la compatibilité des caractères spéciaux.": "Faili za CSV zinaweza kufunguliwa na Excel, Google Sheets au lahajedwali nyingine yoyote. Usimbaji wa UTF-8 unatumika kuhakikisha ulinganifu wa herufi maalum.",
    "Format recommandé: YYYY-YYYY (ex: 2024-2025)": "Muundo unaopendekezwa: YYYY-YYYY (mfano: 2024-2025)",
    "Nombre de jours avant la fin de saison pour envoyer les rappels de renouvellement aux clubs.": "Idadi ya siku kabla ya mwisho wa msimu kutuma vikumbusho vya kuhuisha kwa klabu.",
    "La saison courante sera utilisée par défaut pour les nouvelles affiliations.": "Msimu wa sasa utatumika kwa kawaida kwa ushirika mpya.",
    "Les saisons sportives couvrent généralement de septembre à août.": "Misimu ya michezo kwa kawaida inashughulikia Septemba hadi Agosti.",
    "Les rappels automatiques seront envoyés aux clubs X jours avant la fin de saison.": "Vikumbusho vya kiotomatiki vitatumwa kwa klabu siku X kabla ya mwisho wa msimu.",
    "Exemple: votre-federation.martialcomp.com": "Mfano: shirikisho-lako.martialcomp.com",
    "Utilisez votre propre site web": "Tumia tovuti yako mwenyewe",
    "Ce champ est mis à jour automatiquement selon le type de site web choisi.": "Sehemu hii inasasishwa kiotomatiki kulingana na aina ya tovuti iliyochaguliwa.",
    "JPG, PNG ou SVG. Max 2 Mo.": "JPG, PNG au SVG. Upeo MB 2.",
    "Les modifications seront immédiatement appliquées à votre fédération et visibles par les clubs affiliés.": "Mabadiliko yatatumika mara moja kwa shirikisho lako na yataonekana na klabu zilizoshirikishwa.",
    "Un nom clair aide les clubs à vous identifier facilement.": "Jina wazi husaidia klabu kukutambua kwa urahisi.",
    "Le site web permettra aux visiteurs d'en savoir plus.": "Tovuti itaruhusu wageni kujifunza zaidi.",
    "Mes Affectations": "Ugawaji Wangu",
    "Retour mode Pratiquant": "Rudi aina ya Mtendaji",
    "Affectations du Jour": "Ugawaji wa Siku",
    "Role": "Jukumu",
    "Prêt à juger": "Tayari kuamua",
    "Accéder à la feuille de notation": "Fikia karatasi ya alama",
    "Pas d'affectation aujourd'hui": "Hakuna ugawaji leo",
    "Vous n'avez pas d'affectation pour aujourd'hui.": "Huna ugawaji kwa leo.",
    "Prochaines Affectations": "Ugawaji Ujao",
    "Pas de prochaines affectations": "Hakuna ugawaji ujao",
    "Consultez l'historique de vos participations et notations.": "Angalia historia ya ushiriki wako na alama.",
    "Notes Donnees": "Alama Zilizotolewa",
    "Annees d'Experience": "Miaka ya Uzoefu",
    "Note Moyenne": "Alama ya Wastani",
    "Gerez les performances a noter et visualisez celles deja notees.": "Simamia utendaji wa kupewa alama na uone ule ambao tayari umepewa alama.",
    "Performances en Attente de Notation": "Utendaji Unaosubiri Alama",
    "Aucune performance en attente": "Hakuna utendaji unaosubiri",
    "Toutes les performances ont ete notees ou aucune competition n'est en cours.": "Utendaji wote umepewa alama au hakuna mashindano yanayoendelea.",
    "Performances Notees": "Utendaji Uliopewa Alama",
    "Aucune performance notee": "Hakuna utendaji uliopewa alama",
    "Vous n'avez pas encore note de performances.": "Bado hujatoa alama kwa utendaji wowote.",
    "Informations du Profil Juge": "Taarifa za Wasifu wa Hakimu",
    "Numero de certification": "Nambari ya uthibitisho",
    "Preferences de Notation": "Mapendeleo ya Alama",
    "Les preferences de notation seront disponibles dans une prochaine mise a jour.": "Mapendeleo ya alama yatapatikana katika sasisho lijalo.",
    "Contacter la Federation": "Wasiliana na Shirikisho",
    "Pour toute modification de vos qualifications ou informations de juge, veuillez contacter votre federation.": "Kwa marekebisho yoyote ya sifa zako au taarifa za hakimu, tafadhali wasiliana na shirikisho lako.",
    "Tableau de bord Juge Technique": "Dashibodi ya Hakimu wa Ufundi",
    "Espace Juge Technique": "Eneo la Hakimu wa Ufundi",
    "Voici votre tableau de bord de notation.": "Hii ni dashibodi yako ya alama.",
    "Juge Actif": "Hakimu Hai",
    "Affectations Aujourd'hui": "Ugawaji wa Leo",
    "Performances en Attente": "Utendaji Unaosubiri",
    "Mes Affectations du Jour": "Ugawaji Wangu wa Siku",
    "Programme du Jour": "Programu ya Siku",
    "Pas de programme": "Hakuna programu",
    "Aucun evenement prevu aujourd'hui.": "Hakuna tukio lililotarajiwa leo.",
    "Accédez aux aires de combat pour arbitrer les matchs en direct.": "Fikia maeneo ya mapigano kuamua mechi kwa moja kwa moja.",
    "Mon Profil Juge": "Wasifu Wangu wa Hakimu",
    "Experience": "Uzoefu",
    "pts": "pnt",
    "La boîte de dialogue d'impression va s'ouvrir automatiquement. Sélectionnez 'Enregistrer en PDF' comme imprimante pour créer un fichier PDF.": "Kisanduku cha mazungumzo ya uchapishaji kitafunguka kiotomatiki. Chagua 'Hifadhi kama PDF' kama printa kuunda faili ya PDF.",
    "Ce document est un export officiel du système MartialComp": "Hati hii ni usafirishaji rasmi wa mfumo wa MartialComp",
    "Combats Actifs": "Mapigano Hai",
    "Aucun combat actif": "Hakuna pigano hai",
    "Les combats actifs apparaîtront ici": "Mapigano hai yataonekana hapa",
    "Combats Récents": "Mapigano ya Hivi Karibuni",
    "Accès Rapide": "Ufikiaji wa Haraka",
    "Tous les Combats": "Mapigano Yote",
    "Interface spécialisée pour les combats Taekwondo avec système de points et pénalités spécifiques": "Kiolesura maalum kwa mapigano ya Taekwondo na mfumo wa pointi na adhabu maalum",
    "Aucun combat Taekwondo actif": "Hakuna pigano la Taekwondo linaloendelea",
    "Aucun combat à afficher": "Hakuna pigano la kuonyesha",
    "Statistiques Scoring": "Takwimu za Alama",
    "Performances totales": "Jumla ya utendaji",
    "Compétitions - Progression Scoring": "Mashindano - Maendeleo ya Alama",
    "Non démarré": "Haijaanza",
    "Organisez votre première compétition pour accéder au scoring": "Andaa mashindano yako ya kwanza kufikia alama",
}
