# -*- coding: utf-8 -*-
TRANSLATIONS = {
    "Gestion Pro": "Usimamizi wa Kitaalamu",
    "Publier & Partager": "Chapisha na Shiriki",
    "Vue d'ensemble de la compétition": "Muhtasari wa mashindano",
    "Affectation rapide": "Ugawaji wa haraka",
    "Pratiquants non affectés": "Watendaji wasio na ugawaji",
    "Aucun pratiquant non affecté": "Hakuna mtendaji asiye na ugawaji",
    "Juges non affectés": "Waamuzi wasio na ugawaji",
    "Envoyer notifications": "Tuma arifa",
    "Prochaines étapes": "Hatua zinazofuata",
    "Définir les types de compétition": "Weka aina za mashindano",
    "Créer les catégories": "Unda kategoria",
    "Enregistrer les participants": "Sajili washiriki",
    "Affecter les juges": "Gawa waamuzi",
    "Ajouter un type": "Ongeza aina",
    "Glissez des catégories ici": "Buruta kategoria hapa",
    "Aucun type de compétition défini. Les types permettent d'organiser les catégories (ex: Combat, Technique, Démonstration).": "Hakuna aina ya mashindano iliyofafanuliwa. Aina huruhusu kupanga kategoria (mfano: Mapigano, Ufundi, Maonyesho).",
    "Glissez des pratiquants ici": "Buruta watendaji hapa",
    "Aucune catégorie définie. Créez des catégories pour organiser les participants.": "Hakuna kategoria iliyofafanuliwa. Unda kategoria ili kupanga washiriki.",
    "Nom, club, licence...": "Jina, klabu, leseni...",
    "Non affecté": "Haijagawiwa",
    "Aucune inscription pour le moment": "Hakuna usajili kwa sasa",
    "Juges Techniques (Notation Technique)": "Waamuzi wa Ufundi (Alama za Ufundi)",
    "Ajouter un juge technique": "Ongeza hakimu wa ufundi",
    "Les juges techniques effectuent la notation technique. Il peut y avoir plus de 5 juges techniques selon le type de compétition.": "Waamuzi wa ufundi hufanya upangaji wa alama za ufundi. Kunaweza kuwa na zaidi ya waamuzi 5 wa ufundi kulingana na aina ya mashindano.",
    "Juges techniques disponibles": "Waamuzi wa ufundi wanaopatikana",
    "Aucun juge technique disponible": "Hakuna hakimu wa ufundi anayepatikana",
    "Glisser les juges techniques ici (peut être plus de 5)": "Buruta waamuzi wa ufundi hapa (inaweza kuwa zaidi ya 5)",
    "Aucune catégorie créée. Créez d'abord des catégories.": "Hakuna kategoria iliyoundwa. Unda kategoria kwanza.",
    "Arbitres de Combat": "Waamuzi wa Mapigano",
    "Ajouter un arbitre": "Ongeza hakimu",
    "Pour les combats : Arbitre central (1), Arbitres de coin (2-3), Arbitre de table (1), Placator (1).": "Kwa mapigano: Hakimu mkuu (1), Waamuzi wa kona (2-3), Hakimu wa meza (1), Msuluhishi (1).",
    "Arbitres disponibles": "Waamuzi wanaopatikana",
    "Aucun arbitre disponible": "Hakuna hakimu anayepatikana",
    "Affectations par tatami": "Ugawaji kwa tatami",
    "Arbitre Central": "Hakimu Mkuu",
    "Glisser 1 arbitre central": "Buruta hakimu mkuu 1",
    "Arbitres de Coin": "Waamuzi wa Kona",
    "Glisser 2-3 arbitres de coin": "Buruta waamuzi wa kona 2-3",
    "Arbitre de Table": "Hakimu wa Meza",
    "Glisser 1 arbitre de table": "Buruta hakimu wa meza 1",
    "Placator": "Msuluhishi",
    "Glisser 1 placator": "Buruta msuluhishi 1",
    "Programmation et suivi temps réel": "Kupanga ratiba na ufuatiliaji wa wakati halisi",
    "Démarrer le suivi": "Anza ufuatiliaji",
    "Planning de la journée": "Ratiba ya siku",
    "Accueil et pesée": "Mapokezi na kupima uzito",
    "Vérification des licences et pesée officielle": "Uhakiki wa leseni na kupima uzito rasmi",
    "Monter": "Panda juu",
    "Descendre": "Shuka chini",
    "Présentation des juges et rappel des règles": "Utambulisho wa waamuzi na ukumbusho wa sheria",
    "Compétitions - Session 1": "Mashindano - Kipindi cha 1",
    "Catégories jeunes et débutants": "Kategoria za vijana na wanaoanza",
    "Temps réel": "Wakati halisi",
    "État des tatamis": "Hali ya tatami",
    "Publication et partage": "Uchapishaji na kushiriki",
    "État de publication": "Hali ya uchapishaji",
    "Cette compétition n'est pas encore publiée. Elle n'est visible que par les organisateurs.": "Mashindano haya bado hayajachapishwa. Yanaonekana na waandaaji peke yao.",
    "Checklist avant publication": "Orodha ya ukaguzi kabla ya kuchapisha",
    "Lieu défini": "Mahali pamefafanuliwa",
    "Au moins une catégorie créée": "Angalau kategoria moja imeundwa",
    "Informations complètes": "Taarifa kamili",
    "Publier maintenant": "Chapisha sasa",
    "Cette compétition est publiée et visible publiquement.": "Mashindano haya yamechapishwa na yanaonekana hadharani.",
    "URL publique": "URL ya umma",
    "Dépublier": "Ondoa uchapishaji",
    "Options de visibilité": "Chaguo za uonekano",
    "Autoriser les inscriptions en ligne": "Ruhusu usajili mtandaoni",
    "Afficher la liste des participants": "Onyesha orodha ya washiriki",
    "Partager la compétition": "Shiriki mashindano",
    "Partager sur Facebook": "Shiriki kwenye Facebook",
    "Partager sur Twitter": "Shiriki kwenye Twitter",
    "Partager sur WhatsApp": "Shiriki kwenye WhatsApp",
    "Notifier les juges": "Arifu waamuzi",
    "Ajouter un type de compétition": "Ongeza aina ya mashindano",
    "Règles spécifiques": "Sheria mahususi",
    "Aucun grade minimum": "Hakuna daraja la chini",
    "Aucun grade maximum": "Hakuna daraja la juu",
    "Rechercher un utilisateur": "Tafuta mtumiaji",
    "Nom ou email": "Jina au barua pepe",
    "Juge de coin": "Hakimu wa kona",
    "Table de marque": "Meza ya alama",
    "Arbitre en chef": "Hakimu mkuu",
    "Pratiquant affecté avec succès": "Mtendaji amegawiwa kwa mafanikio",
    "Erreur de connexion": "Hitilafu ya muunganisho",
    "Êtes-vous sûr de vouloir retirer ce pratiquant de cette catégorie ?": "Je, una uhakika unataka kumwondoa mtendaji huyu kutoka kategoria hii?",
    "Pratiquant retiré de la catégorie": "Mtendaji ameondolewa kutoka kategoria",
    "Juge affecté avec succès": "Hakimu amegawiwa kwa mafanikio",
    "Catégorie créée avec succès": "Kategoria imeundwa kwa mafanikio",
    "Erreur lors de la création": "Hitilafu wakati wa kuunda",
    "Type de compétition créé avec succès": "Aina ya mashindano imeundwa kwa mafanikio",
    "Erreur de connexion: ": "Hitilafu ya muunganisho: ",
    "Recherche...": "Inatafuta...",
    "Arbitre national": "Hakimu wa kitaifa",
    "Juge régional": "Hakimu wa mkoa",
    "Catégorie supprimée avec succès": "Kategoria imefutwa kwa mafanikio",
    "Êtes-vous sûr de vouloir publier cette compétition ? Elle sera visible publiquement.": "Je, una uhakika unataka kuchapisha mashindano haya? Yataonekana hadharani.",
    "Compétition publiée avec succès !": "Mashindano yamechapishwa kwa mafanikio!",
    "Erreur lors de la publication": "Hitilafu wakati wa kuchapisha",
    "Génération de la programmation en cours...": "Uzalishaji wa ratiba unaendelea...",
    "Suivi temps réel activé": "Ufuatiliaji wa wakati halisi umewashwa",
    "Progression sauvegardée": "Maendeleo yamehifadhiwa",
    "Êtes-vous sûr de vouloir supprimer ce type de compétition ?": "Je, una uhakika unataka kufuta aina hii ya mashindano?",
    "Type de compétition supprimé avec succès": "Aina ya mashindano imefutwa kwa mafanikio",
    "Export PDF en cours de développement": "Usafirishaji PDF unaendelezwa",
    "Envoi de notifications en cours de développement": "Utumaji wa arifa unaendelezwa",
    "Import en cours de développement": "Uagizaji unaendelezwa",
    "Modification en cours de développement": "Marekebisho yanaendelezwa",
    "Suppression en cours de développement": "Ufutaji unaendelezwa",
    "Dépublication en cours de développement": "Kuondoa uchapishaji kunaendelezwa",
    "Téléchargement du QR Code": "Upakuaji wa QR Code",
    "Envoi de notifications à tous les participants": "Utumaji wa arifa kwa washiriki wote",
    "Envoi de notifications aux juges": "Utumaji wa arifa kwa waamuzi",
    "Bienvenue sur MartialComp! Votre compte a été créé avec succès.": "Karibu MartialComp! Akaunti yako imeundwa kwa mafanikio.",
    "Une erreur est survenue lors de la création de votre compte. Notre équipe a été notifiée.": "Hitilafu imetokea wakati wa kuunda akaunti yako. Timu yetu imearifiwa.",
    "Votre compte a été créé, mais certaines informations complémentaires n'ont pas pu être enregistrées. Vous pourrez les compléter plus tard.": "Akaunti yako imeundwa, lakini baadhi ya taarifa za ziada hazikuweza kuhifadhiwa. Unaweza kuzikamilisha baadaye.",
    "Code verifier requis pour PKCE.": "Msimbo wa uthibitishaji unahitajika kwa PKCE.",
    "Etes-vous sur ?": "Je, una uhakika?",
    "Timestamps": "Muhuri wa wakati",
    "Vie privée": "Faragha",
    "Messagerie": "Ujumbe",
    "Message privé": "Ujumbe wa faragha",
    "UUID": "UUID",
    "Type de conversation": "Aina ya mazungumzo",
    "Nom du groupe (optionnel pour les conversations directes)": "Jina la kikundi (hiari kwa mazungumzo ya moja kwa moja)",
    "Description du groupe ou de la conversation": "Maelezo ya kikundi au mazungumzo",
    "Avatar du groupe": "Picha ya kikundi",
    "Club associé": "Klabu inayohusiana",
    "Dernier message le": "Ujumbe wa mwisho tarehe",
    "Aperçu du dernier message": "Muhtasari wa ujumbe wa mwisho",
    "Autoriser les réponses": "Ruhusu majibu",
    "Si désactivé, seuls les admins peuvent envoyer des messages": "Ikiwa imezimwa, wasimamizi peke yao wanaweza kutuma ujumbe",
    "Conversation directe": "Mazungumzo ya moja kwa moja",
    "Modérateur": "Msimamizi",
    "Notifications désactivées": "Arifa zimezimwa",
    "Épinglé": "Imebandikwa",
    "Dernier lu le": "Ilisomwa mwisho tarehe",
    "Surnom": "Jina la utani",
    "Surnom affiché dans cette conversation": "Jina la utani linaloonyeshwa katika mazungumzo haya",
    "Type de message": "Aina ya ujumbe",
    "Contenu du message (supporte le markdown basique)": "Maudhui ya ujumbe (inasaidia markdown ya msingi)",
    "En réponse à": "Kwa kujibu",
    "Supprimé par": "Imefutwa na",
    "Modifié": "Imerekebishwa",
    "Tableur": "Lahajedwali",
    "Taille (bytes)": "Ukubwa (baiti)",
    "Taille du fichier en bytes": "Ukubwa wa faili kwa baiti",
    "Largeur": "Upana",
    "Hauteur": "Urefu",
    "Miniature": "Picha ndogo",
    "Téléchargé le": "Imepakiwa tarehe",
    "Statut de lecture": "Hali ya kusoma",
    "Statuts de lecture": "Hali za kusoma",
    "Automatique": "Kiotomatiki",
    "Recevoir un email pour les messages non lus": "Pokea barua pepe kwa ujumbe ambao haujasomwa",
    "Notifications push": "Arifa za push",
    "Sons activés": "Sauti zimewashwa",
    "Afficher les confirmations de lecture": "Onyesha uthibitisho wa kusoma",
    "Afficher 'est en train d'écrire'": "Onyesha 'anaandika'",
    "Afficher mon statut en ligne": "Onyesha hali yangu ya mtandaoni",
    "Paramètres de chat": "Mipangilio ya mazungumzo",
    "Nouvelle conversation": "Mazungumzo mapya",
    "Aucune conversation": "Hakuna mazungumzo",
    "Commencer une discussion": "Anza mazungumzo",
    "Sélectionnez une conversation": "Chagua mazungumzo",
    "Choisissez une conversation dans la liste ou commencez-en une nouvelle.": "Chagua mazungumzo kutoka orodha au anza mapya.",
    "Direct": "Moja kwa moja",
    "Nom du groupe": "Jina la kikundi",
    "Ex: Équipe technique": "Mfano: Timu ya ufundi",
    "Destinataire(s)": "Mpokeaji (wapokeaji)",
    "Rechercher par nom ou email...": "Tafuta kwa jina au barua pepe...",
    "Quitter": "Ondoka",
    "Discussion privée": "Mazungumzo ya faragha",
    "Discussion à plusieurs": "Mazungumzo ya watu wengi",
    "Ex: Équipe compétition": "Mfano: Timu ya mashindano",
    "Créer la conversation": "Unda mazungumzo",
    "\n                %(count)s participant\n                ": "\n                Mshiriki %(count)s\n                ",
    "Mettre en sourdine": "Nyamazisha",
    "Aucun message. Commencez la discussion !": "Hakuna ujumbe. Anza mazungumzo!",
    "Tapez votre message...": "Andika ujumbe wako...",
    "Pas de messages": "Hakuna ujumbe",
    "Message supprimé": "Ujumbe umefutwa",
    "Réagir": "Jibu kwa hisia",
    "Vous n'avez pas accès à cette conversation.": "Huna ufikiaji wa mazungumzo haya.",
    "Conversation et contenu requis.": "Mazungumzo na maudhui yanahitajika.",
    "Sélectionnez au moins un destinataire.": "Chagua angalau mpokeaji mmoja.",
    "Le contenu ne peut pas être vide.": "Maudhui hayawezi kuwa tupu.",
    "Emoji requis.": "Emoji inahitajika.",
    "Date non définie": "Tarehe haijafafanuliwa",
    "Âge": "Umri",
    "Changer statut": "Badilisha hali",
    "Navigation pages": "Urambazaji wa kurasa",
    "Générer tous les QR codes": "Zalisha QR code zote",
    "Créez votre première compétition": "Unda mashindano yako ya kwanza",
    "Suivi financier": "Ufuatiliaji wa fedha",
    "Module de gestion financière en cours de développement": "Moduli ya usimamizi wa fedha inaendelezwa",
    "Gestion de l'entraînement": "Usimamizi wa mazoezi",
    "Module d'entraînement": "Moduli ya mazoezi",
    "Gérez vos sessions d'entraînement et programmes": "Simamia vipindi vyako vya mazoezi na programu",
    "Aucun événement": "Hakuna tukio",
    "Créez votre premier événement": "Unda tukio lako la kwanza",
    "Vendez du matériel et des produits à vos membres": "Uza vifaa na bidhaa kwa wanachama wako",
    "Assigner un rôle": "Gawa jukumu",
    "Gérez les rôles et permissions des membres de votre club": "Simamia majukumu na ruhusa za wanachama wa klabu yako",
    "Gestion complète du club": "Usimamizi kamili wa klabu",
    "Gestion des membres et inscriptions": "Usimamizi wa wanachama na usajili",
    "Pratiquant supprimé avec succès": "Mtendaji amefutwa kwa mafanikio",
    "Import réussi": "Uagizaji umefanikiwa",
    "Inscription réussie": "Usajili umefanikiwa",
    "Erreur lors du changement de statut": "Hitilafu wakati wa kubadilisha hali",
    "Format non supporté. Utilisez CSV ou Excel (.csv, .xlsx, .xls)": "Muundo hauafikiwi. Tumia CSV au Excel (.csv, .xlsx, .xls)",
    "Import en cours...": "Uagizaji unaendelea...",
    "Progression de la poule": "Maendeleo ya kundi",
    "combats": "mapigano",
    "Équipes participantes": "Timu zinazoshiriki",
    "Pratiquants participants": "Watendaji wanaoshiriki",
    "Aucun participant n'a été ajouté à cette poule.": "Hakuna mshiriki aliyeongezwa katika kundi hili.",
    "Créer le premier combat": "Unda pigano la kwanza",
    "Retour à la gestion de la poule": "Rudi kwenye usimamizi wa kundi",
    "PÉNALITÉ": "ADHABU",
    "SORTIE": "KUTOKA",
    "Annuler la dernière action": "Ghairi kitendo cha mwisho",
    "ANNULER": "GHAIRI",
    "DÉMARRER": "ANZA",
    "PAUSE": "PUMZIKO",
    "Historique des Actions": "Historia ya Vitendo",
    "Configuration régionale": "Usanidi wa eneo",
    "Migration et métadonnées": "Uhamishaji na metadata",
    "%(count)d club(s) supprimé(s) avec succès.": "Klabu %(count)d zimefutwa kwa mafanikio.",
    "Supprimer les clubs sélectionnés": "Futa klabu zilizochaguliwa",
    "%(count)d club(s) désactivé(s).": "Klabu %(count)d zimezimwa.",
    "Désactiver les clubs sélectionnés": "Zima klabu zilizochaguliwa",
    "%(count)d club(s) activé(s).": "Klabu %(count)d zimewashwa.",
    "Activer les clubs sélectionnés": "Washa klabu zilizochaguliwa",
    "Sans organisation": "Bila shirika",
    "Avec organisation": "Na shirika",
    "Organisation a laquelle le pratiquant est rattache.": "Shirika ambalo mtendaji amehusishwa nalo.",
    "Disciplines et grades": "Taaluma na madaraja",
    "Assigner organisation depuis le club du proprietaire": "Gawa shirika kutoka klabu ya mmiliki",
    "%(count)d pratiquant(s) mis a jour.": "Watendaji %(count)d wamesasishwa.",
    "%(count)d erreur(s): %(errors)s": "Hitilafu %(count)d: %(errors)s",
    "Assigner a une organisation specifique": "Gawa kwa shirika maalum",
    "%(count)d pratiquant(s) sans organisation. Utilisez la commande: python manage.py fix_practitioners_organization --fix --org-id=ID. Organisations: %(orgs)s": "Watendaji %(count)d bila shirika. Tumia amri: python manage.py fix_practitioners_organization --fix --org-id=ID. Mashirika: %(orgs)s",
    "Afficher le diagnostic": "Onyesha uchunguzi",
    "Statistiques: %(without)d pratiquants sans organisation sur %(total)d total (%(pct).1f%%). Utilisez le filtre \"Sans organisation\" pour les voir.": "Takwimu: Watendaji %(without)d bila shirika kati ya %(total)d jumla (%(pct).1f%%). Tumia kichujio \"Bila shirika\" kuwaona.",
    "Haïti": "Haiti",
    "Format de message invalide": "Muundo wa ujumbe batili",
    "Données de score incomplètes": "Data ya alama haijakamilika",
    "Erreur lors de la sauvegarde du score": "Hitilafu wakati wa kuhifadhi alama",
    "Seul l'arbitre peut démarrer le combat": "Hakimu peke yake anaweza kuanza pigano",
    "Seul l'arbitre peut attribuer des points": "Hakimu peke yake anaweza kutoa pointi",
    "Seul l'arbitre peut donner des pénalités": "Hakimu peke yake anaweza kutoa adhabu",
    "Description de l'examen": "Maelezo ya mtihani",
    "Lieu de l'examen": "Mahali pa mtihani",
    "Prérequis pour participer": "Mahitaji ya kushiriki",
    "Règlement de l'examen": "Kanuni za mtihani",
    "Matériel à apporter": "Vifaa vya kuleta",
    "Frais d'inscription en euros": "Ada ya usajili kwa euro",
    "Laisser vide si l'examen ne dure qu'une journée": "Acha tupu ikiwa mtihani unachukua siku moja tu",
    "La fin des inscriptions doit être postérieure au début.": "Tarehe ya mwisho wa usajili lazima iwe baada ya mwanzo.",
    "Les inscriptions doivent se terminer avant le début de l'examen.": "Usajili lazima umalize kabla ya mwanzo wa mtihani.",
    "Informations complémentaires ou motivation": "Taarifa za ziada au motisha",
    "Grade obtenu": "Daraja lililopatikana",
    "Commentaires de l'examinateur": "Maoni ya mtahini",
    "Note sur 20": "Alama kati ya 20",
    "Instagram: @votrecompte\nYouTube: votre-chaine": "Instagram: @akauntiyako\nYouTube: chaneli-yako",
    "Ex: 50-80€": "Mfano: 50-80€",
    "Aucune configuration disponible. Vous pouvez creer un combat sans configuration.": "Hakuna usanidi unaopatikana. Unaweza kuunda pigano bila usanidi.",
    "Configuration de scoring pour ce combat (optionnel).": "Usanidi wa alama kwa pigano hili (hiari).",
    "Aucun arbitre disponible. Vous pouvez creer un combat sans arbitre.": "Hakuna hakimu anayepatikana. Unaweza kuunda pigano bila hakimu.",
    "Arbitre principal pour ce combat (optionnel).": "Hakimu mkuu wa pigano hili (hiari).",
    "La valeur d'un point doit etre positive.": "Thamani ya pointi lazima iwe chanya.",
    "La valeur d'une penalite doit etre negative.": "Thamani ya adhabu lazima iwe hasi.",
    "1/4 point - Phan Tu Diem": "Pointi 1/4 - Phan Tu Diem",
    "1/2 point - Nua Diem": "Pointi 1/2 - Nua Diem",
    "1 point - Mot Diem": "Pointi 1 - Mot Diem",
    "1.5 points - Mot Diem Duoi": "Pointi 1.5 - Mot Diem Duoi",
    "2 points - Hai Diem": "Pointi 2 - Hai Diem",
    "Avertissement - Canh Cao": "Onyo - Canh Cao",
    "Retrait 1/2 point - Kem Diem": "Kuondoa pointi 1/2 - Kem Diem",
    "Retrait 1 point - Phat": "Kuondoa pointi 1 - Phat",
    "Disqualification - Phat Hai/Loai": "Kufukuzwa - Phat Hai/Loai",
    "Nom du type de compétition": "Jina la aina ya mashindano",
    "Description du type de compétition": "Maelezo ya aina ya mashindano",
    "La taille minimale d'équipe est requise pour les compétitions par équipe.": "Ukubwa wa chini wa timu unahitajika kwa mashindano ya timu.",
    "La taille maximale d'équipe est requise pour les compétitions par équipe.": "Ukubwa wa juu wa timu unahitajika kwa mashindano ya timu.",
    "La taille maximale doit être supérieure ou égale à la taille minimale.": "Ukubwa wa juu lazima uwe mkubwa au sawa na ukubwa wa chini.",
    "Un type de compétition avec ce nom existe déjà pour cette discipline.": "Aina ya mashindano yenye jina hili tayari ipo kwa taaluma hii.",
    "Rechercher par nom ou description...": "Tafuta kwa jina au maelezo...",
    "Au moins un type de compétition doit être sélectionné.": "Angalau aina moja ya mashindano lazima ichaguliwe.",
    "Les types sélectionnés ne correspondent pas à la discipline choisie.": "Aina zilizochaguliwa hazilingani na taaluma iliyochaguliwa.",
    "Date de naissance (optionnel)": "Tarehe ya kuzaliwa (hiari)",
    "Cette adresse email est déjà utilisée.": "Anwani hii ya barua pepe tayari inatumika.",
    "Veuillez télécharger un fichier CSV avec les colonnes suivantes: titre, description, type_evenement, date_debut, date_fin, heure_debut (optionnel), heure_fin (optionnel), lieu, ville, etc.": "Tafadhali pakia faili ya CSV yenye safu wima zifuatazo: kichwa, maelezo, aina_ya_tukio, tarehe_ya_kuanza, tarehe_ya_mwisho, saa_ya_kuanza (hiari), saa_ya_mwisho (hiari), mahali, mji, n.k.",
    "Ce grade n'appartient pas à la discipline sélectionnée": "Daraja hili si la taaluma iliyochaguliwa",
    "Sélectionnez votre pays": "Chagua nchi yako",
    "Sélectionnez les disciplines gérées par votre fédération": "Chagua taaluma zinazosimamiwa na shirikisho lako",
    "Le fichier est trop volumineux. La taille maximale autorisée est de 2 Mo.": "Faili ni kubwa sana. Ukubwa wa juu unaoruhusiwa ni MB 2.",
    "Le pays est obligatoire.": "Nchi ni lazima.",
    "Veuillez spécifier un sous-domaine personnalisé.": "Tafadhali bainisha subdomain maalum.",
    "Ce sous-domaine est déjà utilisé par une autre fédération.": "Subdomain hii tayari inatumika na shirikisho lingine.",
    "Ce sous-domaine est déjà utilisé par un autre club.": "Subdomain hii tayari inatumika na klabu nyingine.",
    "Votre adresse": "Anwani yako",
    "Votre ville": "Mji wako",
    "Votre code postal": "Msimbo wa posta wako",
    "Votre numéro de licence": "Nambari yako ya leseni",
    "Taïwan": "Taiwan",
    "Ce pratiquant est un juge": "Mtendaji huyu ni hakimu",
    "-- Sélectionnez un niveau --": "-- Chagua kiwango --",
    "Juge actif": "Hakimu hai",
    "Notes sur la qualification de juge": "Maelezo kuhusu sifa za hakimu",
    "Âge": "Umri",
    "Heure de début de la compétition (ex: 09:00)": "Saa ya kuanza mashindano (mfano: 09:00)",
    "Heure de fin de la compétition (ex: 18:00)": "Saa ya mwisho wa mashindano (mfano: 18:00)",
    "Heure de début de la pause déjeuner (optionnel)": "Saa ya kuanza pumziko la chakula (hiari)",
    "Heure de fin de la pause déjeuner (optionnel)": "Saa ya mwisho wa pumziko la chakula (hiari)",
    "Nombre de tatamis disponibles (1-10)": "Idadi ya tatami zinazopatikana (1-10)",
    "Durée par défaut d'un match en minutes (ex: 3 pour 3 minutes)": "Muda wa kawaida wa mechi kwa dakika (mfano: 3 kwa dakika 3)",
    "Temps de pause entre deux matchs en minutes (ex: 1)": "Muda wa pumziko kati ya mechi mbili kwa dakika (mfano: 1)",
    "Date et heure de début de la pesée (optionnel)": "Tarehe na saa ya kuanza kupima uzito (hiari)",
    "Date et heure de fin de la pesée (optionnel)": "Tarehe na saa ya mwisho wa kupima uzito (hiari)",
    "Heure du briefing des juges (optionnel)": "Saa ya mkutano wa waamuzi (hiari)",
    "Heure de la cérémonie de remise des prix (optionnel)": "Saa ya sherehe ya tuzo (hiari)",
    "Leave blank for global criteria applicable to all categories": "Acha tupu kwa vigezo vya jumla vinavyotumika kwa kategoria zote",
    "Global (All Categories)": "Jumla (Kategoria Zote)",
    "Ex: Programme débutant Karaté": "Mfano: Programu ya wanaoanza Karate",
    "Description détaillée du programme...": "Maelezo ya kina ya programu...",
    "Ex: 12": "Mfano: 12",
    "Ex: 3": "Mfano: 3",
    "Objectifs du programme...": "Malengo ya programu...",
    "Prérequis (optionnel)...": "Mahitaji (hiari)...",
    "Ex: Karaté débutants": "Mfano: Karate wanaoanza",
    "Ex: Dojo principal": "Mfano: Dojo kuu",
    "La date de fin doit être après la date de début": "Tarehe ya mwisho lazima iwe baada ya tarehe ya kuanza",
    "En attente de confirmation": "Inasubiri uthibitisho",
    "Mission terminée": "Kazi imekamilika",
    "A décliné": "Amekataa",
    "Arbitre Assistant": "Hakimu Msaidizi",
    "Novice - Première expérience": "Mwanafunzi - Uzoefu wa kwanza",
    "Débutant - Quelques compétitions": "Mwanzilishi - Mashindano machache",
    "Intermédiaire - Expérience régulière": "Wastani - Uzoefu wa kawaida",
    "Expérimenté - Nombreuses compétitions": "Mwenye uzoefu - Mashindano mengi",
    "Participant à cette compétition": "Mshiriki wa mashindano haya",
    "Membre du club organisateur": "Mwanachama wa klabu inayoandaa",
    "Pratiquant de la discipline": "Mtendaji wa taaluma",
    "Bénévole externe": "Mtoaji hiari wa nje",
    "Juge officiel certifié": "Hakimu rasmi aliyeidhinishwa",
    "Source de recrutement": "Chanzo cha kuajiri",
    "Niveau d'expérience": "Kiwango cha uzoefu",
    "Activé le": "Imewashwa tarehe",
    "Désactivé le": "Imezimwa tarehe",
    "Recruté par": "Ameajiriwa na",
    "Date de recrutement": "Tarehe ya kuajiri",
    "A accepté la mission": "Amekubali kazi",
    "Briefing effectué": "Mkutano umefanyika",
    "Date du briefing": "Tarehe ya mkutano",
    "Évaluation de performance": "Tathmini ya utendaji",
    "Note de 1 à 5 sur la qualité du travail": "Alama ya 1 hadi 5 kuhusu ubora wa kazi",
    "Commentaires sur la performance": "Maoni kuhusu utendaji",
    "Juge ad-hoc": "Hakimu wa dharura",
    "Juges ad-hoc": "Waamuzi wa dharura",
    "Rôle": "Jukumu",
    "Tatami assigné": "Tatami iliyogawiwa",
    "Numéro du tatami/aire où cette catégorie sera jugée": "Nambari ya tatami/eneo ambako kategoria hii itaamuliwa",
    "Ordre de passage sur le tatami assigné": "Mpangilio wa kupita kwenye tatami iliyogawiwa",
    "Mode de combat pour cette catégorie (équipe ou individuel)": "Aina ya mapigano kwa kategoria hii (timu au mtu binafsi)",
    "Examen de grade": "Mtihani wa daraja",
    "Examen de certification": "Mtihani wa uthibitisho",
    "Examen de recertification": "Mtihani wa kuthibitisha upya",
    "Type d'examen": "Aina ya mtihani",
    "Début des inscriptions": "Mwanzo wa usajili",
    "Fin des inscriptions": "Mwisho wa usajili",
    "Examinateur principal": "Mtahini mkuu",
    "Matériel nécessaire": "Vifaa vinavyohitajika",
    "Les inscriptions ne sont pas ouvertes": "Usajili haujafunguliwa",
    "Vous êtes déjà inscrit à cet examen": "Tayari umesajiliwa kwa mtihani huu",
    "Inscription possible": "Usajili unapatikana",
    "Notes de l'inscription": "Maelezo ya usajili",
    "Évalué le": "Imetathminiwa tarehe",
    "Inscription à un examen": "Usajili kwa mtihani",
    "Inscriptions aux examens": "Usajili kwa mitihani",
    "Position: top-left, top-center, top-right": "Nafasi: juu-kushoto, juu-katikati, juu-kulia",
    "Couleur du texte": "Rangi ya maandishi",
    "Variables disponibles: {recipient_name}, {certification_type}, {level}, {date}, {certification_number}, {organization_name}, {discipline}": "Vibadala vinavyopatikana: {recipient_name}, {certification_type}, {level}, {date}, {certification_number}, {organization_name}, {discipline}",
    "Inscription directe": "Usajili wa moja kwa moja",
    "Suivi activité": "Ufuatiliaji wa shughuli",
    "Maître": "Bwana",
    "3 titulaires + 2 remplaçants": "Wachezaji 3 + wabadala 2",
    "5 titulaires + 2 remplaçants": "Wachezaji 5 + wabadala 2",
    "Si activé, les équipes doivent avoir le minimum de remplaçants requis": "Ikiwa imewashwa, timu lazima ziwe na kima cha chini cha wabadala kinachohitajika",
    "Si moins d'équipes sont inscrites, proposer basculement vers individuel": "Ikiwa timu chache zimesajiliwa, pendekeza kubadilisha kuwa mtu binafsi",
    "Nombre maximum de membres en entente (prêtés d'autres clubs)": "Idadi ya juu ya wanachama waliokopeshwa (kutoka klabu nyingine)",
    "Si activé, les ententes doivent être approuvées par l'organisateur": "Ikiwa imewashwa, makubaliano lazima yaidhinishwe na mwandaaji",
    "Mono-club": "Klabu moja",
    "Multi-clubs (fusion)": "Klabu nyingi (muungano)",
    "Fusion en attente": "Muungano unasubiri",
    "Fusion completee": "Muungano umekamilika",
    "Archivée": "Imehifadhiwa kumbukumbu",
    "Club principal": "Klabu kuu",
    "Equipe parente (fusion)": "Timu mama (muungano)",
    "Indique si cette équipe résulte d'une fusion": "Inaonyesha kama timu hii ni matokeo ya muungano",
    "Fusionnée dans": "Imeunganishwa katika",
    "Si archivée suite à fusion, l'équipe résultante": "Ikiwa imehifadhiwa baada ya muungano, timu iliyotokana",
    "False si l'équipe a été fusionnée ou archivée (soft delete)": "Uongo ikiwa timu imeunganishwa au kuhifadhiwa (kufuta laini)",
    "Minimum de membres": "Kima cha chini cha wanachama",
    "Maximum de membres": "Kima cha juu cha wanachama",
    "Message de demande de fusion": "Ujumbe wa ombi la muungano",
    "Cree le": "Imeundwa tarehe",
    "Mis a jour le": "Imesasishwa tarehe",
    "Membre prêté par un autre club": "Mwanachama aliyekopeshwa na klabu nyingine",
    "Pour les ententes: équipe d'où vient le membre": "Kwa makubaliano: timu ambayo mwanachama anatoka",
    "Équipe d'origine si ce membre a été transféré lors d'une fusion": "Timu ya asili ikiwa mwanachama huyu alihamishwa wakati wa muungano",
    "Indique si le membre a participé à au moins un combat": "Inaonyesha kama mwanachama ameshiriki angalau pigano moja",
    "Score cumulé rouge": "Alama za jumla nyekundu",
    "Score cumulé blanc": "Alama za jumla nyeupe",
    "Nom suggéré pour l'équipe fusionnée": "Jina lililopendekezwa kwa timu iliyounganishwa",
    "Petite finale (3ème place)": "Fainali ndogo (nafasi ya 3)",
    "Position dans le bracket (1 = premier match)": "Nafasi katika mchoro (1 = mechi ya kwanza)",
    "Ex: '1er Poule A' ou 'Vainqueur QF1'": "Mfano: 'Wa kwanza Kundi A' au 'Mshindi QF1'",
    "Ex: '2ème Poule B' ou 'Perdant DF1'": "Mfano: 'Wa pili Kundi B' au 'Aliyeshindwa DF1'",
    "JSON avec détails de chaque membre (nom, rôle, stats)": "JSON yenye maelezo ya kila mwanachama (jina, jukumu, takwimu)",
    "Ex: Tatami 1, Aire A, Zone Combat 1": "Mfano: Tatami 1, Eneo A, Eneo la Mapigano 1",
    "Token unique pour l'URL d'accès": "Token ya kipekee kwa URL ya ufikiaji",
    "Si désactivée, l'aire n'est plus accessible": "Ikiwa imezimwa, eneo halipatikani tena",
    "Bleu": "Bluu",
    "Vert": "Kijani",
    "Jaune": "Njano",
    "Violet": "Zambarau",
    "Rose": "Waridi",
    "Dernière fois que quelqu'un s'est connecté à cette aire": "Mara ya mwisho mtu alipoingia katika eneo hili",
    "Terminé le": "Ilimalizika tarehe",
    "Type de système de notation utilisé pour ce type de compétition": "Aina ya mfumo wa alama unaotumika kwa aina hii ya mashindano",
    "Icône": "Ikoni",
    "Date et heure exactes pour envoyer le rappel (prioritaire sur \"temps avant\")": "Tarehe na saa halisi ya kutuma ukumbusho (kipaumbele juu ya \"muda kabla\")",
    "Frère/Sœur": "Kaka/Dada",
    "Prêt": "Tayari",
    "Ex-æquo": "Sare",
    "1er - Or": "Wa 1 - Dhahabu",
    "True si ajouté manuellement par l'organisateur": "Kweli ikiwa imeongezwa kwa mkono na mwandaaji",
    "Ex: Mérite, Encouragement (affiché si show_title=True)": "Mfano: Sifa, Hamasa (inaonyeshwa ikiwa show_title=True)",
    "Entrées au podium": "Viingilio kwenye jukwaa la tuzo",
    "Prête": "Tayari",
    "Verrouillé le": "Imefungwa tarehe",
    "Nombre de notes": "Idadi ya alama",
    "Moyenne des notes": "Wastani wa alama",
    "Verrouillage juge par catégorie": "Kufunga hakimu kwa kategoria",
    "Verrouillages juges par catégorie": "Kufunga waamuzi kwa kategoria",
    "1 = Tour initial, 2+ = Barrages": "1 = Raundi ya kwanza, 2+ = Raundi za ziada",
    "Le nom d'utilisateur ne peut pas être vide": "Jina la mtumiaji haliwezi kuwa tupu",
    "Le nom d'utilisateur doit contenir au moins 3 caractères": "Jina la mtumiaji lazima liwe na herufi 3 au zaidi",
    "Le nom d'utilisateur ne peut pas dépasser 30 caractères": "Jina la mtumiaji haliwezi kuzidi herufi 30",
    "Caractères autorisés : lettres, chiffres, point et underscore": "Herufi zinazoruhusiwa: herufi, nambari, nukta na mstari wa chini",
    "Ce nom d'utilisateur est déjà pris": "Jina hili la mtumiaji tayari limechukuliwa",
    "Ce pratiquant possède déjà un compte utilisateur": "Mtendaji huyu tayari ana akaunti ya mtumiaji",
    "Compte créé avec succès": "Akaunti imeundwa kwa mafanikio",
    "Vos identifiants de connexion MartialComp": "Vitambulisho vyako vya kuingia MartialComp",
    "Certifie que {recipient_name} a obtenu la certification de {certification_type} niveau {level} en date du {date}.": "Inathibitisha kuwa {recipient_name} amepata uthibitisho wa {certification_type} kiwango cha {level} tarehe {date}.",
    "%(count)d combat(s) planifié(s) non joué(s).": "Mapigano %(count)d yaliyopangwa hayakuchezwa.",
    "%(count)d catégorie(s) marquée(s) comme terminée(s).": "Kategoria %(count)d zimewekwa alama kuwa zimekamilika.",
    "%(count)d résultat(s) de combat généré(s).": "Matokeo %(count)d ya mapigano yamezalishwa.",
    "%(count)d résultat(s) technique(s) généré(s).": "Matokeo %(count)d ya ufundi yamezalishwa.",
    "Combats: %(combats)d | V: %(v)d | D: %(d)d | N: %(n)d | Points: %(pf)s - %(pa)s": "Mapigano: %(combats)d | U: %(v)d | K: %(d)d | S: %(n)d | Pointi: %(pf)s - %(pa)s",
    "Nul": "Sare",
    "Le mode équipe peut être maintenu": "Aina ya timu inaweza kuendelea",
    "Envisager des fusions d'équipes ou basculement vers individuel": "Fikiria kuunganisha timu au kubadilisha kuwa mtu binafsi",
    "Basculement vers mode individuel recommandé": "Kubadilisha kuwa aina ya mtu binafsi kunapendekezwa",
    "Aucune équipe n'a un effectif complet. Basculement vers mode individuel recommandé.": "Hakuna timu yenye idadi kamili ya wanachama. Kubadilisha kuwa aina ya mtu binafsi kunapendekezwa.",
    "Seulement {completes}/{requis} équipes ont un effectif complet. Envisagez des fusions ou un basculement vers le mode individuel.": "Timu {completes}/{requis} peke yake zina idadi kamili. Fikiria kuunganisha au kubadilisha kuwa aina ya mtu binafsi.",
    "{insuffisantes} équipe(s) ont un effectif insuffisant et pourraient bénéficier d'une fusion.": "Timu {insuffisantes} zina idadi ya kutosha ya wanachama na zinaweza kufaidika na muungano.",
    "Basculer vers le mode individuel": "Badilisha kuwa aina ya mtu binafsi",
    "Réinitialisation de votre mot de passe MartialComp": "Kuweka upya nenosiri lako la MartialComp",
    "Bienvenue sur MartialComp - Connexion via %(provider)s réussie": "Karibu MartialComp - Kuingia kupitia %(provider)s kumefanikiwa",
    "Le club d'accueil a atteint le maximum d'ententes autorisées ({max})": "Klabu inayopokea imefikia kiwango cha juu cha makubaliano yaliyoruhusiwa ({max})",
    "L'entente doit être approuvée pour assigner une équipe": "Makubaliano lazima yaidhinishwe ili kugawa timu",
    "L'équipe doit appartenir au club d'accueil": "Timu lazima iwe ya klabu inayopokea",
    "Age minimum requis: %(min_age)d ans (actuellement %(current_age)d ans)": "Umri wa chini unaohitajika: miaka %(min_age)d (kwa sasa miaka %(current_age)d)",
    "Age minimum: %(age)d ans": "Umri wa chini: miaka %(age)d",
    "- de 6 ans (filles)": "Chini ya miaka 6 (wasichana)",
    "- de 6 ans (garçons)": "Chini ya miaka 6 (wavulana)",
    "Filles de 6 à 8 ans": "Wasichana wa miaka 6 hadi 8",
    "Garçons de 6 à 8 ans": "Wavulana wa miaka 6 hadi 8",
    "Filles de 9 à 12 ans": "Wasichana wa miaka 9 hadi 12",
    "Garçons de 9 à 12 ans": "Wavulana wa miaka 9 hadi 12",
    "Femmes de 13 à 17 ans": "Wanawake wa miaka 13 hadi 17",
    "Hommes de 13 à 17 ans": "Wanaume wa miaka 13 hadi 17",
    "Femmes de 18 à 21 ans": "Wanawake wa miaka 18 hadi 21",
    "Hommes de 18 à 21 ans": "Wanaume wa miaka 18 hadi 21",
    "Femmes de 22 à 34 ans": "Wanawake wa miaka 22 hadi 34",
    "Hommes de 22 à 34 ans": "Wanaume wa miaka 22 hadi 34",
    "Femmes de 35 à 49 ans": "Wanawake wa miaka 35 hadi 49",
    "Hommes de 35 à 49 ans": "Wanaume wa miaka 35 hadi 49",
    "Femmes de 50 à 64 ans": "Wanawake wa miaka 50 hadi 64",
    "Hommes de 50 à 64 ans": "Wanaume wa miaka 50 hadi 64",
    "Femmes de 65 ans et plus": "Wanawake wa miaka 65 na zaidi",
    "Hommes de 65 ans et plus": "Wanaume wa miaka 65 na zaidi",
    "AEI - AESS": "AEI - AESS",
    "ADEPS MS niveau 1": "ADEPS MS kiwango cha 1",
    "ADEPS MS niveau 2": "ADEPS MS kiwango cha 2",
    "ADEPS MS niveau 3; 4": "ADEPS MS kiwango cha 3; 4",
    "Troisième place": "Nafasi ya tatu",
    "Deuxième place": "Nafasi ya pili",
}
