# -*- coding: utf-8 -*-
TRANSLATIONS = {
    "Prioritaires": "Za Kipaumbele",
    "Mode Juge/Arbitre": "Aina ya Hakimu/Mwamuzi",
    "Visualisez toutes vos competitions, examens de grade, evenements du club et deadlines d'inscription": "Tazama mashindano yako yote, mitihani ya daraja, matukio ya klabu na tarehe za mwisho za usajili",
    "Découvrir des compétitions": "Gundua mashindano",
    "Consultez les compétitions disponibles pour vous inscrire.": "Angalia mashindano yanayopatikana kwa kusajili.",
    "Rechercher une compétition": "Tafuta mashindano",
    "Voir mes résultats": "Tazama matokeo yangu",
    "Dernier jour !": "Siku ya mwisho!",
    "Aucune compétition n'est ouverte aux inscriptions pour le moment.": "Hakuna mashindano yaliyofunguliwa kwa usajili kwa sasa.",
    "COMPÉTITIONS": "MASHINDANO",
    "ENTRAÎNEMENT": "MAZOEZI",
    "FINANCES": "FEDHA",
    "FAMILLE": "FAMILIA",
    "MON COMPTE": "AKAUNTI YANGU",
    "Voici un aperçu de votre activité sportive": "Hii ni muhtasari wa shughuli yako ya michezo",
    "Vous êtes également juge/arbitre": "Pia wewe ni hakimu/mwamuzi",
    "Basculez vers votre interface de juge pour noter les compétitions": "Badilisha kwenda kiolesura chako cha hakimu kutoa alama kwa mashindano",
    "Paiements dus": "Malipo yanayodaiwa",
    "Aucune compétition prévue": "Hakuna mashindano yaliyopangwa",
    "Inscrivez-vous à des compétitions pour les voir apparaître ici": "Sajili mashindano ili kuyaona yakionekana hapa",
    "Mon entraînement": "Mazoezi yangu",
    "Programme complet": "Programu kamili",
    "Notre équipe est là pour vous aider": "Timu yetu ipo hapa kukusaidia",
    "Pour commencer à participer aux compétitions, créez votre profil de participant": "Ili kuanza kushiriki mashindano, unda wasifu wako wa mshiriki",
    "Cliquez pour modifier votre photo": "Bofya kurekebisha picha yako",
    "Mode Juge": "Aina ya Hakimu",
    "Inscrivez-vous à une compétition pour commencer": "Sajili mashindano ili kuanza",
    "Votre calendrier est vide pour les 30 prochains jours": "Kalenda yako ni tupu kwa siku 30 zijazo",
    "Modifier la photo": "Rekebisha picha",
    "Modifier ma photo de profil": "Rekebisha picha yangu ya wasifu",
    "Sélectionner une nouvelle photo": "Chagua picha mpya",
    "Formats acceptés : JPG, PNG, GIF. Taille maximum : 5 Mo": "Muundo unaokubaliwa: JPG, PNG, GIF. Ukubwa wa juu: MB 5",
    "Supprimer la photo actuelle": "Futa picha ya sasa",
    "La taille du fichier ne doit pas dépasser 5 Mo": "Ukubwa wa faili hauwezi kuzidi MB 5",
    "Veuillez sélectionner une image valide": "Tafadhali chagua picha halali",
    "Mode Pratiquant": "Aina ya Mtendaji",
    "Juge Ad-Hoc Temporaire": "Hakimu wa Dharura wa Muda",
    "Vous êtes actuellement assigné comme juge temporaire pour": "Kwa sasa umegawiwa kama hakimu wa muda kwa",
    "compétition(s).": "mashindano.",
    "Mes assignations ad-hoc": "Ugawaji wangu wa dharura",
    "Type de rôle": "Aina ya jukumu",
    "Nous avons le plaisir de vous informer qu'un compte utilisateur a été créé pour vous sur MartialComp.": "Tunafurahi kukuarifu kuwa akaunti ya mtumiaji imeundwa kwa ajili yako kwenye MartialComp.",
    "Vos identifiants de connexion": "Vitambulisho vyako vya kuingia",
    "Pour votre sécurité, vous devrez changer ce mot de passe lors de votre première connexion.": "Kwa usalama wako, utalazimika kubadilisha nenosiri hili wakati wa kuingia kwako kwa mara ya kwanza.",
    "Avec votre compte, vous pourrez": "Na akaunti yako, utaweza",
    "Consulter vos informations personnelles": "Angalia taarifa zako binafsi",
    "Voir vos inscriptions aux compétitions": "Tazama usajili wako wa mashindano",
    "Suivre vos résultats et palmarès": "Fuatilia matokeo yako na tuzo",
    "Accéder à votre carte d'identité numérique": "Fikia kadi yako ya kitambulisho cha kidijitali",
    "Passer des commandes dans la boutique": "Weka oda katika duka",
    "Se connecter à MartialComp": "Ingia kwenye MartialComp",
    "Si vous rencontrez des difficultés, contactez votre responsable de club.": "Ikiwa unakabiliwa na ugumu, wasiliana na msimamizi wa klabu yako.",
    "Si vous avez reçu cet email par erreur, veuillez l'ignorer.": "Ikiwa umepokea barua pepe hii kwa kosa, tafadhali ipuuze.",
    "Ajoutez des questions personnalisées au-delà des options de date/heure pour collecter plus d'informations des participants.": "Ongeza maswali maalum zaidi ya chaguo za tarehe/saa kukusanya taarifa zaidi kutoka kwa washiriki.",
    "Les questions personnalisées seront disponibles après l'application des dernières mises à jour de la base de données.": "Maswali maalum yatapatikana baada ya kutumia sasisho za hivi karibuni za hifadhidata.",
    "Entrez l\\'URL:": "Ingiza URL:",
    "Personne ne s'est encore inscrit a cet evenement.": "Hakuna mtu aliyesajili kwa tukio hili bado.",
    "L\\'extension du fichier n\\'est pas autorisée. Utilisez JPG, JPEG, PNG ou SVG.": "Ugani wa faili hauruhusiwi. Tumia JPG, JPEG, PNG au SVG.",
    "\n                            Attention : %(count)s participant(s) sont inscrits à cette formation. La suppression entraînera également la suppression de toutes les inscriptions associées.\n                            ": "\n                            Tahadhari: Washiriki %(count)s wamesajiliwa kwa mafunzo haya. Kufuta kutasababisha pia kufutwa kwa usajili wote unaohusiana.\n                            ",
    "Âge min.": "Umri wa chini",
    "\n                                Expire le %(end_date)s\n                            ": "\n                                Inaisha %(end_date)s\n                            ",
    "\n                                Jusqu'au %(end_date)s\n                            ": "\n                                Hadi %(end_date)s\n                            ",
    "\n                %(remaining)s restants\n            ": "\n                %(remaining)s iliyobaki\n            ",
    "Toutes les notifications ont été marquées comme lues": "Arifa zote zimewekwa alama kuwa zimesomwa",
    "Recrutement de Juges Ad-Hoc": "Kuajiri Waamuzi wa Dharura",
    "Recrutez des participants adultes (18+) comme juges temporaires. Ils seront disponibles dans les onglets 'Juges Techniques' et 'Arbitres' ci-dessus.": "Ajiri washiriki watu wazima (18+) kama waamuzi wa muda. Watapatikana katika vichupo vya 'Waamuzi wa Ufundi' na 'Waamuzi' hapo juu.",
    "Pratiquants discipline": "Watendaji wa taaluma",
    "Juges ad-hoc recrutés": "Waamuzi wa dharura walioajiriwa",
    "Recruter comme": "Ajiri kama",
    "Ces pratiquants ne sont pas inscrits à la compétition. Un compte utilisateur sera créé si nécessaire.": "Watendaji hawa hawajasajiliwa kwa mashindano. Akaunti ya mtumiaji itaundwa ikiwa ni lazima.",
    "Aucun participant adulte éligible trouvé": "Hakuna mshiriki mtu mzima anayestahiki aliyepatikana",
    "Recruté": "Ameajiriwa",
    "Déjà recruté comme Juge Technique": "Tayari ameajiriwa kama Hakimu wa Ufundi",
    "Juge Tech.": "Hak. Ufundi",
    "Recruter comme Juge Technique": "Ajiri kama Hakimu wa Ufundi",
    "Déjà recruté comme Arbitre": "Tayari ameajiriwa kama Mwamuzi",
    "Recruter comme Arbitre Combat": "Ajiri kama Mwamuzi wa Mapigano",
    "Aucun pratiquant de la discipline disponible": "Hakuna mtendaji wa taaluma anayepatikana",
    "Compte à créer": "Akaunti ya kuundwa",
    "Aucun juge ad-hoc recruté": "Hakuna hakimu wa dharura aliyeajiriwa",
    "Utilisez les boutons ci-dessus pour recruter des juges": "Tumia vitufe hapo juu kuajiri waamuzi",
    "Compte en attente": "Akaunti inayosubiri",
    "recruté comme": "ameajiriwa kama",
    "Retirer ce juge de la compétition ?": "Ondoa hakimu huyu kutoka mashindano?",
    "Juge retiré avec succès": "Hakimu ameondolewa kwa mafanikio",
    "Juge activé": "Hakimu amewashwa",
    "Erreur lors de l'activation": "Hitilafu wakati wa kuwasha",
    "Juge supprimé": "Hakimu amefutwa",
    "Nom, prénom, licence, club...": "Jina, jina la kwanza, leseni, klabu...",
    "Par page": "Kwa ukurasa",
    "Actions en lot...": "Vitendo kwa wingi...",
    "Mettre en attente": "Weka kusubiri",
    "Veuillez sélectionner une action.": "Tafadhali chagua kitendo.",
    "Veuillez sélectionner au moins une inscription.": "Tafadhali chagua angalau usajili mmoja.",
    "Êtes-vous sûr de vouloir supprimer les inscriptions sélectionnées ? Cette action est irréversible.": "Je, una uhakika unataka kufuta usajili uliochaguliwa? Kitendo hiki hakiwezi kurejeshwa.",
    "Âge:": "Umri:",
    "Veuillez sélectionner un juge, une catégorie et un type d'assignation.": "Tafadhali chagua hakimu, kategoria na aina ya ugawaji.",
    "Rechercher un praticien existant": "Tafuta mtaalamu aliyepo",
    "Rechercher par nom ou prénom...": "Tafuta kwa jina au jina la kwanza...",
    "Informations du participant": "Taarifa za mshiriki",
    "Performances et Scores": "Utendaji na Alama",
    "scores": "alama",
    "Pas encore noté": "Bado haijapewa alama",
    "Aucune performance pour cette catégorie.": "Hakuna utendaji kwa kategoria hii.",
    "Aucune catégorie n'a été créée pour cette compétition. Créez d'abord des catégories pour configurer le scoring.": "Hakuna kategoria iliyoundwa kwa mashindano haya. Unda kwanza kategoria ili kusanidi alama.",
    "Organisation non définie": "Shirika halijafafanuliwa",
    "Pratiquant non défini": "Mtendaji hajafafanuliwa",
    "Utilisé pour l'estimation": "Inatumika kwa makisio",
    "Choisissez le format d'exportation.": "Chagua muundo wa usafirishaji.",
    "Temps de pause entre les matchs (minutes)": "Muda wa pumziko kati ya mechi (dakika)",
    "Horaires spéciaux": "Ratiba maalum",
    "Configurez les horaires pour la pause, la pesée, le briefing et la cérémonie.": "Sanidi ratiba kwa pumziko, kupima uzito, mkutano na sherehe.",
    "Fonctionnalité à venir": "Kipengele kinachokuja",
    "Gérer affectations": "Simamia ugawaji",
    "Inviter": "Alika",
    "Aucun juge disponible pour les disciplines de cette compétition.": "Hakuna hakimu anayepatikana kwa taaluma za mashindano haya.",
    "Juge inconnu": "Hakimu asiyejulikana",
    "Aucun juge assigné à cette catégorie.": "Hakuna hakimu aliyegawiwa kwa kategoria hii.",
    "Aucune qualification trouvée": "Hakuna sifa iliyopatikana",
    "Êtes-vous sûr de vouloir retirer ce juge de la compétition ? Toutes ses assignations seront supprimées.": "Je, una uhakika unataka kumwondoa hakimu huyu kutoka mashindano? Ugawaji wake wote utafutwa.",
    "de cette compétition ?": "kutoka mashindano haya?",
    "Êtes-vous sûr de vouloir retirer cette assignation ?": "Je, una uhakika unataka kuondoa ugawaji huu?",
    "Export en cours...": "Usafirishaji unaendelea...",
    "Pas d\\'": "Hakuna\\'",
    "Sélectionner un pratiquant...": "Chagua mtendaji...",
    "Ex: Mérite, Encouragement...": "Mfano: Sifa, Hamasa...",
    "URL principale": "URL kuu",
    "URL alternative disponible": "URL mbadala inapatikana",
    "URLs disponibles": "URL zinazopatikana",
    "URL alternative (tableau de bord)": "URL mbadala (dashibodi)",
    "Vous devez accepter les conditions d\\'utilisation et l\\'utilisation de vos données personnelles.": "Lazima ukubali masharti ya matumizi na matumizi ya data yako binafsi.",
    "Optimiser le planning automatiquement ?": "Boresha ratiba kiotomatiki?",
    "Vérifier conflits": "Angalia migogoro",
    "Publier le planning ?": "Chapisha ratiba?",
    "Gérer les tatamis": "Simamia tatami",
    "Aucun tatami configuré. Veuillez configurer les tatamis dans les paramètres du planning.": "Hakuna tatami iliyosanidiwa. Tafadhali sanidi tatami katika mipangilio ya ratiba.",
    "Toutes les catégories sont planifiées.": "Kategoria zote zimepangwa.",
    "Planifiées": "Zimepangwa",
    "Supprimer cette catégorie du planning ?": "Futa kategoria hii kutoka ratiba?",
    "Dernières modifications": "Marekebisho ya mwisho",
    "Aucune modification récente": "Hakuna marekebisho ya hivi karibuni",
    "Heure de debut": "Saa ya kuanza",
    "Duree estimee (minutes)": "Muda unaokadiriwa (dakika)",
    "Statistiques de Notation": "Takwimu za Alama",
    "Total Performances": "Jumla ya Utendaji",
    "Statistiques par Juge": "Takwimu kwa Hakimu",
    "Total scores": "Jumla ya alama",
    "Aucun juge assigné à cette catégorie": "Hakuna hakimu aliyegawiwa kwa kategoria hii",
    "Statistiques par Critère": "Takwimu kwa Kigezo",
    "Aucun critère configuré pour cette catégorie": "Hakuna kigezo kilichosanidiwa kwa kategoria hii",
    "Dernières Performances": "Utendaji wa Hivi Karibuni",
    "Aucune performance pour cette catégorie": "Hakuna utendaji kwa kategoria hii",
    "Pour accéder à ce site en local, ajoutez cette ligne à votre fichier hosts :": "Kufikia tovuti hii ndani, ongeza mstari huu kwenye faili yako ya hosts:",
    "--- Sélectionnez un pays ---": "--- Chagua nchi ---",
    "Sélectionnez une ou plusieurs disciplines pratiquées dans votre club": "Chagua taaluma moja au zaidi zinazofanywa katika klabu yako",
    "Problème Technique": "Tatizo la Kiufundi",
    "Un problème technique est survenu": "Tatizo la kiufundi limetokea",
    "Nous sommes désolés, mais nous rencontrons actuellement un problème temporaire.": "Tunasikitika, lakini kwa sasa tunakabiliwa na tatizo la muda.",
    "Bonne nouvelle !": "Habari njema!",
    "Notre équipe technique a été automatiquement notifiée et travaille à résoudre ce problème.": "Timu yetu ya ufundi imearifiwa kiotomatiki na inafanya kazi kutatua tatizo hili.",
    "Que pouvez-vous faire ?": "Unaweza kufanya nini?",
    "Réessayer dans quelques minutes": "Jaribu tena baada ya dakika chache",
    "Vérifier votre connexion internet": "Angalia muunganisho wako wa mtandao",
    "Consulter notre centre d'aide": "Tembelea kituo chetu cha msaada",
    "Code d'erreur :": "Msimbo wa hitilafu:",
    "R&ocirc;le": "Jukumu",
    "T&eacute;l&eacute;phone": "Simu",
    "Cr&eacute;er ma f&eacute;d&eacute;ration": "Unda shirikisho langu",
    "Organisez des événements sans être affilié à un club.": "Andaa matukio bila kushirikishwa na klabu.",
    "Répartition": "Ugawaji",
    "Consultez l'historique de vos factures et leur statut": "Angalia historia ya ankara zako na hali zake",
    "Total factures": "Jumla ya ankara",
    "Aucune facture": "Hakuna ankara",
    "Vous n'avez pas encore de factures": "Bado huna ankara",
    "Historique et suivi de vos paiements": "Historia na ufuatiliaji wa malipo yako",
    "Complétés": "Yamekamilika",
    "Programmés": "Yaliyopangwa",
    "Initiés": "Yaliyoanzishwa",
    "Tous les moyens": "Njia zote",
    "Aucun paiement": "Hakuna malipo",
    "Vous n'avez pas encore effectué de paiements": "Bado hujafanya malipo",
    "Historique complet de vos transactions financières": "Historia kamili ya miamala yako ya kifedha",
    "Crédits": "Mikopo",
    "Débits": "Malipo",
    "Vous n'avez pas encore de transactions": "Bado huna miamala",
    "Le code de vérification se trouve généralement en bas du certificat, près du QR code.": "Msimbo wa uthibitishaji kwa kawaida uko chini ya cheti, karibu na QR code.",
    "Cette vérification confirme l'authenticité du certificat dans notre registre officiel.": "Uthibitishaji huu unathibitisha uhalisi wa cheti katika daftari letu rasmi.",
    "Votre navigateur ne supporte pas l\\'": "Kivinjari chako hakisaidii\\'",
    "Impossible d\\'": "Haiwezekani\\'",
    "Back to Dashboard": "Rudi kwenye Dashibodi",
    "Configure the scoring system and parameters for this category. Leave fields blank to use system defaults.": "Sanidi mfumo wa alama na vigezo kwa kategoria hii. Acha sehemu tupu kutumia mipangilio ya kawaida ya mfumo.",
    "Override Settings (Optional)": "Badilisha Mipangilio (Hiari)",
    "Leave these fields blank to use the scoring system defaults.": "Acha sehemu hizi tupu kutumia mipangilio ya kawaida ya mfumo wa alama.",
    "Cancel": "Ghairi",
    "Save Configuration": "Hifadhi Usanidi",
    "Tableau de bord - Scoring": "Dashibodi - Alama",
    "Vue d'ensemble complète de vos compétitions et performances": "Muhtasari kamili wa mashindano yako na utendaji",
    "Disqualifiée": "Imefukuzwa",
    "Aucune performance trouvée": "Hakuna utendaji uliopatikana",
    "Aucune compétition active trouvée": "Hakuna mashindano hai yaliyopatikana",
    "Configurations de catégories": "Usanidi wa kategoria",
    "Aucune configuration de catégorie trouvée": "Hakuna usanidi wa kategoria uliopatikana",
    "Accès rapide aux fonctionnalités principales": "Ufikiaji wa haraka wa vipengele vikuu",
    "Créer un système de notation": "Unda mfumo wa alama",
    "Créer un critère": "Unda kigezo",
    "Gérer les critères": "Simamia vigezo",
    "Edit Scoring Criterion": "Rekebisha Kigezo cha Alama",
    "Create Scoring Criterion": "Unda Kigezo cha Alama",
    "Edit Scoring System": "Rekebisha Mfumo wa Alama",
    "Ajouter une catégorie de notation": "Ongeza kategoria ya alama",
    "Créez une nouvelle catégorie pour l'évaluation technique": "Unda kategoria mpya kwa tathmini ya ufundi",
    "Sélectionnez une compétition pour laquelle créer cette catégorie.": "Chagua mashindano ya kuunda kategoria hii.",
    "-- Sélectionnez une compétition --": "-- Chagua mashindano --",
    "Catégorie pour la compétition :": "Kategoria kwa mashindano:",
    "Optionnel : sélectionnez un template pour pré-remplir les champs": "Hiari: chagua kiolezo cha kujaza mapema sehemu",
    "Évaluation des biais potentiels dans les notations": "Tathmini ya upendeleo unaowezekana katika alama",
    "Export PDF": "Usafirishaji PDF",
    "Risque faible": "Hatari ya chini",
    "Risque modéré": "Hatari ya wastani",
    "Classement basé sur le score de neutralité global": "Cheo kinachotegemea alama ya haki ya jumla",
    "Pas assez de données pour afficher le podium": "Data haitoshi kuonyesha jukwaa la tuzo",
    "Sélectionnez les juges à comparer (maximum 6 pour une meilleure lisibilité)": "Chagua waamuzi wa kulinganisha (upeo 6 kwa usomaji bora)",
    "Biais Club": "Upendeleo wa Klabu",
    "Maximum 6 juges peuvent être comparés simultanément": "Waamuzi 6 upeo wanaweza kulinganishwa kwa wakati mmoja",
    "Verrouiller les notations": "Funga alama",
    "Pratiquants notés": "Watendaji waliopewa alama",
    "Note min": "Alama ya chini",
    "Note max": "Alama ya juu",
    "ATTENTION": "TAHADHARI",
    "Une fois verrouillées, vos notes ne pourront plus être modifiées.": "Mara zitakapofungwa, alama zako hazitaweza kurekebishwa tena.",
    "Je confirme avoir vérifié toutes mes notes": "Ninathibitisha nimeangalia alama zangu zote",
    "Verrouiller": "Funga",
    "Classement provisoire": "Cheo cha muda",
    "Chargement du classement...": "Kupakia cheo...",
    "Aucun classement disponible pour le moment.": "Hakuna cheo kinachopatikana kwa sasa.",
    "Sélectionnez une note": "Chagua alama",
    "Insuffisant": "Haitoshi",
    "Passable": "Inakubalika",
    "Assez bien": "Vizuri vya kutosha",
    "Bien": "Vizuri",
    "Excellent": "Bora kabisa",
    "Ajoutez un commentaire sur cette note...": "Ongeza maoni kuhusu alama hii...",
    "Entrée": "Ingizo",
    "Échap": "Toroka",
    "Valider la note": "Thibitisha alama",
    "Cela peut signifier qu'aucune prestation technique n'a été notée, ou que les données sont stockées dans un autre format.": "Hii inaweza kumaanisha kuwa hakuna utendaji wa ufundi uliopewa alama, au data imehifadhiwa katika muundo mwingine.",
    "Évaluez les performances techniques": "Tathmini utendaji wa ufundi",
    "Précision": "Usahihi",
    "Nom à venir": "Jina litakuja",
    "Catégorie à définir": "Kategoria ya kufafanua",
    "Qualité d'exécution des mouvements": "Ubora wa utekelezaji wa mienendo",
    "Précision (0-10)": "Usahihi (0-10)",
    "Fluidité et esthétique": "Ulaini na uzuri",
    "Sauvegarde en brouillon à implémenter": "Hifadhi kama rasimu itatekelezwa",
    "Veuillez renseigner tous les critères de notation.": "Tafadhali jaza vigezo vyote vya alama.",
    "Soumission du formulaire à implémenter": "Uwasilishaji wa fomu utatekelezwa",
    "Feuille de notation": "Karatasi ya alama",
    "notés": "wamepewa alama",
    "Réinitialiser mes notes (test)": "Weka upya alama zangu (jaribio)",
    "Reset (Test)": "Weka upya (Jaribio)",
    "Tour 1": "Raundi 1",
    "Tour 2": "Raundi 2",
    "Cliquez pour noter": "Bofya kutoa alama",
    "Noter Tour 1": "Toa alama Raundi 1",
    "T1": "R1",
    "Modifier Tour 1": "Rekebisha Raundi 1",
    "Noter Tour 2": "Toa alama Raundi 2",
    "T2": "R2",
    "Modifier Tour 2": "Rekebisha Raundi 2",
    "Aucune performance programmée pour cette catégorie.": "Hakuna utendaji uliopangwa kwa kategoria hii.",
    "Notés": "Wamepewa alama",
    "Aucun classement disponible": "Hakuna cheo kinachopatikana",
    "Cette page teste le système automatique de gestion des jetons CSRF.": "Ukurasa huu unajaribu mfumo wa kiotomatiki wa usimamizi wa tokeni za CSRF.",
    "Entrez du texte pour tester": "Ingiza maandishi kwa kujaribu",
    "Test requête AJAX": "Jaribio la ombi la AJAX",
    "Cliquez sur 'Test requête AJAX' pour tester les requêtes asynchrones": "Bofya 'Jaribio la ombi la AJAX' kujaribu maombi ya asynchronous",
    "Utilisez 'Rafraîchir jeton CSRF' pour tester le rafraîchissement automatique": "Tumia 'Pya tokeni ya CSRF' kujaribu upyaji kiotomatiki",
    "Ouvrez la console du navigateur pour voir les logs détaillés": "Fungua konsoli ya kivinjari kuona kumbukumbu za kina",
    "Le système gère automatiquement l'expiration et le rafraîchissement des jetons CSRF.": "Mfumo unasimamia kiotomatiki kuisha na upyaji wa tokeni za CSRF.",
    "Jeton reçu : ": "Tokeni iliyopokelewa: ",
    "Flux d'onboarding attendu :": "Mtiririko wa kuanza unaotarajiwa:",
    "- L'utilisateur s'inscrit via le formulaire ou OAuth": "- Mtumiaji anasajili kupitia fomu au OAuth",
    "- Un profil UserProfile est automatiquement créé": "- Wasifu wa UserProfile unaundwa kiotomatiki",
    "- L'utilisateur choisit son rôle (coach, participant, etc.)": "- Mtumiaji anachagua jukumu lake (kocha, mshiriki, n.k.)",
    "Le middleware OnboardingRedirectMiddleware s'assure que les utilisateurs non configurés sont automatiquement redirigés vers l'onboarding.": "Middleware ya OnboardingRedirectMiddleware inahakikisha kuwa watumiaji ambao hawajasanidiwa wanaelekezwa kiotomatiki kwenye kuanza.",
    "' + JSON.stringify(data, null, 2) + '": "' + JSON.stringify(data, null, 2) + '",
    "Test WebSocket - Notation Technique": "Jaribio la WebSocket - Alama za Ufundi",
    "Connexion WebSocket": "Muunganisho wa WebSocket",
    "Déconnecté": "Imekatwa muunganisho",
    "ID de la compétition": "Kitambulisho cha mashindano",
    "Ping": "Ping",
    "Simulation de Notation": "Uigaji wa Alama",
    "ID Performance": "Kitambulisho cha Utendaji",
    "ID Critère": "Kitambulisho cha Kigezo",
    "Journal WebSocket": "Kumbukumbu ya WebSocket",
    "En attente de connexion...": "Inasubiri muunganisho...",
    "Connexion en cours...": "Kuunganisha...",
    "Veuillez entrer un ID de compétition": "Tafadhali ingiza kitambulisho cha mashindano",
    "Tentative de connexion...": "Jaribio la kuunganisha...",
    "Connexion établie": "Muunganisho umeanzishwa",
    "Message reçu": "Ujumbe umepokelewa",
    "Juge connecté": "Hakimu ameunganishwa",
    "Juge déconnecté": "Hakimu amekatwa muunganisho",
    "Score mis à jour": "Alama imesasishwa",
    "Erreur WebSocket": "Hitilafu ya WebSocket",
    "Connexion fermée proprement": "Muunganisho umefungwa vizuri",
    "Connexion perdue": "Muunganisho umepotea",
    "Message envoyé": "Ujumbe umetumwa",
    "WebSocket non connecté": "WebSocket haijaunganishwa",
    "Joyeuses Fêtes de la part de toute l'équipe MartialComp !": "Sherehe njema kutoka timu yote ya MartialComp!",
    "Des tarifs simples et accessibles, identiques partout dans le monde": "Bei rahisi na zinazopatikana, sawa popote ulimwenguni",
    "Les fédérations affiliées bénéficient d'une commission de 7%% sur les abonnements de leurs clubs membres. Un système gagnant-gagnant pour développer la communauté des arts martiaux.": "Mashirikisho yanayoshirikishwa hufaidika na kamisheni ya 7%% juu ya usajili wa klabu zao za wanachama. Mfumo wa kushinda-kushinda kuendeleza jumuiya ya sanaa za kijeshi.",
    "Phase de test en cours (1er-30 juin 2025) – \n        Lancement officiel: 1er juillet 2025 – \n        ": "Awamu ya majaribio inaendelea (1-30 Juni 2025) – \n        Uzinduzi rasmi: 1 Julai 2025 – \n        ",
    "ELIGIBLE": "ANASTAHIKI",
    "BLOQUE": "IMEZUIWA",
    "GRADE MAXIMUM": "DARAJA LA JUU",
    "EN PROGRESSION": "INAENDELEA",
    "Site actif": "Tovuti hai",
    "Gérez votre site web automatique et vos QR codes pour maximiser votre visibilité": "Simamia tovuti yako ya kiotomatiki na QR code zako ili kuongeza uonekano wako",
    "Gérez vos QR codes d'inscription et de promotion pour faciliter l'accès à vos services": "Simamia QR code zako za usajili na matangazo ili kurahisisha ufikiaji wa huduma zako",
    "Aucun QR code généré pour le moment": "Hakuna QR code iliyozalishwa kwa sasa",
    "Générer les QR codes": "Zalisha QR code",
    "Personnalisez l'apparence de votre site pour refléter votre identité": "Binafsisha mwonekano wa tovuti yako kuonyesha utambulisho wako",
    "1920 x 600 px recommandé": "1920 x 600 px inapendekezwa",
    "Formats: JPG, PNG, WebP. Max 5 Mo. Dimensions recommandées: 1920x600px": "Muundo: JPG, PNG, WebP. Upeo MB 5. Vipimo vinavyopendekezwa: 1920x600px",
    "Max 6 images. JPG, PNG, WebP. Max 3 Mo par image.": "Upeo picha 6. JPG, PNG, WebP. Upeo MB 3 kwa picha.",
    "Couleur d accent": "Rangi ya msisitizo",
    "Décrivez votre organisation en quelques mots...": "Elezea shirika lako kwa maneno machache...",
    "Aperçu non disponible": "Onyesho halipatikani",
    "Le site sera visible une fois configuré": "Tovuti itaonekana mara itakaposanidiwa",
    "Scans cette semaine": "Usomaji wiki hii",
    "Expiration": "Kuisha",
    "Couleur modifiée. Cliquez sur Sauvegarder pour appliquer.": "Rangi imebadilishwa. Bofya Hifadhi kutumia.",
    "Téléchargement en cours...": "Upakuaji unaendelea...",
    "Lien non disponible": "Kiungo hakipatikani",
    "Génération de l aper\u00e7u...": "Kuzalisha onyesho...",
    "Erreur lors de la génération de l aperçu": "Hitilafu wakati wa kuzalisha onyesho",
    "Personnalisation sauvegardée avec succès": "Ubinafsishaji umehifadhiwa kwa mafanikio",
    "Utilisez le bouton Visiter le site pour voir les changements": "Tumia kitufe cha Tembelea tovuti kuona mabadiliko",
    "Session expirée. Veuillez vous reconnecter.": "Kipindi kimeisha. Tafadhali ingia tena.",
    "Martial Arts Club": "Klabu ya Sanaa za Kijeshi",
    "Services": "Huduma",
    "Excellence, Discipline, Tradition - Your journey in martial arts begins here": "Ubora, Nidhamu, Mila - Safari yako katika sanaa za kijeshi inaanza hapa",
    "Discover our classes": "Gundua madarasa yetu",
    "What we offer": "Tunachotoa",
    "Discover comprehensive martial arts training with qualified instructors": "Gundua mafunzo kamili ya sanaa za kijeshi na wakufunzi wenye sifa",
    "Classes & Training": "Madarasa na Mafunzo",
    "Classes adapted to all levels, from beginner to expert. In-depth technical training with certified and passionate instructors.": "Madarasa yaliyobadilishwa kwa viwango vyote, kutoka mwanaoanza hadi mtaalamu. Mafunzo ya kina ya ufundi na wakufunzi waliothibitishwa na wenye shauku.",
    "Participate in local, national and international competitions. Develop your skills in a stimulating competitive environment.": "Shiriki katika mashindano ya ndani, kitaifa na kimataifa. Endeleza ujuzi wako katika mazingira ya ushindani yanayochochea.",
    "Join a passionate and caring community. Exchanges, events and lasting friendships in a spirit of mutual respect.": "Jiunge na jumuiya yenye shauku na inayojali. Mabadilishano, matukio na urafiki wa kudumu katika roho ya heshima ya pande zote.",
    "Our Gallery": "Mkusanyiko Wetu wa Picha",
    "Discover our club in pictures": "Gundua klabu yetu kwa picha",
    "Highlights, training sessions and events that make our community": "Mambo muhimu, vipindi vya mafunzo na matukio yanayounda jumuiya yetu",
    "Our upcoming events": "Matukio yetu yanayokuja",
    "Stay informed about upcoming competitions and events": "Baki na habari kuhusu mashindano na matukio yanayokuja",
    "Event": "Tukio",
    "No events scheduled at this time": "Hakuna matukio yaliyopangwa kwa sasa",
    "Come back soon to discover our upcoming competitions": "Rudi hivi karibuni kugundua mashindano yetu yanayokuja",
    "Use our QR codes for instant access to all our services": "Tumia QR code zetu kwa ufikiaji wa haraka wa huduma zetu zote",
    "Pay your membership fees online": "Lipa ada yako ya uanachama mtandaoni",
    "Referral": "Mapendekezo",
    "Refer your friends and get benefits": "Pendekeza marafiki wako na upate faida",
    "Equipment, uniforms and club accessories": "Vifaa, sare na vifaa vya klabu",
    "Quick access via QR code": "Ufikiaji wa haraka kupitia QR code",
    "Ready to start your journey? We are here to support you": "Tayari kuanza safari yako? Tuko hapa kukusaidia",
    "To be defined": "Itafafanuliwa",
    "Phone": "Simu",
    "Write to us": "Tuandikie",
    "Your reference martial arts club. Excellence, discipline and tradition at the service of your personal and athletic development.": "Klabu yako ya sanaa za kijeshi ya rejea. Ubora, nidhamu na mila katika huduma ya maendeleo yako binafsi na ya michezo.",
    "Complete management platform for martial arts clubs and federations. Simplify your management, focus on practice.": "Jukwaa kamili la usimamizi kwa klabu na mashirikisho ya sanaa za kijeshi. Rahisisha usimamizi wako, lenga mazoezi.",
    "All rights reserved.": "Haki zote zimehifadhiwa.",
    "l'excellence": "ubora",
    "avec un coach expert": "na kocha mtaalamu",
    "ans d'experience pour vous accompagner vers vos objectifs.": "miaka ya uzoefu kukuongoza kuelekea malengo yako.",
    "Expert dans plusieurs arts martiaux pour un enseignement complet et adapte": "Mtaalamu wa sanaa nyingi za kijeshi kwa ufundishaji kamili na uliobadilishwa",
    "Des formules adaptees a vos besoins et votre budget": "Mipango iliyobadilishwa kwa mahitaji yako na bajeti yako",
    "Ce que disent mes eleves": "Wanafunzi wangu wanasema nini",
    "Des temoignages authentiques de mes eleves": "Ushuhuda halisi kutoka kwa wanafunzi wangu",
    "Excellent coach ! Tres pedagogue et patient. J'ai progresse tres rapidement grace a son enseignement.": "Kocha bora! Mwalimu mzuri na mvumilivu. Nimeendelea haraka sana shukrani kwa ufundishaji wake.",
    "Grace a lui, j'ai passe ma ceinture noire en 4 ans. Un vrai professionnel qui sait motiver ses eleves.": "Shukrani kwake, nimepata ukanda mweusi wangu katika miaka 4. Mtaalamu wa kweli anayejua kuwamotisha wanafunzi wake.",
    "Les cours prives sont exceptionnels. Programme vraiment personnalise et resultats rapides.": "Kozi za faragha ni za kipekee. Programu iliyobinafsishwa kweli na matokeo ya haraka.",
    "Reservez votre cours d'essai gratuit ou demandez plus d'informations": "Hifadhi kozi yako ya majaribio ya bure au omba taarifa zaidi",
    "Je suis interesse par...": "Nina hamu ya...",
    "Fédération d'arts martiaux dédiée à la promotion, au développement et à l'excellence des pratiques martiales.": "Shirikisho la sanaa za kijeshi linalojishughulisha na ukuzaji, maendeleo na ubora wa mazoezi ya kijeshi.",
    "PROCHAINS ÉVÉNEMENTS": "MATUKIO YANAYOKUJA",
    "NOS DISCIPLINES": "TAALUMA ZETU",
    "NOS SERVICES": "HUDUMA ZETU",
    "Ce que nous offrons à nos membres et clubs affiliés": "Tunachotoa kwa wanachama wetu na klabu zilizoshirikishwa",
    "GALERIE": "MKUSANYIKO WA PICHA",
    "CONTACT": "WASILIANA",
    "Réglez vos cotisations en ligne de manière simple et sécurisée pour": "Lipa michango yako mtandaoni kwa njia rahisi na salama kwa",
    "Idéal pour les débutants qui souhaitent découvrir notre art martial": "Bora kwa wanaoanza wanaotaka kugundua sanaa yetu ya kijeshi",
    "Notre formule la plus populaire pour les pratiquants réguliers": "Mpango wetu maarufu zaidi kwa watendaji wa kawaida",
    "Notre équipe est disponible pour répondre à toutes vos questions concernant les cotisations, les paiements échelonnés ou toute autre demande.": "Timu yetu inapatikana kujibu maswali yako yote kuhusu michango, malipo ya awamu au ombi lingine lolote.",
    "Contact the club to finalize your registration or choose a payment method below.": "Wasiliana na klabu kukamilisha usajili wako au chagua njia ya malipo hapa chini.",
    "Credit card payment - You will be redirected to our secure payment platform.": "Malipo kwa kadi ya mkopo - Utaelekezwa kwenye jukwaa letu salama la malipo.",
    "Bank transfer - Banking details will be sent to you by email after registration.": "Uhamisho wa benki - Maelezo ya benki yatatumwa kwako kwa barua pepe baada ya usajili.",
    "Check - To be handed in at the club secretariat to the order indicated.": "Hundi - Itawasilishwa kwenye ofisi ya klabu kwa mpangilio ulioonyeshwa.",
    "Cash - To be handed in directly at the club secretariat.": "Pesa taslimu - Itawasilishwa moja kwa moja kwenye ofisi ya klabu.",
    "Retrouvez tous les équipements, tenues et accessoires officiels de": "Pata vifaa vyote, sare na vifaa rasmi vya",
}
