# -*- coding: utf-8 -*-
TRANSLATIONS = {
    "Organisation non trouvée": "Shirika halikupatikana",
    "Aucune organisation associée au club": "Hakuna shirika linalohusiana na klabu",
    "Aucun fichier fourni": "Hakuna faili iliyotolewa",
    "Type de fichier non autorisé": "Aina ya faili haikuruhusiwa",
    "Action non valide": "Kitendo batili",
    "Erreur lors de la mise à jour du logo: {}": "Hitilafu wakati wa kusasisha nembo: {}",
    "Le nom ne peut pas être vide": "Jina haliwezi kuwa tupu",
    "Nom du club mis à jour avec succès": "Jina la klabu limesasishwa kwa mafanikio",
    "Disciplines mises à jour avec succès": "Taaluma zimesasishwa kwa mafanikio",
    "Disciplines supprimées": "Taaluma zimefutwa",
    "Paramètres du club mis à jour avec succès": "Mipangilio ya klabu imesasishwa kwa mafanikio",
    "Erreur lors du chargement du dashboard. Retour à la version classique.": "Hitilafu wakati wa kupakia dashibodi. Inarudi kwenye toleo la kawaida.",
    "Passionné par les arts martiaux depuis plus de 15 ans, je propose des cours adaptés à tous les niveaux.": "Mwenye shauku ya sanaa za kijeshi kwa zaidi ya miaka 15, ninatoa kozi zilizobadilishwa kwa viwango vyote.",
    "Stage de perfectionnement technique pour les ceintures marron et noires. Focus sur les applications de combat et les subtilités techniques avancées.": "Semina ya kuboresha ufundi kwa mikanda ya kahawia na nyeusi. Kulenga matumizi ya mapigano na hila za ufundi za juu.",
    "Séminaire d'introduction aux techniques de self-défense pour tous niveaux. Ouvert au public, aucune expérience préalable requise.": "Semina ya utangulizi wa mbinu za kujilinda kwa viwango vyote. Imefunguliwa kwa umma, hakuna uzoefu wa awali unaohitajika.",
    "Un excellent coach avec une pédagogie adaptée à\xa0 chaque élève. Très attentif aux détails techniques et toujours disponible pour des explications supplémentaires.": "Kocha bora na ufundishaji uliobadilishwa kwa kila mwanafunzi. Makini sana na maelezo ya ufundi na daima anapatikana kwa maelezo ya ziada.",
    "Grâce à\xa0 son enseignement rigoureux mais bienveillant, j'ai pu progresser rapidement. Les cours sont variés et toujours intéressants.": "Shukrani kwa ufundishaji wake mkali lakini wa huruma, nimeweza kuendelea haraka. Kozi zinatofautiana na daima ni za kuvutia.",
    "\"Cette plateforme a transformé la gestion de mes élèves !\"": "\"Jukwaa hili limebadilisha usimamizi wa wanafunzi wangu!\"",
    "\"Simple, rapide et efficace pour organiser mes cours.\"": "\"Rahisi, haraka na bora kwa kupanga kozi zangu.\"",
    "Cliquez sur \"Ajouter un élève\" dans le menu Actions rapides.": "Bofya \"Ongeza mwanafunzi\" kwenye menyu ya Vitendo vya Haraka.",
    "Utilisez le bouton \"Nouvel entraînement\" sur le tableau de bord.": "Tumia kitufe cha \"Mazoezi mapya\" kwenye dashibodi.",
    "Vous n'avez pas accès au module Combat.": "Huna ufikiaji wa moduli ya Mapigano.",
    "Tarifs d'affiliation - %(season)s": "Bei za ushirika - %(season)s",
    "Demande de renouvellement approuvée. Une facture a été générée.": "Ombi la kuhuisha limeidhinishwa. Ankara imezalishwa.",
    "La personnalisation du thème sera disponible prochainement.": "Ubinafsishaji wa mandhari utapatikana hivi karibuni.",
    "Juge non trouvé.": "Hakimu hakupatikana.",
    "Invitation envoyee au club. En attente de leur approbation.": "Mwaliko umetumwa kwa klabu. Inasubiri idhini yao.",
    "Affiliation approuvee! Le club est maintenant affilie.": "Ushirika umeidhinishwa! Klabu sasa imeshirikishwa.",
    "Demande approuvee. En attente de l'approbation du club.": "Ombi limeidhinishwa. Inasubiri idhini ya klabu.",
    "Le club a ete desaffilie.": "Klabu imeondolewa ushirika.",
    "Fonctionnalité temporairement indisponible": "Kipengele hakipatikani kwa muda",
    "Gestion des certifications": "Usimamizi wa vyeti",
    "Vous n'avez pas les droits d'accès à cette fonctionnalité.": "Huna haki za kufikia kipengele hiki.",
    "Profil pratiquant non trouvé.": "Wasifu wa mtendaji haukupatikana.",
    "Photo de profil supprimée avec succès.": "Picha ya wasifu imefutwa kwa mafanikio.",
    "Format de fichier non autorisé. Utilisez JPG, PNG, GIF ou WebP.": "Muundo wa faili haukuruhusiwa. Tumia JPG, PNG, GIF au WebP.",
    "Photo de profil mise à jour avec succès.": "Picha ya wasifu imesasishwa kwa mafanikio.",
    "Aucune photo sélectionnée.": "Hakuna picha iliyochaguliwa.",
    "Une erreur est survenue lors de la mise à jour de la photo.": "Hitilafu imetokea wakati wa kusasisha picha.",
    "Votre profil juge n'est pas configuré comme juge technique.": "Wasifu wako wa hakimu haujasanidiwa kama hakimu wa ufundi.",
    "Votre profil juge n'est pas actif. Contactez votre fédération.": "Wasifu wako wa hakimu si hai. Wasiliana na shirikisho lako.",
    "Vous êtes maintenant en mode Juge Technique": "Sasa uko katika aina ya Hakimu wa Ufundi",
    "Vous n'avez pas de profil pratiquant": "Huna wasifu wa mtendaji",
    "Vous n'avez pas de profil juge/arbitre. Contactez votre fédération pour devenir juge.": "Huna wasifu wa hakimu/mwamuzi. Wasiliana na shirikisho lako kuwa hakimu.",
    "Vous êtes maintenant en mode Pratiquant": "Sasa uko katika aina ya Mtendaji",
    "Vous avez déjà un profil juge/arbitre": "Tayari una wasifu wa hakimu/mwamuzi",
    "Pour devenir juge/arbitre, veuillez contacter votre fédération ou votre club.": "Ili kuwa hakimu/mwamuzi, tafadhali wasiliana na shirikisho lako au klabu yako.",
    "Vous devez avoir un profil pratiquant pour postuler comme juge": "Lazima uwe na wasifu wa mtendaji kuomba kama hakimu",
    "Votre profil juge technique n'est pas actif.": "Wasifu wako wa hakimu wa ufundi si hai.",
    "Vous n'avez pas de profil juge.": "Huna wasifu wa hakimu.",
    "Vous n'avez pas accès à cette page.": "Huna ufikiaji wa ukurasa huu.",
    "Paramètres enregistrés avec succès.": "Mipangilio imehifadhiwa kwa mafanikio.",
    "Participant ajouté avec succès.": "Mshiriki ameongezwa kwa mafanikio.",
    "Erreur lors de l'ajout du participant: {}": "Hitilafu wakati wa kuongeza mshiriki: {}",
    "Une erreur s'est produite: {}": "Hitilafu imetokea: {}",
    "Le fichier doit être au format CSV.": "Faili lazima iwe katika muundo wa CSV.",
    "Ligne {}: {}": "Mstari {}: {}",
    "Erreurs rencontrées:": "Hitilafu zilizopatikana:",
    "Participant modifié avec succès.": "Mshiriki amerekebishwa kwa mafanikio.",
    "Erreur lors de la modification: {}": "Hitilafu wakati wa kurekebisha: {}",
    "Participant supprimé avec succès.": "Mshiriki amefutwa kwa mafanikio.",
    "Erreur lors de la suppression: {}": "Hitilafu wakati wa kufuta: {}",
    "Erreur lors de l'export: {}": "Hitilafu wakati wa kusafirisha: {}",
    "Le club {} a été affilié à votre fédération avec succès.": "Klabu {} imeshirikishwa na shirikisho lako kwa mafanikio.",
    "Erreur lors de l'affiliation du club.": "Hitilafu wakati wa kushirikisha klabu.",
    "Le club sélectionné n'existe pas.": "Klabu iliyochaguliwa haipo.",
    "Le club {} a été créé et affilié à votre fédération avec succès.": "Klabu {} imeundwa na kushirikishwa na shirikisho lako kwa mafanikio.",
    "Erreur lors de la création du club: {}": "Hitilafu wakati wa kuunda klabu: {}",
    "Erreur dans le champ {}: {}": "Hitilafu katika sehemu {}: {}",
    "Les informations du club {} ont été mises à jour.": "Taarifa za klabu {} zimesasishwa.",
    "Erreur lors de la mise à jour: {}": "Hitilafu wakati wa kusasisha: {}",
    "Vous n'avez pas les droits pour effectuer cette action.": "Huna haki za kufanya kitendo hiki.",
    "Cette formation ne peut pas être démarrée (statut: {}).": "Mafunzo haya hayawezi kuanzishwa (hali: {}).",
    "La formation '{}' a été démarrée avec succès.": "Mafunzo '{}' yameanzishwa kwa mafanikio.",
    "Cette formation ne peut pas être terminée (statut: {}).": "Mafunzo haya hayawezi kumalizika (hali: {}).",
    "La formation '{}' a été terminée avec succès.": "Mafunzo '{}' yamemalizika kwa mafanikio.",
    "Organisation créée automatiquement pour cette fédération.": "Shirika limeundwa kiotomatiki kwa shirikisho hili.",
    "Impossible de créer l'organisation pour cette fédération: {}": "Haiwezekani kuunda shirika kwa shirikisho hili: {}",
    "Erreur d'import du modèle Exam: {}": "Hitilafu ya kuagiza modeli ya Mtihani: {}",
    "Les examens ne sont pas encore disponibles. Erreur: {}": "Mitihani bado haipatikani. Hitilafu: {}",
    "Examens - {0}": "Mitihani - {0}",
    "Cette fédération n'a pas d'organisation associée.": "Shirikisho hili halina shirika linalohusiana.",
    "L'examen a été créé avec succès.": "Mtihani umeundwa kwa mafanikio.",
    "L'examen a été mis à jour avec succès.": "Mtihani umesasishwa kwa mafanikio.",
    "L'examen a été supprimé avec succès.": "Mtihani umefutwa kwa mafanikio.",
    "Le juge a été retiré de la compétition ({} assignation(s) supprimée(s)).": "Hakimu ameondolewa kutoka mashindano (ugawaji {} umefutwa).",
    "Aucune assignation trouvée pour ce juge dans cette compétition.": "Hakuna ugawaji uliopatikana kwa hakimu huyu katika mashindano haya.",
    "Erreur lors du retrait du juge: {}": "Hitilafu wakati wa kuondoa hakimu: {}",
    "Le juge {} a été invité avec succès à la compétition.": "Hakimu {} amealikwa kwa mafanikio kwa mashindano.",
    "Erreur lors de l'invitation du juge: {}": "Hitilafu wakati wa kualika hakimu: {}",
    "Juge {} assigné à la catégorie {} comme {}.": "Hakimu {} amegawiwa kwa kategoria {} kama {}.",
    "Erreur lors de l'assignation du juge: {}": "Hitilafu wakati wa kugawa hakimu: {}",
    "Le juge {} a été retiré de la catégorie {}.": "Hakimu {} ameondolewa kutoka kategoria {}.",
    "Erreur lors du retrait de l'assignation: {}": "Hitilafu wakati wa kuondoa ugawaji: {}",
    "Erreur lors de la récupération des catégories: {}": "Hitilafu wakati wa kupata kategoria: {}",
    "Erreur lors de la récupération des types de compétition: {}": "Hitilafu wakati wa kupata aina za mashindano: {}",
    "Aucune compétition en cours à gérer.": "Hakuna mashindano yanayoendelea ya kusimamia.",
    "Votre club a été créé avec succès.": "Klabu yako imeundwa kwa mafanikio.",
    "Erreur lors de la création du club.": "Hitilafu wakati wa kuunda klabu.",
    "Erreur lors de la création du club. Veuillez réessayer ou contacter le support.": "Hitilafu wakati wa kuunda klabu. Tafadhali jaribu tena au wasiliana na msaada.",
    "Une erreur technique critique est survenue. Notre équipe a été notifiée automatiquement.": "Hitilafu muhimu ya kiufundi imetokea. Timu yetu imearifiwa kiotomatiki.",
    "Votre fédération a été créée avec succès.": "Shirikisho lako limeundwa kwa mafanikio.",
    "Erreur lors de la création. Veuillez réessayer.": "Hitilafu wakati wa kuunda. Tafadhali jaribu tena.",
    "Erreur technique. Notre équipe a été notifiée.": "Hitilafu ya kiufundi. Timu yetu imearifiwa.",
    "Bienvenue sur MartialComp! Votre inscription est complète.": "Karibu MartialComp! Usajili wako umekamilika.",
    "Vous avez déjà une fédération. Configuration terminée.": "Tayari una shirikisho. Usanidi umekamilika.",
    "Rôle sélectionné avec succès": "Jukumu limechaguliwa kwa mafanikio",
    "Rôle invalide sélectionné": "Jukumu batili limechaguliwa",
    "Je participe aux compétitions": "Ninashiriki mashindano",
    "Gestionnaire de club": "Msimamizi wa klabu",
    "Je gère un club": "Ninasimamia klabu",
    "Je juge les compétitions": "Ninaamua mashindano",
    "J'entraîne des pratiquants": "Ninafundisha watendaji",
    "Administrateur fédération": "Msimamizi wa shirikisho",
    "Je gère une fédération": "Ninasimamia shirikisho",
    "Organisateur externe": "Mwandaaji wa nje",
    "J'organise des événements": "Ninaandaa matukio",
    "Je regarde les compétitions": "Ninatazama mashindano",
    "Une erreur est survenue lors de la sélection du rôle": "Hitilafu imetokea wakati wa kuchagua jukumu",
    "Rôle sélectionné avec succès.": "Jukumu limechaguliwa kwa mafanikio.",
    "Rôle invalide sélectionné.": "Jukumu batili limechaguliwa.",
    "J\u2019entraîne des pratiquants": "Ninafundisha watendaji",
    "J\u2019organise des événements": "Ninaandaa matukio",
    "Une erreur est survenue lors de la sélection du rôle.": "Hitilafu imetokea wakati wa kuchagua jukumu.",
    "Votre organisation n'est pas associée à un club. Contactez l'administrateur.": "Shirika lako halihusishwi na klabu. Wasiliana na msimamizi.",
    "Cette compétition n'est pas accessible publiquement.": "Mashindano haya hayapatikani hadharani.",
    "Accès refusé: Vous devez être administrateur du club '{}' pour scanner des QR codes. Contactez le propriétaire du club ({}) pour obtenir les permissions.": "Ufikiaji umekataliwa: Lazima uwe msimamizi wa klabu '{}' ili kuchanganua QR code. Wasiliana na mmiliki wa klabu ({}) kupata ruhusa.",
    "Vous n'avez pas les permissions pour voir ce QR code.": "Huna ruhusa za kuona QR code hii.",
    "Erreur technique lors de la génération du QR code. Veuillez contacter l'administrateur.": "Hitilafu ya kiufundi wakati wa kuzalisha QR code. Tafadhali wasiliana na msimamizi.",
    "Données invalides": "Data batili",
    "You are not assigned to judge this competition.": "Hukugawiwa kuamua mashindano haya.",
    "Définir les critères de notation par catégorie": "Fafanua vigezo vya alama kwa kategoria",
    "Assigner les juges aux catégories": "Gawa waamuzi kwa kategoria",
    "Gestion des performances": "Usimamizi wa utendaji",
    "Organiser et suivre les performances": "Andaa na ufuatilie utendaji",
    "Monitor des performances en cours": "Fuatilia utendaji unaoendelea",
    "Consulter les résultats par catégorie": "Angalia matokeo kwa kategoria",
    "Scores enregistrés avec succès.": "Alama zimehifadhiwa kwa mafanikio.",
    "ID de compétition requis.": "Kitambulisho cha mashindano kinahitajika.",
    "Critères par défaut générés (simulation).": "Vigezo vya kawaida vimezalishwa (uigaji).",
    "Critère ajouté (simulation).": "Kigezo kimeongezwa (uigaji).",
    "Configuration mise à jour (simulation).": "Usanidi umesasishwa (uigaji).",
    "Juge assigné (simulation).": "Hakimu amegawiwa (uigaji).",
    "Juge retiré (simulation).": "Hakimu ameondolewa (uigaji).",
    "Aucune catégorie trouvée pour cette compétition. Veuillez créer des catégories d'abord.": "Hakuna kategoria iliyopatikana kwa mashindano haya. Tafadhali unda kategoria kwanza.",
    "Performance ajoutée (simulation).": "Utendaji umeongezwa (uigaji).",
    "Performance supprimée (simulation).": "Utendaji umefutwa (uigaji).",
    "Performance démarrée (simulation).": "Utendaji umeanzishwa (uigaji).",
    "Vous devez être un juge pour accéder à cette interface.": "Lazima uwe hakimu kufikia kiolesura hiki.",
    "%(count)d performance(s) ont été automatiquement créées pour cette catégorie.": "Utendaji %(count)d umeundwa kiotomatiki kwa kategoria hii.",
    "Juge non trouvé": "Hakimu hakupatikana",
    "Tous les passages doivent être notés avant de verrouiller.": "Vipindi vyote lazima vipate alama kabla ya kufunga.",
    "Vos notations ont été verrouillées avec succès.": "Alama zako zimefungwa kwa mafanikio.",
    "Score invalide pour le critère {}": "Alama batili kwa kigezo {}",
    "Scores enregistrés avec succès": "Alama zimehifadhiwa kwa mafanikio",
    "Méthode non autorisée. Utilisez POST.": "Njia isiyoruhusiwa. Tumia POST.",
    "Vous devez être un juge pour enregistrer des scores.": "Lazima uwe hakimu ili kuhifadhi alama.",
    "ID de performance requis.": "Kitambulisho cha utendaji kinahitajika.",
    "ID de critère requis.": "Kitambulisho cha kigezo kinahitajika.",
    "Score requis.": "Alama inahitajika.",
    "Score invalide. Doit être un nombre.": "Alama batili. Lazima iwe nambari.",
    "Le score doit être entre 0 et 10.": "Alama lazima iwe kati ya 0 na 10.",
    "Le score doit être un multiple de 0.25.": "Alama lazima iwe kizidisho cha 0.25.",
    "Performance non trouvée.": "Utendaji haukupatikana.",
    "Critère de notation non trouvé ou inactif.": "Kigezo cha alama hakikupatikana au hakipo hai.",
    "Le score doit être entre {} et {} pour ce critère.": "Alama lazima iwe kati ya {} na {} kwa kigezo hiki.",
    "Score enregistré avec succès.": "Alama imehifadhiwa kwa mafanikio.",
    "Données JSON invalides.": "Data ya JSON batili.",
    "Critère non trouvé.": "Kigezo hakikupatikana.",
    "Vous devez confirmer avoir vérifié toutes vos notes.": "Lazima uthibitishe kuwa umeangalia alama zako zote.",
    "Vos notes sont déjà verrouillées pour ce round.": "Alama zako tayari zimefungwa kwa raundi hii.",
    "Vous devez noter tous les pratiquants avant de verrouiller.": "Lazima uwape alama watendaji wote kabla ya kufunga.",
    "Vos notes ont été verrouillées avec succès.": "Alama zako zimefungwa kwa mafanikio.",
    "Vos notes sont verrouillées.": "Alama zako zimefungwa.",
    "Vous n'avez pas les permissions pour cette action.": "Huna ruhusa za kitendo hiki.",
    "Confirmation requise. Envoyez confirmed=true.": "Uthibitisho unahitajika. Tuma confirmed=true.",
    "Seuls les administrateurs peuvent réinitialiser tous les scores.": "Wasimamizi peke yao wanaweza kuweka upya alama zote.",
    "Onboarding réinitialisé. Vous allez être redirigé.": "Mwanzo umewekwa upya. Utaelekezwa.",
    "Image du grade": "Picha ya daraja",
    "Téléchargez une image pour représenter ce grade (PNG, JPG, SVG - max 500KB, recommandé 100x100px)": "Pakia picha ya kuwakilisha daraja hili (PNG, JPG, SVG - upeo 500KB, inapendekezwa 100x100px)",
    "La taille de l'image ne doit pas dépasser 500 KB.": "Ukubwa wa picha hauwezi kuzidi KB 500.",
    "Image du grade (PNG, JPG, SVG, WebP - max 500KB, recommandé 100x100px)": "Picha ya daraja (PNG, JPG, SVG, WebP - upeo 500KB, inapendekezwa 100x100px)",
    "Icône Font Awesome": "Ikoni ya Font Awesome",
    "Classe Font Awesome optionnelle (ex: fa-medal, fa-award)": "Darasa la Font Awesome hiari (mfano: fa-medal, fa-award)",
    "\n                                            %(count)s pratiquants suivent cette discipline.\n                                            ": "\n                                            Watendaji %(count)s wanafuata taaluma hii.\n                                            ",
    "Vovinam": "Vovinam",
    "✅ Classe GradeFilter chargée": "Darasa la GradeFilter limepakiwa",
    "✅ Instance GradeFilter créée": "Mfano wa GradeFilter umeundwa",
    "❌ Erreur création GradeFilter: ' + error.message + '": "Hitilafu ya kuunda GradeFilter: ' + error.message + '",
    "DIPLÔME D'EXCELLENCE": "CHETI CHA UBORA",
    "à {}": "kwa {}",
    "Cet examen ne peut pas être supprimé car il a des inscriptions. Veuillez annuler l'examen plutôt que de le supprimer.": "Mtihani huu hauwezi kufutwa kwa sababu una usajili. Tafadhali ghairi mtihani badala ya kuufuta.",
    "\n                                Vous avez %(count)s paiement(s) en attente qui nécessite(nt) votre attention.\n                                ": "\n                                Una malipo %(count)s yanayosubiri yanayohitaji umakini wako.\n                                ",
    "Date de creation": "Tarehe ya kuundwa",
    "Derniere MAJ": "Sasisho la mwisho",
    "Payeur": "Mlipaji",
    "Reference": "Rejea",
    "Methode": "Njia",
    "Date completion": "Tarehe ya kukamilika",
    "Utilisations": "Matumizi",
    "Date facture": "Tarehe ya ankara",
    "Echeance": "Tarehe ya mwisho",
    "Nb produits": "Idadi ya bidhaa",
    "Details stock": "Maelezo ya hisa",
    "Nb articles": "Idadi ya vitu",
    "Date commande": "Tarehe ya oda",
    "Detail articles": "Maelezo ya vitu",
    "Administration MartialComp": "Utawala wa MartialComp",
    "Admin MartialComp": "Msimamizi wa MartialComp",
    "Gestion Complete": "Usimamizi Kamili",
    "Paiement à réception de facture.\nTout retard de paiement entraînera des pénalités de 3% du montant total.\nMerci de votre confiance.": "Malipo wakati wa kupokea ankara.\nKuchelewa kwa malipo yoyote kutasababisha adhabu ya 3% ya jumla.\nAsante kwa imani yako.",
    "Paiement dû sous 30 jours à compter de la date d'émission. Pénalités de retard applicables selon les conditions générales.": "Malipo yanadaiwa ndani ya siku 30 kutoka tarehe ya kutolewa. Adhabu za kuchelewa zinatumika kulingana na masharti ya jumla.",
    "Traitement en cours": "Usindikaji unaendelea",
    "Terminé avec erreurs": "Imemalizika na hitilafu",
    "Importé par": "Imeagizwa na",
    "Format du fichier": "Muundo wa faili",
    "Format bancaire": "Muundo wa benki",
    "Fichier original": "Faili ya asili",
    "Total transactions": "Jumla ya miamala",
    "Importées": "Zilizoagizwa",
    "Doublons": "Nakala rudufu",
    "Total revenus": "Jumla ya mapato",
    "Total dépenses": "Jumla ya matumizi",
    "Journal des erreurs": "Kumbukumbu ya hitilafu",
    "Date d'import": "Tarehe ya kuagiza",
    "Lot d'import bancaire": "Kundi la kuagiza benki",
    "Lots d'import bancaires": "Makundi ya kuagiza benki",
    "Rapproché": "Imepatanishwa",
    "Partiellement rapproché": "Imepatanishwa kwa sehemu",
    "Non rapproché": "Haijapatanishwa",
    "Doublon": "Nakala rudufu",
    "Virement instantané": "Uhamisho wa papo hapo",
    "Paiement par carte": "Malipo kwa kadi",
    "Paiement par carte de crédit": "Malipo kwa kadi ya mkopo",
    "Lot d'import": "Kundi la kuagiza",
    "Date d'exécution": "Tarehe ya utekelezaji",
    "Date valeur": "Tarehe ya thamani",
    "Méthode de paiement (brut)": "Njia ya malipo (ghafi)",
    "IBAN contrepartie": "IBAN ya mhusika",
    "Nom contrepartie": "Jina la mhusika",
    "Communication": "Mawasiliano",
    "Détails bruts": "Maelezo ghafi",
    "Statut bancaire": "Hali ya benki",
    "Statut réconciliation": "Hali ya upatanisho",
    "Score de confiance (%)": "Alama ya uhakika (%)",
    "Notes de réconciliation": "Maelezo ya upatanisho",
    "Réconcilié le": "Imepatanishwa tarehe",
    "Réconcilié par": "Imepatanishwa na",
    "Transaction système": "Muamala wa mfumo",
    "Pratiquant identifié": "Mtendaji aliyetambuliwa",
    "Transaction bancaire": "Muamala wa benki",
    "Transactions bancaires": "Miamala ya benki",
    "Contient": "Ina",
    "Correspondance exacte": "Mechi kamili",
    "Commence par": "Inaanza na",
    "Finit par": "Inaishia na",
    "Expression régulière": "Usemi wa kawaida",
    "Plage de montant": "Kiwango cha kiasi",
    "Montant exact": "Kiasi halisi",
    "Assigner catégorie": "Gawa kategoria",
    "Assigner pratiquant": "Gawa mtendaji",
    "Ignorer": "Puuza",
    "Marquer pour révision": "Weka alama kwa ukaguzi",
    "Nom de la règle": "Jina la kanuni",
    "ID Organisation": "Kitambulisho cha Shirika",
    "Champ à matcher": "Sehemu ya kulinganisha",
    "Valeur à chercher": "Thamani ya kutafuta",
    "Catégorie à assigner": "Kategoria ya kugawa",
    "Pratiquant à assigner": "Mtendaji wa kugawa",
    "Fois appliquée": "Mara iliyotumika",
    "Dernière application": "Matumizi ya mwisho",
    "Règle de réconciliation": "Kanuni ya upatanisho",
    "Règles de réconciliation": "Kanuni za upatanisho",
    "Titulaire du compte": "Mmiliki wa akaunti",
    "Variantes de nom": "Lahaja za jina",
    "Liste des noms alternatifs pour le matching": "Orodha ya majina mbadala kwa kulinganisha",
    "Compte principal": "Akaunti kuu",
    "Info bancaire pratiquant": "Taarifa za benki za mtendaji",
    "Infos bancaires pratiquants": "Taarifa za benki za watendaji",
    "¼ point (Phân Tu Điểm)": "Pointi ¼ (Phân Tu Điểm)",
    "½ point (Nửa Điểm)": "Pointi ½ (Nửa Điểm)",
    "1 point (Một Điểm)": "Pointi 1 (Một Điểm)",
    "1.5 points (Một Điểm Dưới)": "Pointi 1.5 (Một Điểm Dưới)",
    "2 points (Hai Điểm)": "Pointi 2 (Hai Điểm)",
    "Cảnh Cáo (Avertissement verbal)": "Cảnh Cáo (Onyo la mdomo)",
    "Kém Điểm (Retrait de ½ point)": "Kém Điểm (Kuondoa pointi ½)",
    "Phạt (Retrait de 1 point)": "Phạt (Kuondoa pointi 1)",
    "Phạt Hai (Retrait de 1 point + Disqualification)": "Phạt Hai (Kuondoa pointi 1 + Kufukuzwa)",
    "Loại (Disqualification immédiate)": "Loại (Kufukuzwa mara moja)",
    "Émetteur": "Mtumaji",
    "Type du bénéficiaire": "Aina ya mnufaika",
    "ID du bénéficiaire": "Kitambulisho cha mnufaika",
    "Europe de l'Ouest/Amérique du Nord/Océanie": "Ulaya ya Magharibi/Amerika Kaskazini/Oceania",
    "Solde négatif: %(amount).2f %(currency)s à payer": "Salio hasi: %(amount).2f %(currency)s ya kulipa",
    "\n                                Attention : Ce compte contient %(count)s transaction(s). Que souhaitez-vous faire de ces transactions ?\n                                ": "\n                                Tahadhari: Akaunti hii ina miamala %(count)s. Ungependa kufanya nini na miamala hii?\n                                ",
    "Ex: Crédit Agricole": "Mfano: Crédit Agricole",
    "Import Bancaire": "Uagizaji wa Benki",
    "Nouvel Import": "Uagizaji Mpya",
    "Importez et réconciliez vos relevés bancaires": "Agiza na upatanishe taarifa zako za benki",
    "Transactions importées": "Miamala iliyoagizwa",
    "En attente de réconciliation": "Inasubiri upatanisho",
    "Transactions réconciliées": "Miamala iliyopatanishwa",
    "Imports effectués": "Uagizaji uliofanywa",
    "Importer un relevé bancaire": "Agiza taarifa ya benki",
    "Réconcilier": "Patanisha",
    "Historique des imports": "Historia ya uagizaji",
    "Formats supportés": "Muundo unaosaidiwa",
    "doublons": "nakala rudufu",
    "Avec erreurs": "Na hitilafu",
    "Aucun import effectué": "Hakuna uagizaji uliofanywa",
    "Effectuer un premier import": "Fanya uagizaji wa kwanza",
    "Détail de l'import": "Maelezo ya uagizaji",
    "Importé le": "Imeagizwa tarehe",
    "Réconciliées": "Zimepatanishwa",
    "Réconcilié": "Imepatanishwa",
    "Contrepartie": "Mhusika",
    "Aucune transaction ne correspond aux filtres.": "Hakuna muamala unaolingana na vichujio.",
    "Historique des imports bancaires": "Historia ya uagizaji wa benki",
    "Consultez tous vos imports de relevés bancaires": "Angalia uagizaji wako wote wa taarifa za benki",
    "Tous les comptes": "Akaunti zote",
    "Aucun import trouvé": "Hakuna uagizaji uliopatikana",
    "Commencez par importer un relevé bancaire.": "Anza kwa kuagiza taarifa ya benki.",
    "Prévisualisation Import": "Onyesho la Awali la Uagizaji",
    "Prévisualisation de l'import": "Onyesho la awali la uagizaji",
    "Vérifiez les données avant de confirmer l'import": "Angalia data kabla ya kuthibitisha uagizaji",
    "Format détecté": "Muundo uliogunduliwa",
    "Compte cible": "Akaunti lengwa",
    "Total Revenus": "Jumla ya Mapato",
    "Total Dépenses": "Jumla ya Matumizi",
    "Aperçu des transactions": "Muhtasari wa miamala",
    "50 premières affichées": "50 za kwanza zinaonyeshwa",
    "Ref": "Rejea",
    "Confirmer l'import": "Thibitisha uagizaji",
    "Sélectionnez un fichier CSV ou Excel de votre banque": "Chagua faili ya CSV au Excel kutoka benki yako",
    "Compte bancaire cible": "Akaunti ya benki lengwa",
    "Détection automatique": "Ugunduzi wa kiotomatiki",
    "Laissez vide pour une détection automatique du format": "Acha tupu kwa ugunduzi wa kiotomatiki wa muundo",
    "Parcourir...": "Vinjari...",
    "Comment exporter votre relevé?": "Jinsi ya kusafirisha taarifa yako ya benki?",
    "Autres banques": "Benki nyingine",
    "Consultez la documentation de votre banque pour exporter vos transactions au format CSV.": "Angalia nyaraka za benki yako ili kusafirisha miamala yako kwa muundo wa CSV.",
    "Le système détecte automatiquement le format dans la plupart des cas.": "Mfumo unagundua kiotomatiki muundo katika hali nyingi.",
    "Pour une meilleure réconciliation automatique, assurez-vous que les communications structurées contiennent les noms des pratiquants.": "Kwa upatanisho bora wa kiotomatiki, hakikisha mawasiliano yaliyopangwa yana majina ya watendaji.",
    "Tableau de Bord Rapprochement": "Dashibodi ya Upatanisho",
    "Rapprochement Bancaire": "Upatanisho wa Benki",
    "Suivi et analyse du rapprochement des transactions": "Ufuatiliaji na uchambuzi wa upatanisho wa miamala",
    "Tout": "Yote",
    "Compte:": "Akaunti:",
    "Rapprochées": "Zimepatanishwa",
    "Auto-rapprochées": "Zimepatanishwa kiotomatiki",
    "Manuelles": "Za mkono",
    "Non rapprochées": "Hazijapatanishwa",
    "Taux de rapprochement": "Kiwango cha upatanisho",
    "des transactions rapprochées": "ya miamala iliyopatanishwa",
    "Montants rapprochés": "Kiasi kilichopatanishwa",
    "Entrées": "Mapato",
    "Montants en attente": "Kiasi kinachosubiri",
    "Entrées en attente": "Mapato yanayosubiri",
    "Sorties en attente": "Matumizi yanayosubiri",
    "Total en attente": "Jumla inayosubiri",
    "Traiter ces transactions": "Shughulikia miamala hii",
    "Evolution du rapprochement": "Mabadiliko ya upatanisho",
    "Par méthode de paiement": "Kwa njia ya malipo",
    "Top contreparties non rapprochées": "Wahusika wakuu wasiopatanishwa",
    "Toutes les transactions sont rapprochées": "Miamala yote imepatanishwa",
    "Transactions récentes non rapprochées": "Miamala ya hivi karibuni isiyopatanishwa",
    "Toutes les transactions sont rapprochées!": "Miamala yote imepatanishwa!",
    "Transactions rapprochées": "Miamala iliyopatanishwa",
    "Transactions à réconcilier": "Miamala ya kupatanisha",
    "Associez les transactions bancaires aux pratiquants": "Husisha miamala ya benki na watendaji",
    "Valider toutes les transactions en attente et les créer dans le système?": "Thibitisha miamala yote inayosubiri na kuiunda katika mfumo?",
    "Tout valider": "Thibitisha yote",
    "Réconciliation auto": "Upatanisho wa kiotomatiki",
    "Revenus à réconcilier": "Mapato ya kupatanisha",
    "Dépenses à réconcilier": "Matumizi ya kupatanisha",
    "Nom, communication...": "Jina, mawasiliano...",
    "Aucune transaction en attente!": "Hakuna muamala unaosubiri!",
    "Toutes les transactions ont été réconciliées.": "Miamala yote imepatanishwa.",
    "Réconcilier transaction": "Patanisha muamala",
    "Réconcilier une transaction": "Patanisha muamala",
    "Associez cette transaction bancaire à un pratiquant ou une catégorie": "Husisha muamala huu wa benki na mtendaji au kategoria",
    "Suggestions automatiques": "Mapendekezo ya kiotomatiki",
    "Associer à un pratiquant": "Husisha na mtendaji",
    "Rechercher un pratiquant": "Tafuta mtendaji",
    "Associer ce pratiquant": "Husisha mtendaji huyu",
    "Assigner une catégorie": "Gawa kategoria",
    "Assigner cette catégorie": "Gawa kategoria hii",
    "Ignorer cette transaction": "Puuza muamala huu",
    "Si cette transaction n'est pas pertinente pour la comptabilité du club, vous pouvez l'ignorer.": "Ikiwa muamala huu sio muhimu kwa uhasibu wa klabu, unaweza kuupuuza.",
    "Raison (optionnel)": "Sababu (hiari)",
    "Ex: Frais bancaires, virement personnel...": "Mfano: Ada za benki, uhamisho wa kibinafsi...",
    "Toutes les transactions": "Miamala yote",
    "Votre profil utilisateur n'a pas de rôle défini. Veuillez compléter votre onboarding ou contacter un administrateur.": "Wasifu wako wa mtumiaji hauna jukumu lililofafanuliwa. Tafadhali kamilisha mwanzo wako au wasiliana na msimamizi.",
    "La date d\\'": "Tarehe ya\\'",
    "\n            %(count)s factures trouvées\n            ": "\n            Ankara %(count)s zimepatikana\n            ",
    "Âge moyen (impayées)": "Umri wa wastani (ambazo hazijalipwa)",
    "\n            %(count)s transactions trouvées\n            ": "\n            Miamala %(count)s imepatikana\n            ",
    "Veuillez sélectionner un fichier.": "Tafadhali chagua faili.",
    "Veuillez sélectionner un compte bancaire.": "Tafadhali chagua akaunti ya benki.",
    "Erreur lors de l'analyse du fichier: {}": "Hitilafu wakati wa kuchambua faili: {}",
    "Aucun import en attente de confirmation.": "Hakuna uagizaji unaosubiri uthibitisho.",
    "Session expirée. Veuillez recommencer l'import.": "Kipindi kimeisha. Tafadhali anza upya uagizaji.",
    "Import réussi! {} transactions importées, {} doublons ignorés.": "Uagizaji umefanikiwa! Miamala {} imeagizwa, nakala rudufu {} zimepuuzwa.",
    "{} erreurs lors de l'import.": "Hitilafu {} wakati wa kuagiza.",
    "Erreur lors de l'import: {}": "Hitilafu wakati wa kuagiza: {}",
    "Transaction réconciliée et créée dans le système.": "Muamala umepatanishwa na kuundwa katika mfumo.",
    "Transaction créée et catégorie assignée.": "Muamala umeundwa na kategoria imegawiwa.",
    "Transaction ignorée.": "Muamala umepuuzwa.",
    "Utilisez le bouton 'Réconciliation auto' pour lancer le processus.": "Tumia kitufe cha 'Upatanisho wa kiotomatiki' kuanza mchakato.",
    "{matched} transactions réconciliées, {created} transactions créées dans le système.": "Miamala {matched} imepatanishwa, miamala {created} imeundwa katika mfumo.",
    "{created} transactions créées, {errors} erreurs.": "Miamala {created} imeundwa, hitilafu {errors}.",
    "{created} transactions créées dans le système.": "Miamala {created} imeundwa katika mfumo.",
    "Le module reportlab n'est pas installé. Export PDF non disponible.": "Moduli ya reportlab haijasakinishwa. Usafirishaji wa PDF haupatikani.",
    "Toutes les données": "Data yote",
    "Rapport de Rapprochement Bancaire": "Ripoti ya Upatanisho wa Benki",
    "Indicateur": "Kiashiria",
    "Détail des Montants": "Maelezo ya Kiasi",
    "Entrées (EUR)": "Mapato (EUR)",
    "Sorties (EUR)": "Matumizi (EUR)",
    "Solde (EUR)": "Salio (EUR)",
    "Transactions non rapprochées (Top 20)": "Miamala isiyopatanishwa (20 ya juu)",
    "Rapport généré automatiquement": "Ripoti imezalishwa kiotomatiki",
    "Pour créer des factures, vous devez avoir l'un des rôles suivants : Responsable de fédération, Responsable de club, Coach, ou Manager. Contactez votre administrateur pour obtenir les permissions appropriées.": "Ili kuunda ankara, lazima uwe na moja ya majukumu yafuatayo: Msimamizi wa shirikisho, Msimamizi wa klabu, Kocha, au Meneja. Wasiliana na msimamizi wako kupata ruhusa zinazofaa.",
    "Pour modifier des factures, vous devez avoir l'un des rôles suivants : Responsable de fédération, Responsable de club, Coach, ou Manager. Contactez votre administrateur pour obtenir les permissions appropriées.": "Ili kurekebisha ankara, lazima uwe na moja ya majukumu yafuatayo: Msimamizi wa shirikisho, Msimamizi wa klabu, Kocha, au Meneja. Wasiliana na msimamizi wako kupata ruhusa zinazofaa.",
    "Pour supprimer des factures, vous devez avoir l'un des rôles suivants : Responsable de fédération, Responsable de club, Coach, ou Manager. Contactez votre administrateur pour obtenir les permissions appropriées.": "Ili kufuta ankara, lazima uwe na moja ya majukumu yafuatayo: Msimamizi wa shirikisho, Msimamizi wa klabu, Kocha, au Meneja. Wasiliana na msimamizi wako kupata ruhusa zinazofaa.",
    "Aucune adresse e-mail destinataire disponible.": "Hakuna anwani ya barua pepe ya mpokeaji inayopatikana.",
    "Facture %(number)s": "Ankara %(number)s",
    "La facture a été envoyée par e-mail à %(email)s.": "Ankara imetumwa kwa barua pepe kwa %(email)s.",
    "Erreur lors de l'envoi de l'e-mail: %(error)s": "Hitilafu wakati wa kutuma barua pepe: %(error)s",
    "Pour créer des méthodes de paiement, vous devez avoir l'un des rôles suivants : Responsable de fédération, Responsable de club, Coach, ou Manager. Contactez votre administrateur pour obtenir les permissions appropriées.": "Ili kuunda njia za malipo, lazima uwe na moja ya majukumu yafuatayo: Msimamizi wa shirikisho, Msimamizi wa klabu, Kocha, au Meneja. Wasiliana na msimamizi wako kupata ruhusa zinazofaa.",
    "Pour modifier des méthodes de paiement, vous devez avoir l'un des rôles suivants : Responsable de fédération, Responsable de club, Coach, ou Manager. Contactez votre administrateur pour obtenir les permissions appropriées.": "Ili kurekebisha njia za malipo, lazima uwe na moja ya majukumu yafuatayo: Msimamizi wa shirikisho, Msimamizi wa klabu, Kocha, au Meneja. Wasiliana na msimamizi wako kupata ruhusa zinazofaa.",
    "Pour supprimer des méthodes de paiement, vous devez avoir l'un des rôles suivants : Responsable de fédération, Responsable de club, Coach, ou Manager. Contactez votre administrateur pour obtenir les permissions appropriées.": "Ili kufuta njia za malipo, lazima uwe na moja ya majukumu yafuatayo: Msimamizi wa shirikisho, Msimamizi wa klabu, Kocha, au Meneja. Wasiliana na msimamizi wako kupata ruhusa zinazofaa.",
    "Accès refusé à cette tentative de paiement.": "Ufikiaji umekataliwa kwa jaribio hili la malipo.",
    "Pour créer des transactions, vous devez avoir l'un des rôles suivants : Responsable de fédération, Responsable de club, Coach, ou Manager. Contactez votre administrateur pour obtenir les permissions appropriées.": "Ili kuunda miamala, lazima uwe na moja ya majukumu yafuatayo: Msimamizi wa shirikisho, Msimamizi wa klabu, Kocha, au Meneja. Wasiliana na msimamizi wako kupata ruhusa zinazofaa.",
    "Pour modifier des transactions, vous devez avoir l'un des rôles suivants : Responsable de fédération, Responsable de club, Coach, ou Manager. Contactez votre administrateur pour obtenir les permissions appropriées.": "Ili kurekebisha miamala, lazima uwe na moja ya majukumu yafuatayo: Msimamizi wa shirikisho, Msimamizi wa klabu, Kocha, au Meneja. Wasiliana na msimamizi wako kupata ruhusa zinazofaa.",
    "J-30 avant eligibilite": "Siku 30 kabla ya kustahiki",
    "J-7 avant eligibilite": "Siku 7 kabla ya kustahiki",
    "J-14 avant deadline examen": "Siku 14 kabla ya tarehe ya mwisho ya mtihani",
    "J-3 avant deadline examen": "Siku 3 kabla ya tarehe ya mwisho ya mtihani",
    "Jalon": "Hatua muhimu",
}
