#!/bin/bash
# Script de test pour l'API de génération de licence

echo "=========================================="
echo "TEST API GÉNÉRATION DE LICENCE"
echo "=========================================="
echo ""

# Configuration
BASE_URL="https://martialcomp.com"
API_ENDPOINT="/fr/competitions/api/generate-license-number/"

echo "1. Test de l'endpoint API:"
echo "   URL: ${BASE_URL}${API_ENDPOINT}"
echo ""
echo "2. Pour tester manuellement, utilisez:"
echo ""
echo "   curl -X POST ${BASE_URL}${API_ENDPOINT} \\"
echo "     -H 'Content-Type: application/json' \\"
echo "     -H 'X-CSRFToken: YOUR_CSRF_TOKEN' \\"
echo "     -H 'Cookie: csrftoken=YOUR_CSRF_TOKEN; sessionid=YOUR_SESSION_ID' \\"
echo "     -d '{"
echo "       \"birth_date\": \"2010-05-15\","
echo "       \"disciplines\": [\"Taekwondo\"],"
echo "       \"last_name\": \"Dupont\""
echo "     }'"
echo ""
echo "3. Vérifications à faire dans le navigateur:"
echo "   - Ouvrir la console (F12)"
echo "   - Aller sur: ${BASE_URL}/fr/competitions/club/practitioners/88/edit/"
echo "   - Remplir: date de naissance, discipline, nom"
echo "   - Cliquer sur 'Générer'"
echo "   - Vérifier les logs dans la console"
echo ""
echo "4. Vérifications du code JavaScript:"
echo "   - Le bouton doit se désactiver et afficher 'Génération...'"
echo "   - Les logs doivent apparaître dans la console"
echo "   - Le numéro de licence doit apparaître dans le champ"
echo ""
