#!/usr/bin/env python3
"""Batch translate short entries for KO, VI, NO, RU, YO, ZU."""
import polib, os, sys

# Multi-language translations: French -> {lang: translation}
# Start with the shortest/most common entries
MULTI = {
    "Gestion Pro": {"ko": "프로 관리", "vi": "Quản lý chuyên nghiệp", "no": "Profesjonell styring", "ru": "Управление Pro", "yo": "Ìṣàkóso Pro", "zu": "Ukuphatha Pro"},
    "Publier & Partager": {"ko": "게시 및 공유", "vi": "Đăng & Chia sẻ", "no": "Publiser & Del", "ru": "Опубликовать и поделиться", "yo": "Ṣàtẹ̀jáde & Pín", "zu": "Shicilela & Yabelana"},
    "Affectation rapide": {"ko": "빠른 배정", "vi": "Phân công nhanh", "no": "Rask tildeling", "ru": "Быстрое назначение", "yo": "Ìyànsípò kíákíá", "zu": "Ukwabiwa okusheshayo"},
    "Pratiquants non affectés": {"ko": "미배정 수련생", "vi": "Võ sinh chưa phân công", "no": "Ikke tildelte utøvere", "ru": "Неназначенные спортсмены", "yo": "Àwọn olùṣe tí a kò yàn sí", "zu": "Abazivocavocayo abangabelwanga"},
    "Aucun pratiquant non affecté": {"ko": "미배정 수련생 없음", "vi": "Không có võ sinh chưa phân công", "no": "Ingen utildelte utøvere", "ru": "Нет неназначенных спортсменов", "yo": "Kò sí olùṣe tí a kò yàn sí", "zu": "Akekho ozivocavocayo ongabelwanga"},
    "Juges non affectés": {"ko": "미배정 심판", "vi": "Trọng tài chưa phân công", "no": "Ikke tildelte dommere", "ru": "Неназначенные судьи", "yo": "Àwọn adájọ́ tí a kò yàn sí", "zu": "Abahluleli abangabelwanga"},
    "Envoyer notifications": {"ko": "알림 보내기", "vi": "Gửi thông báo", "no": "Send varsler", "ru": "Отправить уведомления", "yo": "Fi ìfitónilétí ránṣẹ́", "zu": "Thumela izaziso"},
    "Prochaines étapes": {"ko": "다음 단계", "vi": "Bước tiếp theo", "no": "Neste steg", "ru": "Следующие шаги", "yo": "Àwọn ìgbésẹ̀ tó ń bọ̀", "zu": "Izinyathelo ezilandelayo"},
    "Créer les catégories": {"ko": "카테고리 생성", "vi": "Tạo hạng mục", "no": "Opprett kategorier", "ru": "Создать категории", "yo": "Ṣẹ̀dá àwọn ẹ̀ka", "zu": "Dala izigaba"},
    "Enregistrer les participants": {"ko": "참가자 등록", "vi": "Đăng ký người tham gia", "no": "Registrer deltakere", "ru": "Зарегистрировать участников", "yo": "Forúkọ àwọn olùkópa sílẹ̀", "zu": "Bhalisa ababambi qhaza"},
    "Affecter les juges": {"ko": "심판 배정", "vi": "Phân công trọng tài", "no": "Tildel dommere", "ru": "Назначить судей", "yo": "Yàn àwọn adájọ́ sí", "zu": "Abela abahluleli"},
    "Ajouter un type": {"ko": "유형 추가", "vi": "Thêm loại", "no": "Legg til type", "ru": "Добавить тип", "yo": "Fi irú kan kún", "zu": "Engeza uhlobo"},
    "Glissez des catégories ici": {"ko": "여기에 카테고리를 드래그하세요", "vi": "Kéo thả hạng mục vào đây", "no": "Dra kategorier hit", "ru": "Перетащите категории сюда", "yo": "Fa àwọn ẹ̀ka sí ibí", "zu": "Hudulela izigaba lapha"},
    "Glissez des pratiquants ici": {"ko": "여기에 수련생을 드래그하세요", "vi": "Kéo thả võ sinh vào đây", "no": "Dra utøvere hit", "ru": "Перетащите спортсменов сюда", "yo": "Fa àwọn olùṣe sí ibí", "zu": "Hudulela abazivocavocayo lapha"},
    "Nom, club, licence...": {"ko": "이름, 도장, 면허...", "vi": "Tên, câu lạc bộ, giấy phép...", "no": "Navn, klubb, lisens...", "ru": "Имя, клуб, лицензия...", "yo": "Orúkọ, ẹgbẹ́, ìwé àṣẹ...", "zu": "Igama, ikhlabi, ilayisensi..."},
    "Non affecté": {"ko": "미배정", "vi": "Chưa phân công", "no": "Ikke tildelt", "ru": "Не назначен", "yo": "A kò yàn sí", "zu": "Akabelwanga"},
    "Ajouter un juge technique": {"ko": "기술 심판 추가", "vi": "Thêm trọng tài kỹ thuật", "no": "Legg til teknisk dommer", "ru": "Добавить технического судью", "yo": "Fi adájọ́ ọ̀nà kún", "zu": "Engeza umhluleli wezobuchwepheshe"},
    "Juges techniques disponibles": {"ko": "배정 가능한 기술 심판", "vi": "Trọng tài kỹ thuật sẵn sàng", "no": "Tilgjengelige tekniske dommere", "ru": "Доступные технические судьи", "yo": "Àwọn adájọ́ ọ̀nà tí ó wà", "zu": "Abahluleli bezobuchwepheshe abatholakalayo"},
    "Aucun juge technique disponible": {"ko": "배정 가능한 기술 심판 없음", "vi": "Không có trọng tài kỹ thuật", "no": "Ingen tekniske dommere tilgjengelig", "ru": "Нет доступных технических судей", "yo": "Kò sí adájọ́ ọ̀nà tí ó wà", "zu": "Akekho abahluleli bezobuchwepheshe abatholakalayo"},
    "Arbitres de Combat": {"ko": "대전 심판", "vi": "Trọng tài thi đấu", "no": "Kampdommere", "ru": "Судьи поединков", "yo": "Àwọn adájọ́ ìjà", "zu": "Abahluleli bempi"},
    "Ajouter un arbitre": {"ko": "심판 추가", "vi": "Thêm trọng tài", "no": "Legg til dommer", "ru": "Добавить судью", "yo": "Fi adájọ́ kan kún", "zu": "Engeza umhluleli"},
    "Arbitres disponibles": {"ko": "배정 가능한 심판", "vi": "Trọng tài sẵn sàng", "no": "Tilgjengelige dommere", "ru": "Доступные судьи", "yo": "Àwọn adájọ́ tí ó wà", "zu": "Abahluleli abatholakalayo"},
    "Aucun arbitre disponible": {"ko": "배정 가능한 심판 없음", "vi": "Không có trọng tài sẵn sàng", "no": "Ingen dommere tilgjengelig", "ru": "Нет доступных судей", "yo": "Kò sí adájọ́ tí ó wà", "zu": "Akekho abahluleli abatholakalayo"},
    "Affectations par tatami": {"ko": "다다미별 배정", "vi": "Phân công theo sàn đấu", "no": "Tildelinger per tatami", "ru": "Назначения по татами", "yo": "Ìyànsípò fún tatami", "zu": "Ukwabiwa nge-tatami"},
    "Arbitre Central": {"ko": "중앙 심판", "vi": "Trọng tài chính", "no": "Hoveddommer", "ru": "Главный судья", "yo": "Adájọ́ àárín", "zu": "Umhluleli omkhulu"},
    "Glisser 1 arbitre central": {"ko": "중앙 심판 1명 드래그", "vi": "Kéo 1 trọng tài chính", "no": "Dra 1 hoveddommer", "ru": "Перетащите 1 главного судью", "yo": "Fa adájọ́ àárín 1", "zu": "Hudulela umhluleli omkhulu o-1"},
    "Arbitres de Coin": {"ko": "코너 심판", "vi": "Trọng tài góc", "no": "Hjørnedommere", "ru": "Угловые судьи", "yo": "Àwọn adájọ́ igun", "zu": "Abahluleli basegumbini"},
    "Glisser 2-3 arbitres de coin": {"ko": "코너 심판 2-3명 드래그", "vi": "Kéo 2-3 trọng tài góc", "no": "Dra 2-3 hjørnedommere", "ru": "Перетащите 2-3 угловых судей", "yo": "Fa adájọ́ igun 2-3", "zu": "Hudulela abahluleli basegumbini aba-2-3"},
    "Arbitre de Table": {"ko": "테이블 심판", "vi": "Trọng tài bàn", "no": "Borddommer", "ru": "Судья за столом", "yo": "Adájọ́ tábìlì", "zu": "Umhluleli wasetafuleni"},
    "Glisser 1 arbitre de table": {"ko": "테이블 심판 1명 드래그", "vi": "Kéo 1 trọng tài bàn", "no": "Dra 1 borddommer", "ru": "Перетащите 1 судью за столом", "yo": "Fa adájọ́ tábìlì 1", "zu": "Hudulela umhluleli wasetafuleni o-1"},
    "Placator": {"ko": "플라카토르", "vi": "Placator", "no": "Placator", "ru": "Плакатор", "yo": "Placator", "zu": "I-Placator"},
    "Glisser 1 placator": {"ko": "플라카토르 1명 드래그", "vi": "Kéo 1 placator", "no": "Dra 1 placator", "ru": "Перетащите 1 плакатора", "yo": "Fa placator 1", "zu": "Hudulela i-placator e-1"},
    "Démarrer le suivi": {"ko": "추적 시작", "vi": "Bắt đầu theo dõi", "no": "Start sporing", "ru": "Начать отслеживание", "yo": "Bẹ̀rẹ̀ ìtọpinpin", "zu": "Qala ukulandelela"},
    "Planning de la journée": {"ko": "일정 계획", "vi": "Lịch trình trong ngày", "no": "Dagsplan", "ru": "План на день", "yo": "Ètò ọjọ́", "zu": "Uhlelo losuku"},
    "Accueil et pesée": {"ko": "접수 및 계체", "vi": "Đón tiếp và cân nặng", "no": "Mottak og veiing", "ru": "Регистрация и взвешивание", "yo": "Ìgbàbọ̀ àti ìwọ̀n", "zu": "Ukwamukela nokukalwa"},
    "Monter": {"ko": "위로", "vi": "Lên", "no": "Opp", "ru": "Вверх", "yo": "Gòkè", "zu": "Phezulu"},
    "Descendre": {"ko": "아래로", "vi": "Xuống", "no": "Ned", "ru": "Вниз", "yo": "Sọ̀kalẹ̀", "zu": "Phansi"},
    "Temps réel": {"ko": "실시간", "vi": "Thời gian thực", "no": "Sanntid", "ru": "В реальном времени", "yo": "Àkókò gidi", "zu": "Isikhathi sangempela"},
    "État des tatamis": {"ko": "다다미 상태", "vi": "Trạng thái sàn đấu", "no": "Tatami-status", "ru": "Состояние татами", "yo": "Ipò tatami", "zu": "Isimo se-tatami"},
    "Publication et partage": {"ko": "게시 및 공유", "vi": "Đăng và chia sẻ", "no": "Publisering og deling", "ru": "Публикация и обмен", "yo": "Àtẹ̀jáde àti pínpín", "zu": "Ukushicilela nokwabelana"},
    "État de publication": {"ko": "게시 상태", "vi": "Trạng thái đăng", "no": "Publiseringsstatus", "ru": "Статус публикации", "yo": "Ipò àtẹ̀jáde", "zu": "Isimo sokushicilela"},
    "Checklist avant publication": {"ko": "게시 전 체크리스트", "vi": "Danh sách kiểm tra trước khi đăng", "no": "Sjekkliste før publisering", "ru": "Чеклист перед публикацией", "yo": "Àtòjọ àyẹ̀wò ṣáájú àtẹ̀jáde", "zu": "Uhlu lokuhlola ngaphambi kokushicilela"},
    "Lieu défini": {"ko": "장소 지정됨", "vi": "Đã xác định địa điểm", "no": "Sted definert", "ru": "Место определено", "yo": "Ibi ti a tọ́kasí", "zu": "Indawo ichazwe"},
    "Au moins une catégorie créée": {"ko": "최소 1개 카테고리 생성됨", "vi": "Ít nhất một hạng mục đã tạo", "no": "Minst én kategori opprettet", "ru": "Создана хотя бы одна категория", "yo": "Ó kéré ẹ̀ka kan ti ṣẹ̀dá", "zu": "Okungenani isigaba esisodwa sidalwe"},
    "Informations complètes": {"ko": "정보 완료", "vi": "Thông tin đầy đủ", "no": "Fullstendig informasjon", "ru": "Информация заполнена", "yo": "Àlàyé pípe", "zu": "Ulwazi oluphelele"},
    "Publier maintenant": {"ko": "지금 게시", "vi": "Đăng ngay", "no": "Publiser nå", "ru": "Опубликовать сейчас", "yo": "Ṣàtẹ̀jáde báyìí", "zu": "Shicilela manje"},
    "URL publique": {"ko": "공개 URL", "vi": "URL công khai", "no": "Offentlig URL", "ru": "Публичный URL", "yo": "URL gbangba", "zu": "I-URL yomphakathi"},
    "Dépublier": {"ko": "게시 취소", "vi": "Hủy đăng", "no": "Avpubliser", "ru": "Снять с публикации", "yo": "Yọ àtẹ̀jáde kúrò", "zu": "Susa ukushicilela"},
    "Options de visibilité": {"ko": "공개 설정", "vi": "Tùy chọn hiển thị", "no": "Synlighetsalternativer", "ru": "Параметры видимости", "yo": "Àwọn àṣàyàn ìríran", "zu": "Izinketho zokubonakala"},
    "Autoriser les inscriptions en ligne": {"ko": "온라인 등록 허용", "vi": "Cho phép đăng ký trực tuyến", "no": "Tillat påmelding på nett", "ru": "Разрешить онлайн-регистрацию", "yo": "Gbà ìforúkọsílẹ̀ lórí ayélujára", "zu": "Vumela ukubhalisa ku-inthanethi"},
    "Afficher la liste des participants": {"ko": "참가자 목록 표시", "vi": "Hiển thị danh sách người tham gia", "no": "Vis deltakerliste", "ru": "Показать список участников", "yo": "Fi àtòjọ àwọn olùkópa hàn", "zu": "Bonisa uhlu lwababambi qhaza"},
    "Partager la compétition": {"ko": "대회 공유", "vi": "Chia sẻ cuộc thi", "no": "Del konkurransen", "ru": "Поделиться соревнованием", "yo": "Pín ìdíje náà", "zu": "Yabelana umqhudelwano"},
    "Partager sur Facebook": {"ko": "Facebook에 공유", "vi": "Chia sẻ trên Facebook", "no": "Del på Facebook", "ru": "Поделиться в Facebook", "yo": "Pín sí Facebook", "zu": "Yabelana ku-Facebook"},
    "Partager sur Twitter": {"ko": "Twitter에 공유", "vi": "Chia sẻ trên Twitter", "no": "Del på Twitter", "ru": "Поделиться в Twitter", "yo": "Pín sí Twitter", "zu": "Yabelana ku-Twitter"},
    "Partager sur WhatsApp": {"ko": "WhatsApp에 공유", "vi": "Chia sẻ trên WhatsApp", "no": "Del på WhatsApp", "ru": "Поделиться в WhatsApp", "yo": "Pín sí WhatsApp", "zu": "Yabelana ku-WhatsApp"},
    "Notifier les juges": {"ko": "심판에게 알림", "vi": "Thông báo cho trọng tài", "no": "Varsle dommere", "ru": "Уведомить судей", "yo": "Fi tó àwọn adájọ́ létí", "zu": "Azisa abahluleli"},
    "Ajouter un type de compétition": {"ko": "대회 유형 추가", "vi": "Thêm loại cuộc thi", "no": "Legg til konkurransetype", "ru": "Добавить тип соревнования", "yo": "Fi irú ìdíje kan kún", "zu": "Engeza uhlobo lomqhudelwano"},
    "Règles spécifiques": {"ko": "특별 규칙", "vi": "Quy tắc cụ thể", "no": "Spesifikke regler", "ru": "Особые правила", "yo": "Àwọn òfin pàtó", "zu": "Imithetho eqondile"},
    "Aucun grade minimum": {"ko": "최소 단 없음", "vi": "Không có đai tối thiểu", "no": "Ingen minimumsgrad", "ru": "Нет минимального разряда", "yo": "Kò sí ìpele tí ó kéré jù", "zu": "Akukho banga eliphansi"},
    "Aucun grade maximum": {"ko": "최대 단 없음", "vi": "Không có đai tối đa", "no": "Ingen maksimumsgrad", "ru": "Нет максимального разряда", "yo": "Kò sí ìpele tí ó pọ̀ jù", "zu": "Akukho banga eliphezulu"},
    "Rechercher un utilisateur": {"ko": "사용자 검색", "vi": "Tìm kiếm người dùng", "no": "Søk etter bruker", "ru": "Поиск пользователя", "yo": "Wá olùlò kan", "zu": "Sesha umsebenzisi"},
    "Nom ou email": {"ko": "이름 또는 이메일", "vi": "Tên hoặc email", "no": "Navn eller e-post", "ru": "Имя или email", "yo": "Orúkọ tàbí ímeèlì", "zu": "Igama noma i-imeyili"},
    "Juge de coin": {"ko": "코너 심판", "vi": "Trọng tài góc", "no": "Hjørnedommer", "ru": "Угловой судья", "yo": "Adájọ́ igun", "zu": "Umhluleli wasegumbini"},
    "Table de marque": {"ko": "득점표", "vi": "Bảng điểm", "no": "Resultattavle", "ru": "Стол для подсчёта", "yo": "Tábìlì àmì", "zu": "Ithebula lamaphuzu"},
    "Arbitre en chef": {"ko": "수석 심판", "vi": "Trọng tài trưởng", "no": "Hoveddommer", "ru": "Главный судья", "yo": "Olórí adájọ́", "zu": "Umhluleli omkhulu"},
    "Pratiquant affecté avec succès": {"ko": "수련생 배정 성공", "vi": "Phân công võ sinh thành công", "no": "Utøver tildelt", "ru": "Спортсмен успешно назначен", "yo": "Olùṣe ti yàn sí ní àṣeyọrí", "zu": "Umzivocavocayo ubelwe ngempumelelo"},
    "Erreur de connexion": {"ko": "연결 오류", "vi": "Lỗi kết nối", "no": "Tilkoblingsfeil", "ru": "Ошибка подключения", "yo": "Àṣìṣe ìsopọ̀", "zu": "Iphutha lokuxhuma"},
    "Pratiquant retiré de la catégorie": {"ko": "카테고리에서 수련생 제거됨", "vi": "Đã rút võ sinh khỏi hạng mục", "no": "Utøver fjernet fra kategorien", "ru": "Спортсмен удалён из категории", "yo": "A ti yọ olùṣe kúrò nínú ẹ̀ka", "zu": "Umzivocavocayo ususwe esigabeni"},
    "Juge affecté avec succès": {"ko": "심판 배정 성공", "vi": "Phân công trọng tài thành công", "no": "Dommer tildelt", "ru": "Судья успешно назначен", "yo": "Adájọ́ ti yàn sí ní àṣeyọrí", "zu": "Umhluleli ubelwe ngempumelelo"},
    "Catégorie créée avec succès": {"ko": "카테고리 생성 성공", "vi": "Tạo hạng mục thành công", "no": "Kategori opprettet", "ru": "Категория успешно создана", "yo": "Ẹ̀ka ti ṣẹ̀dá ní àṣeyọrí", "zu": "Isigaba sidalwe ngempumelelo"},
    "Erreur lors de la création": {"ko": "생성 중 오류", "vi": "Lỗi khi tạo", "no": "Feil ved opprettelse", "ru": "Ошибка при создании", "yo": "Àṣìṣe nígbà ìṣẹ̀dá", "zu": "Iphutha ngesikhathi sokudala"},
    "Type de compétition créé avec succès": {"ko": "대회 유형 생성 성공", "vi": "Tạo loại cuộc thi thành công", "no": "Konkurransetype opprettet", "ru": "Тип соревнования успешно создан", "yo": "Irú ìdíje ti ṣẹ̀dá ní àṣeyọrí", "zu": "Uhlobo lomqhudelwano ludalwe ngempumelelo"},
    "Erreur de connexion: ": {"ko": "연결 오류: ", "vi": "Lỗi kết nối: ", "no": "Tilkoblingsfeil: ", "ru": "Ошибка подключения: ", "yo": "Àṣìṣe ìsopọ̀: ", "zu": "Iphutha lokuxhuma: "},
    "Recherche...": {"ko": "검색 중...", "vi": "Đang tìm kiếm...", "no": "Søker...", "ru": "Поиск...", "yo": "Ń wá...", "zu": "Iyasesha..."},
    "Arbitre national": {"ko": "국가 심판", "vi": "Trọng tài quốc gia", "no": "Nasjonal dommer", "ru": "Национальный судья", "yo": "Adájọ́ orílẹ̀-èdè", "zu": "Umhluleli kazwelonke"},
    "Juge régional": {"ko": "지역 심판", "vi": "Trọng tài khu vực", "no": "Regional dommer", "ru": "Региональный судья", "yo": "Adájọ́ ẹkùn", "zu": "Umhluleli wesifunda"},
    "Catégorie supprimée avec succès": {"ko": "카테고리 삭제 성공", "vi": "Xóa hạng mục thành công", "no": "Kategori slettet", "ru": "Категория успешно удалена", "yo": "Ẹ̀ka ti parẹ́ ní àṣeyọrí", "zu": "Isigaba sisuswe ngempumelelo"},
    "Compétition publiée avec succès !": {"ko": "대회 게시 성공!", "vi": "Đăng cuộc thi thành công!", "no": "Konkurranse publisert!", "ru": "Соревнование успешно опубликовано!", "yo": "Ìdíje ti tẹ̀jáde ní àṣeyọrí!", "zu": "Umqhudelwano ushicilelwe ngempumelelo!"},
    "Erreur lors de la publication": {"ko": "게시 중 오류", "vi": "Lỗi khi đăng", "no": "Feil ved publisering", "ru": "Ошибка при публикации", "yo": "Àṣìṣe nígbà àtẹ̀jáde", "zu": "Iphutha ngesikhathi sokushicilela"},
    "Suivi temps réel activé": {"ko": "실시간 추적 활성화됨", "vi": "Theo dõi thời gian thực đã bật", "no": "Sanntidssporing aktivert", "ru": "Отслеживание в реальном времени включено", "yo": "Ìtọpinpin àkókò gidi ti ṣiṣẹ́", "zu": "Ukulandelela kwesikhathi sangempela kuvuliwe"},
    "Progression sauvegardée": {"ko": "진행 상황 저장됨", "vi": "Tiến trình đã lưu", "no": "Fremdrift lagret", "ru": "Прогресс сохранён", "yo": "Ìlọsíwájú ti fipamọ́", "zu": "Inqubekelaphambili ilondoloziwe"},
    "Type de compétition supprimé avec succès": {"ko": "대회 유형 삭제 성공", "vi": "Xóa loại cuộc thi thành công", "no": "Konkurransetype slettet", "ru": "Тип соревнования успешно удалён", "yo": "Irú ìdíje ti parẹ́ ní àṣeyọrí", "zu": "Uhlobo lomqhudelwano lususwe ngempumelelo"},
    "Etes-vous sur ?": {"ko": "확실합니까?", "vi": "Bạn có chắc không?", "no": "Er du sikker?", "ru": "Вы уверены?", "yo": "Ṣé o dá ọ lójú?", "zu": "Uqinisekile?"},
    "Timestamps": {"ko": "타임스탬프", "vi": "Dấu thời gian", "no": "Tidsstempler", "ru": "Временные метки", "yo": "Àmì àkókò", "zu": "Izitembu zesikhathi"},
    "Vie privée": {"ko": "개인정보", "vi": "Quyền riêng tư", "no": "Personvern", "ru": "Конфиденциальность", "yo": "Àṣírí", "zu": "Ubumfihlo"},
    "Messagerie": {"ko": "메시지", "vi": "Tin nhắn", "no": "Meldinger", "ru": "Сообщения", "yo": "Ìfiránṣẹ́", "zu": "Imilayezo"},
    "Message privé": {"ko": "비밀 메시지", "vi": "Tin nhắn riêng", "no": "Privat melding", "ru": "Личное сообщение", "yo": "Ìfiránṣẹ́ àdáni", "zu": "Umlayezo oyimfihlo"},
    "UUID": {"ko": "UUID", "vi": "UUID", "no": "UUID", "ru": "UUID", "yo": "UUID", "zu": "UUID"},
    "Type de conversation": {"ko": "대화 유형", "vi": "Loại cuộc trò chuyện", "no": "Samtaletype", "ru": "Тип беседы", "yo": "Irú ìjíròrò", "zu": "Uhlobo lwengxoxo"},
    "Avatar du groupe": {"ko": "그룹 아바타", "vi": "Ảnh đại diện nhóm", "no": "Gruppeavatar", "ru": "Аватар группы", "yo": "Àwòrán ẹgbẹ́", "zu": "I-avatar yeqembu"},
    "Club associé": {"ko": "연관 클럽", "vi": "Câu lạc bộ liên kết", "no": "Tilknyttet klubb", "ru": "Связанный клуб", "yo": "Ẹgbẹ́ tí ó ní àjọṣe", "zu": "Ikhlabi elihlanganyelayo"},
    "Dernier message le": {"ko": "마지막 메시지", "vi": "Tin nhắn cuối", "no": "Siste melding", "ru": "Последнее сообщение", "yo": "Ìfiránṣẹ́ tó gbẹ̀yìn ní", "zu": "Umlayezo wokugcina ngo"},
    "Aperçu du dernier message": {"ko": "마지막 메시지 미리보기", "vi": "Xem trước tin nhắn cuối", "no": "Forhåndsvisning av siste melding", "ru": "Превью последнего сообщения", "yo": "Ìwòran ìfiránṣẹ́ tó gbẹ̀yìn", "zu": "Ukubuka kuqala komlayezo wokugcina"},
    "Autoriser les réponses": {"ko": "답장 허용", "vi": "Cho phép trả lời", "no": "Tillat svar", "ru": "Разрешить ответы", "yo": "Gbà àwọn ìdáhùn", "zu": "Vumela izimpendulo"},
    "Conversation directe": {"ko": "직접 대화", "vi": "Trò chuyện trực tiếp", "no": "Direkte samtale", "ru": "Прямой диалог", "yo": "Ìjíròrò tààrà", "zu": "Ingxoxo eqondile"},
    "Modérateur": {"ko": "관리자", "vi": "Người kiểm duyệt", "no": "Moderator", "ru": "Модератор", "yo": "Olùṣàkóso", "zu": "Umphathi"},
    "Notifications désactivées": {"ko": "알림 비활성화", "vi": "Đã tắt thông báo", "no": "Varsler deaktivert", "ru": "Уведомления отключены", "yo": "Àwọn ìfitónilétí ti dáwọ́ dúró", "zu": "Izaziso zivaliwe"},
    "Épinglé": {"ko": "고정됨", "vi": "Đã ghim", "no": "Festet", "ru": "Закреплено", "yo": "Ti fara mọ́", "zu": "Kunamathiselwe"},
    "Dernier lu le": {"ko": "마지막 읽은 날짜", "vi": "Đọc lần cuối", "no": "Sist lest", "ru": "Прочитано", "yo": "Ti ka tó gbẹ̀yìn ní", "zu": "Ukufundwa kokugcina ngo"},
    "Surnom": {"ko": "별명", "vi": "Biệt danh", "no": "Kallenavn", "ru": "Прозвище", "yo": "Orúkọ àpèje", "zu": "Isidlaliso"},
    "Type de message": {"ko": "메시지 유형", "vi": "Loại tin nhắn", "no": "Meldingstype", "ru": "Тип сообщения", "yo": "Irú ìfiránṣẹ́", "zu": "Uhlobo lomlayezo"},
    "En réponse à": {"ko": "답장 대상", "vi": "Trả lời cho", "no": "Som svar på", "ru": "В ответ на", "yo": "Ní ìdáhùn sí", "zu": "Ukuphendula ku"},
    "Supprimé par": {"ko": "삭제자", "vi": "Đã xóa bởi", "no": "Slettet av", "ru": "Удалено пользователем", "yo": "Ti parẹ́ nípasẹ̀", "zu": "Kususe ngu"},
    "Modifié": {"ko": "수정됨", "vi": "Đã sửa", "no": "Endret", "ru": "Изменено", "yo": "Ti ṣàtúnṣe", "zu": "Kugujwe"},
    "Tableur": {"ko": "스프레드시트", "vi": "Bảng tính", "no": "Regneark", "ru": "Электронная таблица", "yo": "Àkójọ tábìlì", "zu": "Ispredishithi"},
    "Taille (bytes)": {"ko": "크기 (바이트)", "vi": "Kích thước (bytes)", "no": "Størrelse (bytes)", "ru": "Размер (байт)", "yo": "Ìwọ̀n (bytes)", "zu": "Usayizi (bytes)"},
    "Largeur": {"ko": "너비", "vi": "Chiều rộng", "no": "Bredde", "ru": "Ширина", "yo": "Ìbú", "zu": "Ububanzi"},
    "Hauteur": {"ko": "높이", "vi": "Chiều cao", "no": "Høyde", "ru": "Высота", "yo": "Gíga", "zu": "Ubude"},
    "Miniature": {"ko": "미리보기 이미지", "vi": "Hình thu nhỏ", "no": "Miniatyrbilde", "ru": "Миниатюра", "yo": "Àwòrán kékeré", "zu": "Isithombe esincane"},
    "Téléchargé le": {"ko": "업로드일", "vi": "Tải lên ngày", "no": "Lastet opp", "ru": "Загружено", "yo": "Ti gba sókè ní", "zu": "Kulayishwe ngo"},
    "Statut de lecture": {"ko": "읽음 상태", "vi": "Trạng thái đọc", "no": "Lesestatus", "ru": "Статус прочтения", "yo": "Ipò kíkà", "zu": "Isimo sokufunda"},
    "Statuts de lecture": {"ko": "읽음 상태 목록", "vi": "Các trạng thái đọc", "no": "Lesestatuser", "ru": "Статусы прочтения", "yo": "Àwọn ipò kíkà", "zu": "Izimo zokufunda"},
    "Automatique": {"ko": "자동", "vi": "Tự động", "no": "Automatisk", "ru": "Автоматически", "yo": "Àìfọwọ́yí", "zu": "Okuzenzakalelayo"},
    "Notifications push": {"ko": "푸시 알림", "vi": "Thông báo đẩy", "no": "Push-varsler", "ru": "Push-уведомления", "yo": "Ìfitónilétí títì", "zu": "Izaziso ze-push"},
    "Sons activés": {"ko": "소리 켜짐", "vi": "Bật âm thanh", "no": "Lyd aktivert", "ru": "Звук включён", "yo": "Ohùn ti ṣiṣẹ́", "zu": "Imisindo ivuliwe"},
    "Paramètres de chat": {"ko": "채팅 설정", "vi": "Cài đặt trò chuyện", "no": "Chat-innstillinger", "ru": "Настройки чата", "yo": "Ètò ìjíròrò", "zu": "Izilungiselelo zengxoxo"},
    "Nouvelle conversation": {"ko": "새 대화", "vi": "Cuộc trò chuyện mới", "no": "Ny samtale", "ru": "Новый диалог", "yo": "Ìjíròrò tuntun", "zu": "Ingxoxo entsha"},
    "Aucune conversation": {"ko": "대화 없음", "vi": "Không có cuộc trò chuyện", "no": "Ingen samtaler", "ru": "Нет бесед", "yo": "Kò sí ìjíròrò", "zu": "Akukho ngxoxo"},
    "Commencer une discussion": {"ko": "토론 시작", "vi": "Bắt đầu trò chuyện", "no": "Start en samtale", "ru": "Начать обсуждение", "yo": "Bẹ̀rẹ̀ ìjíròrò", "zu": "Qala ingxoxo"},
    "Sélectionnez une conversation": {"ko": "대화 선택", "vi": "Chọn cuộc trò chuyện", "no": "Velg en samtale", "ru": "Выберите диалог", "yo": "Yan ìjíròrò kan", "zu": "Khetha ingxoxo"},
    "Direct": {"ko": "다이렉트", "vi": "Trực tiếp", "no": "Direkte", "ru": "Личный", "yo": "Tààrà", "zu": "Okuqondile"},
    "Nom du groupe": {"ko": "그룹 이름", "vi": "Tên nhóm", "no": "Gruppenavn", "ru": "Название группы", "yo": "Orúkọ ẹgbẹ́", "zu": "Igama leqembu"},
    "Ex: Équipe technique": {"ko": "예: 기술팀", "vi": "VD: Đội kỹ thuật", "no": "F.eks: Teknisk lag", "ru": "Напр.: Техническая команда", "yo": "Àpẹẹrẹ: Ẹgbẹ́ ọ̀nà", "zu": "Isb: Ithimu yezobuchwepheshe"},
    "Destinataire(s)": {"ko": "수신자", "vi": "Người nhận", "no": "Mottaker(e)", "ru": "Получатель(и)", "yo": "Olùgbà", "zu": "Umamukeli"},
    "Quitter": {"ko": "나가기", "vi": "Thoát", "no": "Forlat", "ru": "Выйти", "yo": "Jáde", "zu": "Phuma"},
    "Discussion privée": {"ko": "비밀 대화", "vi": "Trò chuyện riêng", "no": "Privat samtale", "ru": "Личная беседа", "yo": "Ìjíròrò àdáni", "zu": "Ingxoxo eyimfihlo"},
    "Discussion à plusieurs": {"ko": "그룹 대화", "vi": "Trò chuyện nhóm", "no": "Gruppesamtale", "ru": "Групповой чат", "yo": "Ìjíròrò ẹgbẹ́", "zu": "Ingxoxo yeqembu"},
    "Ex: Équipe compétition": {"ko": "예: 대회팀", "vi": "VD: Đội thi đấu", "no": "F.eks: Konkurranselag", "ru": "Напр.: Команда соревнования", "yo": "Àpẹẹrẹ: Ẹgbẹ́ ìdíje", "zu": "Isb: Ithimu yomqhudelwano"},
    "Créer la conversation": {"ko": "대화 만들기", "vi": "Tạo cuộc trò chuyện", "no": "Opprett samtale", "ru": "Создать беседу", "yo": "Ṣẹ̀dá ìjíròrò", "zu": "Dala ingxoxo"},
    "Mettre en sourdine": {"ko": "음소거", "vi": "Tắt tiếng", "no": "Demp", "ru": "Отключить звук", "yo": "Pa ohùn rẹ̀", "zu": "Thulisa"},
    "Tapez votre message...": {"ko": "메시지를 입력하세요...", "vi": "Nhập tin nhắn...", "no": "Skriv din melding...", "ru": "Введите сообщение...", "yo": "Tẹ ìfiránṣẹ́ rẹ sílẹ̀...", "zu": "Thayipha umlayezo wakho..."},
    "Pas de messages": {"ko": "메시지 없음", "vi": "Không có tin nhắn", "no": "Ingen meldinger", "ru": "Нет сообщений", "yo": "Kò sí ìfiránṣẹ́", "zu": "Akukho milayezo"},
    "Message supprimé": {"ko": "삭제된 메시지", "vi": "Tin nhắn đã xóa", "no": "Melding slettet", "ru": "Сообщение удалено", "yo": "Ìfiránṣẹ́ ti parẹ́", "zu": "Umlayezo ususwe"},
    "Réagir": {"ko": "반응하기", "vi": "Phản ứng", "no": "Reager", "ru": "Отреагировать", "yo": "Dáhùn", "zu": "Phendula"},
    "Emoji requis.": {"ko": "이모지가 필요합니다.", "vi": "Cần có emoji.", "no": "Emoji påkrevd.", "ru": "Требуется эмодзи.", "yo": "Emoji jẹ́ dandan.", "zu": "Kudingeka i-emoji."},
    "Date non définie": {"ko": "날짜 미정", "vi": "Chưa xác định ngày", "no": "Dato ikke satt", "ru": "Дата не указана", "yo": "Ọjọ́ kò tíì yàn", "zu": "Usuku aluchazwanga"},
    "Âge": {"ko": "나이", "vi": "Tuổi", "no": "Alder", "ru": "Возраст", "yo": "Ọjọ́ orí", "zu": "Iminyaka"},
    "Changer statut": {"ko": "상태 변경", "vi": "Đổi trạng thái", "no": "Endre status", "ru": "Изменить статус", "yo": "Yí ipò padà", "zu": "Shintsha isimo"},
    "Navigation pages": {"ko": "페이지 이동", "vi": "Điều hướng trang", "no": "Sidenavigasjon", "ru": "Навигация по страницам", "yo": "Ìlọ̀ sí ojú ewé", "zu": "Ukuzulazula emakhasini"},
    "Générer tous les QR codes": {"ko": "모든 QR 코드 생성", "vi": "Tạo tất cả mã QR", "no": "Generer alle QR-koder", "ru": "Сгенерировать все QR-коды", "yo": "Ṣẹ̀dá gbogbo àwọn kóòdù QR", "zu": "Khiqiza wonke amakhodi e-QR"},
    "Créez votre première compétition": {"ko": "첫 대회를 만드세요", "vi": "Tạo cuộc thi đầu tiên", "no": "Opprett din første konkurranse", "ru": "Создайте первое соревнование", "yo": "Ṣẹ̀dá ìdíje rẹ àkọ́kọ́", "zu": "Dala umqhudelwano wakho wokuqala"},
    "Suivi financier": {"ko": "재정 추적", "vi": "Theo dõi tài chính", "no": "Finansiell sporing", "ru": "Финансовый учёт", "yo": "Ìtọpinpin owó", "zu": "Ukulandelela kwezezimali"},
    "Module d'entraînement": {"ko": "훈련 모듈", "vi": "Mô-đun huấn luyện", "no": "Treningsmodul", "ru": "Модуль тренировок", "yo": "Apá ìdánilẹ́kọ̀ọ́", "zu": "Imodyuli yokuqeqesha"},
    "Aucun événement": {"ko": "이벤트 없음", "vi": "Không có sự kiện", "no": "Ingen arrangementer", "ru": "Нет мероприятий", "yo": "Kò sí ìṣẹ̀lẹ̀", "zu": "Akukho mcimbi"},
    "Créez votre premier événement": {"ko": "첫 이벤트를 만드세요", "vi": "Tạo sự kiện đầu tiên", "no": "Opprett ditt første arrangement", "ru": "Создайте первое мероприятие", "yo": "Ṣẹ̀dá ìṣẹ̀lẹ̀ rẹ àkọ́kọ́", "zu": "Dala umcimbi wakho wokuqala"},
    "Assigner un rôle": {"ko": "역할 배정", "vi": "Chỉ định vai trò", "no": "Tildel rolle", "ru": "Назначить роль", "yo": "Yàn ipò kan sí", "zu": "Abela indima"},
    "Gestion complète du club": {"ko": "클럽 전체 관리", "vi": "Quản lý câu lạc bộ toàn diện", "no": "Komplett klubbstyring", "ru": "Полное управление клубом", "yo": "Ìṣàkóso ẹgbẹ́ ní kíkún", "zu": "Ukuphatha ikhlabi ngokugcwele"},
    "Gestion des membres et inscriptions": {"ko": "회원 및 등록 관리", "vi": "Quản lý thành viên và đăng ký", "no": "Medlems- og påmeldingsstyring", "ru": "Управление членами и регистрациями", "yo": "Ìṣàkóso àwọn ọmọ ẹgbẹ́ àti ìforúkọsílẹ̀", "zu": "Ukuphatha amalungu nokubhalisa"},
    "Pratiquant supprimé avec succès": {"ko": "수련생 삭제 성공", "vi": "Xóa võ sinh thành công", "no": "Utøver slettet", "ru": "Спортсмен успешно удалён", "yo": "Olùṣe ti parẹ́ ní àṣeyọrí", "zu": "Umzivocavocayo ususwe ngempumelelo"},
    "Import réussi": {"ko": "가져오기 성공", "vi": "Nhập thành công", "no": "Import vellykket", "ru": "Импорт успешен", "yo": "Ìgbéwọlé ti ṣàṣeyọrí", "zu": "Ukungenisa kuphumelele"},
    "Inscription réussie": {"ko": "등록 성공", "vi": "Đăng ký thành công", "no": "Påmelding vellykket", "ru": "Регистрация успешна", "yo": "Ìforúkọsílẹ̀ ti ṣàṣeyọrí", "zu": "Ukubhalisa kuphumelele"},
    "Import en cours...": {"ko": "가져오기 중...", "vi": "Đang nhập...", "no": "Importerer...", "ru": "Импорт...", "yo": "Ìgbéwọlé ń lọ...", "zu": "Iyangenisa..."},
    "Progression de la poule": {"ko": "풀 진행 상황", "vi": "Tiến trình bảng đấu", "no": "Puljefremgang", "ru": "Прогресс пула", "yo": "Ìlọsíwájú ẹgbẹ́ ìdíje", "zu": "Inqubekelaphambili yeqoqo"},
    "combats": {"ko": "대전", "vi": "trận đấu", "no": "kamper", "ru": "поединки", "yo": "àwọn ìjà", "zu": "impi"},
    "Équipes participantes": {"ko": "참가 팀", "vi": "Các đội tham gia", "no": "Deltakende lag", "ru": "Команды-участники", "yo": "Àwọn ẹgbẹ́ olùkópa", "zu": "Amathimu abambi qhaza"},
    "Pratiquants participants": {"ko": "참가 수련생", "vi": "Các võ sinh tham gia", "no": "Deltakende utøvere", "ru": "Участвующие спортсмены", "yo": "Àwọn olùṣe olùkópa", "zu": "Abazivocavocayo ababambi qhaza"},
    "Créer le premier combat": {"ko": "첫 대전 만들기", "vi": "Tạo trận đấu đầu tiên", "no": "Opprett første kamp", "ru": "Создать первый поединок", "yo": "Ṣẹ̀dá ìjà àkọ́kọ́", "zu": "Dala impi yokuqala"},
    "PÉNALITÉ": {"ko": "페널티", "vi": "PHẠT", "no": "STRAFF", "ru": "ШТРАФ", "yo": "ÌJÌYÀ", "zu": "INHLAWULO"},
    "SORTIE": {"ko": "퇴장", "vi": "THOÁT", "no": "UTGANG", "ru": "ВЫХОД", "yo": "JÁDE", "zu": "UKUPHUMA"},
    "Annuler la dernière action": {"ko": "마지막 작업 취소", "vi": "Hủy thao tác cuối", "no": "Angre siste handling", "ru": "Отменить последнее действие", "yo": "Fagílé ìṣe tó gbẹ̀yìn", "zu": "Hlehlisa isenzo sokugcina"},
    "ANNULER": {"ko": "취소", "vi": "HỦY", "no": "AVBRYT", "ru": "ОТМЕНА", "yo": "FAGÍLÉ", "zu": "KHANSELA"},
    "DÉMARRER": {"ko": "시작", "vi": "BẮT ĐẦU", "no": "START", "ru": "СТАРТ", "yo": "BẸRẸ", "zu": "QALA"},
    "PAUSE": {"ko": "일시정지", "vi": "TẠM DỪNG", "no": "PAUSE", "ru": "ПАУЗА", "yo": "DÚRÓ", "zu": "PHUMULA"},
    "Historique des Actions": {"ko": "작업 내역", "vi": "Lịch sử hành động", "no": "Handlingshistorikk", "ru": "История действий", "yo": "Ìtàn àwọn ìṣe", "zu": "Umlando wezenzo"},
    "Configuration régionale": {"ko": "지역 설정", "vi": "Cấu hình khu vực", "no": "Regional konfigurasjon", "ru": "Региональная настройка", "yo": "Ètò ẹkùn", "zu": "Ukumisa kwesifunda"},
    "Sans organisation": {"ko": "소속 없음", "vi": "Không thuộc tổ chức", "no": "Uten organisasjon", "ru": "Без организации", "yo": "Láìsí ẹgbẹ́", "zu": "Ngaphandle kwenhlangano"},
    "Avec organisation": {"ko": "소속 있음", "vi": "Có tổ chức", "no": "Med organisasjon", "ru": "С организацией", "yo": "Pẹ̀lú ẹgbẹ́", "zu": "Nenhlangano"},
    "Disciplines et grades": {"ko": "종목 및 단", "vi": "Bộ môn và đai", "no": "Disipliner og grader", "ru": "Дисциплины и разряды", "yo": "Ẹ̀kọ́ àti àwọn ìpele", "zu": "Izifundo namabanga"},
}

# Apply to all 6 languages
langs = ['ko', 'vi', 'no', 'ru', 'yo', 'zu']
for lang in langs:
    po = polib.pofile(f'locale/{lang}/LC_MESSAGES/django.po')
    count = 0
    for entry in po.untranslated_entries():
        if entry.msgid in MULTI and lang in MULTI[entry.msgid]:
            entry.msgstr = MULTI[entry.msgid][lang]
            count += 1
    po.save()
    remaining = len(polib.pofile(f'locale/{lang}/LC_MESSAGES/django.po').untranslated_entries())
    print(f'{lang}: {count} translated, {remaining} remaining')
