#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
Traduction complete et nettoyage du fichier PO italien.
"""

import re
import os
from collections import OrderedDict

# Dictionnaire francais -> italien tres complet
FR_IT_DICT = {
    # --- Juges et arbitres ---
    "Juges Techniques (Notation Technique)": "Giudici Tecnici (Valutazione Tecnica)",
    "Ajouter un juge technique": "Aggiungi un giudice tecnico",
    "Juges techniques disponibles": "Giudici tecnici disponibili",
    "ans d'expérience": "anni di esperienza",
    "Aucun juge technique disponible": "Nessun giudice tecnico disponibile",
    "Affectations par catégorie": "Assegnazioni per categoria",
    "Glisser les juges techniques ici (peut être plus de 5)": "Trascina i giudici tecnici qui (può essere più di 5)",
    "Aucune catégorie créée. Créez d'abord des catégories.": "Nessuna categoria creata. Crea prima le categorie.",
    "Arbitres de Combat": "Arbitri di Combattimento",
    "Ajouter un arbitre": "Aggiungi un arbitro",
    "Pour les combats : Arbitre central (1), Arbitres de coin (2-3), Arbitre de table (1), Placator (1).": "Per i combattimenti: Arbitro centrale (1), Arbitri d'angolo (2-3), Arbitro di tavolo (1), Placator (1).",
    "Arbitres disponibles": "Arbitri disponibili",
    "Aucun arbitre disponible": "Nessun arbitro disponibile",
    "Affectations par tatami": "Assegnazioni per tatami",
    "Arbitre Central": "Arbitro Centrale",
    "Glisser 1 arbitre central": "Trascina 1 arbitro centrale",
    "Arbitres de Coin": "Arbitri d'Angolo",
    "Glisser 2-3 arbitres de coin": "Trascina 2-3 arbitri d'angolo",
    "Arbitre de Table": "Arbitro di Tavolo",
    "Glisser 1 arbitre de table": "Trascina 1 arbitro di tavolo",
    "Placator": "Placator",
    "Glisser 1 placator": "Trascina 1 placator",

    # --- Planning ---
    "Programmation et suivi temps réel": "Programmazione e monitoraggio in tempo reale",
    "Démarrer le suivi": "Avvia il monitoraggio",
    "Planning de la journée": "Pianificazione della giornata",
    "Accueil et pesée": "Accoglienza e pesatura",
    "Vérification des licences et pesée officielle": "Verifica delle licenze e pesatura ufficiale",
    "Monter": "Sali",
    "Descendre": "Scendi",
    "Cérémonie d'ouverture": "Cerimonia di apertura",
    "Présentation des juges et rappel des règles": "Presentazione dei giudici e promemoria delle regole",
    "Compétitions - Session 1": "Competizioni - Sessione 1",
    "Catégories jeunes et débutants": "Categorie giovani e principianti",
    "Temps réel": "Tempo reale",
    "État des tatamis": "Stato dei tatami",

    # --- Publication ---
    "Publication et partage": "Pubblicazione e condivisione",
    "État de publication": "Stato di pubblicazione",
    "Cette compétition n'est pas encore publiée. Elle n'est visible que par les organisateurs.": "Questa competizione non è ancora pubblicata. È visibile solo dagli organizzatori.",
    "Checklist avant publication": "Checklist prima della pubblicazione",
    "Lieu défini": "Luogo definito",
    "Au moins une catégorie créée": "Almeno una categoria creata",
    "Informations complètes": "Informazioni complete",
    "Publier maintenant": "Pubblica ora",
    "Cette compétition est publiée et visible publiquement.": "Questa competizione è pubblicata e visibile pubblicamente.",
    "URL publique": "URL pubblico",
    "Options de visibilité": "Opzioni di visibilità",
    "Autoriser les inscriptions en ligne": "Consenti le iscrizioni online",
    "Afficher la liste des participants": "Mostra l'elenco dei partecipanti",
    "Afficher le planning": "Mostra la pianificazione",
    "Partager sur les réseaux sociaux": "Condividi sui social network",

    # --- Inscriptions ---
    "Inscriptions ouvertes": "Iscrizioni aperte",
    "Inscriptions fermées": "Iscrizioni chiuse",
    "S'inscrire": "Iscriviti",
    "Date limite d'inscription": "Data limite di iscrizione",
    "Tarif d'inscription": "Tariffa di iscrizione",
    "Frais d'inscription": "Costi di iscrizione",
    "Inscription réussie": "Iscrizione riuscita",
    "Inscription en attente": "Iscrizione in attesa",
    "Inscription validée": "Iscrizione convalidata",
    "Inscription refusée": "Iscrizione rifiutata",
    "Annuler l'inscription": "Annulla l'iscrizione",
    "Confirmer l'inscription": "Conferma l'iscrizione",
    "Modifier l'inscription": "Modifica l'iscrizione",
    "Nouvelle inscription": "Nuova iscrizione",
    "Inscription à la compétition": "Iscrizione alla competizione",
    "Mes inscriptions": "Le mie iscrizioni",
    "Liste des inscriptions": "Elenco delle iscrizioni",
    "Gérer les inscriptions": "Gestisci le iscrizioni",
    "Nombre d'inscriptions": "Numero di iscrizioni",
    "Places disponibles": "Posti disponibili",
    "Places restantes": "Posti rimanenti",
    "Complet": "Completo",
    "Liste d'attente": "Lista d'attesa",

    # --- Catégories ---
    "Catégorie": "Categoria",
    "Catégories": "Categorie",
    "Nouvelle catégorie": "Nuova categoria",
    "Créer une catégorie": "Crea una categoria",
    "Ajouter une catégorie": "Aggiungi una categoria",
    "Modifier la catégorie": "Modifica categoria",
    "Supprimer la catégorie": "Elimina categoria",
    "Nom de la catégorie": "Nome della categoria",
    "Description de la catégorie": "Descrizione della categoria",
    "Catégorie d'âge": "Categoria di età",
    "Catégorie de poids": "Categoria di peso",
    "Catégorie mixte": "Categoria mista",
    "Catégorie masculine": "Categoria maschile",
    "Catégorie féminine": "Categoria femminile",
    "Âge minimum": "Età minima",
    "Âge maximum": "Età massima",
    "Poids minimum": "Peso minimo",
    "Poids maximum": "Peso massimo",
    "Nombre de participants": "Numero di partecipanti",
    "Aucun participant": "Nessun partecipante",

    # --- Compétitions ---
    "Compétition": "Competizione",
    "Compétitions": "Competizioni",
    "Nouvelle compétition": "Nuova competizione",
    "Créer une compétition": "Crea una competizione",
    "Modifier la compétition": "Modifica competizione",
    "Supprimer la compétition": "Elimina competizione",
    "Détails de la compétition": "Dettagli competizione",
    "Informations de la compétition": "Informazioni della competizione",
    "Gestion de la compétition": "Gestione della competizione",
    "Ma compétition": "La mia competizione",
    "Mes compétitions": "Le mie competizioni",
    "Toutes les compétitions": "Tutte le competizioni",
    "Compétitions à venir": "Competizioni in arrivo",
    "Compétitions passées": "Competizioni passate",
    "Compétitions en cours": "Competizioni in corso",
    "Lieu de la compétition": "Luogo della competizione",
    "Date de la compétition": "Data della competizione",
    "Horaires de la compétition": "Orari della competizione",
    "Règlement de la compétition": "Regolamento della competizione",
    "Organisateur": "Organizzatore",
    "Organisateurs": "Organizzatori",

    # --- Résultats ---
    "Résultats": "Risultati",
    "Résultat": "Risultato",
    "Classement": "Classifica",
    "Classements": "Classifiche",
    "Classement final": "Classifica finale",
    "Classement provisoire": "Classifica provvisoria",
    "Position": "Posizione",
    "Rang": "Posizione",
    "Premier": "Primo",
    "Deuxième": "Secondo",
    "Troisième": "Terzo",
    "1er": "1°",
    "2ème": "2°",
    "3ème": "3°",
    "Médaille d'or": "Medaglia d'oro",
    "Médaille d'argent": "Medaglia d'argento",
    "Médaille de bronze": "Medaglia di bronzo",
    "Victoire": "Vittoria",
    "Défaite": "Sconfitta",
    "Match nul": "Pareggio",
    "Égalité": "Pareggio",
    "Gagnant": "Vincitore",
    "Perdant": "Perdente",
    "Score final": "Punteggio finale",
    "Points": "Punti",
    "Point": "Punto",
    "Pénalité": "Penalità",
    "Pénalités": "Penalità",
    "Avertissement": "Avvertimento",
    "Disqualification": "Squalifica",
    "Disqualifié": "Squalificato",
    "Forfait": "Forfait",
    "Abandon": "Abbandono",

    # --- Combats ---
    "Combat": "Combattimento",
    "Combats": "Combattimenti",
    "Match": "Incontro",
    "Matchs": "Incontri",
    "Nouveau combat": "Nuovo combattimento",
    "Prochain combat": "Prossimo combattimento",
    "Combat en cours": "Combattimento in corso",
    "Combat terminé": "Combattimento terminato",
    "Combat à venir": "Combattimento imminente",
    "Aire de combat": "Area di combattimento",
    "Aires de combat": "Aree di combattimento",
    "Tatami": "Tatami",
    "Ring": "Ring",
    "Durée du combat": "Durata del combattimento",
    "Temps restant": "Tempo rimanente",
    "Round": "Round",
    "Rounds": "Round",
    "Manche": "Manche",
    "Reprises": "Riprese",
    "Pause": "Pausa",
    "Démarrer": "Avvia",
    "Arrêter": "Ferma",
    "Reprendre": "Riprendi",
    "Chronomètre": "Cronometro",
    "Minuterie": "Timer",
    "Coin rouge": "Angolo rosso",
    "Coin bleu": "Angolo blu",
    "Rouge": "Rosso",
    "Bleu": "Blu",
    "Combattant rouge": "Combattente rosso",
    "Combattant bleu": "Combattente blu",

    # --- Poules et tableaux ---
    "Poule": "Girone",
    "Poules": "Gironi",
    "Tableau": "Tabellone",
    "Tableaux": "Tabelloni",
    "Tableau final": "Tabellone finale",
    "Phase de poules": "Fase a gironi",
    "Phase finale": "Fase finale",
    "Phase éliminatoire": "Fase eliminatoria",
    "Quart de finale": "Quarto di finale",
    "Demi-finale": "Semifinale",
    "Finale": "Finale",
    "Petite finale": "Finale per il 3° posto",
    "Tirage au sort": "Sorteggio",

    # --- Équipes ---
    "Équipe": "Squadra",
    "Équipes": "Squadre",
    "Nouvelle équipe": "Nuova squadra",
    "Créer une équipe": "Crea una squadra",
    "Ajouter un membre": "Aggiungi un membro",
    "Membres de l'équipe": "Membri della squadra",
    "Chef d'équipe": "Caposquadra",
    "Capitaine": "Capitano",
    "Entraîneur": "Allenatore",
    "Coach": "Coach",

    # --- Pratiquants ---
    "Pratiquant": "Praticante",
    "Pratiquants": "Praticanti",
    "Nouveau pratiquant": "Nuovo praticante",
    "Ajouter un pratiquant": "Aggiungi un praticante",
    "Modifier le pratiquant": "Modifica praticante",
    "Liste des pratiquants": "Elenco dei praticanti",
    "Mes pratiquants": "I miei praticanti",
    "Fiche pratiquant": "Scheda praticante",
    "Historique du pratiquant": "Storico del praticante",

    # --- Club ---
    "Club": "Club",
    "Clubs": "Club",
    "Nouveau club": "Nuovo club",
    "Créer un club": "Crea un club",
    "Modifier le club": "Modifica club",
    "Mon club": "Il mio club",
    "Membres du club": "Membri del club",
    "Gestion du club": "Gestione del club",
    "Logo du club": "Logo del club",

    # --- Grades ---
    "Grade": "Grado",
    "Grades": "Gradi",
    "Ceinture": "Cintura",
    "Ceintures": "Cinture",
    "Ceinture blanche": "Cintura bianca",
    "Ceinture jaune": "Cintura gialla",
    "Ceinture orange": "Cintura arancione",
    "Ceinture verte": "Cintura verde",
    "Ceinture bleue": "Cintura blu",
    "Ceinture marron": "Cintura marrone",
    "Ceinture noire": "Cintura nera",
    "Dan": "Dan",
    "Kyu": "Kyu",
    "Passage de grade": "Passaggio di grado",
    "Examen de grade": "Esame di grado",

    # --- Disciplines ---
    "Discipline": "Disciplina",
    "Disciplines": "Discipline",
    "Karaté": "Karate",
    "Judo": "Judo",
    "Taekwondo": "Taekwondo",
    "Aïkido": "Aikido",
    "Aikido": "Aikido",
    "Kung-fu": "Kung-fu",
    "Boxe": "Boxe",
    "Kickboxing": "Kickboxing",
    "MMA": "MMA",
    "Wushu": "Wushu",
    "Kendo": "Kendo",
    "Jiu-jitsu": "Jiu-jitsu",
    "Jujitsu": "Jujitsu",
    "Vovinam": "Vovinam",
    "Muay Thai": "Muay Thai",
    "Savate": "Savate",
    "Sumo": "Sumo",
    "Lutte": "Lotta",
    "Escrime": "Scherma",

    # --- Informations personnelles ---
    "Nom": "Cognome",
    "Prénom": "Nome",
    "Nom complet": "Nome completo",
    "Nom de famille": "Cognome",
    "Date de naissance": "Data di nascita",
    "Lieu de naissance": "Luogo di nascita",
    "Âge": "Età",
    "Sexe": "Sesso",
    "Genre": "Genere",
    "Homme": "Uomo",
    "Femme": "Donna",
    "Masculin": "Maschile",
    "Féminin": "Femminile",
    "Mixte": "Misto",
    "Adresse": "Indirizzo",
    "Rue": "Via",
    "Ville": "Città",
    "Code postal": "Codice postale",
    "Pays": "Paese",
    "Nationalité": "Nazionalità",
    "Téléphone": "Telefono",
    "Téléphone portable": "Cellulare",
    "Email": "Email",
    "Adresse email": "Indirizzo email",
    "Photo": "Foto",
    "Poids": "Peso",
    "Taille": "Altezza",
    "Licence": "Licenza",
    "Numéro de licence": "Numero di licenza",

    # --- Formulaires et champs ---
    "Formulaire": "Modulo",
    "Champ": "Campo",
    "Champs": "Campi",
    "Obligatoire": "Obbligatorio",
    "Optionnel": "Opzionale",
    "Requis": "Richiesto",
    "Veuillez remplir ce champ": "Si prega di compilare questo campo",
    "Ce champ est obligatoire": "Questo campo è obbligatorio",
    "Format invalide": "Formato non valido",
    "Valeur incorrecte": "Valore non corretto",
    "Saisir": "Inserisci",
    "Entrer": "Inserisci",
    "Choisir": "Scegli",
    "Sélectionner": "Seleziona",
    "Sélectionnez une option": "Seleziona un'opzione",
    "Aucune option": "Nessuna opzione",
    "Tous": "Tutti",
    "Toutes": "Tutte",
    "Aucun": "Nessuno",
    "Aucune": "Nessuna",
    "Rechercher": "Cerca",
    "Rechercher...": "Cerca...",
    "Filtrer": "Filtra",
    "Filtrer par": "Filtra per",
    "Trier": "Ordina",
    "Trier par": "Ordina per",
    "Ordre croissant": "Ordine crescente",
    "Ordre décroissant": "Ordine decrescente",
    "Afficher": "Mostra",
    "Masquer": "Nascondi",
    "Mot de passe": "Password",
    "Confirmer le mot de passe": "Conferma password",
    "Mot de passe oublié": "Password dimenticata",
    "Nouveau mot de passe": "Nuova password",
    "Ancien mot de passe": "Vecchia password",
    "Se souvenir de moi": "Ricordami",
    "Rester connecté": "Resta connesso",

    # --- Actions ---
    "Ajouter": "Aggiungi",
    "Créer": "Crea",
    "Modifier": "Modifica",
    "Éditer": "Modifica",
    "Supprimer": "Elimina",
    "Effacer": "Cancella",
    "Annuler": "Annulla",
    "Confirmer": "Conferma",
    "Valider": "Convalida",
    "Enregistrer": "Salva",
    "Sauvegarder": "Salva",
    "Envoyer": "Invia",
    "Soumettre": "Invia",
    "Appliquer": "Applica",
    "Réinitialiser": "Ripristina",
    "Rafraîchir": "Aggiorna",
    "Actualiser": "Aggiorna",
    "Mettre à jour": "Aggiorna",
    "Télécharger": "Scarica",
    "Téléverser": "Carica",
    "Importer": "Importa",
    "Exporter": "Esporta",
    "Copier": "Copia",
    "Coller": "Incolla",
    "Couper": "Taglia",
    "Dupliquer": "Duplica",
    "Partager": "Condividi",
    "Imprimer": "Stampa",
    "Voir": "Visualizza",
    "Ouvrir": "Apri",
    "Fermer": "Chiudi",
    "Retour": "Indietro",
    "Suivant": "Avanti",
    "Précédent": "Precedente",
    "Continuer": "Continua",
    "Terminer": "Termina",
    "Commencer": "Inizia",
    "Démarrer": "Avvia",
    "Arrêter": "Ferma",
    "Publier": "Pubblica",
    "Dépublier": "Annulla pubblicazione",

    # --- Navigation ---
    "Accueil": "Home",
    "Tableau de bord": "Dashboard",
    "Dashboard": "Dashboard",
    "Menu": "Menu",
    "Connexion": "Accesso",
    "Déconnexion": "Disconnessione",
    "Se connecter": "Accedi",
    "Se déconnecter": "Disconnetti",
    "Inscription": "Registrazione",
    "Créer un compte": "Crea un account",
    "Mon compte": "Il mio account",
    "Profil": "Profilo",
    "Mon profil": "Il mio profilo",
    "Paramètres": "Impostazioni",
    "Préférences": "Preferenze",
    "Configuration": "Configurazione",
    "Aide": "Aiuto",
    "Support": "Supporto",
    "Contact": "Contatto",
    "À propos": "Chi siamo",
    "Page d'accueil": "Pagina iniziale",
    "Retour à l'accueil": "Torna alla home",

    # --- Messages ---
    "Message": "Messaggio",
    "Messages": "Messaggi",
    "Notification": "Notifica",
    "Notifications": "Notifiche",
    "Alerte": "Avviso",
    "Alertes": "Avvisi",
    "Information": "Informazione",
    "Informations": "Informazioni",
    "Succès": "Successo",
    "Erreur": "Errore",
    "Attention": "Attenzione",
    "Avertissement": "Avvertimento",
    "Confirmation": "Conferma",
    "Opération réussie": "Operazione riuscita",
    "Une erreur est survenue": "Si è verificato un errore",
    "Êtes-vous sûr ?": "Sei sicuro?",
    "Cette action est irréversible": "Questa azione è irreversibile",
    "Chargement...": "Caricamento...",
    "Chargement en cours": "Caricamento in corso",
    "Veuillez patienter": "Attendere prego",
    "Aucun résultat": "Nessun risultato",
    "Aucune donnée": "Nessun dato",
    "Aucun élément": "Nessun elemento",
    "Liste vide": "Elenco vuoto",

    # --- Statuts ---
    "Statut": "Stato",
    "Actif": "Attivo",
    "Inactif": "Inattivo",
    "Activé": "Attivato",
    "Désactivé": "Disattivato",
    "En cours": "In corso",
    "En attente": "In attesa",
    "Terminé": "Terminato",
    "Validé": "Convalidato",
    "Refusé": "Rifiutato",
    "Annulé": "Annullato",
    "Confirmé": "Confermato",
    "Non confirmé": "Non confermato",
    "Approuvé": "Approvato",
    "Rejeté": "Rifiutato",
    "Publié": "Pubblicato",
    "Non publié": "Non pubblicato",
    "Brouillon": "Bozza",
    "Archivé": "Archiviato",
    "Supprimé": "Eliminato",
    "Disponible": "Disponibile",
    "Indisponible": "Non disponibile",
    "Ouvert": "Aperto",
    "Fermé": "Chiuso",
    "Complet": "Completo",
    "Incomplet": "Incompleto",
    "Réussi": "Riuscito",
    "Échoué": "Fallito",

    # --- Dates et temps ---
    "Date": "Data",
    "Heure": "Ora",
    "Horaire": "Orario",
    "Horaires": "Orari",
    "Début": "Inizio",
    "Fin": "Fine",
    "Durée": "Durata",
    "Jour": "Giorno",
    "Jours": "Giorni",
    "Semaine": "Settimana",
    "Semaines": "Settimane",
    "Mois": "Mese",
    "Année": "Anno",
    "Aujourd'hui": "Oggi",
    "Hier": "Ieri",
    "Demain": "Domani",
    "Cette semaine": "Questa settimana",
    "Ce mois": "Questo mese",
    "Cette année": "Quest'anno",
    "Maintenant": "Ora",
    "Bientôt": "Presto",
    "Déjà": "Già",
    "Lundi": "Lunedì",
    "Mardi": "Martedì",
    "Mercredi": "Mercoledì",
    "Jeudi": "Giovedì",
    "Vendredi": "Venerdì",
    "Samedi": "Sabato",
    "Dimanche": "Domenica",
    "Janvier": "Gennaio",
    "Février": "Febbraio",
    "Mars": "Marzo",
    "Avril": "Aprile",
    "Mai": "Maggio",
    "Juin": "Giugno",
    "Juillet": "Luglio",
    "Août": "Agosto",
    "Septembre": "Settembre",
    "Octobre": "Ottobre",
    "Novembre": "Novembre",
    "Décembre": "Dicembre",

    # --- Oui/Non ---
    "Oui": "Sì",
    "Non": "No",
    "Vrai": "Vero",
    "Faux": "Falso",

    # --- Général ---
    "Général": "Generale",
    "Détails": "Dettagli",
    "Description": "Descrizione",
    "Commentaire": "Commento",
    "Commentaires": "Commenti",
    "Note": "Nota",
    "Notes": "Note",
    "Remarque": "Osservazione",
    "Options": "Opzioni",
    "Réglages": "Impostazioni",
    "Avancé": "Avanzato",
    "Langue": "Lingua",
    "Version": "Versione",
    "Nouveau": "Nuovo",
    "Nouvelle": "Nuova",
    "Ancien": "Vecchio",
    "Récent": "Recente",
    "Autre": "Altro",
    "Autres": "Altri",
    "Total": "Totale",
    "Nombre": "Numero",
    "Quantité": "Quantità",
    "Page": "Pagina",
    "Pages": "Pagine",
    "sur": "di",
    "de": "di",
    "par": "per",
    "par page": "per pagina",
    "éléments": "elementi",
    "résultats": "risultati",
    "Première page": "Prima pagina",
    "Dernière page": "Ultima pagina",
    "Page suivante": "Pagina successiva",
    "Page précédente": "Pagina precedente",

    # --- Finances ---
    "Prix": "Prezzo",
    "Tarif": "Tariffa",
    "Tarifs": "Tariffe",
    "Montant": "Importo",
    "Total": "Totale",
    "Paiement": "Pagamento",
    "Paiements": "Pagamenti",
    "Facture": "Fattura",
    "Factures": "Fatture",
    "TVA": "IVA",
    "HT": "Netto",
    "TTC": "Lordo",
    "Gratuit": "Gratuito",
    "Payant": "A pagamento",
    "Payé": "Pagato",
    "Non payé": "Non pagato",
    "En attente de paiement": "In attesa di pagamento",
    "Remboursement": "Rimborso",
    "Remboursé": "Rimborsato",
    "Euro": "Euro",
    "EUR": "EUR",
    "€": "€",

    # --- Organisasion ---
    "Organisation": "Organizzazione",
    "Organisations": "Organizzazioni",
    "Fédération": "Federazione",
    "Fédérations": "Federazioni",
    "Ligue": "Lega",
    "Ligues": "Leghe",
    "Comité": "Comitato",
    "Association": "Associazione",
    "Membre": "Membro",
    "Membres": "Membri",
    "Adhérent": "Aderente",
    "Adhérents": "Aderenti",
    "Utilisateur": "Utente",
    "Utilisateurs": "Utenti",
    "Administrateur": "Amministratore",
    "Gestionnaire": "Gestore",
    "Propriétaire": "Proprietario",
    "Invité": "Ospite",
    "Rôle": "Ruolo",
    "Rôles": "Ruoli",
    "Permission": "Permesso",
    "Permissions": "Permessi",

    # --- Documents ---
    "Document": "Documento",
    "Documents": "Documenti",
    "Fichier": "File",
    "Fichiers": "File",
    "PDF": "PDF",
    "Excel": "Excel",
    "CSV": "CSV",
    "Image": "Immagine",
    "Images": "Immagini",
    "Télécharger le PDF": "Scarica il PDF",
    "Exporter en PDF": "Esporta in PDF",
    "Exporter en Excel": "Esporta in Excel",
    "Imprimer": "Stampa",
}

# Corrections mojibake
MOJIBAKE = {
    'Ã©': 'é', 'Ã¨': 'è', 'Ãª': 'ê', 'Ã«': 'ë',
    'Ã ': 'à', 'Ã¢': 'â', 'Ã¤': 'ä',
    'Ã¹': 'ù', 'Ã»': 'û', 'Ã¼': 'ü',
    'Ã´': 'ô', 'Ã¶': 'ö',
    'Ã®': 'î', 'Ã¯': 'ï',
    'Ã§': 'ç',
    'Å"': 'œ',
    'Ã€': 'À', 'Ã‰': 'É', 'Ãˆ': 'È', 'Ã‡': 'Ç',
    'â€™': "'", 'â€"': '–', 'â€œ': '"', 'â€': '"',
    'Â ': ' ', 'Â': '',
}


def fix_mojibake(text):
    """Corrige les caracteres mojibake."""
    for bad, good in MOJIBAKE.items():
        text = text.replace(bad, good)
    return text


def main():
    """Fonction principale."""
    po_path = 'locale/it/LC_MESSAGES/django.po'

    print("=" * 70)
    print("TRADUCTION COMPLETE DU PO ITALIEN")
    print("=" * 70)

    with open(po_path, 'r', encoding='utf-8') as f:
        content = f.read()

    # Nettoyer le mojibake
    content = fix_mojibake(content)

    translations_applied = 0

    # Appliquer les traductions
    for fr_term, it_term in FR_IT_DICT.items():
        # Echapper les caracteres speciaux pour regex
        fr_escaped = re.escape(fr_term)

        # Pattern pour msgstr vide
        pattern1 = re.compile(
            rf'(msgid "{fr_escaped}"\n)(msgstr "")',
            re.MULTILINE
        )
        content, count1 = pattern1.subn(rf'\1msgstr "{it_term}"', content)
        translations_applied += count1

        # Pattern pour msgstr = msgid
        pattern2 = re.compile(
            rf'(msgid "{fr_escaped}"\n)(msgstr "{fr_escaped}")',
            re.MULTILINE
        )
        content, count2 = pattern2.subn(rf'\1msgstr "{it_term}"', content)
        translations_applied += count2

    # Sauvegarder
    with open(po_path, 'w', encoding='utf-8') as f:
        f.write(content)

    print(f"\nTraductions appliquees: {translations_applied}")
    print("=" * 70)


if __name__ == '__main__':
    main()
