ServerName martialcomp.com
ServerAlias www.martialcomp.com

DocumentRoot /var/www/vhosts/martialcomp.com/httpdocs

<Directory /var/www/vhosts/martialcomp.com/httpdocs>
    Require all granted
    Options -MultiViews
    AllowOverride All
</Directory>

<IfModule mod_passenger.c>
    PassengerEnabled on
    PassengerAppRoot /var/www/vhosts/martialcomp.com/httpdocs
    PassengerAppType wsgi
    PassengerStartupFile passenger_wsgi.py
    PassengerPython /usr/bin/python3
    PassengerMinInstances 1
</IfModule>

ErrorLog /var/www/vhosts/martialcomp.com/logs/error.log
CustomLog /var/www/vhosts/martialcomp.com/logs/access.log combined 
ServerAlias www.martialcomp.com

DocumentRoot /var/www/vhosts/martialcomp.com/httpdocs

<Directory /var/www/vhosts/martialcomp.com/httpdocs>
    Require all granted
    Options -MultiViews
    AllowOverride All
</Directory>

<IfModule mod_passenger.c>
    PassengerEnabled on
    PassengerAppRoot /var/www/vhosts/martialcomp.com/httpdocs
    PassengerAppType wsgi
    PassengerStartupFile passenger_wsgi.py
    PassengerPython /usr/bin/python3
    PassengerMinInstances 1
</IfModule>

ErrorLog /var/www/vhosts/martialcomp.com/logs/error.log
CustomLog /var/www/vhosts/martialcomp.com/logs/access.log combined 