BBBBBBB BBBBBBBBBBB
BBBB BBBBBB
BBBB BBBB

BBBBB BBBBB gettext(u'Podium')  X  X BBBBBBBB

BBBBB BBBBBBBBB
XXXXXXX
    XXXXXXXXXXXXXXXXX X
        XXXXXXXX XXXXX
        XXXXXXXXXXXXXXXX XXXXXXX
        XXXXXXXXXXXX XXXXXXXXX
        XXXXXXX XXXX XX
        XXXXXXX XXXXXX
    X
    
    XXXXXXXXXXXXX X
        XXXXXXXX XXXXX
        XXXXXXXXXXXXXXX XXXXXXX
        XXXXXXXXXXXX XXXXXXX
        XXXXXXXXX XXXXXXXXX
        XXXXXXX X XXXXX
    X
    
    XXXXXXXXXXXX X
        XXXXXXXX XXXXX
        XXXXXXXXXXXXXXX XXXXXXX
        XXXXXXXXXXXX XXXXXXX
        XXXXXXXXXXXXXXXX XXXXXXXXX
        XXXXXX XXXXXX
        XXXXXXXXXXX XXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXX XXXX
        XXXXXXXXXXXXXXXXXXXXXXXX XXXX
        XXXXXX XXXXXX
        XXXXXXXXXXXX XXXXX
        XXXXXXXXXXXX XXXXX
    X
    
    XXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXXXXXXXX XXXXXXXX XX XXXX XX
        XXXXXXX XXXXXX
        XXXXXX XX
    X
    
    XXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXXXXXXXX XXXXXXXX XX XXXXXX XX
        XXXXXXX XXXXXX
        XXXXXX XX
    X
    
    XXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXXXXXXXX XXXXXXXX XX XXXXXX XX
        XXXXXXX XXXXXX
        XXXXXX XX
    X
    
    XXXXXXXXXXXXXX X
        XXXXXXXXXX XXXXX
        XXXXXXXXXXXXXX XXXXX
    X
    
    XXXXXXXXXXXXX X
        XXXXXXXXXX XXXXXXX
        XXXXXXXXXXXXXX XXXXX
    X
    
    XXXXXXXXXXXXXX X
        XXXXXXXXX XXXXXXXXX
        XXXXXXX XXXXX
        XXXXX XXXX
        XXXXXXXXXX XXXXXXXXXXXXXXXXX
        XXXXXX XXXXX
        XXXXXXX XXXXX
        XXXXXXXXXXXXXX XXXX
        XXXXXXXXXXXXXXXXX XXXXXXXX
        XXXXXXXX XXXXX
        XXXXXXXXXXXX XXXXXXX
        XXXXXXXXXXXXXXXX XXXXXXX
        XXXXXXXXX XXXXXXX
        XXXXXXX XXX XXXXXX
    X
    
    XXXXXX XXXXXXXXXXXXXX X
        XXXXXXXXXXXXX XXXXXXXX
    X
    
    XXXXXXX XXXXXXXXXXXXXX X
        XXXXXXXXXXXXX XXXXXXXX
    X
    
    XXXXXX XXXXXXXXXXXXXX X
        XXXXXXXXXXXXX XXXXXXXX
    X
    
    XXXXXXXXXXXXXX XXX X
        XXXXXX XXXXX
        XXXXXXX XXXXX
        XXXXXXXXXXX XXXXXX
    X
    
    XXXXXXXXXXXX X
        XXXXXXXXXXXX XXXXX
        XXXXXXXXXXX XXXXXXX
        XXXXXXXXXXX XXXXXXX
        XXXXXXXXXX XXXXXX
    X
    
    XXXXXXXXXXXX X
        XXXXXXXXXX XXXXXXXX
        XXXXXX XXXXX
        XXXXXXXXXX XXXXXX
        XXXXXXXXXXX XXXXXXX
    X
    
    XXXXXXXXXXXXX X
        XXXXXXXXXXX XXXXX
        XXXXXXXXXX XXXXXXXX
        XXXXXXXXXXXX XXXXX
    X
    
    XXXXXX XXXXXXXXXXX XXXXXXXXX X
        XXXXXXXXXXXX X
            XXXXXX XXXXXX
        X
        
        XXXXXXXXXXXXXX X
            XXXXXX XXXXX
            XXXXXXX XXXXX
        X
        
        XXXXXXXXXXXXXX X
            XXXXXXXXXX XXXXXXX
        X
        
        XXXXXXXXXXXXX X
            XXXXXXXXXX XXXXX
        X
    X
XXXXXXXX
BBBBBBBB

BBBBB BBBBBBB
XXXX XXXXXXXXXXXXXXXX XXXXXX
    XXXX XXXXX XX XXXXXXXXXX XXX
    XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXX
        XXX XXXXXXXXXXX gettext(u'Podium')  X XXXXX
        XXXX XXXXXXXXXXXXXXXXXX
            XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBB BBBBBBBBBBBX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                XX XXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX gettext(u'Retour aux résultats') 
            XXXX
            XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXX gettext(u'Partager') 
            XXXXXXXXX
        XXXXXX
    XXXXXX

    XXXX XXXXXXXXXXX XXX XX XXXXXXXXX XXX
    XXXX XXXXXXXXXXX XXXXXXXXX XXXXXX
        XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX
            XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                XXX XXXXXXXXX XXXXXX X XXXXX
                XXXXX XXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXX
            XXXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXX
                    XX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXX XXXXXXXXXX gettext(u'Participants') X XXXX
                    XX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXX gettext(u'Date') X 
                        BB BBBBBBBBBBBBBBBBBBB
                            FFFFFFFFFFF FFFF
                        BBBB
                            FFFFFFFFFFFF
                        BBBBB
                    XXXX
                    XX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXX gettext(u'Statut') X 
                        BB BBBBBBBBBBBBBBB BB BBBBBBBBB
                            XXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX gettext(u'En attente') XXXXXXX
                        BBBB BBBBBBBBBBBBBBB BB BBBBBBBBB
                            XXXXX XXXXXXXXXXXX XXXXXXXXX gettext(u'En cours') XXXXXXX
                        BBBB BBBBBBBBBBBBBBB BB BBBBBBBBBBB
                            XXXXX XXXXXXXXXXXX XXXXXXXXXXXX gettext(u'Terminée') XXXXXXX
                        BBBB BBBBBBBBBBBBBBB BB BBBBBBBBBBB
                            XXXXX XXXXXXXXXXXX XXXXXXXXXXX gettext(u'Annulée') XXXXXXX
                        BBBBB
                    XXXX
                XXXXXX
                XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXX
                        XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBB BBBBBBBBBBBX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                            XX XXXXXXXXXX XXXXXXXXX XXXXXXXXXX gettext(u'Voir tous les résultats') 
                        XXXX
                        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                            XX XXXXXXXXXX XXXXXXXX XXXXXXXXXX gettext(u'Imprimer') 
                        XXXXXXXXX
                    XXXXXX
                XXXXXX
            XXXXXX
        XXXXXX
    XXXXXX

    XXXX XXXXXX XXX
    XXXX XXXXXXXXXXX XXXXXXXXX XXXXXX
        XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXX
            XXX XXXXXXXXXXXXX gettext(u'Podium')  X XXXXX
            
            BB BBBBBBBBBBBBB B B
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                    BBB BBBBBBB BB BBBBBB
                        BB BBBBBBBBBBBB BB B
                            XXXX XXXXXXXXXXXXXXXXXXXXX
                                XXXX XXXXXXXXXXXXXXXXXXXXXX
                                    BB BBBBBBBBBBBBBBBBBBBBBBBBBB
                                        XXXX XXXXXX XXXXXXX
                                    BBBB
                                        XX XXXXXXXXXX XXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXX
                                    BBBBB
                                XXXXXX
                                XXXX XXXXXXXXXXXXXXXXXX BB BBBBBBBBBBBB BB BXXXXXBBBB BBBBBBBBBBBB BB BXXXXXXBBBB BBBBBBBBBBBB BB BXXXXXBBBBBXX
                                    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                    XXXX XXXXXXXXXXXXXXXXXXXXX
                                        BB BBBBBBBBBBBB BB BXBBBB BBBBBBBBBBBB BB BXBBBB BBBBBBBBBBBB BB BXBBBBB
                                    XXXXXX
                                    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                                XXXXXX
                                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                                BB BBBBBBBBBBBBBBBBBBBBBBBBB
                                    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                                BBBBB
                            XXXXXX
                        BBBBB
                    BBBBBB
                XXXXXX
            BBBB
                XXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXX
                    XX XXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXX gettext(u'Aucun résultat disponible pour le podium.') 
                XXXXXX
            BBBBB
        XXXXXX
    XXXXXX

    XXXX XXXXXXX XXX XXXXXXXXX XXX
    XXXX XXXXXXXXXXX XXXXXXXXX XXXXXX
        XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXX
            XXX XXXXXXXXX XXXXXX gettext(u'Détails des médaillés') XXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXX
                BBB BBBBBBB BB BBBBBB
                    BB BBBBBBBBBBBB BB B
                        XXXX XXXXXXXXXXXXXXX XXXXXX
                            XXXX XXXXXXXXXXX XXXXX 
                                BB BBBBBBBBBBBB BB BXXXXXXXXXXXXXXBBBB BBBBBBBBBBBB BB BXXXXXXXXXXXXXXXXBBBB BBBBBBBBBBBB BB BXXXXXXXXXXXXXBBBBBXX
                                XXXX XXXXXXXXXXXXXXXXXX 
                                    BB BBBBBBBBBBBB BB BXXXXXXXXXXBBBB BBBBBBBBBBBB BB BXXXXXXXXXXXX XXXXXXXXXXBBBB BBBBBBBBBBBB BB BXXXXXXXXX XXXXXXXXXXBBBBBXX
                                    XXX XXXXXXXXX XXXXXX
                                        BB BBBBBBBBBBBB BB B
                                            XX XXXXXXXXXX XXXXXXXX XXXXXXXXXX gettext(u"Médaille d'or") 
                                        BBBB BBBBBBBBBBBB BB B
                                            XX XXXXXXXXXX XXXXXXXX XXXXXXXXXX gettext(u"Médaille d'argent") 
                                        BBBB BBBBBBBBBBBB BB B
                                            XX XXXXXXXXXX XXXXXXXX XXXXXXXXXX gettext(u'Médaille de bronze') 
                                        BBBBB
                                    XXXXX
                                XXXXXX
                                XXXX XXXXXXXXXXXXXXXXXX
                                    XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXX
                                        BB BBBBBBBBBBBBBBBBBBBBBBBBBB
                                            XXXX XXXXXX XXXXXX 
                                                XXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXX XXXXXXXXXXXX
                                        BBBB
                                            XXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXX 
                                                XXXXXXXXXXXXX XXXXX XXXXXXX XXXXXXX
                                                XX XXXXXXXXXX XXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXX
                                            XXXXXX
                                        BBBBB
                                        XXXXX
                                            XXX XXXXXXXXXXXXXXXXX XXXXXXXXXXX
                                            BB BBBBBBBBBBBBBBBBBBBBBBBBB
                                                XX XXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX
                                            BBBBB
                                        XXXXXX
                                    XXXXXX
                                    XXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
                                        XXX XXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                                             gettext(u'Score final') 
                                            XXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                                        XXXXX
                                        BB BBBBBBBBBBBBBB
                                            XXX XXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                                                 gettext(u'Ex-aequo') 
                                                XXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXX gettext(u'Oui') XXXXXXX
                                            XXXXX
                                        BBBBB
                                    XXXXX
                                XXXXXX
                            XXXXXX
                        XXXXXX
                    BBBBB
                BBBBB
                    XXXX XXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXX
                            XX XXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXX gettext(u'Aucun médaillé disponible.') 
                        XXXXXX
                    XXXXXX
                BBBBBB
            XXXXXX
        XXXXXX
    XXXXXX
XXXXXX

XXXX XXXXX XX XXXXXXX XXX
XXXX XXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX
                XXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXX gettext(u'Partager le podium') 
                XXXXX
                XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXX
            XXXX XXXXXXXXXXXXXXXXXXX
                XXX gettext(u'Partagez ce podium sur les réseaux sociaux ou par e-mail.') XXXX
                
                XXXX XXX XX XXXXXXX XXX
                XXXX XXXXXXXXXXXXX
                    XXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX gettext(u'Lien de partage') XXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXX
                        XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX 
                               XXXXXXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBB BBBBBBBBBBBX 
                               XXXXXXXXX
                        XXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                            XX XXXXXXXXXX XXXXXXXXXXXXX
                        XXXXXXXXX
                    XXXXXX
                    XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                XXXXXX
                
                XXXX XXXXXXX XX XXXXXXX XXX
                XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXX
                    XX XXXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
                        XX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXX
                    XXXX
                    XX XXXXXXXX XXXXXXXXXX XXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
                        XX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX
                    XXXX
                    XX XXXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
                        XX XXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXX
                    XXXX
                    XX XXXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
                        XX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXX
                    XXXX
                XXXXXX
                
                XXXX XXXXXXXXXXXXXX XXX
                XXXX XXXXXXXXXXXXX XXXXXXX
                    XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                        XX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX gettext(u"Télécharger l'image du podium") 
                    XXXXXXXXX
                XXXXXX
            XXXXXX
        XXXXXX
    XXXXXX
XXXXXX

BBBBBBBB

BBBBB BBBBBBBB
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X
        XX XXXXXXXX XXXX XXXXXX XX XXXX
        XXXXX XXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        
        XX XXXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X
                XXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
                    XXXXXXXXXXXXXXXXXXXXXX X X gettext(u'Lien copié !') XX
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    
                    XXXXXXXXXXXXXXXXXXXXX X
                        XXXXXXXXXXXXXXXXXXXXXX X XXX
                    XX XXXXXX
                XX XXXXXXXXXX X
                    XXXXXXXXXXXXXXXXXXXXXX X X gettext(u'Échec de la copie') XX
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXX
            XXX
        X
        
        XX XXXX XX XXXXXXX
        XXXXX XXXXXXX X XXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXX
        XXXXX XXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        
        XX XXXXXXX XXX XXXXXX
        XXXXX XXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XX XXXXXXXXXXXX X
            XXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        X
        
        XX XXXXXXX XXX XXXXXXX
        XXXXX XXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XX XXXXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        X
        
        XX XXXXXXX XXX XXXXXXXX
        XXXXX XXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XX XXXXXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        X
        
        XX XXXXXXX XXX XXXXXXXX
        XXXXX XXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XX XXXXXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
        X
        
        XX XXXXXXXXXXXXXX XX XXXXXX
        XXXXX XXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XX XXXXXXXXXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X
                XXXXX XXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                
                XX XXXXXXXXXXXXXXXXX X
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXX X
                        XXXXXXXXXXXXXXXX XXXXXXXXXX
                        XXXXXX X
                    XXXXXXXXXXXXXXXXXXXXXXXX X
                        XXXXX XXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXXXXXXXXX X XXXXXXXXXXXXXX
                        XXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXXXXXXXXX
                    XXX
                X
            XXX
        X
    XXX
XXXXXXXXX
BBBBBBBB