BBBBBBB BBBBBBBBBBB
BBBB BBBBBB
BBBB BBBB

BBBBB BBBBB gettext(u'Réorganiser les performances')  X BBBBBBBB

BBBBB BBBBBBB
XXXX XXXXXXXXXXXXXXXX XXXXXX
    XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXX
        XXX XXXXXXXXXXX gettext(u'Réorganiser les performances') XXXXX
        XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBB BBBBBBBBBBBX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
            XX XXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX gettext(u'Retour aux performances') 
        XXXX
    XXXXXX

    XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXX XXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX
                    XXX XXXXXXXXX XXXXXX X XXXXX
                XXXXXX
                XXXX XXXXXXXXXXXXXXXXXX
                    XX XXXXXXXXXXXX XXXXXXXXXXXX
                        XX XXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXX
                         gettext(u'Glissez et déposez les performances pour modifier leur ordre de passage.') 
                    XXXX

                    XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXX
                        BBB BBBBBBBBBBB BB BBBBBBBBBBBB
                        XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
                            XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                                XXXX XXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXX
                                    XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                                XXXXXX
                                XXXXX
                                    XXXXXXXXXXXXXXXXX
                                    BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBB
                                    XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
                                    BBBBB
                                XXXXXX
                            XXXXXX
                            XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                                XXXXX XXXXXXXXXXXX BB BBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBXXXXXXXXXXBBBB BBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBXXXXXXXXXXBBBB BBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBXXXXXXXXXBBBBXXXXXXXXXXXXBBBBB XXXXXX
                                    
                                XXXXXXX
                                XXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                            XXXXXX
                        XXXXXX
                        BBBBB
                        XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX
                            XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
                             gettext(u'Aucune performance à réorganiser.') 
                        XXXXXX
                        BBBBBB
                    XXXXXX

                    XXXX XXXXXXXXXXXXX XXXXXXX
                        XXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX
                            XX XXXXXXXXXX XXXXXXX XXXXXXXXXX gettext(u"Enregistrer l'ordre") 
                        XXXXXXXXX
                        XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBB BBBBBBBBBBBX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                             gettext(u'Annuler') 
                        XXXX
                    XXXXXX
                XXXXXX
            XXXXXX
        XXXXXX
    XXXXXX
XXXXXX
BBBBBBBB

BBBBB BBBBBBBB
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X
        XX XXXXXXXXXXX XXXXXXXXXXX
        XXX XX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXX XXXXXXXX X XXXXXXXXXXXXXXXXXXX X
            XXXXXXX XXXXXXXXXXXXXXX
            XXXXXXXXXX XXXX
            XXXXXX XXXXXXXXXXXXX X
                XX XXXXXX X XXXX XXX XXXXXX XX XXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXX
            X
        XXX

        XX XXXXXX X XXXX XXX XXXXXXXXXXX XXXXXXX
        XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX X
            XXXXX XXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXX XXXXXX XX X
                XXXXX XXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXX X XXXXX X XX
            XXX
        X

        XX XXXXXXXXXXX XXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X
            XXXXX XXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
            XXXXX XXXXXXXXXXXXXXXXX X XXX

            XXXXXXXXXXXXXXXXXXXX XXXXXX XX X
                XXXXXXXXXXXXXXXXXXXXXXXX
                    XXX XXXXXXXXXXXXXXXX
                    XXXXXX XXXXX X X
                XXX
            XXX

            XX XXXXXXX XXX XXXXXXX XX XXXXXXX
            XXXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBB BBBBBBBBBBBXX X
                XXXXXXX XXXXXXX
                XXXXXXXX X
                    XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXX XX
                XX
                XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XX
            XX
            XXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXX
            XXXXXXXXXX XX X
                XX XXXXXXXXXXXX XXX XXXXXXXXXX X
                    XX XXXXXXXXX XXXX XX XXXX XX XXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXXXX X XBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBB BBBBBBBBBBBXX
                X XXXX X
                    XXXXXXX gettext(u'Une erreur est survenue lors de la sauvegarde.') XXX
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                X
            XX
            XXXXXXXXXXXX XX X
                XXXXXXX gettext(u'Une erreur est survenue lors de la sauvegarde.') XXX
                XXXXXXXXXXXXXXXXXXXXX
            XXX
        XXX
    XXX
XXXXXXXXX
BBBBBBBB