from django.urls import path
from apps.competitions.views import combat

app_name = 'combat'

urlpatterns = [
    path('', combat.liste_combats, name='liste_combats'),
    path('configurations/', combat.liste_configurations, name='liste_configurations'),
    path('configurations/creer/', combat.creer_configuration, name='creer_configuration'),
    path('configurations/<int:config_id>/modifier/', combat.modifier_configuration, name='modifier_configuration'),
    path('configurations/<int:config_id>/supprimer/', combat.supprimer_configuration, name='supprimer_configuration'),
    path('equipes/', combat.liste_equipes, name='liste_equipes'),
    path('equipes/competition/<int:competition_id>/', combat.liste_equipes, name='liste_equipes_competition'),
    path('equipes/creer/', combat.creer_equipe, name='creer_equipe'),
    path('equipes/creer/competition/<int:competition_id>/', combat.creer_equipe, name='creer_equipe_competition'),
    path('equipes/<int:equipe_id>/', combat.detail_equipe, name='detail_equipe'),
    path('equipes/<int:equipe_id>/modifier/', combat.modifier_equipe, name='modifier_equipe'),
    path('equipes/<int:equipe_id>/supprimer/', combat.supprimer_equipe, name='supprimer_equipe'),
    path('equipes/<int:equipe_id>/ajouter-membre/', combat.ajouter_membre_equipe, name='ajouter_membre_equipe'),
    path('membres/<int:membre_id>/modifier/', combat.modifier_membre_equipe, name='modifier_membre_equipe'),
    path('membres/<int:membre_id>/supprimer/', combat.supprimer_membre_equipe, name='supprimer_membre_equipe'),
    path('poules/<int:competition_id>/', combat.liste_poules, name='liste_poules'),
    path('poules/<int:competition_id>/creer/', combat.creer_poule, name='creer_poule'),
    path('poules/<int:poule_id>/', combat.detail_poule, name='detail_poule'),
    path('poules/<int:poule_id>/modifier/', combat.modifier_poule, name='modifier_poule'),
    path('poules/<int:poule_id>/supprimer/', combat.supprimer_poule, name='supprimer_poule'),
    path('poules/<int:competition_id>/generer/', combat.generer_poules, name='generer_poules'),
    path('combats/', combat.liste_combats, name='liste_combats'),
    path('combats/competition/<int:competition_id>/', combat.liste_combats, name='liste_combats_competition'),
    path('combats/creer/', combat.creer_combat, name='creer_combat'),
    path('combats/<int:combat_id>/', combat.detail_combat, name='detail_combat'),
    path('combats/<int:combat_id>/modifier/', combat.modifier_combat, name='modifier_combat'),
    path('combats/<int:combat_id>/supprimer/', combat.supprimer_combat, name='supprimer_combat'),
    path('combats/<int:combat_id>/demarrer/', combat.demarrer_combat, name='demarrer_combat'),
    path('combats/<int:combat_id>/terminer/', combat.terminer_combat, name='terminer_combat'),
    path('combats/<int:combat_id>/annuler/', combat.annuler_combat, name='annuler_combat'),
    path('combats/<int:combat_id>/interface/', combat.interface_combat, name='interface_combat'),
    path('combats/<int:combat_id>/monitor/', combat.monitor_match, name='monitor_match'),
    path('combats/<int:combat_id>/affichage/', combat.affichage_combat, name='affichage_combat'),
    path('combats/<int:combat_id>/ajouter-action/', combat.ajouter_action, name='ajouter_action'),
    path('actions/<int:action_id>/annuler/', combat.annuler_action, name='annuler_action'),
    path('combats/<int:combat_id>/api-statut/', combat.api_statut_combat, name='api_statut_combat'),
    path('combats/<int:combat_id>/api-actions/', combat.api_liste_actions, name='api_liste_actions'),
] 
