XXXXXXXXX XXXXX
BBBB BBBB
BBBB BBBBBB
XXXXX XXXXXXXX
XXXXXX
    XXXXX XXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
    XXXXXXXBBBBB BBBBBXXXXXXXXXXXBBBBBBBBXXXXXXXX
    
    XXXX XXXXXXXXX XXX XXX
    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
    XXXX XXXX XXXXXXX XXX
    XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    
    BBBBB BBBBBBBBBBBBBBBBB
XXXXXXX
XXXXXX
    XXXX XXXXXX XXX
    XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXX XXXXXX
        XXXX XXXXXXXXXXXXXXXXXX
            XX XXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBXX
                XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXX
            XXXX
            XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXX
            XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
                XXX XXXXXXXXXXXXXXXXX XXXXXXXXX
                    XXX XXXXXXXXXXXXXXXXX
                        XX XXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBXX
                            XX XXXXXXXXXX XXXXXXX XXXXXXXXXX  gettext(u'Accueil') 
                        XXXX
                    XXXXX
                    XXXX XXXXXXX XXXXXXXX XXXXX XX XXXXXXXXXX XX XXXXXXXXXX XXX
                XXXXX
                XXX XXXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXX XXXXXXXX XXX
                    XXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXX
                        XX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX 
                           XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                            XX XXXXXXXXXX XXXXXXXX XXXXXXXXXX
                            BBB BBBBBBBBBB BBBBBBBBB BB BBBBBBBBB
                                BB BBBBBBBBB BB BBBBBBBBBBBBB
                                    
                                BBBBB
                            BBBBBB
                        XXXX
                        XXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                            BBB BBBBBBBBBB BBBBBBBBB BB BBBBBBBBB
                                XXXX
                                    XX XXXXXXXX 
                                       XXXXXXXXXXXXXXXXXXXX BB BBBBBBBBB BB BBBBBBBBBBBBBXXXXXXBBBBBX
                                       XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX
                                        
                                    XXXX
                                XXXXX
                            BBBBBB
                            
                            XXXX XXXXXXXXXX XXXXX XXXX XX XXXXXXXXXX XX XXXXXX XXX
                            XXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXBBB BBBBBBBBBBBBBBX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                                BBBBBBBBBB
                                XXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXX
                                XXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXX
                            XXXXXXX
                        XXXXX
                    XXXXX
                    
                    XXXX XXXX XXXX XXX
                    BB BBBBBBBBBBBBBBBBBBBBB
                        XXX XXXXXXXXXXXXXXX XXXXXXXXXX
                            XX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX 
                               XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                                XX XXXXXXXXXX XXXXXXX XXXXXXXXXX 
                            XXXX
                            XXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                XXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBXX
                                    XX XXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX gettext(u'Tableau de bord') 
                                XXXXXXXXX
                                XXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBXX
                                    XX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXX gettext(u'Mon profil') 
                                XXXXXXXXX
                                BB BBBBBBBBBBBBB
                                XXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBXX
                                    XX XXXXXXXXXX XXXXXXX XXXXXXXXXX gettext(u'Administration') 
                                XXXXXXXXX
                                BBBBB
                                XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                XXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBXX
                                    XX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXX gettext(u'Déconnexion') 
                                XXXXXXXXX
                            XXXXX
                        XXXXX
                    BBBB
                        XXX XXXXXXXXXXXXXXXXX
                            XX XXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBXX gettext(u'Connexion') XXXX
                        XXXXX
                    BBBBB
                XXXXX
            XXXXXX
        XXXXXX
    XXXXXX

    XXXX XXXXXXX XXXXXXX XXX
    BB BBBBBBBB
        XXXX XXXXXXXXXXXXXXXX XXXXXX
            BBB BBBBBBB BB BBBBBBBB
                XXXX XXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXX XXXX XXXXXX
                    
                    XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXX
            BBBBBB
        XXXXXX
    BBBBB

    XXXX XXXXXXX XXX
    BBBBB BBBBBBBBBBBBBBB

    XXXX XXXXXX XXX
    XXXXXXX XXXXXXXXXXXXXX XXXXXXXXXX XXXX XXXXXX
        XXXX XXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXX
                    XXXXXXXXX BBB BBB XXXXXXXXXXXX  gettext(u'Tous droits réservés.') XXXX
                XXXXXX
                XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX
                    XXX gettext(u"Plateforme de gestion de compétitions d'arts martiaux") XXXX
                XXXXXX
            XXXXXX
        XXXXXX
    XXXXXXXXX

    XXXX XXXXXXXXX XXXXXX XXXX XXXXXX XXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    
    XXXX XXXXXX XXXX XX XXXXXXXXXX XX XXXXXX XXX
    XXXXXXXX
        XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXX X
            XXXXXXXXXXXXXXXXXXXXXXX
            XXXXX XXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXX XXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            
            XXXXXXXXXXXXXXXXXXX X XXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXX
        X
    XXXXXXXXX
    
    BBBBB BBBBBBBBBBBBBBBB
XXXXXXX
XXXXXXX