# Generated by Django 4.2.11 on 2024-05-15 10:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name="Nom de l'organisation")),
                ('slug', models.SlugField(max_length=50, unique=True, verbose_name='Identifiant')),
                ('schema_name', models.CharField(max_length=63, unique=True, verbose_name='Nom du schéma PostgreSQL')),
                ('domain', models.CharField(help_text='Ex: club1.martialcomp.com', max_length=253, unique=True, verbose_name='Domaine principal')),
                ('continent', models.CharField(choices=[('africa', 'Afrique'), ('asia_se', 'Asie du Sud-Est'), ('asia_other', 'Asie (autres)'), ('south_america', 'Amérique du Sud'), ('central_america', 'Amérique Centrale'), ('europe_east', "Europe de l'Est"), ('europe_west', "Europe de l'Ouest"), ('north_america', 'Amérique du Nord'), ('oceania', 'Océanie'), ('middle_east', 'Moyen-Orient')], help_text='Détermine la grille tarifaire applicable', max_length=20, verbose_name='Continent')),
                ('country', models.CharField(max_length=2, verbose_name='Pays')),
                ('timezone', models.CharField(default='UTC', max_length=50, verbose_name='Fuseau horaire')),
                ('currency', models.CharField(default='EUR', max_length=3, verbose_name='Devise')),
                ('language', models.CharField(default='fr', max_length=10, verbose_name='Langue')),
                ('subscription_plan', models.CharField(choices=[('essentials', 'Dojo Essentials'), ('masters', "Master's Circle"), ('champion', 'Grand Champion Suite'), ('trial', 'Essai Gratuit')], default='trial', max_length=20, verbose_name="Plan d'abonnement")),
                ('subscription_start_date', models.DateTimeField(blank=True, null=True, verbose_name="Début d'abonnement")),
                ('subscription_end_date', models.DateTimeField(blank=True, null=True, verbose_name="Fin d'abonnement")),
                ('is_trial', models.BooleanField(default=True, verbose_name="En période d'essai")),
                ('trial_end_date', models.DateTimeField(blank=True, null=True, verbose_name="Fin de l'essai")),
                ('payment_provider', models.CharField(choices=[('stripe', 'Stripe'), ('stripe_connect', 'Stripe Connect'), ('paystack', 'Paystack'), ('mercado_pago', 'Mercado Pago'), ('alipay', 'Alipay'), ('paytm', 'Paytm'), ('custom', 'Custom Provider')], default='stripe', max_length=20, verbose_name='Fournisseur de paiement')),
                ('payment_config', models.JSONField(default=dict, help_text='Configuration spécifique au fournisseur de paiement (clés API, etc.)', verbose_name='Configuration paiement')),
                ('stripe_account_id', models.CharField(blank=True, help_text='Pour les organisations utilisant Stripe Connect', max_length=255, verbose_name='ID Compte Stripe Connect')),
                ('max_users', models.PositiveIntegerField(default=100, verbose_name="Nombre max d'utilisateurs")),
                ('max_disciplines', models.PositiveIntegerField(default=2, verbose_name='Nombre max de disciplines')),
                ('features_config', models.JSONField(default=dict, help_text='Fonctionnalités activées/désactivées selon le plan', verbose_name='Configuration des fonctionnalités')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('activated_at', models.DateTimeField(blank=True, null=True, verbose_name="Date d'activation")),
                ('deactivated_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de désactivation')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_tenants', to=settings.AUTH_USER_MODEL, verbose_name='Propriétaire')),
            ],
            options={
                'verbose_name': 'Tenant',
                'verbose_name_plural': 'Tenants',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TenantFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_code', models.CharField(help_text='Ex: advanced_reporting, api_access, mobile_app', max_length=50, verbose_name='Code de la fonctionnalité')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='Activé')),
                ('enabled_until', models.DateTimeField(blank=True, help_text='Pour les fonctionnalités temporaires', null=True, verbose_name="Activé jusqu'à")),
                ('metadata', models.JSONField(default=dict, help_text='Configuration spécifique à la fonctionnalité', verbose_name='Métadonnées')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_features', to='multitenant.tenant')),
            ],
            options={
                'verbose_name': 'Fonctionnalité tenant',
                'verbose_name_plural': 'Fonctionnalités tenant',
                'ordering': ['feature_code'],
                'unique_together': {('tenant', 'feature_code')},
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=253, unique=True, verbose_name='Domaine')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Domaine principal')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='multitenant.tenant')),
            ],
            options={
                'verbose_name': 'Domaine',
                'verbose_name_plural': 'Domaines',
                'ordering': ['-is_primary', 'domain'],
            },
        ),
        migrations.AddIndex(
            model_name='tenant',
            index=models.Index(fields=['domain'], name='multitenant_domain_a0ac80_idx'),
        ),
        migrations.AddIndex(
            model_name='tenant',
            index=models.Index(fields=['schema_name'], name='multitenant_schema__9f8a1d_idx'),
        ),
        migrations.AddIndex(
            model_name='tenant',
            index=models.Index(fields=['is_active', 'subscription_end_date'], name='multitenant_is_acti_c7c8a0_idx'),
        ),
    ]