# Generated by Django 5.1.4 on 2025-05-19 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('multitenant', '0003_paymentmethod_tenantpayment_tenantsubscription_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='primary_color',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='secondary_color',
        ),
    ]
