# Generated by Django 4.2.21 on 2025-07-31 11:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        ('competitions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('grades', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userclubrole',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='userclubrole',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='competitions.clubrole'),
        ),
        migrations.AddField(
            model_name='userclubrole',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trainingslot',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_slots', to='competitions.club', verbose_name='Club'),
        ),
        migrations.AddField(
            model_name='trainingslot',
            name='discipline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_slots', to='competitions.discipline', verbose_name='Discipline'),
        ),
        migrations.AddField(
            model_name='trainingslot',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_slots', to=settings.AUTH_USER_MODEL, verbose_name='Instructeur'),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='actual_instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Instructeur réel'),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='training_slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='competitions.trainingslot', verbose_name='Créneau'),
        ),
        migrations.AddField(
            model_name='trainingreservation',
            name='practitioner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_reservations', to='competitions.practitioner', verbose_name='Pratiquant'),
        ),
        migrations.AddField(
            model_name='trainingreservation',
            name='training_slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='competitions.trainingslot', verbose_name='Créneau'),
        ),
        migrations.AddField(
            model_name='trainingprogram',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_training_programs', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AddField(
            model_name='trainingprogram',
            name='disciplines',
            field=models.ManyToManyField(related_name='training_programs', to='competitions.discipline', verbose_name='Disciplines'),
        ),
        migrations.AddField(
            model_name='trainingmodule',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='competitions.trainingprogram', verbose_name='Programme'),
        ),
        migrations.AddField(
            model_name='trainingexercise',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='competitions.trainingmodule', verbose_name='Module'),
        ),
        migrations.AddField(
            model_name='technique',
            name='discipline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='techniques', to='competitions.discipline', verbose_name='Discipline'),
        ),
        migrations.AddField(
            model_name='technique',
            name='minimum_grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='required_techniques', to='grades.grade', verbose_name='Grade minimum requis'),
        ),
        migrations.AddField(
            model_name='technicalscoreresult',
            name='criterion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_results', to='competitions.scoringcriterion', verbose_name='Critère'),
        ),
        migrations.AddField(
            model_name='technicalscoreresult',
            name='judge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technical_score_results', to=settings.AUTH_USER_MODEL, verbose_name='Juge'),
        ),
        migrations.AddField(
            model_name='technicalscoreresult',
            name='performance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technical_scores', to='competitions.technicalperformanceresult', verbose_name='Performance'),
        ),
        migrations.AddField(
            model_name='technicalscore',
            name='criterion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technical_scores', to='competitions.scoringcriterion', verbose_name='Critère'),
        ),
        migrations.AddField(
            model_name='technicalscore',
            name='judge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technical_scores', to=settings.AUTH_USER_MODEL, verbose_name='Juge'),
        ),
        migrations.AddField(
            model_name='technicalscore',
            name='performance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='competitions.technicalperformance', verbose_name='Prestation'),
        ),
        migrations.AddField(
            model_name='technicalperformanceresult',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_results', to='competitions.competitioncategory', verbose_name='Catégorie'),
        ),
        migrations.AddField(
            model_name='technicalperformanceresult',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technical_performance_results', to='competitions.competition', verbose_name='Compétition'),
        ),
        migrations.AddField(
            model_name='technicalperformanceresult',
            name='practitioner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technical_performance_results', to='competitions.practitioner', verbose_name='Pratiquant'),
        ),
        migrations.AddField(
            model_name='technicalperformance',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technical_performances', to='competitions.competitioncategory', verbose_name='Catégorie'),
        ),
        migrations.AddField(
            model_name='technicalperformance',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technical_performances', to='competitions.competition', verbose_name='Compétition'),
        ),
        migrations.AddField(
            model_name='technicalperformance',
            name='practitioner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technical_performances', to='competitions.practitioner', verbose_name='Pratiquant'),
        ),
        migrations.AddField(
            model_name='teachingschedule',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competitions.club', verbose_name='Club'),
        ),
        migrations.AddField(
            model_name='teachingschedule',
            name='coach_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_schedules', to='competitions.coachprofile', verbose_name='Profil coach'),
        ),
        migrations.AddField(
            model_name='teachingschedule',
            name='discipline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competitions.discipline', verbose_name='Discipline'),
        ),
        migrations.AddField(
            model_name='tatamischedule',
            name='competition_schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tatami_schedules', to='competitions.competitionschedule', verbose_name='Planning de compétition'),
        ),
        migrations.AddField(
            model_name='tatamischedule',
            name='responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_for_tatamis', to=settings.AUTH_USER_MODEL, verbose_name='Responsable'),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='participant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='survey_responses', to=settings.AUTH_USER_MODEL, verbose_name='Participant'),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='competitions.eventsurvey', verbose_name='Sondage'),
        ),
        migrations.AddField(
            model_name='surveyquestion',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='competitions.eventsurvey', verbose_name='Sondage'),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL, verbose_name='Assigné Ã\xa0'),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_tickets', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AddField(
            model_name='supportmessage',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Expéditeur'),
        ),
        migrations.AddField(
            model_name='supportmessage',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='competitions.supportticket', verbose_name='Ticket'),
        ),
        migrations.AddField(
            model_name='style',
            name='discipline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='styles', to='competitions.discipline', verbose_name='Discipline'),
        ),
        migrations.AddField(
            model_name='scoringcriterion',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scoring_criteria', to='competitions.competitioncategory'),
        ),
        migrations.AddField(
            model_name='scoringconfiguration',
            name='category',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scoring_configuration', to='competitions.competitioncategory', verbose_name='Catégorie'),
        ),
        migrations.AddField(
            model_name='score',
            name='criterion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_scores', to='competitions.scoringcriterion'),
        ),
        migrations.AddField(
            model_name='score',
            name='judge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='competitions.judge'),
        ),
        migrations.AddField(
            model_name='score',
            name='performance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='competitions.performance'),
        ),
        migrations.AddField(
            model_name='schedulechange',
            name='category_schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='changes', to='competitions.categoryschedule', verbose_name='Planning de catégorie'),
        ),
        migrations.AddField(
            model_name='schedulechange',
            name='changed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_changes', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par'),
        ),
        migrations.AddField(
            model_name='schedulechange',
            name='competition_schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='competitions.competitionschedule', verbose_name='Planning'),
        ),
    ]
