# Generated by Django 4.2.21 on 2025-07-31 11:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finances', '0001_initial'),
        ('organizations', '0001_initial'),
        ('competitions', '0002_initial'),
        ('family_management', '0001_initial'),
        ('grades', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='referraluse',
            name='payment_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referral_uses', to='finances.transaction', verbose_name='Transaction de paiement'),
        ),
        migrations.AddField(
            model_name='referraluse',
            name='practitioner_created',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referral_signups', to='competitions.practitioner', verbose_name='Pratiquant créé'),
        ),
        migrations.AddField(
            model_name='referraluse',
            name='referral_link',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uses', to='competitions.referrallink', verbose_name='Lien de parrainage'),
        ),
        migrations.AddField(
            model_name='referraluse',
            name='referred_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_signups', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur parrainé'),
        ),
        migrations.AddField(
            model_name='referrallink',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referral_links', to='competitions.club', verbose_name='Club'),
        ),
        migrations.AddField(
            model_name='referrallink',
            name='federation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referral_links', to='competitions.federation', verbose_name='Fédération'),
        ),
        migrations.AddField(
            model_name='referrallink',
            name='referrer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_links', to=settings.AUTH_USER_MODEL, verbose_name='Parrain'),
        ),
        migrations.AddField(
            model_name='rankingentry',
            name='performance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ranking_entries', to='competitions.technicalperformanceresult', verbose_name='Performance'),
        ),
        migrations.AddField(
            model_name='rankingentry',
            name='practitioner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranking_entries', to='competitions.practitioner', verbose_name='Pratiquant'),
        ),
        migrations.AddField(
            model_name='rankingentry',
            name='ranking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='competitions.categoryranking', verbose_name='Classement'),
        ),
        migrations.AddField(
            model_name='questionresponse',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='competitions.surveyquestion', verbose_name='Question'),
        ),
        migrations.AddField(
            model_name='questionresponse',
            name='response',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_responses', to='competitions.surveyresponse', verbose_name='Réponse au sondage'),
        ),
        migrations.AddField(
            model_name='qrcodescan',
            name='competition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qr_scans', to='competitions.competition', verbose_name='Compétition'),
        ),
        migrations.AddField(
            model_name='qrcodescan',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qr_scans', to='competitions.event', verbose_name='Ã‰vénement'),
        ),
        migrations.AddField(
            model_name='qrcodescan',
            name='qr_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='competitions.practitionerqrcode', verbose_name='QR Code'),
        ),
        migrations.AddField(
            model_name='qrcodescan',
            name='scanned_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qr_scans_performed', to=settings.AUTH_USER_MODEL, verbose_name='Scanné par'),
        ),
        migrations.AddField(
            model_name='qrcodescan',
            name='training_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qr_scans', to='competitions.trainingsession', verbose_name="Session d'entraÃ®nement"),
        ),
        migrations.AddField(
            model_name='programenrollment',
            name='practitioner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_enrollments', to='competitions.practitioner', verbose_name='Pratiquant'),
        ),
        migrations.AddField(
            model_name='programenrollment',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='competitions.trainingprogram', verbose_name='Programme'),
        ),
        migrations.AddField(
            model_name='practitionerqualification',
            name='certified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certified_qualifications', to=settings.AUTH_USER_MODEL, verbose_name='Certifié par'),
        ),
        migrations.AddField(
            model_name='practitionerqualification',
            name='discipline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualifications', to='competitions.discipline', verbose_name='Discipline'),
        ),
        migrations.AddField(
            model_name='practitionerqualification',
            name='practitioner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practitioner_qualifications', to='competitions.practitioner'),
        ),
        migrations.AddField(
            model_name='practitionerqrcode',
            name='practitioner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qr_code', to='competitions.practitioner', verbose_name='Pratiquant'),
        ),
        migrations.AddField(
            model_name='practitionerprogress',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practitioner_progress', to='competitions.trainingexercise', verbose_name='Exercice'),
        ),
        migrations.AddField(
            model_name='practitionerprogress',
            name='practitioner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_progress', to='competitions.practitioner', verbose_name='Pratiquant'),
        ),
        migrations.AddField(
            model_name='practitionerdiscipline',
            name='discipline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discipline_practitioners', to='competitions.discipline'),
        ),
        migrations.AddField(
            model_name='practitionerdiscipline',
            name='practitioner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practitioner_disciplines', to='competitions.practitioner'),
        ),
        migrations.AddField(
            model_name='practitionerdiscipline',
            name='reference_instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to=settings.AUTH_USER_MODEL, verbose_name='Instructeur référent'),
        ),
        migrations.AddField(
            model_name='practitioner',
            name='disciplines',
            field=models.ManyToManyField(blank=True, related_name='practitioners', to='competitions.discipline', verbose_name='Disciplines pratiquées'),
        ),
        migrations.AddField(
            model_name='practitioner',
            name='family',
            field=models.ForeignKey(blank=True, help_text='Famille Ã\xa0 laquelle appartient ce pratiquant', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='family_practitioners', to='family_management.family', verbose_name='Famille'),
        ),
        migrations.AddField(
            model_name='practitioner',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='practitioner_current_grades', to='grades.grade', verbose_name='Grade actuel'),
        ),
        migrations.AddField(
            model_name='practitioner',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='practitioners', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='practitioner',
            name='primary_discipline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_practitioners', to='competitions.discipline', verbose_name='Discipline principale'),
        ),
        migrations.AddField(
            model_name='practitioner',
            name='secondary_disciplines',
            field=models.ManyToManyField(blank=True, related_name='secondary_practitioners', to='competitions.discipline', verbose_name='Disciplines secondaires'),
        ),
        migrations.AddField(
            model_name='practitioner',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='practitioners', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='poule',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poules', to='competitions.competition', verbose_name='Compétition'),
        ),
        migrations.AddField(
            model_name='poule',
            name='equipes',
            field=models.ManyToManyField(blank=True, related_name='poules', to='competitions.equipe', verbose_name='Ã‰quipes'),
        ),
        migrations.AddField(
            model_name='poule',
            name='pratiquants',
            field=models.ManyToManyField(blank=True, related_name='poules_individuelles', to='competitions.practitioner', verbose_name='Pratiquants individuels'),
        ),
        migrations.AddField(
            model_name='pollresponse',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='competitions.polloption', verbose_name='Option'),
        ),
        migrations.AddField(
            model_name='pollresponse',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poll_responses', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AddField(
            model_name='pollquestionresponse',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='competitions.pollquestion', verbose_name='Question'),
        ),
        migrations.AddField(
            model_name='pollquestionresponse',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poll_question_responses', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AddField(
            model_name='pollquestion',
            name='poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_questions', to='competitions.eventpoll', verbose_name='Sondage'),
        ),
        migrations.AddField(
            model_name='polloption',
            name='poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='competitions.eventpoll', verbose_name='Sondage'),
        ),
        migrations.AddField(
            model_name='personalgoal',
            name='practitioner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_goals', to='competitions.practitioner', verbose_name='Pratiquant'),
        ),
        migrations.AddField(
            model_name='performanceresult',
            name='performance',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='competitions.technicalperformanceresult', verbose_name='Performance'),
        ),
        migrations.AddField(
            model_name='performanceresult',
            name='validated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_results', to=settings.AUTH_USER_MODEL, verbose_name='Validé par'),
        ),
        migrations.AddField(
            model_name='performance',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performances', to='competitions.competitioncategory'),
        ),
        migrations.AddField(
            model_name='performance',
            name='practitioner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performances', to='competitions.practitioner'),
        ),
        migrations.AddField(
            model_name='participantcategoryregistration',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competitions.competitioncategory'),
        ),
        migrations.AddField(
            model_name='participantcategoryregistration',
            name='competition_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competitions.competitiontype'),
        ),
        migrations.AddField(
            model_name='participantcategoryregistration',
            name='registration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_registrations', to='competitions.competitionregistration'),
        ),
        migrations.AddField(
            model_name='organizationtemplate',
            name='organization',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='template', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='organizationqrcodescan',
            name='payment_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qr_scans', to='finances.transaction', verbose_name='Transaction de paiement'),
        ),
        migrations.AddField(
            model_name='organizationqrcodescan',
            name='practitioner_created',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qr_registrations', to='competitions.practitioner', verbose_name='Pratiquant créé'),
        ),
        migrations.AddField(
            model_name='organizationqrcodescan',
            name='qr_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='competitions.organizationqrcode', verbose_name='Code QR'),
        ),
        migrations.AddField(
            model_name='organizationqrcodescan',
            name='scanned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organization_qr_scans', to=settings.AUTH_USER_MODEL, verbose_name='Scanné par'),
        ),
        migrations.AddField(
            model_name='organizationqrcodescan',
            name='user_created',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qr_registrations', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur créé'),
        ),
        migrations.AddField(
            model_name='organizationqrcode',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qr_codes', to='competitions.club', verbose_name='Club'),
        ),
        migrations.AddField(
            model_name='organizationqrcode',
            name='coach_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qr_codes', to='competitions.coachprofile', verbose_name='Coach'),
        ),
        migrations.AddField(
            model_name='organizationqrcode',
            name='federation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qr_codes', to='competitions.federation', verbose_name='Fédération'),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='messagetemplate',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_message_templates', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AddField(
            model_name='messagetemplate',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_templates', to='organizations.organization', verbose_name='Organisation'),
        ),
        migrations.AddField(
            model_name='messageread',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_by', to='competitions.message', verbose_name='Message'),
        ),
        migrations.AddField(
            model_name='messageread',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AddField(
            model_name='messagereaction',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='competitions.message', verbose_name='Message'),
        ),
        migrations.AddField(
            model_name='messagereaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AddField(
            model_name='message',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='competitions.conversation', verbose_name='Conversation'),
        ),
        migrations.AddField(
            model_name='message',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='competitions.message', verbose_name='Réponse Ã\xa0'),
        ),
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_messages', to=settings.AUTH_USER_MODEL, verbose_name='Expéditeur'),
        ),
        migrations.AddField(
            model_name='membreequipe',
            name='equipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='competitions.equipe', verbose_name='Ã‰quipe'),
        ),
        migrations.AddField(
            model_name='membreequipe',
            name='pratiquant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipe_memberships', to='competitions.practitioner', verbose_name='Pratiquant'),
        ),
        migrations.AddField(
            model_name='membership',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_memberships', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AddField(
            model_name='membership',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='member_subscriptions', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='membership',
            name='practitioner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='competitions.practitioner'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='practitioner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medical_record', to='competitions.practitioner'),
        ),
        migrations.AddField(
            model_name='medicalcertificate',
            name='practitioner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_certificates', to='competitions.practitioner'),
        ),
        migrations.AddField(
            model_name='matchtimeslot',
            name='category_schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='competitions.categoryschedule', verbose_name='Planning de catégorie'),
        ),
        migrations.AddField(
            model_name='matchtimeslot',
            name='match',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='time_slot', to='competitions.match', verbose_name='Match'),
        ),
        migrations.AddField(
            model_name='match',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='competitions.competition'),
        ),
        migrations.AddField(
            model_name='match',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='matches', to='competitions.practitioner'),
        ),
        migrations.AddField(
            model_name='license',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issued_licenses', to='organizations.organization', verbose_name='Fédération'),
        ),
        migrations.AddField(
            model_name='license',
            name='practitioner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licenses', to='competitions.practitioner'),
        ),
        migrations.AddField(
            model_name='judgetrainingregistration',
            name='judge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_registrations', to='competitions.judge'),
        ),
        migrations.AddField(
            model_name='judgetrainingregistration',
            name='training',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='competitions.judgetraining'),
        ),
        migrations.AddField(
            model_name='judgetraining',
            name='disciplines',
            field=models.ManyToManyField(related_name='judge_trainings', to='competitions.discipline', verbose_name='Disciplines'),
        ),
        migrations.AddField(
            model_name='judgetraining',
            name='federation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='judge_trainings', to='competitions.federation', verbose_name='Fédération'),
        ),
        migrations.AddField(
            model_name='judgetraining',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taught_trainings', to=settings.AUTH_USER_MODEL, verbose_name='Formateur'),
        ),
        migrations.AddField(
            model_name='judgetechnicalapplication',
            name='disciplines',
            field=models.ManyToManyField(related_name='judge_technical_applications', to='competitions.discipline', verbose_name='Disciplines'),
        ),
        migrations.AddField(
            model_name='judgetechnicalapplication',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_judge_applications', to=settings.AUTH_USER_MODEL, verbose_name='Examiné par'),
        ),
        migrations.AddField(
            model_name='judgetechnicalapplication',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technical_judge_applications', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AddField(
            model_name='judgesubmissionstatusresult',
            name='judge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submission_status_results', to=settings.AUTH_USER_MODEL, verbose_name='Juge'),
        ),
        migrations.AddField(
            model_name='judgesubmissionstatusresult',
            name='performance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submission_statuses', to='competitions.technicalperformanceresult', verbose_name='Performance'),
        ),
        migrations.AddField(
            model_name='judgesubmissionstatus',
            name='judge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competitions.judge'),
        ),
        migrations.AddField(
            model_name='judgesubmissionstatus',
            name='performance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competitions.performance'),
        ),
        migrations.AddField(
            model_name='judgesettings',
            name='judge',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='competitions.judge'),
        ),
        migrations.AddField(
            model_name='judgequalification',
            name='discipline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='judge_qualifications', to='competitions.discipline', verbose_name='Discipline'),
        ),
        migrations.AddField(
            model_name='judgequalification',
            name='issuing_organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_qualifications', to='organizations.organization', verbose_name='Fédération émettrice'),
        ),
        migrations.AddField(
            model_name='judgequalification',
            name='practitioner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualifications', to='competitions.practitioner', verbose_name='Pratiquant'),
        ),
        migrations.AddField(
            model_name='judgecompetitionassignment',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competition_judge_assignments', to='competitions.competitioncategory'),
        ),
        migrations.AddField(
            model_name='judgecompetitionassignment',
            name='registration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='competitions.competitionregistration'),
        ),
        migrations.AddField(
            model_name='judgecertification',
            name='discipline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='competitions.discipline', verbose_name='Discipline'),
        ),
        migrations.AddField(
            model_name='judgecertification',
            name='examiner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='examiner_certifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='judgecertification',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='judge_certifications', to='organizations.organization', verbose_name='Organisation'),
        ),
        migrations.AddField(
            model_name='judgeassignment',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='judge_assignments_made', to=settings.AUTH_USER_MODEL, verbose_name='Assigné par'),
        ),
        migrations.AddField(
            model_name='judgeassignment',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='judge_assignments', to='competitions.competitioncategory', verbose_name='Catégorie'),
        ),
        migrations.AddField(
            model_name='judgeassignment',
            name='chief_judge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chief_judge_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Juge en chef'),
        ),
        migrations.AddField(
            model_name='judgeassignment',
            name='registration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='judge_assignments', to='competitions.competitionregistration', verbose_name='Inscription'),
        ),
        migrations.AddField(
            model_name='judgeassignment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='judge_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AddField(
            model_name='judgeapplication',
            name='disciplines',
            field=models.ManyToManyField(related_name='judge_applications', to='competitions.discipline'),
        ),
        migrations.AddField(
            model_name='judgeapplication',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='judgeapplication',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='judge',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certified_judges', to='organizations.organization', verbose_name='Fédération certifiante'),
        ),
        migrations.AddField(
            model_name='judge',
            name='practitioner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='judge', to='competitions.practitioner', verbose_name='Pratiquant'),
        ),
        migrations.AddField(
            model_name='judge',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='judge_profile', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AddField(
            model_name='federationadministrator',
            name='federation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='administrators', to='competitions.federation', verbose_name='Fédération'),
        ),
        migrations.AddField(
            model_name='federationadministrator',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='federation_administrators', to='organizations.organization', verbose_name='Organisation'),
        ),
        migrations.AddField(
            model_name='federationadministrator',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='federation_admin_roles', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AddField(
            model_name='federation',
            name='disciplines',
            field=models.ManyToManyField(blank=True, related_name='federation_disciplines', to='competitions.discipline', verbose_name='Disciplines'),
        ),
        migrations.AddField(
            model_name='federation',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legacy_federations', to='organizations.organization', verbose_name='Organisation associée'),
        ),
        migrations.AddField(
            model_name='federation',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_federations', to=settings.AUTH_USER_MODEL, verbose_name='Propriétaire (déprécié)'),
        ),
        migrations.AddField(
            model_name='eventsurvey',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_surveys', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AddField(
            model_name='eventsurvey',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surveys', to='competitions.event', verbose_name='Ã‰vénement'),
        ),
        migrations.AddField(
            model_name='eventstatistics',
            name='event',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='competitions.event', verbose_name='Ã‰vénement'),
        ),
        migrations.AddField(
            model_name='eventstatistics',
            name='poll',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='competitions.eventpoll', verbose_name='Sondage'),
        ),
        migrations.AddField(
            model_name='eventreminder',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_reminders', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AddField(
            model_name='eventreminder',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='competitions.event', verbose_name='Ã‰vénement'),
        ),
        migrations.AddField(
            model_name='eventreminder',
            name='recipients',
            field=models.ManyToManyField(blank=True, help_text='Destinataires spécifiques (vide = tous les participants)', related_name='event_reminders', to=settings.AUTH_USER_MODEL, verbose_name='Destinataires'),
        ),
        migrations.AddField(
            model_name='eventpoll',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_polls', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AddField(
            model_name='eventpoll',
            name='event',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='poll', to='competitions.event', verbose_name='Ã‰vénement associé'),
        ),
        migrations.AddField(
            model_name='eventpoll',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_polls', to='organizations.organization', verbose_name='Organisation'),
        ),
        migrations.AddField(
            model_name='eventparticipant',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='competitions.event', verbose_name='Ã‰vénement'),
        ),
        migrations.AddField(
            model_name='eventparticipant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_participations', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AddField(
            model_name='eventfeedback',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_feedbacks', to='competitions.event', verbose_name='Ã‰vénement'),
        ),
        migrations.AddField(
            model_name='eventfeedback',
            name='submitted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_feedbacks', to=settings.AUTH_USER_MODEL, verbose_name='Soumis par'),
        ),
        migrations.AddField(
            model_name='event',
            name='contact_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organized_events', to=settings.AUTH_USER_MODEL, verbose_name='Personne de contact'),
        ),
        migrations.AddField(
            model_name='event',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_events', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AddField(
            model_name='event',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='organizations.organization', verbose_name='Organisation'),
        ),
        migrations.AddField(
            model_name='equipe',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipes_combat', to='competitions.club', verbose_name='Club'),
        ),
        migrations.AddField(
            model_name='equipe',
            name='coach',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipes_coachees', to=settings.AUTH_USER_MODEL, verbose_name='Coach'),
        ),
        migrations.AddField(
            model_name='equipe',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipes_combat', to='competitions.competition', verbose_name='Compétition'),
        ),
        migrations.AddField(
            model_name='equipe',
            name='membres',
            field=models.ManyToManyField(related_name='equipes_combat', through='competitions.MembreEquipe', to='competitions.practitioner', verbose_name='Membres'),
        ),
        migrations.AddField(
            model_name='disciplineexpertise',
            name='coach_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discipline_expertises', to='competitions.coachprofile', verbose_name='Profil coach'),
        ),
        migrations.AddField(
            model_name='disciplineexpertise',
            name='discipline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competitions.discipline', verbose_name='Discipline'),
        ),
        migrations.AddField(
            model_name='disciplineexpertise',
            name='federation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='competitions.federation', verbose_name='Fédération affiliée'),
        ),
        migrations.AddField(
            model_name='discipline',
            name='grading_system',
            field=models.ForeignKey(blank=True, help_text='Configuration du système de grades pour cette discipline', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disciplines', to='grades.gradingsystem', verbose_name='Système de grade'),
        ),
        migrations.AddField(
            model_name='discipline',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_disciplines', to='organizations.organization', verbose_name='Fédération principale'),
        ),
        migrations.AddField(
            model_name='conversationparticipant',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competitions.conversation', verbose_name='Conversation'),
        ),
        migrations.AddField(
            model_name='conversationparticipant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_conversations', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='organizations.organization', verbose_name='Organisation'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='participants',
            field=models.ManyToManyField(related_name='conversations', through='competitions.ConversationParticipant', to=settings.AUTH_USER_MODEL, verbose_name='Participants'),
        ),
        migrations.AddField(
            model_name='competitiontype',
            name='discipline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competition_types', to='competitions.discipline'),
        ),
        migrations.AddField(
            model_name='competitionschedule',
            name='competition',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='competitions.competition', verbose_name='Compétition'),
        ),
        migrations.AddField(
            model_name='competitionschedule',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_schedules', to=settings.AUTH_USER_MODEL, verbose_name='Mis Ã\xa0 jour par'),
        ),
        migrations.AddField(
            model_name='competitionrole',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='competitions.competition'),
        ),
        migrations.AddField(
            model_name='competitionresult',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='results', to='competitions.competitioncategory', verbose_name='Catégorie'),
        ),
        migrations.AddField(
            model_name='competitionresult',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='competitions.competition', verbose_name='Compétition'),
        ),
        migrations.AddField(
            model_name='competitionresult',
            name='practitioner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competition_results', to='competitions.practitioner', verbose_name='Pratiquant'),
        ),
        migrations.AddField(
            model_name='competitionregistration',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='registrations', to='competitions.competitioncategory'),
        ),
        migrations.AddField(
            model_name='competitionregistration',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='competitions.competition'),
        ),
        migrations.AddField(
            model_name='competitionregistration',
            name='competition_types',
            field=models.ManyToManyField(blank=True, related_name='registrations', to='competitions.competitiontype'),
        ),
        migrations.AddField(
            model_name='competitionregistration',
            name='practitioner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='competitions.practitioner'),
        ),
        migrations.AddField(
            model_name='competitionregistration',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='registrations', to='competitions.competitionrole'),
        ),
        migrations.AddField(
            model_name='competitionranking',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rankings', to='competitions.competitioncategory', verbose_name='Catégorie'),
        ),
        migrations.AddField(
            model_name='competitionranking',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rankings', to='competitions.competition', verbose_name='Compétition'),
        ),
        migrations.AddField(
            model_name='competitionranking',
            name='practitioner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rankings', to='competitions.practitioner', verbose_name='Pratiquant'),
        ),
        migrations.AddField(
            model_name='competitioncategory',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='competitions.competition'),
        ),
        migrations.AddField(
            model_name='competitioncategory',
            name='competition_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='competitions.competitiontype'),
        ),
        migrations.AddField(
            model_name='competitioncategory',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_in_competitions', to='competitions.categorytemplate', verbose_name='Template source'),
        ),
        migrations.AddField(
            model_name='competition',
            name='competition_types',
            field=models.ManyToManyField(related_name='competitions', to='competitions.competitiontype'),
        ),
        migrations.AddField(
            model_name='competition',
            name='discipline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='competitions', to='competitions.discipline', verbose_name='Discipline'),
        ),
        migrations.AddField(
            model_name='competition',
            name='organizing_organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organized_competitions', to='organizations.organization', verbose_name='Organisation organisatrice'),
        ),
        migrations.AddField(
            model_name='combatconfiguration',
            name='discipline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combat_configurations', to='competitions.discipline', verbose_name='Discipline'),
        ),
        migrations.AddField(
            model_name='combat',
            name='arbitre_central',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='combats_arbitre_central', to='competitions.judge', verbose_name='Arbitre central'),
        ),
        migrations.AddField(
            model_name='combat',
            name='arbitres_lateraux',
            field=models.ManyToManyField(blank=True, related_name='combats_arbitre_lateral', to='competitions.judge', verbose_name='Arbitres latéraux'),
        ),
        migrations.AddField(
            model_name='combat',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combats', to='competitions.competition', verbose_name='Compétition'),
        ),
        migrations.AddField(
            model_name='combat',
            name='configuration',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='combats', to='competitions.combatconfiguration', verbose_name='Configuration'),
        ),
        migrations.AddField(
            model_name='combat',
            name='equipe_blanc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='combats_blanc', to='competitions.equipe', verbose_name='Ã‰quipe blanc'),
        ),
        migrations.AddField(
            model_name='combat',
            name='equipe_rouge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='combats_rouge', to='competitions.equipe', verbose_name='Ã‰quipe rouge'),
        ),
        migrations.AddField(
            model_name='combat',
            name='poule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='combats', to='competitions.poule', verbose_name='Poule'),
        ),
        migrations.AddField(
            model_name='combat',
            name='pratiquant_blanc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='combats_blanc', to='competitions.practitioner', verbose_name='Pratiquant blanc'),
        ),
        migrations.AddField(
            model_name='combat',
            name='pratiquant_rouge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='combats_rouge', to='competitions.practitioner', verbose_name='Pratiquant rouge'),
        ),
        migrations.AddField(
            model_name='coachprofile',
            name='practitioner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coach_profile', to='competitions.practitioner', verbose_name='Pratiquant'),
        ),
        migrations.AddField(
            model_name='coachprofile',
            name='primary_teaching_place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_coaches', to='competitions.club', verbose_name='Club référencé (interne)'),
        ),
        migrations.AddField(
            model_name='coachachievement',
            name='coach_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='competitions.coachprofile', verbose_name='Profil coach'),
        ),
        migrations.AddField(
            model_name='coachachievement',
            name='discipline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='competitions.discipline', verbose_name='Discipline concernée'),
        ),
        migrations.AddField(
            model_name='clubteam',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teams', to='competitions.club', verbose_name='Club (obsolète)'),
        ),
        migrations.AddField(
            model_name='clubteam',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competition_teams', to='competitions.competition', verbose_name='Compétition'),
        ),
        migrations.AddField(
            model_name='clubteam',
            name='members',
            field=models.ManyToManyField(related_name='team_memberships', to=settings.AUTH_USER_MODEL, verbose_name='Membres'),
        ),
        migrations.AddField(
            model_name='clubteam',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club_teams', to='organizations.organization', verbose_name='Organisation'),
        ),
        migrations.AddField(
            model_name='clubrole',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='clubadministrator',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='administrators', to='competitions.club', verbose_name='Club'),
        ),
        migrations.AddField(
            model_name='clubadministrator',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='club_administrators', to='organizations.organization', verbose_name='Organisation'),
        ),
        migrations.AddField(
            model_name='clubadministrator',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club_admin_roles', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AddField(
            model_name='club',
            name='disciplines',
            field=models.ManyToManyField(blank=True, related_name='club_disciplines', to='competitions.discipline', verbose_name='Disciplines'),
        ),
        migrations.AddField(
            model_name='club',
            name='main_discipline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_clubs', to='competitions.discipline', verbose_name='Discipline principale'),
        ),
        migrations.AddField(
            model_name='club',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legacy_clubs', to='organizations.organization', verbose_name='Organisation associée'),
        ),
        migrations.AddField(
            model_name='club',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_clubs', to=settings.AUTH_USER_MODEL, verbose_name='Propriétaire'),
        ),
        # NOTE: Champ 'tenant' supprimé car l'app multitenant n'est pas installée dans cet environnement
        migrations.AddField(
            model_name='certificationregistration',
            name='certification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='competitions.judgecertification', verbose_name='Certification'),
        ),
        migrations.AddField(
            model_name='certificationregistration',
            name='practitioner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cert_registrations', to='competitions.practitioner'),
        ),
        migrations.AddField(
            model_name='certificationregistration',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_certification_registrations', to=settings.AUTH_USER_MODEL, verbose_name='Examiné par'),
        ),
        migrations.AddField(
            model_name='certificationregistration',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certification_registrations', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AddField(
            model_name='categorytemplate',
            name='competition_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_templates', to='competitions.competitiontype', verbose_name='Type de compétition'),
        ),
        migrations.AddField(
            model_name='categorytemplate',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_category_templates', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AddField(
            model_name='categorytemplate',
            name='discipline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_templates', to='competitions.discipline', verbose_name='Discipline'),
        ),
        migrations.AddField(
            model_name='categoryschedule',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='competitions.competitioncategory', verbose_name='Catégorie'),
        ),
        migrations.AddField(
            model_name='categoryschedule',
            name='competition_schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_schedules', to='competitions.competitionschedule', verbose_name='Planning de compétition'),
        ),
        migrations.AddField(
            model_name='categoryschedule',
            name='tatami',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_schedules', to='competitions.tatamischedule', verbose_name='Tatami'),
        ),
        migrations.AddField(
            model_name='categoryranking',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_rankings', to='competitions.competitioncategory', verbose_name='Catégorie'),
        ),
        migrations.AddField(
            model_name='categoryranking',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_rankings', to='competitions.competition', verbose_name='Compétition'),
        ),
        migrations.AddField(
            model_name='categoryranking',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_rankings', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='practitioner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='competitions.practitioner', verbose_name='Pratiquant'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='recorded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_attendances', to=settings.AUTH_USER_MODEL, verbose_name='Enregistré par'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='competitions.trainingsession', verbose_name='Session'),
        ),
        migrations.AddField(
            model_name='affiliationrequest',
            name='requesting_organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_affiliation_requests', to='organizations.organization', verbose_name='Organisation demandeuse'),
        ),
        migrations.AddField(
            model_name='affiliationrequest',
            name='target_organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_affiliation_requests', to='organizations.organization', verbose_name='Organisation cible'),
        ),
        migrations.AddField(
            model_name='actioncombat',
            name='arbitre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions_combat', to='competitions.judge', verbose_name='Arbitre'),
        ),
        migrations.AddField(
            model_name='actioncombat',
            name='combat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='competitions.combat', verbose_name='Combat'),
        ),
        migrations.AlterUniqueTogether(
            name='userclubrole',
            unique_together={('user', 'organization', 'role')},
        ),
        migrations.AlterUniqueTogether(
            name='trainingslot',
            unique_together={('club', 'day_of_week', 'start_time', 'location')},
        ),
        migrations.AlterUniqueTogether(
            name='trainingsession',
            unique_together={('training_slot', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='trainingreservation',
            unique_together={('practitioner', 'training_slot', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='technique',
            unique_together={('discipline', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='technicalscoreresult',
            unique_together={('performance', 'judge', 'criterion')},
        ),
        migrations.AlterUniqueTogether(
            name='technicalscore',
            unique_together={('performance', 'judge', 'criterion')},
        ),
        migrations.AlterUniqueTogether(
            name='technicalperformanceresult',
            unique_together={('competition', 'category', 'practitioner')},
        ),
        migrations.AlterUniqueTogether(
            name='technicalperformance',
            unique_together={('competition', 'category', 'practitioner')},
        ),
        migrations.AlterUniqueTogether(
            name='tatamischedule',
            unique_together={('competition_schedule', 'tatami_number')},
        ),
        migrations.AlterUniqueTogether(
            name='style',
            unique_together={('discipline', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='score',
            unique_together={('performance', 'judge', 'criterion')},
        ),
        migrations.AlterUniqueTogether(
            name='rankingentry',
            unique_together={('ranking', 'practitioner')},
        ),
        migrations.AddIndex(
            model_name='qrcodescan',
            index=models.Index(fields=['qr_code', 'scan_type'], name='competition_qr_code_2318c7_idx'),
        ),
        migrations.AddIndex(
            model_name='qrcodescan',
            index=models.Index(fields=['scan_date'], name='competition_scan_da_8b76ab_idx'),
        ),
        migrations.AddIndex(
            model_name='qrcodescan',
            index=models.Index(fields=['is_offline_scan'], name='competition_is_offl_07674b_idx'),
        ),
        migrations.AddIndex(
            model_name='qrcodescan',
            index=models.Index(fields=['offline_scan_id'], name='competition_offline_b4f93b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='programenrollment',
            unique_together={('practitioner', 'program', 'start_date')},
        ),
        migrations.AlterUniqueTogether(
            name='practitionerqualification',
            unique_together={('practitioner', 'qualification_type', 'discipline')},
        ),
        migrations.AlterUniqueTogether(
            name='practitionerprogress',
            unique_together={('practitioner', 'exercise')},
        ),
        migrations.AlterUniqueTogether(
            name='practitionerdiscipline',
            unique_together={('practitioner', 'discipline')},
        ),
        migrations.AddIndex(
            model_name='practitioner',
            index=models.Index(fields=['last_name', 'first_name'], name='competition_last_na_3aca86_idx'),
        ),
        migrations.AddIndex(
            model_name='practitioner',
            index=models.Index(fields=['organization'], name='competition_organiz_e186dc_idx'),
        ),
        migrations.AddIndex(
            model_name='practitioner',
            index=models.Index(fields=['user'], name='competition_user_id_f33065_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='poule',
            unique_together={('competition', 'phase', 'numero')},
        ),
        migrations.AlterUniqueTogether(
            name='pollresponse',
            unique_together={('option', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='pollquestionresponse',
            unique_together={('question', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='pollquestion',
            unique_together={('poll', 'order')},
        ),
        migrations.AlterUniqueTogether(
            name='polloption',
            unique_together={('poll', 'date', 'start_time')},
        ),
        migrations.AlterUniqueTogether(
            name='participantcategoryregistration',
            unique_together={('registration', 'competition_type')},
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', '-created_at'], name='competition_user_id_405c75_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read'], name='competition_user_id_7d6ccf_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='messageread',
            unique_together={('message', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='messagereaction',
            unique_together={('message', 'user', 'emoji')},
        ),
        migrations.AlterUniqueTogether(
            name='membreequipe',
            unique_together={('equipe', 'pratiquant')},
        ),
        migrations.AlterUniqueTogether(
            name='license',
            unique_together={('practitioner', 'license_number', 'organization')},
        ),
        migrations.AlterUniqueTogether(
            name='judgetrainingregistration',
            unique_together={('judge', 'training')},
        ),
        migrations.AlterUniqueTogether(
            name='judgesubmissionstatusresult',
            unique_together={('judge', 'performance')},
        ),
        migrations.AlterUniqueTogether(
            name='judgesubmissionstatus',
            unique_together={('judge', 'performance')},
        ),
        migrations.AlterUniqueTogether(
            name='judgequalification',
            unique_together={('practitioner', 'qualification_type', 'discipline')},
        ),
        migrations.AlterUniqueTogether(
            name='judgecompetitionassignment',
            unique_together={('registration', 'category', 'assignment_type')},
        ),
        migrations.AlterUniqueTogether(
            name='judgeassignment',
            unique_together={('registration', 'category', 'assignment_type')},
        ),
        migrations.AlterUniqueTogether(
            name='federationadministrator',
            unique_together={('user', 'organization'), ('user', 'federation')},
        ),
        migrations.AlterUniqueTogether(
            name='eventparticipant',
            unique_together={('event', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='eventfeedback',
            unique_together={('event', 'submitted_by')},
        ),
        migrations.AlterUniqueTogether(
            name='disciplineexpertise',
            unique_together={('coach_profile', 'discipline')},
        ),
        migrations.AlterUniqueTogether(
            name='conversationparticipant',
            unique_together={('conversation', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='competitionrole',
            unique_together={('competition', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='competitionresult',
            unique_together={('competition', 'category', 'practitioner')},
        ),
        migrations.AlterUniqueTogether(
            name='competitionregistration',
            unique_together={('practitioner', 'competition')},
        ),
        migrations.AlterUniqueTogether(
            name='competitionranking',
            unique_together={('competition', 'category', 'practitioner')},
        ),
        migrations.AddConstraint(
            model_name='competitioncategory',
            constraint=models.UniqueConstraint(fields=('competition', 'name'), name='unique_category_per_competition'),
        ),
        migrations.AlterUniqueTogether(
            name='clubrole',
            unique_together={('name', 'organization')},
        ),
        migrations.AlterUniqueTogether(
            name='clubadministrator',
            unique_together={('user', 'club'), ('user', 'organization')},
        ),
        migrations.AlterUniqueTogether(
            name='categorytemplate',
            unique_together={('discipline', 'competition_type', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='categoryranking',
            unique_together={('category', 'competition')},
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('session', 'practitioner')},
        ),
    ]
