# Generated by Django 4.2.21 on 2025-07-31 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0003_initial'),
    ]

    operations = [
    ]
