# Generated by Django 4.2.21 on 2025-08-01 20:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('competitions', '0004_fix_timezone_notifications'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('exam_type', models.CharField(choices=[('grade', 'Examen de grade'), ('certification', 'Examen de certification'), ('recertification', 'Examen de recertification')], default='grade', max_length=20, verbose_name="Type d'examen")),
                ('start_date', models.DateField(verbose_name='Date de début')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Date de fin')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='Heure de début')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='Heure de fin')),
                ('location', models.CharField(max_length=255, verbose_name='Lieu')),
                ('address', models.TextField(blank=True, verbose_name='Adresse complète')),
                ('registration_start', models.DateField(verbose_name='Début des inscriptions')),
                ('registration_end', models.DateField(verbose_name='Fin des inscriptions')),
                ('max_participants', models.PositiveIntegerField(default=50, verbose_name='Nombre maximum de participants')),
                ('registration_fee', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name="Frais d'inscription")),
                ('requirements', models.TextField(blank=True, verbose_name='Prérequis')),
                ('rules', models.TextField(blank=True, verbose_name='Règlement')),
                ('materials_needed', models.TextField(blank=True, verbose_name='Matériel nécessaire')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('published', 'Publié'), ('ongoing', 'En cours'), ('completed', 'Terminé'), ('cancelled', 'Annulé')], default='draft', max_length=20, verbose_name='Statut')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('chief_examiner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chief_examiner_exams', to=settings.AUTH_USER_MODEL, verbose_name='Examinateur principal')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_exams', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='competitions.discipline', verbose_name='Discipline')),
                ('examiners', models.ManyToManyField(blank=True, related_name='examiner_exams', to=settings.AUTH_USER_MODEL, verbose_name='Examinateurs')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='organizations.organization', verbose_name='Organisation')),
            ],
            options={
                'verbose_name': 'Examen',
                'verbose_name_plural': 'Examens',
                'ordering': ['-start_date', 'title'],
            },
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Créé le'),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='training_notifications',
            field=models.BooleanField(default=True, verbose_name="Notifications d'entraînement"),
        ),
        migrations.CreateModel(
            name='ExamRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_date', models.DateTimeField(auto_now_add=True, verbose_name="Date d'inscription")),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvée'), ('rejected', 'Rejetée'), ('completed', 'Terminée'), ('absent', 'Absent')], default='pending', max_length=20, verbose_name='Statut')),
                ('notes', models.TextField(blank=True, verbose_name="Notes de l'inscription")),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Note')),
                ('grade_obtained', models.CharField(blank=True, max_length=50, verbose_name='Grade obtenu')),
                ('passed', models.BooleanField(blank=True, null=True, verbose_name='Réussi')),
                ('examiner_feedback', models.TextField(blank=True, verbose_name="Commentaires de l'examinateur")),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Évalué le')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='competitions.exam', verbose_name='Examen')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_exam_registrations', to=settings.AUTH_USER_MODEL, verbose_name='Évalué par')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_registrations', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Inscription à un examen',
                'verbose_name_plural': 'Inscriptions aux examens',
                'ordering': ['-registration_date'],
                'unique_together': {('exam', 'user')},
            },
        ),
    ]
