# Generated by Django 4.2.21 on 2025-08-15 13:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('competitions', '0006_merge_conflicts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubqrcode',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='organizationqrcode',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organization_qr_codes', to='competitions.club', verbose_name='Club'),
        ),
        migrations.AlterField(
            model_name='organizationqrcodescan',
            name='user_created',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organization_qr_registrations', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur créé'),
        ),
    ]
