# Generated by Django 4.2.11 on 2025-10-12 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0008_alter_userprofile_organization'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='competitionrole',
            options={'verbose_name': 'Rôle de compétition', 'verbose_name_plural': 'Rôles de compétition'},
        ),
        migrations.AlterModelOptions(
            name='participantcategoryregistration',
            options={'verbose_name': 'Inscription à une catégorie', 'verbose_name_plural': 'Inscriptions aux catégories'},
        ),
        migrations.AddField(
            model_name='competitiontype',
            name='scoring_system',
            field=models.CharField(choices=[('technical', 'Technique'), ('combat', 'Combat'), ('mixed', 'Mixte'), ('custom', 'Personnalisé')], default='technical', help_text='Type de système de notation utilisé pour ce type de compétition', max_length=20, verbose_name='Système de notation'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='max_age',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Âge maximum'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='min_age',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Âge minimum'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Mis à jour le'),
        ),
        migrations.AlterField(
            model_name='competitionrole',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nom du rôle'),
        ),
    ]
