# Generated by Django 4.2.11 on 2025-11-03 18:31

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0009_add_scoring_system_to_competition_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='StandaloneCategoryRankingSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.IntegerField()),
                ('competition_id', models.IntegerField()),
                ('created_by_id', models.IntegerField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('is_final', models.BooleanField(default=False)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Category Ranking Snapshot',
                'verbose_name_plural': 'Category Ranking Snapshots',
            },
        ),
        migrations.CreateModel(
            name='StandaloneJudgeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(unique=True)),
                ('display_mode', models.CharField(choices=[('compact', 'Compact'), ('detailed', 'Detailed')], default='detailed', max_length=20)),
                ('notification_sounds', models.BooleanField(default=True)),
                ('auto_submit', models.BooleanField(default=False)),
                ('theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark')], default='light', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Judge Settings',
                'verbose_name_plural': 'Judge Settings',
            },
        ),
        migrations.CreateModel(
            name='StandalonePerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competition_id', models.IntegerField()),
                ('category_id', models.IntegerField()),
                ('practitioner_id', models.IntegerField()),
                ('round_type', models.CharField(choices=[('preliminary', 'Preliminary'), ('semifinal', 'Semifinal'), ('final', 'Final'), ('exhibition', 'Exhibition')], default='preliminary', max_length=20)),
                ('round_number', models.PositiveIntegerField(default=1)),
                ('performance_order', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('disqualified', 'Disqualified'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('disqualification_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Performance',
                'verbose_name_plural': 'Performances',
                'ordering': ['round_type', 'round_number', 'performance_order'],
            },
        ),
        migrations.CreateModel(
            name='StandaloneScoringSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('system_type', models.CharField(choices=[('standard', 'Standard (Weighted Average)'), ('point', 'Point System'), ('direct', 'Direct Elimination'), ('custom', 'Custom')], default='standard', max_length=20)),
                ('min_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('max_score', models.DecimalField(decimal_places=2, default=10.0, max_digits=5)),
                ('score_step', models.DecimalField(decimal_places=2, default=0.1, max_digits=5)),
                ('exclude_extreme_scores', models.BooleanField(default=False)),
                ('allow_ties', models.BooleanField(default=True)),
                ('real_time_results', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Scoring System',
                'verbose_name_plural': 'Scoring Systems',
                'db_table': 'competitions_standalonescoringystem',
            },
        ),
        migrations.CreateModel(
            name='StandaloneScoringCriterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('weight', models.DecimalField(decimal_places=2, default=1.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('min_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('max_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('step', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('order_num', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scoring_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standalone_criteria', to='competitions.standalonescoringsystem')),
            ],
            options={
                'verbose_name': 'Scoring Criterion',
                'verbose_name_plural': 'Scoring Criteria',
                'ordering': ['order_num', 'name'],
            },
        ),
        migrations.CreateModel(
            name='StandaloneRankingSnapshotEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('practitioner_id', models.IntegerField()),
                ('rank', models.PositiveIntegerField()),
                ('final_score', models.DecimalField(decimal_places=3, max_digits=7)),
                ('is_tie', models.BooleanField(default=False)),
                ('medal', models.CharField(choices=[('gold', 'Gold'), ('silver', 'Silver'), ('bronze', 'Bronze'), ('none', 'None')], default='none', max_length=10)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='competitions.standalonecategoryrankingsnapshot')),
            ],
            options={
                'verbose_name': 'Ranking Snapshot Entry',
                'verbose_name_plural': 'Ranking Snapshot Entries',
                'db_table': 'competitions_standalonerankingsnapshotentry',
                'ordering': ['snapshot', 'rank'],
            },
        ),
        migrations.CreateModel(
            name='StandaloneCategoryScoringConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.IntegerField(unique=True)),
                ('override_min_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('override_max_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('override_score_step', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('exclude_extreme_scores', models.BooleanField(blank=True, null=True)),
                ('allow_ties', models.BooleanField(blank=True, null=True)),
                ('real_time_results', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scoring_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standalone_category_configs', to='competitions.standalonescoringsystem')),
            ],
            options={
                'verbose_name': 'Category Scoring Configuration',
                'verbose_name_plural': 'Category Scoring Configurations',
            },
        ),
        migrations.CreateModel(
            name='StandaloneScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judge_id', models.IntegerField()),
                ('value', models.DecimalField(decimal_places=2, max_digits=5)),
                ('original_value', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('is_locked', models.BooleanField(default=False)),
                ('is_training_score', models.BooleanField(default=False)),
                ('modified_by_id', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standalone_scores', to='competitions.standalonescoringcriterion')),
                ('performance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standalone_scores', to='competitions.standaloneperformance')),
            ],
            options={
                'verbose_name': 'Score',
                'verbose_name_plural': 'Scores',
                'unique_together': {('performance', 'judge_id', 'criterion')},
            },
        ),
        migrations.CreateModel(
            name='StandaloneJudgeSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judge_id', models.IntegerField()),
                ('is_submitted', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('performance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standalone_judge_submissions', to='competitions.standaloneperformance')),
            ],
            options={
                'verbose_name': 'Judge Submission',
                'verbose_name_plural': 'Judge Submissions',
                'unique_together': {('performance', 'judge_id')},
            },
        ),
        migrations.CreateModel(
            name='StandaloneCompetitionRanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competition_id', models.IntegerField()),
                ('category_id', models.IntegerField()),
                ('practitioner_id', models.IntegerField()),
                ('rank', models.PositiveIntegerField()),
                ('final_score', models.DecimalField(decimal_places=3, max_digits=7)),
                ('is_tie', models.BooleanField(default=False)),
                ('medal', models.CharField(choices=[('gold', 'Gold'), ('silver', 'Silver'), ('bronze', 'Bronze'), ('none', 'None')], default='none', max_length=10)),
                ('is_published', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('performance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='standalone_rankings', to='competitions.standaloneperformance')),
            ],
            options={
                'verbose_name': 'Competition Ranking',
                'verbose_name_plural': 'Competition Rankings',
                'ordering': ['category_id', 'rank'],
                'unique_together': {('category_id', 'practitioner_id')},
            },
        ),
    ]
