# Generated by Django 5.1.6 on 2025-11-29 23:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0012_equipe_fusion_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipe',
            options={'verbose_name': 'Equipe', 'verbose_name_plural': 'Equipes'},
        ),
        migrations.RemoveField(
            model_name='combatconfiguration',
            name='afficher_nom_equipe',
        ),
        migrations.RemoveField(
            model_name='combatconfiguration',
            name='couleurs_interface',
        ),
        migrations.RemoveField(
            model_name='combatconfiguration',
            name='cumul_points_equipe',
        ),
        migrations.RemoveField(
            model_name='combatconfiguration',
            name='labels_penalites',
        ),
        migrations.RemoveField(
            model_name='combatconfiguration',
            name='labels_points',
        ),
        migrations.RemoveField(
            model_name='combatconfiguration',
            name='nb_combattants_equipe',
        ),
        migrations.AlterField(
            model_name='combat',
            name='score_cumul_blanc',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Score cumulé blanc'),
        ),
        migrations.AlterField(
            model_name='combat',
            name='score_cumul_rouge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Score cumulé rouge'),
        ),
        migrations.AlterField(
            model_name='equipe',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipes_combat', to='competitions.competition', verbose_name='Competition'),
        ),
        migrations.AlterField(
            model_name='equipe',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Cree le'),
        ),
        migrations.CreateModel(
            name='JudgeCategoryLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.PositiveIntegerField(default=1, verbose_name='Numéro de round')),
                ('is_locked', models.BooleanField(default=False, verbose_name='Verrouillé')),
                ('locked_at', models.DateTimeField(blank=True, null=True, verbose_name='Verrouillé le')),
                ('scores_count', models.PositiveIntegerField(default=0, verbose_name='Nombre de notes')),
                ('average_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Moyenne des notes')),
                ('min_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Note minimale')),
                ('max_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Note maximale')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='judge_locks', to='competitions.competitioncategory', verbose_name='Catégorie')),
                ('judge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_locks', to='competitions.judge', verbose_name='Juge')),
            ],
            options={
                'verbose_name': 'Verrouillage juge par catégorie',
                'verbose_name_plural': 'Verrouillages juges par catégorie',
                'ordering': ['category', 'round_number', 'judge'],
                'unique_together': {('judge', 'category', 'round_number')},
            },
        ),
    ]
