# Generated by Django 5.1.6 on 2025-12-03 09:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0013_alter_equipe_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdHocJudge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('competition_participant', 'Participant à cette compétition'), ('club_member', 'Membre du club organisateur'), ('discipline_practitioner', 'Pratiquant de la discipline'), ('external_volunteer', 'Bénévole externe')], default='competition_participant', max_length=30, verbose_name='Source de recrutement')),
                ('judge_type', models.CharField(choices=[('technical_judge', 'Juge Technique'), ('combat_referee', 'Arbitre Combat'), ('assistant_referee', 'Arbitre Assistant'), ('timekeeper', 'Chronométreur'), ('scorekeeper', 'Marqueur')], default='technical_judge', max_length=20, verbose_name='Type de juge')),
                ('status', models.CharField(choices=[('pending', 'En attente de confirmation'), ('active', 'Actif'), ('completed', 'Mission terminée'), ('declined', 'A décliné'), ('revoked', 'Révoqué')], default='pending', max_length=20, verbose_name='Statut')),
                ('experience_level', models.CharField(choices=[('novice', 'Novice - Première expérience'), ('beginner', 'Débutant - Quelques compétitions'), ('intermediate', 'Intermédiaire - Expérience régulière'), ('experienced', 'Expérimenté - Nombreuses compétitions')], default='novice', max_length=20, verbose_name="Niveau d'expérience")),
                ('activated_at', models.DateTimeField(blank=True, null=True, verbose_name='Activé le')),
                ('deactivated_at', models.DateTimeField(blank=True, null=True, verbose_name='Désactivé le')),
                ('recruitment_date', models.DateTimeField(auto_now_add=True, verbose_name='Date de recrutement')),
                ('has_accepted', models.BooleanField(default=False, verbose_name='A accepté la mission')),
                ('briefing_completed', models.BooleanField(default=False, verbose_name='Briefing effectué')),
                ('briefing_date', models.DateTimeField(blank=True, null=True, verbose_name='Date du briefing')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('performance_rating', models.PositiveSmallIntegerField(blank=True, help_text='Note de 1 à 5 sur la qualité du travail', null=True, verbose_name='Évaluation de performance')),
                ('performance_comments', models.TextField(blank=True, verbose_name='Commentaires sur la performance')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_categories', models.ManyToManyField(blank=True, related_name='adhoc_judges', to='competitions.competitioncategory', verbose_name='Catégories assignées')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adhoc_judges', to='competitions.competition', verbose_name='Compétition')),
                ('practitioner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adhoc_judge_assignments', to='competitions.practitioner', verbose_name='Pratiquant')),
                ('recruited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recruited_adhoc_judges', to=settings.AUTH_USER_MODEL, verbose_name='Recruté par')),
            ],
            options={
                'verbose_name': 'Juge ad-hoc',
                'verbose_name_plural': 'Juges ad-hoc',
                'ordering': ['-recruitment_date'],
                'unique_together': {('competition', 'practitioner', 'judge_type')},
            },
        ),
    ]
