# Generated by Django 5.1.6 on 2025-12-03 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0014_add_adhoc_judge_model'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='competitioncategory',
            options={'ordering': ['competition', 'assigned_tatami', 'schedule_order', 'name'], 'verbose_name': 'Catégorie de compétition', 'verbose_name_plural': 'Catégories de compétition'},
        ),
        migrations.AddField(
            model_name='competitioncategory',
            name='assigned_tatami',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Numéro du tatami/aire où cette catégorie sera jugée', null=True, verbose_name='Tatami assigné'),
        ),
        migrations.AddField(
            model_name='competitioncategory',
            name='estimated_duration',
            field=models.PositiveIntegerField(blank=True, default=30, null=True, verbose_name='Durée estimée (minutes)'),
        ),
        migrations.AddField(
            model_name='competitioncategory',
            name='estimated_start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Heure de début estimée'),
        ),
        migrations.AddField(
            model_name='competitioncategory',
            name='schedule_order',
            field=models.PositiveIntegerField(blank=True, help_text='Ordre de passage sur le tatami assigné', null=True, verbose_name='Ordre de passage'),
        ),
    ]
