# Generated by Django 5.1.6 on 2025-12-05 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0015_add_schedule_fields_to_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipe',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipes_combat', to='competitions.competitioncategory', verbose_name='Catégorie'),
        ),
        migrations.AlterField(
            model_name='adhocjudge',
            name='source',
            field=models.CharField(choices=[('competition_participant', 'Participant à cette compétition'), ('club_member', 'Membre du club organisateur'), ('discipline_practitioner', 'Pratiquant de la discipline'), ('external_volunteer', 'Bénévole externe'), ('official_judge', 'Juge officiel certifié')], default='competition_participant', max_length=30, verbose_name='Source de recrutement'),
        ),
    ]
