# Generated by Django 5.1.6 on 2025-12-08 21:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0016_add_category_to_equipe'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='technicalscore',
            options={'ordering': ['performance', 'round_number', 'judge'], 'verbose_name': 'Note technique', 'verbose_name_plural': 'Notes techniques'},
        ),
        migrations.AlterUniqueTogether(
            name='technicalscore',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='technicalscore',
            name='is_active_for_ranking',
            field=models.BooleanField(default=True, help_text="Si False, cette note n'est pas comptée dans le classement final", verbose_name='Active pour le classement'),
        ),
        migrations.AddField(
            model_name='technicalscore',
            name='round_number',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Tour initial'), (2, 'Barrage 1'), (3, 'Barrage 2'), (4, 'Barrage 3')], default=1, help_text='1 = Tour initial, 2+ = Barrages', verbose_name='Tour de notation'),
        ),
        migrations.AlterUniqueTogether(
            name='technicalscore',
            unique_together={('performance', 'judge', 'criterion', 'round_number')},
        ),
    ]
