# Generated by Django 5.1.6 on 2025-12-09
# Sprint 1: Team Configuration, Entente, Fusion support

from django.db import migrations, models
import django.db.models.deletion
import django.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0017_add_round_number_to_technical_score'),
    ]

    operations = [
        # Sprint 1.1: Création du modèle TeamConfiguration
        migrations.CreateModel(
            name='TeamConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format_preset', models.CharField(
                    choices=[
                        ('2+1', '2 titulaires + 1 remplaçant'),
                        ('3+1', '3 titulaires + 1 remplaçant'),
                        ('3+2', '3 titulaires + 2 remplaçants'),
                        ('5+2', '5 titulaires + 2 remplaçants'),
                        ('custom', 'Personnalisé')
                    ],
                    default='3+1',
                    max_length=20,
                    verbose_name='Format prédéfini'
                )),
                ('min_titulaires', models.PositiveSmallIntegerField(
                    default=3,
                    validators=[django.core.validators.MinValueValidator(1)],
                    verbose_name='Minimum de titulaires'
                )),
                ('max_titulaires', models.PositiveSmallIntegerField(
                    default=3,
                    validators=[django.core.validators.MinValueValidator(1)],
                    verbose_name='Maximum de titulaires'
                )),
                ('min_remplacants', models.PositiveSmallIntegerField(
                    default=0,
                    verbose_name='Minimum de remplaçants'
                )),
                ('max_remplacants', models.PositiveSmallIntegerField(
                    default=1,
                    verbose_name='Maximum de remplaçants'
                )),
                ('remplacants_obligatoires', models.BooleanField(
                    default=False,
                    help_text='Si activé, les équipes doivent avoir le minimum de remplaçants requis',
                    verbose_name='Remplaçants obligatoires'
                )),
                ('min_equipes_required', models.PositiveSmallIntegerField(
                    default=3,
                    help_text='Si moins d\'équipes sont inscrites, proposer basculement vers individuel',
                    verbose_name='Nombre minimum d\'équipes'
                )),
                ('max_ententes_par_equipe', models.PositiveSmallIntegerField(
                    default=2,
                    help_text='Nombre maximum de membres en entente (prêtés d\'autres clubs)',
                    verbose_name='Maximum d\'ententes par équipe'
                )),
                ('entente_validation_required', models.BooleanField(
                    default=False,
                    help_text='Si activé, les ententes doivent être approuvées par l\'organisateur',
                    verbose_name='Validation des ententes requise'
                )),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('competition', models.OneToOneField(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='team_configuration',
                    to='competitions.competition',
                    verbose_name='Compétition'
                )),
            ],
            options={
                'verbose_name': "Configuration d'équipe",
                'verbose_name_plural': "Configurations d'équipes",
            },
        ),

        # Sprint 1.2: Ajout des champs fusion à Equipe
        migrations.AddField(
            model_name='equipe',
            name='is_fusion',
            field=models.BooleanField(
                default=False,
                help_text='Indique si cette équipe résulte d\'une fusion',
                verbose_name='Est une fusion'
            ),
        ),
        migrations.AddField(
            model_name='equipe',
            name='merged_into',
            field=models.ForeignKey(
                blank=True,
                help_text='Si archivée suite à fusion, l\'équipe résultante',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='equipes_absorbees',
                to='competitions.equipe',
                verbose_name='Fusionnée dans'
            ),
        ),
        migrations.AddField(
            model_name='equipe',
            name='is_active',
            field=models.BooleanField(
                default=True,
                help_text='False si l\'équipe a été fusionnée ou archivée (soft delete)',
                verbose_name='Active'
            ),
        ),

        # Sprint 1.3: Ajout des champs entente à MembreEquipe
        migrations.AddField(
            model_name='membreequipe',
            name='is_entente',
            field=models.BooleanField(
                default=False,
                help_text='Membre prêté par un autre club',
                verbose_name='Est en entente'
            ),
        ),
        migrations.AddField(
            model_name='membreequipe',
            name='club_origine',
            field=models.ForeignKey(
                blank=True,
                help_text='Pour les membres en entente: leur club d\'origine',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='membres_en_entente',
                to='competitions.club',
                verbose_name='Club d\'origine'
            ),
        ),
        migrations.AddField(
            model_name='membreequipe',
            name='equipe_origine',
            field=models.ForeignKey(
                blank=True,
                help_text='Pour les ententes: équipe d\'où vient le membre',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='membres_pretes',
                to='competitions.membreequipe',
                verbose_name='Équipe d\'origine'
            ),
        ),
        migrations.AddField(
            model_name='membreequipe',
            name='equipe_avant_fusion',
            field=models.ForeignKey(
                blank=True,
                help_text='Équipe d\'origine si ce membre a été transféré lors d\'une fusion',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='anciens_membres',
                to='competitions.equipe',
                verbose_name='Équipe avant fusion'
            ),
        ),
        migrations.AddField(
            model_name='membreequipe',
            name='a_combattu',
            field=models.BooleanField(
                default=False,
                help_text='Indique si le membre a participé à au moins un combat',
                verbose_name='A combattu'
            ),
        ),

        # Sprint 1.4: Extension des status de Combat (REQ-08)
        migrations.AlterField(
            model_name='combat',
            name='status',
            field=models.CharField(
                choices=[
                    ('planifie', 'Planifié'),
                    ('en_cours', 'En cours'),
                    ('termine', 'Terminé'),
                    ('annule', 'Annulé'),
                    ('forfait', 'Forfait'),
                    ('reporte', 'Reporté'),
                ],
                default='planifie',
                max_length=20,
                verbose_name='Statut'
            ),
        ),

        # Mise à jour du status d'Equipe avec 'archived'
        migrations.AlterField(
            model_name='equipe',
            name='status',
            field=models.CharField(
                choices=[
                    ('active', 'Active'),
                    ('pending_fusion', 'Fusion en attente'),
                    ('fusion_complete', 'Fusion completée'),
                    ('archived', 'Archivée'),
                ],
                default='active',
                max_length=20,
                verbose_name='Statut'
            ),
        ),
    ]
