# Generated by Django 5.1.6 on 2025-12-09
# Sprint 2: Entente (prêt de joueurs) et TeamMerge (fusion d'équipes)

from django.db import migrations, models
from django.conf import settings
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0018_sprint1_team_configuration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Sprint 2.1: Création du modèle Entente (REQ-06)
        migrations.CreateModel(
            name='Entente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(
                    choices=[
                        ('pending', 'En attente'),
                        ('approved', 'Approuvée'),
                        ('rejected', 'Refusée'),
                        ('cancelled', 'Annulée'),
                    ],
                    default='pending',
                    max_length=20,
                    verbose_name='Statut'
                )),
                ('role', models.CharField(
                    choices=[
                        ('titulaire', 'Titulaire'),
                        ('remplacant', 'Remplaçant'),
                    ],
                    default='titulaire',
                    max_length=20,
                    verbose_name='Rôle dans l\'équipe'
                )),
                ('raison', models.TextField(
                    blank=True,
                    help_text='Motif de la demande d\'entente',
                    verbose_name='Raison de l\'entente'
                )),
                ('commentaire_validation', models.TextField(
                    blank=True,
                    help_text='Commentaire lors de la validation/refus',
                    verbose_name='Commentaire de validation'
                )),
                ('date_demande', models.DateTimeField(
                    auto_now_add=True,
                    verbose_name='Date de demande'
                )),
                ('date_validation', models.DateTimeField(
                    blank=True,
                    null=True,
                    verbose_name='Date de validation'
                )),
                ('competition', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='ententes',
                    to='competitions.competition',
                    verbose_name='Compétition'
                )),
                ('pratiquant', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='ententes',
                    to='competitions.practitioner',
                    verbose_name='Pratiquant'
                )),
                ('club_origine', models.ForeignKey(
                    help_text='Club d\'origine du pratiquant',
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='ententes_sortantes',
                    to='competitions.club',
                    verbose_name='Club d\'origine'
                )),
                ('club_accueil', models.ForeignKey(
                    help_text='Club qui accueille le pratiquant en entente',
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='ententes_entrantes',
                    to='competitions.club',
                    verbose_name='Club d\'accueil'
                )),
                ('equipe_accueil', models.ForeignKey(
                    blank=True,
                    help_text='Équipe dans laquelle le pratiquant sera intégré',
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='ententes',
                    to='competitions.equipe',
                    verbose_name='Équipe d\'accueil'
                )),
                ('demandeur', models.ForeignKey(
                    help_text='Utilisateur qui a fait la demande d\'entente',
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='ententes_demandees',
                    to=settings.AUTH_USER_MODEL,
                    verbose_name='Demandeur'
                )),
                ('validateur', models.ForeignKey(
                    blank=True,
                    help_text='Utilisateur qui a validé/refusé l\'entente',
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='ententes_validees',
                    to=settings.AUTH_USER_MODEL,
                    verbose_name='Validateur'
                )),
            ],
            options={
                'verbose_name': 'Entente',
                'verbose_name_plural': 'Ententes',
                'ordering': ['-date_demande'],
            },
        ),
        # Contrainte d'unicité pour éviter les doublons
        migrations.AddConstraint(
            model_name='entente',
            constraint=models.UniqueConstraint(
                fields=['competition', 'pratiquant', 'club_accueil'],
                name='unique_entente_per_competition'
            ),
        ),

        # Sprint 2.2: Création du modèle TeamMerge (REQ-07)
        migrations.CreateModel(
            name='TeamMerge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(
                    choices=[
                        ('pending', 'En attente'),
                        ('approved', 'Approuvée'),
                        ('rejected', 'Refusée'),
                        ('completed', 'Fusionnée'),
                        ('cancelled', 'Annulée'),
                    ],
                    default='pending',
                    max_length=20,
                    verbose_name='Statut'
                )),
                ('raison', models.TextField(
                    blank=True,
                    help_text='Motif de la demande de fusion (ex: effectif insuffisant)',
                    verbose_name='Raison de la fusion'
                )),
                ('commentaire_validation', models.TextField(
                    blank=True,
                    help_text='Commentaire lors de la validation/refus',
                    verbose_name='Commentaire'
                )),
                ('nom_equipe_proposee', models.CharField(
                    blank=True,
                    help_text='Nom proposé pour l\'équipe fusionnée',
                    max_length=100,
                    verbose_name='Nom proposé'
                )),
                ('date_demande', models.DateTimeField(
                    auto_now_add=True,
                    verbose_name='Date de demande'
                )),
                ('date_validation', models.DateTimeField(
                    blank=True,
                    null=True,
                    verbose_name='Date de validation'
                )),
                ('date_fusion', models.DateTimeField(
                    blank=True,
                    null=True,
                    verbose_name='Date de fusion effective'
                )),
                ('competition', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='fusions',
                    to='competitions.competition',
                    verbose_name='Compétition'
                )),
                ('equipe_demandeur', models.ForeignKey(
                    help_text='Équipe qui initie la demande de fusion',
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='fusions_initiees',
                    to='competitions.equipe',
                    verbose_name='Équipe demandeur'
                )),
                ('equipe_cible', models.ForeignKey(
                    help_text='Équipe avec laquelle fusionner',
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='fusions_recues',
                    to='competitions.equipe',
                    verbose_name='Équipe cible'
                )),
                ('equipe_resultante', models.ForeignKey(
                    blank=True,
                    help_text='Équipe résultant de la fusion (créée après approbation)',
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='fusion_source',
                    to='competitions.equipe',
                    verbose_name='Équipe résultante'
                )),
                ('demandeur', models.ForeignKey(
                    help_text='Utilisateur qui a fait la demande de fusion',
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='fusions_demandees',
                    to=settings.AUTH_USER_MODEL,
                    verbose_name='Demandeur'
                )),
                ('validateur', models.ForeignKey(
                    blank=True,
                    help_text='Utilisateur qui a validé/refusé la fusion',
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='fusions_validees',
                    to=settings.AUTH_USER_MODEL,
                    verbose_name='Validateur'
                )),
            ],
            options={
                'verbose_name': 'Fusion d\'équipes',
                'verbose_name_plural': 'Fusions d\'équipes',
                'ordering': ['-date_demande'],
            },
        ),
        # Contrainte d'unicité pour éviter les demandes de fusion en double
        migrations.AddConstraint(
            model_name='teammerge',
            constraint=models.UniqueConstraint(
                fields=['competition', 'equipe_demandeur', 'equipe_cible'],
                condition=models.Q(status__in=['pending', 'approved']),
                name='unique_pending_fusion'
            ),
        ),
    ]
