# Generated by Django 5.1.6 on 2025-12-09
# Sprint 3: Phase Finale et Podium équipe complet (REQ-05)

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0019_sprint2_entente_teammerge'),
    ]

    operations = [
        # Sprint 3.1: Création du modèle PhaseFinale
        migrations.CreateModel(
            name='PhaseFinale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(
                    choices=[
                        ('huitiemes', 'Huitièmes de finale'),
                        ('quarts', 'Quarts de finale'),
                        ('demis', 'Demi-finales'),
                        ('petite_finale', 'Petite finale (3ème place)'),
                        ('finale', 'Finale'),
                    ],
                    default='demis',
                    max_length=20,
                    verbose_name='Phase'
                )),
                ('status', models.CharField(
                    choices=[
                        ('draft', 'Brouillon'),
                        ('active', 'Active'),
                        ('completed', 'Terminée'),
                        ('cancelled', 'Annulée'),
                    ],
                    default='draft',
                    max_length=20,
                    verbose_name='Statut'
                )),
                ('qualifies_par_poule', models.PositiveSmallIntegerField(
                    default=2,
                    help_text='Nombre de premiers de chaque poule qualifiés',
                    verbose_name='Qualifiés par poule'
                )),
                ('avec_petite_finale', models.BooleanField(
                    default=True,
                    help_text='Activer le match pour la 3ème place',
                    verbose_name='Avec petite finale'
                )),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créée le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mise à jour le')),
                ('competition', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='phases_finales',
                    to='competitions.competition',
                    verbose_name='Compétition'
                )),
            ],
            options={
                'verbose_name': 'Phase finale',
                'verbose_name_plural': 'Phases finales',
                'ordering': ['competition', '-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='phasefinale',
            constraint=models.UniqueConstraint(
                fields=['competition', 'phase'],
                name='unique_phase_per_competition'
            ),
        ),

        # Sprint 3.2: Création du modèle CombatPhaseFinale
        migrations.CreateModel(
            name='CombatPhaseFinale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordre', models.PositiveSmallIntegerField(
                    default=0,
                    help_text='Position dans le bracket (1 = premier match)',
                    verbose_name='Ordre'
                )),
                ('equipe1_source', models.CharField(
                    blank=True,
                    help_text="Ex: '1er Poule A' ou 'Vainqueur QF1'",
                    max_length=50,
                    verbose_name='Source équipe 1'
                )),
                ('equipe2_source', models.CharField(
                    blank=True,
                    help_text="Ex: '2ème Poule B' ou 'Perdant DF1'",
                    max_length=50,
                    verbose_name='Source équipe 2'
                )),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('phase_finale', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='combats',
                    to='competitions.phasefinale',
                    verbose_name='Phase finale'
                )),
                ('combat', models.OneToOneField(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='info_phase_finale',
                    to='competitions.combat',
                    verbose_name='Combat'
                )),
                ('combat_suivant', models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='combats_precedents',
                    to='competitions.combatphasefinale',
                    verbose_name='Combat suivant'
                )),
            ],
            options={
                'verbose_name': 'Combat de phase finale',
                'verbose_name_plural': 'Combats de phases finales',
                'ordering': ['phase_finale', 'ordre'],
            },
        ),

        # Sprint 3.3: Création du modèle PodiumEquipe
        migrations.CreateModel(
            name='PodiumEquipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.PositiveSmallIntegerField(
                    choices=[
                        (1, '1ère place - Or'),
                        (2, '2ème place - Argent'),
                        (3, '3ème place - Bronze'),
                        (4, '4ème place'),
                        (5, '5ème place'),
                    ],
                    verbose_name='Place'
                )),
                ('victoires', models.PositiveSmallIntegerField(default=0, verbose_name='Victoires')),
                ('defaites', models.PositiveSmallIntegerField(default=0, verbose_name='Défaites')),
                ('nuls', models.PositiveSmallIntegerField(default=0, verbose_name='Matchs nuls')),
                ('points_marques', models.PositiveIntegerField(default=0, verbose_name='Points marqués')),
                ('points_encaisses', models.PositiveIntegerField(default=0, verbose_name='Points encaissés')),
                ('membres_details', models.JSONField(
                    blank=True,
                    default=dict,
                    help_text='JSON avec détails de chaque membre (nom, rôle, stats)',
                    verbose_name='Détails des membres'
                )),
                ('is_fusion', models.BooleanField(default=False, verbose_name='Équipe fusionnée')),
                ('clubs_partenaires', models.CharField(
                    blank=True,
                    help_text='Liste des clubs si équipe multi-clubs',
                    max_length=255,
                    verbose_name='Clubs partenaires'
                )),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('competition', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='podiums_equipes',
                    to='competitions.competition',
                    verbose_name='Compétition'
                )),
                ('equipe', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='podiums',
                    to='competitions.equipe',
                    verbose_name='Équipe'
                )),
            ],
            options={
                'verbose_name': 'Podium équipe',
                'verbose_name_plural': 'Podiums équipes',
                'ordering': ['competition', 'place'],
            },
        ),
        migrations.AddConstraint(
            model_name='podiumequipe',
            constraint=models.UniqueConstraint(
                fields=['competition', 'place'],
                name='unique_place_per_competition'
            ),
        ),
    ]
