# Generated by Django 5.1.6 on 2025-12-09
# Fix: Add role field to Entente and make equipe_accueil nullable

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0020_sprint3_phase_finale_podium'),
    ]

    operations = [
        # Add role field to Entente
        migrations.AddField(
            model_name='entente',
            name='role',
            field=models.CharField(
                choices=[('titulaire', 'Titulaire'), ('remplacant', 'Remplaçant')],
                default='titulaire',
                max_length=20,
                verbose_name='Rôle prévu'
            ),
        ),
        # Make equipe_accueil nullable (can be assigned later)
        migrations.AlterField(
            model_name='entente',
            name='equipe_accueil',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=models.CASCADE,
                related_name='ententes_recues',
                to='competitions.equipe',
                verbose_name="Équipe d'accueil"
            ),
        ),
    ]
