# Generated by Django 5.1.6 on 2025-12-09 22:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0021_fix_entente_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AireCombat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Ex: Tatami 1, Aire A, Zone Combat 1', max_length=50, verbose_name="Nom de l'aire")),
                ('numero', models.PositiveSmallIntegerField(default=1, help_text="Numéro d'ordre de l'aire", verbose_name='Numéro')),
                ('pin_code', models.CharField(help_text='Code PIN à 4-6 chiffres pour accéder à cette aire', max_length=6, verbose_name='Code PIN')),
                ('access_token', models.UUIDField(default=uuid.uuid4, editable=False, help_text="Token unique pour l'URL d'accès", unique=True)),
                ('is_active', models.BooleanField(default=True, help_text="Si désactivée, l'aire n'est plus accessible", verbose_name='Active')),
                ('couleur', models.CharField(choices=[('blue', 'Bleu'), ('red', 'Rouge'), ('green', 'Vert'), ('yellow', 'Jaune'), ('purple', 'Violet'), ('orange', 'Orange'), ('teal', 'Turquoise'), ('pink', 'Rose')], default='blue', help_text="Couleur d'identification de l'aire", max_length=20, verbose_name='Couleur')),
                ('description', models.TextField(blank=True, help_text='Notes ou instructions spécifiques pour cette aire', verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('last_accessed', models.DateTimeField(blank=True, help_text="Dernière fois que quelqu'un s'est connecté à cette aire", null=True, verbose_name='Dernier accès')),
            ],
            options={
                'verbose_name': 'Aire de combat',
                'verbose_name_plural': 'Aires de combat',
                'ordering': ['competition', 'numero'],
            },
        ),
        migrations.CreateModel(
            name='AireCombatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('user_agent', models.CharField(blank=True, max_length=255, verbose_name='User Agent')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Démarré le')),
                ('last_activity', models.DateTimeField(auto_now=True, verbose_name='Dernière activité')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='Terminé le')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': "Session d'aire",
                'verbose_name_plural': "Sessions d'aires",
                'ordering': ['-started_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='membreequipe',
            options={'ordering': ['equipe', 'est_remplacant', 'ordre'], 'verbose_name': "Membre d'équipe", 'verbose_name_plural': "Membres d'équipe"},
        ),
        migrations.AlterModelOptions(
            name='teammerge',
            options={'ordering': ['-date_demande'], 'verbose_name': "Fusion d'équipe", 'verbose_name_plural': "Fusions d'équipes"},
        ),
        migrations.RemoveConstraint(
            model_name='entente',
            name='unique_entente_per_competition',
        ),
        migrations.RemoveConstraint(
            model_name='phasefinale',
            name='unique_phase_per_competition',
        ),
        migrations.RemoveConstraint(
            model_name='podiumequipe',
            name='unique_place_per_competition',
        ),
        migrations.RemoveConstraint(
            model_name='teammerge',
            name='unique_pending_fusion',
        ),
        migrations.AlterField(
            model_name='entente',
            name='club_accueil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ententes_entrantes', to='competitions.club', verbose_name="Club d'accueil"),
        ),
        migrations.AlterField(
            model_name='entente',
            name='club_origine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ententes_sortantes', to='competitions.club', verbose_name="Club d'origine"),
        ),
        migrations.AlterField(
            model_name='entente',
            name='commentaire_validation',
            field=models.TextField(blank=True, verbose_name='Commentaire de validation'),
        ),
        migrations.AlterField(
            model_name='entente',
            name='demandeur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ententes_demandees', to=settings.AUTH_USER_MODEL, verbose_name='Demandé par'),
        ),
        migrations.AlterField(
            model_name='entente',
            name='pratiquant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ententes', to='competitions.practitioner', verbose_name='Pratiquant prêté'),
        ),
        migrations.AlterField(
            model_name='entente',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvée'), ('rejected', 'Refusée'), ('cancelled', 'Annulée'), ('expired', 'Expirée')], default='pending', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='entente',
            name='validateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ententes_validees', to=settings.AUTH_USER_MODEL, verbose_name='Validateur'),
        ),
        migrations.AlterField(
            model_name='equipe',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('pending_fusion', 'Fusion en attente'), ('fusion_complete', 'Fusion completee'), ('archived', 'Archivée')], default='active', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='membreequipe',
            name='equipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='competitions.equipe', verbose_name='Équipe'),
        ),
        migrations.AlterField(
            model_name='membreequipe',
            name='ordre',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Ordre de passage'),
        ),
        migrations.AlterField(
            model_name='teammerge',
            name='commentaire_validation',
            field=models.TextField(blank=True, verbose_name='Commentaire'),
        ),
        migrations.AlterField(
            model_name='teammerge',
            name='demandeur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fusions_demandees', to=settings.AUTH_USER_MODEL, verbose_name='Demandé par'),
        ),
        migrations.AlterField(
            model_name='teammerge',
            name='equipe_cible',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fusions_recues', to='competitions.equipe', verbose_name='Équipe cible'),
        ),
        migrations.AlterField(
            model_name='teammerge',
            name='equipe_demandeur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fusions_initiees', to='competitions.equipe', verbose_name='Équipe demandeuse'),
        ),
        migrations.AlterField(
            model_name='teammerge',
            name='equipe_resultante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fusion_source', to='competitions.equipe', verbose_name='Équipe résultante'),
        ),
        migrations.AlterField(
            model_name='teammerge',
            name='nom_equipe_proposee',
            field=models.CharField(blank=True, help_text="Nom suggéré pour l'équipe fusionnée", max_length=100, verbose_name='Nom proposé'),
        ),
        migrations.AlterField(
            model_name='teammerge',
            name='raison',
            field=models.TextField(blank=True, help_text='Explication de la demande de fusion', verbose_name='Raison de la fusion'),
        ),
        migrations.AlterField(
            model_name='teammerge',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvée'), ('rejected', 'Refusée'), ('completed', 'Complétée'), ('cancelled', 'Annulée')], default='pending', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='teammerge',
            name='validateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fusions_validees', to=settings.AUTH_USER_MODEL, verbose_name='Validateur'),
        ),
        migrations.AlterUniqueTogether(
            name='phasefinale',
            unique_together={('competition', 'phase')},
        ),
        migrations.AlterUniqueTogether(
            name='podiumequipe',
            unique_together={('competition', 'place')},
        ),
        migrations.AddField(
            model_name='airecombat',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='aires_combat', to='competitions.competitioncategory', verbose_name='Catégories assignées'),
        ),
        migrations.AddField(
            model_name='airecombat',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aires_combat', to='competitions.competition', verbose_name='Compétition'),
        ),
        migrations.AddField(
            model_name='airecombatsession',
            name='aire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='competitions.airecombat', verbose_name='Aire de combat'),
        ),
        migrations.AlterUniqueTogether(
            name='airecombat',
            unique_together={('competition', 'numero')},
        ),
    ]
