# Generated by Django 5.1.6 on 2025-12-10 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0024_add_category_description_to_poule'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitioncategory',
            name='combat_mode',
            field=models.CharField(choices=[('team', 'Équipe'), ('individual', 'Individuel')], default='team', help_text='Mode de combat pour cette catégorie (équipe ou individuel)', max_length=20, verbose_name='Mode combat'),
        ),
    ]
