# Generated by Django 5.1.6 on 2025-12-12 08:47

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0025_add_combat_mode_to_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PodiumEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(choices=[(1, '1er - Or'), (2, '2ème - Argent'), (3, '3ème - Bronze')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)], verbose_name='Position')),
                ('is_manual', models.BooleanField(default=True, help_text="True si ajouté manuellement par l'organisateur", verbose_name='Ajout manuel')),
                ('honorary_title', models.CharField(blank=True, help_text='Ex: Mérite, Encouragement (affiché si show_title=True)', max_length=100, verbose_name='Titre honorifique')),
                ('show_title', models.BooleanField(default=False, verbose_name='Afficher le titre')),
                ('internal_note', models.TextField(blank=True, help_text='Note visible uniquement par les organisateurs', verbose_name='Note interne')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_podium_entries', to=settings.AUTH_USER_MODEL, verbose_name='Ajouté par')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='podium_entries', to='competitions.competitioncategory', verbose_name='Catégorie')),
                ('practitioner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='podium_entries', to='competitions.practitioner', verbose_name='Pratiquant')),
            ],
            options={
                'verbose_name': 'Entrée au podium',
                'verbose_name_plural': 'Entrées au podium',
                'ordering': ['category', 'position', 'created_at'],
                'unique_together': {('category', 'practitioner')},
            },
        ),
    ]
