# Generated by Django 5.1.6 on 2026-01-05 13:53

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0027_add_metadata_to_federation'),
        ('organizations', '0011_add_organization_video_links'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom du modèle')),
                ('template_type', models.CharField(choices=[('judge', 'Certification de juge'), ('grade', 'Diplôme de grade'), ('participation', 'Attestation de participation'), ('achievement', 'Certificat de réussite')], default='judge', max_length=20, verbose_name='Type de certificat')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('orientation', models.CharField(choices=[('landscape', 'Paysage'), ('portrait', 'Portrait')], default='landscape', max_length=20, verbose_name='Orientation')),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='certificates/backgrounds/', verbose_name='Image de fond')),
                ('logo_position', models.CharField(default='top-center', help_text='Position: top-left, top-center, top-right', max_length=20, verbose_name='Position du logo')),
                ('primary_color', models.CharField(default='#1a1f2e', max_length=7, verbose_name='Couleur primaire')),
                ('secondary_color', models.CharField(default='#c9a227', max_length=7, verbose_name='Couleur secondaire')),
                ('text_color', models.CharField(default='#333333', max_length=7, verbose_name='Couleur du texte')),
                ('title_font_size', models.PositiveIntegerField(default=36, verbose_name='Taille titre (pt)')),
                ('body_font_size', models.PositiveIntegerField(default=14, verbose_name='Taille corps (pt)')),
                ('header_text', models.CharField(blank=True, max_length=200, verbose_name="Texte d'en-tête")),
                ('title_text', models.CharField(default='CERTIFICAT', max_length=200, verbose_name='Texte du titre')),
                ('body_template', models.TextField(default='Certifie que {recipient_name} a obtenu la certification de {certification_type} niveau {level} en date du {date}.', help_text='Variables disponibles: {recipient_name}, {certification_type}, {level}, {date}, {certification_number}, {organization_name}, {discipline}', verbose_name='Template du corps')),
                ('footer_text', models.TextField(blank=True, verbose_name='Texte de pied de page')),
                ('show_signature_line', models.BooleanField(default=True, verbose_name='Afficher ligne de signature')),
                ('signature_label', models.CharField(default='Le Président', max_length=100, verbose_name='Label signature')),
                ('signature_image', models.ImageField(blank=True, null=True, upload_to='certificates/signatures/', verbose_name='Image de signature')),
                ('show_stamp', models.BooleanField(default=True, verbose_name='Afficher cachet')),
                ('stamp_image', models.ImageField(blank=True, null=True, upload_to='certificates/stamps/', verbose_name='Image du cachet')),
                ('include_qr_code', models.BooleanField(default=True, verbose_name='Inclure QR code de vérification')),
                ('qr_position', models.CharField(default='bottom-right', max_length=20, verbose_name='Position QR code')),
                ('is_default', models.BooleanField(default=False, verbose_name='Modèle par défaut')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_certificate_templates', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificate_templates', to='organizations.organization', verbose_name='Organisation')),
            ],
            options={
                'verbose_name': 'Modèle de certificat',
                'verbose_name_plural': 'Modèles de certificats',
                'ordering': ['organization', 'template_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='IssuedCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID du certificat')),
                ('verification_code', models.CharField(editable=False, max_length=12, unique=True, verbose_name='Code de vérification')),
                ('certificate_number', models.CharField(max_length=50, verbose_name='Numéro de certificat')),
                ('title', models.CharField(max_length=200, verbose_name='Titre du certificat')),
                ('recipient_name', models.CharField(max_length=200, verbose_name='Nom du bénéficiaire')),
                ('certification_type', models.CharField(max_length=100, verbose_name='Type de certification')),
                ('level', models.CharField(blank=True, max_length=50, verbose_name='Niveau')),
                ('discipline', models.CharField(blank=True, max_length=100, verbose_name='Discipline')),
                ('issue_date', models.DateField(default=django.utils.timezone.now, verbose_name="Date d'émission")),
                ('valid_from', models.DateField(default=django.utils.timezone.now, verbose_name='Valide à partir de')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name="Valide jusqu'au")),
                ('status', models.CharField(choices=[('valid', 'Valide'), ('expired', 'Expiré'), ('revoked', 'Révoqué'), ('suspended', 'Suspendu')], default='valid', max_length=20, verbose_name='Statut')),
                ('revocation_reason', models.TextField(blank=True, verbose_name='Raison de révocation')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='Révoqué le')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='certificates/issued/', verbose_name='Fichier PDF')),
                ('notes', models.TextField(blank=True, verbose_name='Notes internes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('download_count', models.PositiveIntegerField(default=0, verbose_name='Nombre de téléchargements')),
                ('verification_count', models.PositiveIntegerField(default=0, verbose_name='Nombre de vérifications')),
                ('last_verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Dernière vérification')),
                ('certification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_certificates', to='competitions.judgecertification', verbose_name='Type de certification')),
                ('exam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_certificates', to='competitions.exam', verbose_name='Examen associé')),
                ('issued_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_certificates_as_issuer', to=settings.AUTH_USER_MODEL, verbose_name='Émis par')),
                ('judge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates', to='competitions.judge', verbose_name='Profil juge')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issued_certificates', to='organizations.organization', verbose_name='Organisation émettrice')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_certificates', to=settings.AUTH_USER_MODEL, verbose_name='Bénéficiaire')),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revoked_certificates', to=settings.AUTH_USER_MODEL, verbose_name='Révoqué par')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_certificates', to='competitions.certificatetemplate', verbose_name='Modèle utilisé')),
            ],
            options={
                'verbose_name': 'Certificat émis',
                'verbose_name_plural': 'Certificats émis',
                'ordering': ['-issue_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CertificationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_level', models.CharField(choices=[('novice', 'Novice'), ('regional', 'Régional'), ('national', 'National'), ('international', 'International')], default='regional', max_length=20, verbose_name='Niveau demandé')),
                ('motivation', models.TextField(help_text='Expliquez pourquoi vous demandez cette certification', verbose_name='Motivation')),
                ('experience_description', models.TextField(blank=True, verbose_name="Description de l'expérience")),
                ('cv_file', models.FileField(blank=True, null=True, upload_to='certification_requests/cv/', verbose_name='CV')),
                ('supporting_documents', models.FileField(blank=True, null=True, upload_to='certification_requests/documents/', verbose_name='Documents justificatifs')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('under_review', "En cours d'examen"), ('approved', 'Approuvée'), ('rejected', 'Rejetée'), ('cancelled', 'Annulée')], default='pending', max_length=20, verbose_name='Statut')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Examiné le')),
                ('reviewer_notes', models.TextField(blank=True, verbose_name="Notes de l'examinateur")),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Raison du rejet')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certification_requests', to=settings.AUTH_USER_MODEL, verbose_name='Demandeur')),
                ('certification_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='competitions.judgecertification', verbose_name='Type de certification demandée')),
                ('judge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certification_requests', to='competitions.judge', verbose_name='Profil juge')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certification_requests', to='organizations.organization', verbose_name='Organisation (fédération)')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_certification_requests', to=settings.AUTH_USER_MODEL, verbose_name='Examiné par')),
                ('issued_certificate', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certification_request', to='competitions.issuedcertificate', verbose_name='Certificat émis')),
            ],
            options={
                'verbose_name': 'Demande de certification',
                'verbose_name_plural': 'Demandes de certification',
                'ordering': ['-created_at'],
            },
        ),
    ]
