# Generated by Django 5.1.4 on 2025-05-12 09:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('competitions', '0001_initial'),
        ('grades', '0001_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legacy_clubs', to='organizations.organization', verbose_name='Organisation associée'),
        ),
        migrations.AddField(
            model_name='club',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_clubs', to=settings.AUTH_USER_MODEL, verbose_name='Propriétaire'),
        ),
        migrations.AddField(
            model_name='clubadministrator',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='administrators', to='competitions.club', verbose_name='Club'),
        ),
        migrations.AddField(
            model_name='clubadministrator',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='club_administrators', to='organizations.organization', verbose_name='Organisation'),
        ),
        migrations.AddField(
            model_name='clubadministrator',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club_admin_roles', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AddField(
            model_name='clubrole',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='clubteam',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teams', to='competitions.club', verbose_name='Club (obsolète)'),
        ),
        migrations.AddField(
            model_name='clubteam',
            name='members',
            field=models.ManyToManyField(related_name='team_memberships', to=settings.AUTH_USER_MODEL, verbose_name='Membres'),
        ),
        migrations.AddField(
            model_name='clubteam',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club_teams', to='organizations.organization', verbose_name='Organisation'),
        ),
        migrations.AddField(
            model_name='competition',
            name='organizing_organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organized_competitions', to='organizations.organization', verbose_name='Organisation organisatrice'),
        ),
        migrations.AddField(
            model_name='clubteam',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competition_teams', to='competitions.competition', verbose_name='Compétition'),
        ),
        migrations.AddField(
            model_name='competitioncategory',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='competitions.competition'),
        ),
        migrations.AddField(
            model_name='competitioncategory',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_in_competitions', to='competitions.categorytemplate', verbose_name='Template source'),
        ),
        migrations.AddField(
            model_name='categoryschedule',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='competitions.competitioncategory', verbose_name='Catégorie'),
        ),
        migrations.AddField(
            model_name='competitionranking',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rankings', to='competitions.competitioncategory', verbose_name='Catégorie'),
        ),
        migrations.AddField(
            model_name='competitionranking',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rankings', to='competitions.competition', verbose_name='Compétition'),
        ),
        migrations.AddField(
            model_name='competitionregistration',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='registrations', to='competitions.competitioncategory'),
        ),
        migrations.AddField(
            model_name='competitionregistration',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='competitions.competition'),
        ),
        migrations.AddField(
            model_name='competitionrole',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='competitions.competition'),
        ),
        migrations.AddField(
            model_name='competitionregistration',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='registrations', to='competitions.competitionrole'),
        ),
        migrations.AddField(
            model_name='competitionschedule',
            name='competition',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='competitions.competition', verbose_name='Compétition'),
        ),
        migrations.AddField(
            model_name='competitionschedule',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_schedules', to=settings.AUTH_USER_MODEL, verbose_name='Mis à jour par'),
        ),
        migrations.AddField(
            model_name='categoryschedule',
            name='competition_schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_schedules', to='competitions.competitionschedule', verbose_name='Planning de compétition'),
        ),
        migrations.AddField(
            model_name='competitionregistration',
            name='competition_types',
            field=models.ManyToManyField(blank=True, related_name='registrations', to='competitions.competitiontype'),
        ),
        migrations.AddField(
            model_name='competitioncategory',
            name='competition_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='competitions.competitiontype'),
        ),
        migrations.AddField(
            model_name='competition',
            name='competition_types',
            field=models.ManyToManyField(related_name='competitions', to='competitions.competitiontype'),
        ),
        migrations.AddField(
            model_name='categorytemplate',
            name='competition_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_templates', to='competitions.competitiontype', verbose_name='Type de compétition'),
        ),
        migrations.AddField(
            model_name='discipline',
            name='grading_system',
            field=models.ForeignKey(blank=True, help_text='Configuration du système de grades pour cette discipline', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disciplines', to='grades.gradingsystem', verbose_name='Système de grade'),
        ),
        migrations.AddField(
            model_name='discipline',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_disciplines', to='organizations.organization', verbose_name='Fédération principale'),
        ),
        migrations.AddField(
            model_name='competitiontype',
            name='discipline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competition_types', to='competitions.discipline'),
        ),
        migrations.AddField(
            model_name='competition',
            name='discipline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='competitions', to='competitions.discipline', verbose_name='Discipline'),
        ),
        migrations.AddField(
            model_name='club',
            name='disciplines',
            field=models.ManyToManyField(blank=True, related_name='club_disciplines', to='competitions.discipline', verbose_name='Disciplines'),
        ),
        migrations.AddField(
            model_name='club',
            name='main_discipline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_clubs', to='competitions.discipline', verbose_name='Discipline principale'),
        ),
        migrations.AddField(
            model_name='categorytemplate',
            name='discipline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_templates', to='competitions.discipline', verbose_name='Discipline'),
        ),
        migrations.AddField(
            model_name='federation',
            name='disciplines',
            field=models.ManyToManyField(blank=True, related_name='federation_disciplines', to='competitions.discipline', verbose_name='Disciplines'),
        ),
        migrations.AddField(
            model_name='federation',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legacy_federations', to='organizations.organization', verbose_name='Organisation associée'),
        ),
        migrations.AddField(
            model_name='federation',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_federations', to=settings.AUTH_USER_MODEL, verbose_name='Propriétaire (déprécié)'),
        ),
        migrations.AddField(
            model_name='affiliationrequest',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affiliation_requests', to='competitions.federation', verbose_name='Fédération'),
        ),
        migrations.AddField(
            model_name='federationadministrator',
            name='federation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='administrators', to='competitions.federation', verbose_name='Fédération'),
        ),
        migrations.AddField(
            model_name='federationadministrator',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='federation_administrators', to='organizations.organization', verbose_name='Organisation'),
        ),
        migrations.AddField(
            model_name='federationadministrator',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='federation_admin_roles', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AddField(
            model_name='judge',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certified_judges', to='organizations.organization', verbose_name='Fédération certifiante'),
        ),
        migrations.AddField(
            model_name='judge',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='judge_profile', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AddField(
            model_name='judgeapplication',
            name='disciplines',
            field=models.ManyToManyField(related_name='judge_applications', to='competitions.discipline'),
        ),
        migrations.AddField(
            model_name='judgeapplication',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='judgeapplication',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='judgeassignment',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='judge_assignments_made', to=settings.AUTH_USER_MODEL, verbose_name='Assigné par'),
        ),
        migrations.AddField(
            model_name='judgeassignment',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='judge_assignments', to='competitions.competitioncategory', verbose_name='Catégorie'),
        ),
        migrations.AddField(
            model_name='judgeassignment',
            name='chief_judge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chief_judge_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Juge en chef'),
        ),
        migrations.AddField(
            model_name='judgeassignment',
            name='registration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='judge_assignments', to='competitions.competitionregistration', verbose_name='Inscription'),
        ),
        migrations.AddField(
            model_name='judgeassignment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='judge_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AddField(
            model_name='judgecertification',
            name='discipline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='competitions.discipline', verbose_name='Discipline'),
        ),
        migrations.AddField(
            model_name='judgecertification',
            name='examiner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='examiner_certifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='judgecertification',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='judge_certifications', to='organizations.organization', verbose_name='Organisation'),
        ),
        migrations.AddField(
            model_name='certificationregistration',
            name='certification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='competitions.judgecertification', verbose_name='Certification'),
        ),
        migrations.AddField(
            model_name='judgecompetitionassignment',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competition_judge_assignments', to='competitions.competitioncategory'),
        ),
        migrations.AddField(
            model_name='judgecompetitionassignment',
            name='registration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='competitions.competitionregistration'),
        ),
        migrations.AddField(
            model_name='judgequalification',
            name='discipline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='judge_qualifications', to='competitions.discipline', verbose_name='Discipline'),
        ),
        migrations.AddField(
            model_name='judgequalification',
            name='issuing_organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_qualifications', to='organizations.organization', verbose_name='Fédération émettrice'),
        ),
        migrations.AddField(
            model_name='judgesettings',
            name='judge',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='competitions.judge'),
        ),
        migrations.AddField(
            model_name='judgesubmissionstatus',
            name='judge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competitions.judge'),
        ),
        migrations.AddField(
            model_name='judgetechnicalapplication',
            name='disciplines',
            field=models.ManyToManyField(related_name='judge_technical_applications', to='competitions.discipline', verbose_name='Disciplines'),
        ),
        migrations.AddField(
            model_name='judgetechnicalapplication',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_judge_applications', to=settings.AUTH_USER_MODEL, verbose_name='Examiné par'),
        ),
        migrations.AddField(
            model_name='judgetechnicalapplication',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technical_judge_applications', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AddField(
            model_name='license',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issued_licenses', to='organizations.organization', verbose_name='Fédération'),
        ),
        migrations.AddField(
            model_name='match',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='competitions.competition'),
        ),
        migrations.AddField(
            model_name='matchtimeslot',
            name='category_schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='competitions.categoryschedule', verbose_name='Planning de catégorie'),
        ),
        migrations.AddField(
            model_name='matchtimeslot',
            name='match',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='time_slot', to='competitions.match', verbose_name='Match'),
        ),
        migrations.AddField(
            model_name='membership',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_memberships', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AddField(
            model_name='membership',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='member_subscriptions', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AddField(
            model_name='participantcategoryregistration',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competitions.competitioncategory'),
        ),
        migrations.AddField(
            model_name='participantcategoryregistration',
            name='competition_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competitions.competitiontype'),
        ),
        migrations.AddField(
            model_name='participantcategoryregistration',
            name='registration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_registrations', to='competitions.competitionregistration'),
        ),
        migrations.AddField(
            model_name='performance',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performances', to='competitions.competitioncategory'),
        ),
        migrations.AddField(
            model_name='judgesubmissionstatus',
            name='performance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competitions.performance'),
        ),
        migrations.AddField(
            model_name='practitioner',
            name='disciplines',
            field=models.ManyToManyField(blank=True, related_name='practitioners', to='competitions.discipline', verbose_name='Disciplines pratiquées'),
        ),
        migrations.AddField(
            model_name='practitioner',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='practitioner_current_grades', to='grades.grade', verbose_name='Grade actuel'),
        ),
        migrations.AddField(
            model_name='practitioner',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='practitioners', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='practitioner',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='practitioners', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='performance',
            name='practitioner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performances', to='competitions.practitioner'),
        ),
        migrations.AddField(
            model_name='membership',
            name='practitioner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='competitions.practitioner'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='practitioner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medical_record', to='competitions.practitioner'),
        ),
        migrations.AddField(
            model_name='medicalcertificate',
            name='practitioner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_certificates', to='competitions.practitioner'),
        ),
        migrations.AddField(
            model_name='match',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='matches', to='competitions.practitioner'),
        ),
        migrations.AddField(
            model_name='license',
            name='practitioner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licenses', to='competitions.practitioner'),
        ),
        migrations.AddField(
            model_name='judgequalification',
            name='practitioner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualifications', to='competitions.practitioner', verbose_name='Pratiquant'),
        ),
        migrations.AddField(
            model_name='judge',
            name='practitioner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='judge', to='competitions.practitioner', verbose_name='Pratiquant'),
        ),
        migrations.AddField(
            model_name='competitionregistration',
            name='practitioner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='competitions.practitioner'),
        ),
        migrations.AddField(
            model_name='competitionranking',
            name='practitioner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rankings', to='competitions.practitioner', verbose_name='Pratiquant'),
        ),
        migrations.AddField(
            model_name='certificationregistration',
            name='practitioner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cert_registrations', to='competitions.practitioner'),
        ),
        migrations.AddField(
            model_name='practitionerdiscipline',
            name='discipline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discipline_practitioners', to='competitions.discipline'),
        ),
        migrations.AddField(
            model_name='practitionerdiscipline',
            name='practitioner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practitioner_disciplines', to='competitions.practitioner'),
        ),
        migrations.AddField(
            model_name='practitionerdiscipline',
            name='reference_instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to=settings.AUTH_USER_MODEL, verbose_name='Instructeur référent'),
        ),
        migrations.AddField(
            model_name='practitionerqualification',
            name='certified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certified_qualifications', to=settings.AUTH_USER_MODEL, verbose_name='Certifié par'),
        ),
        migrations.AddField(
            model_name='practitionerqualification',
            name='discipline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualifications', to='competitions.discipline', verbose_name='Discipline'),
        ),
        migrations.AddField(
            model_name='practitionerqualification',
            name='practitioner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practitioner_qualifications', to='competitions.practitioner'),
        ),
        migrations.AddField(
            model_name='schedulechange',
            name='category_schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='changes', to='competitions.categoryschedule', verbose_name='Planning de catégorie'),
        ),
        migrations.AddField(
            model_name='schedulechange',
            name='changed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_changes', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par'),
        ),
        migrations.AddField(
            model_name='schedulechange',
            name='competition_schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='competitions.competitionschedule', verbose_name='Planning'),
        ),
        migrations.AddField(
            model_name='score',
            name='judge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='competitions.judge'),
        ),
        migrations.AddField(
            model_name='score',
            name='performance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='competitions.performance'),
        ),
        migrations.AddField(
            model_name='scoringconfiguration',
            name='category',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scoring_configuration', to='competitions.competitioncategory', verbose_name='Catégorie'),
        ),
        migrations.AddField(
            model_name='scoringcriterion',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scoring_criteria', to='competitions.competitioncategory'),
        ),
        migrations.AddField(
            model_name='score',
            name='criterion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_scores', to='competitions.scoringcriterion'),
        ),
        migrations.AddField(
            model_name='style',
            name='discipline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='styles', to='competitions.discipline', verbose_name='Discipline'),
        ),
        migrations.AddField(
            model_name='tatamischedule',
            name='competition_schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tatami_schedules', to='competitions.competitionschedule', verbose_name='Planning de compétition'),
        ),
        migrations.AddField(
            model_name='tatamischedule',
            name='responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_for_tatamis', to=settings.AUTH_USER_MODEL, verbose_name='Responsable'),
        ),
        migrations.AddField(
            model_name='categoryschedule',
            name='tatami',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_schedules', to='competitions.tatamischedule', verbose_name='Tatami'),
        ),
        migrations.AddField(
            model_name='technicalperformance',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technical_performances', to='competitions.competitioncategory', verbose_name='Catégorie'),
        ),
        migrations.AddField(
            model_name='technicalperformance',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technical_performances', to='competitions.competition', verbose_name='Compétition'),
        ),
        migrations.AddField(
            model_name='technicalperformance',
            name='practitioner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technical_performances', to='competitions.practitioner', verbose_name='Pratiquant'),
        ),
        migrations.AddField(
            model_name='technicalscore',
            name='criterion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technical_scores', to='competitions.scoringcriterion', verbose_name='Critère'),
        ),
        migrations.AddField(
            model_name='technicalscore',
            name='judge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technical_scores', to=settings.AUTH_USER_MODEL, verbose_name='Juge'),
        ),
        migrations.AddField(
            model_name='technicalscore',
            name='performance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='competitions.technicalperformance', verbose_name='Prestation'),
        ),
        migrations.AddField(
            model_name='technique',
            name='discipline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='techniques', to='competitions.discipline', verbose_name='Discipline'),
        ),
        migrations.AddField(
            model_name='technique',
            name='minimum_grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='required_techniques', to='grades.grade', verbose_name='Grade minimum requis'),
        ),
        migrations.AddField(
            model_name='userclubrole',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_roles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userclubrole',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='userclubrole',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='competitions.clubrole'),
        ),
        migrations.AddField(
            model_name='userclubrole',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_profiles', to='competitions.club', verbose_name='Organisation'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='clubadministrator',
            unique_together={('user', 'club'), ('user', 'organization')},
        ),
        migrations.AlterUniqueTogether(
            name='clubrole',
            unique_together={('name', 'organization')},
        ),
        migrations.AlterUniqueTogether(
            name='competitionrole',
            unique_together={('competition', 'name')},
        ),
        migrations.AddConstraint(
            model_name='competitioncategory',
            constraint=models.UniqueConstraint(fields=('competition', 'name'), name='unique_category_per_competition'),
        ),
        migrations.AlterUniqueTogether(
            name='categorytemplate',
            unique_together={('discipline', 'competition_type', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='federationadministrator',
            unique_together={('user', 'federation'), ('user', 'organization')},
        ),
        migrations.AlterUniqueTogether(
            name='judgeassignment',
            unique_together={('registration', 'category', 'assignment_type')},
        ),
        migrations.AlterUniqueTogether(
            name='judgecompetitionassignment',
            unique_together={('registration', 'category', 'assignment_type')},
        ),
        migrations.AlterUniqueTogether(
            name='participantcategoryregistration',
            unique_together={('registration', 'competition_type')},
        ),
        migrations.AlterUniqueTogether(
            name='judgesubmissionstatus',
            unique_together={('judge', 'performance')},
        ),
        migrations.AddIndex(
            model_name='practitioner',
            index=models.Index(fields=['last_name', 'first_name'], name='competition_last_na_3aca86_idx'),
        ),
        migrations.AddIndex(
            model_name='practitioner',
            index=models.Index(fields=['organization'], name='competition_organiz_e186dc_idx'),
        ),
        migrations.AddIndex(
            model_name='practitioner',
            index=models.Index(fields=['user'], name='competition_user_id_f33065_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='license',
            unique_together={('practitioner', 'license_number', 'organization')},
        ),
        migrations.AlterUniqueTogether(
            name='judgequalification',
            unique_together={('practitioner', 'qualification_type', 'discipline')},
        ),
        migrations.AlterUniqueTogether(
            name='competitionregistration',
            unique_together={('practitioner', 'competition')},
        ),
        migrations.AlterUniqueTogether(
            name='competitionranking',
            unique_together={('competition', 'category', 'practitioner')},
        ),
        migrations.AlterUniqueTogether(
            name='practitionerdiscipline',
            unique_together={('practitioner', 'discipline')},
        ),
        migrations.AlterUniqueTogether(
            name='practitionerqualification',
            unique_together={('practitioner', 'qualification_type', 'discipline')},
        ),
        migrations.AlterUniqueTogether(
            name='score',
            unique_together={('performance', 'judge', 'criterion')},
        ),
        migrations.AlterUniqueTogether(
            name='style',
            unique_together={('discipline', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='tatamischedule',
            unique_together={('competition_schedule', 'tatami_number')},
        ),
        migrations.AlterUniqueTogether(
            name='technicalperformance',
            unique_together={('competition', 'category', 'practitioner')},
        ),
        migrations.AlterUniqueTogether(
            name='technicalscore',
            unique_together={('performance', 'judge', 'criterion')},
        ),
        migrations.AlterUniqueTogether(
            name='technique',
            unique_together={('discipline', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='userclubrole',
            unique_together={('user', 'organization', 'role')},
        ),
    ]
