# Generated by Django 3.2.16 on 2025-05-13 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0004_add_competition_result'),
        ('competitions', '0006_fix_technical_score_judge_related_name'),
    ]

    operations = [
    ]