# Generated by Django 3.2.16 on 2025-05-13 11:30

from django.db import migrations


class Migration(migrations.Migration):
    """
    Migration de fusion pour résoudre les conflits entre 
    0008_create_categoryranking et 0009_remove_categoryranking_references.
    """

    dependencies = [
        ('competitions', '0008_create_categoryranking'),
        ('competitions', '0009_remove_categoryranking_references'),
    ]

    operations = [
    ]