# Generated by Django 4.2.11 on 2025-05-30 16:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('competitions', '0003_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('family_name', models.CharField(help_text='Nom principal de la famille (ex: Famille Martin)', max_length=100, verbose_name='Nom de famille')),
                ('billing_address', models.TextField(blank=True, help_text='Adresse principale pour la facturation familiale', verbose_name='Adresse de facturation')),
                ('billing_phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone de contact')),
                ('billing_email', models.EmailField(blank=True, help_text='Email pour recevoir les factures et communications administratives', max_length=254, verbose_name='Email de facturation')),
                ('shared_calendar', models.BooleanField(default=True, help_text='Autoriser la vue consolidée du calendrier familial', verbose_name='Calendrier familial partagé')),
                ('shared_notifications', models.BooleanField(default=True, help_text='Centraliser les notifications au niveau familial', verbose_name='Notifications partagées')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Famille active')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='families', to='organizations.organization')),
                ('primary_responsible', models.ForeignKey(help_text='Parent ou tuteur responsable de la gestion familiale', on_delete=django.db.models.deletion.PROTECT, related_name='managed_families', to=settings.AUTH_USER_MODEL, verbose_name='Responsable principal')),
            ],
            options={
                'verbose_name': 'Famille',
                'verbose_name_plural': 'Familles',
                'ordering': ['family_name'],
            },
        ),
        migrations.CreateModel(
            name='FamilyRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('parent', 'Parent'), ('guardian', 'Tuteur légal'), ('child', 'Enfant'), ('spouse', 'Conjoint(e)'), ('sibling', 'Frère/Sœur'), ('other', 'Autre relation')], max_length=50, unique=True, verbose_name='Nom du rôle')),
                ('can_manage_family', models.BooleanField(default=False, help_text='Autorise la gestion administrative de la famille', verbose_name='Peut gérer la famille')),
                ('can_view_all_data', models.BooleanField(default=True, help_text='Autorise la consultation des données de tous les membres', verbose_name='Peut voir toutes les données')),
                ('can_register_members', models.BooleanField(default=False, help_text="Autorise l'inscription des membres aux compétitions/événements", verbose_name='Peut inscrire les membres')),
            ],
            options={
                'verbose_name': 'Rôle familial',
                'verbose_name_plural': 'Rôles familiaux',
            },
        ),
        migrations.CreateModel(
            name='FamilyPaymentGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('description', models.CharField(help_text='Description du groupe de paiements', max_length=200, verbose_name='Description')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Montant total')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_paid', models.BooleanField(default=False, verbose_name='Payé')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_groups', to='family_management.family', verbose_name='Famille')),
            ],
            options={
                'verbose_name': 'Groupe de paiement familial',
                'verbose_name_plural': 'Groupes de paiements familiaux',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('parent', 'Parent'), ('guardian', 'Tuteur légal'), ('child', 'Enfant'), ('spouse', 'Conjoint(e)'), ('sibling', 'Frère/Sœur'), ('other', 'Autre relation')], default='child', max_length=50, verbose_name='Rôle familial')),
                ('can_manage_others', models.BooleanField(default=False, verbose_name='Peut gérer les autres membres')),
                ('can_make_payments', models.BooleanField(default=False, verbose_name='Peut effectuer des paiements')),
                ('is_active', models.BooleanField(default=True, verbose_name='Membre actif')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('share_calendar', models.BooleanField(default=True, help_text='Afficher les événements de ce membre dans le calendrier familial', verbose_name='Partager le calendrier')),
                ('receive_family_notifications', models.BooleanField(default=True, verbose_name='Recevoir les notifications familiales')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='family_management.family', verbose_name='Famille')),
                ('practitioner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='family_memberships', to='competitions.practitioner', verbose_name='Pratiquant')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='family_memberships', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Membre de famille',
                'verbose_name_plural': 'Membres de famille',
                'unique_together': {('family', 'user'), ('family', 'practitioner')},
            },
        ),
        migrations.CreateModel(
            name='FamilyEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('start_date', models.DateTimeField(verbose_name='Date de début')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Date de fin')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Lieu')),
                ('is_private', models.BooleanField(default=False, help_text='Visible uniquement par la famille', verbose_name='Événement privé')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('concerned_members', models.ManyToManyField(blank=True, related_name='family_events', to='family_management.familymember', verbose_name='Membres concernés')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_family_events', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_events', to='family_management.family', verbose_name='Famille')),
            ],
            options={
                'verbose_name': 'Événement familial',
                'verbose_name_plural': 'Événements familiaux',
                'ordering': ['start_date'],
            },
        ),
    ]
