# Generated by Django 4.2.11 on 2025-05-30 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='description',
            field=models.TextField(blank=True, help_text='Description optionnelle de la famille', verbose_name='Description'),
        ),
    ]
