# Generated by Django 4.2.11 on 2025-05-30 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family_management', '0002_family_description'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='familymember',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='familymember',
            constraint=models.UniqueConstraint(condition=models.Q(('practitioner__isnull', False)), fields=('family', 'practitioner'), name='unique_family_practitioner'),
        ),
        migrations.AddConstraint(
            model_name='familymember',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False), ('practitioner__isnull', True)), fields=('family', 'user'), name='unique_family_user_only'),
        ),
    ]
