# Generated by Django 4.2.11 on 2025-05-30 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family_management', '0003_alter_familymember_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='familymember',
            name='unique_family_practitioner',
        ),
        migrations.RemoveConstraint(
            model_name='familymember',
            name='unique_family_user_only',
        ),
        migrations.AddIndex(
            model_name='familymember',
            index=models.Index(fields=['family', 'practitioner'], name='family_practitioner_idx'),
        ),
        migrations.AddIndex(
            model_name='familymember',
            index=models.Index(fields=['family', 'user'], name='family_user_idx'),
        ),
    ]
