"""
Choix réutilisables pour les formulaires Django
"""

from django.utils.translation import gettext_lazy as _

# Liste des pays selon la norme ISO 3166-1 alpha-2
COUNTRY_CHOICES = [
    ('', _('Sélectionnez un pays')),
    ('AF', _('Afghanistan')),
    ('ZA', _('Afrique du Sud')),
    ('AL', _('Albanie')),
    ('DZ', _('Algérie')),
    ('DE', _('Allemagne')),
    ('AD', _('Andorre')),
    ('AO', _('Angola')),
    ('AG', _('Antigua-et-Barbuda')),
    ('SA', _('Arabie saoudite')),
    ('AR', _('Argentine')),
    ('AM', _('Arménie')),
    ('AU', _('Australie')),
    ('AT', _('Autriche')),
    ('AZ', _('AzerbaÃ¯djan')),
    ('BS', _('Bahamas')),
    ('BH', _('BahreÃ¯n')),
    ('BD', _('Bangladesh')),
    ('BB', _('Barbade')),
    ('BY', _('Bélarus')),
    ('BE', _('Belgique')),
    ('BZ', _('Belize')),
    ('BJ', _('Bénin')),
    ('BT', _('Bhoutan')),
    ('BO', _('Bolivie')),
    ('BA', _('Bosnie-Herzégovine')),
    ('BW', _('Botswana')),
    ('BR', _('Brésil')),
    ('BN', _('Brunei')),
    ('BG', _('Bulgarie')),
    ('BF', _('Burkina Faso')),
    ('BI', _('Burundi')),
    ('CV', _('Cap-Vert')),
    ('KH', _('Cambodge')),
    ('CM', _('Cameroun')),
    ('CA', _('Canada')),
    ('CF', _('République centrafricaine')),
    ('CL', _('Chili')),
    ('CN', _('Chine')),
    ('CY', _('Chypre')),
    ('CO', _('Colombie')),
    ('KM', _('Comores')),
    ('CG', _('Congo')),
    ('CD', _('République démocratique du Congo')),
    ('CR', _('Costa Rica')),
    ('CI', _('CÃ´te d\'Ivoire')),
    ('HR', _('Croatie')),
    ('CU', _('Cuba')),
    ('DK', _('Danemark')),
    ('DJ', _('Djibouti')),
    ('DM', _('Dominique')),
    ('EG', _('Ã‰gypte')),
    ('AE', _('Ã‰mirats arabes unis')),
    ('EC', _('Ã‰quateur')),
    ('ER', _('Ã‰rythrée')),
    ('ES', _('Espagne')),
    ('EE', _('Estonie')),
    ('SZ', _('Eswatini')),
    ('US', _('Ã‰tats-Unis')),
    ('ET', _('Ã‰thiopie')),
    ('FJ', _('Fidji')),
    ('FI', _('Finlande')),
    ('FR', _('France')),
    ('GA', _('Gabon')),
    ('GM', _('Gambie')),
    ('GE', _('Géorgie')),
    ('GH', _('Ghana')),
    ('GR', _('Grèce')),
    ('GD', _('Grenade')),
    ('GT', _('Guatemala')),
    ('GN', _('Guinée')),
    ('GW', _('Guinée-Bissau')),
    ('GQ', _('Guinée équatoriale')),
    ('GY', _('Guyana')),
    ('HT', _('HaÃ¯ti')),
    ('HN', _('Honduras')),
    ('HU', _('Hongrie')),
    ('IN', _('Inde')),
    ('ID', _('Indonésie')),
    ('IQ', _('Irak')),
    ('IR', _('Iran')),
    ('IE', _('Irlande')),
    ('IS', _('Islande')),
    ('IL', _('IsraÃ«l')),
    ('IT', _('Italie')),
    ('JM', _('JamaÃ¯que')),
    ('JP', _('Japon')),
    ('JO', _('Jordanie')),
    ('KZ', _('Kazakhstan')),
    ('KE', _('Kenya')),
    ('KG', _('Kirghizistan')),
    ('KI', _('Kiribati')),
    ('KW', _('KoweÃ¯t')),
    ('LA', _('Laos')),
    ('LS', _('Lesotho')),
    ('LV', _('Lettonie')),
    ('LB', _('Liban')),
    ('LR', _('Liberia')),
    ('LY', _('Libye')),
    ('LI', _('Liechtenstein')),
    ('LT', _('Lituanie')),
    ('LU', _('Luxembourg')),
    ('MK', _('Macédoine du Nord')),
    ('MG', _('Madagascar')),
    ('MY', _('Malaisie')),
    ('MW', _('Malawi')),
    ('MV', _('Maldives')),
    ('ML', _('Mali')),
    ('MT', _('Malte')),
    ('MA', _('Maroc')),
    ('MH', _('ÃŽles Marshall')),
    ('MU', _('Maurice')),
    ('MR', _('Mauritanie')),
    ('MX', _('Mexique')),
    ('FM', _('Micronésie')),
    ('MD', _('Moldavie')),
    ('MC', _('Monaco')),
    ('MN', _('Mongolie')),
    ('ME', _('Monténégro')),
    ('MZ', _('Mozambique')),
    ('MM', _('Myanmar')),
    ('NA', _('Namibie')),
    ('NR', _('Nauru')),
    ('NP', _('Népal')),
    ('NI', _('Nicaragua')),
    ('NE', _('Niger')),
    ('NG', _('Nigeria')),
    ('NU', _('Niue')),
    ('NO', _('Norvège')),
    ('NZ', _('Nouvelle-Zélande')),
    ('OM', _('Oman')),
    ('UG', _('Ouganda')),
    ('UZ', _('Ouzbékistan')),
    ('PK', _('Pakistan')),
    ('PW', _('Palaos')),
    ('PA', _('Panama')),
    ('PG', _('Papouasie-Nouvelle-Guinée')),
    ('PY', _('Paraguay')),
    ('NL', _('Pays-Bas')),
    ('PE', _('Pérou')),
    ('PH', _('Philippines')),
    ('PL', _('Pologne')),
    ('PT', _('Portugal')),
    ('QA', _('Qatar')),
    ('DO', _('République dominicaine')),
    ('CZ', _('République tchèque')),
    ('RO', _('Roumanie')),
    ('GB', _('Royaume-Uni')),
    ('RU', _('Russie')),
    ('RW', _('Rwanda')),
    ('KN', _('Saint-Christophe-et-Niévès')),
    ('SM', _('Saint-Marin')),
    ('VA', _('Saint-Siège')),
    ('LC', _('Sainte-Lucie')),
    ('VC', _('Saint-Vincent-et-les-Grenadines')),
    ('SB', _('ÃŽles Salomon')),
    ('SV', _('Salvador')),
    ('WS', _('Samoa')),
    ('ST', _('Sao Tomé-et-Principe')),
    ('SN', _('Sénégal')),
    ('RS', _('Serbie')),
    ('SC', _('Seychelles')),
    ('SL', _('Sierra Leone')),
    ('SG', _('Singapour')),
    ('SK', _('Slovaquie')),
    ('SI', _('Slovénie')),
    ('SO', _('Somalie')),
    ('SD', _('Soudan')),
    ('SS', _('Soudan du Sud')),
    ('LK', _('Sri Lanka')),
    ('SE', _('Suède')),
    ('CH', _('Suisse')),
    ('SR', _('Suriname')),
    ('SY', _('Syrie')),
    ('TJ', _('Tadjikistan')),
    ('TZ', _('Tanzanie')),
    ('TD', _('Tchad')),
    ('TH', _('ThaÃ¯lande')),
    ('TL', _('Timor oriental')),
    ('TG', _('Togo')),
    ('TO', _('Tonga')),
    ('TT', _('Trinité-et-Tobago')),
    ('TN', _('Tunisie')),
    ('TM', _('Turkménistan')),
    ('TR', _('Turquie')),
    ('TV', _('Tuvalu')),
    ('UA', _('Ukraine')),
    ('UY', _('Uruguay')),
    ('VU', _('Vanuatu')),
    ('VE', _('Venezuela')),
    ('VN', _('Vietnam')),
    ('YE', _('Yémen')),
    ('ZM', _('Zambie')),
    ('ZW', _('Zimbabwe')),
]

def get_country_name(country_code):
    """
    Retourne le nom du pays Ã  partir de son code ISO.
    """
    for code, name in COUNTRY_CHOICES:
        if code == country_code:
            return str(name)
    return country_code  # Retourne le code si non trouvé

def get_valid_country_codes():
    """
    Retourne la liste des codes pays valides.
    """
    return [code for code, name in COUNTRY_CHOICES if code]
