BBBBBBB BBBBBBBBBBB
BBBB BBBB
BBBB BBBBBB
BBBB BBBBBBBBBBBBB

BBBBB BBBBB gettext(u'Tableau de bord Fédération')  X XXXXXXXXXXXBBBBBBBB

BBBBB BBBBBBBBB
XXXXXXX
  XX XXXXXXXXX XX XXXXXXX XX XXXXXXXXXXXXX XX XXXX XX
  XXXXX X
    XXXXXXXXXX XXXXXXXX
    XXXXXXXXXXXXXXXX XXXXXXXX
    XXXXXXXXXXXXXXX XXXXXXXX
    XXXXXXXXXXXX XXXXXXXX
    XXXXXXXXXX XXXXXXXX
    XXXXXXX XXXXXXXX
    XXXXXXXXXX XXXXXXXX
    XXXXXXXXX XXXXXXXX
    XXXXXXXX XXXXXXXX
    XXXXXXX XXXXXXXX
    XXXXXXXXXXX XXXXXXXX
    XXXXXXXXXXX XXXXXXXX
    XXXXXXXXXXX XXXXXXXX
    XXXXXXXXXXX XXXXXXXX
    XXXXXXXXXXXXXXXX XXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX
    XXXXXXXXXXXXXXXXXXXXX XXXXX
    XXXXXXXXXXXXXXXXXXXX XXXX
    XXXXXXXXXXXXXXXXXXX XXXXX
  X
  
  XX XXXXXXXXX XXXXXXXXXX XX
  XXXX X
    XXXXXXXXXXXXXXXXX XXXXXXXX
    XXXXXXXXXXX XXXXXXX
  X

  XXXXXXXXXXXXXXXXXXXX X
    XXXXXXXX XXXXX
    XXXXXXXXXXX XXXXXXXXXX X XXXXXX
  X
  
  XX XXXXX XXXXXXXX XXXXXXX XX
  XXXXXXXX X
    XXXXXX XXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXX XXXXXXX XXXXXX
    XXXXXX XXXXXX
    XXXXXXXXX XXXXXX
    XXXX XXXXX
    XXXXXXX XX
    XXXXX XX
    XXXXXXXX XXXX
    XXXXXXXX XX
    XXXXXXXXXXX XXXXX
    XXXXXXXXXXX XXX XXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXX X X XXXX XXXXXXX XX XX XXXXX
  X
  
  XX XXXXXXX XXXXXXXXX XX
  XXXXXXXXXXXXX X
    XXXXX XX
    XXXXXXXX XXXXX
    XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXX XXX XXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXX XXXXX
  X
  
  XX XXXX XX XXXXXXXXXX XX
  XXXXXXXXX X
    XXXXXXXX XXXXXX XXXXXXX
    XXXXXX XXXXXXXXX XXXX XXXX XXXXX
    XXXXXXXXXXXX XXX XXXXX XXXXXXXXXXXX
    XXXXXXXXXXXXXX XXXXXXXX
    XXXXXXXX XXXXX
    XXXXXXXXXXXX XXXXXXX
    XXXXXXXXXXX XXX XXXXXXXXXXXXXXXXXXXXXXXX
  X
  
  XXXXXXXXXXXXXXX X
    XXXXXX XXXXXX
    XXXXXXXXXXXXXXXXX XXXXXXXXX XXXX XXXX XXXXX
    XXXXXXXXXXXX XXX XXXXX XXXXXXXXXXXXXXX
    XXXXXXXXXX XXXXXXXXXXXXXXXX
  X
  
  XXXXXXXXXXXXXXXX X
    XXXXXX XXXXXX
    XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
    XXXXXXXXXXXX XXX XXXXX XXXXXX
    XXXXXXXXXXXX XXXX
    XXXXXXXXXXX X X XXXX XXXXXXXXX XXX XXX XXXXX
  X
  
  XXXXXXXXX X X
    XXXXXXXXXXXXX XXXXX
    XXXXXX XXXXX
    XXXXXXXXXXX XXXXXXX
  X
  
  XXXXXXXXXXXXXXXX X
    XXXXXXXX XXXX XXXXXX XXXXXXX
    XXXXXXXXXX XXXXXXX
    XXXXXXXXXXXXXXX XXXXXXXXXX
    XXXXXXXXXXXXXXX XXXXXX
    XXXXXX XXXXXXXXX XXXX XXXX XXXXX
    XXXXXXXXXXXX XXXX
  X
  
  XX XXXXXX XXXXXXXXXX XX
  XXXXXXXXXXXXXXXXXXX X
    XXXXXXXX XXXXXX XXXXX
    XXXXXXXXXXXXXX XXX XXXXX XXXXXXXXX XXXX XXXX XXXXX
    XXXXXXXXXXX XXXXXXX XX XX XXXXX
    XXXXXXXXXXX XXX XXXXXXXXXXXXXXXXXXXXXXXX
  X
  
  XXXXXXXXXXXXXXXXXX X
    XXXXXX XXXXX
    XXXXXXX XXXXX
    XXXXXXXXXXXXXXXXX XXXXXX
    XXXXXXXXXXXXXX XXXXX
    XXXXXXX X XXXX XXXXXXXX
    XXXXXXXX XXXXX
    XXXXXXXXXXXX XXXXXXX
    XXXXXXXXXXXXXXXX XXXXXXX
    XXXXXXXXXXX X XXX XXXX XXXXXXX XX XX XXXXXX
    XXXXXXXXXXX XXX XXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXX XXXX
  X
  
  XXXXXXXXXXXXXXXXXX XXX X
    XXXXXXXXXX XXXXX
    XXXXXXXXXXX XXXXX
    XXXXXXXXXXX XXXXXXXX
  X
  
  XXXXXXXXXXXXXXXXXXXXXXXX X
    XXXXXXXXXX XXXXXXXXXXXX
  X
  
  XX XXXXX XXXXXXXX XX
  XXXXXXXXXXXXXXX X
    XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXX X XXX XXXX XXXXXXX XX XX XXXXXX
    XXXXXXXXXXXXXX XXXXXXX
    XXXXXXXXXXXXXXXXX XXXXXX
    XXXXXXX XXXXX
    XXXXXXXXXXX XXX XXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXX XXXXXXX
  X
  
  XXXXXXXXXXXXXXXXXXXXX X
    XXXXXXXXXX XXXXXXXXXXXXXXXXX
    XXXXXXXXXXX X XXX XXXX XXXXXXX XX XX XXXXX
  X
  
  XX XXXXXX XX XXXXXXXXXXXX XX
  XXXXXXXXXXX X
    XXXXXXXX XXXXX
    XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXX
    XXXX XXXXXXX
    XXXXXXXXXXXXXX XXXXX
  X
  
  XXXXXXXXXXX X
    XXXXXXXX XXXXXXXX
    XXXXXXXXXXX XXXXXXX
    XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXX XXXXX
  X
  
  XXXXXXXXXXX X
    XXXXXX XXXXX
    XXXXXXX XXXXX
    XXXXXXX X XXXX XXXXXXXX
    XXXXXXXX XXXXX
    XXXXXXXXXXXX XXXXXXX
    XXXXXXXXXXXXXXXX XXXXXXX
    XXXXXXXXXXXXXX XXXX
    XXXXXXXXXX XXXXXXX
    XXXXXXXXXXX X XXX XXXX XXXXXXX XX XX XXXXXX
    XXXXXXXXXXX XXX XXXXXXXXXXXXXXXXXXXXXXXX
  X
  
  XXXXXXXXXXXXXXXXX XXXXXXXXXXX X
    XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX
  X
  
  XX XXXXXXXX XXX XXXXXX XX XXXXX XX
  XXXXXXXXXXXX X
    XXXXXXXXXXXXXXXXX XXXXXXXXX XXX XXX XXXXX
    XXXXXX XXXXXXXX
  X
  
  XXXXXXXXXXXXXXXXXXX X
    XXXXXXXXXXXXXXXXX XXXXXXXX XXXX XXX XXXXX
    XXXXXX XXXXXXXX
  X
  
  XXXXXXXXXXXXX X
    XXXXXXXXXXXXXXXXX XXXXXXXX XXXX XXXX XXXXX
    XXXXXX XXXXXXXX
  X
  
  XXXXXXXXXXXXXXXXXXX X
    XXXXXXXXXXXXXXXXX XXXXXXXXX XXXX XX XXXXX
    XXXXXX XXXXXXXX
  X
  
  XXXXXXXXXXXXXXX X
    XXXXXXXXXXXXXXXXX XXXXXXXX XXXX XXX XXXXX
    XXXXXX XXXXXXXX
  X
  
  XXXXXXXXXXXX X
    XXXXXXXXXX XXXXXXXX
    XXXXXXXXXXXX XXXX
    XXXXXXXXXXXXXX XXXXXXXX
    XXXXXX XXXXXXXXXXXX
    XXXXXXXXXXX XXX XXXXXXXXXXXXXXXXXXXXXXXX
  X
  
  XXXXXXXXXXXX X
    XXXXXXXXXX XXXXXXX
    XXXXXXXXXXXXXXX XXXXXXXXXX
    XXXXXX XXXXXXXXXXXXXXXXX
    XXXXXXXXXXXX XXXX
    XXXXXXXXXXXXXXX XXXXXX
  X
  
  XX XXXXXXX XXX XXXXXXX XXXXXXX XX
  XXXXXXXXXXXXXXXXXXX X
    XXXXXXXX XXXXX
    XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXX
    XXXX XXXXXXX
    XXXXXXXXXXXXXX XXXXX
  X
  
  XXXXXXXXXXXXX X
    XXXXXXXX XXXXX
    XXXXXXXXXXXXXXX XXXXXXX
    XXXXXXXXXXXX XXXXXXX
    XXXXXXXXXXX XXXXXXX
    XXXXXXXX XXXX XXXXXXX
    XXXXXXXXXXXXXXXXX XXXXXX
    XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXX X XXX XXXX XXXXXXX XX XX XXXXXX
    XXXXXXXXXXX XXX XXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXX XXXXX
    XXXXXXXXX XXXXXXXXX
    XXXXXXXXX XXXXXXX
  X
  
  XXXXXXXXXXXXXXXXXXX X
    XXXXXXXXXX XXXXXXXXXXXXXXXXX
    XXXXXXXXXXX X XXX XXXX XXXXXXX XX XX XXXXX
  X
  
  XXXXXXXXXXXXXXXXXXXXX X
    XXXXXXXX XXX
    XXXXXXXXX XXXXXXXXX
    XXXX XX
    XXXXX XX
    XXXXXX XXXXX
    XXXXXXX XXXX
    XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
  X
  
  XXXXXXXXXXXX X
    XXXXXX XXXXX
    XXXXXXX XXXXX
    XXXXXXXX XXXXX
    XXXXXXXXXXXX XXXXXXX
    XXXXXXXXXXXXXXXX XXXXXXX
    XXXXXXXXXXXXXX XXXX
    XXXXXXXXXXXXXX XXXXXXXX
    XXXXXXXXXX XXXXXXXX
    XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
    XXXXXX XXXXXXXXXXXXXXX
    XXXXXXXXXXX XXX XXXXXXXXXXXXXXXXXXXXXXXX
  X
  
  XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX X
    XXXXXXXXXX XXXXXXXXXXX
    XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
    XXXXXX XXXXXX
  X
  
  XXXXXXXXXXXXX X
    XXXXXXXXXX XXXXXXXX
    XXXXXXXXXXXX XXXX
    XXXXXXXXXXXXXX XXXXXXXX
    XXXXXX XXXXXXXXXXXX
  X
  
  XXXXXXXXXXXXXXXXXXX X
    XXXXXXXXXX XXXXXXXX
    XXXXXX XXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXX XXXXXXX
    XXXXXXXXXX XX
  X
  
  XX XXXXXXXX XX
  XXXXXXXXXXXXXXXXXX X
    XXXXXXXXXXXXXX XXXXXXX
  X
  
  XXXXXXXXXXXXXXX X
    XXXXXXXX XXXXX
    XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
    XXXXXXXXXXXX XXXXXXX
    XXXXXXXXXXXXXX XXXXXXXX
  X
  
  XXXXXXXXXXXXXX X
    XXXXXXXXXX XXXXXXXX
    XXXXXXXXXXXX XXXX
    XXXXXX XXXXXXXXXXXX
    XXXXXXXXXXXXXX XX
    XXXXXXXX XXXXX
    XXXXXXXXXXXX XXXXXXX
  X
  
  XXXXXXXXXXXXXX X X
    XXXXXXXXXXXXX XXXXXXXX
    XXXXXX XXXXXXXXXXXXXXX
    XXXXXXXXXX XXXXXXXX
  X
  
  XX XXXXX XXX XXXXXXXXXXXX XX
  XXXXXXXXXXXXXXXXXX X
    XXXXXXXX XXXXX
    XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXX
    XXXX XXXXXXXX
  X
  
  XXXXXXXXXXXXXXXXX X
    XXXXXXXXX XXXXXXXXX
    XXXXXXXX XXXXXXXX
    XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXX XXXXXX
    XXXXXXXXXXX X XXX XXXX XXXXXXX XX XX XXXXXX
    XXXXXXXXXXX XXX XXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXX XXXXXXX
  X
  
  XXXXXXXXXXXXXXXXXXXXXXX X
    XXXXXXXXXX XXXXXXXXXXXXXXXXX
    XXXXXXXXXXX X XXX XXXX XXXXXXX XX XX XXXXX
  X
  
  XXXXXXXXXXXXXXXXXXXXXXXXX X
    XXXXXXXX XXX
    XXXXXXXXX XXXXXXXXX
    XXXX XX
    XXXXX XX
    XXXXXXX XXXXX
    XXXXXX XXXX
  X
  
  XX XXXXX XXX XXXXXXXXXXXX XX
  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
    XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
  X
  
  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
    XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
  X
  
  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
    XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
  X
  
  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
    XXXXXXXXXXXXXXXXX XXXXXXXXXXXX
  X
  
  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
    XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
  X
  
  XXXXXXXXXXXXXXXXXX X
    XXXXXXXXXX XXXXXXX
    XXXXXXXXXXXX XXXX
    XXXXXXXXXXXXXX XXXXXXXX
    XXXXXX XXXXXXXXXXXX
  X
  
  XXXXXXXXXXXXXXXXX X
    XXXXXXXX XXXXX
    XXXXXXXXXXXX XXXXXXX
    XXXXXXXXXXXXXX XXXXXXXX
    XXXXXXXXXX XXXXXXX
    XXXXXX XXXXXXXXXXXXXXXXX
  X
  
  XXXXXXXXXXXXXXXXX X X
    XXXXXXXXXXXXX XXXXXXX
    XXXXXX XXXXX
    XXXXXXXXXXX XXXXXXX
    XXXXXX XXXXXXXXXXXXXXX
  X
  
  XXXXXXXXXXXXXXXXXXX X
    XXXXXXXXXXXXXX XXXXX
    XXXXXXXX XXXXX
    XXXXXXXXXX XXXXX
    XXXX XXXXXXX
  X
  
  XXXXXXXXXXXXXXXXXXXX X
    XXXXXXXX XXXXX
    XXXXXXXXXXXXXXXX XXXXXXXXX
    XXXXXXXXXXX XXXXX
    XXXX XXXXXXX
  X
  
  XX XXXXXXXX XXXXXXX XX
  XXXXXXXXXXXXXXXXXX X
    XXXXXXXXX XXXXXXXXX
    XXXXXXXXXXXXX XXXXX
  X
  
  XXXXXXXXXXXXXX X
    XXXXXXXXX XXXXXXXXX
    XXXXXXXXXXXXXXX XXXXXXXX
    XXXXXXXXXXXXXX XXXXXXXX
  X
  
  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
    XXXXXXXX XXX
    XXXXXXXXX XXXXXXXXX
    XXXXX XXXXXX
    XXXX XXXX
    XXXXXXX XXXXX
    XXXXXX XXXX
    XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
  X
  
  XXXXXXXXXXXXX X
    XXXXXXXXX XXXXXXXXX
    XXXXX XXXXXX
    XXXX XX
    XXXXXX XXXXX
    XXXXXXX XXXXX
    XXXXXXXXXXXXXX XXXX
    XXXXXXX XXX XXXXX XXXXXX
    XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
    XXXXXXXXXXX X X X XXX XXXXXXXXX XXX XXX XXXXX
  X
  
  XXXXXXXXXXXXXX X
    XXXXXXXXXX XXXXXXX
    XXXXXX XXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXX XXXXXXXX
    XXXXXXXX XXXXXX
  X
  
  XXXXXXXXXXXXXXX X
    XXXXXXXXXXXX XXXX
    XXXXXXXXXXXXXX XXXXXXXX
  X
  
  XX XXXXXXX X XXXXX XX
  XXXXXXXXXXXXXXXXXX X
    XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
    XXXXXX XXXXXX
    XXXXXXXXXX XXXXXXX
    XXXXXXXX XXXXXXX XXXXXXX
    XXXXXXXXXXXXXX XXXXX
    XXXXXXXXXXXX XXXXXXX
  X
  
  XX XXXX XXXXXXXXXX XX
  XXXXXX XXXXXXXXXXX XXXXXX X
    XXXXXXXX X
      XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXXXXXXX XXXXXXX
    X
    
    XXXXXXXXXXXXX X
      XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    X
    
    XXXXXXXXXXXXXXXXXXX X
      XXXXXXXX XXXX XXXXXXX
    X
    
    XXXXXXXXXXXXXXXXXX X
      XXXXXX XXXXX
      XXXXXXX XXXXX
    X
    
    XXXXXXXXX X
      XXXXXXXXXXXXXXXX XXXXXXX
      XXXXXXXX XXXXXX XXXXXXX
    X
    
    XXXXXXXXX X X
      XXXXXXXXXXXXX XX
    X
    
    XXXXXXXXXXXXXXXXX 
    XXXXXXXXX XXXXX 
    XXXXXXXXXXXXXXXXXXX XXX 
    XXXXXXXXXXXXXXXXXXX XX 
    XXXXXXXXXXXXXXXXXXX XXXXXXX
    XXXXXXXXXXX X
      XXXXXXXX XXXXX
    X
  X
  
  XXXXXX XXXXXXXXXXX XXXXXX X
    XXXXXXXX X
      XXXXXXXXXX XXXXXXXXXXXXXXXXXX
      XXXXXX XXXXXXXXXXXXXXXXXXXXX
    X
    
    XXXXXXXXXXXXXXX X
      XXXXXXXXXX XXXXXXXXXXXXXX
    X
    
    XXXXXXXXXXXXXXXXX 
    XXXXXXXXX XXXXX 
    XXXXXXXXXXXXXXXXXXX XXX 
    XXXXXXXXXXXXXXXXXXX XX 
    XXXXXXXXXXXXXXXXXXX XXXXXXX
    XXXXXXXXXXX X
      XXXXXXXX XXXXXX
    X
    
    XXXXXXXXX X
      XXXXXXXXXXXXXXXX XXXXXXXXXXX
      XXXXXXXX XXXXXX XXXXXXX
    X
    
    XXXXXXXXX X X
      XXXXXXXXXXXXX XXXXX
    X
    
    XXXXXXXXXXXXX X
      XXXXXXXXXXXX XX
    X
    
    XXXXXXXXXXXXXXX X
      XXXXXXXX XXXXXX
    X
    
    XXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXX X
      XXXXXXXXXXXXXXXXXXXXXX XXXX
    X
  X
XXXXXXXX
BBBBBBBB

BBBBB BBBBBBB
XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXX XXXXX XXXXXXXX XXX
  XXXX XXXXXXXXXXXXXXXX
    XXXX XXXXXX XXXXXXXXXX XXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
        BB BBBBBBBBBBBBBBB
          XXXX XXXXXX XXXXXXX
        BBBB
          XX XXXXXXXXXX XXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXX
        BBBBB
      XXXXXX
      XXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX
      XX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXX gettext(u'Fédération') XXXX
      XXXXX XXXXXXXXXXXX XXXXXXXXXXX gettext(u'Administration') XXXXXXX
    XXXXXX
    
    XXXX XXXX XXXXXXXXX XXX
    XXXX XXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Général') XXXXXX
      XXX XXXXXXXXXX XXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXXXX
          XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBX XXXXXXXXXXXXXXX XXXXXXXX
            XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXX gettext(u'Tableau de bord') XXXXXXX
          XXXX
        XXXXX
        XXX XXXXXXXXXXXXXXXXX
          XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBX XXXXXXXXXXXXXXXXX
            XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXX gettext(u'Calendrier') XXXXXXX
          XXXX
        XXXXX
      XXXXX
      
      XXXX XXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Compétitions') XXXXXX
      XXX XXXXXXXXXX XXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXXXX
          XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBX XXXXXXXXXXXXXXXXX
            XX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXX gettext(u'Compétitions') XXXXXXX
          XXXX
        XXXXX
        XXX XXXXXXXXXXXXXXXXX
          XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBX XXXXXXXXXXXXXXXXX
            XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXX gettext(u'Créer une compétition') XXXXXXX
          XXXX
        XXXXX
        XXX XXXXXXXXXXXXXXXXX
          XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXX
            XX XXXXXXXXXX XXXXXXXXXXXXXX XXXXXX gettext(u'Gérer comme organisateur') XXXXXXX
            BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB B B
              XXXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX
            BBBBB
          XXXX
        XXXXX
        XXX XXXXXXXXXXXXXXXXX
          XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXX
            XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXX gettext(u'Module Combat') XXXXXXX
            BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB B B
              XXXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXX
            BBBBB
          XXXX
        XXXXX
        XXX XXXXXXXXXXXXXXXXX
          XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBX XXXXXXXXXXXXXXXXX
            XX XXXXXXXXXX XXXXXXXXXXXXXX XXXXXX gettext(u'Clubs membres') XXXXXXX
          XXXX
        XXXXX
        XXX XXXXXXXXXXXXXXXXX
          XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBX XXXXXXXXXXXXXXXXX
            XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXX gettext(u'Catégories') XXXXXXX
          XXXX
        XXXXX
      XXXXX
      
      XXXX XXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Administration') XXXXXX
      XXX XXXXXXXXXX XXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXXXX
          XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBX XXXXXXXXXXXXXXXXX
            XX XXXXXXXXXX XXXXXXXXXXXXX XXXXXX gettext(u'Clubs affiliés') XXXXXXX
          XXXX
        XXXXX
        XXX XXXXXXXXXXXXXXXXX
          XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBX XXXXXXXXXXXXXXXXX
            XX XXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXX gettext(u'Utilisateurs') XXXXXXX
          XXXX
        XXXXX
        XXX XXXXXXXXXXXXXXXXX
          XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBX XXXXXXXXXXXXXXXXX
            XX XXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXX gettext(u'Rôles et permissions') XXXXXXX
          XXXX
        XXXXX
        XXX XXXXXXXXXXXXXXXXX
          XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBX XXXXXXXXXXXXXXXXX
            XX XXXXXXXXXX XXXXXXXXXXXXXX XXXXXX gettext(u'Juges et arbitres') XXXXXXX
          XXXX
        XXXXX
      XXXXX
      
      XXXX XXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Grades') XXXXXX
      XXX XXXXXXXXXX XXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXXXX
          XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXX
            XX XXXXXXXXXX XXXXXXXXXXXXXX XXXXXX gettext(u'Gestion des grades') XXXXXXX
          XXXX
        XXXXX
        XXX XXXXXXXXXXXXXXXXX
          XX XXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXX
            XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXX gettext(u'Certifications') XXXXXXX
            XXXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXX gettext(u'Bientôt') XXXXXXX
          XXXX
        XXXXX
        XXX XXXXXXXXXXXXXXXXX
          XX XXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXX
            XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXX gettext(u'Examens') XXXXXXX
            XXXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXX gettext(u'Bientôt') XXXXXXX
          XXXX
        XXXXX
      XXXXX
      
      XXXX XXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Finances & Licences') XXXXXX
      XXX XXXXXXXXXX XXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXXXX
          XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBX XXXXXXXXXXXXXXXXX
            XX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX gettext(u'Licences') XXXXXXX
          XXXX
        XXXXX
        XXX XXXXXXXXXXXXXXXXX
          XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXX
            XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX gettext(u'Finances') XXXXXXX
          XXXX
        XXXXX
        XXX XXXXXXXXXXXXXXXXX
          XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXX
            XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXX gettext(u'Transactions') XXXXXXX
          XXXX
        XXXXX
        XXX XXXXXXXXXXXXXXXXX
          XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXX
            XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXX gettext(u'Factures') XXXXXXX
          XXXX
        XXXXX
        XXX XXXXXXXXXXXXXXXXX
          XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
            XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXX gettext(u'Boutique') XXXXXXX
            XXXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXX gettext(u'Nouveau') XXXXXXX
          XXXX
        XXXXX
      XXXXX
      
      XXXX XXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Paramètres') XXXXXX
      XXX XXXXXXXXXX XXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXXXX
          XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBX XXXXXXXXXXXXXXXXX
            XX XXXXXXXXXX XXXXXXXXXXXX XXXXXX gettext(u'Paramètres') XXXXXXX
          XXXX
        XXXXX
        XXX XXXXXXXXXXXXXXXXX
          XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBX XXXXXXXXXXXXXXXXX
            XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXX gettext(u'Import / Export') XXXXXXX
          XXXX
        XXXXX
        XXX XXXXXXXXXXXXXXXXX
          XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXX
            XX XXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXX gettext(u'Documents') XXXXXXX
          XXXX
        XXXXX
        XXX XXXXXXXXXXXXXXXXX
          XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
            XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXX gettext(u'Espace Famille') XXXXXXX
            BBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBB
            BB BBBBBBBBBBBBBBBBBBB B B
            XXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXX XXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXX XXXXXXXXXXX
              
              XXXXX XXXXXXXXXXXXXXXXXXXXXXXX gettext(u'actions en attente') XXXXXXX
            XXXXXXX
            BBBBB
          XXXX
        XXXXX
      XXXXX
      
		XXXX XXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Site Web') XXXXXX
		XXX XXXXXXXXXX XXXXXXXXXXXXX
		  XXX XXXXXXXXXXXXXXXXX
			XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
			  XX XXXXXXXXXX XXXXXXXXXXXXXX XXXXXX gettext(u'Voir le site public') XXXXXXX
			  XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
			XXXX
		  XXXXX
		  XXX XXXXXXXXXXXXXXXXX
			XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
			  XX XXXXXXXXXX XXXXXXXXXXXX XXXXXX gettext(u'Gérer le site') XXXXXXX
			  XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
			XXXX
		  XXXXX
		  XXX XXXXXXXXXXXXXXXXX
			XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXX
			  XX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXX gettext(u'Codes QR du site') XXXXXXX
			XXXX
		  XXXXX
		XXXXX
	XXXXXX
XXXXXX

  XXXX XXXXXXX XXXXXXXXX XXX
  XXXX XXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXX XXXX XXXXXXX XXX
    XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXX
      XXXXX
        XXX XXXXXXXXX XXXXXX gettext(u'Tableau de bord Fédération') XXXXX
        XX XXXXXXXXXXXXXXXXX XXXXXXXXXX
      XXXXXX
      XXXX XXXXXXXXXXXXXXX
        XXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXX XXXX XXXXXXXXXXX
          XX XXXXXXXXXX XXXXXXXXXXXXX
        XXXXXXXXX
        XXXX XXXXXXXXXXXXXXX XXXXXX
          XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
            XX XXXXXXXXXX XXXXXXX XXXXXXXXXX  gettext(u'Actions rapides') 
          XXXXXXXXX
          XXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
            XXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBXX
              XX XXXXXXXXXX XXXXXXXXX XXXX XXXXXXXXXXXXXXXXX  gettext(u'Nouvelle compétition') 
            XXXXXXXXX
            XXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBXX
              XX XXXXXXXXXX XXXXXXX XXXX XXXXXXXXXXXXXXXXXX  gettext(u'Ajouter un club') 
            XXXXXXXXX
            XXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBXX
              XX XXXXXXXXXX XXXXXXXXXX XXXX XXXXXXXXXXXXXXX  gettext(u'Nouvelle licence') 
            XXXXXXXXX
            XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXXXXXXXX
              XX XXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXX  gettext(u'Nouveau produit') 
            XXXXXXXXX
            XXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXXXXXXXX
              XX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXX  gettext(u'Gérer les commandes') 
            XXXXXXXXX
            XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBXX
              XX XXXXXXXXXX XXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXX  gettext(u'Nouvelle transaction') 
            XXXXXXXXX
            XXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBXX
              XX XXXXXXXXXX XXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXXXX  gettext(u'Importer des données') 
            XXXXXXXXX
            XXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBXX
              XX XXXXXXXXXX XXXXXXXXXXX XXXX XXXXXXXXXXXXXXX  gettext(u'Gestion documentaire') 
            XXXXXXXXX
          XXXXX
        XXXXXX
        BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
      XXXXXX
    XXXXXX

    XXXX XXXXXX XXXXXXXXX XXX
    XXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX
      XXXX XXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXX XXXXXXXXX
            XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
              XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXX XXXX
                XX XXXXXXXXXX XXXXXXXXXXXXXXX
              XXXXXX
              XXXXX
                XXX XXXXXXXXXXXXX gettext(u'Finances') XXXXX
                XX XXXXXXXXXXXXXXXXX XXXX XXXXXXX gettext(u'Résumé financier') XXXX
              XXXXXX
            XXXXXX
          XXXXXX
          XXXX XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXX XXXXXXXXXXXXX
              XXXX XXXXXXXXXXXX XXXXXXXX XXXX XXXXXXXXX
                XXX XXXXXXXXXXXXXFFFFFFFFFFF XXXXXX
                XX XXXXXXXXXXXXXXXXX XXXX XXXXXXX gettext(u'Solde total') XXXX
              XXXXXX
              XXXX XXXXXXXXXXXX XXXXXXXX XXXX XXXXXXXXX
                XXX XXXXXXXXXXXXXFFFFFFFFFFF XXXXXX
                XX XXXXXXXXXXXXXXXXX XXXX XXXXXXX gettext(u'Revenus') XXXX
              XXXXXX
              XXXX XXXXXXXXXXXX XXXXXXXXXX
                XXX XXXXXXXXXXXXXFFFFFFFFFFF XXXXXX
                XX XXXXXXXXXXXXXXXXX XXXX XXXXXXX gettext(u'Dépenses') XXXX
              XXXXXX
              XXXX XXXXXXXXXXXX XXXXXXXXXX
                XXX XXXXXXXXXXXXXFFFFFFFFFFFXXXXX
                XX XXXXXXXXXXXXXXXXX XXXX XXXXXXX gettext(u'Factures en attente') XXXX
              XXXXXX
            XXXXXX
          XXXXXX
        XXXXXX
      XXXXXX
      XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXX
        XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBX XXXXXXXXXX XXXXXX XXXXXXXXXXXX
          XX XXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX  gettext(u'Voir le détail') 
        XXXX
      XXXXXX
    XXXXXX

    XXXX XXXXXX XX XXXXXXXXXXXX XXX
    XXXX XXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
          XX XXXXXXXXXX XXXXXXXXXXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXFFFFFFFFFFFXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXX gettext(u'Clubs affiliés') XXXXXX
        XXXX XXXXXXXXXXXXX
          XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXX
            XX XXXXXXXXXX XXXXXX XXXXXXXXXX  gettext(u'Voir les clubs') 
          XXXX
        XXXXXX
      XXXXXX
      
      XXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
          XX XXXXXXXXXX XXXXXXXXXXXXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXFFFFFFFFFFFXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXX gettext(u'Compétitions') XXXXXX
        XXXX XXXXXXXXXXXXX
          XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXX
            XX XXXXXXXXXX XXXXXX XXXXXXXXXX  gettext(u'Voir') 
          XXXX
          XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXX XXXXXX
            XX XXXXXXXXXX XXXXXXX XXXXXXXXXX  gettext(u'Créer') 
          XXXX
        XXXXXX
      XXXXXX
      
      XXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
          XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXFFFFFFFFFFFXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXX gettext(u'Événements à venir') XXXXXX
        XXXX XXXXXXXXXXXXX
          XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXX
            XX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXX  gettext(u'Calendrier') 
          XXXX
        XXXXXX
      XXXXXX
      
      XXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
          XX XXXXXXXXXX XXXXXXXXXXXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXFFFFFFFFFFFXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXX gettext(u'Participants') XXXXXX
        XXXX XXXXXXXXXXXXX
          XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXX
            XX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXX  gettext(u'Voir les licences') 
          XXXX
        XXXXXX
      XXXXXX
    XXXXXX
    
    XXXX XXXXXXX XXX XXXXXXX XXXXXXX XXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXXXXXXXXX
          XX XXXXXXXXXX XXXXXXXXXXXXX  gettext(u'Actions rapides') 
        XXXXX
      XXXXXX
      
      XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXXXXX
            XX XXXXXXXXXX XXXXXXXXXXXXXXX
          XXXXXX
          XXX XXXXXXXXXXXXXXXXXXXXX gettext(u'Créer une compétition') XXXXX
          XX XXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Configurez et publiez une nouvelle compétition pour votre fédération.') XXXX
          XXXX XXXXXXXXXXXXXXXX
            XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBX XXXXXXXXXX XXXXXXXXXXXX
              XX XXXXXXXXXX XXXXXXX XXXXXXXXXX  gettext(u'Nouvelle compétition') 
            XXXX
          XXXXXX
        XXXXXX
        
        XXXX XXXXXXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXXXXX
            XX XXXXXXXXXX XXXXXXXXXXXXX
          XXXXXX
          XXX XXXXXXXXXXXXXXXXXXXXX gettext(u'Gérer les clubs') XXXXX
          XX XXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Ajoutez, approuvez et gérez les clubs affiliés à votre fédération.') XXXX
          XXXX XXXXXXXXXXXXXXXX
            XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBX XXXXXXXXXX XXXXXXXXXXXX
              XX XXXXXXXXXX XXXXXXXX XXXXXXXXXX  gettext(u'Voir les clubs') 
            XXXX
          XXXXXX
        XXXXXX
        
        XXXX XXXXXXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXXXXX
            XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
          XXXXXX
          XXX XXXXXXXXXXXXXXXXXXXXX gettext(u'Gérer la boutique') XXXXX
          XX XXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u"Vendez du matériel d'arts martiaux et gérez vos produits, commandes et stocks.") XXXX
          XXXX XXXXXXXXXXXXXXXX
            XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX
              XX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXX  gettext(u'Accéder à la boutique') 
            XXXX
          XXXXXX
        XXXXXX
        
        XXXX XXXXXXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXXXXX
            XX XXXXXXXXXX XXXXXXXXXXXXXXXX
          XXXXXX
          XXX XXXXXXXXXXXXXXXXXXXXX gettext(u'Gestion des licences') XXXXX
          XX XXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Émettez, renouvelez et gérez les licences pour les pratiquants.') XXXX
          XXXX XXXXXXXXXXXXXXXX
            XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBX XXXXXXXXXX XXXXXXXXXXXX
              XX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXX  gettext(u'Voir les licences') 
            XXXX
          XXXXXX
        XXXXXX
        
        XXXX XXXXXXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXXXXX
            XX XXXXXXXXXX XXXXXXXXXXXXXX
          XXXXXX
          XXX XXXXXXXXXXXXXXXXXXXXX gettext(u'Gestion des grades') XXXXX
          XX XXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Configurez et gérez le système de grades de votre fédération.') XXXX
          XXXX XXXXXXXXXXXXXXXX
            XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBX XXXXXXXXXX XXXXXXXXXXXX
              XX XXXXXXXXXX XXXXXXXX XXXXXXXXXX  gettext(u'Voir les grades') 
            XXXX
          XXXXXX
        XXXXXX
      XXXXXX
    XXXXXX
    
    XXXX XXXXXXXXXXXX X XXXXX XXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXXXXXXXXX
          XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX  gettext(u'Compétitions à venir') 
        XXXXX
        XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
          XX XXXXXXXXXX XXXXXX XXXXXXXXXX  gettext(u'Voir toutes') 
        XXXX
      XXXXXX
      
      XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
        BBB BBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
        XXXX XXXXXXXXXXXXXXXXXXXXXXX XX
          XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXX
              XX XXXXXXXXXX XXXXXXXXXXXXXXX 
            XXXXXXX
            XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
              XX XXXXXXXXXX XXXXXXXXXXXXXXXXX 
            XXXXXXX
          XXXXXX
          XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          
          XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
            XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX FFFFFFFFFFFF
            BB BBBBBBBBBBBBBBBBBBBB BBB BBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBBBB
            X FFFFFFFFFFFF
            BBBBB
          XXXXXX
          
          XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
            XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX 
          XXXXXX
          
          XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
            XX XXXXXXXXXX XXXXXXXXXXXXXX   gettext(u'participants') 
          XXXXXX
          
          XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXX
              XX XXXXXXXXXX XXXXXX XXXXXXXXXX  gettext(u'Détails') 
            XXXX
            
            XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBX XXXXXXXXXX XXXXXX XXXXXXXXXXXX
              XX XXXXXXXXXX XXXXXX XXXXXXXXXX  gettext(u'Gérer') 
            XXXX
          XXXXXX
        XXXXXX
        BBBBB
        XXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX
          XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXX
            XXXX XXXXXXXXXXXXX
              XX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXX
            XXXXXX
            XXXX gettext(u'Aucune compétition à venir') XXXXX
            XX XXXXXXXXXXXXXXXXXXX gettext(u"Il n'y a actuellement aucune compétition planifiée pour votre fédération.") XXXX
            XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBX XXXXXXXXXX XXXXXXXXXX XXXXXX
              XX XXXXXXXXXX XXXXXXX XXXXXXXXXX  gettext(u'Créer une compétition') 
            XXXX
          XXXXXX
        XXXXXX
        BBBBBB
      XXXXXX
    XXXXXX
    
    XXXX XXXXXXXX XXXXXXX XXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXXXXXXXXX
          XX XXXXXXXXXX XXXXXXXXXXXXXXXX  gettext(u'Activité récente') 
        XXXXX
      XXXXXX
      
      XXXX XXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXX
              XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                BB BBBBBBBBBBBBBBBBB
                  BBB BBBBBBBB BB BBBBBBBBBBBBBBBBB
                  XXXX XXXXXXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXX XXXXXXXXXXXXXXXXXXXXXXFFFFFFFFFFF FFFFXXXXXXX
                    XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XX XXXXXXXXXXXXXXXXX
                  XXXXXX
                  BBBBBB
                BBBB
                  XXXX XXXXXXXXXXXXXXXXXX XXXXXX
                    XX XXXXXXXXXX XXXXXXXXXXXXXX XXXXX XXXXXXXXXX XXXXXXXXXX
                    XXXX gettext(u'Aucune activité récente') XXXXX
                    XX XXXXXXXXXXXXXXXXXXX gettext(u'Les activités récentes apparaîtront ici.') XXXX
                  XXXXXX
                BBBBB
              XXXXXX
            XXXXXX
          XXXXXX
        XXXXXX
        
        XXXX XXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXX
              XXX XXXXXXXXXXXXXXXXX XXXXXX gettext(u'À faire') XXXXX
            XXXXXX
            XXXX XXXXXXXXXXXXXXXXXX
              BB BBBBBBBBBB
                XXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
                  BBB BBBB BB BBBBBBBBBB
                  XXX XXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXX
                    XXXXX
                      XXX XXXXXXXXXXXXXXXXXX
                      XX XXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXX
                    XXXXXX
                    XX XXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXX
                      XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                    XXXX
                  XXXXX
                  BBBBBB
                XXXXX
              BBBB
                XXXX XXXXXXXXXXXXXXXXXX XXXXXX
                  XX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXX XXXXXXXXXX
                  XXXX gettext(u'Tout est à jour') XXXXX
                  XX XXXXXXXXXXXXXXXXXXX gettext(u"Vous n'avez aucune tâche en attente.") XXXX
                XXXXXX
              BBBBB
            XXXXXX
          XXXXXX
        XXXXXX
      XXXXXX
    XXXXXX

    XXXX XXXXXXX XXXXX XXX XXXXXXXXX XXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXXXXXXXXX
          XX XXXXXXXXXX XXXXXXXXXXXX  gettext(u'Suivi des Commandes Boutique') 
        XXXXX
        XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
          XX XXXXXXXXXX XXXXXXX XXXXXXXXXX  gettext(u'Voir toutes') 
        XXXX
      XXXXXX
      
      XXXX XXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXX
              BB BBBBBBBBBBBBB
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                  XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX
                    XXXXXXX
                      XXXX
                        XXXX gettext(u'Référence') XXXXX
                        XXXX gettext(u'Client') XXXXX
                        XXXX gettext(u'Date') XXXXX
                        XXXX gettext(u'Montant') XXXXX
                        XXXX gettext(u'Statut') XXXXX
                        XXXX gettext(u'Actions') XXXXX
                      XXXXX
                    XXXXXXXX
                    XXXXXXX
                      BBB BBBBB BB BBBBBBBBBBBBB
                      XXXX
                        XXXX
                          XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBXXXXXXXXXXXXXXXXX
                            X
                          XXXX
                        XXXXX
                        XXXXFFFFFFFFFFFFFFFFFFFFFFFFFFFXXXXX
                        XXXXFFFFFFFFFFF FFFFXXXXX
                        XXXX XXXXXX
                        XXXX
                          XXXXX XXXXXXXXXXXX XXXBB BBBBBBBBBBBB BB BBBBBBBBBXXXXXXXBBBB BBBBBBBBBBBB BB BBBBBBBBBBBXXXXXXXBBBBXXXXXXXXXBBBBBXX
                            
                          XXXXXXX
                        XXXXX
                        XXXX
                          XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXX
                            XX XXXXXXXXXX XXXXXXXXXXXX
                          XXXX
                        XXXXX
                      XXXXX
                      BBBBBB
                    XXXXXXXX
                  XXXXXXXX
                XXXXXX
              BBBB
                XXXX XXXXXXXXXXXXXXXXXX XXXXXX
                  XX XXXXXXXXXX XXXXXX XXXXX XXXXXXXXXX XXXXXXXXXX
                  XXXX gettext(u'Aucune commande récente') XXXXX
                  XX XXXXXXXXXXXXXXXXXXX gettext(u'Les commandes de votre boutique fédérale apparaîtront ici.') XXXX
                XXXXXX
              BBBBB
            XXXXXX
          XXXXXX
        XXXXXX
      XXXXXX
    XXXXXX

    XXXX XXXXXXX XXXXX XXX XXXXXXXXX XXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXXXXXXXXX
          XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXX  gettext(u'Suivi des Paiements') 
        XXXXX
        XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
          XX XXXXXXXXXX XXXXXXX XXXXXXXXXX  gettext(u'Voir tous') 
        XXXX
      XXXXXX
      
      XXXX XXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXX
              BB BBBBBBBBBBBBBBB
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                  XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX
                    XXXXXXX
                      XXXX
                        XXXX gettext(u'Référence') XXXXX
                        XXXX gettext(u'Type') XXXXX
                        XXXX gettext(u'Club/Pratiquant') XXXXX
                        XXXX gettext(u'Date') XXXXX
                        XXXX gettext(u'Montant') XXXXX
                        XXXX gettext(u'Statut') XXXXX
                      XXXXX
                    XXXXXXXX
                    XXXXXXX
                      BBB BBBBBBB BB BBBBBBBBBBBBBBB
                      XXXX
                        XXXXXXXXX
                        XXXXXXXXX
                        XXXXXXXXX
                        XXXXFFFFFFFFFFF FFFFXXXXX
                        XXXX XXXXXX
                        XXXX
                          XXXXX XXXXXXXXXXXX XXXBB BBBBBBBBBBBBBB BB BBBBBBXXXXXXXBBBB BBBBBBBBBBBBBB BB BBBBBBBBBXXXXXXXBBBBXXXXXXBBBBBXX
                            
                          XXXXXXX
                        XXXXX
                      XXXXX
                      BBBBBB
                    XXXXXXXX
                  XXXXXXXX
                XXXXXX
              BBBB
                XXXX XXXXXXXXXXXXXXXXXX XXXXXX
                  XX XXXXXXXXXX XXXXXXXXXXXXXX XXXXX XXXXXXXXXX XXXXXXXXXX
                  XXXX gettext(u'Aucun paiement récent') XXXXX
                  XX XXXXXXXXXXXXXXXXXXX gettext(u'Les paiements de votre fédération apparaîtront ici.') XXXX
                XXXXXX
              BBBBB
            XXXXXX
            XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXX
              XXXX XXXXXXXXXX XXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXX
                  XXX XXXXXXXXXXXXXFFFFFFFFFFF XXXXXX
                  XXXXXX XXXXXXXXXXXXXXXXXXX gettext(u'Total') XXXXXXXX
                XXXXXX
                XXXX XXXXXXXXXXXXXX
                  XXX XXXXXXXXXXXXXFFFFFFFFFFFXXXXX
                  XXXXXX XXXXXXXXXXXXXXXXXXX gettext(u'Payés') XXXXXXXX
                XXXXXX
                XXXX XXXXXXXXXXXXXX
                  XXX XXXXXXXXXXXXXFFFFFFFFFFFXXXXX
                  XXXXXX XXXXXXXXXXXXXXXXXXX gettext(u'En attente') XXXXXXXX
                XXXXXX
              XXXXXX
            XXXXXX
          XXXXXX
        XXXXXX
      XXXXXX
    XXXXXX

    XXXX XXXXXXX XXXXX XXX XXXXXXXXXXXX XXXXX XXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXXXXXXXXX
          XX XXXXXXXXXX XXXXXXXXXXXXXXXXXX  gettext(u'Affiliation des Clubs') 
        XXXXX
        XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
          XX XXXXXXXXXX XXXXXXX XXXXXXXXXX  gettext(u'Gérer les clubs') 
        XXXX
      XXXXXX
      
      XXXX XXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXX
              XXX XXXXXXXXXXXXXXXXX XXXXXX gettext(u"Demandes d'affiliation") XXXXX
            XXXXXX
            XXXX XXXXXXXXXXXXXXXXXX
              BB BBBBBBBBBBBBBBBBBBBB
                XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
                  BBB BBBBBBB BB BBBBBBBBBBBBBBBBBBBB
                  XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                    XXXXX
                      XXX XXXXXXXXXXXXXXXXXX
                      XX XXXXXXXXXXX XXXXXXXXXXXX
                        XXXXXXXFFFFFFFFFFFF X XXXXXXXX
                      XXXX
                    XXXXXX
                    XXXXX
                      XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBB BBBBBBBBBBX XXXXXXXXXX XXXXXX XXXXXXXXXXXXX
                        XX XXXXXXXXXX XXXXXXXXXXXXXX
                      XXXX
                      XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBB BBBBBBBBBBX XXXXXXXXXX XXXXXX XXXXXXXXXXXX
                        XX XXXXXXXXXX XXXXXXXXXXXXXX
                      XXXX
                    XXXXXX
                  XXXXXX
                  BBBBBB
                XXXXXX
              BBBB
                XXXX XXXXXXXXXXXXXXXXXX XXXXXX
                  XX XXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXXXXXX XXXXXXXXXX
                  XX XXXXXXXXXXXXXXXXXXX gettext(u"Aucune demande d'affiliation en attente.") XXXX
                XXXXXX
              BBBBB
            XXXXXX
          XXXXXX
        XXXXXX
        
        XXXX XXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXX
              XXX XXXXXXXXXXXXXXXXX XXXXXX gettext(u'Clubs récemment affiliés') XXXXX
            XXXXXX
            XXXX XXXXXXXXXXXXXXXXXX
              BB BBBBBBBBBBBBBBBBBBB
                XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
                  BBB BBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBB
                  XXXX XXXXXXXXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                      XXXXX
                        XXX XXXXXXXXXXXXXXXXXX
                        XX XXXXXXXXXXX XXXXXXXXXXXX
                          XXXXXXXXXXXXXX XX FFFFFFFFFFFFXXXXXXXX
                        XXXX
                      XXXXXX
                      XXXXX XXXXXXXXXXXX XXXXXXXXXXXX
                        XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX gettext(u'Actif') XXXXXXX
                    XXXXXX
                  XXXXXX
                  BBBBBB
                XXXXXX
              BBBB
                XXXX XXXXXXXXXXXXXXXXXX XXXXXX
                  XX XXXXXXXXXX XXXXXXXX XXXXX XXXXXXXXXX XXXXXXXXXX
                  XX XXXXXXXXXXXXXXXXXXX gettext(u'Aucun club récemment affilié.') XXXX
                XXXXXX
              BBBBB
            XXXXXX
          XXXXXX
        XXXXXX
      XXXXXX
    XXXXXX

    XXXX XXXXXXX XXXXXXXXXXXXX XXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXXXXXXXXX
          XX XXXXXXXXXX XXXXXXXXXXXXX  gettext(u'Notifications') 
        XXXXX
        XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
          XX XXXXXXXXXX XXXXXX XXXXXXXXXX  gettext(u'Gérer les notifications') 
        XXXX
      XXXXXX
      
      XXXX XXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXX
              XXXX XXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXX
                XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                   gettext(u'Récentes') 
                  BB BBBBBBBBBBBBBBBBBBBBXXXXX XXXXXXXXXXXX XXXXXXXXX XXXXXXFFFFFFXXXXXXXBBBBB
                XXXXXXXXX
                XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                   gettext(u'Système') 
                XXXXXXXXX
                XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                   gettext(u'Compétitions') 
                XXXXXXXXX
              XXXXXX
              
              XXXX XXXXXXXXXXXXXXXXXX XXXXXX
                XXXX XXXXXXXXXXXXXXX XXXX XXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                  BB BBBBBBBBBBBBBBBBBBBB
                    XXXX XXXXXXXXXXXXXXXXXXX
                      BBB BBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBB
                      XXXX XXXXXXXXXXXXXXXXXXXXXX BB BBB BBBBBBBBBBBBBBBBBBBBXXXXXXXXBBBBBXX
                        XXXX XXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                          XXX XXXXXXXXXXXXXXXXXX
                          XXXXXXXFFFFFFFFFFF FFFFXXXXXXXX
                        XXXXXX
                        XX XXXXXXXXXXXXXXXXX
                        BB BBB BBBBBBBBBBBBBBBBBBBB
                        XXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Marquer comme lu') XXXXXXXXXXXX
                        BBBBB
                      XXXXXX
                      BBBBBB
                    XXXXXX
                  BBBB
                    XXXX XXXXXXXXXXXXXXXXXX XXXXXX
                      XX XXXXXXXXXX XXXXXXXXXXXXX XXXXX XXXXXXXXXX XXXXXXXXXX
                      XX XXXXXXXXXXXXXXXXXXX gettext(u'Aucune notification récente.') XXXX
                    XXXXXX
                  BBBBB
                XXXXXX
                
                XXXX XXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                  XXXX XXXXXXXXXXXXXXXXXX XXXXXX
                    XX XXXXXXXXXX XXXXXX XXXXX XXXXXXXXXX XXXXXXXXXX
                    XX XXXXXXXXXXXXXXXXXXX gettext(u'Les notifications système apparaîtront ici.') XXXX
                  XXXXXX
                XXXXXX
                
                XXXX XXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                  XXXX XXXXXXXXXXXXXXXXXX XXXXXX
                    XX XXXXXXXXXX XXXXXXXXX XXXXX XXXXXXXXXX XXXXXXXXXX
                    XX XXXXXXXXXXXXXXXXXXX gettext(u'Les notifications de compétitions apparaîtront ici.') XXXX
                  XXXXXX
                XXXXXX
              XXXXXX
            XXXXXX
          XXXXXX
        XXXXXX
      XXXXXX
    XXXXXX

    XXXX XXXXXXX XXXXX XXX XXXXXXXX XXXXXXX XXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXXXXXXXXX
          XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX  gettext(u'Support et Demandes') 
        XXXXX
        XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
          XX XXXXXXXXXX XXXXXXX XXXXXXXXXX  gettext(u'Voir toutes') 
        XXXX
      XXXXXX
      
      XXXX XXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXX
              BB BBBBBBBBBBBBBBB
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                  XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX
                    XXXXXXX
                      XXXX
                        XXXX gettext(u'Ticket') XXXXX
                        XXXX gettext(u'Sujet') XXXXX
                        XXXX gettext(u'Demandeur') XXXXX
                        XXXX gettext(u'Date') XXXXX
                        XXXX gettext(u'Priorité') XXXXX
                        XXXX gettext(u'Statut') XXXXX
                        XXXX gettext(u'Actions') XXXXX
                      XXXXX
                    XXXXXXXX
                    XXXXXXX
                      BBB BBBBBB BB BBBBBBBBBBBBBBB
                      XXXX
                        XXXXXXXXXX
                        XXXXXXXXX
                        XXXXFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFXXXXX
                        XXXXFFFFFFFFFFF FFFFXXXXX
                        XXXX
                          XXXXX XXXXXXXXXXXX XXXBB BBBBBBBBBBBBBBB BB BBBBBBXXXXXXBBBB BBBBBBBBBBBBBBB BB BBBBBBBBXXXXXXXBBBBXXXXBBBBBXX
                            
                          XXXXXXX
                        XXXXX
                        XXXX
                          XXXXX XXXXXXXXXXXX XXXBB BBBBBBBBBBBBB BB BBBBBBXXXXXXXBBBB BBBBBBBBBBBBB BB BBBBBBBBBBBBBXXXXXXXBBBB BBBBBBBBBBBBB BB BBBBBBBBBBXXXXXXXBBBBXXXXXXXXXBBBBBXX
                            
                          XXXXXXX
                        XXXXX
                        XXXX
                          XX XXXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                            XX XXXXXXXXXX XXXXXXXXXXXX
                          XXXX
                        XXXXX
                      XXXXX
                      BBBBBB
                    XXXXXXXX
                  XXXXXXXX
                XXXXXX
              BBBB
                XXXX XXXXXXXXXXXXXXXXXX XXXXXX
                  XX XXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXX XXXXXXXXXX
                  XXXX gettext(u'Aucune demande de support') XXXXX
                  XX XXXXXXXXXXXXXXXXXXX gettext(u'Les demandes de support apparaîtront ici.') XXXX
                XXXXXX
              BBBBB
            XXXXXX
            XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXX
              XXXX XXXXXXXXXX XXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXX
                  XXX XXXXXXXXXXXXXFFFFFFFFFFFXXXXX
                  XXXXXX XXXXXXXXXXXXXXXXXXX gettext(u'Ouverts') XXXXXXXX
                XXXXXX
                XXXX XXXXXXXXXXXXXX
                  XXX XXXXXXXXXXXXXFFFFFFFFFFFXXXXX
                  XXXXXX XXXXXXXXXXXXXXXXXXX gettext(u'En cours') XXXXXXXX
                XXXXXX
                XXXX XXXXXXXXXXXXXX
                  XXX XXXXXXXXXXXXXFFFFFFFFFFFXXXXX
                  XXXXXX XXXXXXXXXXXXXXXXXXX gettext(u'Résolus') XXXXXXXX
                XXXXXX
                XXXX XXXXXXXXXXXXXX
                  XXX XXXXXXXXXXXXXFFFFFFFFFFFXXXXX
                  XXXXXX XXXXXXXXXXXXXXXXXXX gettext(u'Fermés') XXXXXXXX
                XXXXXX
              XXXXXX
            XXXXXX
          XXXXXX
        XXXXXX
      XXXXXX
    XXXXXX
  XXXXXX
XXXXXX

BBBBB BBBBBBBB
XXXXXXXX
  XX XXXXXXXX XXXX XXXXX XX XXXXXXXXXXX XX XX XXXXX XXXXXXXX
  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X
    XXXXX XXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    
    XX XXXXXXXXXXXXXXXXXX X
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXX
    X
    
    XX XXXXXX XX XXXXX XXXXXXXX XXXXX XX XXXXXX X XXXXXXXXXXX XXXX XXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX X
      XXXXX XXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXX XXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      
      XX XXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXX X XXX XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      X
    XXX
  XXX
XXXXXXXXX
BBBBBBBB
BBBBBBBB