BBBBBBB BBBBBBBBBBBBBBBBBBBBBB
BBBB BBBB BBBBBBBBBB BBBBBB BBBBBBBBBB
BBBB BBBB

BBBBB BBBBB X  _('Django site admin') BBBBBBBB

BBBBB BBBBBBBBBBB
XXXX XXXXXXXXXXXXXXXXXXXX
XX XXXXXXBBB BBBBBBBBBBBBBXX gettext(u'Home') XXXX
XXXXXXXX 
XXXXXX
BBBBBBBB

BBBBB BBBBBBB
XXXXXXXXX

XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    BB BBBB BB BBBBBBBB
    XXXX XXXXX XX XXXXXX XX XXXXXXX XXX
    XXXX XXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXX
        XXXXXX XXXXXXXXXX XXXXXXXXXXXXXXX gettext(u'Étape 1: Sélection du fichier') XXXXX
        
        XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
            BBBBBBBBBB
            XXXX XXXXXXXXXXXXXXXXXXX
                XXXXXX XXXXXXXXXXXXXXXXXX gettext(u'Fichier à importer:') XXXXXXXX
                XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX 
                       XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
                XXXXXX XXXXXXXXXXXXXXXXXX gettext(u'Formats supportés: Excel (.xlsx, .xls), CSV (.csv), JSON (.json), XML (.xml)') XXXXXXXX
            XXXXXX
            
            XXXX XXXXXXXXXXXXXXXXXXXXX
                XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX
                    XX XXXXXXXXXX XXXXXXXXXXXXXXXX gettext(u'Analyser le fichier') XXXXXXXXX
            XXXXXX
        XXXXXXX
        
        XXXX XXXXXXXXXXXXXXXXX
            XXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXX gettext(u'Fonctionnalités IA') XXXXX
            XXXX
                XXXXXXXXXXXX gettext(u'Détection automatique de format') XXXXXXXXX gettext(u'- Reconnaissance intelligente du type de fichier') XXXXX
                XXXXXXXXXXXX gettext(u'Mappage intelligent des colonnes') XXXXXXXXX gettext(u'- Correspondance automatique avec TF-IDF') XXXXX
                XXXXXXXXXXXX gettext(u'Validation avancée') XXXXXXXXX gettext(u'- Scoring automatique de la qualité des données') XXXXX
                XXXXXXXXXXXX gettext(u'Détection de doublons') XXXXXXXXX gettext(u'- IA sémantique avec sentence-transformers') XXXXX
            XXXXX
        XXXXXX
    XXXXXX
    
    BBBB BBBB BB BBBBBBBBB
    XXXX XXXXX XX XXXXXXX XXX XXXXXXXX XXX
    XXXX XXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXX
        XXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX gettext(u'Étape 2: Mappage des colonnes') XXXXX
        
        BB BBBBBBBBBBBBBBBB
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXX
                    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXX XXXXXXXXXXXXXXXXXXX gettext(u'Lignes') XXXXXXX
                XXXXXX
                XXXX XXXXXXXXXXXXXXXXXX
                    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXX XXXXXXXXXXXXXXXXXXX gettext(u'Colonnes') XXXXXXX
                XXXXXX
                XXXX XXXXXXXXXXXXXXXXXX
                    XXXXX XXXXXXXXXXXXXXXXXXXFFFFFXXXXXXX
                    XXXXX XXXXXXXXXXXXXXXXXXX gettext(u'Format') XXXXXXX
                XXXXXX
                XXXX XXXXXXXXXXXXXXXXXX
                    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXX XXXXXXXXXXXXXXXXXXX gettext(u'Mappées') XXXXXXX
                XXXXXX
            XXXXXX
        XXXXXX
        
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXX gettext(u'Mappage intelligent des colonnes') XXXXX
            XX XXXXXXXXXXXXXXXXXXXX XXXXX XXXXX X XXXXXXXXXXXXXXX XXXXXXX XXX XXXXXXXXXXXXXXX XXXXXXXXXX 
                XXXX XXXXXX XXXXXXX XX XXXXXXX XX XXXXXXXXXXXX XXXXXX
            
            XXXX XXXXXXXXXXXXXXXXXXXXX
                BBB BBBBBBBBBBBBB BBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
                XXXX XXXXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXXX
                        XXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXXXXX
                            BBB BBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBB
                            XXXXX XXXXXXXXXXXXXXXFFFFFFFFFFFFFFFFXXXXXXX
                            BBBBBB
                        XXXXXX
                    XXXXXX
                    
                    XXXX XXXXXXXXXXXXXXXXXXXXXX
                        XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXXXXXXX 
                             XXXXXXXXXXXXXXXXXXX
                            FFFFFFFFFFFFFX
                        XXXXXX
                    XXXXXX
                    
                    XXXX XXXXXXXXXXXXXXXXXXXXXX
                        XXXXXXX XXXXXXXXXXXXXXXX 
                                XXXXXXXXXXXXXXXXXXXXXX
                            XXXXXXX XXXXXXXXX gettext(u'-- Non mappé --') XXXXXXXXX
                            XXXXXXX XXXXXXXXXXXXXXXXXX BB BBBBBBBBBBBB BB BBBBBBBBBBBBXXXXXXXXBBBBBX gettext(u'Prénom') XXXXXXXXX
                            XXXXXXX XXXXXXXXXXXXXXXXX BB BBBBBBBBBBBB BB BBBBBBBBBBBXXXXXXXXBBBBBX gettext(u'Nom') XXXXXXXXX
                            XXXXXXX XXXXXXXXXXXXX BB BBBBBBBBBBBB BB BBBBBBBXXXXXXXXBBBBBX gettext(u'Email') XXXXXXXXX
                            XXXXXXX XXXXXXXXXXXXX BB BBBBBBBBBBBB BB BBBBBBBXXXXXXXXBBBBBX gettext(u'Téléphone') XXXXXXXXX
                            XXXXXXX XXXXXXXXXXXXXXXXXX BB BBBBBBBBBBBB BB BBBBBBBBBBBBXXXXXXXXBBBBBX gettext(u'Date de naissance') XXXXXXXXX
                            XXXXXXX XXXXXXXXXXXXX BB BBBBBBBBBBBB BB BBBBBBBXXXXXXXXBBBBBX gettext(u'Grade') XXXXXXXXX
                            XXXXXXX XXXXXXXXXXXXXXXXXX BB BBBBBBBBBBBB BB BBBBBBBBBBBBXXXXXXXXBBBBBX gettext(u'Discipline') XXXXXXXXX
                            XXXXXXX XXXXXXXXXXXX BB BBBBBBBBBBBB BB BBBBBBXXXXXXXXBBBBBX gettext(u'Club') XXXXXXXXX
                            XXXXXXX XXXXXXXXXXXXXXXXXXXXXX BB BBBBBBBBBBBB BB BBBBBBBBBBBBBBBBXXXXXXXXBBBBBX gettext(u'Numéro de licence') XXXXXXXXX
                        XXXXXXXXX
                        
                        BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
                        XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                            BBB BBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
                            XXXXX XXXXXXXXXXXXXXXXXXXX
                            BBBBBB
                        XXXXXX
                        BBBBB
                    XXXXXX
                XXXXXX
                BBBBBB
                
                BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXX gettext(u'Colonnes non mappées') XXXXX
                    BBB BBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
                    XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXXXXX
                            XXXXXXXXXXXXXXX
                        XXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXXXXX
                            XX XXXXXXXXXX XXXXXXXXXXXXXXXXX
                        XXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXXXXX
                            XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                                XXXXXXX XXXXXXXXX gettext(u'-- Non mappé --') XXXXXXXXX
                                XXXXXXX XXXXXXXXXXXXXXXXXXX gettext(u'Prénom') XXXXXXXXX
                                XXXXXXX XXXXXXXXXXXXXXXXXX gettext(u'Nom') XXXXXXXXX
                                XXXXXXX XXXXXXXXXXXXXX gettext(u'Email') XXXXXXXXX
                                XXXXXXX XXXXXXXXXXXXXX gettext(u'Téléphone') XXXXXXXXX
                                XXXXXXX XXXXXXXXXXXXXXXXXXX gettext(u'Date de naissance') XXXXXXXXX
                                XXXXXXX XXXXXXXXXXXXXX gettext(u'Grade') XXXXXXXXX
                                XXXXXXX XXXXXXXXXXXXXXXXXXX gettext(u'Discipline') XXXXXXXXX
                                XXXXXXX XXXXXXXXXXXXX gettext(u'Club') XXXXXXXXX
                                XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX gettext(u'Numéro de licence') XXXXXXXXX
                            XXXXXXXXX
                        XXXXXX
                    XXXXXX
                    BBBBBB
                XXXXXX
                BBBBB
            XXXXXX
            
            XXXX XXXXXXXXXXXXXXXXXXXXX
                XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXX gettext(u'Retour') XXXXXXXXX
                XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XX XXXXXXXXXX XXXXXXXXXXXXXX gettext(u'Valider le mappage') XXXXXXXXX
            XXXXXX
        XXXXXX
        BBBB
        XXXX XXXXXXXXXXXXXXXXXXXXXX
            XXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u"Erreur d'analyse") XXXXX
            XXXXXXX
            XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBX XXXXXXXXXX XXXXXXXXXXXXXXX gettext(u'Recommencer') XXXX
        XXXXXX
        BBBBB
    XXXXXX
    
    BBBBB
    
    XXXX XXXXXXXXX XX XXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXX XXX
    XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX
        XXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX gettext(u'Étape 3: Validation des données') XXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXX
    
    XXXX XXXXXXXXX XX XXXXXXXX XXXXXXXX XXXXXXXXXXXXXX XXX
    XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX
        XXXXXX XXXXXXXXXX XXXXXXXXXXXXX gettext(u'Étape 4: Détection de doublons') XXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXX
    
    XXXX XXXXXX XXXXX XXX
    XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX
        XXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXX gettext(u'Étape 5: Import final') XXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXX
XXXXXX

XXXXXXX
XXXXXXXXXXXXXXXXXXXXXXX X
    XXXXXXXXXX XXXXXXX
    XXXXXXX X XXXXX
X

XXXXXXXXXXXX X
    XXXXXXXXXXX XXXXX
    XXXXXXX XXX XXXXX XXXXX
    XXXXXXXXXXXXXX XXXX
    XXXXXXXX XXXXX
    XXXXXXXXXXXXXX XXXXX
X

XXXXXXXXXXXXXXXXXXX X
    XXXXXXXXXXXXX XXXXXXXX
    XXXXXXXXXXX X XXX XXX XXXXXXXXXXXXXXXXXXXX
X

XXXXXXXXXXXX XX X
    XXXXXX XXXXX
    XXXXXXXXXXXXXX XXXXX
    XXXXXXXXXXXXXXX XXXXX
    XXXXXXXXXXXXXX XXX XXXXX XXXXXXXX
X

XXXXXXXXXXX X
    XXXXXXXX XXXXX
    XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXX
    XXXX XXXXX
    XXXXXXXXXXXXXX XXXXX
X

XXXXXXXXXX X
    XXXXXXXXXXX XXXXXXX
    XXXXXXXX XXXXX
    XXXXXXXXXXX XXXXXXXX
    XXXXXXXXXXXXXX XXXX
X

XXXXXXXXXXX X
    XXXXXXXX XXXXXX
    XXXXXXXXXX XXXXX
    XXXXXXXXXXXX XXXXX
    XXXXXX XXXXXXXX
X

XXXXXXXXXXX X
    XXXXXXXX XXXXXX
    XXXXXXXXXX XXXXX
    XXXXXX XXXXX
    XXXXXXXXXXXXXXX XXXXXXXXXX
X

XXXXXXXXXXXXX X
    XXXXXXXXXXXXXX XXXXX
X

XXXXXXXXXXXX X
    XXXXXXXX XXXXX
    XXXXXXXXXXXXXXXXXXXXXX XXX XXXX XXXX
    XXXX XXXXX
    XXXXXXXXXXXX XXXXXXX
    XXXXXXXX XXXXX
    XXXXXXX XXX XXXXX XXXXX
    XXXXXXXXXXXXXX XXXX
    XXXXXXXXXXXXXX XXXXX
X

XXXXXXXXXXXXXXXXXXXXX X
    XXXXXXXXXXX XXXXXXXX
X

XXXXXXXXXXXXXX XXXXX X
    XXXXXXXXXXXX XXXXX
    XXXXXX XXXXX
X

XXXXXXXXXXXXXX X
    XXXXXXXXXXX XXXX
X

XXXXXXX X
    XXXXXXXX XXXXXXXXXXXXX
    XXXXXXXXXXX XXXXXXXX
    XXXXXX XXXXXXXX
    XXXXXXXX XXX XXXX
    XXXXXXXXXXXXXX XXXX
    XXXXXXXXXX XXXXX
    XXXXXXXXXXXXX XXXX
X

XXXXXXXXXXXXXX X
    XXXXXXXXXXX XXXXXXX
    XXXXXX XXXXXXXX
X

XXXXXXXXXXXXXXXXX X
    XXXXXXXXXX XXXXX
    XXXXXXXXXXXX XXXXX
    XXXXXXXXXXX XXXX
X

XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX 
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
    XXXXXX XXXXXXXX
X

XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX 
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
    XXXXXX XXXXXXXX
X

XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX 
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX 
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX 
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
    XXXXXX XXXXXXXX
X

XXXXXXXXXXXXXX X
    XXXXXX XXXXX
    XXXXXXXX XXXX
    XXXXXXX XXX XXXXX XXXXX
    XXXXXXXXXXXXXX XXXX
X

XXXXXXXXXXXXXXXXX X
    XXXXXXXXXXX XXXX
X

XXXXX X
    XXXXXXXX XXXXXX
    XXXXXXXXXX XXXXX
    XXXXXX XXXXXXXX
X

XXXXXXXXXXXXX X
    XXXXXXXXXXX XXXXXX
    XXXXXXXXXXX XXXXX
    XXXXXXXXXXXX XXXXX
    XXXXXXXXXXX XXX XXXXX XXXXX
X

XXXX X
    XXXXXXXX XXXX XXXXX
    XXXXXXX XXXXX
    XXXXXXXXXXXXXX XXXX
    XXXXXXX XXXXXXXX
    XXXXXXXXXXXXXXXX XXXXX
    XXXXXXXXXXXX XXXXX
X

XXXXXXXXXXXX X
    XXXXXXXXXXX XXXXXXXX
    XXXXXX XXXXXX
X

XXXXXXXXXXXXXX X
    XXXXXXXXXXX XXXXXXXX
    XXXXXX XXXXXX
X

XXXXXXXXXX X
    XXXXXXXX XXXX
X

XXXXXXXXX X
    XXXXXXXXXXX XXXXXXXX
    XXXXXXX XXX XXXXX XXXXXXXX
    XXXXXXXXXXXXXX XXXX
    XXXXXXXX XXXXX
    XXXXXXXXXXX XXXXX
X

XXXXXXXXX XX X
    XXXXXX XXXXXXXX
    XXXXXXXXXXXXXX XXXXX
X

XXXXXXXXX XX X
    XXXXXXX XX
    XXXXXXXXXXXXX XXXXX
X

XXXXXXXXX XX X
    XXXXXXXXXXXXXX XXXX
X

XXXXXXXXXXXXXX X
    XXXXXXXXXXX XXXXXXXX
    XXXXXXX XXX XXXXX XXXXXXXX
    XXXXXXXXXXXXXX XXXX
    XXXXXXXX XXXXX
    XXXXXXXXXXX XXXXXXX
X

XXXXXXXXXXXXXX XX X
    XXXXXX XXXXXXXX
    XXXXXXXXXXXXXX XXXXX
X

XXXXXXXXXX X
    XXXXXX XXXXX
    XXXXXXXXXX XXXXX
    XXXXXXXXXXX XXXX
X

XXXXXXXXXXXX XXXXXXXXXXX X
    XXXXXXXXXXXXXX XXXXX
X

XXXXXXXXXXXX XXXXX X
    XXXXXXXX XXXXXX
    XXXXXXXXXXXX XXXXX
    XXXXXXXXXXXXXX XXXX
X

XXXXXXXXXXXX XXXXXXXXXXXXXXXXXX X
    XXXXXX XXXXX
    XXXXXXXX XXXXX
    XXXXXXX XXX XXXXXX XXXXX
    XXXXXXXXXXXXXX XXXX
    XXXXXXXXXXX XXXXXXXX
X
XXXXXXXX

XXXXXXXX
XXXXXXXX XXXXXXXXXXXXXXXX X
    XXXXXXXXXXXXXXXXXXXX X XBBB BBBBBBBBBBBBBBBBBBBBXX
X

XXXXXXXX XXXXXXXXXXXXXXXXX X
    XX XXXXXXXXX XX XXXXXXX XXX XXXXXXXX
    XXXXX XXXXXXX X XXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX X
        XXXXX XXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXXXXXXX X XXXXXXXXXXXXX
        XX XXXXXXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXX
        X
    XXX
    
    XX XXXXXXX XX XXXXXXX XX XXXXXXXXXX
    XXXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBXX X
        XXXXXXX XXXXXXX
        XXXXXXXX X
            XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XX
        XXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
    XX
    XXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXX
    XXXXXXXXXX XX X
        XX XXXXXXXXXXXX X
            XXXXXXXXXXXXXX X X XXXXXXXXXXXX
            XXXXXXX
        X
        
        XX XXXXXXXX XXX XXXXXXXXX XX XXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXX
        
        XX XXXXXX X XXXXXXX XXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXX
    XX
    XXXXXXXXXXXX XX X
        XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX
        XXXXXXXXXXXXX XXXX XX XX XXXXXXXXXXXXX
    XXX
X

XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX X
    XXXXX XXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    
    XXX XXXX X X
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXX gettext(u'Résultats de validation') XXXXX
            XXXX XXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXX
                    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXX XXXXXXXXXXXXXXXXXXX gettext(u'Score global') XXXXXXX
                XXXXXX
                XXXX XXXXXXXXXXXXXXXXXX
                    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXX XXXXXXXXXXXXXXXXXXX gettext(u'Lignes valides') XXXXXXX
                XXXXXX
                XXXX XXXXXXXXXXXXXXXXXX
                    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXX XXXXXXXXXXXXXXXXXXX gettext(u'Avertissements') XXXXXXX
                XXXXXX
                XXXX XXXXXXXXXXXXXXXXXX
                    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXX XXXXXXXXXXXXXXXXXXX gettext(u'Erreurs') XXXXXXX
                XXXXXX
            XXXXXX
        XXXXXX
    XX
    
    XX XXXXXXXXXXXXXXXXXXX X XX X
        XXXX XX X
            XXXX XXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
                XXX XXXXXXXXXXXXXXXXXXX
        XX
        XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XX X
            XXXX XX XXXXXXXXXXXXXXXXXXXX
        XXX
        XXXX XX XXXXXXXXXXXXXX
    X
    
    XXXX XX X
        XXXX XXXXXXXXXXXXXXXXXXXXX
            XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXX gettext(u'Retour au mappage') XXXXXXXXX
            XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XX XXXXXXXXXX XXXXXXXXXXXXXXX gettext(u'Détecter les doublons') XXXXXXXXX
        XXXXXX
    XX
    
    XXXXXXXXXXXXXXXXXXX X XXXXX
X

XXXXXXXX XXXXXXXXXXXXXXXXXX X
    XXXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBXX X
        XXXXXXX XXXXXXX
        XXXXXXXX X
            XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        X
    XX
    XXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXX
    XXXXXXXXXX XX X
        XX XXXXXXXXXXXX X
            XXXXXXXXXXXXXX X X XXXXXXXXXXXX
            XXXXXXX
        X
        
        XXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXX
    XX
    XXXXXXXXXXXX XX X
        XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX
        XXXXXXXXXXXXX XXXX XX XX XXXXXXXXX XX XXXXXXXXXXX
    XXX
X

XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX X
    XXXXX XXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    
    XXX XXXX X X
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXX gettext(u'Détection de doublons') XXXXX
            XXXX XXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXX
                    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXX XXXXXXXXXXXXXXXXXXX gettext(u'Groupes de doublons') XXXXXXX
                XXXXXX
                XXXX XXXXXXXXXXXXXXXXXX
                    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXX XXXXXXXXXXXXXXXXXXX gettext(u'Enregistrements concernés') XXXXXXX
                XXXXXX
                XXXX XXXXXXXXXXXXXXXXXX
                    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXX XXXXXXXXXXXXXXXXXXX gettext(u'Fusion automatique') XXXXXXX
                XXXXXX
            XXXXXX
        XXXXXX
    XX
    
    XX XXXXXXXXXXXXXXXXXXXXXXXX X XX X
        XXXX XX X
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                XXXX gettext(u'Suggestions de fusion') XXXXX
        XX
        
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX XX X
            XXXXX XXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXX X XXXXXXXXX
            XXXX XX X
                XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
                    XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXXXXX
                            XXXXXXXX gettext(u'Enregistrement principal:') XXXXXXXXX
                            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXX XXXXXXXXXXX
                        XXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                            XXXXXXXX gettext(u'Doublons potentiels:') XXXXXXXXX
                            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX 
                                XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXX XX XXXX XXXXXXXXXXXX
                            XXXXXXXXX XXX
                        XXXXXX
                    XXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXXX
                        XXXXXXX
                            XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX 
                                   XXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXX X XXXX gettext(u'Fusionner automatiquement') XXXXXXXX
                        XXXXXXX
                            XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX gettext(u'Garder séparés') XXXXXXXX
                        XXXXXXX
                            XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX gettext(u'Traitement manuel') XXXXXXXX
                    XXXXXX
                XXXXXX
            XX
        XXX
        
        XXXX XX XXXXXXXXX
    X
    
    XXXX XX X
        XXXX XXXXXXXXXXXXXXXXXXXXX
            XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXX gettext(u'Retour à la validation') XXXXXXXXX
            XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                XX XXXXXXXXXX XXXXXXXXXXXXXXXXX gettext(u"Finaliser l'import") XXXXXXXXX
        XXXXXX
    XX
    
    XXXXXXXXXXXXXXXXXXX X XXXXX
X

XXXXXXXX XXXXXXXXXXXXXXX X
    XX XXXXXXXXX XXX XXXXXXXXX XX XXXXXX
    XXXXX XXXXXXXXX X XXX
    
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX X
        XXXXX XXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
        XXXXX XXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        
        XX XXXXXXXXXXXXXXXX X
            XXXXXXXXXXXXXXXX
                XXXXXXXXX XXXXXXXX
                XXXXXXX XXXXXXXXXXXXXXXXXXXX
            XXX
        X
    XXX
    
    XXXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBXX X
        XXXXXXX XXXXXXX
        XXXXXXXX X
            XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XX
        XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
    XX
    XXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXX
    XXXXXXXXXX XX X
        XX XXXXXXXXXXXX X
            XXXXXXXXXXXXXX X X XXXXXXXXXXXX
            XXXXXXX
        X
        
        XX XXXXXXXX XXX XXXXXXXXX XXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXX
        
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X X
            XXXX XXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX gettext(u'Import terminé avec succès') XXXXX
                XXXXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXX
                    XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBX XXXXXXXXXX XXXXXXXXXXXXX gettext(u'Nouvel import') XXXX
                    XX XXXXXXBBB BBBBBBBBBBBBBX XXXXXXXXXX XXXXXXXXXXXXXXX gettext(u"Retour à l'administration") XXXX
                XXXXXX
            XXXXXX
        XX
    XX
    XXXXXXXXXXXX XX X
        XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX
        XXXXXXXXXXXXX XXXX XX XXXXXXXXXX XXXXXXXX
    XXX
X

XXXXXXXX XXXXXXXXXXXXXXXXX X
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXX
X

XXXXXXXX XXXXXXXXXXXXXXXXXXXX X
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXX
X
XXXXXXXXX
BBBBBBBB