# Generated by Django 4.2.11 on 2025-05-26 22:16

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import documents.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('grades', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('competitions', '0032_alter_documentacceptance_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('file', models.FileField(upload_to=documents.models.document_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx', 'ppt', 'pptx', 'txt', 'csv', 'jpg', 'jpeg', 'png', 'gif', 'mp4', 'zip', 'rar'])], verbose_name='Fichier')),
                ('file_size', models.PositiveIntegerField(default=0, verbose_name='Taille du fichier (octets)')),
                ('mime_type', models.CharField(blank=True, max_length=255, verbose_name='Type MIME')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='Version')),
                ('is_latest_version', models.BooleanField(default=True, verbose_name='Version la plus récente')),
                ('is_public', models.BooleanField(default=False, verbose_name='Public')),
                ('is_template', models.BooleanField(default=False, verbose_name='Modèle')),
                ('expiry_date', models.DateTimeField(blank=True, null=True, verbose_name="Date d'expiration")),
                ('object_id', models.CharField(blank=True, max_length=255, null=True, verbose_name="ID de l'objet associé")),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Métadonnées')),
                ('document_type', models.CharField(blank=True, choices=[('certificate', 'Certificat'), ('diploma', 'Diplôme'), ('license', 'Licence'), ('medical', 'Certificat médical'), ('competition', 'Document de compétition'), ('training', "Document d'entraînement"), ('technical', 'Document technique'), ('administrative', 'Document administratif'), ('other', 'Autre')], max_length=50, verbose_name='Type de document')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='Nombre de vues')),
                ('download_count', models.PositiveIntegerField(default=0, verbose_name='Nombre de téléchargements')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype', verbose_name='Type de contenu associé')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['-created_at'],
                'permissions': [('can_view_document', 'Peut voir le document'), ('can_download_document', 'Peut télécharger le document'), ('can_share_document', 'Peut partager le document')],
            },
        ),
        migrations.CreateModel(
            name='TechnicalDocumentMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(blank=True, choices=[('beginner', 'Débutant'), ('intermediate', 'Intermédiaire'), ('advanced', 'Avancé'), ('expert', 'Expert'), ('master', 'Maître')], max_length=20, verbose_name='Niveau')),
                ('content_type', models.CharField(blank=True, choices=[('kata', 'Kata/Forme'), ('technique', 'Technique'), ('drill', 'Exercice'), ('theory', 'Théorie'), ('exam', 'Examen'), ('syllabus', 'Programme technique')], max_length=20, verbose_name='Type de contenu')),
                ('requirements', models.TextField(blank=True, verbose_name='Prérequis')),
                ('keywords', models.CharField(blank=True, help_text='Mots-clés séparés par des virgules', max_length=500, verbose_name='Mots-clés')),
                ('discipline', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='technical_documents', to='competitions.discipline', verbose_name='Discipline')),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='technical_metadata', to='documents.document', verbose_name='Document')),
            ],
            options={
                'verbose_name': 'Métadonnées de document technique',
                'verbose_name_plural': 'Métadonnées de documents techniques',
            },
        ),
        migrations.CreateModel(
            name='GradeDocumentMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('certificate', 'Certificat de grade'), ('requirements', 'Exigences de passage'), ('exam_form', "Formulaire d'examen"), ('theory', 'Support théorique'), ('jury_guidelines', 'Guide pour le jury')], max_length=20, verbose_name='Type de document de grade')),
                ('valid_from', models.DateField(blank=True, null=True, verbose_name='Valide à partir du')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name="Valide jusqu'au")),
                ('issuing_authority', models.CharField(blank=True, max_length=255, verbose_name='Autorité de délivrance')),
                ('authorized_by', models.CharField(blank=True, max_length=255, verbose_name='Autorisé par')),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='grade_metadata', to='documents.document', verbose_name='Document')),
                ('grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='grades.grade', verbose_name='Grade')),
            ],
            options={
                'verbose_name': 'Métadonnées de document de grade',
                'verbose_name_plural': 'Métadonnées de documents de grade',
            },
        ),
        migrations.CreateModel(
            name='DocumentTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Nom du tag')),
                ('color', models.CharField(default='#cccccc', help_text='Code couleur hexadécimal (ex: #FF5733)', max_length=7, verbose_name='Couleur')),
            ],
            options={
                'verbose_name': 'Tag de document',
                'verbose_name_plural': 'Tags de documents',
                'ordering': ['name'],
                'unique_together': {('name',)},
            },
        ),
        migrations.CreateModel(
            name='DocumentShare',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('group_object_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='ID du groupe')),
                ('access_level', models.CharField(choices=[('R', 'Lecture'), ('W', 'Écriture'), ('F', 'Contrôle total')], default='R', max_length=1, verbose_name="Niveau d'accès")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Expire le')),
                ('notify_on_access', models.BooleanField(default=False, verbose_name="Notifier lors de l'accès")),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_shares_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='documents.document', verbose_name='Document')),
                ('group_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_shares', to='contenttypes.contenttype', verbose_name='Type de groupe')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_shares_received', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Partage de document',
                'verbose_name_plural': 'Partages de documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentFolder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Nom du dossier')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('is_public', models.BooleanField(default=False, verbose_name='Public')),
                ('path', models.CharField(blank=True, max_length=1000, verbose_name='Chemin')),
                ('visible_to_admins', models.BooleanField(default=True, verbose_name='Visible pour les administrateurs')),
                ('visible_to_federations', models.BooleanField(default=False, verbose_name='Visible pour les fédérations')),
                ('visible_to_clubs', models.BooleanField(default=False, verbose_name='Visible pour les clubs')),
                ('visible_to_practitioners', models.BooleanField(default=False, verbose_name='Visible pour les pratiquants')),
                ('visible_to_judges', models.BooleanField(default=False, verbose_name='Visible pour les juges')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_folders_owned', to=settings.AUTH_USER_MODEL, verbose_name='Propriétaire')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='documents.documentfolder', verbose_name='Dossier parent')),
            ],
            options={
                'verbose_name': 'Dossier de documents',
                'verbose_name_plural': 'Dossiers de documents',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DocumentComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField(verbose_name='Contenu')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents_comments', to=settings.AUTH_USER_MODEL, verbose_name='Auteur')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='documents.document', verbose_name='Document')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='documents.documentcomment', verbose_name='Commentaire parent')),
            ],
            options={
                'verbose_name': 'Commentaire',
                'verbose_name_plural': 'Commentaires',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentAccessLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Horodatage')),
                ('action', models.CharField(choices=[('view', 'Consultation'), ('download', 'Téléchargement'), ('edit', 'Modification'), ('share', 'Partage'), ('delete', 'Suppression')], max_length=20, verbose_name='Action')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='Détails')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='documents.document', verbose_name='Document')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_access_logs', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': "Journal d'accès aux documents",
                'verbose_name_plural': "Journal d'accès aux documents",
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddField(
            model_name='document',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='documents.documentfolder', verbose_name='Dossier'),
        ),
        migrations.AddField(
            model_name='document',
            name='modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_modified', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par'),
        ),
        migrations.AddField(
            model_name='document',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versions', to='documents.document', verbose_name='Version précédente'),
        ),
        migrations.AddField(
            model_name='document',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='documents', to='documents.documenttag', verbose_name='Tags'),
        ),
        migrations.CreateModel(
            name='CompetitionDocumentMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('rules', 'Règlement'), ('schedule', 'Planning'), ('registration', 'Inscription'), ('drawing', 'Tirage au sort'), ('results', 'Résultats'), ('report', 'Rapport'), ('certificate', 'Certificat/Diplôme')], max_length=20, verbose_name='Type de document de compétition')),
                ('event_date', models.DateField(blank=True, null=True, verbose_name="Date de l'événement")),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='competitions.competitioncategory', verbose_name='Catégorie')),
                ('competition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='competitions.competition', verbose_name='Compétition')),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='competition_metadata', to='documents.document', verbose_name='Document')),
            ],
            options={
                'verbose_name': 'Métadonnées de document de compétition',
                'verbose_name_plural': 'Métadonnées de documents de compétition',
            },
        ),
        migrations.AddConstraint(
            model_name='documentshare',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('group_object_id__isnull', True), ('user__isnull', False)), models.Q(('group_object_id__isnull', False), ('user__isnull', True)), _connector='OR'), name='share_user_or_group_not_both'),
        ),
        migrations.AlterUniqueTogether(
            name='documentfolder',
            unique_together={('name', 'parent')},
        ),
    ]
