from django.core.exceptions import PermissionDenied
# Generated by Django 5.1.6 on 2025-08-23 20:22

from django.db import migrations, models
from apps.core.isolation import OrganizationIsolationMixin, get_organization_queryset


class Migration(migrations.Migration):

    dependencies = [
        ('api_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refreshtoken',
            name='token',
            field=models.CharField(max_length=1024, unique=True, verbose_name='Token'),
        ),
    ]
