# Generated by Django 5.1.4 on 2025-05-27 08:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, default=django.utils.timezone.now, help_text='Nom de la marque du produit (ex: Nike, Adidas, Venum)', max_length=100, verbose_name='Marque'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='supplier',
            field=models.CharField(blank=True, default=django.utils.timezone.now, help_text='Nom du fournisseur ou distributeur', max_length=100, verbose_name='Fournisseur'),
            preserve_default=False,
        ),
    ]
