# Generated by Django 5.1.4 on 2025-05-27 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_convert_brand_supplier_to_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='brand_text',
        ),
        migrations.RemoveField(
            model_name='product',
            name='supplier_text',
        ),
    ]
