XXXXXXXXX XXXXX
BBBB BBBB
BBBB BBBBBB
XXXXX XXXXXXXX
XXXXXX
    XXXXX XXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
    XXXXXXX gettext(u"MartialComp - La Plateforme Complète de Gestion des Compétitions d'Arts Martiaux") XXXXXXXX
    
    XXXX XXXX XXXXXXXXXXXX XXXX XXX XXX
    XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXX gettext(u'MartialComp est la solution complète pour organiser, gérer et participer aux compétitions d\\') XX
    XXXXX XXXXXXXXXXXXXXX XXXXXXXXX gettext(u'arts martiaux, compétitions, karaté, judo, taekwondo, gestion tournois, notation technique') XX
    
    XXXX XXXXX X XXXXX XXX
    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    
    XXXXXXX
        XXXXX X
            XXXXXXXXXX XXXXXXXX
            XXXXXXXXXXXXXXX XXXXXXXX
            XXXXXXXXXXXX XXXXXXXX
            XXXXXXXXX XXXXXXXX
            XXXXXXXXXXXXXX XXXXXXXX
            XXXXXXXX XXXXXXXX
            XXXXXXX XXXXXXXX
            XXXXXXX XXXXXXXX
            XXXXXXXX XXXXXXXX
            XXXXXXXXXX XXXXXXXX
            XXXXXXX XXXXXXXX
            XXXXXXXXXX XXXXXXXX
            XXXXXXXXXXXXXXXX XXXX
            XXXXXXXXX X XXX XXXX XXXXXXX XX XX XXXXX
            XXXXXXXXXXXXXXX X XXX XXXX XXXXXXX XX XX XXXXXX
            XXXXXXXXXXXXX XXX XXXX XXXXX
        X
        
        X X
            XXXXXXX XX
            XXXXXXXX XX
            XXXXXXXXXXX XXXXXXXXXXX
        X
        
        XXXX X
            XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXX
            XXXXXXXXXXXX XXXX
            XXXXXXXXXXXXXXXXX XXXXXXXXXXXX
            XXXXXX XXXXXXXXXXXXX
            XXXXXXXXXXX XXXXXXX
        X
        
        XX XXXX XXXXXX X XXXXXXXXXX XXXX XX
        XXXXXXX X
            XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXX XXXXXXXXXXXXXX XXXXXX
            XXXXXXXX XXXX XX
            XXXXXXXXX XXXXXX
            XXXX XX
            XXXXXX XXXXX
            XXXXXXXX XXXXX
            XXXXXXXXXXXXXXXX XXXXXXXXXXX
            XXXXXXXXXXXXXX XXX XXXXX XXXXXXXXXXXXXX
        X
        
        XXXXXXXXXXXXXX X
            XXXXXXXXXX XXXXXXX
            XXXXXXX X XXXXX
            XXXXXXXX X XXXXX
            XXXXXXXX XXXXX
            XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
            XXXXXXXXXXXX XXXXXXX
        X
        
        XXXXX X
            XXXXXXXX XXXXX
            XXXXXXXXXXXX XXXXXXX
            XXXX XXXXX
            XXXXXXXXXX XXXXXXX
            XXXXXXXXXXXX XXXX
            XXXXXX XXXXXXXXXXXXX
            XXXXXXXXXXXXXXXX XXXXX
        X
        
        XXXXXXXXXX X
            XXXXXX XXXXX
            XXXXXXX XXXXX
            XXXXXXXXXXX XXXXXXXXXXXXXX
            XXXXXXXXXXXXXX XXXX
            XXXXXXXX XXXXX
            XXXXXXXXXXXX XXXXXXX
            XXXXXXXXXXXXXXXX XXXXXXX
            XXXXXX XXXXXXXXXXXX
        X
        
        XXXXXXXXXX X
            XXXXXXXX XXXXX
            XXXX XXXXX
            XXXXXXXXXXX XXXXX
        X
        
        XXXXXXXXXX X X
            XXXXXX XXXXXXXXXXXXX
            XXXXXXXXXXXXXXXX XXXXX
            XXXXXXXXXXXX XXXX
            XXXXXXXX XXXXXX XXXXX
            XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXX XXXXXXXXXXXXXXXXXX
        X
        
        XXXXXXXXXX XXXXXXX X
            XXXXXXXXXXXXXXXXX XXXXXXXXX XXXX XXX XXXXX
            XXXXXX XXXXXXXXXXXXXX
        X
        
        XXXXXXXXXXXXX X
            XXXXXXXX XXXXX
            XXXXXXXXXXXX XXXXXXX
            XXXX XXXXX
        X
        
        XXXX X
            XXXXXXXX XXXXXXX XXXXXXX
            XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXX XXXXX
            XXXXXXXXXXXX XXXX
            XXXXXXXXXXX XXXXXXXXXXXXXXXXXX
            XXXXXXX XXXXX
            XXXXXXX XXXXXXXX
            XXXXXXXX XXXXXXXXXXXX
            XXXXXXXXXXXX XXXXXXX
            XXXX XXXXXXX
        X
        
        XXXXXXXXXXXX X
            XXXXXXXXXXX XXXXXXXXXXXXXXX
            XXXXXX XXXXXXXXXXXXX
        X
        
        XXXXXXXXXXXXXXXXXX X
            XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXX XXXXXXXXXXXXXXXXX
        X
        
        XXXXXXXXXXXX X
            XXXXXXXXXXX XXXXXXXXXXXX
            XXXXXX XXXXXXXXXXXXX
            XXXXXXX XXX XXXXX XXXXXXXXXXXXXX
        X
        
        XXXXXXXXXXXXXXXXXX X
            XXXXXXXXXXX XXXXXXXXXXXXXX
            XXXXXX XXXXXXXXXXXX
        X
        
        XX XXXX XXXX XXXXXXX XXXX XX
        XXXXX X
            XXXXXXXXXXX XXXXXX
            XXXXXXXX XXXXX
            XXXXXXXXXXXX XXXXXXX
            XXXXXXXX XXXXX X XXXXX
            XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXX XXXXXXXXXXXXXXXX XXXXXX
            XXXXXXXXX XXXXXXXXX
            XXXXXXXXX XXXXXXX
        X
        
        XXXXXXXXXXXXX X
            XXXXXXXX XXX
            XXXXXXXXX XXXXXXXXX
            XXXX XX
            XXXXX XX
            XXXXXX XX
            XXXXXXX XX
            XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXX XXXX
        X
        
        XXXXXXXXXXXXXXX X
            XXXXXXXXXX XXXXXXX
            XXXXXXX X XXXXX
            XXXXXXXX X XXXXX
            XXXXXXXX XXXXX
            XXXXXXXXXXXXXXXXXXXXXX XXX XXXX
            XXXX XXXXX
            XXXXXXXXXXXX XXXXXXX
            XXXXXXXXX XXXXXXXXX
            XXXXXXXX XX
        X
        
        XXXXXXXXXXXXX XX X
            XXXXXXXXXX XXXXXXX
            XXXXXXXXXXXX XXXX
            XXXXXXXXXXXXXX XXXXXXX
            XXXXXXXXXXXX XXXX
            XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXX XXXXXXXXXXXXX XXXXXX
            XXXXXXXXXXXXXXXX XXXXX
            XXXXXXXXXXXXXXXXXXXXXXXX XXXXX
            XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
        X
        
        XXXXXXXXXXXXX XXXXXXXXX X
            XXXXXXXXXX XXXXXXX
            XXXXXX XXXXXXXXXXXXX
            XXXXXXXXXXXXXX XXXXX
            XXXXXXXX XXXX
        X
        
        XXXXXXXXXXXXX XXXXXXXXXXXX X
            XXXXXXXXXX XXXXXXX
            XXXXXX XXXXXXXXXXXX
            XXXXXXXXXXXXXX XXXXX
            XXXXXXXXXXXX XXXX
        X
        
        XXXXXXXXX X
            XXXXXXXX XXXXX
            XXXX XXXXXXX
            XXXXXXXXXXXXXX XXXXX
        X
        
        XXXXXXXXXXX X
            XXXXXXXX XXXXX
            XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXX
            XXXX XXXXX
            XXXXXXXXXXX XXXXX
        X
        
        XXXXXXXXXX X
            XXXXXXXXXXX XXXXXXX
            XXXXXXXX XXXXXXX
            XXXXXXXXXXX XXXXXXXXX XXXX XXXX XXXXXX
            XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
            XXXXXXX XXX XXXXX XXXXXXXXX XXXX XXX XXXXX
        X
        
        XXXXXXXXXXXX X
            XXXXXXXXXX XXXXXXX
            XXXXXXXXXXXX XXXX
            XXXXXX XXXXXXXXXXXXXX
            XXXXXXXXXXXXXX XXXXXXX
        X
        
        XXXXXXXXXXX X
            XXXXXXXXXX XXXXXXX
            XXXXXX XXXXXXXXXXXX
        X
        
        XXXXXXXXXXXX X
            XXXXXXXX XXXXX
            XXXXXXXXXXXX XXXXXXX
            XXXXXXXXXXXXXXXX XXXXXXX
            XXXXXXXXX XXXXXXXXX
        X
        
        XXXXXXXXXXX X
            XXXXXX XXXXX
            XXXXXXXXXX XXXXXX
            XXXXXXXXXXXXXX XXXXX
            XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
            XXXXXXXXXXX XXXXXXXXXXXXXXXXXX
        X
        
        XXXXXXXXXXXXXXXXX X
            XXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
        X
        
        XX XXXX XXXXX XXXXXXXXXXX XXXXXXX XXXX XX
        XXXXXXXXXXXXXXXXXX X
            XXXXXXXX XXXXX XX
            XXXXXXXXXXX XXXXXXXXXXXXXXXXX
        X
        
        XXXXXXXXXX X
            XXXXXXXXXX XXXXXXX
            XXXXXXX X XXXXX
            XXXXXXXX X XXXXX
        X
        
        XXXXXXXXXXXXXXX X
            XXXXXXXXXXX XXXXXXX
            XXXXXXXXXXXXXX XXXXX
        X
        
        XXXXXXXXXXXXXX X
            XXXXXXXXXX XXXXXXX
            XXXXXXXXXXXX XXXX
            XXXXXXXXXXXXXX XXXXXXX
            XXXXXX XXXXXXXXXXXXX
        X
        
        XXXXXXXXXXXXXXXXX X
            XXXXXXXXXX XXXXXXX
            XXXXXX XXXXXXXXXXXX
            XXXXXXXXXX XXXXXX
            XXXXXXX X XXXXX
        X
        
        XXXXXXXXXXX X
            XXXXXXXX XXXXX
            XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXX
            XXXX XXXXX
        X
        
        XXXXXXXXXXX X
            XXXXXXXXXXX XXXXXXXXXXXX
            XXXXXXXX XXXXX
            XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXX XXXXXXX
            XXXXXXXXXXX XXXXXXXXXXXXXXXXXX
            XXXXXXX XXX XXXXX XXXXXXXXX XXXX XXX XXXXX
            XXXXXXXXX XXXXXXXXX
            XXXXXXXXX XXXXXXX
        X
        
        XXXXXXXXXXXXXXXXXXX X
            XXXXXXXX XXX
            XXXXXXXXX XXXXXXXXX
            XXXX XX
            XXXXX XX
            XXXXXX XX
            XXXXXXX XXXX
            XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
        X
        
        XXXXXXXXXXXXXXXXX X
            XXXXXXXXXX XXXXXXXXXXXXXXXXXX
            XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXX XXXXXXXXXXXXXX
        X
        
        XXXXXXXXXXX X
            XXXXXX XXXXX
            XXXXXXX XXXXX
            XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
            XXXXXXXXXXXXXX XXXX
            XXXXXXXX XXXXX
            XXXXXXXXXXXX XXXXXXX
            XXXXXXXXXXXXXXXX XXXXXXX
            XXXXXXX X XXXX XXXXX
            XXXXXXXXXX XXXXX
            XXXXXX XXXXXXXXXXXXX
        X
        
        XXXXXXXXXXX XX X
            XXXXXXXXXX XXXXXXX
            XXXXXXXXXXXX XXXX
            XXXXXXXXXXXXXX XXXXX
            XXXXXX XXXXXXXXXXXXX
        X
        
        XXXXXXXXXXX X X
            XXXXXX XXXXXXXXXXXX
            XXXXXXXXXXXX XXXX
            XXXXXXXXXXXXXX XXXXX
        X
        
        XXXXXXXXXXXXX X
            XXXXXXXXXXX XXXXX
            XXXXXXXXXXXXXX XXXXX
        X
        
        XXXXXXXXXXXXX XX X
            XXXXXXXX XXXXXX XX
            XXXXXX XXXXXXXXXXXXX
            XXXXXXXX XXXXX
            XXXXXXXXXXXX XXXXXXX
            XXXX XXXXXXX
        X
        
        XXXXXXXXXXXXX XXXXXXXXXX X
            XXXXXXXX XXXX
            XXXXXX XXXXXXXXXXXXXX
            XXXXXXXXXXXX XXXXX
        X
        
        XX XXXX XXXXXX XXXXXXXXX XXXXXXX XXXX XX
        XXXXXXXXXXXXXXXXX X
            XXXXXXXX XXXXX XX
            XXXXXXXXXXX XXXXXXXXXXXX
        X
        
        XXXXXXXXXXXXXX X
            XXXXXXXX XXXXX
            XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXX
            XXXX XXXXXXX
            XXXXXXXXXXX XXXXX
        X
        
        XXXXXXXXXXXXXX X
            XXXXXXXXXXX XXXXXXXXXXXXXXXXX
            XXXXXXXX XXXXXXX
            XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXX XXXXXXX
            XXXXXXXXXXX XXXXXXXXXXXXXXXXXX
            XXXXXXX XXX XXXXX XXXXXXXXXXXX
        X
        
        XXXXXXXXXXXXXXXXXXXX X
            XXXXXXXXXXXXX XXXXXXXXXXXXXX
            XXXXXXXXXX XXXXXXXXXXXXXXXXX
        X
        
        XXXXXXXXXXXXXX X
            XXXXXX XXXXX
            XXXXXXX XXXXX
            XXXXXXXXXXX XXXXXXXXXXXXXX
            XXXXXXXXXXXXXX XXXX
            XXXXXXXX XXXXX
            XXXXXXXXXXXX XXXXXXX
            XXXXXXXXXXXXXXXX XXXXXXX
            XXXXXXX X XXXX XXXXXXX
            XXXXXXXXXX XXXXXXX
            XXXXXX XXXXXXXXXXXX
        X
        
        XXXXXXXXXXXXXX XX X
            XXXXXXXXXX XXXXXXX
            XXXXXXXXXXXX XXXX
            XXXXXXXXXXXXXX XXXXX
            XXXXXX XXXXXXXXXXXXXX
        X
        
        XXXXXXXXXXXXXX X X
            XXXXXX XXXXXXXXXXXX
            XXXXXXXXXXXXXX XXXXXXX
        X
        
        XXXXXXXXXXXXXXXXXX X
            XXXXXXXXXXX XXXXX
            XXXXXXXXXXXXXX XXXXX
        X
        
        XXXXXXXXXXXXXXXXXX XX X
            XXXXXXXX XXXXXX XX
            XXXXXX XXXXXXXXXXXXX
            XXXXXXXXXX XXXXXXX
        X
        
        XX XXXX XXXXXXXX XXXXXXXXXXXX XXXXXXX XXXX XX
        XXXXXXXXXXXXXXXXXXXXXX X
            XXXXXXXX XXXXX XX
            XXXXXXXXXXX XXXXXXXXXXXXXXXXX
        X
        
        XXXXXXXXXXXXXXXXXX X
            XXXXXXXX XXXXX
            XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXX
            XXXX XXXXX
            XXXXXXXXXXX XXXXX
        X
        
        XXXXXXXXXXXXXXXXX X
            XXXXXXXXXXX XXXXXXXXXXXX
            XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXX XXXXXXX
            XXXXXXXXXXX XXXXXXXXXXXXXXXXXX
            XXXXXXX XXX XXXXX XXXXXXXXX XXXX XXX XXXXX
        X
        
        XXXXXXXXXXXXXXXXXXXXXXX X
            XXXXXXXXXX XXXXXXXXXXXXXXXXX
            XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
        X
        
        XXXXXXXXXXXXXXXXXXX X
            XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
            XXXXXXXX XXXXXXX
            XXXXXX XXXXXXXXXXXXX
        X
        
        XXXXXXXXXXXXXXXXX X
            XXXXXXXXXX XXXXXXX
            XXXXXXXX XXXX
            XXXXXXXXXXXXXX XXXXXXX
        X
        
        XXXXXXXXXXXXXXXXXX X
            XXXXXXXXXX XXXXXXX
            XXXXXXXXXXXX XXXX
        X
        
        XXXXXXXXXXXXXXXXX X
            XXXXXXXX XXXXXXX
        X
        
        XXXXXXXXXXXXXXXXX X
            XXXXXXXX XXXXX
            XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
            XXXXXXXXXXXXXX XXXXX
            XXXXXXXXXX XXXXXXX
            XXXXXX XXXXXXXXXXXX
        X
        
        XX XXXX XXXX XXXXX XXXXXX XXXX XX
        XXXXXXXXXXXXXXXXXX X
            XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
            XXXXXX XXXXXXXXXXXX
            XXXXXXXXXXX XXXXXXX
            XXXXXXXX XXXXXXX
            XXXXXXXXXXXX XXXX
            XXXXXXXXX XXXXXXXXX
            XXXXXXXXX XXXXXXX
        X
        
        XXXXXXXXXXXXXXXXXXXXXXXXXX X
            XXXXXXXX XXX
            XXXXXXXXX XXXXXXXXX
            XXXX XX
            XXXXX XXXXXX
            XXXXXX XXXXX
            XXXXXXX XXXXX
            XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
            XXXXXXXXXX XXXXX XX XXXXXXXXX
        X
        
        XXXXXXXXXX XXXXX X
            XX X XXXXX XXXXXX X
            XXXX X XXXXX XXXXX X
        X
        
        XX XXXX XXXXXX XXXX XX
        XXXXXXX X
            XXXXXXXXXXX XXXXXXXXXXXX
            XXXXXXXX XXXX X XXXXX
            XXXXXXXXXXX XXX XXXXX XXXXXXXXXXXXXX
        X
        
        XXXXXXXXXXXX X
            XXXXXXXX XXXXX
            XXXXXXXXXXXXXXXXXXXXXX XXX XXX XXX XXXX
            XXXX XXXXX
            XXXXXXXXXXXXXX XXXXX
        X
        
        XXXXXXXXXXXXX XX X
            XXXXXXXXXX XXXXXXX
            XXXXXXXXXXXX XXXX
            XXXXXXXXXXXXXX XXXXX
            XXXXXX XXXXXXXXXXXXXX
        X
        
        XXXXXXXXXXXXX X X
            XXXXXX XXXXXXXXXXXX
            XXXXXXXXXXXX XXXX
            XXXXXXXXXXXXXX XXXXX
        X
        
        XXXXXXXXXXXXX X
            XXXXXXXX XXXXX
            XXXX XXXXX
        X
        
        XXXXXXXXXXXX X
            XXXXXX XXXXX
            XXXXXXX XXXXX
            XXXXXXXXXXX XXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXX XXXX
            XXXXXXXX XXXXX
            XXXXXXXXXXXX XXXXXXX
            XXXXXXXXXXXXXXXX XXXXXXX
            XXXXXX XXXXXXXXXXXXX
            XXXXXXXXXXX XXXXXXXXXXXXXXXXXX
        X
        
        XXXXXXXXXXXXXXXXXX X
            XXXXXXXXXXX XXXXXXXXXXXXXX
            XXXXXX XXXXXXXXXXXX
        X
        
        XXXXXXXXXXXXX XX X
            XXXXXXXXXX XXXXXXX
            XXXXXXXXXXXX XXXX
            XXXXXXXXXXXXXX XXXXXXX
            XXXXXX XXXXXXXXXXXXX
        X
        
        XXXXXXXXXXXXX XX X
            XXXXXXXXXXX XXXXX
        X
        
        XXXXXXXXXXXXX X X
            XXXXXX XXXXXXXXXXXX
            XXXXXXXXXXXXXXXX XXXXX
            XXXXXXXXXXX XXXXXXXXXXXXXXXXXX
            XXXXXXXX XXXXXX
            XXXXXXXX XXXXXX XX
        X
        
        XXXXXXXXXXXXX XXXXXXX X
            XXXXXX XXXXXXXXXXXXXX
            XXXXXXXXXXXXX XXXXXXX
        X
        
        XXXXXXXXXXXXXX X
            XXXXXXXXXXX XXXXXXX
            XXXXXXXXXXXX XXXXX
            XXXXXXXXXXX XXX XXXXX XXXXXXXXX XXXX XXXX XXXXX
            XXXXXX XXXXXXXXXXXX
        X
        
        XX XXXX XXXXXXXXXX XXXXXX XXXX XX
        XXXXXX XXXXXXXXXXX XXXXXX X
            XXXXXXXXXX X
                XXXXXXXX XXXXX
            X
            
            XXXXXXXXXXXXXXX X
                XXXXXXXXXXXXXXXXXXXXXX XXXX
                XXXX XXXXX
                XXXXXXXXXXX XXXXXXX
            X
            
            XXXXXXXXXXXXX XX X
                XXXXXXXXXX XXXXXXX
            X
            
            XXXXXXXXX X
                XXXXXXXXXXXXXXX XXXXXXX
            X
            
            XXXXXXXXXXX X
                XXXXXXXXXXXXXXXXXXXXXX XXXX
            X
            
            XXXXXXXXXXXX X
                XXXXXXXXXXXXXXXXXXXXXX XXXX
                XXXX XXXXX
            X
        X
        
        XX XXXX XXXXXXXXXX XXXX XX
        XXXXXXXX X
            XXXXXXXX XX
            XXXXXXXXXX XXXXXXXXXXXXXXXXX
            XXXXXXXXXXX XXX XXXX XXXXX
        X
        
        XXXXXXXXXXXXXXXX X
            XXXXXXXX XX
            XXXXXXXXXX XXXXXXXXXXXXXX
        X
        
        XX XXXX XXXXX XXXXXX XXXX XX
        XXXXXX X
            XXXXXXXX XXXXX
            XXXXXXXXX XXXXXX
            XXXXXXXX XXXXX
            XXXXX XX
            XXXX XX
            XXXXXX XXXXX
            XXXXXXX XXXXX
            XXXXXXXXXXXXXXXXX XXXXXXX XX XX XXXXX
            XXXXXXXXXXXXXXXX XXXXXXXXXX
        X
        
        XXXXXXXXXXXXXX X
            XXXXXXXXXXX XXXXXXXXXXXX
            XXXXXXX XX XXXXX
            XXXXXXXX XXXXX
            XXXXXXX XXX XXXXX XXXXXXXXXXXXXX
            XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
            XXXXXX XXXX
            XXXXXXXXXX XXXXXX
            XXXXXXXXX XXXXXXXXX
        X
        
        XXXXXXXXXXXX X
            XXXXXXXXX XXXXXXXXX
            XXXX XXXXX
            XXXXXX XXXXXXX
            XXXXXXXXXX XXXXX
            XXXXXX XXXXXXXXXXXX
            XXXXXXX XXXXXXXX
            XXXXXXXXXXX XXXXXXXXXXXXXXXXXX
        X
        
        XXXXXXXXXXXXXXXXXX X
            XXXXXX XXXXXXXXXXXXXX
        X
        
        XXXXXX XX X
            XXXXXXXXXXXXXX XXXXX
            XXXXXX XXXXXXXXXXXXX
        X
        
        XXXXXXXXXXX X
            XXXXXXXXXXXXXX XXXXXXX
        X
        
        XXXXXXXXXXX XXXXX X
            XXXXXXXX XXXXXX
            XXXXXXXXXXXXXX XXXXXXX
            XXXXXX XXXXXXXXXXXXX
            XXXXXXXXXXXX XXXX
        X
        
        XXXXXXXXXXX XXXXX X
            XXXXXX XXXXX
            XXXXXXXX XXXXXXXX
            XXXXXXX XXX XXXXX XXXXXXXXX XXXX XXXX XXXXX
            XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXX XXXXXXXXXXXXXXXXX
            XXXXXX XXXXXXXXXXXXX
            XXXXXXXXXXX XXXXXXXXXXXXXXXXXX
        X
        
        XXXXXXXXXXX XXXXXXXXXXX X
            XXXXXXXX XXXXX
            XXXXXXXXXXXXX XXXXXXXXXXXXXX
        X
    XXXXXXXX
XXXXXXX

XXXXXX
    XXXX XXXX XXXXX XXXXXX XXX
    BB BBBBBBBBBBBBB
    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
        XX XXXXXXXXXX XXXXXXXXXXXXXX
         gettext(u'Phase de test en cours')  X gettext(u'1er-30 juin 2025') X X 
         gettext(u'Lancement officiel') X  gettext(u'1er juillet 2025')  X 
        XXXXXXXX gettext(u'Rejoignez les testeurs !') XXXXXXXXX
    XXXXXX
    BBBBB
    
    XXXX XXXXXX XXX
    XXXXXXX XXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXX
            XX XXXXXXXX XXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXX
                    XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                XXXXXX
                XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXX
            
            XXXX XXXXXXXXXXXXXXXXXX
                XX XXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Fonctionnalités') XXXX
                XX XXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Solutions') XXXX
                XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Compétitions') XXXX
                XX XXXXXXXXXXXXXXXX gettext(u'Contact') XXXX
            XXXXXX
            
            XXXX XXXXXXXXXXXXXXXXXXXXX
                XXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                     gettext(u'Se connecter') 
                XXXXXXXXX
                XX XXXXXXBBB BBBBBBBBX XXXXXXXXXX XXXXXXXXXXXXX
                    XX XXXXXXXXXX XXXXXXXXXXXXXXXXXX
                     gettext(u'Rejoindre la phase de test') 
                XXXX
            XXXXXX
        XXXXXX
    XXXXXXXXX
    
    XXXX XXXX XXXXXXX XXX
    XXXXXXXX XXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXX
                XXXX gettext(u"La solution complète pour vos compétitions d'arts martiaux") XXXXX
                XX XXXXXXXXXXXXXXXXX
                     gettext(u'Simplicité • Professionnalisme • Innovation') 
                XXXX
                XX XXXXXXXXXXXXXXXXXXXX
                     gettext(u"MartialComp révolutionne l'organisation des compétitions d'arts martiaux avec une plateforme tout-en-un qui simplifie la gestion des événements, des inscriptions, de la notation et des résultats pour tous les acteurs du milieu.") 
                XXXX
                
                XXXX XXXXXXXXXXXXXXXXX
                    XX XXXXXXBBB BBBBBBBBX XXXXXXXXXX XXXXXXXXXXXXX
                        XX XXXXXXXXXX XXXXXXXXXXXXXXX
                         gettext(u'Commencer maintenant') 
                    XXXX
                    XXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XX XXXXXXXXXX XXXXXXXXXXXXX
                         gettext(u'Voir la démo') 
                    XXXXXXXXX
                XXXXXX
                
                XXXX XXXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXXXFFFFFFFFFFFFFXXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXX gettext(u'Compétitions organisées') XXXXXX
                    XXXXXX
                    XXXX XXXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXXXFFFFFFFFFFFFFFXXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXX gettext(u'Pratiquants actifs') XXXXXX
                    XXXXXX
                    XXXX XXXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXX gettext(u'Langues supportées') XXXXXX
                    XXXXXX
                XXXXXX
            XXXXXX
            
            XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXX
                XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXX gettext(u'Interface MartialComp') X XXXXXXXXXXXXXXXXXXX
            XXXXXX
        XXXXXX
    XXXXXXXXXX
    
    XXXX XXXXX XXXXXXXXXXX XXXXXXX XXX
    XXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
                XXX XXXXXXXXXXXXXXXXXXXXXX gettext(u'Pourquoi choisir MartialComp ?') XXXXX
                XX XXXXXXXXXXXXXXXXXXXXXXXXX
                     gettext(u"Une solution complète qui couvre tous vos besoins, de la création d'événements à la publication des résultats") 
                XXXX
            XXXXXX
            
            XXXX XXXXXXXXXXXXXXXXXXX
                BBB BBBBBBB BB BBBBBBBBBBBB
                XXXX XXXXXXXXXXXXXXXXX XXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXX
                        XX XXXXXXXXXX XXXXXXXXX
                    XXXXXX
                    XXXXXXXXX
                    XXXXXXX
                    XXX XXXXXXXXXXXXXXXXXXXXX
                        BBB BBBBBBB BB BBBBBBBBBBBBBBBB
                        XXXXXXXXX
                        BBBBBB
                    XXXXX
                    XX XXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX gettext(u'En savoir plus') XXXX
                XXXXXX
                BBBBBB
            XXXXXX
        XXXXXX
    XXXXXXXXXX
    
    XXXX XXXXXX XXXXXXXXX XXXXXXX XXX
    XXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
                XXX XXXXXXXXXXXXXXXXXXXXXX gettext(u'Solutions adaptées à chaque public') XXXXX
                XX XXXXXXXXXXXXXXXXXXXXXXXXX
                     gettext(u"Des outils spécialisés pour chaque acteur de l'écosystème des arts martiaux") 
                XXXX
            XXXXXX
            
            XXXX XXXXXXXXXXXXXXXXXXXXXX
                BBB BBBBBBBB BB BBBBBBBBBBBBBBBB
                XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXXX
                        XX XXXXXXXXXX XXXXXXXXX
                    XXXXXX
                    XXXXXXXXX
                    XXXXXXX
                    XXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                        BBB BBBBBBB BB BBBBBBBBBBBBBBBBB
                        XXXXX XXXXX
                        BBBBBB
                    XXXXX
                    XX XXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXX
                XXXXXX
                BBBBBB
            XXXXXX
        XXXXXX
    XXXXXXXXXX
    
    XXXX XXXXXXXX XXXXXXXXXXXX XXXXXXX XXX
    XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
                XXX XXXXXXXXXXXXXXXXXXXXXX gettext(u'Prochaines compétitions') XXXXX
                XX XXXXXXXXXXXXXXXXXXXXXXXXX
                     gettext(u'Découvrez les événements organisés sur notre plateforme') 
                XXXX
            XXXXXX
            
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                BBB BBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBBB
                XXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                            XX XXXXXXXXXX XXXXXXXXXXXXXXXXX
                            FFFFFFF F FF
                        XXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                            XXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX FFFFFFFFFF FFFFFFFFXXXXXXX
                            XXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXX FFFFFFFFFFFFFFFFFFXXXXXXX
                        XXXXXX
                        XXXFFFFFFFFFFFFFFFFFXXXX
                        XX XXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX gettext(u"S'inscrire") XXXX
                    XXXXXX
                XXXXXX
                BBBBB
                XXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                            XX XXXXXXXXXX XXXXXXXXXXXXXXXXX
                             gettext(u'Bientôt disponible') 
                        XXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u"Championnats d'été 2025") XXXXXX
                    XXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                            XXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX  gettext(u'Multi-sites') XXXXXXX
                            XXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXX  gettext(u'Ouvert à tous') XXXXXXX
                        XXXXXX
                        XXX gettext(u'Première saison de compétitions organisées via MartialComp. Toutes disciplines confondues.') XXXX
                        XX XXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX gettext(u'Être notifié') XXXX
                    XXXXXX
                XXXXXX
                BBBBBB
            XXXXXX
        XXXXXX
    XXXXXXXXXX
    
    XXXX XXXXXX XXX
    XXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXXXX
                    XXX
                         gettext(u"La référence en matière de gestion de compétitions d'arts martiaux. Une solution complète pour organisateurs, clubs, arbitres et compétiteurs.") 
                    XXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXX
                        XX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                        XX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                        XX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                        XX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                    XXXXXX
                XXXXXX
                
                XXXX XXXXXXXXXXXXXXXXXXXXX
                    XXXX gettext(u'Plateforme') XXXXX
                    XXXX
                        XXXXXX XXXXXXXXX gettext(u'Fonctionnalités') XXXXXXXXX
                        XXXXXX XXXXXXXXX gettext(u'Tarifs') XXXXXXXXX
                        XXXXXX XXXXXXXXX gettext(u'Intégrations') XXXXXXXXX
                        XXXXXX XXXXXXXXX gettext(u'API') XXXXXXXXX
                    XXXXX
                XXXXXX
                
                XXXX XXXXXXXXXXXXXXXXXXXXX
                    XXXX gettext(u'Ressources') XXXXX
                    XXXX
                        XXXXXX XXXXXXXXX gettext(u"Guide d'utilisation") XXXXXXXXX
                        XXXXXX XXXXXXXXX gettext(u"Centre d'aide") XXXXXXXXX
                        XXXXXX XXXXXXXXX gettext(u'Webinaires') XXXXXXXXX
                        XXXXXX XXXXXXXXX gettext(u'Blog') XXXXXXXXX
                    XXXXX
                XXXXXX
                
                XXXX XXXXXXXXXXXXXXXXXXXXX
                    XXXX gettext(u'Contact') XXXXX
                    XXXX
                        XXXXXX XXXXXXXXX gettext(u'Support') XXXXXXXXX
                        XXXXXX XXXXXXXXX gettext(u'Démonstration') XXXXXXXXX
                        XXXXXX XXXXXXXXX gettext(u'Partenaires') XXXXXXXXX
                        XXXXXX XXXXXXXXX gettext(u'Nous rejoindre') XXXXXXXXX
                    XXXXX
                XXXXXX
            XXXXXX
            
            XXXX XXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXX XXXX XXXXXXXXXXXX  gettext(u'Tous droits réservés.') XXXX
            XXXXXX
        XXXXXX
    XXXXXXXXX
    
    XXXX XXXXX XXXXX XXX
    XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXX
            XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXX gettext(u'Connexion') XXXXX
            XXXXX XXXXXXXXBBB BBBBBBBX XXXXXXXXXXXXXX
                BBBBBBBBBB
                XXXX XXXXXXXXXXXXXXXXXXX
                    XXXXXX XXXXXXXXXXXXXXX gettext(u"Nom d'utilisateur") XXXXXXXX
                    XXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXX
                XXXXXX
                XXXX XXXXXXXXXXXXXXXXXXX
                    XXXXXX XXXXXXXXXXXXXXX gettext(u'Mot de passe') XXXXXXXX
                    XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXX
                XXXXXX
                XXXXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFXX
                XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXX
                     gettext(u'Se connecter') 
                XXXXXXXXX
            XXXXXXX
            XXXX XXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXX XXXXXX XXXXXXXXXXXXXX
                XXX gettext(u'Pas encore de compte ?')  XX XXXXXXBBB BBBBBBBBX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX gettext(u'Rejoignez la phase de test') XXXXXXXX
            XXXXXX
        XXXXXX
    XXXXXX
    
    XXXXXXXX
        XX XXXXXXXXXX XX XXXXXX
        XXXXX XXXXXXXXXXXXXXX X X
            XXXXXXXXXX XXXX
            XXXXXXXXXXX XXXX XXX XXXXX XXXX
        XX
        
        XXXXX XXXXXXXX X XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX X
            XXXXXXXXXXXXXXXXXXXXX XX X
                XX XXXXXXXXXXXXXXXXXXXXXX X
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                X
            XXX
        XX XXXXXXXXXXXXXXXXX
        
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX X
            XXXXXXXXXXXXXXXXXXXXX
        XXX
        
        XX XXXXXXX XXX XXXXXXX
        XXXXXXXX XXXXXXXXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXX
        X
        
        XXXXXXXX XXXXXXXXXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXX
        X
        
        XX XXXXXX XXXXXX XX XXXXXXXX X XXXXXXXXXXX
        XXXXXXXXXXXXXX X XXXXXXXXXXXXXXX X
            XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
                XXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXX
            X
        X
        
        XX XXXXXX XXXXXX XXXX XXX XXXXXXXX
        XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXX XXXXXXXX
            XXX
        X
        
        XX XXXXXX XXXXXX XXXX XXXX XXX XXXXX XXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX X
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXX X
                XXXXXXXXXXXXXXXXXXX
                XXXXX XXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XX XXXXXXXX X
                    XXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXXXXX XXXXXXXXX
                        XXXXXX XXXXXXX
                    XXX
                X
            XXX
        XXX
        
        XX XXXXXX XXXXXX XXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XX X
            XXXXX XXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XX XXXXXXXXXXXXXXX X XXXX X
                XXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXX XXX XXX XXXXXXX
            X XXXX X
                XXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXX
            X
        XXX
    XXXXXXXXX
XXXXXXX
XXXXXXX