# Generated by Django 5.1.4 on 2025-05-29 22:02

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayPerUseFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('description', models.TextField(verbose_name='Description')),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix par unité')),
                ('unit_label', models.CharField(max_length=50, verbose_name="Libellé de l'unité")),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
            ],
            options={
                'verbose_name': "Fonctionnalité à l'usage",
                'verbose_name_plural': "Fonctionnalités à l'usage",
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PromotionCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Code')),
                ('description', models.TextField(verbose_name='Description')),
                ('discount_type', models.CharField(choices=[('percentage', 'Pourcentage de réduction'), ('fixed', 'Montant fixe de réduction'), ('free_months', 'Mois gratuits')], max_length=20, verbose_name='Type de réduction')),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valeur de la réduction')),
                ('valid_from', models.DateTimeField(verbose_name='Valide à partir de')),
                ('valid_until', models.DateTimeField(verbose_name="Valide jusqu'à")),
                ('max_uses', models.PositiveIntegerField(blank=True, null=True, verbose_name="Nombre max d'utilisations")),
                ('current_uses', models.PositiveIntegerField(default=0, verbose_name='Utilisations actuelles')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
            ],
            options={
                'verbose_name': 'Code promotionnel',
                'verbose_name_plural': 'Codes promotionnels',
                'ordering': ['-valid_until'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('description', models.TextField(verbose_name='Description')),
                ('price_monthly', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix mensuel')),
                ('price_annually', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix annuel')),
                ('max_users', models.PositiveIntegerField(verbose_name="Nombre max d'utilisateurs")),
                ('max_competitions', models.PositiveIntegerField(verbose_name='Nombre max de compétitions')),
                ('max_storage_gb', models.PositiveIntegerField(verbose_name='Stockage max (GB)')),
                ('features', models.JSONField(default=dict, verbose_name='Fonctionnalités')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
            ],
            options={
                'verbose_name': "Niveau d'abonnement",
                'verbose_name_plural': "Niveaux d'abonnement",
                'ordering': ['price_monthly'],
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name="Nom de l'organisation")),
                ('slug', models.SlugField(unique=True, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.RegexValidator(message='Seuls les lettres minuscules, chiffres et tirets sont autorisés.', regex='^[a-z0-9-]+$')], verbose_name='Identifiant')),
                ('schema_name', models.CharField(max_length=63, unique=True, validators=[django.core.validators.RegexValidator(message='Le nom du schéma doit commencer par une lettre et contenir uniquement des lettres minuscules, chiffres et underscores.', regex='^[a-z][a-z0-9_]*$')], verbose_name='Nom du schéma PostgreSQL')),
                ('domain', models.CharField(help_text='Ex: club1.martialcomp.com', max_length=253, unique=True, verbose_name='Domaine principal')),
                ('continent', models.CharField(choices=[('africa', 'Afrique'), ('asia_se', 'Asie du Sud-Est'), ('asia_other', 'Asie (autres)'), ('south_america', 'Amérique du Sud'), ('central_america', 'Amérique Centrale'), ('europe_east', "Europe de l'Est"), ('europe_west', "Europe de l'Ouest"), ('north_america', 'Amérique du Nord'), ('oceania', 'Océanie'), ('middle_east', 'Moyen-Orient')], help_text='Détermine la grille tarifaire applicable', max_length=20, verbose_name='Continent')),
                ('country', models.CharField(max_length=2, verbose_name='Pays')),
                ('timezone', models.CharField(default='UTC', max_length=50, verbose_name='Fuseau horaire')),
                ('currency', models.CharField(default='EUR', max_length=3, verbose_name='Devise')),
                ('language', models.CharField(default='fr', max_length=10, verbose_name='Langue')),
                ('subscription_plan', models.CharField(choices=[('essentials', 'Dojo Essentials'), ('masters', "Master's Circle"), ('champion', 'Grand Champion Suite'), ('trial', 'Essai Gratuit')], default='trial', max_length=20, verbose_name="Plan d'abonnement")),
                ('subscription_start_date', models.DateTimeField(blank=True, null=True, verbose_name="Début d'abonnement")),
                ('subscription_end_date', models.DateTimeField(blank=True, null=True, verbose_name="Fin d'abonnement")),
                ('is_trial', models.BooleanField(default=True, verbose_name="En période d'essai")),
                ('trial_end_date', models.DateTimeField(blank=True, null=True, verbose_name="Fin de l'essai")),
                ('payment_provider', models.CharField(choices=[('stripe', 'Stripe'), ('stripe_connect', 'Stripe Connect'), ('paystack', 'Paystack'), ('mercado_pago', 'Mercado Pago'), ('alipay', 'Alipay'), ('paytm', 'Paytm'), ('custom', 'Custom Provider')], default='stripe', max_length=20, verbose_name='Fournisseur de paiement')),
                ('payment_config', models.JSONField(default=dict, help_text='Configuration spécifique au fournisseur de paiement (clés API, etc.)', verbose_name='Configuration paiement')),
                ('stripe_account_id', models.CharField(blank=True, help_text='Pour les organisations utilisant Stripe Connect', max_length=255, verbose_name='ID Compte Stripe Connect')),
                ('max_users', models.PositiveIntegerField(default=100, verbose_name="Nombre max d'utilisateurs")),
                ('max_disciplines', models.PositiveIntegerField(default=2, verbose_name='Nombre max de disciplines')),
                ('features_config', models.JSONField(default=dict, help_text='Fonctionnalités activées/désactivées selon le plan', verbose_name='Configuration des fonctionnalités')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('activated_at', models.DateTimeField(blank=True, null=True, verbose_name="Date d'activation")),
                ('deactivated_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de désactivation')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_tenants', to=settings.AUTH_USER_MODEL, verbose_name='Propriétaire')),
            ],
            options={
                'verbose_name': 'Tenant',
                'verbose_name_plural': 'Tenants',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('card', 'Carte bancaire'), ('bank_account', 'Compte bancaire'), ('paypal', 'PayPal'), ('mobile_money', 'Mobile Money')], max_length=20, verbose_name='Type')),
                ('is_default', models.BooleanField(default=False, verbose_name='Méthode par défaut')),
                ('display_name', models.CharField(help_text='Ex: Visa se terminant par 4242', max_length=100, verbose_name="Nom d'affichage")),
                ('provider_method_id', models.CharField(max_length=255, unique=True, verbose_name='ID de la méthode chez le fournisseur')),
                ('provider', models.CharField(max_length=50, verbose_name='Fournisseur')),
                ('provider_metadata', models.JSONField(blank=True, default=dict, verbose_name='Métadonnées du fournisseur')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to='multitenant.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Méthode de paiement',
                'verbose_name_plural': 'Méthodes de paiement',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LegacyTenantSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plan', models.CharField(choices=[('essentials', 'Dojo Essentials'), ('masters', "Master's Circle"), ('champion', 'Grand Champion Suite'), ('trial', 'Essai Gratuit')], max_length=50, verbose_name="Plan d'abonnement")),
                ('status', models.CharField(choices=[('active', 'Actif'), ('cancelled', 'Annulé'), ('expired', 'Expiré'), ('suspended', 'Suspendu')], default='active', max_length=20, verbose_name='Statut')),
                ('start_date', models.DateTimeField(verbose_name='Date de début')),
                ('end_date', models.DateTimeField(verbose_name='Date de fin')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name="Date d'annulation")),
                ('next_billing_date', models.DateTimeField(blank=True, null=True, verbose_name='Prochaine date de facturation')),
                ('subscription_id', models.CharField(help_text="ID de l'abonnement chez le fournisseur", max_length=255, unique=True, verbose_name="ID d'abonnement")),
                ('payment_provider', models.CharField(max_length=50, verbose_name='Fournisseur de paiement')),
                ('provider_metadata', models.JSONField(blank=True, default=dict, verbose_name='Métadonnées du fournisseur')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='legacy_subscription', to='multitenant.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Abonnement tenant (legacy)',
                'verbose_name_plural': 'Abonnements tenant (legacy)',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeatureUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantité')),
                ('usage_date', models.DateTimeField(verbose_name="Date d'utilisation")),
                ('billed', models.BooleanField(default=False, verbose_name='Facturé')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usages', to='multitenant.payperusefeature')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_usages', to='multitenant.tenant')),
            ],
            options={
                'verbose_name': 'Utilisation de fonctionnalité',
                'verbose_name_plural': 'Utilisations de fonctionnalités',
                'ordering': ['-usage_date'],
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=253, unique=True, verbose_name='Domaine')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Domaine principal')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='multitenant.tenant')),
            ],
            options={
                'verbose_name': 'Domaine',
                'verbose_name_plural': 'Domaines',
                'ordering': ['-is_primary', 'domain'],
            },
        ),
        migrations.CreateModel(
            name='TenantFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_code', models.CharField(help_text='Ex: advanced_reporting, api_access, mobile_app', max_length=50, verbose_name='Code de la fonctionnalité')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='Activé')),
                ('enabled_until', models.DateTimeField(blank=True, help_text='Pour les fonctionnalités temporaires', null=True, verbose_name="Activé jusqu'à")),
                ('metadata', models.JSONField(default=dict, help_text='Configuration spécifique à la fonctionnalité', verbose_name='Métadonnées')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_features', to='multitenant.tenant')),
            ],
            options={
                'verbose_name': 'Fonctionnalité tenant',
                'verbose_name_plural': 'Fonctionnalités tenant',
                'ordering': ['feature_code'],
            },
        ),
        migrations.CreateModel(
            name='TenantPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant')),
                ('currency', models.CharField(default='EUR', max_length=3, verbose_name='Devise')),
                ('description', models.CharField(help_text='Description du paiement', max_length=255, verbose_name='Description')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('completed', 'Complété'), ('failed', 'Échoué'), ('refunded', 'Remboursé'), ('cancelled', 'Annulé')], default='pending', max_length=20, verbose_name='Statut')),
                ('payment_method', models.CharField(choices=[('card', 'Carte bancaire'), ('bank_transfer', 'Virement bancaire'), ('paypal', 'PayPal'), ('mobile_money', 'Mobile Money'), ('other', 'Autre')], max_length=20, verbose_name='Méthode de paiement')),
                ('provider', models.CharField(help_text='Ex: stripe, paystack, etc.', max_length=50, verbose_name='Fournisseur de paiement')),
                ('provider_payment_id', models.CharField(help_text='ID du paiement chez le fournisseur', max_length=255, unique=True, verbose_name='ID de paiement du fournisseur')),
                ('provider_metadata', models.JSONField(blank=True, default=dict, verbose_name='Métadonnées du fournisseur')),
                ('subscription_period_start', models.DateTimeField(blank=True, null=True, verbose_name='Début de la période')),
                ('subscription_period_end', models.DateTimeField(blank=True, null=True, verbose_name='Fin de la période')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('invoice_id', models.CharField(blank=True, help_text='Référence de la facture associée', max_length=100, verbose_name='Numéro de facture')),
                ('payment_date', models.DateTimeField(blank=True, null=True, verbose_name='Date du paiement')),
                ('failure_reason', models.TextField(blank=True, help_text="Détails en cas d'échec du paiement", verbose_name="Raison de l'échec")),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_payments', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='multitenant.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Paiement tenant',
                'verbose_name_plural': 'Paiements tenant',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TenantSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Mensuel'), ('annually', 'Annuel')], max_length=10, verbose_name='Cycle de facturation')),
                ('status', models.CharField(choices=[('active', 'Actif'), ('past_due', 'En retard de paiement'), ('canceled', 'Annulé'), ('trialing', "En période d'essai")], default='active', max_length=10, verbose_name='Statut')),
                ('start_date', models.DateTimeField(verbose_name='Date de début')),
                ('end_date', models.DateTimeField(verbose_name='Date de fin')),
                ('auto_renew', models.BooleanField(default=True, verbose_name='Renouvellement automatique')),
                ('payment_provider_subscription_id', models.CharField(blank=True, max_length=255, null=True, verbose_name="ID d'abonnement fournisseur")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='multitenant.tenant')),
                ('tier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tenant_subscriptions', to='multitenant.subscriptiontier')),
            ],
            options={
                'verbose_name': 'Abonnement tenant',
                'verbose_name_plural': 'Abonnements tenant',
                'ordering': ['-start_date'],
            },
        ),
        migrations.AddIndex(
            model_name='tenant',
            index=models.Index(fields=['domain'], name='multitenant_domain_5f6a4e_idx'),
        ),
        migrations.AddIndex(
            model_name='tenant',
            index=models.Index(fields=['schema_name'], name='multitenant_schema__b64901_idx'),
        ),
        migrations.AddIndex(
            model_name='tenant',
            index=models.Index(fields=['is_active', 'subscription_end_date'], name='multitenant_is_acti_818ec6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='paymentmethod',
            unique_together={('tenant', 'is_default')},
        ),
        migrations.AlterUniqueTogether(
            name='tenantfeature',
            unique_together={('tenant', 'feature_code')},
        ),
        migrations.AddIndex(
            model_name='tenantpayment',
            index=models.Index(fields=['tenant', 'status'], name='multitenant_tenant__ce6f7e_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantpayment',
            index=models.Index(fields=['provider_payment_id'], name='multitenant_provide_3fd7ea_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantpayment',
            index=models.Index(fields=['created_at'], name='multitenant_created_12fcae_idx'),
        ),
    ]
