# Generated by Django 5.1.4 on 2025-05-23 08:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multitenant', '0007_handle_missing_tables'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tenantsubscription',
            options={'ordering': ['-start_date'], 'verbose_name': 'Abonnement tenant', 'verbose_name_plural': 'Abonnements tenant'},
        ),
        migrations.RemoveField(
            model_name='subscriptiontier',
            name='subscriptions',
        ),
        migrations.RemoveField(
            model_name='tenantsubscription',
            name='cancelled_at',
        ),
        migrations.RemoveField(
            model_name='tenantsubscription',
            name='next_billing_date',
        ),
        migrations.RemoveField(
            model_name='tenantsubscription',
            name='payment_provider',
        ),
        migrations.RemoveField(
            model_name='tenantsubscription',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='tenantsubscription',
            name='provider_metadata',
        ),
        migrations.RemoveField(
            model_name='tenantsubscription',
            name='subscription_id',
        ),
        migrations.AddField(
            model_name='tenantsubscription',
            name='auto_renew',
            field=models.BooleanField(default=True, verbose_name='Renouvellement automatique'),
        ),
        migrations.AddField(
            model_name='tenantsubscription',
            name='billing_cycle',
            field=models.CharField(choices=[('monthly', 'Mensuel'), ('annually', 'Annuel')], default=django.utils.timezone.now, max_length=10, verbose_name='Cycle de facturation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tenantsubscription',
            name='payment_provider_subscription_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="ID d'abonnement fournisseur"),
        ),
        migrations.AddField(
            model_name='tenantsubscription',
            name='tier',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.PROTECT, related_name='tenant_subscriptions', to='multitenant.subscriptiontier'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tenantsubscription',
            name='status',
            field=models.CharField(choices=[('active', 'Actif'), ('past_due', 'En retard de paiement'), ('canceled', 'Annulé'), ('trialing', "En période d'essai")], default='active', max_length=10, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='tenantsubscription',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='multitenant.tenant'),
        ),
    ]
