# Generated by Django 5.1.6 on 2025-08-20 14:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('finances', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentattempt',
            name='payee_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_attempt_payee_ct', to='contenttypes.contenttype', verbose_name='Type du bénéficiaire'),
        ),
        migrations.AddField(
            model_name='paymentattempt',
            name='payee_object_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ID du bénéficiaire'),
        ),
        migrations.AddField(
            model_name='paymentattempt',
            name='payer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_attempts_made', to=settings.AUTH_USER_MODEL, verbose_name='Émetteur'),
        ),
    ]
