# Generated by Django 5.1.6 on 2025-12-02 12:52

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0013_alter_equipe_options_and_more'),
        ('finances', '0002_paymentattempt_payee_content_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankImportBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=255, verbose_name='Nom du fichier')),
                ('file_format', models.CharField(choices=[('csv', 'CSV'), ('xlsx', 'Excel (XLSX)'), ('xls', 'Excel (XLS)'), ('ofx', 'OFX'), ('qif', 'QIF')], default='csv', max_length=20, verbose_name='Format du fichier')),
                ('bank_format', models.CharField(choices=[('BNP_FORTIS_BE', 'BNP Paribas Fortis (Belgique)'), ('ING_BE', 'ING (Belgique)'), ('KBC_BE', 'KBC (Belgique)'), ('BELFIUS_BE', 'Belfius (Belgique)'), ('SOCIETE_GENERALE_FR', 'Société Générale (France)'), ('CREDIT_AGRICOLE_FR', 'Crédit Agricole (France)'), ('BNP_FR', 'BNP Paribas (France)'), ('BOURSORAMA_FR', 'Boursorama (France)'), ('DEUTSCHE_BANK_DE', 'Deutsche Bank (Allemagne)'), ('SPARKASSE_DE', 'Sparkasse (Allemagne)'), ('ORANGE_MONEY_CI', "Orange Money (Côte d'Ivoire)"), ('WAVE_SN', 'Wave (Sénégal)'), ('MPESA_KE', 'M-Pesa (Kenya)'), ('GENERIC', 'Format générique')], default='GENERIC', max_length=50, verbose_name='Format bancaire')),
                ('file', models.FileField(blank=True, null=True, upload_to='finances/bank_imports/%Y/%m/', verbose_name='Fichier original')),
                ('total_transactions', models.IntegerField(default=0, verbose_name='Total transactions')),
                ('imported_count', models.IntegerField(default=0, verbose_name='Importées')),
                ('duplicate_count', models.IntegerField(default=0, verbose_name='Doublons')),
                ('error_count', models.IntegerField(default=0, verbose_name='Erreurs')),
                ('total_income', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Total revenus')),
                ('total_expense', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Total dépenses')),
                ('date_start', models.DateField(blank=True, null=True, verbose_name='Date début')),
                ('date_end', models.DateField(blank=True, null=True, verbose_name='Date fin')),
                ('status', models.CharField(choices=[('pending', 'En cours'), ('processing', 'Traitement en cours'), ('completed', 'Terminé'), ('completed_with_errors', 'Terminé avec erreurs'), ('failed', 'Échoué')], default='pending', max_length=30, verbose_name='Statut')),
                ('error_log', models.TextField(blank=True, verbose_name='Journal des erreurs')),
                ('import_date', models.DateTimeField(auto_now_add=True, verbose_name="Date d'import")),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Terminé le')),
                ('financial_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_batches', to='finances.financialaccount', verbose_name='Compte financier')),
                ('imported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_imports', to=settings.AUTH_USER_MODEL, verbose_name='Importé par')),
            ],
            options={
                'verbose_name': "Lot d'import bancaire",
                'verbose_name_plural': "Lots d'import bancaires",
                'ordering': ['-import_date'],
            },
        ),
        migrations.CreateModel(
            name='BankTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_reference', models.CharField(max_length=100, verbose_name='Référence externe')),
                ('transaction_date', models.DateField(verbose_name="Date d'exécution")),
                ('value_date', models.DateField(verbose_name='Date valeur')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant')),
                ('currency', models.CharField(default='EUR', max_length=3, verbose_name='Devise')),
                ('transaction_type', models.CharField(choices=[('INCOME', 'Revenu'), ('EXPENSE', 'Dépense')], max_length=10, verbose_name='Type')),
                ('payment_method', models.CharField(choices=[('virement_instantane', 'Virement instantané'), ('virement', 'Virement'), ('paiement_carte', 'Paiement par carte'), ('paiement_carte_credit', 'Paiement par carte de crédit'), ('prelevement', 'Prélèvement'), ('cheque', 'Chèque'), ('especes', 'Espèces'), ('mobile_money', 'Mobile Money'), ('autre', 'Autre')], default='autre', max_length=50, verbose_name='Méthode de paiement')),
                ('payment_method_raw', models.CharField(blank=True, max_length=200, verbose_name='Méthode de paiement (brut)')),
                ('counterparty_iban', models.CharField(blank=True, max_length=34, verbose_name='IBAN contrepartie')),
                ('counterparty_name', models.CharField(blank=True, max_length=200, verbose_name='Nom contrepartie')),
                ('communication', models.TextField(blank=True, verbose_name='Communication')),
                ('raw_details', models.TextField(blank=True, verbose_name='Détails bruts')),
                ('bank_status', models.CharField(default='Accepté', max_length=50, verbose_name='Statut bancaire')),
                ('reconciliation_status', models.CharField(choices=[('pending', 'En attente'), ('matched', 'Rapproché'), ('partial', 'Partiellement rapproché'), ('unmatched', 'Non rapproché'), ('ignored', 'Ignoré'), ('duplicate', 'Doublon')], default='pending', max_length=20, verbose_name='Statut réconciliation')),
                ('reconciliation_score', models.IntegerField(default=0, verbose_name='Score de confiance (%)')),
                ('reconciliation_notes', models.TextField(blank=True, verbose_name='Notes de réconciliation')),
                ('reconciled_at', models.DateTimeField(blank=True, null=True, verbose_name='Réconcilié le')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('import_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='finances.bankimportbatch', verbose_name="Lot d'import")),
                ('matched_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finances.transactioncategory', verbose_name='Catégorie')),
                ('matched_practitioner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_transactions', to='competitions.practitioner', verbose_name='Pratiquant identifié')),
                ('matched_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_transactions', to='finances.transaction', verbose_name='Transaction système')),
                ('reconciled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reconciled_bank_transactions', to=settings.AUTH_USER_MODEL, verbose_name='Réconcilié par')),
            ],
            options={
                'verbose_name': 'Transaction bancaire',
                'verbose_name_plural': 'Transactions bancaires',
                'ordering': ['-transaction_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PractitionerBankInfo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('iban', models.CharField(max_length=34, verbose_name='IBAN')),
                ('bic', models.CharField(blank=True, max_length=11, verbose_name='BIC/SWIFT')),
                ('account_holder_name', models.CharField(blank=True, max_length=200, verbose_name='Titulaire du compte')),
                ('name_variants', models.JSONField(blank=True, default=list, help_text='Liste des noms alternatifs pour le matching', verbose_name='Variantes de nom')),
                ('is_primary', models.BooleanField(default=True, verbose_name='Compte principal')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Vérifié')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('practitioner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_infos', to='competitions.practitioner', verbose_name='Pratiquant')),
            ],
            options={
                'verbose_name': 'Info bancaire pratiquant',
                'verbose_name_plural': 'Infos bancaires pratiquants',
            },
        ),
        migrations.CreateModel(
            name='ReconciliationRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Nom de la règle')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('organization_id', models.CharField(blank=True, max_length=50, verbose_name='ID Organisation')),
                ('match_field', models.CharField(choices=[('communication', 'Communication'), ('counterparty_name', 'Nom contrepartie'), ('counterparty_iban', 'IBAN contrepartie'), ('amount', 'Montant'), ('raw_details', 'Détails bruts')], max_length=50, verbose_name='Champ à matcher')),
                ('match_type', models.CharField(choices=[('contains', 'Contient'), ('exact', 'Correspondance exacte'), ('starts_with', 'Commence par'), ('ends_with', 'Finit par'), ('regex', 'Expression régulière'), ('amount_range', 'Plage de montant'), ('amount_exact', 'Montant exact')], max_length=20, verbose_name='Type de match')),
                ('match_value', models.CharField(max_length=500, verbose_name='Valeur à chercher')),
                ('min_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Montant minimum')),
                ('max_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Montant maximum')),
                ('transaction_type', models.CharField(blank=True, choices=[('INCOME', 'Revenu'), ('EXPENSE', 'Dépense')], max_length=10, verbose_name='Type de transaction')),
                ('action_type', models.CharField(choices=[('assign_category', 'Assigner catégorie'), ('assign_practitioner', 'Assigner pratiquant'), ('ignore', 'Ignorer'), ('flag_review', 'Marquer pour révision')], default='assign_category', max_length=30, verbose_name='Action')),
                ('priority', models.IntegerField(default=0, verbose_name='Priorité')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('times_applied', models.IntegerField(default=0, verbose_name='Fois appliquée')),
                ('last_applied_at', models.DateTimeField(blank=True, null=True, verbose_name='Dernière application')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('assign_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finances.transactioncategory', verbose_name='Catégorie à assigner')),
                ('assign_practitioner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='competitions.practitioner', verbose_name='Pratiquant à assigner')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_reconciliation_rules', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
            ],
            options={
                'verbose_name': 'Règle de réconciliation',
                'verbose_name_plural': 'Règles de réconciliation',
                'ordering': ['-priority', 'name'],
            },
        ),
        migrations.AddIndex(
            model_name='bankimportbatch',
            index=models.Index(fields=['status'], name='finances_ba_status_20f99c_idx'),
        ),
        migrations.AddIndex(
            model_name='bankimportbatch',
            index=models.Index(fields=['import_date'], name='finances_ba_import__b73dd0_idx'),
        ),
        migrations.AddIndex(
            model_name='banktransaction',
            index=models.Index(fields=['reconciliation_status'], name='finances_ba_reconci_b6506d_idx'),
        ),
        migrations.AddIndex(
            model_name='banktransaction',
            index=models.Index(fields=['transaction_date'], name='finances_ba_transac_71e4b9_idx'),
        ),
        migrations.AddIndex(
            model_name='banktransaction',
            index=models.Index(fields=['transaction_type'], name='finances_ba_transac_3a6cf0_idx'),
        ),
        migrations.AddIndex(
            model_name='banktransaction',
            index=models.Index(fields=['counterparty_name'], name='finances_ba_counter_3b2a85_idx'),
        ),
        migrations.AddIndex(
            model_name='banktransaction',
            index=models.Index(fields=['external_reference'], name='finances_ba_externa_9be3be_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='banktransaction',
            unique_together={('import_batch', 'external_reference', 'transaction_date', 'amount')},
        ),
        migrations.AddIndex(
            model_name='practitionerbankinfo',
            index=models.Index(fields=['iban'], name='finances_pr_iban_f2e29f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='practitionerbankinfo',
            unique_together={('practitioner', 'iban')},
        ),
        migrations.AddIndex(
            model_name='reconciliationrule',
            index=models.Index(fields=['is_active'], name='finances_re_is_acti_2aeb20_idx'),
        ),
        migrations.AddIndex(
            model_name='reconciliationrule',
            index=models.Index(fields=['priority'], name='finances_re_priorit_f4ceca_idx'),
        ),
    ]
