# Generated by Django 5.1.6 on 2026-01-05 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0003_add_bank_import_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionpayment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'En attente'), ('COMPLETED', 'Complété'), ('FAILED', 'Échoué'), ('REFUNDED', 'Remboursé')], default='PENDING', max_length=20),
        ),
    ]
