# Generated by Django 5.1.6 on 2025-09-07 20:33

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('competitions', '0008_alter_userprofile_organization'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipPackage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Nom du package')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('package_type', models.CharField(choices=[('monthly', 'Mensuel'), ('quarterly', 'Trimestriel'), ('semi_annual', 'Semestriel'), ('annual', 'Annuel'), ('custom', 'Personnalisé')], default='monthly', max_length=20, verbose_name='Type de package')),
                ('category', models.CharField(choices=[('student', 'Élève'), ('competitor', 'Compétiteur'), ('recreational', 'Loisir'), ('professional', 'Professionnel'), ('family', 'Famille'), ('senior', 'Senior'), ('youth', 'Jeune')], default='student', max_length=20, verbose_name='Catégorie')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Prix de base')),
                ('currency', models.CharField(default='EUR', max_length=3, verbose_name='Devise')),
                ('max_sessions_per_week', models.PositiveIntegerField(blank=True, help_text='0 = illimité', null=True, verbose_name='Sessions max/semaine')),
                ('includes_competitions', models.BooleanField(default=False, verbose_name='Inclut les compétitions')),
                ('includes_seminars', models.BooleanField(default=False, verbose_name='Inclut les stages')),
                ('includes_equipment', models.BooleanField(default=False, verbose_name="Inclut l'équipement")),
                ('auto_renewal', models.BooleanField(default=True, verbose_name='Renouvellement automatique')),
                ('grace_period_days', models.PositiveIntegerField(default=7, verbose_name='Période de grâce (jours)')),
                ('min_age', models.PositiveIntegerField(blank=True, null=True, verbose_name='Âge minimum')),
                ('max_age', models.PositiveIntegerField(blank=True, null=True, verbose_name='Âge maximum')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Mis en avant')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('disciplines', models.ManyToManyField(blank=True, help_text='Disciplines accessibles avec ce package', to='competitions.discipline', verbose_name='Disciplines incluses')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_packages', to='organizations.organization', verbose_name='Organisation')),
            ],
            options={
                'verbose_name': "Package d'adhésion",
                'verbose_name_plural': "Packages d'adhésion",
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MembershipSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateField(verbose_name='Date de début')),
                ('end_date', models.DateField(verbose_name='Date de fin')),
                ('renewal_date', models.DateField(blank=True, null=True, verbose_name='Prochaine date de renouvellement')),
                ('status', models.CharField(choices=[('active', 'Actif'), ('expired', 'Expiré'), ('suspended', 'Suspendu'), ('cancelled', 'Annulé'), ('pending', 'En attente')], default='pending', max_length=20, verbose_name='Statut')),
                ('auto_renew', models.BooleanField(default=True, verbose_name='Renouvellement automatique')),
                ('price_paid', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix payé')),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('custom_disciplines', models.ManyToManyField(blank=True, help_text='Remplace les disciplines du package si définies', to='competitions.discipline', verbose_name='Disciplines personnalisées')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='membership.membershippackage', verbose_name='Package')),
                ('practitioner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_subscriptions', to='competitions.practitioner', verbose_name='Pratiquant')),
            ],
            options={
                'verbose_name': "Souscription d'adhésion",
                'verbose_name_plural': "Souscriptions d'adhésion",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MembershipAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alert_type', models.CharField(choices=[('expiry_warning', "Alerte d'expiration"), ('renewal_reminder', 'Rappel de renouvellement'), ('payment_due', 'Paiement dû'), ('package_upgrade', "Suggestion d'upgrade"), ('attendance_low', 'Assiduité faible')], max_length=30, verbose_name="Type d'alerte")),
                ('priority', models.CharField(choices=[('low', 'Faible'), ('medium', 'Moyenne'), ('high', 'Élevée'), ('urgent', 'Urgente')], default='medium', max_length=20, verbose_name='Priorité')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('message', models.TextField(verbose_name='Message')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='Résolu')),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('notification_sent', models.BooleanField(default=False, verbose_name='Notification envoyée')),
                ('notification_sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Résolu par')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='membership.membershipsubscription', verbose_name='Souscription')),
            ],
            options={
                'verbose_name': "Alerte d'adhésion",
                'verbose_name_plural': "Alertes d'adhésion",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MembershipWorkflow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Nom du workflow')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('trigger_type', models.CharField(choices=[('new_subscription', 'Nouvelle souscription'), ('renewal_due', 'Renouvellement dû'), ('expiry_warning', "Alerte d'expiration"), ('payment_failed', 'Échec de paiement'), ('cancellation', 'Annulation')], max_length=30, verbose_name='Type de déclencheur')),
                ('trigger_days_before', models.IntegerField(default=0, help_text="Pour les rappels d'expiration", verbose_name='Jours avant le déclencheur')),
                ('action_type', models.CharField(choices=[('send_email', 'Envoyer un email'), ('send_sms', 'Envoyer un SMS'), ('create_notification', 'Créer une notification'), ('suspend_membership', "Suspendre l'adhésion"), ('auto_renew', 'Renouveler automatiquement'), ('create_task', 'Créer une tâche')], max_length=30, verbose_name="Type d'action")),
                ('action_content', models.JSONField(default=dict, help_text="Configuration spécifique à l'action", verbose_name="Contenu de l'action")),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicable_packages', models.ManyToManyField(blank=True, to='membership.membershippackage', verbose_name='Packages applicables')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_workflows', to='organizations.organization', verbose_name='Organisation')),
            ],
            options={
                'verbose_name': "Workflow d'adhésion",
                'verbose_name_plural': "Workflows d'adhésion",
                'ordering': ['trigger_type', 'trigger_days_before'],
            },
        ),
        migrations.CreateModel(
            name='OnlineMembershipForm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Nom du formulaire')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('form_type', models.CharField(choices=[('registration', 'Inscription'), ('renewal', 'Renouvellement'), ('upgrade', 'Changement de package')], default='registration', max_length=20, verbose_name='Type de formulaire')),
                ('title', models.CharField(max_length=300, verbose_name='Titre')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('welcome_message', models.TextField(blank=True, verbose_name='Message de bienvenue')),
                ('success_message', models.TextField(blank=True, verbose_name='Message de succès')),
                ('require_medical_certificate', models.BooleanField(default=True, verbose_name='Certificat médical requis')),
                ('collect_emergency_contact', models.BooleanField(default=True, verbose_name="Contact d'urgence")),
                ('collect_experience_level', models.BooleanField(default=True, verbose_name="Niveau d'expérience")),
                ('allow_payment_plans', models.BooleanField(default=False, verbose_name='Échelonnement de paiement')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('is_public', models.BooleanField(default=True, verbose_name='Public')),
                ('max_submissions_per_day', models.PositiveIntegerField(blank=True, null=True, verbose_name='Soumissions max/jour')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('available_packages', models.ManyToManyField(to='membership.membershippackage', verbose_name='Packages disponibles')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_forms', to='organizations.organization', verbose_name='Organisation')),
            ],
            options={
                'verbose_name': "Formulaire d'adhésion en ligne",
                'verbose_name_plural': "Formulaires d'adhésion en ligne",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MembershipFormSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('first_name', models.CharField(max_length=100, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nom')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('date_of_birth', models.DateField(verbose_name='Date de naissance')),
                ('emergency_contact_name', models.CharField(blank=True, max_length=200, verbose_name="Nom du contact d'urgence")),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=20, verbose_name="Téléphone d'urgence")),
                ('form_data', models.JSONField(default=dict, verbose_name='Données du formulaire')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('processing', 'En traitement'), ('approved', 'Approuvé'), ('rejected', 'Rejeté'), ('completed', 'Complété')], default='pending', max_length=20, verbose_name='Statut')),
                ('processing_notes', models.TextField(blank=True, verbose_name='Notes de traitement')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Traité par')),
                ('selected_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membership.membershippackage', verbose_name='Package sélectionné')),
                ('created_subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='membership.membershipsubscription', verbose_name='Souscription créée')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='membership.onlinemembershipform', verbose_name='Formulaire')),
            ],
            options={
                'verbose_name': "Soumission de formulaire d'adhésion",
                'verbose_name_plural': "Soumissions de formulaires d'adhésion",
                'ordering': ['-created_at'],
            },
        ),
    ]
