# Generated by Django 5.1.6 on 2026-01-05 19:56

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('competitions', '0028_initial'),
        ('organizations', '0011_add_organization_video_links'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(choices=[('web', 'Serveur Web'), ('database', 'Base de données'), ('redis', 'Redis'), ('celery', 'Celery Worker'), ('celery_beat', 'Celery Beat'), ('nginx', 'Nginx')], max_length=20, unique=True, verbose_name='Nom du service')),
                ('status', models.CharField(choices=[('ok', 'OK'), ('warning', 'Avertissement'), ('error', 'Erreur'), ('unknown', 'Inconnu')], default='unknown', max_length=20, verbose_name='Statut')),
                ('response_time_ms', models.IntegerField(blank=True, null=True, verbose_name='Temps de réponse (ms)')),
                ('pid', models.IntegerField(blank=True, null=True, verbose_name='PID')),
                ('cpu_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='CPU (%)')),
                ('memory_mb', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Mémoire (MB)')),
                ('last_check', models.DateTimeField(auto_now=True, verbose_name='Dernière vérification')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name="Message d'erreur")),
            ],
            options={
                'verbose_name': 'Statut de service',
                'verbose_name_plural': 'Statuts des services',
            },
        ),
        migrations.CreateModel(
            name='MembershipProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('profile_type', models.CharField(choices=[('subscription', 'Abonnement'), ('event', 'Événement'), ('hybrid', 'Hybride')], default='subscription', max_length=20, verbose_name='Type de profil')),
                ('validity_type', models.CharField(choices=[('duration', 'Durée fixe'), ('event_bound', 'Lié à un événement')], default='duration', max_length=20, verbose_name='Type de validité')),
                ('validity_duration', models.IntegerField(blank=True, help_text='Nombre de jours de validité. Null si lié à un événement.', null=True, verbose_name='Durée de validité (jours)')),
                ('is_global', models.BooleanField(default=False, help_text='Profil créé par le super admin, applicable à tous.', verbose_name='Profil global')),
                ('feature_overrides', models.JSONField(blank=True, default=dict, help_text='Format: {"feature_code": true/false}', verbose_name='Surcharges de features')),
                ('pricing_model', models.CharField(choices=[('per_member', 'Par membre'), ('flat', 'Forfait'), ('free', 'Gratuit')], default='per_member', max_length=20, verbose_name='Modèle de tarification')),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Prix')),
                ('currency', models.CharField(default='EUR', max_length=3, verbose_name='Devise')),
                ('max_participants', models.IntegerField(default=0, help_text='0 = illimité', verbose_name='Nombre max de participants')),
                ('requires_approval', models.BooleanField(default=False, verbose_name='Approbation requise')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('allowed_disciplines', models.ManyToManyField(blank=True, related_name='membership_profiles', to='competitions.discipline', verbose_name='Disciplines autorisées')),
                ('created_by_organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_membership_profiles', to='organizations.organization', verbose_name='Organisation créatrice')),
                ('linked_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='membership_profiles', to='competitions.competition', verbose_name='Événement lié')),
            ],
            options={
                'verbose_name': 'Profil de membership',
                'verbose_name_plural': 'Profils de membership',
                'ordering': ['-is_global', 'name'],
            },
        ),
        migrations.CreateModel(
            name='EventPass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvé'), ('active', 'Actif'), ('expired', 'Expiré'), ('cancelled', 'Annulé')], default='pending', max_length=20, verbose_name='Statut')),
                ('payment_status', models.CharField(choices=[('pending', 'En attente'), ('paid', 'Payé'), ('free', 'Gratuit'), ('refunded', 'Remboursé')], default='pending', max_length=20, verbose_name='Statut du paiement')),
                ('payment_reference', models.CharField(blank=True, max_length=100, null=True, verbose_name='Référence de paiement')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Approuvé le')),
                ('expires_at', models.DateTimeField(verbose_name='Expire le')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_event_passes', to=settings.AUTH_USER_MODEL, verbose_name='Approuvé par')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_passes', to='competitions.competition', verbose_name='Compétition')),
                ('organization', models.ForeignKey(blank=True, help_text='Club invité (si applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_passes', to='organizations.organization', verbose_name='Organisation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_passes', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
                ('membership_profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='event_passes', to='superadmin.membershipprofile', verbose_name='Profil de membership')),
            ],
            options={
                'verbose_name': "Passe d'événement",
                'verbose_name_plural': "Passes d'événement",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MembershipTransformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transformation_type', models.CharField(choices=[('upgrade', 'Mise à niveau'), ('downgrade', 'Rétrogradation'), ('conversion', 'Conversion'), ('new', 'Nouveau')], default='new', max_length=20, verbose_name='Type de transformation')),
                ('discount_applied', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Réduction appliquée')),
                ('discount_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Code de réduction')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('from_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transformations_from', to='superadmin.membershipprofile', verbose_name='Profil source')),
                ('source_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='membership_transformations', to='competitions.competition', verbose_name='Événement source')),
                ('to_profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transformations_to', to='superadmin.membershipprofile', verbose_name='Profil cible')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_transformations', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Transformation de membership',
                'verbose_name_plural': 'Transformations de membership',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlatformAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('disk_space', 'Espace disque'), ('db_connections', 'Connexions DB'), ('memory', 'Mémoire'), ('service_down', 'Service hors ligne'), ('high_error_rate', "Taux d'erreur élevé"), ('security', 'Sécurité'), ('performance', 'Performance')], max_length=30, verbose_name="Type d'alerte")),
                ('severity', models.CharField(choices=[('info', 'Information'), ('warning', 'Avertissement'), ('critical', 'Critique')], default='warning', max_length=20, verbose_name='Sévérité')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('message', models.TextField(verbose_name='Message')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='Résolu')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Résolu le')),
                ('auto_resolved', models.BooleanField(default=False, verbose_name='Résolution automatique')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_alerts', to=settings.AUTH_USER_MODEL, verbose_name='Résolu par')),
            ],
            options={
                'verbose_name': 'Alerte plateforme',
                'verbose_name_plural': 'Alertes plateforme',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_type', models.CharField(choices=[('db_size', 'Taille base de données'), ('db_connections', 'Connexions DB'), ('storage_total', 'Stockage total'), ('storage_used', 'Stockage utilisé'), ('cpu_usage', 'Utilisation CPU'), ('memory_usage', 'Utilisation mémoire'), ('active_users', 'Utilisateurs actifs'), ('requests_per_minute', 'Requêtes par minute')], max_length=30, verbose_name='Type de métrique')),
                ('value', models.DecimalField(decimal_places=4, max_digits=20, verbose_name='Valeur')),
                ('unit', models.CharField(help_text="Ex: 'GB', '%', 'count', 'req/min'", max_length=20, verbose_name='Unité')),
                ('recorded_at', models.DateTimeField(auto_now_add=True, verbose_name='Enregistré le')),
                ('metadata', models.JSONField(blank=True, help_text='Détails supplémentaires', null=True, verbose_name='Métadonnées')),
            ],
            options={
                'verbose_name': 'Métrique système',
                'verbose_name_plural': 'Métriques système',
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['metric_type', 'recorded_at'], name='superadmin__metric__da54ad_idx')],
            },
        ),
        migrations.CreateModel(
            name='AdminAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('restart_service', 'Redémarrage service'), ('maintenance_mode', 'Mode maintenance'), ('emergency_stop', "Arrêt d'urgence"), ('config_change', 'Modification configuration'), ('profile_create', 'Création de profil'), ('profile_modify', 'Modification de profil'), ('profile_delete', 'Suppression de profil'), ('user_action', 'Action utilisateur'), ('backup_trigger', 'Déclenchement backup'), ('cache_clear', 'Vidage cache')], max_length=30, verbose_name="Type d'action")),
                ('target_service', models.CharField(blank=True, max_length=50, null=True, verbose_name='Service cible')),
                ('target_object_type', models.CharField(blank=True, max_length=100, null=True, verbose_name="Type d'objet cible")),
                ('target_object_id', models.IntegerField(blank=True, null=True, verbose_name="ID de l'objet cible")),
                ('description', models.TextField(verbose_name='Description')),
                ('ip_address', models.GenericIPAddressField(verbose_name='Adresse IP')),
                ('user_agent', models.TextField(verbose_name='User Agent')),
                ('status', models.CharField(choices=[('initiated', 'Initié'), ('in_progress', 'En cours'), ('completed', 'Terminé'), ('failed', 'Échoué')], default='initiated', max_length=20, verbose_name='Statut')),
                ('result_message', models.TextField(blank=True, null=True, verbose_name='Message de résultat')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Terminé le')),
                ('admin_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_actions', to=settings.AUTH_USER_MODEL, verbose_name='Administrateur')),
            ],
            options={
                'verbose_name': "Action d'administration",
                'verbose_name_plural': "Actions d'administration",
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['action_type', 'created_at'], name='superadmin__action__fb886c_idx'), models.Index(fields=['admin_user', 'created_at'], name='superadmin__admin_u_313c7b_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='membershipprofile',
            index=models.Index(fields=['profile_type', 'is_active'], name='superadmin__profile_aebbf0_idx'),
        ),
        migrations.AddIndex(
            model_name='membershipprofile',
            index=models.Index(fields=['is_global', 'is_active'], name='superadmin__is_glob_27df56_idx'),
        ),
        migrations.AddIndex(
            model_name='membershipprofile',
            index=models.Index(fields=['slug'], name='superadmin__slug_06a5a6_idx'),
        ),
        migrations.AddIndex(
            model_name='eventpass',
            index=models.Index(fields=['user', 'competition'], name='superadmin__user_id_c37106_idx'),
        ),
        migrations.AddIndex(
            model_name='eventpass',
            index=models.Index(fields=['status', 'expires_at'], name='superadmin__status_03194c_idx'),
        ),
        migrations.AddIndex(
            model_name='eventpass',
            index=models.Index(fields=['competition', 'status'], name='superadmin__competi_8e7ba1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='eventpass',
            unique_together={('user', 'competition', 'membership_profile')},
        ),
        migrations.AddIndex(
            model_name='membershiptransformation',
            index=models.Index(fields=['transformation_type', 'created_at'], name='superadmin__transfo_788c46_idx'),
        ),
        migrations.AddIndex(
            model_name='membershiptransformation',
            index=models.Index(fields=['user', 'created_at'], name='superadmin__user_id_8058d2_idx'),
        ),
        migrations.AddIndex(
            model_name='platformalert',
            index=models.Index(fields=['alert_type', 'is_resolved', 'created_at'], name='superadmin__alert_t_9d8828_idx'),
        ),
        migrations.AddIndex(
            model_name='platformalert',
            index=models.Index(fields=['severity', 'is_resolved'], name='superadmin__severit_1c7993_idx'),
        ),
    ]
