BBBB BBBB
XXXXXXXXX XXXXX
XXXXX XXXXXXXXXX
XXXXXX
    XXXXX XXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
    XXXXXXX gettext(u'Connexion - MartialComp') XXXXXXXX
    XXXXXXX
        XXXXX X
            XXXXXXXXXX XXXXXXXX
            XXXXXXXXX XXXXXXXX
            XXXXXXX XXXXXXXX
            XXXXXXXX XXXXXXXX
        X
        X X XXXXXXX XX XXXXXXXX XX XXXXXXXXXXX XXXXXXXXXXX X
        XXXX X
            XXXXXXXXXXXX XXXXXXXX XXXXXXXXXXX
            XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX
            XXXXXXXXXXX XXXXXX
            XXXXXXXX XXXXX
            XXXXXXXXXXXX XXXXXXX
            XXXXXXXXXXXXXXXX XXXXXXX
            XXXXXX XXXXXXXXXXXXX
        X
        XXXXXXXXXX X
            XXXXXXXXXXX XXXXXXXXX XXXX XXXX XXXXX
            XXXXXXXX XXXXX
            XXXXXXXXXXXXXX XXXXX
            XXXXXXXXXXXXXXXX XXXXXXXXXXX
            XXXXXX XXXXX
            XXXXXXXXXX XXXXXX
            XXXXXXXXXXX X XXX XXXX XXXXXXX XX XX XXXXX
        X
        XXXXX X
            XXXXXXXXXXX XXXXXXX
            XXXXXXXXXXXXXX XXXXX
        X
        XXXXX XX X
            XXXXXX XXXXXXXXXXXXXX
            XXXXXXXXXX XXXXX
            XXXXXXX XX
        X
        XXXXXXXX X
            XXXXXXXXXXX XXXXXXXX XXXX XXX XXXXX
            XXXXXX XXXXXXXX
            XXXXXXXX XXXXX
            XXXXXXXXXXXXXX XXXX
            XXXXXXXXXXXXXX XXXXX
            XXXXXXXXXXX XXXXXXX
            XXXXXXX XXX XXXXX XXXXXXXX XXXX XXX XXXXX
        X
        XXXXXXXXXXX X
            XXXXXXXXXXXXXX XXXXX
        X
        XXXXXXXXXXX XXXXX X
            XXXXXXXX XXXXXX
            XXXXXXXXXXXXXX XXXXXXX
            XXXXXX XXXXXXXXXXXXX
        X
        XXXXXXXXXXX XXXXX X
            XXXXXX XXXXX
            XXXXXXXX XXXXXXX
            XXXXXXX XXX XXXXX XXXXXXXXX XXXX XXXX XXXXX
            XXXXXXXXXXXXXX XXXX
            XXXXXXXXXXX XXXXXXXXX XXXX XXXX XXXXX
            XXXXXX XXXXXXXXXXXXX
            XXXXXXXXXXX XXXXXXXXXXX
        X
        XXXX X
            XXXXXX XXXXX
            XXXXXXXX XXXXX
            XXXXXXX XXXXX
            XXXXXXXXXXXXXX XXXX
            XXXXXXXXXXXX XXXX
            XXXXXXX XXXXXXXX
            XXXXXXXXXXXXXX XXXXX
            XXXXXXXXXXXXXXXX XXXXX
            XXXXXXXX XXXXXXXXXXXXX
            XXXXXXXXXXX XXXXXXX
            XXXXXXXXXXX XXXXXXXXXXX
        X
        XXXXXXXXXXXX X XXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXX XXXXX X
        XXXXXXXXXXX X XXXXXXXXXXX XXXXXXXX XXXXXX XXXXX X
        XXXXXXXXXXXXX X XXXXXXXXXXX XXXXXXXX XXXXXX XXXXX X
        XXXXXXXX X
            XXXXXXXXXXX XXXXXXX
            XXXXXXX XXXX XX
            XXXXXX XXXXX
        X
        XXXXXX X
            XXXXXXXXXXX XXXXXXX
            XXXXXXXXXXX XXXXX
        X
        XXXXXX X X
            XXXXXX XXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXX XXXXX
            XXXXXXX X XXXXXXX
        X
    XXXXXXXX
XXXXXXX
XXXXXX
    XXXX XXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXX
            XXX gettext(u'Connexion à votre compte') XXXX
        XXXXXX
        
        XXXX XXXXXXXXXXXXXXXX gettext(u'Authentification moderne entièrement opérationnelle !') XXXXXX
        
        XXXXX XXXXXXXXXXXXXX
            BBBBBBBBBB
            
            XXXX XXXXXXXXXXXXXXXXXXX
                XXXXXX XXXXXXXXXXXXXXX gettext(u"Email ou nom d'utilisateur") XXXXXXXX
                XXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXX
            XXXXXX
            
            XXXX XXXXXXXXXXXXXXXXXXX
                XXXXXX XXXXXXXXXXXXXXXXXX gettext(u'Mot de passe') XXXXXXXX
                XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXX
            XXXXXX
            
            XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX gettext(u'Se connecter') XXXXXXXXX
        XXXXXXX
        
        XXXX XXXXXXXXXXXXXXXX gettext(u'Ou connectez-vous avec') XXXXXX
        
        XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX gettext(u'Continuer avec Google') XXXX
        
        XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXX gettext(u'Continuer avec Facebook') XXXX
        
        XXXX XXXXXXXXXXXXXX
            XX XXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Créer un compte') XXXX
            XX XXXXXXXXX gettext(u"← Retour à l'accueil") XXXX
        XXXXXX
    XXXXXX
XXXXXXX
XXXXXXX