BBBBBBB BBBBBBBBBBB
BBBB BBBB
BBBB BBBBBBBBBBBBBB

BBBBB BBBBB gettext(u'Déconnexion')  X XXXXXXXXXXXBBBBBBBB

BBBBB BBBBBBBBB
XXXXXXX
    XXXXX X
        XXXXXXXXXX XXXXXXXX
        XXXXXXXXX XXXXXXXX
        XXXXXXX XXXXXXXX
        XXXXXXXX XXXXXXXX
    X
    
    XXXXXXXXXXXXXXXXX X
        XXXXXXXXXXX XXXXX
        XXXXXXXX XXXXX
        XXXXXXXXXXXX XXXXXXX
        XXXXXXXXXXXXXXXX XXXXXXX
        XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXX XXX XXXXX XXXXXXXXX XXXX XXX XXXXXX
    X
    
    XXXXXXXXXXXX X
        XXXXXXXXXXX XXXXXX
        XXXXXXXXXXXXXX XXXXX
        XXXXXXXXXXX X XXXX XXXX XXXXXXX XX XX XXXXX
        XXXXXXXX XXXXXXX
        XXXXXX XXXXX
        XXXXXXXXXX XXXXXX
        XXXXXXX XXX XXXXX XXXXXXXXX XXX XXX XXXXX
        XXXXXXXXXXX XXXXXXX
    X
    
    XXXXXXXXXXXXXX X
        XXXXXXXXXXXXXX XXXXX
    X
    
    XXXXXXXXXXXXXX XX X
        XXXXXX XXXXXXXXXXXXXXX
        XXXXXXXXXX XXXXXXX
        XXXXXXXXXXXX XXXX
        XXXXXXXXXXXXXX XXXXXXX
    X
    
    XXXXXXXXXXXXXX X X
        XXXXXX XXXXXXXX
        XXXXXXXXXX XXXXXXX
    X
    
    XXXXXXXXXX X
        XXXXXXXXXXXXXX XXXXXXX
        XXXXXXXXXX XXXXXXX
        XXXXXX XXXXXXXXXXXXXXX
    X
    
    XXXXXXXXX X
        XXXXXX XXXXX
        XXXXXXXX XXXXXXXXX
        XXXXXXX XXXXX
        XXXXXXXXXXXXXX XXXX
        XXXXXXXXXXXX XXXX
        XXXXXXXXXX XXXXX
        XXXXXXX XXXXXXXX
        XXXXXXXXXXX XXX XXXX XXXXX
        XXXXXXXXXXXXXX XXXXX
        XXXXXXXXXXXXXXXX XXXXX
        XXXXXXXX XXXXXXXXXXXXX
        XXXXXXXXXXX XXXXXXX
    X
    
    XXXXXXXXXXXXXXXXX X
        XXXXXXXXXXX XXXXXXXXXXXXXXX
        XXXXXX XXXXXX
    X
    
    XXXXXXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXX XXXXXXXX
        XXXXXXXXXX XXXXXXXXXXXXXXXXX
        XXXXXXXXXXX X XXX XXXX XXXXXXXXX XXX XXX XXXXX
    X
    
    XXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXX XXXXXXXX
        XXXXXX XXXXXXXX
        XXXXXXX XXX XXXXX XXXXXXXX
    X
    
    XXXXXXXXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXX XXXXXXXX
        XXXXXXXXXX XXXXXXXXXXXXXXXXX
        XXXXXXXXXXX X XXX XXXX XXXXXXX XX XX XXXXX
    X
    
    XXXXXXXXXXX X
        XXXXXXXXXXX XXXXXXX
        XXXXXXXXXXX XXXXX
        XXXXXXXXXXXX XXXXX
        XXXXXXXXXXX XXX XXXXX XXXXXXXX
    X
    
    XXXXXXXXXXX X X
        XXXXXX XXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXX XXXXX
        XXXXXXXXXXXX XXXX
        XXXXXXX X XXXXX
    X
    
    XXXXXXXXXXX XXXXXXX X
        XXXXXX XXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXX XXXXXXXXXX
    X
    
    XXXXXXXXX X
        XXXXXXXXXXXXXXXXX XXXXXXXXX XXX XXX XXXXXX
        XXXXXXXXXXXXXX XXXX
        XXXXXXXX XXXXXXX
        XXXXXXXXXXXXXX XXXXX
        XXXXXXXXXXXX XXX XXXXX XXXXXXXXXXXXXXX
    X
    
    XXXXXXXXX X X
        XXXXXXX XX
        XXXXXX XXXXXXXX
    X
XXXXXXXX
BBBBBBBB

BBBBB BBBBBBB
XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXX
            XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
        XXXXXX
        
        XXXX XXXXXXXXXXXXXXXXXXXXXX
            XXXX gettext(u'Déconnexion') XXXXX
            XXX gettext(u'Confirmer la déconnexion de votre compte') XXXX
        XXXXXX
        
        XXXX XXXXXXXXXXXXXXXXX
            XXX gettext(u'Êtes-vous sûr de vouloir vous déconnecter de MartialComp ?') XXXX
        XXXXXX
        
        BB BBBBBBBB
        XXXX XXXXXXXXXXXXXXX XXXXXX
            BBB BBBBBBB BB BBBBBBBB
            XXXX XXXXXXXXXXXX BB BBBBBBBBBBBBXXXXXXBBBBXXXXXXXXXXBBBBBXX
                
            XXXXXX
            BBBBBB
        XXXXXX
        BBBBB
        
        XXXXX XXXXXXXXXXXXX XXXXXXXXBBB BBBBBBBBBBBBBBBBXX
            BBBBBBBBBB
            
            BB BBBBBBBBBBBBBBBBBBBB
            XXXXXX XXXXXXXXXXXXX XXXXXXX XXXXXXXXXX
            BBBBB
            
            XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
                XX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXX
                 gettext(u'Confirmer la déconnexion') 
            XXXXXXXXX
            
            XX XXXXXXBBB BBBBBBBBBX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                XX XXXXXXXXXX XXXXXXXX XXXXXXXXXX
                 gettext(u'Annuler') 
            XXXX
        XXXXXXX
        
        XXXX XXXXXXXXXXXXXXXXXXX
            XX XXXXXXBBB BBBBBBBBBBBBBBBXX
                XX XXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXX
                 gettext(u'Se connecter') 
            XXXX
            XX XXXXXXBBB BBBBBBBBBXX
                XX XXXXXXXXXX XXXXXXX XXXXXXXXXX
                 gettext(u'Accueil') 
            XXXX
        XXXXXX
    XXXXXX
XXXXXX
BBBBBBBB