BBBBBBB BBBBBBBBBBB
BBBB BBBB
BBBB BBBBBBB BBBBBBBBBBBBB
BBBB BBBBBBBBBBBBBB

BBBBB BBBBB gettext(u'Créer un compte')  X XXXXXXXXXXXBBBBBBBB

BBBBB BBBBBBBBB
XXXXXXX
    XXXXX X
        XXXXXXXXXX XXXXXXXX
        XXXXXXXXX XXXXXXXX
        XXXXXXX XXXXXXXX
        XXXXXXXX XXXXXXXX
    X
    
    XXXXXXXXXXXXXXX X
        XXXXXXXXXXX XXXXX
        XXXXXXXX XXXXX
        XXXXXXXXXXXX XXXXXXX
        XXXXXXXXXXXXXXXX XXXXXXX
        XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXX XXX XXXXX XXXXXXXXX XXXX XXX XXXXXX
    X
    
    XXXXXXXXXX X
        XXXXXXXXXXX XXXXXX
        XXXXXXXXXXXXXX XXXXX
        XXXXXXXXXXX X XXXX XXXX XXXXXXX XX XX XXXXX
        XXXXXXXX XXXXXXX
        XXXXXX XXXXX
        XXXXXXXXXX XXXXXX
        XXXXXXX XXX XXXXX XXXXXXXXX XXX XXX XXXXX
    X
    
    XXXXXXXXXXXX X
        XXXXXXXXXXX XXXXXXX
        XXXXXXXXXXXXXX XXXXX
    X
    
    XXXXXXXXXXXX XX X
        XXXXXX XXXXXXXXXXXXXXX
        XXXXXXXXXX XXXXXXX
        XXXXXXXXXXXX XXXX
        XXXXXXXXXXXXXX XXXXXXX
    X
    
    XXXXXXXXXXXX X X
        XXXXXX XXXXXXXX
        XXXXXXXXXX XXXXXXX
    X
    
    XXXXXXXXXXX X
        XXXXXXXXXXXXXX XXXXXXX
    X
    
    XXXXXXXXXXX XXXXX X
        XXXXXXXX XXXXXX
        XXXXXXXXXXXXXX XXXXXXX
        XXXXXX XXXXX
        XXXXXXXXXXXX XXXX
    X
    
    XXXXXXXXXXXXX X
        XXXXXX XXXXX
        XXXXXXXX XXXXXXXX XXXXX
        XXXXXXX XXX XXXXX XXXXXXXX
        XXXXXXXXXXXXXX XXXX
        XXXXXXXXXX XXXXX
        XXXXXXXXXXX XXXXXXXXXXXX XXXX XXXXX
    X
    
    XXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXXXX XXXXXXXXXXXXXXX
        XXXXXXXXXXX X X X XXXXXX XXXXXXXXX XXX XXX XXXXX
        XXXXXXXX XXXXX
    X
    
    XXXXXXXXX X
        XXXXXX XXXXX
        XXXXXXXX XXXXXXXXX
        XXXXXXX XXXXX
        XXXXXXXXXXXXXX XXXX
        XXXXXXXXXXXX XXXX
        XXXXXXXXXX XXXXX
        XXXXXXX XXXXXXXX
        XXXXXXXXXXX XXX XXXX XXXXX
        XXXXXXXXXXXXXX XXXXX
        XXXXXXXXXXXXXXXX XXXXX
        XXXXXXXX XXXXXXXXXXXXX
        XXXXXXXXXXX XXXXXXX
    X
    
    XXXXXXXXXXXXXXXXX X
        XXXXXXXXXXX XXXXXXXXXXXXXXX
        XXXXXX XXXXXX
    X
    
    XXXXXXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXX XXXXXXXX
        XXXXXXXXXX XXXXXXXXXXXXXXXXX
        XXXXXXXXXXX X XXX XXXX XXXXXXXXX XXX XXX XXXXX
    X
    
    XXXXXXXXXXXXXXX X
        XXXXXXXXXXX XXXXXXX
        XXXXXXX XXXX XX
        XXXXXXXXX XXXXXXXXX
        XXXXXX XXXXXXXX
    X
    
    XXXXXXXXXXXXXXXXXXXXXXX X
        XXXXXXXX XXX
        XXXXXXXXX XXXXXXXXX
        XXXX XXXX
        XXXXX XX
        XXXXXX XX
        XXXXXXX XXXX
        XXXXXXXXXXX XXXXXXXX
        XXXXXXXX XX
    X
    
    XXXXXXXXXXXXXXX XXXX X
        XXXXXXXXXXX XXXXXX
        XXXXXXXX X XXXXX
        XXXXXXXXX XXXXXXXXX
        XXXXXXXX XX
    X
    
    XXXXXXXXXXX X
        XXXXXXXXXXX XXXXXXXX
        XXXXXX XXXXXX
    X
    
    XXXXXXXXXXXXXXXXX X
        XXXXXXXXXXX XXXXXXXX
        XXXXXX XXXXXX
    X
    
    XXXXXXXXXXXXX X
        XXXXXXXXXXX XXXXXXXX
        XXXXXX XXXXXX
    X
    
    XXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXX XXXXXXXX
        XXXXXX XXXXXX
    X
    
    XXXXXXXXXXX X
        XXXXXXXXXXX XXXXXXX
        XXXXXXXXXXX XXXXX
        XXXXXXXXXXXX XXXXX
        XXXXXXXXXXX XXX XXXXX XXXXXXXX
    X
    
    XXXXXXXXXXX X X
        XXXXXX XXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXX XXXXX
        XXXXXXXXXXXX XXXX
        XXXXXXX X XXXXX
    X
    
    XXXXXXXXXXX XXXXXXX X
        XXXXXX XXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXX XXXXXXXXXX
    X
    
    XXXXXXXXXX X
        XXXXXXXXXXX XXXXXXXXX XXX XXX XXXXX
        XXXXXXX XXX XXXXX XXXXXXXXX XXX XXX XXXXX
        XXXXXXXXXXXXXX XXXX
        XXXXXXXX XXXXXXXX
        XXXXXXXXXXXXXX XXXXX
        XXXXXXXXXXX XXXXX
    X
    
    XXXXXXXXXX XX X
        XXXXXX XXXXXXXX
        XXXXXXX XX
    X
    
    XXXXXXXXXXXX X
        XXXXXX XXXXXXXX
        XXXXXXXXXXX XXXXXXX
        XXXXXXXXXX XXXXXXX
        XXXXXXXX XXXXXX
    X
    
    XXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXXXX XXXXXXXX
    X
    
    XXXXXX X
        XXXXXXXX XXXXX
        XXXXXXXXXXXXXX XXXXXXX
        XXXXXXXXXXXXXX XXXX
    X
    
    XXXXXXXXXXXXX X
        XXXXXXXXXXXXXXXXX XXXXXXXXX XXX XXX XXXXX
        XXXXXXX XXX XXXXX XXXXXXXXX XXX XXX XXXXX
        XXXXXX XXXXXXXX
    X
    
    XXXXXXXXXXXXXX X
        XXXXXXXXXXXXXXXXX XXXXXXXX XXXX XXX XXXXX
        XXXXXXX XXX XXXXX XXXXXXXX XXXX XXX XXXXX
        XXXXXX XXXXXXXX
    X
XXXXXXXX
BBBBBBBB

BBBBB BBBBBBB
XXXX XXXXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXX
            XXXX gettext(u'MartialComp') XXXXX
            XXX gettext(u'Créer votre compte') XXXX
        XXXXXX
        
        BB BBBBBBBB
        XXXX XXXXXXXXXXXXXXXXX
            BBB BBBBBBB BB BBBBBBBB
            XXXX XXXXXXXXXXXX BB BBBBBBBBBBBBXXXXXXBBBBXXXXXXXXXXBBBBBXX
                
            XXXXXX
            BBBBBB
        XXXXXX
        BBBBB
        
        BB BBBBBBBBBBBBBBBBBBBBB
        XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX
            BBB BBBBB BB BBBBBBBBBBBBBBBBBBBBB
                
            BBBBBB
        XXXXXX
        BBBBB
        
        XXXXX XXXXXXXXXXXXX XXXXXXXXBBB BBBBBBBBBBBBBBBBXX
            BBBBBBBBBB
            
            XXXX XXXXXXXXXXXXXXXXXXX
                XXXXXX XXXXXXX gettext(u"Nom d'utilisateur") XXXXXXXX
                FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
                BB BBBBBBBBBBBBBBBBBBBB
                    XXXXX XXXXXXXXXXXXXXXXXXXX
                        BBB BBBBB BB BBBBBBBBBBBBBBBBBBBB
                            
                        BBBBBB
                    XXXXXXX
                BBBBB
                BB BBBBBBBBBBBBBBBBBBBBBBB
                    XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                BBBBB
            XXXXXX
            
            XXXX XXXXXXXXXXXXXXXXXXX
                XXXXXX XXXXXXX gettext(u'Adresse email') XXXXXXXX
                FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
                BB BBBBBBBBBBBBBBBBB
                    XXXXX XXXXXXXXXXXXXXXXXXXX
                        BBB BBBBB BB BBBBBBBBBBBBBBBBB
                            
                        BBBBBB
                    XXXXXXX
                BBBBB
            XXXXXX
            
            XXXX XXXXXXXXXXXXXXXXXXX
                XXXXXX XXXXXXX gettext(u'Mot de passe') XXXXXXXX
                FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
                BB BBBBBBBBBBBBBBBBBBBBB
                    XXXXX XXXXXXXXXXXXXXXXXXXX
                        BBB BBBBB BB BBBBBBBBBBBBBBBBBBBBB
                            
                        BBBBBB
                    XXXXXXX
                BBBBB
                BB BBBBBBBBBBBBBBBBBBBBBBBB
                    XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                BBBBB
            XXXXXX
            
            XXXX XXXXXXXXXXXXXXXXXXX
                XXXXXX XXXXXXX gettext(u'Confirmer le mot de passe') XXXXXXXX
                FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
                BB BBBBBBBBBBBBBBBBBBBBB
                    XXXXX XXXXXXXXXXXXXXXXXXXX
                        BBB BBBBB BB BBBBBBBBBBBBBBBBBBBBB
                            
                        BBBBBB
                    XXXXXXX
                BBBBB
            XXXXXX
            
            XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
                XX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXX
                 gettext(u'Créer mon compte') 
            XXXXXXXXX
            
            BB BBBBBBBBBBBBBBBBBBBB
                XXXXXX XXXXXXXXXXXXX XXXXXXX XXXXXXXX XX
            BBBBB
        XXXXXXX
        
        XXXX XXXXXXXXXXXXXXXXXXXXXXX
            XXXXXX gettext(u'Ou inscrivez-vous avec') XXXXXXX
        XXXXXX
        
        BBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBBBBB
        BBB BBBBBBBB BB BBBBBBBBBBBBBBBBBBBBBBB
            BB BBBBBBBBBBB BB BBBBBBBB
                XX XXXXXXBBBBBBBBBBBBBBBBBB BBBBBBBBX XXXXXXXXXXXXXXX XXXXXXXXXXXX
                    XX XXXXXXXXXX XXXXXXXXX XXXXXXXXXX
                     gettext(u"S'inscrire avec Google") 
                XXXX
            BBBB BBBBBBBBBBB BB BBBBBBBBBB
                XX XXXXXXBBBBBBBBBBBBBBBBBB BBBBBBBBBBX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX
                    XX XXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX
                     gettext(u"S'inscrire avec Facebook") 
                XXXX
            BBBBB
        BBBBBB
        
        XXXX XXXXXXXXXXXXXXXXXXX
            XX XXXXXXBBB BBBBBBBBBBBBBBBXX
                XX XXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXX
                 gettext(u"J'ai déjà un compte") 
            XXXX
            XX XXXXXXBBB BBBBBBBBBXX
                XX XXXXXXXXXX XXXXXXX XXXXXXXXXX
                 gettext(u"Retour à l'accueil") 
            XXXX
        XXXXXX
    XXXXXX
XXXXXX
BBBBBBBB