# Generated by Django 4.2.21 on 2025-07-31 11:13

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('competitions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('color', models.CharField(blank=True, max_length=50, verbose_name='Couleur')),
                ('color_code', models.CharField(blank=True, help_text='Code hexadécimal de la couleur (ex: #FFFFFF)', max_length=7, verbose_name='Code couleur')),
                ('level', models.PositiveSmallIntegerField(default=0, help_text='Ordre numérique du grade dans la hiérarchie', verbose_name='Niveau')),
                ('min_age', models.PositiveSmallIntegerField(default=0, help_text='Ã‚ge minimum requis pour ce grade', verbose_name='Ã‚ge minimum')),
                ('min_time_in_previous_grade', models.PositiveSmallIntegerField(default=0, help_text='Temps minimum requis dans le grade précédent (en mois)', verbose_name='Temps minimum dans le grade précédent (mois)')),
                ('requirements_text', models.TextField(blank=True, verbose_name='Exigences')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('is_dan_grade', models.BooleanField(default=False, help_text="S'agit-il d'un grade dan/dang (ceinture noire)", verbose_name='Grade dan/dang')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name="Ordre d'affichage")),
            ],
            options={
                'verbose_name': 'Grade',
                'verbose_name_plural': 'Grades',
                'ordering': ['discipline', 'level', 'name'],
            },
        ),
        migrations.CreateModel(
            name='GradeExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('date', models.DateField(verbose_name='Date')),
                ('location', models.CharField(max_length=200, verbose_name='Lieu')),
                ('max_participants', models.PositiveSmallIntegerField(default=50, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Nombre maximum de participants')),
                ('registration_deadline', models.DateField(verbose_name="Date limite d'inscription")),
                ('examiners', models.CharField(blank=True, max_length=200, verbose_name='Examinateurs')),
                ('fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Frais d'inscription")),
                ('status', models.CharField(choices=[('scheduled', 'Planifié'), ('in_progress', 'En cours'), ('completed', 'Terminé'), ('cancelled', 'Annulé')], default='scheduled', max_length=20, verbose_name='Statut')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis Ã\xa0 jour le')),
                ('available_grades', models.ManyToManyField(related_name='exams', to='grades.grade', verbose_name='Grades disponibles')),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_exams', to='competitions.discipline', verbose_name='Discipline')),
            ],
            options={
                'verbose_name': 'Examen de passage de grade',
                'verbose_name_plural': 'Examens de passage de grade',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='GradingSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grading_systems', to='competitions.discipline', verbose_name='Discipline')),
            ],
            options={
                'verbose_name': 'Système de graduation',
                'verbose_name_plural': 'Systèmes de graduation',
            },
        ),
        migrations.CreateModel(
            name='GradeRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_mandatory', models.BooleanField(default=True, verbose_name='Obligatoire')),
                ('min_age', models.PositiveSmallIntegerField(default=0, verbose_name='Ã‚ge minimum')),
                ('min_time_in_previous_grade', models.PositiveSmallIntegerField(default=0, verbose_name='Temps minimum dans le grade précédent (mois)')),
                ('required_points', models.PositiveSmallIntegerField(default=0, verbose_name='Points requis')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_requirements', to='grades.grade', verbose_name='Grade')),
            ],
            options={
                'verbose_name': 'Exigence de grade',
                'verbose_name_plural': 'Exigences de grade',
                'ordering': ['grade', 'order'],
            },
        ),
        migrations.CreateModel(
            name='GradeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_categories', to='competitions.discipline', verbose_name='Discipline')),
            ],
            options={
                'verbose_name': 'Catégorie de grade',
                'verbose_name_plural': 'Catégories de grade',
                'ordering': ['discipline', 'order', 'name'],
                'unique_together': {('name', 'discipline')},
            },
        ),
        migrations.CreateModel(
            name='GradeActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('add', 'Ajout'), ('update', 'Modification'), ('delete', 'Suppression'), ('set_current', 'Définition comme grade actuel'), ('revoke', 'Retrait')], max_length=20, verbose_name="Type d'action")),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Horodatage')),
                ('grade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_logs', to='grades.grade', verbose_name='Grade')),
                ('practitioner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_action_logs', to='competitions.practitioner', verbose_name='Pratiquant')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grade_actions', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': "Journal d'action sur grade",
                'verbose_name_plural': 'Journal des actions sur grades',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddField(
            model_name='grade',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='grades.gradecategory', verbose_name='Catégorie'),
        ),
        migrations.AddField(
            model_name='grade',
            name='discipline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='competitions.discipline', verbose_name='Discipline'),
        ),
        migrations.CreateModel(
            name='PractitionerGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_obtained', models.DateField(default=django.utils.timezone.now, verbose_name="Date d'obtention")),
                ('date_expiry', models.DateField(blank=True, null=True, verbose_name="Date d'expiration")),
                ('awarded_by', models.CharField(blank=True, max_length=100, verbose_name='Décerné par')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name="Lieu d'obtention")),
                ('certificate_number', models.CharField(blank=True, max_length=50, verbose_name='Numéro de certificat')),
                ('certificate_file', models.FileField(blank=True, null=True, upload_to='grades/certificates/', verbose_name='Certificat')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('is_current', models.BooleanField(default=True, help_text="Indique si c'est le grade actuel du pratiquant pour cette discipline", verbose_name='Grade actuel')),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practitioner_grades', to='competitions.discipline', verbose_name='Discipline')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practitioners', to='grades.grade', verbose_name='Grade')),
                ('practitioner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_history', to='competitions.practitioner', verbose_name='Pratiquant')),
            ],
            options={
                'verbose_name': 'Grade de pratiquant',
                'verbose_name_plural': 'Grades des pratiquants',
                'ordering': ['-date_obtained'],
                'indexes': [models.Index(fields=['practitioner', 'discipline', 'is_current'], name='grades_prac_practit_282ad8_idx'), models.Index(fields=['grade', 'date_obtained'], name='grades_prac_grade_i_df8030_idx')],
            },
        ),
        migrations.CreateModel(
            name='GradeExamRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_date', models.DateTimeField(auto_now_add=True, verbose_name="Date d'inscription")),
                ('payment_confirmed', models.BooleanField(default=False, verbose_name='Paiement confirmé')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvée'), ('rejected', 'Rejetée'), ('passed', 'Réussi'), ('failed', 'Ã‰choué'), ('absent', 'Absent')], default='pending', max_length=20, verbose_name='Statut')),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Score')),
                ('examiner_notes', models.TextField(blank=True, verbose_name="Notes de l'examinateur")),
                ('certificate_issued', models.BooleanField(default=False, verbose_name='Certificat émis')),
                ('certificate_number', models.CharField(blank=True, max_length=50, verbose_name='Numéro de certificat')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='grades.gradeexam', verbose_name='Examen')),
                ('practitioner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_exam_registrations', to='competitions.practitioner', verbose_name='Pratiquant')),
                ('target_grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_registrations', to='grades.grade', verbose_name='Grade visé')),
            ],
            options={
                'verbose_name': 'Inscription Ã\xa0 un examen de grade',
                'verbose_name_plural': 'Inscriptions aux examens de grade',
                'ordering': ['exam', 'registration_date'],
                'unique_together': {('exam', 'practitioner')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='grade',
            unique_together={('name', 'discipline')},
        ),
    ]
