# Generated by Django 4.2.11 on 2025-10-03 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='min_age',
            field=models.PositiveSmallIntegerField(default=0, help_text='Âge minimum requis pour ce grade', verbose_name='Âge minimum'),
        ),
        migrations.AlterField(
            model_name='graderequirement',
            name='min_age',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Âge minimum'),
        ),
    ]
