# Generated by Django 5.1.6 on 2025-11-29 00:23

import apps.grades.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0002_alter_grade_min_age_alter_graderequirement_min_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='icon',
            field=models.CharField(blank=True, help_text='Classe Font Awesome optionnelle (ex: fa-medal, fa-award)', max_length=50, verbose_name='Icône Font Awesome'),
        ),
        migrations.AddField(
            model_name='grade',
            name='image',
            field=models.ImageField(blank=True, help_text='Image du grade (PNG, JPG, SVG, WebP - max 500KB, recommandé 100x100px)', null=True, upload_to='grades/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'svg', 'webp']), apps.grades.models.validate_image_size], verbose_name='Image du grade'),
        ),
    ]
