# Generated by Django 5.1.6 on 2025-12-18 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0026_add_podium_entry_model'),
        ('grades', '0003_add_grade_image_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeAlertLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('milestone', models.CharField(choices=[('j-30', 'J-30 avant eligibilite'), ('j-7', 'J-7 avant eligibilite'), ('eligible', 'Devient eligible'), ('deadline-j14', 'J-14 avant deadline examen'), ('deadline-j3', 'J-3 avant deadline examen'), ('monthly-reminder', 'Rappel mensuel')], max_length=20, verbose_name='Jalon')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de creation')),
                ('exam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='grades.gradeexam', verbose_name='Examen')),
                ('notification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grade_alerts', to='competitions.notification', verbose_name='Notification')),
                ('practitioner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_alerts', to='competitions.practitioner', verbose_name='Pratiquant')),
                ('target_grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='grades.grade', verbose_name='Grade cible')),
            ],
            options={
                'verbose_name': "Log d'alerte grade",
                'verbose_name_plural': "Logs d'alertes grade",
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['practitioner', 'target_grade', 'milestone'], name='grades_grad_practit_b8185a_idx'), models.Index(fields=['practitioner', 'exam', 'milestone'], name='grades_grad_practit_8fd784_idx'), models.Index(fields=['created_at'], name='grades_grad_created_be3e68_idx')],
            },
        ),
    ]
