#!/usr/bin/env python
"""
Script pour synchroniser TOUTES les traductions manquantes dans les fichiers PO.
Langues: am, ar, hi, ja, ko, no, ru, sw, vi, yo, zh, zh-hans, zu
"""

import os

# Traductions pour toutes les langues manquantes
TRANSLATIONS = {
    "am": {  # Amharic
        "Organisation non trouvée": "ድርጅት አልተገኘም",
        "Erreur génération QR codes": "የQR ኮድ ማመንጨት ስህተት",
        "Type de QR code non trouvé": "የQR ኮድ ዓይነት አልተገኘም",
        "Permissions insuffisantes": "በቂ ፈቃዶች የሉም",
        "Méthode non autorisée": "ያልተፈቀደ ዘዴ",
        "Méthode POST requise": "POST ዘዴ ያስፈልጋል",
        "Données QR manquantes": "የQR መረጃ ጎድሏል",
        "Message envoyé avec succès!": "መልእክት በተሳካ ሁኔታ ተልኳል!",
        "Check-in effectué avec succès!": "ቼክ-ኢን በተሳካ ሁኔታ ተደርጓል!",
        "QR code invalide ou membre non trouvé": "ልክ ያልሆነ QR ኮድ ወይም አባል አልተገኘም",
        "Erreur lors du check-in": "በቼክ-ኢን ጊዜ ስህተት",
        "Erreur serveur": "የሰርቨር ስህተት",
        "Non authentifié": "አልተረጋገጠም",
        "Permission refusée": "ፈቃድ ተከልክሏል",
        "Données manquantes": "የጎደለ መረጃ",
        "JSON invalide": "ልክ ያልሆነ JSON",
        "category_id requis": "category_id ያስፈልጋል",
        "Catégorie retirée du tatami": "ምድብ ከታታሚ ተወግዷል",
        "Données invalides": "ልክ ያልሆነ መረጃ",
        "Catégorie non assignée": "ምድብ አልተመደበም",
        "Déjà en première position": "ቀድሞውንም በመጀመሪያ ቦታ ላይ",
        "Déjà en dernière position": "ቀድሞውንም በመጨረሻ ቦታ ላይ",
        "Horaire mis à jour": "መርሃ ግብር ተዘምኗል",
        "Aucune catégorie à programmer": "የሚቀጠር ምድብ የለም",
        "Format d'heure invalide (HH:MM)": "ልክ ያልሆነ የሰዓት ቅርጸት (HH:MM)",
        "Paramètres manquants": "የጎደሉ መለኪያዎች",
        "Action non reconnue": "ያልታወቀ እርምጃ",
        "Erreur lors de l'opération": "በአሠራር ጊዜ ስህተት",
        "Club non trouvé": "ክለብ አልተገኘም",
        "Import/Export de données": "መረጃ ማስገባት/ማውጣት",
        "Exporter les données": "መረጃ ወደ ውጭ ላክ",
        "Importer des données": "መረጃ አስገባ",
        "Exporter en Excel": "ወደ Excel ላክ",
        "Formats acceptés: .xlsx, .xls": "ተቀባይነት ያላቸው ቅርጸቶች: .xlsx, .xls",
        "Importer les données": "መረጃ አስገባ",
        "Nom": "ስም",
        "Prénom": "የመጀመሪያ ስም",
        "Email": "ኢሜይል",
        "Grade": "ደረጃ",
    },
    "ar": {  # Arabic
        "Organisation non trouvée": "المنظمة غير موجودة",
        "Erreur génération QR codes": "خطأ في إنشاء رموز QR",
        "Type de QR code non trouvé": "نوع رمز QR غير موجود",
        "Permissions insuffisantes": "صلاحيات غير كافية",
        "Méthode non autorisée": "طريقة غير مسموح بها",
        "Méthode POST requise": "مطلوب طريقة POST",
        "Données QR manquantes": "بيانات QR مفقودة",
        "Message envoyé avec succès!": "تم إرسال الرسالة بنجاح!",
        "Check-in effectué avec succès!": "تم تسجيل الوصول بنجاح!",
        "QR code invalide ou membre non trouvé": "رمز QR غير صالح أو العضو غير موجود",
        "Erreur lors du check-in": "خطأ أثناء تسجيل الوصول",
        "Erreur serveur": "خطأ في الخادم",
        "Non authentifié": "غير مصادق عليه",
        "Permission refusée": "تم رفض الإذن",
        "Données manquantes": "بيانات مفقودة",
        "JSON invalide": "JSON غير صالح",
        "category_id requis": "مطلوب category_id",
        "Catégorie retirée du tatami": "تمت إزالة الفئة من التاتامي",
        "Données invalides": "بيانات غير صالحة",
        "Catégorie non assignée": "فئة غير مخصصة",
        "Déjà en première position": "بالفعل في المركز الأول",
        "Déjà en dernière position": "بالفعل في المركز الأخير",
        "Horaire mis à jour": "تم تحديث الجدول",
        "Aucune catégorie à programmer": "لا توجد فئة للجدولة",
        "Format d'heure invalide (HH:MM)": "تنسيق وقت غير صالح (HH:MM)",
        "Paramètres manquants": "معلمات مفقودة",
        "Action non reconnue": "إجراء غير معروف",
        "Erreur lors de l'opération": "خطأ أثناء العملية",
        "Club non trouvé": "النادي غير موجود",
        "Import/Export de données": "استيراد/تصدير البيانات",
        "Exporter les données": "تصدير البيانات",
        "Importer des données": "استيراد البيانات",
        "Exporter en Excel": "تصدير إلى Excel",
        "Formats acceptés: .xlsx, .xls": "الصيغ المقبولة: .xlsx, .xls",
        "Importer les données": "استيراد البيانات",
        "Nom": "الاسم",
        "Prénom": "الاسم الأول",
        "Email": "البريد الإلكتروني",
        "Grade": "الدرجة",
    },
    "hi": {  # Hindi
        "Organisation non trouvée": "संगठन नहीं मिला",
        "Erreur génération QR codes": "QR कोड जनरेशन त्रुटि",
        "Type de QR code non trouvé": "QR कोड प्रकार नहीं मिला",
        "Permissions insuffisantes": "अपर्याप्त अनुमतियां",
        "Méthode non autorisée": "अनधिकृत विधि",
        "Méthode POST requise": "POST विधि आवश्यक",
        "Données QR manquantes": "QR डेटा गायब",
        "Message envoyé avec succès!": "संदेश सफलतापूर्वक भेजा गया!",
        "Check-in effectué avec succès!": "चेक-इन सफलतापूर्वक हुआ!",
        "QR code invalide ou membre non trouvé": "अमान्य QR कोड या सदस्य नहीं मिला",
        "Erreur lors du check-in": "चेक-इन के दौरान त्रुटि",
        "Erreur serveur": "सर्वर त्रुटि",
        "Non authentifié": "प्रमाणित नहीं",
        "Permission refusée": "अनुमति अस्वीकृत",
        "Données manquantes": "डेटा गायब",
        "JSON invalide": "अमान्य JSON",
        "category_id requis": "category_id आवश्यक",
        "Catégorie retirée du tatami": "श्रेणी तातामी से हटाई गई",
        "Données invalides": "अमान्य डेटा",
        "Catégorie non assignée": "श्रेणी असाइन नहीं",
        "Déjà en première position": "पहले से पहले स्थान पर",
        "Déjà en dernière position": "पहले से अंतिम स्थान पर",
        "Horaire mis à jour": "समय सारिणी अपडेट की गई",
        "Aucune catégorie à programmer": "शेड्यूल करने के लिए कोई श्रेणी नहीं",
        "Format d'heure invalide (HH:MM)": "अमान्य समय प्रारूप (HH:MM)",
        "Paramètres manquants": "पैरामीटर गायब",
        "Action non reconnue": "अपरिचित क्रिया",
        "Erreur lors de l'opération": "ऑपरेशन के दौरान त्रुटि",
        "Club non trouvé": "क्लब नहीं मिला",
        "Import/Export de données": "डेटा आयात/निर्यात",
        "Exporter les données": "डेटा निर्यात करें",
        "Importer des données": "डेटा आयात करें",
        "Exporter en Excel": "Excel में निर्यात करें",
        "Formats acceptés: .xlsx, .xls": "स्वीकृत प्रारूप: .xlsx, .xls",
        "Importer les données": "डेटा आयात करें",
        "Nom": "नाम",
        "Prénom": "पहला नाम",
        "Email": "ईमेल",
        "Grade": "ग्रेड",
    },
    "ja": {  # Japanese
        "Organisation non trouvée": "組織が見つかりません",
        "Erreur génération QR codes": "QRコード生成エラー",
        "Type de QR code non trouvé": "QRコードタイプが見つかりません",
        "Permissions insuffisantes": "権限が不十分です",
        "Méthode non autorisée": "許可されていないメソッド",
        "Méthode POST requise": "POSTメソッドが必要です",
        "Données QR manquantes": "QRデータがありません",
        "Message envoyé avec succès!": "メッセージが正常に送信されました！",
        "Check-in effectué avec succès!": "チェックインが正常に完了しました！",
        "QR code invalide ou membre non trouvé": "無効なQRコードまたはメンバーが見つかりません",
        "Erreur lors du check-in": "チェックイン中のエラー",
        "Erreur serveur": "サーバーエラー",
        "Non authentifié": "認証されていません",
        "Permission refusée": "権限が拒否されました",
        "Données manquantes": "データがありません",
        "JSON invalide": "無効なJSON",
        "category_id requis": "category_idが必要です",
        "Catégorie retirée du tatami": "カテゴリが畳から削除されました",
        "Données invalides": "無効なデータ",
        "Catégorie non assignée": "カテゴリが割り当てられていません",
        "Déjà en première position": "すでに最初の位置にあります",
        "Déjà en dernière position": "すでに最後の位置にあります",
        "Horaire mis à jour": "スケジュールが更新されました",
        "Aucune catégorie à programmer": "スケジュールするカテゴリがありません",
        "Format d'heure invalide (HH:MM)": "無効な時間形式 (HH:MM)",
        "Paramètres manquants": "パラメータがありません",
        "Action non reconnue": "認識されないアクション",
        "Erreur lors de l'opération": "操作中のエラー",
        "Club non trouvé": "クラブが見つかりません",
        "Import/Export de données": "データのインポート/エクスポート",
        "Exporter les données": "データをエクスポート",
        "Importer des données": "データをインポート",
        "Exporter en Excel": "Excelにエクスポート",
        "Formats acceptés: .xlsx, .xls": "対応形式: .xlsx, .xls",
        "Importer les données": "データをインポート",
        "Nom": "名前",
        "Prénom": "名",
        "Email": "メール",
        "Grade": "級",
    },
    "ko": {  # Korean
        "Organisation non trouvée": "조직을 찾을 수 없습니다",
        "Erreur génération QR codes": "QR 코드 생성 오류",
        "Type de QR code non trouvé": "QR 코드 유형을 찾을 수 없습니다",
        "Permissions insuffisantes": "권한이 부족합니다",
        "Méthode non autorisée": "허용되지 않는 방법",
        "Méthode POST requise": "POST 방법이 필요합니다",
        "Données QR manquantes": "QR 데이터 누락",
        "Message envoyé avec succès!": "메시지가 성공적으로 전송되었습니다!",
        "Check-in effectué avec succès!": "체크인이 성공적으로 완료되었습니다!",
        "QR code invalide ou membre non trouvé": "잘못된 QR 코드 또는 회원을 찾을 수 없습니다",
        "Erreur lors du check-in": "체크인 중 오류",
        "Erreur serveur": "서버 오류",
        "Non authentifié": "인증되지 않음",
        "Permission refusée": "권한 거부됨",
        "Données manquantes": "누락된 데이터",
        "JSON invalide": "잘못된 JSON",
        "category_id requis": "category_id 필요",
        "Catégorie retirée du tatami": "카테고리가 타타미에서 제거되었습니다",
        "Données invalides": "잘못된 데이터",
        "Catégorie non assignée": "카테고리가 할당되지 않음",
        "Déjà en première position": "이미 첫 번째 위치에 있습니다",
        "Déjà en dernière position": "이미 마지막 위치에 있습니다",
        "Horaire mis à jour": "일정이 업데이트되었습니다",
        "Aucune catégorie à programmer": "예약할 카테고리가 없습니다",
        "Format d'heure invalide (HH:MM)": "잘못된 시간 형식 (HH:MM)",
        "Paramètres manquants": "매개변수 누락",
        "Action non reconnue": "인식되지 않는 작업",
        "Erreur lors de l'opération": "작업 중 오류",
        "Club non trouvé": "클럽을 찾을 수 없습니다",
        "Import/Export de données": "데이터 가져오기/내보내기",
        "Exporter les données": "데이터 내보내기",
        "Importer des données": "데이터 가져오기",
        "Exporter en Excel": "Excel로 내보내기",
        "Formats acceptés: .xlsx, .xls": "지원 형식: .xlsx, .xls",
        "Importer les données": "데이터 가져오기",
        "Nom": "이름",
        "Prénom": "이름",
        "Email": "이메일",
        "Grade": "급",
    },
    "no": {  # Norwegian
        "Organisation non trouvée": "Organisasjon ikke funnet",
        "Erreur génération QR codes": "Feil ved generering av QR-koder",
        "Type de QR code non trouvé": "QR-kodetype ikke funnet",
        "Permissions insuffisantes": "Utilstrekkelige tillatelser",
        "Méthode non autorisée": "Metode ikke tillatt",
        "Méthode POST requise": "POST-metode kreves",
        "Données QR manquantes": "Manglende QR-data",
        "Message envoyé avec succès!": "Melding sendt!",
        "Check-in effectué avec succès!": "Innsjekking fullført!",
        "QR code invalide ou membre non trouvé": "Ugyldig QR-kode eller medlem ikke funnet",
        "Erreur lors du check-in": "Feil under innsjekking",
        "Erreur serveur": "Serverfeil",
        "Non authentifié": "Ikke autentisert",
        "Permission refusée": "Tillatelse nektet",
        "Données manquantes": "Manglende data",
        "JSON invalide": "Ugyldig JSON",
        "category_id requis": "category_id kreves",
        "Catégorie retirée du tatami": "Kategori fjernet fra tatami",
        "Données invalides": "Ugyldige data",
        "Catégorie non assignée": "Kategori ikke tildelt",
        "Déjà en première position": "Allerede i første posisjon",
        "Déjà en dernière position": "Allerede i siste posisjon",
        "Horaire mis à jour": "Timeplan oppdatert",
        "Aucune catégorie à programmer": "Ingen kategori å planlegge",
        "Format d'heure invalide (HH:MM)": "Ugyldig tidsformat (HH:MM)",
        "Paramètres manquants": "Manglende parametere",
        "Action non reconnue": "Ukjent handling",
        "Erreur lors de l'opération": "Feil under operasjonen",
        "Club non trouvé": "Klubb ikke funnet",
        "Import/Export de données": "Data import/eksport",
        "Exporter les données": "Eksporter data",
        "Importer des données": "Importer data",
        "Exporter en Excel": "Eksporter til Excel",
        "Formats acceptés: .xlsx, .xls": "Aksepterte formater: .xlsx, .xls",
        "Importer les données": "Importer data",
        "Nom": "Navn",
        "Prénom": "Fornavn",
        "Email": "E-post",
        "Grade": "Grad",
    },
    "ru": {  # Russian
        "Organisation non trouvée": "Организация не найдена",
        "Erreur génération QR codes": "Ошибка генерации QR-кодов",
        "Type de QR code non trouvé": "Тип QR-кода не найден",
        "Permissions insuffisantes": "Недостаточно прав",
        "Méthode non autorisée": "Метод не разрешен",
        "Méthode POST requise": "Требуется метод POST",
        "Données QR manquantes": "Отсутствуют данные QR",
        "Message envoyé avec succès!": "Сообщение успешно отправлено!",
        "Check-in effectué avec succès!": "Регистрация успешно выполнена!",
        "QR code invalide ou membre non trouvé": "Недействительный QR-код или участник не найден",
        "Erreur lors du check-in": "Ошибка при регистрации",
        "Erreur serveur": "Ошибка сервера",
        "Non authentifié": "Не аутентифицирован",
        "Permission refusée": "Доступ запрещен",
        "Données manquantes": "Отсутствуют данные",
        "JSON invalide": "Недействительный JSON",
        "category_id requis": "Требуется category_id",
        "Catégorie retirée du tatami": "Категория удалена с татами",
        "Données invalides": "Недействительные данные",
        "Catégorie non assignée": "Категория не назначена",
        "Déjà en première position": "Уже на первой позиции",
        "Déjà en dernière position": "Уже на последней позиции",
        "Horaire mis à jour": "Расписание обновлено",
        "Aucune catégorie à programmer": "Нет категории для планирования",
        "Format d'heure invalide (HH:MM)": "Неверный формат времени (ЧЧ:ММ)",
        "Paramètres manquants": "Отсутствуют параметры",
        "Action non reconnue": "Неизвестное действие",
        "Erreur lors de l'opération": "Ошибка при выполнении операции",
        "Club non trouvé": "Клуб не найден",
        "Import/Export de données": "Импорт/Экспорт данных",
        "Exporter les données": "Экспортировать данные",
        "Importer des données": "Импортировать данные",
        "Exporter en Excel": "Экспорт в Excel",
        "Formats acceptés: .xlsx, .xls": "Допустимые форматы: .xlsx, .xls",
        "Importer les données": "Импортировать данные",
        "Nom": "Фамилия",
        "Prénom": "Имя",
        "Email": "Эл. почта",
        "Grade": "Разряд",
    },
    "sw": {  # Swahili
        "Organisation non trouvée": "Shirika halijapatikana",
        "Erreur génération QR codes": "Hitilafu ya kutengeneza msimbo wa QR",
        "Type de QR code non trouvé": "Aina ya msimbo wa QR haijapatikana",
        "Permissions insuffisantes": "Ruhusa haitoshi",
        "Méthode non autorisée": "Njia haijaidhinishwa",
        "Méthode POST requise": "Njia ya POST inahitajika",
        "Données QR manquantes": "Data ya QR haipo",
        "Message envoyé avec succès!": "Ujumbe umetumwa kwa mafanikio!",
        "Check-in effectué avec succès!": "Kuingia kumefanikiwa!",
        "QR code invalide ou membre non trouvé": "Msimbo wa QR batili au mwanachama hajapatikana",
        "Erreur lors du check-in": "Hitilafu wakati wa kuingia",
        "Erreur serveur": "Hitilafu ya seva",
        "Non authentifié": "Haujathibitishwa",
        "Permission refusée": "Ruhusa imekataliwa",
        "Données manquantes": "Data haipo",
        "JSON invalide": "JSON batili",
        "category_id requis": "category_id inahitajika",
        "Catégorie retirée du tatami": "Kategoria imeondolewa kwenye tatami",
        "Données invalides": "Data batili",
        "Catégorie non assignée": "Kategoria haijapewa",
        "Déjà en première position": "Tayari katika nafasi ya kwanza",
        "Déjà en dernière position": "Tayari katika nafasi ya mwisho",
        "Horaire mis à jour": "Ratiba imesasishwa",
        "Aucune catégorie à programmer": "Hakuna kategoria ya kupanga",
        "Format d'heure invalide (HH:MM)": "Muundo wa wakati batili (HH:MM)",
        "Paramètres manquants": "Vigezo havipo",
        "Action non reconnue": "Hatua isiyotambuliwa",
        "Erreur lors de l'opération": "Hitilafu wakati wa operesheni",
        "Club non trouvé": "Klabu haijapatikana",
        "Import/Export de données": "Ingiza/Hamisha Data",
        "Exporter les données": "Hamisha data",
        "Importer des données": "Ingiza data",
        "Exporter en Excel": "Hamisha kwa Excel",
        "Formats acceptés: .xlsx, .xls": "Fomati zinazokubaliwa: .xlsx, .xls",
        "Importer les données": "Ingiza data",
        "Nom": "Jina",
        "Prénom": "Jina la kwanza",
        "Email": "Barua pepe",
        "Grade": "Daraja",
    },
    "vi": {  # Vietnamese
        "Organisation non trouvée": "Không tìm thấy tổ chức",
        "Erreur génération QR codes": "Lỗi tạo mã QR",
        "Type de QR code non trouvé": "Không tìm thấy loại mã QR",
        "Permissions insuffisantes": "Quyền không đủ",
        "Méthode non autorisée": "Phương thức không được phép",
        "Méthode POST requise": "Yêu cầu phương thức POST",
        "Données QR manquantes": "Thiếu dữ liệu QR",
        "Message envoyé avec succès!": "Tin nhắn đã được gửi thành công!",
        "Check-in effectué avec succès!": "Đăng ký thành công!",
        "QR code invalide ou membre non trouvé": "Mã QR không hợp lệ hoặc không tìm thấy thành viên",
        "Erreur lors du check-in": "Lỗi khi đăng ký",
        "Erreur serveur": "Lỗi máy chủ",
        "Non authentifié": "Chưa xác thực",
        "Permission refusée": "Quyền bị từ chối",
        "Données manquantes": "Thiếu dữ liệu",
        "JSON invalide": "JSON không hợp lệ",
        "category_id requis": "Yêu cầu category_id",
        "Catégorie retirée du tatami": "Danh mục đã bị xóa khỏi tatami",
        "Données invalides": "Dữ liệu không hợp lệ",
        "Catégorie non assignée": "Danh mục chưa được gán",
        "Déjà en première position": "Đã ở vị trí đầu tiên",
        "Déjà en dernière position": "Đã ở vị trí cuối cùng",
        "Horaire mis à jour": "Lịch trình đã được cập nhật",
        "Aucune catégorie à programmer": "Không có danh mục để lên lịch",
        "Format d'heure invalide (HH:MM)": "Định dạng giờ không hợp lệ (HH:MM)",
        "Paramètres manquants": "Thiếu tham số",
        "Action non reconnue": "Hành động không được nhận dạng",
        "Erreur lors de l'opération": "Lỗi trong quá trình thao tác",
        "Club non trouvé": "Không tìm thấy câu lạc bộ",
        "Import/Export de données": "Nhập/Xuất dữ liệu",
        "Exporter les données": "Xuất dữ liệu",
        "Importer des données": "Nhập dữ liệu",
        "Exporter en Excel": "Xuất sang Excel",
        "Formats acceptés: .xlsx, .xls": "Định dạng chấp nhận: .xlsx, .xls",
        "Importer les données": "Nhập dữ liệu",
        "Nom": "Họ",
        "Prénom": "Tên",
        "Email": "Email",
        "Grade": "Cấp",
    },
    "yo": {  # Yoruba
        "Organisation non trouvée": "Ko ri ajọ",
        "Erreur génération QR codes": "Aṣiṣe ṣiṣẹda koodu QR",
        "Type de QR code non trouvé": "Ko ri iru koodu QR",
        "Permissions insuffisantes": "Awọn igbanilaaye ko to",
        "Méthode non autorisée": "Ọna ko gba laaye",
        "Méthode POST requise": "Ọna POST nilo",
        "Données QR manquantes": "Data QR ti nsọnu",
        "Message envoyé avec succès!": "Ifiranṣẹ ti ranṣẹ!",
        "Check-in effectué avec succès!": "Iforukọsilẹ ti ṣaṣeyọri!",
        "QR code invalide ou membre non trouvé": "Koodu QR ti ko wulo tabi ko ri ọmọ ẹgbẹ",
        "Erreur lors du check-in": "Aṣiṣe lakoko iforukọsilẹ",
        "Erreur serveur": "Aṣiṣe olupin",
        "Non authentifié": "Ko jẹri",
        "Permission refusée": "Igbanilaaye kọ",
        "Données manquantes": "Data ti nsọnu",
        "JSON invalide": "JSON ti ko wulo",
        "category_id requis": "category_id nilo",
        "Catégorie retirée du tatami": "Ẹka ti yọ kuro ninu tatami",
        "Données invalides": "Data ti ko wulo",
        "Catégorie non assignée": "Ẹka ko yan",
        "Déjà en première position": "Ti wa ni ipo akọkọ tẹlẹ",
        "Déjà en dernière position": "Ti wa ni ipo ikẹhin tẹlẹ",
        "Horaire mis à jour": "Eto akoko ti ṣe imudojuiwọn",
        "Aucune catégorie à programmer": "Ko si ẹka lati ṣeto",
        "Format d'heure invalide (HH:MM)": "Ọna akoko ti ko wulo (HH:MM)",
        "Paramètres manquants": "Awọn paramita ti nsọnu",
        "Action non reconnue": "Iṣe ti a ko mọ",
        "Erreur lors de l'opération": "Aṣiṣe lakoko iṣẹ",
        "Club non trouvé": "Ko ri ẹgbẹ",
        "Import/Export de données": "Gbewọle/Gbejade Data",
        "Exporter les données": "Gbejade data",
        "Importer des données": "Gbewọle data",
        "Exporter en Excel": "Gbejade si Excel",
        "Formats acceptés: .xlsx, .xls": "Awọn ọna ti o gba: .xlsx, .xls",
        "Importer les données": "Gbewọle data",
        "Nom": "Orukọ",
        "Prénom": "Orukọ akọkọ",
        "Email": "Imeeli",
        "Grade": "Ipele",
    },
    "zh": {  # Chinese (Simplified)
        "Organisation non trouvée": "未找到组织",
        "Erreur génération QR codes": "二维码生成错误",
        "Type de QR code non trouvé": "未找到二维码类型",
        "Permissions insuffisantes": "权限不足",
        "Méthode non autorisée": "方法不允许",
        "Méthode POST requise": "需要POST方法",
        "Données QR manquantes": "缺少二维码数据",
        "Message envoyé avec succès!": "消息发送成功！",
        "Check-in effectué avec succès!": "签到成功！",
        "QR code invalide ou membre non trouvé": "二维码无效或未找到成员",
        "Erreur lors du check-in": "签到时出错",
        "Erreur serveur": "服务器错误",
        "Non authentifié": "未认证",
        "Permission refusée": "权限被拒绝",
        "Données manquantes": "数据缺失",
        "JSON invalide": "无效的JSON",
        "category_id requis": "需要category_id",
        "Catégorie retirée du tatami": "类别已从榻榻米移除",
        "Données invalides": "无效数据",
        "Catégorie non assignée": "类别未分配",
        "Déjà en première position": "已在第一位",
        "Déjà en dernière position": "已在最后位置",
        "Horaire mis à jour": "时间表已更新",
        "Aucune catégorie à programmer": "没有要安排的类别",
        "Format d'heure invalide (HH:MM)": "无效的时间格式 (HH:MM)",
        "Paramètres manquants": "缺少参数",
        "Action non reconnue": "无法识别的操作",
        "Erreur lors de l'opération": "操作时出错",
        "Club non trouvé": "未找到俱乐部",
        "Import/Export de données": "数据导入/导出",
        "Exporter les données": "导出数据",
        "Importer des données": "导入数据",
        "Exporter en Excel": "导出到Excel",
        "Formats acceptés: .xlsx, .xls": "接受的格式: .xlsx, .xls",
        "Importer les données": "导入数据",
        "Nom": "姓",
        "Prénom": "名",
        "Email": "电子邮件",
        "Grade": "段位",
    },
    "zu": {  # Zulu
        "Organisation non trouvée": "Inhlangano ayitholakali",
        "Erreur génération QR codes": "Iphutha lokukhiqiza amakhodi e-QR",
        "Type de QR code non trouvé": "Uhlobo lwekhodi ye-QR alutholakalanga",
        "Permissions insuffisantes": "Izimvume azanele",
        "Méthode non autorisée": "Indlela engavunyelwe",
        "Méthode POST requise": "Indlela ye-POST iyadingeka",
        "Données QR manquantes": "Idatha ye-QR ayikho",
        "Message envoyé avec succès!": "Umlayezo uthunyelwe ngempumelelo!",
        "Check-in effectué avec succès!": "Ukubhalisa kuphumelele!",
        "QR code invalide ou membre non trouvé": "Ikhodi ye-QR engavumelekile noma ilungu alitholakali",
        "Erreur lors du check-in": "Iphutha ngesikhathi sokubhalisa",
        "Erreur serveur": "Iphutha leseva",
        "Non authentifié": "Akuqinisekisiwe",
        "Permission refusée": "Imvume yenqatshiwe",
        "Données manquantes": "Idatha elahlekile",
        "JSON invalide": "I-JSON engavumelekile",
        "category_id requis": "category_id iyadingeka",
        "Catégorie retirée du tatami": "Isigaba sisuswe ku-tatami",
        "Données invalides": "Idatha engavumelekile",
        "Catégorie non assignée": "Isigaba asinikeziwe",
        "Déjà en première position": "Sekuvele kusesikhundleni sokuqala",
        "Déjà en dernière position": "Sekuvele kusesikhundleni sokugcina",
        "Horaire mis à jour": "Isheduli ibuyekeziwe",
        "Aucune catégorie à programmer": "Asikho isigaba sokuhlelwa",
        "Format d'heure invalide (HH:MM)": "Ifomethi yesikhathi engavumelekile (HH:MM)",
        "Paramètres manquants": "Amapharamitha alahlekile",
        "Action non reconnue": "Isenzo esingaziwa",
        "Erreur lors de l'opération": "Iphutha ngesikhathi sokusebenza",
        "Club non trouvé": "Iklabhu ayitholakali",
        "Import/Export de données": "Ngenisa/Thumela Ngaphandle Idatha",
        "Exporter les données": "Thumela idatha",
        "Importer des données": "Ngenisa idatha",
        "Exporter en Excel": "Thumela ku-Excel",
        "Formats acceptés: .xlsx, .xls": "Amafomethi amukelwayo: .xlsx, .xls",
        "Importer les données": "Ngenisa idatha",
        "Nom": "Isibongo",
        "Prénom": "Igama",
        "Email": "I-imeyili",
        "Grade": "Ibanga",
    },
}

# Entrées supplémentaires communes à ajouter à toutes les langues
COMMON_ENTRIES_TEMPLATE = {
    "Gestion des données de votre club": None,
    "Cette page vous permet d'importer et d'exporter les données de votre club au format Excel. Vous pouvez ainsi gérer facilement vos pratiquants et optimiser votre organisation.": None,
    "Téléchargez toutes les données de vos pratiquants au format Excel pour les consulter hors ligne ou les modifier dans un tableur.": None,
    "Importez de nouveaux pratiquants ou mettez à jour les existants en uploadant un fichier Excel au format approprié.": None,
    "Commencer l'import": None,
    "Importation de données": None,
    "Téléchargez le modèle": None,
    "Utilisez notre modèle Excel pour vous assurer que vos données sont au bon format.": None,
    "Télécharger le modèle": None,
    "Remplissez le fichier": None,
    "Complétez le fichier Excel avec les informations de vos pratiquants. Veillez à respecter le format des colonnes.": None,
    "Importez le fichier": None,
    "Uploadez votre fichier Excel complété pour importer les données dans le système.": None,
    "Déposez votre fichier ici": None,
    "Choisir un fichier...": None,
    "Structure attendue du fichier Excel": None,
    "Colonne A:": None,
    "Colonne B:": None,
    "Colonne C:": None,
    "Colonne D:": None,
    "Colonne E:": None,
    "Colonne F:": None,
    "Date de naissance (AAAA-MM-JJ)": None,
    "Numéro de licence": None,
    "Retour au tableau de bord": None,
    "Gérer les pratiquants": None,
    "Exporter les pratiquants": None,
    "Téléchargez la liste complète de vos pratiquants au format Excel pour sauvegarde ou modification hors ligne.": None,
    "Format: Excel (.xlsx)": None,
    "Importer des pratiquants": None,
    "Modèle de fichier": None,
    "Téléchargez ce modèle pour vous assurer que votre fichier est au bon format.": None,
    "Télécharger le modèle Excel": None,
    "Format attendu:": None,
    "NOM": None,
    "Date de naissance": None,
    "adresse mail": None,
    "Glissez votre fichier ici": None,
    "ou cliquez pour sélectionner": None,
    "Choisir un fichier": None,
    "Formats acceptés: CSV, Excel (.xlsx, .xls) - Max 10MB": None,
    "Importation en cours...": None,
    "Résultats de l'importation": None,
    "Aide et conseils": None,
    "Formats de date acceptés": None,
    "JJ/MM/AAAA (ex: 15/03/2010)": None,
    "JJ-MM-AAAA (ex: 15-03-2010)": None,
    "JJ.MM.AAAA (ex: 15.03.2010)": None,
    "Conseils pour l'import": None,
    "Vérifiez que les noms de colonnes correspondent": None,
    "Assurez-vous que les dates sont au bon format": None,
    "Les doublons seront automatiquement ignorés": None,
}


def add_translations_to_po(po_file_path, translations, lang_code):
    """Add missing translations to a PO file."""

    with open(po_file_path, 'r', encoding='utf-8') as f:
        content = f.read()

    existing_msgids = set()
    lines = content.split('\n')
    for line in lines:
        if line.startswith('msgid "') and line != 'msgid ""':
            msgid = line[7:-1]
            existing_msgids.add(msgid)

    new_entries = []
    for msgid, msgstr in translations.items():
        if msgid not in existing_msgids:
            escaped_msgid = msgid.replace('"', '\\"')
            escaped_msgstr = msgstr.replace('"', '\\"') if msgstr else escaped_msgid
            entry = f'\nmsgid "{escaped_msgid}"\nmsgstr "{escaped_msgstr}"\n'
            new_entries.append(entry)

    if new_entries:
        with open(po_file_path, 'a', encoding='utf-8') as f:
            f.write(f'\n# New translations for {lang_code}\n')
            for entry in new_entries:
                f.write(entry)
        return len(new_entries)
    return 0


def main():
    base_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

    total = 0
    for lang_code, translations in TRANSLATIONS.items():
        po_path = os.path.join(base_dir, 'locale', lang_code, 'LC_MESSAGES', 'django.po')
        if os.path.exists(po_path):
            count = add_translations_to_po(po_path, translations, lang_code)
            if count > 0:
                print(f"{lang_code}: +{count} translations")
                total += count
        else:
            print(f"{lang_code}: File not found")

    # Handle zh-hans separately if it exists
    zh_hans_path = os.path.join(base_dir, 'locale', 'zh-hans', 'LC_MESSAGES', 'django.po')
    if os.path.exists(zh_hans_path):
        count = add_translations_to_po(zh_hans_path, TRANSLATIONS.get('zh', {}), 'zh-hans')
        if count > 0:
            print(f"zh-hans: +{count} translations")
            total += count

    print(f"\nTotal: {total} translations added")


if __name__ == '__main__':
    main()
