BBBBBBB BBBBBBBBBBB
BBBB BBBB
BBBB BBBBBB

BBBBB BBBBB gettext(u'Gestion de présence')  X BBBBBBBB

BBBBB BBBBBBBBB
XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
XXXXXXX
    XXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXX XXXXXXX XXXXXX
        XXXXXX XXXXXX
        XXXXXXXX XXXX XX
        XXXXXXXXXXXXXX XXXXX
        XXXXXXXXXXXXXX XXXXX
    X
    
    XXXXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXX XXXXXXXX
        XXXXXXX XXX XXXXXX XXXXXXXX
        XXXXXXXXXXXXXX XXXXX
        XXXXXXXX XXXXX
        XXXXXXXXXXX XXXXXXX
        XXXXXXXXXXXXXX XXXXX
    X
    
    XXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXXXX XXXXXXXX
        XXXXXXXXXXX XXXXXXXX
    X
    
    XXXXXXXXXXXXXX X
        XXXXXXXX XXXXX
        XXXX XXXXX
        XXXXXXXXXXXXXX XXXXX
        XXXXXXXXXX XXXXX
    X
    
    XXXXXXXXXXXXXXXXX X
        XXXXXXXX XXXXXXX XXXXXXX
        XXXXXXXXXXXXXX XXXXX
        XXXXXXX XXXXX
        XXXXXXXXXXXX XXXX
        XXXXXXXXXXX XXX XXXX XXXXX
        XXXXXXXX XXXXX
        XXXXXXXXXXXX XXXXXXX
        XXXX XXXXXXX
    X
    
    XXXXXXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXX XXXXXXXXXXXXXXXXX
        XXXXXXXXXXX X XXX XXXX XXXXXXXXXXXXXXXX
    X
    
    XXXXXXXXX X
        XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXX
        XXXXXX XXXXXX
    X
    
    XXXXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXX
        XXXXXX XXXXXX
    X
    
    XXXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXX
        XXXXXX XXXXXX
    X
    
    XXXXXXXXXXX X
        XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXX
        XXXXXX XXXXXX
    X
    
    XXXXXXXXXXXXXXXX X
        XXXXXXX XXXXX
        XXXXXXXXXXXXXX XXXXX
        XXXXXXXXXXX X XXX XXXX XXXXXXXXXXXXXXXX
        XXXXXXXXXXX XXX XXXX XXXXX
    X
    
    XXXXXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXX XXXXXXXXXXXXXXXXX
        XXXXXXXXXXX X XXX XXXX XXXXXXXXXXXXXXXXX
    X
    
    XXXXXXXXXXXXX X
        XXXXXXXX XXXXXX XXXXX
        XXXXXXXXXXXXXX XXXXX
        XXXXXXXXXXXX XXXX
        XXXXXXXXXX XXXXXXX
    X
    
    XXXXXXXXXXXXXXX X
        XXXXXXXXXXX XXXXXXXX
        XXXXXX XXXXXXXX
    X
    
    XXXXXXXXXXXXXX X
        XXXXXXXXXXX XXXXXXXX
        XXXXXX XXXXXXXX
    X
    
    XXXXXXXXXXXXXXX X
        XXXXXXXXXXX XXXXXXXX
        XXXXXX XXXXXXXX
    X
    
    XXXXXXXXXXXX X
        XXXXXXXXXXX XXXXXXXX
        XXXXXX XXXXXXXX
    X
    
    XXXXXXXXXXXXXXXX X
        XXXXXXXXXXX XXXXXXX
        XXXXXXXX XXXXX
        XXXXXXXXXXX XXXXXX
        XXXXXXXXXXXXXX XXXXX
        XXXXXXXXXXXXXX XXXXX
    X
    
    XXXXXXXXXXXXXXXX XXX X
        XXXXXXXXXX XXXXXX
        XXXXXXX XXXXX
    X
    
    XXXXXXXXXXXX X
        XXXXXXXX XXXXX
        XXXXXXXXXXXXXX XXXXX
        XXXXXXX XXXX XX
        XXXXXXXX XXXXX
    X
    
    XXXXXXXXXXXXX X
        XXXXXXXXXXX XXXXXXXX
        XXXXXX XXXXXXXX
        XXXXXXX XXX XXXXX XXXXXXXX
    X
    
    XXXXXXXXXXX X
        XXXXXXXXXXX XXXXXXXX
        XXXXXX XXXXXXXX
        XXXXXXX XXX XXXXX XXXXXXXX
    X
    
    XXXXXXXXXXX X
        XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXX XXXXXXX XXXXXX
        XXXXXXX XXXXX
        XXXXXXXXXXXXXX XXXXX
        XXXXXXXXXXX XXXXXXX
        XXXXXXXX XXXXXXX
        XXXXXXXXXXX XXX XXXX XXXXX
    X
    
    XXXXXXXXXXXXXXXXX X
        XXXXXXXXXX XXXXXXXXXXXXXXXXX
        XXXXXXXXXXX X XXX XXXX XXXXXXXXXXXXXXXX
    X
    
    XXXXXXXXXXXXX X
        XXXXXXXXXX XXXXXXX
        XXXXXXXXXXXX XXXX
        XXXXXXXXXXXXXX XXXXXXX
    X
    
    XXXXXXXXXXXX X
        XXXXXX XXXXXXXX
        XXXXXXXXXXXX XXXX
    X
XXXXXXXX
BBBBBBBB

BBBBB BBBBBBB
XXXX XXXXXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXX XXXX XXXXX XX XXXXXXX XXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXX
                XXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX  gettext(u'Gestion de présence') XXXXX
                XX XXXXXXXXXXXXX X FFFFFFFFFFFFXXXX
            XXXXXX
            XXXX XXXXXXXXXXXXXXX XXXXXXXXXX
                XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                    XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXX  gettext(u'Retour') 
                XXXX
            XXXXXX
                XXXXXX
            XXXXXX

            BB BBBBBBBB
                BBB BBBBBBB BB BBBBBBBB
                    XXXX XXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXX XXXX XXXXX XXXXXXXXXXXXX
                        
                        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXX
                BBBBBB
            BBBBB

    XXXX XXXXXXX XXXXXXX XXX
    XXXX XXXXXXXXXXXXXXXXXXXXXX
        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XX XXXXXXXXXX XXXXXXXXXXXXXXX  gettext(u'Scanner QR Code') 
        XXXXXXXXX
        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
            XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX  gettext(u'Marquer tous présents') 
        XXXXXXXXX
        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
            XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX  gettext(u'Marquer tous absents') 
        XXXXXXXXX
        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XX XXXXXXXXXX XXXXXXXXXXXXXXXXX  gettext(u'Exporter') 
        XXXXXXXXX
    XXXXXX

    XXXX XXXXXXX XX XXXX XXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX
        XXXXXX XXXXXXXXXX XXXXXXXXXXXXXXX  gettext(u'Scanner QR Code') XXXXX
        XX XXXXXXXXXXXXXXXXXXX gettext(u'Scannez le QR code du pratiquant pour marquer sa présence') XXXX
        XXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXX XXXXXXXXXX XXXXXX XXXXXXX X XXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XX XXXXXXXXXX XXXXXXXXXXXXXX  gettext(u'Fermer le scanner') 
        XXXXXXXXX
    XXXXXX

    XXXX XX XXXX XX XX XXXXXXX XXX
    XXXX XXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXX
            XXXXXX XXXXXXXXXX XXXXXXXXXXXXXXX  gettext(u'QR Code de la session') XXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                XX XXXXXXXXXXXXXXXXX XXXXXX gettext(u"Les pratiquants peuvent scanner ce QR code pour s'enregistrer") XXXX
            XXXXXX
        XXXXXX
    XXXXXX

    XXXX XXXXXXXXXXXX XX XXXXXXXX XXX
    XXXX XXXXXXXXXX XXXXXX
        XXXX XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXX gettext(u'Total pratiquants') XXXXXX
            XXXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXX gettext(u'Présents') XXXXXX
            XXXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXX gettext(u'Absents') XXXXXX
            XXXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXX gettext(u'Excusés') XXXXXX
            XXXXXX
        XXXXXX
    XXXXXX

            XXXX XXXXXXXXXXXX XX XX XXXXXXX XXX
    XXXX XXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXX
            XXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXX  gettext(u'Détails de la session') XXXXX
                XXXXXX
                XXXX XXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXXXXX
                            XXXXXXXX gettext(u'Date') XXXXXXXXXXXXXX
                            FFFFFFFFFFFF
                        XXXXXX
                        XXXX XXXXXXXXXXXXXXXXX
                            XXXXXXXX gettext(u'Créneau') XXXXXXXXXXXXXX
                            
                        XXXXXX
                        XXXX XXXXXXXXXXXXXXXXX
                            XXXXXXXX gettext(u'Horaire') XXXXXXXXXXXXXX
                            FFFFFFFFFF X FFFFFFFFFF
                        XXXXXX
                        XXXX XXXXXXXXXXXXXXXXX
                            XXXXXXXX gettext(u'Instructeur') XXXXXXXXXXXXXX
                            BB BBBBBBBBBBBBBBBBBB
                                FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
                            BBBB
                                X
                            BBBBB
                        XXXXXX
                    XXXXXX
                    BB BBBBBBBBBBBBB
                        XXXX XXXXXXXXXXXXX
                            XXXXXXXX gettext(u'Notes') XXXXXXXXXXXXXX
                            
                        XXXXXX
                    BBBBB
                XXXXXX
            XXXXXX

            XXXX XXXXX XX XXXXXXXX XXX
    XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXX
            XXXXXX XXXXXXXXXX XXXXXXXXXXXXXX  gettext(u'Liste des pratiquants') XXXXX
                XXXXXX
                XXXX XXXXXXXXXXXXXXXXXX
                    BB BBBBBBBBBBB
                XXXXX XXXXXXXXXXXXX XXXXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBX XXXXXXXXXXXXXXXXXXXX
                            BBBBBBBBBB
                            XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                                XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX
                                    XXXXXXX
                                        XXXX
                                            XXXX gettext(u'Nom') XXXXX
                                            XXXX gettext(u'Prénom') XXXXX
                                            XXXX gettext(u'Grade') XXXXX
                                            XXXX gettext(u'Statut') XXXXX
                                            XXXX gettext(u"Heure d'arrivée") XXXXX
                                            XXXX gettext(u'Notes') XXXXX
                                    XXXX gettext(u'Actions') XXXXX
                                        XXXXX
                                    XXXXXXXX
                                    XXXXXXX
                                        BBB BBBBBBBBBB BB BBBBBBBBBBB
                                        XXXX
                                            XXXXXXXXX
                                            XXXXXXXXX
                                            XXXX
                                                BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
                                                    
                                                BBBB
                                                    X
                                                BBBBB
                                            XXXXX
                                            XXXX
                                                XXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX 
                                                XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                                                    XXXXXXX XXXXXXXXXXXXXXX BB BBBBBBBBBBBBBBBBB BB BBBBBBBBBXXXXXXXXBBBBBX
                                                         gettext(u'Présent') 
                                                    XXXXXXXXX
                                                    XXXXXXX XXXXXXXXXXXXXX BB BBBBBBBBBBBBBBBBB BB BBBBBBBBXXXXXXXXBBBBBX
                                                         gettext(u'Absent') 
                                                    XXXXXXXXX
                                                    XXXXXXX XXXXXXXXXXXXXXX BB BBBBBBBBBBBBBBBBB BB BBBBBBBBBXXXXXXXXBBBBBX
                                                         gettext(u'Excusé') 
                                                    XXXXXXXXX
                                                    XXXXXXX XXXXXXXXXXXX BB BBBBBBBBBBBBBBBBB BB BBBBBBXXXXXXXXBBBBBX
                                                         gettext(u'En retard') 
                                                    XXXXXXXXX
                                                XXXXXXXXX
                                            XXXXX
                                            XXXX
                                                BB BBBBBBBBBBBBBBBBBBBBBBB
                                                    FFFFFFFFFF
                                                BBBB
                                                    X
                                                BBBBB
                                            XXXXX
                                            XXXX
                                                XXXXXX XXXXXXXXXXX XXXXXXXXXXXXX 
                                                       XXXXXXXX 
                                                       XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                                            XXXXX
                                    XXXX
                                        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXX 
                                                XXXXXXXXXXXXXXXXXXXXXXXX
                                            XX XXXXXXXXXX XXXXXXXXXXXXXX
                                        XXXXXXXXX
                                        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXX 
                                                XXXXXXXXXXXXXXXXXXXXXXX
                                            XX XXXXXXXXXX XXXXXXXXXXXXXX
                                        XXXXXXXXX
                                            XXXXX
                                        XXXXX
                                        BBBBBB
                                    XXXXXXXX
                                XXXXXXXX
                            XXXXXX
                            XXXX XXXXXXXXXXXXXXX XXXXXX
                                XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX
                                    XX XXXXXXXXXX XXXXXXXXXXXXX  gettext(u'Enregistrer') 
                                XXXXXXXXX
                            XXXXXX
                        XXXXXXX
                    BBBB
                        XX XXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXX
                            XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXX  gettext(u'Aucun pratiquant inscrit à cette session.') 
                        XXXX
                    BBBBB
        XXXXXX
    XXXXXX
XXXXXX

XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXX
XXX XXXXXXXXXXXXXXXXXX X XXXXX

XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X
    XX XXXXXX X XXXX XX XXXXXXX XX XXXXXX XX XXXXXXXX XX XXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
        XXX
    XXX
    
    XX XXXXXXX XX XX XXXX XX XX XXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXX
XXX

XXXXXXXX XXXXXXXXXXXXXXXXX X
    XXXXX XXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XX XXXXXXXXXXXXXXXXXXXXXXXX XXX XXXXXXX X
        XXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXX
    X XXXX X
        XXXXXXXXXXXXXXXXXXXXXXX X XXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXX
    X
X

XXXXXXXX XXXXXXXXXXXXXXXX X
    XXXXXXXXXXXXXXXXXX X XXX XXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXX 
        X XXXX XXX XXXXXX XXXXXXX XXXX XXXXXXX XXXX XX
        XXXXX
    XX
    
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
X

XXXXXXXX XXXXXXXXXXXXXXX X
    XX XXXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXX X XXXXX
    X
X

XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX X
    XXXXX XXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXX
    XXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXX XXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXX X XXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XX XXXX XXXXXXX XXXXXXXXXXXXXXXX
    
    XX XXX XXXX XXXXXX XXXXXXX XX XXXXXXX XXXX XXXXXXX XX XX XXXX
    XX XXX XXXXXXXX XXXXXXXX XX XXXXXXXXXX XX XX XXXXXXX XXXXXXX
    
    XXXXXXXXXXXXX XX X
        XXXXXXXXXXXXXXXXXXXXXXX X XXXXXXX
    XX XXXXXX
X

XXXXXXXX XXXXXXXXXXXXXXXXXX X
    XXXXX XXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXX
    XXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXX XXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXX X XXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX XX XXXXX XXXXXXXXXX
    
    XXXXXXXXXXXXX XX X
        XXXXXXXXXXXXXXXXXXXXXXX X XXXXXXX
    XX XXXXXX
X

XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX X
    XXXXX XXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXX X X
        XXXXXXXXXXX X
        XXXXX XFFFFFFFFFFFFXX
        XXXXX XFFFFFFFFFFX
    XX
    
    XX XXX XXXX XXXXXX XXXXXXXX XXX XXXXXXXXXXXX XX XXXX XXXX XXXXXXX XX XX XXXX
    XX XXXX XXXXXXXXXX XX XXXXXXX XXXXX XXX XXXXXXX
    XXXXXXXXXXXXXXXXXXXXX X X
        XXXX XXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXX XXXXX XXXXXXXXXXXXXX XXXXXXX
            XX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXX XXXXXX XXXXXXXXXXXXXX
            XX XXXXXXXXXXX XXXXXXXXXXXXX XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXX
    XX
X

XXXXXXXX XXXXXXXXXXXXXXXX X
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX X
        XXXXXXXXXXXX X XXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
    XXX
X

XXXXXXXX XXXXXXXXXXXXXXX X
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX X
        XXXXXXXXXXXX X XXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
    XXX
X

XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX X
    XXXXX XXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XX XXXXXXXX X
        XXXXXXXXXXXX X XXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
    X
X

XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX X
    XXXXX XXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XX XXXXXXXX X
        XXXXXXXXXXXX X XXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
    X
X

XXXXXXXX XXXXXXXXXXXXXXXXXX X
    XX XXXXXXX XXXXXXXX XXXXX XXXXXX XXXXX
    XXXXXXX gettext(u"Fonctionnalité d\\'export à implémenter") XXX
X
XXXXXXXXX
BBBBBBBB