BBBB BBBB
BBBB BBBBBB
XXXXXXXXX XXXXX
XXXXX XXXXXXFFFFFFFFFFFFXX
XXXXXX
    XXXXX XXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
    XXXXXXXBBBBB BBBBBXXXXXXXXXXXBBBBBBBBXXXXXXXX
    
    XXXX XXXXXXXXX XXX XXX
    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
    XXXX XXXX XXXXXXX XXX
    XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    
    XXXX XXXXXXXXXX XXXX XXXXXXXXXXX XXX
    BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
    
    BBBBB BBBBBBBBBBBBBBBBB
    
    XXXXXXX
        XX XXXXXXX XX XXXXXXXXXXXXX XXXXXXX XX
        XXXXXXXXXXXXXXXXXXX X
            XXXXXXXXX XXXXXXXXX
            XXXXXX XXXXXXXX
            XXXXXXXXXXXXXXXX XXXXX
            XXXXXXXX XXXXXXX
            XXXXXXX X XXXXXXXX
        X
        
        XXXXXXXXXXXXXXXXXXXXXXXXX X
            XXXXXX XXXXXXXX
            XXXXXXXXXXXXXXXX XXXXX
        X
        
        XXXXXXXXXXXXXXXXXXX X
            XXXXXXXXX XXXXXXXXX
            XXXX XXXXX
            XXXXXX XXXXX
            XXXXXXXXXXXXXXXXX XXXXXXXX
            XXXXXX XXXXXX
            XXXXXXXXXXXXXX XXXX
            XXXXXXXX XXX XXXX
            XXXXXXXXXX XXXXXXXX
            XXXXXXXXXXXX XXXXX
            XXXXXXXXXX XXXXX
            XXXXXXXXXXX XXXXXXX
            XXXXXXXXXXXX XX
        X
        
        XXXXXXXXXXXXXXXXXXXXXXX X
            XXXXXXXXXX XXXXXX
            XXXXXXXXXXX XXXXXX
            XXXXXXXXXXX XXXXX
        X
        
        XXXXXXXXXXXXXXXXXX X
            XXXXXXXX XXXXXXXX
            XXXXXXXXXXXXXX XXX XXXXX XXXXXXXX
            XXXXXXX XXXXXXXX
            XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXX
        X
        
        XXXXXXXXXXXXXXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXX XXXXXXXX
        X
        
        XXXXXXXXXXXXXXXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXX XXXXXXXX
            XXXXXXXXXXXX XXX XXXXX XXXXXXXX
        X
        
        XXXXXXXXXXXXXXXXXXX X
            XXXXXXXXXXXX XXXX
            XXXXXXXXXXXXXX XXXXXXXX
            XXXXXXXXXX XXXXXXX
        X
        
        XXXXXXXXXXXXXXXXXXXXX X
            XXXXXX XXXXXXXX
            XXXXXXXXXX XXXXXXX
            XXXXXXXXXXXXXX XXXXXXXX
        X
        
        XXXXXXXXXXXXXXXXXX X
            XXXXXX XXXXXXXX
            XXXXXXXXXX XXXXXXX
        X
        
        XXXXXXXXXXXXXXXXXXX X
            XXXXXXXXXXX XXXXXXX
            XXXXXXXX XXXXX
            XXXXXX XXXXXXXX
        X
    XXXXXXXX
XXXXXXX
XXXXXX
    XXXX XXXXXXXXXX XXXXXXXXXX XXX
    XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXX
            XX XXXXXXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBXX
                XX XXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXX gettext(u'MartialComp') XXXX
            
            XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXX
            
            XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
                XXX XXXXXXXXXXXXXXXXX XXXXXXXXX
                    XXX XXXXXXXXXXXXXXXXX
                        XX XXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBXX gettext(u'Accueil') XXXX
                    XXXXX
                XXXXX
                
                XXX XXXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXX XX XXXXXX XXX
                    XXX XXXXXXXXXXXXXXXXX
                        BBBB BBBBBBBBBBBBBBBBBBB
                        BBBBBBBBBBBBBBBBB
                    XXXXX
                    
                    BB BBBBBBBBBBBBBBBBBBBBB
                        XXXX XXXXXXX XX XXXXXXXXXXXXX X XXXXXXX XXX
                        XXX XXXXXXXXXXXXXXXXX
                            XX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX 
                               XXXXXXX gettext(u'Notifications') XX
                                XX XXXXXXXXXXXXXXX XXXXXXXXXXXXX
                                XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
                            XXXX
                        XXXXX
                        
                        XXXX XXXX XXXXXXXXXXX XXX
                        XXX XXXXXXXXXXXXXXX XXXXXXXXXX
                            XX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX 
                               XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                                XX XXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXX 
                            XXXX
                            XXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                XXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBXX
                                    XX XXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX gettext(u'Tableau de bord') 
                                XXXXXXXXX
                                BBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBB
                                XXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
                                    XX XXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX gettext(u'Mon profil') 
                                XXXXXXXXX
                                BB BBBBBBBBBBBBB
                                XXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBXX
                                    XX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXX gettext(u'Administration') 
                                XXXXXXXXX
                                BBBBB
                                XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                XXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBXX
                                    XX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX gettext(u'Déconnexion') 
                                XXXXXXXXX
                            XXXXX
                        XXXXX
                    BBBB
                        XXX XXXXXXXXXXXXXXXXX
                            XXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                XX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                                 gettext(u'Se connecter') 
                            XXXXXXXXX
                        XXXXX
                        XXX XXXXXXXXXXXXXXXXX
                            XX XXXXXXBBB BBBBBBBBBBBBBBBBX XXXXXXXXXX XXXXXXXXXXXXX
                                XX XXXXXXXXXX XXXXXXXXXXXXXXXXXX
                                 gettext(u"S'inscrire") 
                            XXXX
                        XXXXX
                    BBBBB
                XXXXX
            XXXXXX
        XXXXXX
    XXXXXX

    XXXX XXXXXXXX XXXXXX XXX
    BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB

    XXXX XXXXX XXXXXXXXXXXXXXXXXXXXXX XXX
    XXXX XXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXXXXXX
            XXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Tous les messages') XXXXX
            XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXXX
          XXXX XXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
              XXXX XXXXX XXX XXXXXXXX XXXX XXXXXXXX XXX XXX
            XXXXXX
          XXXXXX
        XXXXXX
      XXXXXX
    XXXXXX

    XXXX XXXXXXX XXXXXXXXX XXX
    XXXXXX
        BBBBB BBBBBBBBBBBBBBB
    XXXXXXX

    XXXX XXXXXX XXX
    XXXXXXX XXXXXXXXXXXXXX XXXXXXXXXX XXXX XXXXXX
        XXXX XXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXX
                    XXXX gettext(u'MartialComp') XXXXX
                    XXX gettext(u"Plateforme de gestion des compétitions d'arts martiaux") XXXX
                XXXXXX
                XXXX XXXXXXXXXXXXXXX XXXXXXXXXX
                    XXXXXXXXX XXXX XXXXXXXXXXXX  gettext(u'Tous droits réservés.') XXXX
                XXXXXX
            XXXXXX
        XXXXXX
    XXXXXXXXX

    XXXX XXXXXXXXX XX XXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    
    XXXX XXXXXX XXXXXXXXXXXXX XXXX XXX
    XXXXXXXX
        XX XXXXXXXXXX XXX XXXXXXXXXXXXX XX XXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X
            BB BBBBBBBBBBBBBBBBBBBBB
                XXXXXXXXXXXXXXXXXXXX
                XX XXXXXXXXXX XXX XXXXXXXXXXXXX XXXXXX XXX XX XXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX
            BBBBB
        XXX
        
        XXXXXXXX XXXXXXXXXXXXXXXXXXX X
            XXX X
                XXXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXX
                    XXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXX
                    XXXXXXXXXX XX X
                        XXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XX
                    XXXXXXXXXXXX XX X
                        XXXXXXXXXXXXXXXXXXXXX XXXX XX XXXXXXXXXX XXX XXXXXXXXXXXXXXXX XXXXXXX
                    XXX
            X XXXXX XXXXXXX X
                XXXXXXXXXXXXXXXXXXXXXXXXXX XXX XXXXXXXXXXXXXX XXXXXXX
            X
        X
        
        XX XXXXXXXXX XXXXXXXXXXXXX X XXXXX XXX XXXXXXX XX XXXXXXXXX XX XXXXXXXX XXXXXXX
        XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX X
            XXXXX XXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXX XXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XX XXXXXXXXXXXXXX XX XXXXXXXXXXXXX XXXXXXX
            XX XXXXXX X XXXX XX XXXXXXXX
            XX XXXXXXXXXXXXXXXXXX X XX X
                XXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXX X XX X XXXXX X XXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXX
            X XXXX X
                XXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXX
            X
            
            XX XXXXXX X XXXX XX XXXXX
            XX XXXXXXXXXXXXXXXXXXXXXXXXXX XXX XX X
                XXXXXXXXXXXXXXXXXXXXX X X
                    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XX XXXXXXXXXX XXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXX
                        XXXXXX XXXXXXXXXXXX
                    XXXXXX
                XX
            X XXXX X
                XXX XXXX X XXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX X
                    XXXX XX X
                        XXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXX X XXXX 
                             XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXX
                            XXXX XXXXXXXXXXXXXXX
                                XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXX
                                XXXX XXXXXXXXXXXXXXXXXXXX
                                    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                XXXXXX
                            XXXXXX
                        XXXXXX
                    XX
                XXX
                XXXXXXXXXXXXXXXXXXXXX X XXXXX
            X
        X
        
        XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X
            XXXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX X
                XXXXXXX XXXXXXX
                XXXXXXXX X
                    XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                X
            XXXXXXXXXX XX X
                XX XXXXXXXXXX XX XXXXXXXXX XXX XXXX X
                    XXXXXXXXXXXXXXXXXXXX X XXXXXXXXXX
                X XXXX X
                    XXXXXXXXXXXXXXXXXXXX
                X
            XXX
        X
        
        XXXXXXXX XXXXXXXXXXXXXXX X
            XXXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXX X
                XXXXXXX XXXXXXX
                XXXXXXXX X
                    XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                X
            XXXXXXXXXX XX X
                XXXXXXXXXXXXXXXXXXXX
            XXX
        X
    XXXXXXXXX
    
    BBBBB BBBBBBBBBBBBBBBB
XXXXXXX
XXXXXXX

XXXXXXXX
XX XXXXXXXXX XX XXXXXX XX XXXXXXXX XXXX XX XXXXXX
XXXXXXXXXXX X
  XXX XXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXX XXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XX XXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXX X
    XXX XXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XX XXXXXX X XX X
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXX
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXX
    X XXXX X
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXX
    X
  X
XXXXX
XX XXXXX XX XXXXX XX XXXXXXXX XXXXX XX XXXXXX XXX XX XXXXXX
XXXXXXXXXXX X
  XXX XXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XX XXXXXX X
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX X
      XXXXXXXXXXXXXXXXXXX
      XXX XXXXX X XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XX XXXXXXX XX XXXXX XXX XXXXXXXX XXXX XX XXXXX
      XXX XXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXX XXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XX XXXX XX XXXXX X
        XXXXXXXXXXXXXX X XXXXXXXXXXXXXX
      X
      XXXXXXXXXXXXX
    XXX
  X
XXXXX
XXXXXXXXX
