# Generated by Django 5.1.4 on 2025-05-29 22:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('competitions', '0001_initial'),
        ('grades', '0001_initial'),
        ('multitenant', '0001_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliationrequest',
            name='requesting_organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_affiliation_requests', to='organizations.organization', verbose_name='Organisation demandeuse'),
        ),
        migrations.AddField(
            model_name='affiliationrequest',
            name='target_organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_affiliation_requests', to='organizations.organization', verbose_name='Organisation cible'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='recorded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_attendances', to=settings.AUTH_USER_MODEL, verbose_name='Enregistré par'),
        ),
        migrations.AddField(
            model_name='categoryranking',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_rankings', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AddField(
            model_name='categorytemplate',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_category_templates', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AddField(
            model_name='certificationregistration',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_certification_registrations', to=settings.AUTH_USER_MODEL, verbose_name='Examiné par'),
        ),
        migrations.AddField(
            model_name='certificationregistration',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certification_registrations', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AddField(
            model_name='club',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legacy_clubs', to='organizations.organization', verbose_name='Organisation associée'),
        ),
        migrations.AddField(
            model_name='club',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_clubs', to=settings.AUTH_USER_MODEL, verbose_name='Propriétaire'),
        ),
        migrations.AddField(
            model_name='club',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='migrated_clubs', to='multitenant.tenant', verbose_name='Tenant associé'),
        ),
        migrations.AddField(
            model_name='clubadministrator',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='administrators', to='competitions.club', verbose_name='Club'),
        ),
        migrations.AddField(
            model_name='clubadministrator',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='club_administrators', to='organizations.organization', verbose_name='Organisation'),
        ),
        migrations.AddField(
            model_name='clubadministrator',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club_admin_roles', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AddField(
            model_name='clubrole',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='clubteam',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teams', to='competitions.club', verbose_name='Club (obsolète)'),
        ),
        migrations.AddField(
            model_name='clubteam',
            name='members',
            field=models.ManyToManyField(related_name='team_memberships', to=settings.AUTH_USER_MODEL, verbose_name='Membres'),
        ),
        migrations.AddField(
            model_name='clubteam',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club_teams', to='organizations.organization', verbose_name='Organisation'),
        ),
        migrations.AddField(
            model_name='coachprofile',
            name='primary_teaching_place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_coaches', to='competitions.club', verbose_name='Club référencé (interne)'),
        ),
        migrations.AddField(
            model_name='coachachievement',
            name='coach_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='competitions.coachprofile', verbose_name='Profil coach'),
        ),
        migrations.AddField(
            model_name='actioncombat',
            name='combat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='competitions.combat', verbose_name='Combat'),
        ),
        migrations.AddField(
            model_name='combat',
            name='configuration',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='combats', to='competitions.combatconfiguration', verbose_name='Configuration'),
        ),
        migrations.AddField(
            model_name='competition',
            name='organizing_organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organized_competitions', to='organizations.organization', verbose_name='Organisation organisatrice'),
        ),
        migrations.AddField(
            model_name='combat',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combats', to='competitions.competition', verbose_name='Compétition'),
        ),
        migrations.AddField(
            model_name='clubteam',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competition_teams', to='competitions.competition', verbose_name='Compétition'),
        ),
        migrations.AddField(
            model_name='categoryranking',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_rankings', to='competitions.competition', verbose_name='Compétition'),
        ),
        migrations.AddField(
            model_name='competitioncategory',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='competitions.competition'),
        ),
        migrations.AddField(
            model_name='competitioncategory',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_in_competitions', to='competitions.categorytemplate', verbose_name='Template source'),
        ),
        migrations.AddField(
            model_name='categoryschedule',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='competitions.competitioncategory', verbose_name='Catégorie'),
        ),
        migrations.AddField(
            model_name='categoryranking',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_rankings', to='competitions.competitioncategory', verbose_name='Catégorie'),
        ),
        migrations.AddField(
            model_name='competitionranking',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rankings', to='competitions.competitioncategory', verbose_name='Catégorie'),
        ),
        migrations.AddField(
            model_name='competitionranking',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rankings', to='competitions.competition', verbose_name='Compétition'),
        ),
        migrations.AddField(
            model_name='competitionregistration',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='registrations', to='competitions.competitioncategory'),
        ),
        migrations.AddField(
            model_name='competitionregistration',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='competitions.competition'),
        ),
        migrations.AddField(
            model_name='competitionresult',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='results', to='competitions.competitioncategory', verbose_name='Catégorie'),
        ),
        migrations.AddField(
            model_name='competitionresult',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='competitions.competition', verbose_name='Compétition'),
        ),
        migrations.AddField(
            model_name='competitionrole',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='competitions.competition'),
        ),
        migrations.AddField(
            model_name='competitionregistration',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='registrations', to='competitions.competitionrole'),
        ),
        migrations.AddField(
            model_name='competitionschedule',
            name='competition',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='competitions.competition', verbose_name='Compétition'),
        ),
        migrations.AddField(
            model_name='competitionschedule',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_schedules', to=settings.AUTH_USER_MODEL, verbose_name='Mis à jour par'),
        ),
        migrations.AddField(
            model_name='categoryschedule',
            name='competition_schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_schedules', to='competitions.competitionschedule', verbose_name='Planning de compétition'),
        ),
        migrations.AddField(
            model_name='competitionregistration',
            name='competition_types',
            field=models.ManyToManyField(blank=True, related_name='registrations', to='competitions.competitiontype'),
        ),
        migrations.AddField(
            model_name='competitioncategory',
            name='competition_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='competitions.competitiontype'),
        ),
        migrations.AddField(
            model_name='competition',
            name='competition_types',
            field=models.ManyToManyField(related_name='competitions', to='competitions.competitiontype'),
        ),
        migrations.AddField(
            model_name='categorytemplate',
            name='competition_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_templates', to='competitions.competitiontype', verbose_name='Type de compétition'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_conversations', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='organizations.organization', verbose_name='Organisation'),
        ),
        migrations.AddField(
            model_name='conversationparticipant',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competitions.conversation', verbose_name='Conversation'),
        ),
        migrations.AddField(
            model_name='conversationparticipant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='participants',
            field=models.ManyToManyField(related_name='conversations', through='competitions.ConversationParticipant', to=settings.AUTH_USER_MODEL, verbose_name='Participants'),
        ),
        migrations.AddField(
            model_name='discipline',
            name='grading_system',
            field=models.ForeignKey(blank=True, help_text='Configuration du système de grades pour cette discipline', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disciplines', to='grades.gradingsystem', verbose_name='Système de grade'),
        ),
        migrations.AddField(
            model_name='discipline',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_disciplines', to='organizations.organization', verbose_name='Fédération principale'),
        ),
        migrations.AddField(
            model_name='competitiontype',
            name='discipline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competition_types', to='competitions.discipline'),
        ),
        migrations.AddField(
            model_name='competition',
            name='discipline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='competitions', to='competitions.discipline', verbose_name='Discipline'),
        ),
        migrations.AddField(
            model_name='combatconfiguration',
            name='discipline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combat_configurations', to='competitions.discipline', verbose_name='Discipline'),
        ),
        migrations.AddField(
            model_name='coachachievement',
            name='discipline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='competitions.discipline', verbose_name='Discipline concernée'),
        ),
        migrations.AddField(
            model_name='club',
            name='disciplines',
            field=models.ManyToManyField(blank=True, related_name='club_disciplines', to='competitions.discipline', verbose_name='Disciplines'),
        ),
        migrations.AddField(
            model_name='club',
            name='main_discipline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_clubs', to='competitions.discipline', verbose_name='Discipline principale'),
        ),
        migrations.AddField(
            model_name='categorytemplate',
            name='discipline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_templates', to='competitions.discipline', verbose_name='Discipline'),
        ),
        migrations.AddField(
            model_name='disciplineexpertise',
            name='coach_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discipline_expertises', to='competitions.coachprofile', verbose_name='Profil coach'),
        ),
        migrations.AddField(
            model_name='disciplineexpertise',
            name='discipline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competitions.discipline', verbose_name='Discipline'),
        ),
        migrations.AddField(
            model_name='equipe',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipes_combat', to='competitions.club', verbose_name='Club'),
        ),
        migrations.AddField(
            model_name='equipe',
            name='coach',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipes_coachees', to=settings.AUTH_USER_MODEL, verbose_name='Coach'),
        ),
        migrations.AddField(
            model_name='equipe',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipes_combat', to='competitions.competition', verbose_name='Compétition'),
        ),
        migrations.AddField(
            model_name='combat',
            name='equipe_blanc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='combats_blanc', to='competitions.equipe', verbose_name='Équipe blanc'),
        ),
        migrations.AddField(
            model_name='combat',
            name='equipe_rouge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='combats_rouge', to='competitions.equipe', verbose_name='Équipe rouge'),
        ),
        migrations.AddField(
            model_name='event',
            name='contact_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organized_events', to=settings.AUTH_USER_MODEL, verbose_name='Personne de contact'),
        ),
        migrations.AddField(
            model_name='event',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_events', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AddField(
            model_name='event',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='organizations.organization', verbose_name='Organisation'),
        ),
        migrations.AddField(
            model_name='eventfeedback',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_feedbacks', to='competitions.event', verbose_name='Événement'),
        ),
        migrations.AddField(
            model_name='eventfeedback',
            name='submitted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_feedbacks', to=settings.AUTH_USER_MODEL, verbose_name='Soumis par'),
        ),
        migrations.AddField(
            model_name='eventparticipant',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='competitions.event', verbose_name='Événement'),
        ),
        migrations.AddField(
            model_name='eventparticipant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_participations', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AddField(
            model_name='eventpoll',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_polls', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AddField(
            model_name='eventpoll',
            name='event',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='poll', to='competitions.event', verbose_name='Événement associé'),
        ),
        migrations.AddField(
            model_name='eventpoll',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_polls', to='organizations.organization', verbose_name='Organisation'),
        ),
        migrations.AddField(
            model_name='eventreminder',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_reminders', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AddField(
            model_name='eventreminder',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='competitions.event', verbose_name='Événement'),
        ),
        migrations.AddField(
            model_name='eventreminder',
            name='recipients',
            field=models.ManyToManyField(blank=True, help_text='Destinataires spécifiques (vide = tous les participants)', related_name='event_reminders', to=settings.AUTH_USER_MODEL, verbose_name='Destinataires'),
        ),
        migrations.AddField(
            model_name='eventstatistics',
            name='event',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='competitions.event', verbose_name='Événement'),
        ),
        migrations.AddField(
            model_name='eventstatistics',
            name='poll',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='competitions.eventpoll', verbose_name='Sondage'),
        ),
        migrations.AddField(
            model_name='eventsurvey',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_surveys', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AddField(
            model_name='eventsurvey',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surveys', to='competitions.event', verbose_name='Événement'),
        ),
        migrations.AddField(
            model_name='federation',
            name='disciplines',
            field=models.ManyToManyField(blank=True, related_name='federation_disciplines', to='competitions.discipline', verbose_name='Disciplines'),
        ),
        migrations.AddField(
            model_name='federation',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legacy_federations', to='organizations.organization', verbose_name='Organisation associée'),
        ),
        migrations.AddField(
            model_name='federation',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_federations', to=settings.AUTH_USER_MODEL, verbose_name='Propriétaire (déprécié)'),
        ),
        migrations.AddField(
            model_name='disciplineexpertise',
            name='federation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='competitions.federation', verbose_name='Fédération affiliée'),
        ),
        migrations.AddField(
            model_name='federationadministrator',
            name='federation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='administrators', to='competitions.federation', verbose_name='Fédération'),
        ),
        migrations.AddField(
            model_name='federationadministrator',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='federation_administrators', to='organizations.organization', verbose_name='Organisation'),
        ),
        migrations.AddField(
            model_name='federationadministrator',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='federation_admin_roles', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AddField(
            model_name='judge',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certified_judges', to='organizations.organization', verbose_name='Fédération certifiante'),
        ),
        migrations.AddField(
            model_name='judge',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='judge_profile', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AddField(
            model_name='combat',
            name='arbitre_central',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='combats_arbitre_central', to='competitions.judge', verbose_name='Arbitre central'),
        ),
        migrations.AddField(
            model_name='combat',
            name='arbitres_lateraux',
            field=models.ManyToManyField(blank=True, related_name='combats_arbitre_lateral', to='competitions.judge', verbose_name='Arbitres latéraux'),
        ),
        migrations.AddField(
            model_name='actioncombat',
            name='arbitre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions_combat', to='competitions.judge', verbose_name='Arbitre'),
        ),
        migrations.AddField(
            model_name='judgeapplication',
            name='disciplines',
            field=models.ManyToManyField(related_name='judge_applications', to='competitions.discipline'),
        ),
        migrations.AddField(
            model_name='judgeapplication',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='judgeapplication',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='judgeassignment',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='judge_assignments_made', to=settings.AUTH_USER_MODEL, verbose_name='Assigné par'),
        ),
        migrations.AddField(
            model_name='judgeassignment',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='judge_assignments', to='competitions.competitioncategory', verbose_name='Catégorie'),
        ),
        migrations.AddField(
            model_name='judgeassignment',
            name='chief_judge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chief_judge_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Juge en chef'),
        ),
        migrations.AddField(
            model_name='judgeassignment',
            name='registration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='judge_assignments', to='competitions.competitionregistration', verbose_name='Inscription'),
        ),
        migrations.AddField(
            model_name='judgeassignment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='judge_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AddField(
            model_name='judgecertification',
            name='discipline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='competitions.discipline', verbose_name='Discipline'),
        ),
        migrations.AddField(
            model_name='judgecertification',
            name='examiner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='examiner_certifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='judgecertification',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='judge_certifications', to='organizations.organization', verbose_name='Organisation'),
        ),
        migrations.AddField(
            model_name='certificationregistration',
            name='certification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='competitions.judgecertification', verbose_name='Certification'),
        ),
        migrations.AddField(
            model_name='judgecompetitionassignment',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competition_judge_assignments', to='competitions.competitioncategory'),
        ),
        migrations.AddField(
            model_name='judgecompetitionassignment',
            name='registration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='competitions.competitionregistration'),
        ),
        migrations.AddField(
            model_name='judgequalification',
            name='discipline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='judge_qualifications', to='competitions.discipline', verbose_name='Discipline'),
        ),
        migrations.AddField(
            model_name='judgequalification',
            name='issuing_organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_qualifications', to='organizations.organization', verbose_name='Fédération émettrice'),
        ),
        migrations.AddField(
            model_name='judgesettings',
            name='judge',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='competitions.judge'),
        ),
        migrations.AddField(
            model_name='judgesubmissionstatus',
            name='judge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competitions.judge'),
        ),
        migrations.AddField(
            model_name='judgesubmissionstatusresult',
            name='judge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submission_status_results', to=settings.AUTH_USER_MODEL, verbose_name='Juge'),
        ),
        migrations.AddField(
            model_name='judgetechnicalapplication',
            name='disciplines',
            field=models.ManyToManyField(related_name='judge_technical_applications', to='competitions.discipline', verbose_name='Disciplines'),
        ),
        migrations.AddField(
            model_name='judgetechnicalapplication',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_judge_applications', to=settings.AUTH_USER_MODEL, verbose_name='Examiné par'),
        ),
        migrations.AddField(
            model_name='judgetechnicalapplication',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technical_judge_applications', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AddField(
            model_name='judgetraining',
            name='disciplines',
            field=models.ManyToManyField(related_name='judge_trainings', to='competitions.discipline', verbose_name='Disciplines'),
        ),
        migrations.AddField(
            model_name='judgetraining',
            name='federation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='judge_trainings', to='competitions.federation', verbose_name='Fédération'),
        ),
        migrations.AddField(
            model_name='judgetraining',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taught_trainings', to=settings.AUTH_USER_MODEL, verbose_name='Formateur'),
        ),
        migrations.AddField(
            model_name='judgetrainingregistration',
            name='judge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_registrations', to='competitions.judge'),
        ),
        migrations.AddField(
            model_name='judgetrainingregistration',
            name='training',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='competitions.judgetraining'),
        ),
        migrations.AddField(
            model_name='license',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issued_licenses', to='organizations.organization', verbose_name='Fédération'),
        ),
        migrations.AddField(
            model_name='match',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='competitions.competition'),
        ),
        migrations.AddField(
            model_name='matchtimeslot',
            name='category_schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='competitions.categoryschedule', verbose_name='Planning de catégorie'),
        ),
        migrations.AddField(
            model_name='matchtimeslot',
            name='match',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='time_slot', to='competitions.match', verbose_name='Match'),
        ),
        migrations.AddField(
            model_name='membership',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_memberships', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AddField(
            model_name='membership',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='member_subscriptions', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='membreequipe',
            name='equipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='competitions.equipe', verbose_name='Équipe'),
        ),
        migrations.AddField(
            model_name='message',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='competitions.conversation', verbose_name='Conversation'),
        ),
        migrations.AddField(
            model_name='message',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='competitions.message', verbose_name='Réponse à'),
        ),
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_messages', to=settings.AUTH_USER_MODEL, verbose_name='Expéditeur'),
        ),
        migrations.AddField(
            model_name='messagereaction',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='competitions.message', verbose_name='Message'),
        ),
        migrations.AddField(
            model_name='messagereaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AddField(
            model_name='messageread',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_by', to='competitions.message', verbose_name='Message'),
        ),
        migrations.AddField(
            model_name='messageread',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AddField(
            model_name='messagetemplate',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_message_templates', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AddField(
            model_name='messagetemplate',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_templates', to='organizations.organization', verbose_name='Organisation'),
        ),
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organizationqrcode',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qr_codes', to='competitions.club', verbose_name='Club'),
        ),
        migrations.AddField(
            model_name='organizationqrcode',
            name='coach_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qr_codes', to='competitions.coachprofile', verbose_name='Coach'),
        ),
        migrations.AddField(
            model_name='organizationqrcode',
            name='federation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qr_codes', to='competitions.federation', verbose_name='Fédération'),
        ),
    ]
