# Generated by Django 5.1.4 on 2025-05-29 22:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('competitions', '0002_initial'),
        ('finances', '0001_initial'),
        ('grades', '0001_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationqrcodescan',
            name='payment_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qr_scans', to='finances.transaction', verbose_name='Transaction de paiement'),
        ),
        migrations.AddField(
            model_name='organizationqrcodescan',
            name='qr_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='competitions.organizationqrcode', verbose_name='Code QR'),
        ),
        migrations.AddField(
            model_name='organizationqrcodescan',
            name='scanned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organization_qr_scans', to=settings.AUTH_USER_MODEL, verbose_name='Scanné par'),
        ),
        migrations.AddField(
            model_name='organizationqrcodescan',
            name='user_created',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qr_registrations', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur créé'),
        ),
        migrations.AddField(
            model_name='participantcategoryregistration',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competitions.competitioncategory'),
        ),
        migrations.AddField(
            model_name='participantcategoryregistration',
            name='competition_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competitions.competitiontype'),
        ),
        migrations.AddField(
            model_name='participantcategoryregistration',
            name='registration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_registrations', to='competitions.competitionregistration'),
        ),
        migrations.AddField(
            model_name='performance',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performances', to='competitions.competitioncategory'),
        ),
        migrations.AddField(
            model_name='judgesubmissionstatus',
            name='performance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competitions.performance'),
        ),
        migrations.AddField(
            model_name='performanceresult',
            name='validated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_results', to=settings.AUTH_USER_MODEL, verbose_name='Validé par'),
        ),
        migrations.AddField(
            model_name='polloption',
            name='poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='competitions.eventpoll', verbose_name='Sondage'),
        ),
        migrations.AddField(
            model_name='pollquestion',
            name='poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_questions', to='competitions.eventpoll', verbose_name='Sondage'),
        ),
        migrations.AddField(
            model_name='pollquestionresponse',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='competitions.pollquestion', verbose_name='Question'),
        ),
        migrations.AddField(
            model_name='pollquestionresponse',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poll_question_responses', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AddField(
            model_name='pollresponse',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='competitions.polloption', verbose_name='Option'),
        ),
        migrations.AddField(
            model_name='pollresponse',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poll_responses', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AddField(
            model_name='poule',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poules', to='competitions.competition', verbose_name='Compétition'),
        ),
        migrations.AddField(
            model_name='poule',
            name='equipes',
            field=models.ManyToManyField(blank=True, related_name='poules', to='competitions.equipe', verbose_name='Équipes'),
        ),
        migrations.AddField(
            model_name='combat',
            name='poule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='combats', to='competitions.poule', verbose_name='Poule'),
        ),
        migrations.AddField(
            model_name='practitioner',
            name='disciplines',
            field=models.ManyToManyField(blank=True, related_name='practitioners', to='competitions.discipline', verbose_name='Disciplines pratiquées'),
        ),
        migrations.AddField(
            model_name='practitioner',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='practitioner_current_grades', to='grades.grade', verbose_name='Grade actuel'),
        ),
        migrations.AddField(
            model_name='practitioner',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='practitioners', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='practitioner',
            name='primary_discipline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_practitioners', to='competitions.discipline', verbose_name='Discipline principale'),
        ),
        migrations.AddField(
            model_name='practitioner',
            name='secondary_disciplines',
            field=models.ManyToManyField(blank=True, related_name='secondary_practitioners', to='competitions.discipline', verbose_name='Disciplines secondaires'),
        ),
        migrations.AddField(
            model_name='practitioner',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='practitioners', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='poule',
            name='pratiquants',
            field=models.ManyToManyField(blank=True, related_name='poules_individuelles', to='competitions.practitioner', verbose_name='Pratiquants individuels'),
        ),
        migrations.AddField(
            model_name='personalgoal',
            name='practitioner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_goals', to='competitions.practitioner', verbose_name='Pratiquant'),
        ),
        migrations.AddField(
            model_name='performance',
            name='practitioner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performances', to='competitions.practitioner'),
        ),
        migrations.AddField(
            model_name='organizationqrcodescan',
            name='practitioner_created',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qr_registrations', to='competitions.practitioner', verbose_name='Pratiquant créé'),
        ),
        migrations.AddField(
            model_name='membreequipe',
            name='pratiquant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipe_memberships', to='competitions.practitioner', verbose_name='Pratiquant'),
        ),
        migrations.AddField(
            model_name='membership',
            name='practitioner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='competitions.practitioner'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='practitioner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medical_record', to='competitions.practitioner'),
        ),
        migrations.AddField(
            model_name='medicalcertificate',
            name='practitioner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_certificates', to='competitions.practitioner'),
        ),
        migrations.AddField(
            model_name='match',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='matches', to='competitions.practitioner'),
        ),
        migrations.AddField(
            model_name='license',
            name='practitioner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licenses', to='competitions.practitioner'),
        ),
        migrations.AddField(
            model_name='judgequalification',
            name='practitioner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualifications', to='competitions.practitioner', verbose_name='Pratiquant'),
        ),
        migrations.AddField(
            model_name='judge',
            name='practitioner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='judge', to='competitions.practitioner', verbose_name='Pratiquant'),
        ),
        migrations.AddField(
            model_name='equipe',
            name='membres',
            field=models.ManyToManyField(related_name='equipes_combat', through='competitions.MembreEquipe', to='competitions.practitioner', verbose_name='Membres'),
        ),
        migrations.AddField(
            model_name='competitionresult',
            name='practitioner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competition_results', to='competitions.practitioner', verbose_name='Pratiquant'),
        ),
        migrations.AddField(
            model_name='competitionregistration',
            name='practitioner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='competitions.practitioner'),
        ),
        migrations.AddField(
            model_name='competitionranking',
            name='practitioner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rankings', to='competitions.practitioner', verbose_name='Pratiquant'),
        ),
        migrations.AddField(
            model_name='combat',
            name='pratiquant_blanc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='combats_blanc', to='competitions.practitioner', verbose_name='Pratiquant blanc'),
        ),
        migrations.AddField(
            model_name='combat',
            name='pratiquant_rouge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='combats_rouge', to='competitions.practitioner', verbose_name='Pratiquant rouge'),
        ),
        migrations.AddField(
            model_name='coachprofile',
            name='practitioner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coach_profile', to='competitions.practitioner', verbose_name='Pratiquant'),
        ),
        migrations.AddField(
            model_name='certificationregistration',
            name='practitioner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cert_registrations', to='competitions.practitioner'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='practitioner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='competitions.practitioner', verbose_name='Pratiquant'),
        ),
        migrations.AddField(
            model_name='practitionerdiscipline',
            name='discipline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discipline_practitioners', to='competitions.discipline'),
        ),
        migrations.AddField(
            model_name='practitionerdiscipline',
            name='practitioner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practitioner_disciplines', to='competitions.practitioner'),
        ),
        migrations.AddField(
            model_name='practitionerdiscipline',
            name='reference_instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to=settings.AUTH_USER_MODEL, verbose_name='Instructeur référent'),
        ),
        migrations.AddField(
            model_name='practitionerprogress',
            name='practitioner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_progress', to='competitions.practitioner', verbose_name='Pratiquant'),
        ),
        migrations.AddField(
            model_name='practitionerqrcode',
            name='practitioner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qr_code', to='competitions.practitioner', verbose_name='Pratiquant'),
        ),
        migrations.AddField(
            model_name='practitionerqualification',
            name='certified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certified_qualifications', to=settings.AUTH_USER_MODEL, verbose_name='Certifié par'),
        ),
        migrations.AddField(
            model_name='practitionerqualification',
            name='discipline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualifications', to='competitions.discipline', verbose_name='Discipline'),
        ),
        migrations.AddField(
            model_name='practitionerqualification',
            name='practitioner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practitioner_qualifications', to='competitions.practitioner'),
        ),
        migrations.AddField(
            model_name='programenrollment',
            name='practitioner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_enrollments', to='competitions.practitioner', verbose_name='Pratiquant'),
        ),
        migrations.AddField(
            model_name='qrcodescan',
            name='competition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qr_scans', to='competitions.competition', verbose_name='Compétition'),
        ),
        migrations.AddField(
            model_name='qrcodescan',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qr_scans', to='competitions.event', verbose_name='Événement'),
        ),
        migrations.AddField(
            model_name='qrcodescan',
            name='qr_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='competitions.practitionerqrcode', verbose_name='QR Code'),
        ),
        migrations.AddField(
            model_name='qrcodescan',
            name='scanned_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qr_scans_performed', to=settings.AUTH_USER_MODEL, verbose_name='Scanné par'),
        ),
        migrations.AddField(
            model_name='rankingentry',
            name='practitioner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranking_entries', to='competitions.practitioner', verbose_name='Pratiquant'),
        ),
        migrations.AddField(
            model_name='rankingentry',
            name='ranking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='competitions.categoryranking', verbose_name='Classement'),
        ),
        migrations.AddField(
            model_name='referrallink',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referral_links', to='competitions.club', verbose_name='Club'),
        ),
        migrations.AddField(
            model_name='referrallink',
            name='federation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referral_links', to='competitions.federation', verbose_name='Fédération'),
        ),
        migrations.AddField(
            model_name='referrallink',
            name='referrer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_links', to=settings.AUTH_USER_MODEL, verbose_name='Parrain'),
        ),
        migrations.AddField(
            model_name='referraluse',
            name='payment_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referral_uses', to='finances.transaction', verbose_name='Transaction de paiement'),
        ),
        migrations.AddField(
            model_name='referraluse',
            name='practitioner_created',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referral_signups', to='competitions.practitioner', verbose_name='Pratiquant créé'),
        ),
        migrations.AddField(
            model_name='referraluse',
            name='referral_link',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uses', to='competitions.referrallink', verbose_name='Lien de parrainage'),
        ),
        migrations.AddField(
            model_name='referraluse',
            name='referred_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_signups', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur parrainé'),
        ),
        migrations.AddField(
            model_name='schedulechange',
            name='category_schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='changes', to='competitions.categoryschedule', verbose_name='Planning de catégorie'),
        ),
        migrations.AddField(
            model_name='schedulechange',
            name='changed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_changes', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par'),
        ),
        migrations.AddField(
            model_name='schedulechange',
            name='competition_schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='competitions.competitionschedule', verbose_name='Planning'),
        ),
        migrations.AddField(
            model_name='score',
            name='judge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='competitions.judge'),
        ),
        migrations.AddField(
            model_name='score',
            name='performance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='competitions.performance'),
        ),
        migrations.AddField(
            model_name='scoringconfiguration',
            name='category',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scoring_configuration', to='competitions.competitioncategory', verbose_name='Catégorie'),
        ),
        migrations.AddField(
            model_name='scoringcriterion',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scoring_criteria', to='competitions.competitioncategory'),
        ),
        migrations.AddField(
            model_name='score',
            name='criterion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_scores', to='competitions.scoringcriterion'),
        ),
        migrations.AddField(
            model_name='standalonejudgesubmission',
            name='performance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standalone_judge_submissions', to='competitions.standaloneperformance'),
        ),
        migrations.AddField(
            model_name='standalonecompetitionranking',
            name='performance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='standalone_rankings', to='competitions.standaloneperformance'),
        ),
        migrations.AddField(
            model_name='standalonerankingsnapshotentry',
            name='snapshot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='competitions.standalonecategoryrankingsnapshot'),
        ),
        migrations.AddField(
            model_name='standalonescore',
            name='performance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standalone_scores', to='competitions.standaloneperformance'),
        ),
        migrations.AddField(
            model_name='standalonescore',
            name='criterion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standalone_scores', to='competitions.standalonescoringcriterion'),
        ),
        migrations.AddField(
            model_name='standalonescoringcriterion',
            name='scoring_system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standalone_criteria', to='competitions.standalonescoringsystem'),
        ),
        migrations.AddField(
            model_name='standalonecategoryscoringconfig',
            name='scoring_system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standalone_category_configs', to='competitions.standalonescoringsystem'),
        ),
        migrations.AddField(
            model_name='style',
            name='discipline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='styles', to='competitions.discipline', verbose_name='Discipline'),
        ),
        migrations.AddField(
            model_name='supportmessage',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Expéditeur'),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL, verbose_name='Assigné à'),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_tickets', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AddField(
            model_name='supportmessage',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='competitions.supportticket', verbose_name='Ticket'),
        ),
        migrations.AddField(
            model_name='surveyquestion',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='competitions.eventsurvey', verbose_name='Sondage'),
        ),
        migrations.AddField(
            model_name='questionresponse',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='competitions.surveyquestion', verbose_name='Question'),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='participant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='survey_responses', to=settings.AUTH_USER_MODEL, verbose_name='Participant'),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='competitions.eventsurvey', verbose_name='Sondage'),
        ),
        migrations.AddField(
            model_name='questionresponse',
            name='response',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_responses', to='competitions.surveyresponse', verbose_name='Réponse au sondage'),
        ),
        migrations.AddField(
            model_name='tatamischedule',
            name='competition_schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tatami_schedules', to='competitions.competitionschedule', verbose_name='Planning de compétition'),
        ),
        migrations.AddField(
            model_name='tatamischedule',
            name='responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_for_tatamis', to=settings.AUTH_USER_MODEL, verbose_name='Responsable'),
        ),
        migrations.AddField(
            model_name='categoryschedule',
            name='tatami',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_schedules', to='competitions.tatamischedule', verbose_name='Tatami'),
        ),
        migrations.AddField(
            model_name='teachingschedule',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competitions.club', verbose_name='Club'),
        ),
        migrations.AddField(
            model_name='teachingschedule',
            name='coach_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_schedules', to='competitions.coachprofile', verbose_name='Profil coach'),
        ),
        migrations.AddField(
            model_name='teachingschedule',
            name='discipline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competitions.discipline', verbose_name='Discipline'),
        ),
        migrations.AddField(
            model_name='technicalperformance',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technical_performances', to='competitions.competitioncategory', verbose_name='Catégorie'),
        ),
        migrations.AddField(
            model_name='technicalperformance',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technical_performances', to='competitions.competition', verbose_name='Compétition'),
        ),
        migrations.AddField(
            model_name='technicalperformance',
            name='practitioner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technical_performances', to='competitions.practitioner', verbose_name='Pratiquant'),
        ),
        migrations.AddField(
            model_name='technicalperformanceresult',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_results', to='competitions.competitioncategory', verbose_name='Catégorie'),
        ),
        migrations.AddField(
            model_name='technicalperformanceresult',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technical_performance_results', to='competitions.competition', verbose_name='Compétition'),
        ),
        migrations.AddField(
            model_name='technicalperformanceresult',
            name='practitioner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technical_performance_results', to='competitions.practitioner', verbose_name='Pratiquant'),
        ),
        migrations.AddField(
            model_name='rankingentry',
            name='performance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ranking_entries', to='competitions.technicalperformanceresult', verbose_name='Performance'),
        ),
        migrations.AddField(
            model_name='performanceresult',
            name='performance',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='competitions.technicalperformanceresult', verbose_name='Performance'),
        ),
        migrations.AddField(
            model_name='judgesubmissionstatusresult',
            name='performance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submission_statuses', to='competitions.technicalperformanceresult', verbose_name='Performance'),
        ),
        migrations.AddField(
            model_name='technicalscore',
            name='criterion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technical_scores', to='competitions.scoringcriterion', verbose_name='Critère'),
        ),
        migrations.AddField(
            model_name='technicalscore',
            name='judge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technical_scores', to=settings.AUTH_USER_MODEL, verbose_name='Juge'),
        ),
        migrations.AddField(
            model_name='technicalscore',
            name='performance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='competitions.technicalperformance', verbose_name='Prestation'),
        ),
        migrations.AddField(
            model_name='technicalscoreresult',
            name='criterion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_results', to='competitions.scoringcriterion', verbose_name='Critère'),
        ),
        migrations.AddField(
            model_name='technicalscoreresult',
            name='judge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technical_score_results', to=settings.AUTH_USER_MODEL, verbose_name='Juge'),
        ),
        migrations.AddField(
            model_name='technicalscoreresult',
            name='performance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technical_scores', to='competitions.technicalperformanceresult', verbose_name='Performance'),
        ),
        migrations.AddField(
            model_name='technique',
            name='discipline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='techniques', to='competitions.discipline', verbose_name='Discipline'),
        ),
        migrations.AddField(
            model_name='technique',
            name='minimum_grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='required_techniques', to='grades.grade', verbose_name='Grade minimum requis'),
        ),
        migrations.AddField(
            model_name='practitionerprogress',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practitioner_progress', to='competitions.trainingexercise', verbose_name='Exercice'),
        ),
        migrations.AddField(
            model_name='trainingexercise',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='competitions.trainingmodule', verbose_name='Module'),
        ),
        migrations.AddField(
            model_name='trainingprogram',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_training_programs', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AddField(
            model_name='trainingprogram',
            name='disciplines',
            field=models.ManyToManyField(related_name='training_programs', to='competitions.discipline', verbose_name='Disciplines'),
        ),
        migrations.AddField(
            model_name='trainingmodule',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='competitions.trainingprogram', verbose_name='Programme'),
        ),
        migrations.AddField(
            model_name='programenrollment',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='competitions.trainingprogram', verbose_name='Programme'),
        ),
        migrations.AddField(
            model_name='trainingreservation',
            name='practitioner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_reservations', to='competitions.practitioner', verbose_name='Pratiquant'),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='actual_instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Instructeur réel'),
        ),
        migrations.AddField(
            model_name='qrcodescan',
            name='training_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qr_scans', to='competitions.trainingsession', verbose_name="Session d'entraînement"),
        ),
        migrations.AddField(
            model_name='attendance',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='competitions.trainingsession', verbose_name='Session'),
        ),
        migrations.AddField(
            model_name='trainingslot',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_slots', to='competitions.club', verbose_name='Club'),
        ),
        migrations.AddField(
            model_name='trainingslot',
            name='discipline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_slots', to='competitions.discipline', verbose_name='Discipline'),
        ),
        migrations.AddField(
            model_name='trainingslot',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_slots', to=settings.AUTH_USER_MODEL, verbose_name='Instructeur'),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='training_slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='competitions.trainingslot', verbose_name='Créneau'),
        ),
        migrations.AddField(
            model_name='trainingreservation',
            name='training_slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='competitions.trainingslot', verbose_name='Créneau'),
        ),
        migrations.AddField(
            model_name='userclubrole',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_roles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userclubrole',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='userclubrole',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='competitions.clubrole'),
        ),
        migrations.AddField(
            model_name='userclubrole',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_profiles', to='competitions.club', verbose_name='Organisation'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='clubadministrator',
            unique_together={('user', 'club'), ('user', 'organization')},
        ),
        migrations.AlterUniqueTogether(
            name='clubrole',
            unique_together={('name', 'organization')},
        ),
        migrations.AlterUniqueTogether(
            name='categoryranking',
            unique_together={('category', 'competition')},
        ),
        migrations.AlterUniqueTogether(
            name='competitionrole',
            unique_together={('competition', 'name')},
        ),
        migrations.AddConstraint(
            model_name='competitioncategory',
            constraint=models.UniqueConstraint(fields=('competition', 'name'), name='unique_category_per_competition'),
        ),
        migrations.AlterUniqueTogether(
            name='conversationparticipant',
            unique_together={('conversation', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='categorytemplate',
            unique_together={('discipline', 'competition_type', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='eventfeedback',
            unique_together={('event', 'submitted_by')},
        ),
        migrations.AlterUniqueTogether(
            name='eventparticipant',
            unique_together={('event', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='disciplineexpertise',
            unique_together={('coach_profile', 'discipline')},
        ),
        migrations.AlterUniqueTogether(
            name='federationadministrator',
            unique_together={('user', 'federation'), ('user', 'organization')},
        ),
        migrations.AlterUniqueTogether(
            name='judgeassignment',
            unique_together={('registration', 'category', 'assignment_type')},
        ),
        migrations.AlterUniqueTogether(
            name='judgecompetitionassignment',
            unique_together={('registration', 'category', 'assignment_type')},
        ),
        migrations.AlterUniqueTogether(
            name='judgetrainingregistration',
            unique_together={('judge', 'training')},
        ),
        migrations.AlterUniqueTogether(
            name='messagereaction',
            unique_together={('message', 'user', 'emoji')},
        ),
        migrations.AlterUniqueTogether(
            name='messageread',
            unique_together={('message', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='participantcategoryregistration',
            unique_together={('registration', 'competition_type')},
        ),
        migrations.AlterUniqueTogether(
            name='judgesubmissionstatus',
            unique_together={('judge', 'performance')},
        ),
        migrations.AlterUniqueTogether(
            name='polloption',
            unique_together={('poll', 'date', 'start_time')},
        ),
        migrations.AlterUniqueTogether(
            name='pollquestion',
            unique_together={('poll', 'order')},
        ),
        migrations.AlterUniqueTogether(
            name='pollquestionresponse',
            unique_together={('question', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='pollresponse',
            unique_together={('option', 'user')},
        ),
        migrations.AddIndex(
            model_name='practitioner',
            index=models.Index(fields=['last_name', 'first_name'], name='competition_last_na_3aca86_idx'),
        ),
        migrations.AddIndex(
            model_name='practitioner',
            index=models.Index(fields=['organization'], name='competition_organiz_e186dc_idx'),
        ),
        migrations.AddIndex(
            model_name='practitioner',
            index=models.Index(fields=['user'], name='competition_user_id_f33065_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='poule',
            unique_together={('competition', 'phase', 'numero')},
        ),
        migrations.AlterUniqueTogether(
            name='membreequipe',
            unique_together={('equipe', 'pratiquant')},
        ),
        migrations.AlterUniqueTogether(
            name='license',
            unique_together={('practitioner', 'license_number', 'organization')},
        ),
        migrations.AlterUniqueTogether(
            name='judgequalification',
            unique_together={('practitioner', 'qualification_type', 'discipline')},
        ),
        migrations.AlterUniqueTogether(
            name='competitionresult',
            unique_together={('competition', 'category', 'practitioner')},
        ),
        migrations.AlterUniqueTogether(
            name='competitionregistration',
            unique_together={('practitioner', 'competition')},
        ),
        migrations.AlterUniqueTogether(
            name='competitionranking',
            unique_together={('competition', 'category', 'practitioner')},
        ),
        migrations.AlterUniqueTogether(
            name='practitionerdiscipline',
            unique_together={('practitioner', 'discipline')},
        ),
        migrations.AlterUniqueTogether(
            name='practitionerqualification',
            unique_together={('practitioner', 'qualification_type', 'discipline')},
        ),
        migrations.AlterUniqueTogether(
            name='score',
            unique_together={('performance', 'judge', 'criterion')},
        ),
        migrations.AlterUniqueTogether(
            name='standalonejudgesubmission',
            unique_together={('performance', 'judge_id')},
        ),
        migrations.AlterUniqueTogether(
            name='standalonecompetitionranking',
            unique_together={('category_id', 'practitioner_id')},
        ),
        migrations.AlterUniqueTogether(
            name='standalonescore',
            unique_together={('performance', 'judge_id', 'criterion')},
        ),
        migrations.AlterUniqueTogether(
            name='style',
            unique_together={('discipline', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='tatamischedule',
            unique_together={('competition_schedule', 'tatami_number')},
        ),
        migrations.AlterUniqueTogether(
            name='technicalperformance',
            unique_together={('competition', 'category', 'practitioner')},
        ),
        migrations.AlterUniqueTogether(
            name='technicalperformanceresult',
            unique_together={('competition', 'category', 'practitioner')},
        ),
        migrations.AlterUniqueTogether(
            name='rankingentry',
            unique_together={('ranking', 'practitioner')},
        ),
        migrations.AlterUniqueTogether(
            name='judgesubmissionstatusresult',
            unique_together={('judge', 'performance')},
        ),
        migrations.AlterUniqueTogether(
            name='technicalscore',
            unique_together={('performance', 'judge', 'criterion')},
        ),
        migrations.AlterUniqueTogether(
            name='technicalscoreresult',
            unique_together={('performance', 'judge', 'criterion')},
        ),
        migrations.AlterUniqueTogether(
            name='technique',
            unique_together={('discipline', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='practitionerprogress',
            unique_together={('practitioner', 'exercise')},
        ),
        migrations.AlterUniqueTogether(
            name='programenrollment',
            unique_together={('practitioner', 'program', 'start_date')},
        ),
        migrations.AddIndex(
            model_name='qrcodescan',
            index=models.Index(fields=['qr_code', 'scan_type'], name='competition_qr_code_2318c7_idx'),
        ),
        migrations.AddIndex(
            model_name='qrcodescan',
            index=models.Index(fields=['scan_date'], name='competition_scan_da_8b76ab_idx'),
        ),
        migrations.AddIndex(
            model_name='qrcodescan',
            index=models.Index(fields=['is_offline_scan'], name='competition_is_offl_07674b_idx'),
        ),
        migrations.AddIndex(
            model_name='qrcodescan',
            index=models.Index(fields=['offline_scan_id'], name='competition_offline_b4f93b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('session', 'practitioner')},
        ),
        migrations.AlterUniqueTogether(
            name='trainingslot',
            unique_together={('club', 'day_of_week', 'start_time', 'location')},
        ),
        migrations.AlterUniqueTogether(
            name='trainingsession',
            unique_together={('training_slot', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='trainingreservation',
            unique_together={('practitioner', 'training_slot', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='userclubrole',
            unique_together={('user', 'organization', 'role')},
        ),
    ]
