# Generated by Django 4.2.11 on 2025-05-30 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('family_management', '0001_initial'),
        ('competitions', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='practitioner',
            name='family',
            field=models.ForeignKey(blank=True, help_text='Famille à laquelle appartient ce pratiquant', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='family_practitioners', to='family_management.family', verbose_name='Famille'),
        ),
        migrations.AddField(
            model_name='practitioner',
            name='family_emergency_contact',
            field=models.CharField(blank=True, help_text="Contact d'urgence si différent du responsable familial", max_length=200, verbose_name="Contact d'urgence familial"),
        ),
        migrations.AddField(
            model_name='practitioner',
            name='family_role',
            field=models.CharField(blank=True, choices=[('parent', 'Parent'), ('guardian', 'Tuteur légal'), ('child', 'Enfant'), ('spouse', 'Conjoint(e)'), ('sibling', 'Frère/Sœur'), ('other', 'Autre')], help_text='Rôle de ce pratiquant dans sa famille', max_length=20, verbose_name='Rôle familial'),
        ),
    ]
