# Generated by Django 5.1.4 on 2025-05-14 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0003_create_standalone_scoring'),
        ('competitions', '0003_create_standalone_scoring_fixed'),
        ('competitions', '0003_standalone_scoring'),
    ]

    operations = [
    ]
