# Generated by Django 5.1.4 on 2025-05-15 13:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0004_merge_20250514_2058'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Combat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('type_combat', models.CharField(choices=[('individuel', 'Individuel'), ('equipe', 'Par équipe')], default='individuel', max_length=20, verbose_name='Type de combat')),
                ('status', models.CharField(choices=[('planifie', 'Planifié'), ('en_cours', 'En cours'), ('termine', 'Terminé'), ('annule', 'Annulé')], default='planifie', max_length=20, verbose_name='Statut')),
                ('duree_combat', models.PositiveSmallIntegerField(default=120, verbose_name='Durée du combat (secondes)')),
                ('duree_prolongation', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Durée de prolongation (secondes)')),
                ('score_rouge', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Score rouge')),
                ('score_blanc', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Score blanc')),
                ('vainqueur', models.CharField(blank=True, choices=[('rouge', 'Rouge'), ('blanc', 'Blanc')], max_length=10, null=True, verbose_name='Couleur du vainqueur')),
                ('est_nul', models.BooleanField(default=False, verbose_name='Match nul')),
                ('motif_annulation', models.TextField(blank=True, verbose_name="Motif d'annulation")),
                ('date_planifiee', models.DateTimeField(blank=True, null=True, verbose_name='Date planifiée')),
                ('debut_combat', models.DateTimeField(blank=True, null=True, verbose_name='Début du combat')),
                ('fin_combat', models.DateTimeField(blank=True, null=True, verbose_name='Fin du combat')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('arbitre_central', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='combats_arbitre_central', to='competitions.judge', verbose_name='Arbitre central')),
                ('arbitres_lateraux', models.ManyToManyField(blank=True, related_name='combats_arbitre_lateral', to='competitions.judge', verbose_name='Arbitres latéraux')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combats', to='competitions.competition', verbose_name='Compétition')),
                ('pratiquant_blanc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='combats_blanc', to='competitions.practitioner', verbose_name='Pratiquant blanc')),
                ('pratiquant_rouge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='combats_rouge', to='competitions.practitioner', verbose_name='Pratiquant rouge')),
            ],
            options={
                'verbose_name': 'Combat',
                'verbose_name_plural': 'Combats',
                'ordering': ['competition', 'date_planifiee', 'poule'],
            },
        ),
        migrations.CreateModel(
            name='ActionCombat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_action', models.CharField(choices=[('point', 'Point'), ('penalite', 'Pénalité'), ('avertissement', 'Avertissement'), ('sortie', 'Sortie de tapis'), ('pause', 'Pause'), ('disqualification', 'Disqualification')], max_length=20, verbose_name="Type d'action")),
                ('couleur', models.CharField(choices=[('rouge', 'Rouge'), ('blanc', 'Blanc'), ('neutre', 'Neutre')], default='neutre', max_length=10, verbose_name='Couleur concernée')),
                ('valeur', models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Valeur')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Description')),
                ('temps', models.DateTimeField(auto_now_add=True, verbose_name="Temps de l'action")),
                ('arbitre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions_combat', to='competitions.judge', verbose_name='Arbitre')),
                ('combat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='competitions.combat', verbose_name='Combat')),
            ],
            options={
                'verbose_name': 'Action de combat',
                'verbose_name_plural': 'Actions de combat',
                'ordering': ['combat', 'temps'],
            },
        ),
        migrations.CreateModel(
            name='CombatConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('system', models.CharField(choices=[('qwan_ki_do', 'Qwan Ki Do'), ('karate', 'Karaté'), ('taekwondo', 'Taekwondo'), ('judo', 'Judo'), ('custom', 'Personnalisé')], default='qwan_ki_do', max_length=20, verbose_name='Système de notation')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('durees_combat', models.JSONField(default=list, verbose_name='Durées de combat disponibles (secondes)')),
                ('durees_prolongation', models.JSONField(default=list, verbose_name='Durées de prolongation disponibles (secondes)')),
                ('nb_sorties_avertissement', models.PositiveSmallIntegerField(default=3, verbose_name='Nombre de sorties avant avertissement')),
                ('nb_sorties_disqualification', models.PositiveSmallIntegerField(default=5, verbose_name='Nombre de sorties avant disqualification')),
                ('valeurs_points', models.JSONField(default=list, verbose_name='Valeurs de points disponibles')),
                ('valeurs_penalites', models.JSONField(default=list, verbose_name='Valeurs de pénalités disponibles')),
                ('nb_avertissements_sanction', models.PositiveSmallIntegerField(default=3, verbose_name="Nombre d'avertissements avant sanction")),
                ('valeur_sanction', models.DecimalField(decimal_places=2, default=-1.0, max_digits=4, verbose_name='Valeur de la sanction après avertissements')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combat_configurations', to='competitions.discipline', verbose_name='Discipline')),
            ],
            options={
                'verbose_name': 'Configuration de combat',
                'verbose_name_plural': 'Configurations de combat',
            },
        ),
        migrations.AddField(
            model_name='combat',
            name='configuration',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='combats', to='competitions.combatconfiguration', verbose_name='Configuration'),
        ),
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('club', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipes_combat', to='competitions.club', verbose_name='Club')),
                ('coach', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipes_coachees', to=settings.AUTH_USER_MODEL, verbose_name='Coach')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipes_combat', to='competitions.competition', verbose_name='Compétition')),
            ],
            options={
                'verbose_name': 'Équipe',
                'verbose_name_plural': 'Équipes',
            },
        ),
        migrations.AddField(
            model_name='combat',
            name='equipe_blanc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='combats_blanc', to='competitions.equipe', verbose_name='Équipe blanc'),
        ),
        migrations.AddField(
            model_name='combat',
            name='equipe_rouge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='combats_rouge', to='competitions.equipe', verbose_name='Équipe rouge'),
        ),
        migrations.CreateModel(
            name='MembreEquipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('est_remplacant', models.BooleanField(default=False, verbose_name='Est remplaçant')),
                ('ordre', models.PositiveSmallIntegerField(default=0, verbose_name='Ordre')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('equipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='competitions.equipe', verbose_name='Équipe')),
                ('pratiquant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipe_memberships', to='competitions.practitioner', verbose_name='Pratiquant')),
            ],
            options={
                'verbose_name': "Membre d'équipe",
                'verbose_name_plural': "Membres d'équipe",
                'ordering': ['equipe', 'ordre'],
                'unique_together': {('equipe', 'pratiquant')},
            },
        ),
        migrations.AddField(
            model_name='equipe',
            name='membres',
            field=models.ManyToManyField(related_name='equipes_combat', through='competitions.MembreEquipe', to='competitions.practitioner', verbose_name='Membres'),
        ),
        migrations.CreateModel(
            name='Poule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='Poule', max_length=100, verbose_name='Nom')),
                ('numero', models.PositiveSmallIntegerField(default=1, verbose_name='Numéro')),
                ('phase', models.CharField(choices=[('eliminatoire', 'Éliminatoire'), ('quart', 'Quart de finale'), ('demi', 'Demi-finale'), ('finale', 'Finale'), ('repechage', 'Repêchage')], default='eliminatoire', max_length=20, verbose_name='Phase')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poules', to='competitions.competition', verbose_name='Compétition')),
                ('equipes', models.ManyToManyField(blank=True, related_name='poules', to='competitions.equipe', verbose_name='Équipes')),
                ('pratiquants', models.ManyToManyField(blank=True, related_name='poules_individuelles', to='competitions.practitioner', verbose_name='Pratiquants individuels')),
            ],
            options={
                'verbose_name': 'Poule',
                'verbose_name_plural': 'Poules',
                'ordering': ['competition', 'phase', 'numero'],
                'unique_together': {('competition', 'phase', 'numero')},
            },
        ),
        migrations.AddField(
            model_name='combat',
            name='poule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='combats', to='competitions.poule', verbose_name='Poule'),
        ),
    ]
