# Generated by Django 5.1.4 on 2025-05-15 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0007_standalonecategoryrankingsnapshot_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='standalonerankingsnapshotentry',
            table='competitions_standalonerankingsnapshotentry',
        ),
    ]
