# Generated by Django 5.1.4 on 2025-05-18 16:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0010_competitionresult'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PractitionerQRCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Code unique')),
                ('qr_image', models.ImageField(blank=True, null=True, upload_to='qr_codes/practitioners/', verbose_name='Image QR Code')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('is_federation_validated', models.BooleanField(default=False, verbose_name='Validé par la fédération')),
                ('federation_validation_date', models.DateTimeField(blank=True, null=True, verbose_name='Date de validation fédération')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('scan_count', models.PositiveIntegerField(default=0, verbose_name='Nombre de scans')),
                ('last_scan_date', models.DateTimeField(blank=True, null=True, verbose_name='Dernier scan')),
                ('practitioner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qr_code', to='competitions.practitioner', verbose_name='Pratiquant')),
            ],
            options={
                'verbose_name': 'QR Code Pratiquant',
                'verbose_name_plural': 'QR Codes Pratiquants',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QRCodeScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_type', models.CharField(choices=[('attendance', 'Présence'), ('competition', 'Compétition'), ('event', 'Événement'), ('training', 'Entraînement'), ('check_in', 'Check-in')], max_length=20, verbose_name='Type de scan')),
                ('scan_date', models.DateTimeField(auto_now_add=True, verbose_name='Date du scan')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='Lieu')),
                ('is_valid', models.BooleanField(default=True, verbose_name='Valide')),
                ('validation_message', models.TextField(blank=True, verbose_name='Message de validation')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('competition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qr_scans', to='competitions.competition', verbose_name='Compétition')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qr_scans', to='competitions.event', verbose_name='Événement')),
                ('qr_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='competitions.practitionerqrcode', verbose_name='QR Code')),
                ('scanned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qr_scans_performed', to=settings.AUTH_USER_MODEL, verbose_name='Scanné par')),
                ('training_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qr_scans', to='competitions.trainingsession', verbose_name="Session d'entraînement")),
            ],
            options={
                'verbose_name': 'Scan QR Code',
                'verbose_name_plural': 'Scans QR Code',
                'ordering': ['-scan_date'],
                'indexes': [models.Index(fields=['qr_code', 'scan_type'], name='competition_qr_code_2318c7_idx'), models.Index(fields=['scan_date'], name='competition_scan_da_8b76ab_idx')],
            },
        ),
    ]
