# Generated by Django 5.1.4 on 2025-05-18 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0011_add_migration_fields_to_club'),
        ('competitions', '0011_practitionerqrcode_qrcodescan'),
    ]

    operations = [
    ]
