# Generated by Django 5.1.4 on 2025-05-19 00:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0012_merge_20250519_0147'),
        ('multitenant', '0004_remove_tenant_logo_remove_tenant_primary_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='country',
            field=models.CharField(blank=True, default='FR', max_length=2, verbose_name='Pays'),
        ),
        migrations.AlterField(
            model_name='club',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='migrated_clubs', to='multitenant.tenant', verbose_name='Tenant associé'),
        ),
    ]
