# Generated by Django 5.1.4 on 2025-05-19 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0014_create_coach_profile_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(blank=True, choices=[('club_manager', 'Responsable de club'), ('federation_admin', 'Responsable de fédération'), ('judge', 'Juge/Arbitre'), ('participant', 'Participant'), ('coach', 'Coach'), ('spectator', 'Spectateur')], default='spectator', max_length=50, null=True, verbose_name='Rôle'),
        ),
    ]
