# Generated by Django 5.1.4 on 2025-05-19 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0015_alter_userprofile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coachachievement',
            name='achievement_type',
            field=models.CharField(choices=[('certification', 'Certification'), ('competition', 'Compétition'), ('teaching', 'Enseignement'), ('publication', 'Publication'), ('seminar', 'Séminaire'), ('other', 'Autre')], max_length=30, verbose_name='Type de réalisation'),
        ),
        migrations.AlterField(
            model_name='coachprofile',
            name='primary_teaching_place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_coaches', to='competitions.club', verbose_name="Club d'enseignement principal"),
        ),
        migrations.AlterField(
            model_name='coachprofile',
            name='profile_type',
            field=models.CharField(choices=[('traditional', 'Enseignant Traditionnel'), ('competitive', 'Entraîneur de Compétition'), ('wellness', 'Spécialiste Bien-être et Santé'), ('children', 'Spécialiste Pédagogie Enfants'), ('master', 'Maître / Expert Technique'), ('fitness', 'Coach Préparation Physique'), ('multidisciplinary', 'Expert Multi-disciplines')], default='traditional', help_text='Orientation principale de votre enseignement', max_length=30, verbose_name='Type de profil'),
        ),
        migrations.AlterField(
            model_name='disciplineexpertise',
            name='level',
            field=models.CharField(choices=[('beginner', 'Débutant'), ('intermediate', 'Intermédiaire'), ('advanced', 'Avancé'), ('expert', 'Expert'), ('master', 'Maître')], default='advanced', max_length=30, verbose_name="Niveau d'expertise"),
        ),
    ]
