# Generated by Django 5.1.4 on 2025-05-19 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0016_alter_coachachievement_achievement_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachprofile',
            name='teaching_place',
            field=models.CharField(blank=True, help_text="Nom de votre club, dojo ou lieu d'enseignement principal", max_length=200, verbose_name="Lieu d'enseignement principal"),
        ),
    ]
