# Generated by Django 5.1.4 on 2025-05-19 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0017_add_teaching_place_field'),
        ('competitions', '0017_coachprofile_teaching_place'),
    ]

    operations = [
    ]
