# Generated by Django 5.1.4 on 2025-05-20 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0018_merge_20250519_2342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coachprofile',
            name='teaching_place',
        ),
        migrations.AddField(
            model_name='coachprofile',
            name='teaching_place_name',
            field=models.CharField(blank=True, help_text="Nom de votre club, dojo ou lieu d'enseignement principal", max_length=200, verbose_name="Lieu ou club d'enseignement"),
        ),
        migrations.AlterField(
            model_name='coachprofile',
            name='primary_teaching_place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_coaches', to='competitions.club', verbose_name='Club référencé (interne)'),
        ),
    ]
