# Generated by Django 5.1.4 on 2025-05-20 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0020_add_teaching_place_name_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coachprofile',
            name='teaching_place_name',
            field=models.CharField(blank=True, help_text="Nom de votre club, dojo ou lieu d'enseignement principal", max_length=200, verbose_name="Lieu ou club d'enseignement"),
        ),
    ]
