# Generated by Django 5.1.4 on 2025-05-21 18:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0024_add_event_planning_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventSurvey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_anonymous', models.BooleanField(default=False, verbose_name='Anonyme')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='Date de début')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Date de fin')),
                ('is_required', models.BooleanField(default=False, verbose_name='Obligatoire')),
                ('allow_multiple_submissions', models.BooleanField(default=False, verbose_name='Autoriser plusieurs soumissions')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
            ],
            options={
                'verbose_name': "Sondage d'événement",
                'verbose_name_plural': "Sondages d'événements",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuestionResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_response', models.TextField(blank=True, verbose_name='Réponse texte')),
                ('choice_response', models.JSONField(blank=True, default=list, verbose_name='Réponse à choix')),
                ('numeric_response', models.IntegerField(blank=True, null=True, verbose_name='Réponse numérique')),
                ('date_response', models.DateField(blank=True, null=True, verbose_name='Réponse date')),
            ],
            options={
                'verbose_name': 'Réponse à une question',
                'verbose_name_plural': 'Réponses aux questions',
            },
        ),
        migrations.CreateModel(
            name='SurveyQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=500, verbose_name='Question')),
                ('question_type', models.CharField(choices=[('text', 'Texte'), ('textarea', 'Zone de texte'), ('single_choice', 'Choix unique'), ('multiple_choice', 'Choix multiple'), ('rating', 'Notation'), ('scale', 'Échelle'), ('date', 'Date')], max_length=20, verbose_name='Type de question')),
                ('is_required', models.BooleanField(default=False, verbose_name='Obligatoire')),
                ('help_text', models.CharField(blank=True, max_length=500, verbose_name="Texte d'aide")),
                ('choices', models.JSONField(blank=True, default=list, verbose_name='Choix')),
                ('min_value', models.IntegerField(blank=True, null=True, verbose_name='Valeur minimale')),
                ('max_value', models.IntegerField(blank=True, null=True, verbose_name='Valeur maximale')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
            ],
            options={
                'verbose_name': 'Question de sondage',
                'verbose_name_plural': 'Questions de sondage',
                'ordering': ['survey', 'order'],
            },
        ),
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('respondent_name', models.CharField(blank=True, max_length=200, verbose_name='Nom du répondant')),
                ('respondent_email', models.EmailField(blank=True, max_length=254, verbose_name='Email du répondant')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Soumis le')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('completion_time', models.DurationField(blank=True, null=True, verbose_name='Temps de complétion')),
            ],
            options={
                'verbose_name': 'Réponse au sondage',
                'verbose_name_plural': 'Réponses aux sondages',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.AddField(
            model_name='eventreminder',
            name='delivery_status',
            field=models.JSONField(blank=True, default=dict, verbose_name='Statut de livraison'),
        ),
        migrations.AddField(
            model_name='eventreminder',
            name='open_rate',
            field=models.FloatField(blank=True, null=True, verbose_name="Taux d'ouverture"),
        ),
        migrations.AddField(
            model_name='eventreminder',
            name='send_to',
            field=models.CharField(choices=[('all', 'Tous les participants'), ('registered', 'Inscrits seulement'), ('confirmed', 'Confirmés seulement'), ('not_confirmed', 'Non confirmés'), ('custom', 'Liste personnalisée')], default='all', max_length=20, verbose_name='Envoyer à'),
        ),
        migrations.AddIndex(
            model_name='qrcodescan',
            index=models.Index(fields=['is_offline_scan'], name='competition_is_offl_07674b_idx'),
        ),
        migrations.AddIndex(
            model_name='qrcodescan',
            index=models.Index(fields=['offline_scan_id'], name='competition_offline_b4f93b_idx'),
        ),
        migrations.AddField(
            model_name='eventsurvey',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_surveys', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AddField(
            model_name='eventsurvey',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surveys', to='competitions.event', verbose_name='Événement'),
        ),
        migrations.AddField(
            model_name='surveyquestion',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='competitions.eventsurvey', verbose_name='Sondage'),
        ),
        migrations.AddField(
            model_name='questionresponse',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='competitions.surveyquestion', verbose_name='Question'),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='participant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='survey_responses', to=settings.AUTH_USER_MODEL, verbose_name='Participant'),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='competitions.eventsurvey', verbose_name='Sondage'),
        ),
        migrations.AddField(
            model_name='questionresponse',
            name='response',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_responses', to='competitions.surveyresponse', verbose_name='Réponse au sondage'),
        ),
    ]
