# Generated by Django 5.1.4 on 2025-05-21 19:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0025_eventsurvey_questionresponse_surveyquestion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de soumission')),
                ('overall_satisfaction', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='Satisfaction générale')),
                ('organization_rating', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='Organisation')),
                ('content_quality', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='Qualité du contenu')),
                ('location_rating', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='Lieu')),
                ('value_for_money', models.PositiveSmallIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True, verbose_name='Rapport qualité-prix')),
                ('would_recommend', models.CharField(choices=[('yes', 'Oui, sans hésitation'), ('maybe', 'Peut-être'), ('no', 'Non')], max_length=10, verbose_name='Recommandation')),
                ('highlights', models.TextField(blank=True, verbose_name='Points forts')),
                ('improvements', models.TextField(blank=True, verbose_name='Points à améliorer')),
                ('additional_comments', models.TextField(blank=True, verbose_name='Commentaires additionnels')),
                ('allow_testimonial', models.BooleanField(default=False, verbose_name='Autoriser comme témoignage')),
                ('competition_fairness', models.PositiveSmallIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True, verbose_name='Équité de la compétition')),
                ('instructor_knowledge', models.PositiveSmallIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True, verbose_name="Connaissance de l'instructeur")),
                ('material_usefulness', models.PositiveSmallIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True, verbose_name='Utilité du matériel')),
                ('exam_difficulty', models.PositiveSmallIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True, verbose_name="Difficulté de l'examen")),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name='Données supplémentaires')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_feedbacks', to='competitions.event', verbose_name='Événement')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_feedbacks', to=settings.AUTH_USER_MODEL, verbose_name='Soumis par')),
            ],
            options={
                'verbose_name': "Feedback d'événement",
                'verbose_name_plural': "Feedbacks d'événements",
                'ordering': ['-submitted_at'],
                'unique_together': {('event', 'submitted_by')},
            },
        ),
    ]
