# Generated by Django 5.1.4 on 2025-05-24 20:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0026_eventfeedback'),
        ('finances', '0007_combatpool_combat_combatround_combatscore_combatteam_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationQRCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('purpose', models.CharField(choices=[('registration', 'Inscription'), ('payment', 'Paiement'), ('both', 'Inscription et paiement'), ('info', 'Information')], default='both', max_length=50, verbose_name='Objectif')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Code QR')),
                ('qr_image', models.ImageField(blank=True, null=True, upload_to='qr_codes/organizations/', verbose_name='Image QR Code')),
                ('url', models.URLField(blank=True, verbose_name='URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='Dernière utilisation')),
                ('scan_count', models.PositiveIntegerField(default=0, verbose_name='Nombre de scans')),
                ('conversion_count', models.PositiveIntegerField(default=0, verbose_name='Nombre de conversions')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('custom_title', models.CharField(blank=True, max_length=100, verbose_name='Titre personnalisé')),
                ('custom_message', models.TextField(blank=True, verbose_name='Message personnalisé')),
                ('expiration_date', models.DateTimeField(blank=True, null=True, verbose_name="Date d'expiration")),
                ('max_uses', models.PositiveIntegerField(blank=True, null=True, verbose_name="Nombre maximum d'utilisations")),
                ('club', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qr_codes', to='competitions.club', verbose_name='Club')),
                ('coach_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qr_codes', to='competitions.coachprofile', verbose_name='Coach')),
                ('federation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qr_codes', to='competitions.federation', verbose_name='Fédération')),
            ],
            options={
                'verbose_name': "Code QR d'organisation",
                'verbose_name_plural': "Codes QR d'organisations",
            },
        ),
        migrations.CreateModel(
            name='OrganizationQRCodeScan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scanned_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de scan')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='Agent utilisateur')),
                ('location', models.CharField(blank=True, help_text='Lieu où le scan a été effectué', max_length=200, verbose_name='Lieu')),
                ('converted', models.BooleanField(default=False, verbose_name='Converti')),
                ('conversion_type', models.CharField(blank=True, choices=[('registration', 'Inscription'), ('payment', 'Paiement'), ('both', 'Inscription et paiement'), ('other', 'Autre')], max_length=50, verbose_name='Type de conversion')),
                ('conversion_date', models.DateTimeField(blank=True, null=True, verbose_name='Date de conversion')),
                ('payment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Montant payé')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('payment_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qr_scans', to='finances.transaction', verbose_name='Transaction de paiement')),
                ('practitioner_created', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qr_registrations', to='competitions.practitioner', verbose_name='Pratiquant créé')),
                ('qr_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='competitions.organizationqrcode', verbose_name='Code QR')),
                ('scanned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organization_qr_scans', to=settings.AUTH_USER_MODEL, verbose_name='Scanné par')),
                ('user_created', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qr_registrations', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur créé')),
            ],
            options={
                'verbose_name': "Scan de QR code d'organisation",
                'verbose_name_plural': "Scans de QR codes d'organisations",
                'ordering': ['-scanned_at'],
            },
        ),
        migrations.CreateModel(
            name='ReferralLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code de parrainage')),
                ('url', models.URLField(blank=True, verbose_name='URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name="Date d'expiration")),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Montant de réduction')),
                ('discount_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Pourcentage de réduction')),
                ('max_uses', models.PositiveIntegerField(default=10, verbose_name='Utilisations maximales')),
                ('current_uses', models.PositiveIntegerField(default=0, verbose_name='Utilisations actuelles')),
                ('custom_message', models.TextField(blank=True, verbose_name='Message personnalisé')),
                ('club', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referral_links', to='competitions.club', verbose_name='Club')),
                ('federation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referral_links', to='competitions.federation', verbose_name='Fédération')),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_links', to=settings.AUTH_USER_MODEL, verbose_name='Parrain')),
            ],
            options={
                'verbose_name': 'Lien de parrainage',
                'verbose_name_plural': 'Liens de parrainage',
            },
        ),
        migrations.CreateModel(
            name='ReferralUse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'utilisation")),
                ('converted', models.BooleanField(default=False, verbose_name='Converti')),
                ('payment_completed', models.BooleanField(default=False, verbose_name='Paiement effectué')),
                ('payment_date', models.DateTimeField(blank=True, null=True, verbose_name='Date de paiement')),
                ('discount_applied', models.BooleanField(default=False, verbose_name='Réduction appliquée')),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Montant de la réduction')),
                ('payment_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referral_uses', to='finances.transaction', verbose_name='Transaction de paiement')),
                ('practitioner_created', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referral_signups', to='competitions.practitioner', verbose_name='Pratiquant créé')),
                ('referral_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uses', to='competitions.referrallink', verbose_name='Lien de parrainage')),
                ('referred_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_signups', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur parrainé')),
            ],
            options={
                'verbose_name': 'Utilisation de parrainage',
                'verbose_name_plural': 'Utilisations de parrainage',
            },
        ),
    ]
