# Generated by Django 5.1.4 on 2025-05-26 08:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0029_create_event_model'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['start_date', 'start_time'], 'verbose_name': 'Événement', 'verbose_name_plural': 'Événements'},
        ),
        migrations.AlterModelOptions(
            name='eventparticipant',
            options={'ordering': ['event', 'registered_at'], 'verbose_name': "Participant à l'événement", 'verbose_name_plural': 'Participants aux événements'},
        ),
        migrations.RemoveField(
            model_name='eventparticipant',
            name='registration_date',
        ),
        migrations.AddField(
            model_name='eventparticipant',
            name='attended',
            field=models.BooleanField(default=False, verbose_name='A participé'),
        ),
        migrations.AddField(
            model_name='eventparticipant',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Confirmé le'),
        ),
        migrations.AddField(
            model_name='eventparticipant',
            name='payment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Montant payé'),
        ),
        migrations.AddField(
            model_name='eventparticipant',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de paiement'),
        ),
        migrations.AddField(
            model_name='eventparticipant',
            name='registered_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Inscrit le'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='eventparticipant',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='eventparticipant',
            name='status',
            field=models.CharField(choices=[('registered', 'Inscrit'), ('confirmed', 'Confirmé'), ('waitlist', 'Liste en attente'), ('cancelled', 'Annulé')], default='registered', max_length=20, verbose_name='Statut'),
        ),
    ]
