# Generated by Django 4.2.11 on 2025-05-26 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0031_add_poll_custom_questions'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='documentacceptance',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='documentacceptance',
            name='document',
        ),
        migrations.RemoveField(
            model_name='documentacceptance',
            name='user',
        ),
        migrations.RemoveField(
            model_name='documentaccess',
            name='document',
        ),
        migrations.RemoveField(
            model_name='documentaccess',
            name='user',
        ),
        migrations.RemoveField(
            model_name='documentcategory',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='documentcategory',
            name='parent',
        ),
        migrations.AlterUniqueTogether(
            name='documentshare',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='documentshare',
            name='document',
        ),
        migrations.RemoveField(
            model_name='documentshare',
            name='shared_by',
        ),
        migrations.RemoveField(
            model_name='documentshare',
            name='shared_with',
        ),
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.DeleteModel(
            name='DocumentAcceptance',
        ),
        migrations.DeleteModel(
            name='DocumentAccess',
        ),
        migrations.DeleteModel(
            name='DocumentCategory',
        ),
        migrations.DeleteModel(
            name='DocumentShare',
        ),
    ]
