# Generated by Django 5.1.4 on 2025-05-14 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0005_transactions'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='accountingcategory',
            new_name='finances_ac_type_46cca2_idx',
            old_name='finances_ac_type_7a4cbc_idx',
        ),
        migrations.RenameIndex(
            model_name='accountingcategory',
            new_name='finances_ac_is_acti_edab05_idx',
            old_name='finances_ac_is_acti_7f9a8a_idx',
        ),
        migrations.RenameIndex(
            model_name='financialaccount',
            new_name='finances_fi_is_acti_05ed14_idx',
            old_name='finances_fi_is_acti_5bfb32_idx',
        ),
        migrations.RenameIndex(
            model_name='financialaccount',
            new_name='finances_fi_is_defa_dc236a_idx',
            old_name='finances_fi_is_defa_9ab08b_idx',
        ),
        migrations.RenameIndex(
            model_name='invoice',
            new_name='finances_in_status_e91c9f_idx',
            old_name='finances_in_status_9f76e8_idx',
        ),
        migrations.RenameIndex(
            model_name='invoice',
            new_name='finances_in_issued__06e260_idx',
            old_name='finances_in_issued__5c6290_idx',
        ),
        migrations.RenameIndex(
            model_name='invoice',
            new_name='finances_in_due_dat_fb7217_idx',
            old_name='finances_in_due_dat_6c5923_idx',
        ),
        migrations.RenameIndex(
            model_name='membershipfee',
            new_name='finances_me_is_acti_208ec5_idx',
            old_name='finances_me_is_acti_3ba9d9_idx',
        ),
        migrations.RenameIndex(
            model_name='membershipfee',
            new_name='finances_me_start_d_878a5a_idx',
            old_name='finances_me_start_d_6c2a6e_idx',
        ),
        migrations.RenameIndex(
            model_name='membershipfee',
            new_name='finances_me_end_dat_c44895_idx',
            old_name='finances_me_end_dat_c647b3_idx',
        ),
        migrations.RenameIndex(
            model_name='transaction',
            new_name='finances_tr_status_d5ea9d_idx',
            old_name='finances_tr_status_1a98cd_idx',
        ),
        migrations.RenameIndex(
            model_name='transaction',
            new_name='finances_tr_type_db9430_idx',
            old_name='finances_tr_type_52095b_idx',
        ),
        migrations.RenameIndex(
            model_name='transaction',
            new_name='finances_tr_date_cr_f4957e_idx',
            old_name='finances_tr_date_cr_86bb08_idx',
        ),
        migrations.RenameIndex(
            model_name='transactioncategory',
            new_name='finances_tr_transac_0e8bf3_idx',
            old_name='finances_tr_transac_efd903_idx',
        ),
        migrations.RenameIndex(
            model_name='transactioncategory',
            new_name='finances_tr_active_05d654_idx',
            old_name='finances_tr_active_89ccbf_idx',
        ),
    ]
