# Generated by Django 4.2.21 on 2025-07-31 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('trial', 'Essai'), ('active', 'Actif'), ('expired', 'Expiré'), ('cancelled', 'Annulé'), ('suspended', 'Suspendu')], default='trial', max_length=20)),
                ('trial_start', models.DateTimeField(auto_now_add=True, verbose_name="Début de l'essai")),
                ('trial_end', models.DateTimeField(verbose_name="Fin de l'essai")),
                ('subscription_start', models.DateTimeField(blank=True, null=True, verbose_name="Début de l'abonnement")),
                ('subscription_end', models.DateTimeField(blank=True, null=True, verbose_name="Fin de l'abonnement")),
                ('auto_renew', models.BooleanField(default=True, verbose_name='Renouvellement automatique')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization', verbose_name='Organisation')),
            ],
            options={
                'verbose_name': "Abonnement d'organisation",
                'verbose_name_plural': "Abonnements d'organisations",
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant')),
                ('currency', models.CharField(default='EUR', max_length=3, verbose_name='Devise')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('processing', 'En cours'), ('completed', 'Terminé'), ('failed', 'Ã‰choué'), ('cancelled', 'Annulé'), ('refunded', 'Remboursé')], default='pending', max_length=20)),
                ('transaction_id', models.CharField(max_length=100, unique=True, verbose_name='ID de transaction')),
                ('gateway_response', models.JSONField(default=dict, verbose_name='Réponse de la passerelle')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom du plan')),
                ('plan_type', models.CharField(choices=[('trial', 'Essai gratuit'), ('basic', 'Basique'), ('premium', 'Premium'), ('enterprise', 'Entreprise')], default='basic', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix mensuel')),
                ('trial_days', models.IntegerField(default=30, verbose_name="Jours d'essai")),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('features', models.JSONField(default=list, verbose_name='Fonctionnalités')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "Plan d'abonnement",
                'verbose_name_plural': "Plans d'abonnement",
            },
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant remboursé')),
                ('reason', models.TextField(verbose_name='Raison du remboursement')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvé'), ('rejected', 'Rejeté'), ('completed', 'Terminé')], default='pending', max_length=20)),
                ('refund_id', models.CharField(max_length=100, unique=True, verbose_name='ID de remboursement')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Traité le')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.payment', verbose_name='Paiement')),
            ],
            options={
                'verbose_name': 'Remboursement',
                'verbose_name_plural': 'Remboursements',
            },
        ),
        migrations.CreateModel(
            name='PaymentWebhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webhook_id', models.CharField(max_length=100, unique=True, verbose_name='ID du webhook')),
                ('event_type', models.CharField(max_length=50, verbose_name="Type d'événement")),
                ('payload', models.JSONField(verbose_name='Données reçues')),
                ('processed', models.BooleanField(default=False, verbose_name='Traité')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.payment', verbose_name='Paiement')),
            ],
            options={
                'verbose_name': 'Webhook de paiement',
                'verbose_name_plural': 'Webhooks de paiement',
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method_type', models.CharField(choices=[('card', 'Carte bancaire'), ('paypal', 'PayPal'), ('mobile_money', 'Mobile Money'), ('bank_transfer', 'Virement bancaire')], max_length=20, verbose_name='Type de méthode')),
                ('is_default', models.BooleanField(default=False, verbose_name='Méthode par défaut')),
                ('payment_data', models.JSONField(default=dict, verbose_name='Données de paiement')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization', verbose_name='Organisation')),
            ],
            options={
                'verbose_name': 'Méthode de paiement',
                'verbose_name_plural': 'Méthodes de paiement',
            },
        ),
        migrations.CreateModel(
            name='PaymentError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_code', models.CharField(max_length=50, verbose_name="Code d'erreur")),
                ('error_message', models.TextField(verbose_name="Message d'erreur")),
                ('error_data', models.JSONField(default=dict, verbose_name="Données d'erreur")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.payment', verbose_name='Paiement')),
            ],
            options={
                'verbose_name': 'Erreur de paiement',
                'verbose_name_plural': 'Erreurs de paiement',
            },
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.paymentmethod', verbose_name='Méthode de paiement'),
        ),
        migrations.AddField(
            model_name='payment',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.organizationsubscription', verbose_name='Abonnement'),
        ),
        migrations.AddField(
            model_name='organizationsubscription',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.subscriptionplan', verbose_name='Plan'),
        ),
    ]
