# Generated by Django 4.2.11 on 2025-06-05 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='color_am',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Couleur'),
        ),
        migrations.AddField(
            model_name='grade',
            name='color_ar',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Couleur'),
        ),
        migrations.AddField(
            model_name='grade',
            name='color_de',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Couleur'),
        ),
        migrations.AddField(
            model_name='grade',
            name='color_en',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Couleur'),
        ),
        migrations.AddField(
            model_name='grade',
            name='color_es',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Couleur'),
        ),
        migrations.AddField(
            model_name='grade',
            name='color_fr',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Couleur'),
        ),
        migrations.AddField(
            model_name='grade',
            name='color_hi',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Couleur'),
        ),
        migrations.AddField(
            model_name='grade',
            name='color_it',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Couleur'),
        ),
        migrations.AddField(
            model_name='grade',
            name='color_ja',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Couleur'),
        ),
        migrations.AddField(
            model_name='grade',
            name='color_ko',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Couleur'),
        ),
        migrations.AddField(
            model_name='grade',
            name='color_no',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Couleur'),
        ),
        migrations.AddField(
            model_name='grade',
            name='color_pt',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Couleur'),
        ),
        migrations.AddField(
            model_name='grade',
            name='color_sw',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Couleur'),
        ),
        migrations.AddField(
            model_name='grade',
            name='color_yo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Couleur'),
        ),
        migrations.AddField(
            model_name='grade',
            name='color_zh',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Couleur'),
        ),
        migrations.AddField(
            model_name='grade',
            name='color_zu',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Couleur'),
        ),
        migrations.AddField(
            model_name='grade',
            name='name_am',
            field=models.CharField(max_length=100, null=True, verbose_name='Nom'),
        ),
        migrations.AddField(
            model_name='grade',
            name='name_ar',
            field=models.CharField(max_length=100, null=True, verbose_name='Nom'),
        ),
        migrations.AddField(
            model_name='grade',
            name='name_de',
            field=models.CharField(max_length=100, null=True, verbose_name='Nom'),
        ),
        migrations.AddField(
            model_name='grade',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Nom'),
        ),
        migrations.AddField(
            model_name='grade',
            name='name_es',
            field=models.CharField(max_length=100, null=True, verbose_name='Nom'),
        ),
        migrations.AddField(
            model_name='grade',
            name='name_fr',
            field=models.CharField(max_length=100, null=True, verbose_name='Nom'),
        ),
        migrations.AddField(
            model_name='grade',
            name='name_hi',
            field=models.CharField(max_length=100, null=True, verbose_name='Nom'),
        ),
        migrations.AddField(
            model_name='grade',
            name='name_it',
            field=models.CharField(max_length=100, null=True, verbose_name='Nom'),
        ),
        migrations.AddField(
            model_name='grade',
            name='name_ja',
            field=models.CharField(max_length=100, null=True, verbose_name='Nom'),
        ),
        migrations.AddField(
            model_name='grade',
            name='name_ko',
            field=models.CharField(max_length=100, null=True, verbose_name='Nom'),
        ),
        migrations.AddField(
            model_name='grade',
            name='name_no',
            field=models.CharField(max_length=100, null=True, verbose_name='Nom'),
        ),
        migrations.AddField(
            model_name='grade',
            name='name_pt',
            field=models.CharField(max_length=100, null=True, verbose_name='Nom'),
        ),
        migrations.AddField(
            model_name='grade',
            name='name_sw',
            field=models.CharField(max_length=100, null=True, verbose_name='Nom'),
        ),
        migrations.AddField(
            model_name='grade',
            name='name_yo',
            field=models.CharField(max_length=100, null=True, verbose_name='Nom'),
        ),
        migrations.AddField(
            model_name='grade',
            name='name_zh',
            field=models.CharField(max_length=100, null=True, verbose_name='Nom'),
        ),
        migrations.AddField(
            model_name='grade',
            name='name_zu',
            field=models.CharField(max_length=100, null=True, verbose_name='Nom'),
        ),
        migrations.AddField(
            model_name='gradingsystem',
            name='description_am',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='gradingsystem',
            name='description_ar',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='gradingsystem',
            name='description_de',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='gradingsystem',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='gradingsystem',
            name='description_es',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='gradingsystem',
            name='description_fr',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='gradingsystem',
            name='description_hi',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='gradingsystem',
            name='description_it',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='gradingsystem',
            name='description_ja',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='gradingsystem',
            name='description_ko',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='gradingsystem',
            name='description_no',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='gradingsystem',
            name='description_pt',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='gradingsystem',
            name='description_sw',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='gradingsystem',
            name='description_yo',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='gradingsystem',
            name='description_zh',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='gradingsystem',
            name='description_zu',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='gradingsystem',
            name='name_am',
            field=models.CharField(max_length=100, null=True, verbose_name='Nom'),
        ),
        migrations.AddField(
            model_name='gradingsystem',
            name='name_ar',
            field=models.CharField(max_length=100, null=True, verbose_name='Nom'),
        ),
        migrations.AddField(
            model_name='gradingsystem',
            name='name_de',
            field=models.CharField(max_length=100, null=True, verbose_name='Nom'),
        ),
        migrations.AddField(
            model_name='gradingsystem',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Nom'),
        ),
        migrations.AddField(
            model_name='gradingsystem',
            name='name_es',
            field=models.CharField(max_length=100, null=True, verbose_name='Nom'),
        ),
        migrations.AddField(
            model_name='gradingsystem',
            name='name_fr',
            field=models.CharField(max_length=100, null=True, verbose_name='Nom'),
        ),
        migrations.AddField(
            model_name='gradingsystem',
            name='name_hi',
            field=models.CharField(max_length=100, null=True, verbose_name='Nom'),
        ),
        migrations.AddField(
            model_name='gradingsystem',
            name='name_it',
            field=models.CharField(max_length=100, null=True, verbose_name='Nom'),
        ),
        migrations.AddField(
            model_name='gradingsystem',
            name='name_ja',
            field=models.CharField(max_length=100, null=True, verbose_name='Nom'),
        ),
        migrations.AddField(
            model_name='gradingsystem',
            name='name_ko',
            field=models.CharField(max_length=100, null=True, verbose_name='Nom'),
        ),
        migrations.AddField(
            model_name='gradingsystem',
            name='name_no',
            field=models.CharField(max_length=100, null=True, verbose_name='Nom'),
        ),
        migrations.AddField(
            model_name='gradingsystem',
            name='name_pt',
            field=models.CharField(max_length=100, null=True, verbose_name='Nom'),
        ),
        migrations.AddField(
            model_name='gradingsystem',
            name='name_sw',
            field=models.CharField(max_length=100, null=True, verbose_name='Nom'),
        ),
        migrations.AddField(
            model_name='gradingsystem',
            name='name_yo',
            field=models.CharField(max_length=100, null=True, verbose_name='Nom'),
        ),
        migrations.AddField(
            model_name='gradingsystem',
            name='name_zh',
            field=models.CharField(max_length=100, null=True, verbose_name='Nom'),
        ),
        migrations.AddField(
            model_name='gradingsystem',
            name='name_zu',
            field=models.CharField(max_length=100, null=True, verbose_name='Nom'),
        ),
    ]
