# Generated by Django 4.2.21 on 2025-07-31 11:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('competitions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nom')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Slug')),
                ('short_name', models.CharField(blank=True, max_length=50, verbose_name='Nom court')),
                ('organization_type', models.CharField(choices=[('global_body', 'Organisation internationale multidisciplinaire'), ('international_federation', 'Fédération internationale'), ('national_federation', 'Fédération nationale'), ('regional_body', 'Organisation régionale'), ('club', 'Club/Association'), ('academy', 'Académie'), ('other', 'Autre')], max_length=30, verbose_name="Type d'organisation")),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('website', models.URLField(blank=True, verbose_name='Site web')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='Pays')),
                ('address', models.TextField(blank=True, verbose_name='Adresse')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Ville')),
                ('postal_code', models.CharField(blank=True, max_length=20, verbose_name='Code postal')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='organizations/logos/', verbose_name='Logo')),
                ('old_federation_id', models.PositiveIntegerField(blank=True, null=True, verbose_name="ID de l'ancienne fédération")),
                ('old_club_id', models.PositiveIntegerField(blank=True, null=True, verbose_name="ID de l'ancien club")),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis Ã\xa0 jour le')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_organizations', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('disciplines', models.ManyToManyField(blank=True, related_name='organization_list', to='competitions.discipline', verbose_name='Disciplines')),
            ],
            options={
                'verbose_name': 'Organisation',
                'verbose_name_plural': 'Organisations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Affiliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('affiliation_type', models.CharField(choices=[('member', 'Membre'), ('partner', 'Partenaire'), ('technical', 'Affiliation technique'), ('administrative', 'Affiliation administrative')], default='member', max_length=30, verbose_name="Type d'affiliation")),
                ('start_date', models.DateField(verbose_name='Date de début')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Date de fin')),
                ('certification_number', models.CharField(blank=True, max_length=100, verbose_name='Numéro de certification')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis Ã\xa0 jour le')),
                ('child_organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_affiliations', to='organizations.organization', verbose_name='Organisation affiliée')),
                ('parent_organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_affiliations', to='organizations.organization', verbose_name='Organisation parente')),
            ],
            options={
                'verbose_name': 'Affiliation',
                'verbose_name_plural': 'Affiliations',
            },
        ),
        migrations.CreateModel(
            name='OrganizationMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Propriétaire'), ('admin', 'Administrateur'), ('manager', 'Gestionnaire'), ('member', 'Membre'), ('coach', 'EntraÃ®neur'), ('judge', 'Juge')], default='member', max_length=30, verbose_name='RÃ´le')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='Titre')),
                ('join_date', models.DateField(auto_now_add=True, verbose_name="Date d'adhésion")),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Date de fin')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('can_manage_members', models.BooleanField(default=False, verbose_name='Peut gérer les membres')),
                ('can_edit_organization', models.BooleanField(default=False, verbose_name="Peut modifier l'organisation")),
                ('can_manage_competitions', models.BooleanField(default=False, verbose_name='Peut gérer les compétitions')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis Ã\xa0 jour le')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='organizations.organization', verbose_name='Organisation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_memberships', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': "Membre d'organisation",
                'verbose_name_plural': "Membres d'organisations",
                'indexes': [models.Index(fields=['user', 'is_active'], name='organizatio_user_id_8783ae_idx'), models.Index(fields=['organization', 'role', 'is_active'], name='organizatio_organiz_5497e0_idx')],
                'unique_together': {('user', 'organization')},
            },
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['organization_type'], name='organizatio_organiz_d4294a_idx'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['country', 'city'], name='organizatio_country_42ba75_idx'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['old_federation_id'], name='organizatio_old_fed_b3c8d9_idx'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['old_club_id'], name='organizatio_old_clu_295ecf_idx'),
        ),
        migrations.AddIndex(
            model_name='affiliation',
            index=models.Index(fields=['parent_organization', 'is_active'], name='organizatio_parent__4dde64_idx'),
        ),
        migrations.AddIndex(
            model_name='affiliation',
            index=models.Index(fields=['child_organization', 'is_active'], name='organizatio_child_o_2390a8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='affiliation',
            unique_together={('parent_organization', 'child_organization')},
        ),
    ]
