# Generated by Django 4.2.11 on 2025-10-03 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_add_disciplines_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Mis Ã\xa0 jour le'),
        ),
    ]
