# Generated by Django 5.1.6 on 2025-12-28 20:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_add_theme_colors'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='organizationgalleryimage',
            new_name='organizatio_organiz_ecb387_idx',
            old_name='organizatio_organiz_idx',
        ),
        migrations.AddField(
            model_name='affiliation',
            name='child_approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Approuve par club le'),
        ),
        migrations.AddField(
            model_name='affiliation',
            name='child_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='club_approvals', to=settings.AUTH_USER_MODEL, verbose_name='Approuve par (club)'),
        ),
        migrations.AddField(
            model_name='affiliation',
            name='child_status',
            field=models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuve'), ('rejected', 'Refuse')], default='pending', max_length=10, verbose_name='Statut cote club'),
        ),
        migrations.AddField(
            model_name='affiliation',
            name='initiated_by',
            field=models.CharField(choices=[('parent', 'Federation (invitation)'), ('child', 'Club (demande)')], default='parent', max_length=10, verbose_name='Initie par'),
        ),
        migrations.AddField(
            model_name='affiliation',
            name='parent_approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Approuve par federation le'),
        ),
        migrations.AddField(
            model_name='affiliation',
            name='parent_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='federation_approvals', to=settings.AUTH_USER_MODEL, verbose_name='Approuve par (federation)'),
        ),
        migrations.AddField(
            model_name='affiliation',
            name='parent_status',
            field=models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuve'), ('rejected', 'Refuse')], default='pending', max_length=10, verbose_name='Statut cote federation'),
        ),
        migrations.AlterField(
            model_name='affiliation',
            name='certification_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='Numero de certification'),
        ),
        migrations.AlterField(
            model_name='affiliation',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Actif'),
        ),
        migrations.AlterField(
            model_name='affiliation',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date de debut'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='banner',
            field=models.ImageField(blank=True, help_text='Dimensions recommandées: 1920x600px. Max 5 Mo.', null=True, upload_to='organizations/banners/', verbose_name='Bannière'),
        ),
    ]
