# Generated by Django 5.1.6 on 2025-11-29 23:13

import apps.chat.models
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('competitions', '0013_alter_equipe_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('type', models.CharField(choices=[('direct', 'Message privé'), ('group', 'Groupe'), ('club', 'Club'), ('competition', 'Compétition')], default='direct', max_length=20, verbose_name='Type de conversation')),
                ('name', models.CharField(blank=True, help_text='Nom du groupe (optionnel pour les conversations directes)', max_length=100, verbose_name='Nom')),
                ('description', models.TextField(blank=True, help_text='Description du groupe ou de la conversation', verbose_name='Description')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='chat_avatars/', verbose_name='Avatar du groupe')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('last_message_at', models.DateTimeField(blank=True, null=True, verbose_name='Dernier message le')),
                ('last_message_preview', models.CharField(blank=True, max_length=100, verbose_name='Aperçu du dernier message')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('allow_replies', models.BooleanField(default=True, help_text='Si désactivé, seuls les admins peuvent envoyer des messages', verbose_name='Autoriser les réponses')),
                ('club', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='competitions.club', verbose_name='Club associé')),
                ('competition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='competitions.competition', verbose_name='Compétition associée')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_conversations_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
            ],
            options={
                'verbose_name': 'Conversation',
                'verbose_name_plural': 'Conversations',
                'ordering': ['-last_message_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConversationParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('member', 'Membre'), ('moderator', 'Modérateur'), ('admin', 'Administrateur')], default='member', max_length=20, verbose_name='Rôle')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='Rejoint le')),
                ('left_at', models.DateTimeField(blank=True, null=True, verbose_name='Quitté le')),
                ('is_muted', models.BooleanField(default=False, verbose_name='Notifications désactivées')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='Épinglé')),
                ('last_read_at', models.DateTimeField(blank=True, null=True, verbose_name='Dernier lu le')),
                ('nickname', models.CharField(blank=True, help_text='Surnom affiché dans cette conversation', max_length=50, verbose_name='Surnom')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='chat.conversation', verbose_name='Conversation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_participations', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Participant',
                'verbose_name_plural': 'Participants',
                'ordering': ['joined_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('message_type', models.CharField(choices=[('text', 'Texte'), ('system', 'Système'), ('image', 'Image'), ('file', 'Fichier')], default='text', max_length=20, verbose_name='Type de message')),
                ('content', models.TextField(help_text='Contenu du message (supporte le markdown basique)', verbose_name='Contenu')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Envoyé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Supprimé')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Supprimé le')),
                ('is_edited', models.BooleanField(default=False, verbose_name='Modifié')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Métadonnées')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.conversation', verbose_name='Conversation')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_messages_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Supprimé par')),
                ('reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='chat.message', verbose_name='En réponse à')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_messages_sent', to=settings.AUTH_USER_MODEL, verbose_name='Expéditeur')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=apps.chat.models.chat_attachment_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp', 'pdf', 'doc', 'docx', 'xls', 'xlsx', 'txt', 'csv'])], verbose_name='Fichier')),
                ('file_name', models.CharField(max_length=255, verbose_name='Nom du fichier')),
                ('file_type', models.CharField(choices=[('image', 'Image'), ('pdf', 'PDF'), ('document', 'Document'), ('spreadsheet', 'Tableur'), ('other', 'Autre')], default='other', max_length=20, verbose_name='Type de fichier')),
                ('file_size', models.PositiveIntegerField(help_text='Taille du fichier en bytes', verbose_name='Taille (bytes)')),
                ('width', models.PositiveIntegerField(blank=True, null=True, verbose_name='Largeur')),
                ('height', models.PositiveIntegerField(blank=True, null=True, verbose_name='Hauteur')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='chat_thumbnails/', verbose_name='Miniature')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Téléchargé le')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='chat.message', verbose_name='Message')),
            ],
            options={
                'verbose_name': 'Pièce jointe',
                'verbose_name_plural': 'Pièces jointes',
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emoji', models.CharField(max_length=10, verbose_name='Emoji')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='chat.message', verbose_name='Message')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_reactions', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Réaction',
                'verbose_name_plural': 'Réactions',
            },
        ),
        migrations.CreateModel(
            name='MessageReadStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(auto_now_add=True, verbose_name='Lu le')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_statuses', to='chat.message', verbose_name='Message')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_read_messages', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Statut de lecture',
                'verbose_name_plural': 'Statuts de lecture',
            },
        ),
        migrations.CreateModel(
            name='UserChatSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notifications_enabled', models.BooleanField(default=True, verbose_name='Notifications activées')),
                ('email_notifications', models.BooleanField(default=False, help_text='Recevoir un email pour les messages non lus', verbose_name='Notifications par email')),
                ('push_notifications', models.BooleanField(default=True, verbose_name='Notifications push')),
                ('sound_enabled', models.BooleanField(default=True, verbose_name='Sons activés')),
                ('theme', models.CharField(choices=[('light', 'Clair'), ('dark', 'Sombre'), ('auto', 'Automatique')], default='auto', max_length=10, verbose_name='Thème')),
                ('show_read_receipts', models.BooleanField(default=True, verbose_name='Afficher les confirmations de lecture')),
                ('show_typing_indicator', models.BooleanField(default=True, verbose_name="Afficher 'est en train d'écrire'")),
                ('show_online_status', models.BooleanField(default=True, verbose_name='Afficher mon statut en ligne')),
                ('last_seen', models.DateTimeField(blank=True, null=True, verbose_name='Dernière connexion')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chat_settings', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Paramètres de chat',
                'verbose_name_plural': 'Paramètres de chat',
            },
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['type'], name='chat_conver_type_857bd7_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['club'], name='chat_conver_club_id_338101_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['competition'], name='chat_conver_competi_1b1e74_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['-last_message_at'], name='chat_conver_last_me_31163c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='conversationparticipant',
            unique_together={('conversation', 'user')},
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'created_at'], name='chat_messag_convers_3154fc_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sender'], name='chat_messag_sender__c4389c_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['is_deleted'], name='chat_messag_is_dele_543a03_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='messagereaction',
            unique_together={('message', 'user', 'emoji')},
        ),
        migrations.AddIndex(
            model_name='messagereadstatus',
            index=models.Index(fields=['message', 'user'], name='chat_messag_message_0f08b4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='messagereadstatus',
            unique_together={('message', 'user')},
        ),
    ]
